### ISSUE TITLE
[UI Builder] Visual editor do not notify about changes when properties panel editor is being closed

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#100]
In following scenario Visual Editor do not notify Moonshine about changes:
1) Open existing visual editor project where you have added some components
2) Select component and change height/width
3) Click outside properties panel editor

Moonshine didn't get notification about changes. Note that component itself gets new width/height.

![no_changes_from_ve](https://user-images.githubusercontent.com/24554795/33713521-d2281396-db4b-11e7-9f32-a5e2c6ca989c.gif)

**Comment by JoelProminic** [comment]
In my testing, this works fine for both the combobox height and the container position
