### ISSUE TITLE
[UI Builder] Additional Visual Editor File Opens in Text Editor

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#101]
I noticed this behavior during my testing today:
1. Create a new VisualEditor project
2. Right-click on src and add a new Visual Editor Flex File
3. This opens in the visual editor
4. Export the project
5. Create another Visual Editor Flex File
6. BUG:  this file opens with the text editor

@rat-moonshine found that this only triggers for Mac OS.

**Comment by piotrzarzycki21** [comment]
@JoelProminic , @rat-moonshine I cannot reproduce that problem on my Mac. Did we introduce some changes around context menu or something which could fix that issue ?

**Comment by piotrzarzycki21** [comment]
Another thing which come up to my mind is that I should try installed version. Can someone provide me link from bamboo for Mac ?

**Comment by piotrzarzycki21** [comment]
I have found scenario to reproduce the issue. Will work on a fix.

**Comment by piotrzarzycki21** [comment]
The scenario for tests. Once you go through the point 4 of scenario from description, do not change selection of the project in the tree. Right click on the second project and create file using context menu. - Without my fix you will end up with text file instead Visua Editor one.

**Comment by JoelProminic** [comment]
@piotrzarzycki21:  I see this bug was even more specific than I thought :).    I was not able to reproduce it after your update.
