### ISSUE TITLE
Resources has not been copied to the build folder

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#103]
During build of Moonshine sources added resources folder has not being copied to the bin-debug folder.

Scenario:
- Setup Moonshine sources in the IDE
- Build using "Build & Debug"

**Comment by piotrzarzycki21** [comment]
@rat-moonshine if you could take a look into that in the first place. It is probably problem only on my Machine as we discussed earlier.

**Comment by rat-moonshine** [comment]
Although straight test didn't produced me this problem in Windows, but as I've mentioned that there is a distant chance in certain cases when the files not getting copied, during compilation. I shall look into this. Thanks for reporting @piotrzarzycki21 .

**Comment by rat-moonshine** [comment]
Measure taken against distance chance. In my tests, all looks good. @piotrzarzycki21 give a test, let me know if you're still having the issue.

**Comment by piotrzarzycki21** [comment]
I have pulled your changes, build development version and test it. Still have that issue. Maybe I will try to debug on my own since you cannot reproduce it.

**Comment by rat-moonshine** [comment]
You tested while 'Build & Run' or debug?

**Comment by piotrzarzycki21** [comment]
I used Build & Debug

**Comment by rat-moonshine** [comment]
Can you try once 'Build & Run' - if that works for you, then we can close the problem zone to debugging scenario.

**Comment by rat-moonshine** [comment]
I think I able to produce the problem while 'Build & Debug'. I also see a new problem with stopping and restarting debug session -  I shall report that separately. I'm looking into 'Build & Debug' codes again.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just tested and Build & Run is working properly.

**Comment by rat-moonshine** [comment]
There were some reference exists from old debugger API, in MXMLCPlugin; which created a wrong impression of process (during debugging). This reference has been removed, and file copying process during debugging is also working now. Please, give a test @piotrzarzycki21 .

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I can confirm that your fix is working.

**Comment by JoelProminic** [comment]
This works for me.  I tested with:
- a "resources" directory in the project base directory
- a directory with deeper nesting
- a project that was outside of the project directory
