### ISSUE TITLE
s:View tag not recognized in Flex Mobile Project

### ISSUE THREAD

**Issue by Nisaba** [prominic/Moonshine-IDE#107]
I've created a new empty Flex Mobile Project with Moonshine 1.7.0.
But the main <s:View> tag in the source code editor is not recognized.

**Comment by piotrzarzycki21** [comment]
I can reproduce the problem. @rat-moonshine could you take a look into that? I'm in the middle of other task.

**Comment by rat-moonshine** [comment]
I confirm the issue but I don't have any immediate thought on this:
![image](https://user-images.githubusercontent.com/24370870/34027259-9aa981fc-e181-11e7-956f-191737ad42a1.png)
![image](https://user-images.githubusercontent.com/24370870/34027269-a758b742-e181-11e7-8600-a98d7492d5d6.png)

I also couldn't able to create new MXML component inside the class files. @joshtynjala can you please take a look into this (?)

**Comment by piotrzarzycki21** [comment]
@Nisaba ,

I just fixed issue and it will be available in the next version 1.8.0. As a workaround you can do following thing:
1) Open your mobile project and right click on it - choose: "Settings"
2) In tab "Build options" -> "Additional compiler options" add: +configname=airmobile
3) Restart Moonshine.

@rat-moonshine I was thinking about this issue and suddenly come up to my mind @joshtynjala post on Patreon: [ActionScript & MXML v0.8.0 for Visual Studio Code](https://www.patreon.com/posts/actionscript-v0-15590704), where he provide lot's of useful link for documentation of his extension. Thanks to that I was able to figure out what actually was happen.
If airmobile should be added in some other scenario than creating new project let me know.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine does Feathers mobile project need this ? Can you create project and check whether Code Completion is working, than add +configname=airmobile and see if it helps. I don't have Feathers SDK now and cannot download it due to internet connection problem.

**Comment by rat-moonshine** [comment]
Ah.. so the additional argument does affect the code-completion engine! Moonshine adds this argument at the time of compilation, though - but anyway it won't get added if the value is already present in the project's settings. 

I see @piotrzarzycki21 already added the argument to Flex mobile application template, I'm not sure about Feathers, I guess s:View, s:ViewNavigatorApplication etc. are part of the Spark framework not Feathers. I tested without the +configname=airmobile in project's Settings, I didn't noticed any problem Code Completion, though.

**Comment by Nisaba** [comment]
The workaround works well, thanks...

**Comment by joshtynjala** [comment]
Feathers doesn't have any components that are only available on mobile. However, all mobile projects should specify +configname=airmobile so that they have access to Adobe AIR classes that aren't available in Flash Player.

AIR desktop application should use +configname=air instead.

**Comment by JoelProminic** [comment]
I reviewed this for the 1.8.0 release.  
* I confirmed that new Mobile projects have the "+configname=airmobile" value by default in "Additional compiler options"
* I confirmed that code completion and other related features work properly for a new project without further modification.
