### ISSUE TITLE
Update contents to App Store

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#111]
1. Screenshot
2. 'Moonshine Desktop Feature Additions' section
3. Main description update with Feathers SDK reference (and Royale, too?)

**Comment by rat-moonshine** [comment]
- New screenshots added
- Feathers SDK reference added to the description
- 'Moonshine Desktop Feature Additions' - I'm not clearly remember what to-dos we had for this, can you remember @piotrzarzycki21 ?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I think the last item should be simply refreshes with new additions or totally removed. To me it will be repeating for every release with section "Added".

Recommend just remove from the App Store. 

If I go to Moonshine item on app store first thing which I see is section release, description is secondary and "Moonshine Desktop Feature Additions" as at the end. I had to click "read more.." to have it.

**Comment by rat-moonshine** [comment]
Removed. Closing the issue, shall ask @JoelProminic for a last minute check.
