### ISSUE TITLE
Ant build with ANE ?

### ISSUE THREAD

**Issue by Nisaba** [prominic/Moonshine-IDE#112]
I want to compile a project with ANEs.
I've set the Native Extension Folder option, so the Build Project works well.

But with the Build Apache@ Ant File command, the compiler doesn't find the ANEs.
Maybe my build.xml file is wrong ?

Here is error message:
:     [mxmlc] C:\GeoD\src\appli\myAppli.as(62): col: 5 Erreur: Accès à la propriété non définie NativeMaps.
: 
:     [mxmlc] 
:     [mxmlc] 				NativeMaps.init(DISTRIQT_DEV_KEY);
:     [mxmlc] 				^
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\appli\myAppli.as(69): col: 5 Erreur: Accès à la propriété non définie Dialog.
:     [mxmlc] 
:     [mxmlc] 				Dialog.init(myAppli.DISTRIQT_DEV_KEY);
:     [mxmlc] 				^
:     [mxmlc] 
: 
:     [mxmlc] C:\GeoD\src\appli\myAppli.as(72): col: 4 Erreur: Accès à la propriété non définie Dialog.
:     [mxmlc] 
:     [mxmlc] 			Dialog.service.showAlertDialog(pId, pTitle, pMess, pBouton);
:     [mxmlc] 			^
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\appli\myAppli.as(3): col: 38 Erreur: La définition com.distriqt.extension.dialog:Dialog est introuvable.
:     [mxmlc] 
:     [mxmlc] 	import com.distriqt.extension.dialog.Dialog;
:     [mxmlc] 	                                    ^
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\appli\myAppli.as(4): col: 42 Erreur: La définition com.distriqt.extension.nativemaps:NativeMaps est introuvable.
:     [mxmlc] 
:     [mxmlc] 	import com.distriqt.extension.nativemaps.NativeMaps;
:     [mxmlc] 	                                        ^
:     [mxmlc] 
: 
: BUILD FAILED
: C:\GeoD\build\build.xml:125: mxmlc task failed.

**Comment by rat-moonshine** [comment]
At present, the default Ant build file (supplied with a project template) gives a basic build structure setup, exclusive of any custom "Project/Settings/Path" addition/modification that may done by the user. User may need to modify the Ant build file based on their changes to make this work. Moonshine do not updates the Ant build file supplied upon project properties changes. 

You can edit the Ant build file, and make this small changes (considering its a mobile AIR project) :

```
<!-- COMPILE SWF TO BUILD-DEBUG DIRECTORY -->
<target name="compileSWF" depends="modifyDescriptor">
		<mxmlc file="${SOURCE_APP_FILE}" output="${SWF_FILE_PATH}" swf-version="25" configname="airmobile" locale="en_US" fork="true" optimize="true" debug="false" actionscript-file-encoding="UTF-8" incremental="false" keep-generated-actionscript="false" maxmemory="1024m">
			<load-config filename="${FLEX_HOME}/frameworks/airmobile-config.xml"/>
			<source-path path-element="${SOURCE_DIR}"/>
			<compiler.library-path dir="${DEBUG_DIR}" append="true">
				<include name="**/*.swc" />
			</compiler.library-path>
			<compiler.external-library-path dir="../extensions" append="true"> <!-- considering 'extensions' is the folder where you .ane files exists -->
			   <include name="*.ane" />
			</compiler.external-library-path>
		</mxmlc>
	</target>

<!-- Compile APK -->
	<target name="compileAPKProject" depends="compileSWF">
		<java jar="${ADT_PATH}" fork="true" failonerror="true">
			<arg line="-package" />
			<arg line="-target apk-captive-runtime"/>
			<arg line="-storetype pkcs12" />
			<arg line="-keystore '${DESKTOP_SELFSIGNED_CERTIFICATE}' " />
			<arg line="-storepass '${DESKTOP_SELFSIGNED_CERTIFICATE_PASS}'" />
			<arg line="${DESKTOP_PACKAGE_PATH}" />
			<arg line="${DESKTOP_DESCRIPTOR}" />
			<arg line="${SWF_FILE_PATH}" />
			<!-- Add folders to be bundled in the AIR file here -->
			<arg value="-extdir"/>
			<arg value="../extensions"/>
		</java>
	</target>
```

Let me know if this helps you. 

Thanks!

**Comment by Nisaba** [comment]
Yes, it's OK, thanks !

But now, I've a problem with the mxmlc compiler : it doesn't compile because there are warnings in my project; but this project compiled well in Flash Builder...
I guess there are options to disable warnings ?

**Comment by rat-moonshine** [comment]
You can go to the following section:
`Project/Settings/Warnings & Errors`

And uncheck the option "Show ActionScript warnings" to move the build with warnings.

**Comment by Nisaba** [comment]
All these options have been disabled but with no effect.

Here is one of errors:

     [mxmlc] C:\GeoD\src\views\AccueilView.mxml(30): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] <s:VGroup id="vg1" paddingLeft="10" paddingTop="15" width="{screen.width}" height="95%">

**Comment by piotrzarzycki21** [comment]
@Nisaba could you post full stack trace from console or at least the last couple of lines. Warnings shouldn't fail the build. 
Is that warnings are about binding ? I don't know French.

**Comment by Nisaba** [comment]
Yes, it's about binding.

Here is the full stack:

: Moonshine IDE 1.7.1
: Source is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache 2), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 28.0.0.127
: déc. 18, 2017 10:41:04 AM org.xsocket.connection.Server$LifeCycleHandler onConnected
: INFOS: server listening on 0:0:0:0:0:0:0:0:59582 (xSocket 2.8.15)
: Ant build Running
: Buildfile: C:\GeoD\build\build.xml
:      [echo] SDK : D:\cbern\Documents\Flex-Sdk-4.15
: 
: init:
:    [delete] Deleting directory C:\GeoD\build\DEPLOY
: 
:    [delete] Deleting directory C:\GeoD\build\build-debug
: 
:     [mkdir] Created dir: C:\GeoD\build\DEPLOY
: 
:     [mkdir] Created dir: C:\GeoD\build\build-debug
: 
: 
: modifyDescriptor:
:      [copy] Copying 1 file to C:\GeoD\build\build-debug
:      [copy] Copying 1 file to C:\GeoD\build\build-debug
:      [copy] Copying 1 file to C:\GeoD\build\build-debug
: 
: compileSWF:
:     [mxmlc] Chargement du fichier de configuration D:\cbern\Documents\Flex-Sdk-4.15\frameworks\airmobile-config.xml
: 
:     [mxmlc] C:\GeoD\src\views\AccueilView.mxml(30): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] <s:VGroup id="vg1" paddingLeft="10" paddingTop="15" width="{screen.width}" height="95%">
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewSiteView.mxml(97): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
: 
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtNom" width="{screen.width - lbl1.width - 25}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewSiteView.mxml(102): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtCommentaires" width="{screen.width - lbl2.width - 25}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewSiteView.mxml(116): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtNomProprio" softKeyboardType="contact"  width="{screen.width - lbl3.width - 25}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewSiteView.mxml(120): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtTelProprio" softKeyboardType="contact" width="{screen.width - lbl4.width - 25}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewSiteView.mxml(124): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
: 
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtEmailProprio" softKeyboardType="email" width="{screen.width - lbl5.width - 25}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewSiteView.mxml(128): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtAdresseProprio" width="{screen.width - lbl6.width - 25}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewSiteView.mxml(132): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtCommentairesProprio" width="{screen.width - lbl7.width - 25}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(36): Avertissement: La liaison de données ne pourra pas détecter les attributions à Nom.
: 
:     [mxmlc] 
: 
:     [mxmlc] 	<s:Label styleName="H1" text="{vData.CurrentSite.Nom}" paddingLeft="10" paddingTop="15"/>
: 
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(58): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput width="{screen.width - lbl2.width - 25}" text="@{vData.CurrentSite.Commentaires}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(58): Avertissement: La liaison de données ne pourra pas détecter les attributions à Commentaires.
: 
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput width="{screen.width - lbl2.width - 25}" text="@{vData.CurrentSite.Commentaires}"/>
: 
:     [mxmlc] 
: 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(62): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
: 
:     [mxmlc] 
:     [mxmlc] 		<s:HGroup width="{screen.width}" height="{screen.height * 0.25}" verticalAlign="middle" gap="15">
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(62): Avertissement: La liaison de données ne pourra pas détecter les attributions à height.
:     [mxmlc] 
:     [mxmlc] 		<s:HGroup width="{screen.width}" height="{screen.height * 0.25}" verticalAlign="middle" gap="15">
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(86): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput softKeyboardType="contact"  width="{screen.width - lbl3.width - 25}" text="@{vData.CurrentSite.NomProprio}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(90): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtTelProprio" softKeyboardType="contact" width="{screen.width - lbl4.width - 25}" text="@{vData.CurrentSite.TelProprio}"/>
: 
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(94): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtEmailProprio" softKeyboardType="email" width="{screen.width - lbl5.width - 25}" text="@{vData.CurrentSite.EmailProprio}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(98): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput width="{screen.width - lbl6.width - 25}" text="@{vData.CurrentSite.AdresseProprio}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(102): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput width="{screen.width - lbl7.width - 25}" text="@{vData.CurrentSite.CommentairesProprio}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(107): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 		<s:HGroup  width="{screen.width}" height="{screen.height * 0.25}" gap="15" >
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(107): Avertissement: La liaison de données ne pourra pas détecter les attributions à height.
:     [mxmlc] 
:     [mxmlc] 		<s:HGroup  width="{screen.width}" height="{screen.height * 0.25}" gap="15" >
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\SiteView.mxml(116): Avertissement: La liaison de données ne pourra pas détecter les attributions à Commentaires.
:     [mxmlc] 
:     [mxmlc] 				<s:Label text="{vData.CurrentSite.CurrentProspection.Commentaires}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\mapsViews\MapNewSiteView.mxml(91): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
: 
:     [mxmlc] 
:     [mxmlc] <s:VGroup paddingLeft="10" paddingTop="15" width="{screen.width}" height="{screen.height}">
:     [mxmlc] 
: 
:     [mxmlc] C:\GeoD\src\mapsViews\MapNewSiteView.mxml(91): Avertissement: La liaison de données ne pourra pas détecter les attributions à height.
:     [mxmlc] 
:     [mxmlc] <s:VGroup paddingLeft="10" paddingTop="15" width="{screen.width}" height="{screen.height}">
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewProspectionView.mxml(205): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 	<s:HGroup width="{screen.width}" horizontalAlign="center">
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewProspectionView.mxml(221): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtCommentaire" width="{screen.width - lbl2.width - 25}" text="@{newProspection.Commentaires}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewProspectionView.mxml(221): Avertissement: La liaison de données ne pourra pas détecter les attributions à Commentaires.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtCommentaire" width="{screen.width - lbl2.width - 25}" text="@{newProspection.Commentaires}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewProspectionView.mxml(242): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtTrvNom" width="{screen.width - lbl3.width - 25}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewProspectionView.mxml(247): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:SpinnerListContainer width="{screen.width - lbl4.width - 25}">
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewProspectionView.mxml(272): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 			<s:TextInput id="txtTrvCommentaire" width="{screen.width - lbl5.width - 25}" />
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewProspectionView.mxml(275): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 		<s:HGroup width="{screen.width}" height="{screen.height * 0.25}" verticalAlign="middle" gap="15">
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\NewProspectionView.mxml(275): Avertissement: La liaison de données ne pourra pas détecter les attributions à height.
:     [mxmlc] 
:     [mxmlc] 		<s:HGroup width="{screen.width}" height="{screen.height * 0.25}" verticalAlign="middle" gap="15">
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\ProspectionView.mxml(31): Avertissement: La liaison de données ne pourra pas détecter les attributions à DateCreation.
:     [mxmlc] 
:     [mxmlc] 	<s:Label styleName="H1" text="{'PROSPECTION DU ' + myAppli.date2stringH(vData.CurrentSite.CurrentProspection.DateCreation)}"></s:Label>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\ProspectionView.mxml(41): Avertissement: La liaison de données ne pourra pas détecter les attributions à width.
:     [mxmlc] 
:     [mxmlc] 					<s:TextInput id="txtCommentaire" width="{screen.width - lbl2.width - 25}" text="@{vData.CurrentSite.CurrentProspection.Commentaires}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\ProspectionView.mxml(41): Avertissement: La liaison de données ne pourra pas détecter les attributions à Commentaires.
:     [mxmlc] 
:     [mxmlc] 					<s:TextInput id="txtCommentaire" width="{screen.width - lbl2.width - 25}" text="@{vData.CurrentSite.CurrentProspection.Commentaires}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\ProspectionView.mxml(61): Avertissement: La liaison de données ne pourra pas détecter les attributions à Nom.
:     [mxmlc] 
:     [mxmlc] 				<s:Label text="{vTrv.Nom}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\ProspectionView.mxml(64): Avertissement: La liaison de données ne pourra pas détecter les attributions à IdMetal.
:     [mxmlc] 
:     [mxmlc] 					<s:Label text="{vTrv.IdMetal}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\ProspectionView.mxml(68): Avertissement: La liaison de données ne pourra pas détecter les attributions à TailleCm.
:     [mxmlc] 
:     [mxmlc] 					<s:Label text="{vTrv.TailleCm.toString() + ' cm'}"/>					
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\ProspectionView.mxml(72): Avertissement: La liaison de données ne pourra pas détecter les attributions à ProfondeurCm.
:     [mxmlc] 
:     [mxmlc] 					<s:Label text="{vTrv.ProfondeurCm.toString() + ' cm'}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\ProspectionView.mxml(74): Avertissement: La liaison de données ne pourra pas détecter les attributions à Commentaires.
:     [mxmlc] 
:     [mxmlc] 				<s:Label text="{vTrv.Commentaires}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\TrouvailleView.mxml(21): Avertissement: La liaison de données ne pourra pas détecter les attributions à Nom.
:     [mxmlc] 
:     [mxmlc] 	<s:Label styleName="H1" text="{vData.CurrentSite.CurrentProspection.CurrentTrouvaille.Nom}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\TrouvailleView.mxml(29): Avertissement: La liaison de données ne pourra pas détecter les attributions à IdMetal.
:     [mxmlc] 
:     [mxmlc] 					<s:Label text="{vData.CurrentSite.CurrentProspection.CurrentTrouvaille.IdMetal}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\TrouvailleView.mxml(33): Avertissement: La liaison de données ne pourra pas détecter les attributions à TailleCm.
:     [mxmlc] 
:     [mxmlc] 					<s:Label text="{vData.CurrentSite.CurrentProspection.CurrentTrouvaille.TailleCm.toString() + ' cm'}"/>					
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\TrouvailleView.mxml(37): Avertissement: La liaison de données ne pourra pas détecter les attributions à ProfondeurCm.
:     [mxmlc] 
:     [mxmlc] 					<s:Label text="{vData.CurrentSite.CurrentProspection.CurrentTrouvaille.ProfondeurCm.toString() + ' cm'}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\src\views\TrouvailleView.mxml(41): Avertissement: La liaison de données ne pourra pas détecter les attributions à Commentaires.
:     [mxmlc] 
:     [mxmlc] 					<s:Label text="{vData.CurrentSite.CurrentProspection.CurrentTrouvaille.Commentaires}"/>
:     [mxmlc] 
:     [mxmlc] C:\GeoD\build\build-debug\GeoDetect.swf (1678822 octets)
: 
: compileAPKProject:
:      [java] C:\GeoD\build\build-debug\Main-app.xml: error 102: Invalid namespace http://ns.adobe.com/air/application/23.0
: 
: BUILD FAILED
: C:\GeoD\build\build.xml:139: Java returned: 12
: 
: Total time: 21 seconds
: 
: BUILD FAILED
: C:\GeoD\build\build.xml:139: Java returned: 12
: 
: Total time: 21 seconds
: FSCH exit code: 12
: Files produced under DEPLOY folder.

**Comment by piotrzarzycki21** [comment]
@Nisaba it look like you have invalid namespace in your Main-app.xml descriptor. What version of SDK are you using ? Does it have Adobe Air 23 ?

**Comment by rat-moonshine** [comment]
In general Moonshine auto-fix the namespace version while 'Build & Run' command - to the application descriptor file copied into the bin-debug folder. Moonshine do not modify the original descriptor file in source folder without user's concern, though.

So, if an original descriptor file suppose to have:
```
<?xml version="1.0" encoding="UTF-8"?>
<application xmlns="http://ns.adobe.com/air/application/10.0">
```
while 'Build & Run' Moonshine updates the namespace version to 22/23 etc. (based on the default SDK version) to bin-debug folder.

With my quick project tests, I found this logic works. If this do not works in certain scenario with @Nisaba , then we shall again need to look into this (after having more information from @Nisaba on this).

**Comment by Nisaba** [comment]
you're right !!
There was a mistake on the namespace version.
Sorry for the unconvenience.

But now, I've a  problem in this problem:
: compileAPKProject:
:      [java] C:\GeoD\build\build-debug\Main-app.xml(49): error 105: application.initialWindow.content contains an invalid value
:      [java] C:\GeoD\build\build-debug\Main-app.xml(49): error 105: application.initialWindow.content contains an invalid value

Here is the InitialWindow Content:
	<initialWindow>
		
		
		<content>[Cette valeur sera remplacée par Flash Builder dans le fichier app.xml de sortie]</content>

Since the project has been imported from Flash Builder, note the sentence in french in the content tag.
I've replace it with the english sentence and it works.

So a new problem with non english environment ?

**Comment by rat-moonshine** [comment]
It's the same language related problem that @Nisaba reported in #110 . We shall need to look into this, too.

**Comment by piotrzarzycki21** [comment]
Let's close this one if there is not work here. Problem related to language we should resolve in #110

**Comment by rat-moonshine** [comment]
I think if we want to update the namespace version in case of Ant build process, too, then we may need to keep open this version.

**Comment by Nisaba** [comment]
the app.xml file comes from a Flash Builder project with Air23 since my Moonshine IDE environment was set with Air22.
It was a mistake from me so I think you can close this topic.

**Comment by rat-moonshine** [comment]
All static value check in English against InitialContent/Content in Ant build file templates now replaced with Regexp.

**Comment by rat-moonshine** [comment]
Closing this topic for now, until we want to revisit this again.
