### ISSUE TITLE
APK doesn't install

### ISSUE THREAD

**Issue by Nisaba** [prominic/Moonshine-IDE#113]
The command Build Ant command produces an APK file.
But this APK doesn't install in my Android device.

**Comment by Nisaba** [comment]
Note : it concerns also the Hello world project from Moonshine (NewFlexMobileProject)

**Comment by rat-moonshine** [comment]
I shall take a look and let you @Nisaba . Thank you for reporting!

**Comment by rat-moonshine** [comment]
I tried to give this a test today on my Android 7.0 with Moonshine 1.7.1.

I hope you someway able to overcome this problem you mentioned in #112 and able to create a valid APK @Nisaba  (by replacing to English word),

> But now, I've a problem in this problem:
> : compileAPKProject:
> : [java] C:\GeoD\build\build-debug\Main-app.xml(49): error 105: application.initialWindow.content contains an invalid value
> : [java] C:\GeoD\build\build-debug\Main-app.xml(49): error 105: application.initialWindow.content contains an invalid value
> 
> Here is the InitialWindow Content:
> [Cette valeur sera remplacée par Flash Builder dans le fichier app.xml de sortie]
> 
> Since the project has been imported from Flash Builder, note the sentence in french in the content tag.
> I've replace it with the english sentence and it works.

I tested with basic Flex iOS project template and used with auto-generated self-signed certificate. After copying to the device, the APK does installed properly and opened for me, too.

Did you had any error details with your test (when installing)? Did you use your any own certificate that could have problem?

**Comment by Nisaba** [comment]
I've re-installed the Air runtime in the mobile and it works now.
Strange, because there is the captive runtime already in the apk...

Anyway, it's OK now. Thanks.

**Comment by rat-moonshine** [comment]
Good to know that it worked for you @Nisaba . Please, report if you found any more related problem.
