### ISSUE TITLE
Console Prompt Background Color Makes Commands Unreadable

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#114]
While testing a Moonshine nightly build on Mac OS X 10.10.5, I noticed that the background color changed for the console prompt when I tried to enter a command:

![2017_12_18__console_prompt_color](https://user-images.githubusercontent.com/24532731/34119636-8516695e-e3e8-11e7-921a-c27c935f2560.jpg)

The command text is nearly unreadable.
1. Launch Moonshine
2. Click on the console prompt - the color changes
3. Type a command like "clear"

**Comment by rat-moonshine** [comment]
I also have seen the console prompt unnecessarily got focused when Escape key pressed against any opened popup dialog. This needs to be fix, too.

**Comment by rat-moonshine** [comment]
- Command editor now has its default background color
- Listener to Escape key press removed to focus the editor

**Comment by JoelProminic** [comment]
I reviewed this for 1.8.0.  I confirmed that:
* The background color is correct
* Esc does not put focus on the console when closing a prompt

However, I noticed that the console cursor keeps flashing as if it has focus even after I have moved focus to an editor.  I reported a new issue for this (#130)
