### ISSUE TITLE
Clean Project Clears Project Selection

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#115]
While testing a Moonshine Bamboo build on Mac OS X 10.10.5, I noticed that Project > Clean Project clears my project selection.  This is annoying, since I want to rebuild the project in this case.
1. Launch Moonshine
2. Open/Create Multiple projects
3. Select a project
4. Project > Clean Project
5. Project > Build & Run
6. Moonshine prompts user to select a project to build
![2017_12_18__project_clean_selection](https://user-images.githubusercontent.com/24532731/34119863-479ae6ee-e3e9-11e7-86e7-ea72d475f187.jpg)

**Comment by rat-moonshine** [comment]
The above scenario also happens in following case:
- Open multiple projects at a time
- Delete any of the project (maybe Close too?)
- Project selection disappears

**Comment by rat-moonshine** [comment]
I've made some changes to the selection policies in the TreeView class. So far,
- Last tree selection restores after a Clean Project
- Tree selection updates after removing a file/folder from the tree
- Tree selection updates after removing a project from the sidebar

@piotrzarzycki21 I noticed in my test when Moonshine opens with 3 projects, the 2nd project were always coming selected for me. Did you have any certain logic to select project index after auto-open, during startup? At this moment, after my above changes (where last opened project supposed to get selected), selection is not working when Moonshine starts with multiple projects. If you do not have any startup selection logic, then perhaps I need to re-look into this.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine definitely I'm not doing anything on startup. I did involve into the selection logic "Scroll to Source" option, but everything is happen after click. I think this is some new issue, probably cause by some of the latest changes. Don't have any clue to help you without looking into that.

**Comment by rat-moonshine** [comment]
Okay. Thanks for the info, I will look into this.

**Comment by rat-moonshine** [comment]
I noticed adding an object to the tree component do not needs any extra logic to get the item selected - thus, there were none. This works good when adding individual object (opening individual project) to the the tree. However, when auto-opening more than 2 projects during Moonshine startup in the sidebar, tree sometime loss its selection and sometime not. 

I did not able to pinpoint any probable reason for this yet, neither explicitly selecting item works during startup. We need to re-visit this later.

**Comment by rat-moonshine** [comment]
Opening selection is more persistent now. Closing this issue until new selection problem comes up.

**Comment by JoelProminic** [comment]
This seems to work properly.  

There is a noticeable "flicker" after the Project > Clean where the project is deselected and selected, but this is only a minor distraction when using the tool.  Similarly, there is a delay before a project is selected on startup
