### ISSUE TITLE
FlexJS Project Build Failure

### ISSUE THREAD

**Issue by kennylerma** [prominic/Moonshine-IDE#118]
I created a new default FlexJS project and attempted to build, but only get the path error below.  I have the FlexJS SDK and Java JDK 8 paths specified for the defaults and project settings.

: Compiling NewFlexJSBrowserProject
: Using Falcon codebase: D:\flexjssdk
: Using Flex SDK: D:\flexjssdk
: The system cannot find the path specified.
: The system cannot find the path specified.

**Comment by piotrzarzycki21** [comment]
Hi @kennylerma ,

Are you using FlexJS 0.8.0 ?

**Comment by piotrzarzycki21** [comment]
I got exactly the same with FlexJS 0.8.0. I will check what has happened. I recommend you to use for the time being Royale, which has bunch of things fixed. I can provide you link for download if you interested. It is still Nightly build available.

**Comment by kennylerma** [comment]
Yes, I'm using FlexJS 0.8.0 with 1.7.1.  I've also tried it with the nightly build of 0.9.0 recently.

**Comment by kennylerma** [comment]
Using the nightly build of FlexJS, I get other errors.

: Compiling NewFlexJSBrowserProject
: Using Falcon codebase: D:\flexjsnightly
: Using Flex SDK: D:\flexjsnightly
: '"C:\Windows\System32\java.exe"' is not recognized as an internal or external command,
: operable program or batch file.
: '"C:\Windows\System32\java.exe"' is not recognized as an internal or external command,
: operable program or batch file.

**Comment by piotrzarzycki21** [comment]
@kennylerma ,

I will look into that, but it is not on top of my priorities. I recommend you to use Apache Royale. Please download Nightly Build -> [here](http://apacheflexbuild.cloudapp.net:8080/job/royale-asjs/lastSuccessfulBuild/artifact/out/) (apache-royale-0.9.0-bin.zip). Once you unpack zip - Choose folder "royale-asjs" in Moonshine. Check the [instructions ](https://github.com/apache/royale-asjs/wiki/Moonshine-IDE) which I have written - especially [Known issues](https://github.com/apache/royale-asjs/wiki/Moonshine-IDE#notable-known-issues).

Let me know if you were able to create and build hello world to JS. Use: "Build as JavaScript" or "Build & Run as JavaScript".

Thanks for trying!
Piotr

**Comment by piotrzarzycki21** [comment]
@kennylerma as for your problems with FlexJS - I think you have something wrong with JAVA_HOME setup in your system. Could you take a look into the Environment Variables. 
I got the same errors as you initially cause I had some mess in my mxmlc.bat in FlexJS - I was doing some tests a while ago and my Java path there was hard coded. 

Before you go with Royale check as I suggest JAVA_HOME.

**Comment by kennylerma** [comment]
Thanks @piotrzarzycki21 .  I didn't realize Apache Royale was a build that isn't available as a dev build from the Apache Flex SDK Installer.  After adding the playerglobal.swc to the SDK, I was able to make a build.

I checked my JAVA_HOME path and it's set to the Java JDK 1.8.0_151.  So, it doesn't appear to be an issue.  Thanks for your help.  I just wanted to test the latest.  Next year, my team will begin converting all our ActionScript work to FlexJS, so I'm examining all possible workflows and IDE's including Moonshine.

Keep up the great work and I look forward to the first releases for Apache Royale.

**Comment by piotrzarzycki21** [comment]
@kennylerma I recommend you to use nightly build of Royale cause it contains newest fixes and we are pretty close to start release process under the new name - it will be Royale 0.9.0 version.

Apart of that - Royale will not be shipped through the installer. You will be downloading packages through npm or as I provide as an file. Those package will be capable of build your applications to JS. User who would like to build his application both to JS and SWF will have to on his own download all the dependencies (Adobe Air, Flash Player (playerglobal.swc) etc.). Assuming that you no longer interested into SWF you will just download package and use it in Moonshine.

Great to hear that your Team is interested in to use Royale for port your existing AS applications!! Looking forward from you more till then. :)

Piotr
