### ISSUE TITLE
"Rate Our App" Reminder

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#12]
Original request:
> Please add some kind of  reminder for people to rate and promote Moonshine so we can spread the word.
> 
> Include a button to post to Twitter and Facebook about it, and rate the app.   These can just launch an embedded pre-populated text like "I just started using Moonshine IDE -- a modern FlexJS and ActionScript IDE which brings the best of cross platform pure browser (JavaScript), mobile (iOS/Android) and desktop (Mac and Windows) together.  Check it out at moonshine-ide.com" or something like that.
> 
> We need to start tracking, if possible, the number of unique users / downloads we have, and ideally know how often they are using it and make it easy for them to provide feedback / bug reports on GitHub from within Moonshine for anything they have trouble with.

Clarification:
> We should not ask the user at exit - when people are ready to leave an app it is time for them to do something else mentally and I think we will have low acceptance.
> 
> Instead, we need an area of the homepage which does not take up much screen real estate, but is visible and encourages feedback.
> 
> It could look like:
> 
> Are you accomplishing what you want in Moonshine?
> Thumbs Up  (count of users who have up-voted so far -- then it presents a link to the App Store for Mac and suggests social sharing)
> Thumbs Down (count of users who have down-voted so far -- then asks what they would improve)
> 
> Feature request (on GitHub)
> Report a bug (on GitHub)
> Join a discussion (on GitHub)
> Get live help now (in development - some kind of IRC channel for Moonshine) - count of users on-line.
> 
> Something like that.
> 
> Please make some Photoshop mockups of this before you code it so we can further brainstorm.

**Comment by rat-moonshine** [comment]
Some thoughts from Joel on this from last discussion:

> ![image](https://user-images.githubusercontent.com/24370870/31816445-f61fed78-b5ad-11e7-908d-cb7cd58b603f.png)
> ![image](https://user-images.githubusercontent.com/24370870/31816460-083656d2-b5ae-11e7-89d1-0f3a1ca0bb62.png)
> ![image](https://user-images.githubusercontent.com/24370870/31816482-24a907ba-b5ae-11e7-9a88-004636cbfcf3.png)

**Comment by piotrzarzycki21** [comment]
Does "This is great" would also suggest some generic message ? If yes - one suggestion is to have at least one of those hash tags: #moonshineide #actionscript

**Comment by rat-moonshine** [comment]
Regarding Facebook, Twitter involvement - I'm not yet sure how we want to do this - shall we open the Moonshine pages to browser or, we shall encourage to post a generic pre-populated message. For latter, I think we shall need the user to login to the social sites before posting them, though. Which probably shall involve ANE usage (?)

**Comment by JoelProminic** [comment]
@piotrzarzycki21, the "mockup" I made was simply for showing a compact interface that could be included on the Home page.  The "This is great!" button would open an interface showing options for positive feedback (direct messages, Facebook, Twitter, etc), while the "I'm having some problems" button would open an interface for reporting bugs or making feature requests (Do we also want to allow sending a plain message?).  We can change these pages without needing to update the UI on the Home page, so we can design them separately.  

I'm not sure if we want to give a generic message template, but including hashtags would be a good idea.

@rat-moonshine:  For the Facebook and Twitter buttons, it looks like the APIs are designed to be used with Javascript:
https://dev.twitter.com/web/tweet-button
https://developers.facebook.com/docs/plugins/like-button

I don't think we want to try to implement this ourselves in AIR or a native extension.

If we have the Like/Dislike buttons open pages on moonshine-ide.com, though, we should be able to use these buttons normally.  This would also allow us to change the interface without deploying a new version of Moonshine.

**Comment by rat-moonshine** [comment]
Have added two new popup against the rating buttons (in Home screen).

Negative popup contains one bug report input and a button to request feature at GitHub. We shall need an agent for the bug input control, now.

For positive popup, I may need some idea on what contents we should have and how we want to portray them (maybe a mockup design would help).

**Comment by rat-moonshine** [comment]
As we probably want to post to the social sites by help of a web page (and not directly from Moonshine), initial content added to the positive rating popup - includes an input field to type message, and two buttons for Facebook and Twitter posting. We shall need an web page now where Moonshine can send the request/message and therefore rest of the procedures done by the page itself.

This is the default message added to the input field at this moment, its free to change:
> I have a nice experience using Moonshine IDE! #moonshineide #actionscript

**Comment by piotrzarzycki21** [comment]
@rat-moonshine as I understand that logic should be placed on our website http://moonshine-ide.com/ ? 
Do you need some help with that ?

**Comment by rat-moonshine** [comment]
If I understood correctly, the logic page should hold API integration to post to the social sites. Someone who is familiar with integrating social APIs to web pages, should be helpful, here.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine ,

I just tried to implement logic for "Share on Twitter" in the following way:
`var shareOnTwitterRequest:URLRequest = new URLRequest("https://twitter.com/intent/tweet");
var urlVariables:URLVariables = new URLVariables();
urlVariables.text = "text=" + txtMessage.text;

shareOnTwitterRequest.data = urlVariables;
navigateToURL(shareOnTwitterRequest, "_blank");`

Result is nice:
![image](https://user-images.githubusercontent.com/24554795/32217100-405acad0-be27-11e7-9497-eda0e01ed6b3.png)

Question is how it behave on Mac, if it will be the same result I will commit my changes.

**Comment by rat-moonshine** [comment]
One question - above behavior works when you already have logged in to Twitter. Does it also works when you are not logged-in, AND does the URL remains the same way when you logged-in manually after opening Twitter page?

**Comment by piotrzarzycki21** [comment]
I'm getting following page when I'm not logged in:

![image](https://user-images.githubusercontent.com/24554795/32217348-0109de92-be28-11e7-9cad-f948eec7050d.png)

**Comment by rat-moonshine** [comment]
This is great! Then only we've remain FB.

**Comment by piotrzarzycki21** [comment]
In case of FB @JoelProminic posted link to "Like" button and I think we need to have "Share" instead. I will look how to implement "Share" cause it could be similar to twitter. :)

**Comment by piotrzarzycki21** [comment]
With FB things are a bit more complicated. My code looks like that:

```
var shareOnFacebookRequest:URLRequest = new URLRequest("http://www.facebook.com/dialog/share");
var urlVariables:URLVariables = new URLVariables();
urlVariables.app_id = "249823608417885";
urlVariables.href = "http://moonshine-ide.com/";
urlVariables.hashtag = getFirstHashTag();
urlVariables.quote = getTextWithoutHashTags();
urlVariables.redirect_uri = "http://moonshine-ide.com/";
			
shareOnFacebookRequest.data = urlVariables;
navigateToURL(shareOnFacebookRequest, "_blank");
```

First thing is that we need to have some app created on FB - it could be some test app. The most important thing is that we need to get from that application "app_id".
In our app settings on FB we have to add "Facebook Login" product and specify url - Without specifying url we will not be able to share anything.

![image](https://user-images.githubusercontent.com/24554795/32221926-ad39b41c-be37-11e7-8a7d-31b02d8b7289.png)

This is how it look like share:

![image](https://user-images.githubusercontent.com/24554795/32221989-db5ff162-be37-11e7-92fe-59788c177e4b.png)

As you can see our message is not in the message box - it's in the bottom. I haven't found possibility to put message in that box. We can also specify only one hashtag.

This is how it look like with logged out user:
![image](https://user-images.githubusercontent.com/24554795/32222193-9df3ae44-be38-11e7-8795-451ff60409b7.png)

In that case we can see that name of our app is displayed: "TimelineTest". - We could have more friendly app name there.

Let me know guys what do you think about both solution. Twitter seems to be ok, but with FB is a bit harder.

**Comment by piotrzarzycki21** [comment]
I have figure out also logic for "I'm having some problems"

```
var issueGithubRequest:URLRequest = new URLRequest("https://github.com/prominic/Moonshine-IDE/issues/new");
var urlVariables:URLVariables = new URLVariables();
urlVariables.body = txtProblem.text;

issueGithubRequest.data = urlVariables;
navigateToURL(issueGithubRequest, '_blank');
```

I think following popup should not have "Request feature on Github" cause it will be doing exactly the same as Report, unless there were other plans for "Report" - Let me know in that case.
1) User is filling his description:
![image](https://user-images.githubusercontent.com/24554795/32315685-6c2edc8c-bfad-11e7-91f0-f3a0c15fe1f5.png)
2) Click on "Report" and we are navigating to new issue with filled description box:
![image](https://user-images.githubusercontent.com/24554795/32315718-92005058-bfad-11e7-8ff4-3eea044ffa2c.png)
3) User have to filled title on his own.

I didn't commit logic for all of that options. Twitter and Github looks pretty good but with Facebook is more complicated.

**Comment by rat-moonshine** [comment]
In general, requesting a feature may not be a problem to report. Perhaps we want to modify the label 'I want to report an issue' to something else that makes sense both for requesting feature and reporting an issue. Since the 'Report' button now effectively taken the user to Git issues section, I think we can limit the submit button to one, too, by changing the label something that fit for both issue reporting and feature requesting.

**Comment by piotrzarzycki21** [comment]
I just checked and if user is not logged in the link take to the login screen. Once user fill login/password it's landing into the issue tab with filled description field, so we are good here.

As for the button that's ok for me "I want to report an issue" or just "Report Issue" - It would be good if @JoelProminic could look into the label names. Once we decide commit the changes I will be ready with it.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just committed the changes. Review once you get a chance.

**Comment by JoelProminic** [comment]
Some updates for the "This is great!" interface:

Instead of:
"Perhaps you want to share some words on this?"
Use: 
"If you would like to help spread the word, you can share a message on Facebook or Twitter using the buttons below."

Default Message:   "I had a nice experience using Moonshine IDE! #moonshineide #actionscript"

I brought this to @JustinProminic's attention for review, since he originally requested the feature.
