### ISSUE TITLE
How should work options "Open previously opened..." ?

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#120]
This issue has been extracted from #106 and [comment](https://github.com/prominic/Moonshine-IDE/issues/106#issuecomment-353046809)

**Comment by JoelProminic** [comment]
I think both "Open previously opened files for project" and "Open previously opened project branches" are a bit unclear, but I haven't through of a better message that would be more concise ("Open previously opened project branches when project is reopened" seems a little cumbersome).

I think we want to have the "project branches" setting enabled by default.   I don't think we need to split the logic based on whether the project was open I don't follow @rat-moonshine's logic for why we might not want this when reopening the project.

**Comment by piotrzarzycki21** [comment]
I would like to close that one. Since I don't have either better names for that let's leave it as is. Do you suggest @JoelProminic in terms of selection:

**Open previously opened project on startup**: default `false`, currently it's `true`
**Open previously opened project on startup**: default `false`, currently it's `true`
**Open previously opened project branches**: default `true`, currently it's `true `no change here

Thoughts ?

**Comment by piotrzarzycki21** [comment]
I like current state with all default true for those three options.

**Comment by JustinProminic** [comment]
From my point of view, the above default preferences are what other IDEs also do. We can keep this preferences unless we notice any noticeable amount of system delay to open all the projects/files to the Moonshine.

**Comment by rat-moonshine** [comment]
From my point of view, the above default preferences are what other IDEs also do. We can keep this preferences unless we notice any noticeable amount of system delay to open all the projects/files to the Moonshine.

**Comment by piotrzarzycki21** [comment]
@JoelProminic if you will have more thoughts about that please reopen.

**Comment by JoelProminic** [comment]
Defaulting all of these options to true seems consistent with the behavior of IntelliJ, and this behavior makes sense to me.   Since we can quickly close the tabs and projects, I don't think these defaults will be a problem unless they cause a noticeable delay on startup.
