### ISSUE TITLE
Add option "Show in Explorer"

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#122]
In the context menu of project tree we should add option which allow to show file in Explorer.

**Comment by piotrzarzycki21** [comment]
Option has been added to the menu. I did small reorganization:

![image](https://user-images.githubusercontent.com/24554795/34416187-a235de54-ebf2-11e7-876a-39b563692739.png)

**Comment by JoelProminic** [comment]
"Show in Explorer" should be "Show in Finder" on macOS.  The action works properly, though.

A possible future improvement:  If I right-click on a file instead of a folder, the file should have focus in the opened window.  The Windows/macOS APIs may not support this, though...

**Comment by piotrzarzycki21** [comment]
Just fixed that. Thanks!

**Comment by JoelProminic** [comment]
I see the action is called "Show in Finder" now on Mac OS X.   However, the action no longer works for me.  @rat-moonshine reported that "Show in Explorer" still works fine, though.

I confirmed that the Show in Finder action is disabled for a Visual Editor project.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I'm sorry about that. I just fixed it. If it's not too late for @rat-moonshine Moonshine let's pickup this one to the 1.8.0 build.

**Comment by rat-moonshine** [comment]
Once Joel would give green signal, I shall do a new build and upload (to submit to the App Store). This fix shall go with 1.8.0 only @piotrzarzycki21 .
