### ISSUE TITLE
Clean project cause hang during deleting huge folder

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#126]
When I'm deleting folder which has 5MB it causes noticeable hang.

**Comment by piotrzarzycki21** [comment]
I need to add small adjustment. When we are cleaning swf build and there wasn't JS - "bin" folder we don't get notification that clean has been finished.

**Comment by JoelProminic** [comment]
I tested this with a new Apache Royale project.  I confirmed:
* The clean runs quickly for the Javascript build
* The clean reports completion after both an SWF and Javascript build
* The clean still runs quickly if I add some large files to the bin directory.

**Comment by piotrzarzycki21** [comment]
Actually I think we should plan some notification to the user during clean. 
When I'm cleaning quite big Royale example there are plenty of time to click on build during cleaning. I'm not sure what could gonna happen in such scenario. 
Not necessary an edge case if you have enough big project.
