### ISSUE TITLE
Add console colors

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#127]
I believe having more colors in console output give as a bit more readability.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I did first deep look into that and I have found something which doesn't make sense to me. I'm looking into class [MXMLCPlugin](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as), but similar things apply also to [MXMLCJavaScriptPlugin](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCJavaScriptPlugin.as).
This [line](https://github.com/prominic/Moonshine-IDE/blob/04d4b06f8c72c784b4a4994c28b9ae9bde7526ae/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L1042) applies to the **errors** data, later we are displaying everything what data has and stop Native Process. 

errors is displayed in [shellData](https://github.com/prominic/Moonshine-IDE/blob/04d4b06f8c72c784b4a4994c28b9ae9bde7526ae/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L922), but it won't happen because earlier we have finished connection with Native Process.

I'm thinking about displaying things as it is properly should be. If it's error - use `error` method from [ConsoleOutputter](https://github.com/prominic/Moonshine-IDE/blob/04d4b06f8c72c784b4a4994c28b9ae9bde7526ae/ide/MoonshineSharedCore/src/actionScripts/plugin/console/ConsoleOutputter.as#L45).

This distinguish may allow me to colorize output.

Does that make sense to you ?

**Comment by piotrzarzycki21** [comment]
Maybe I will just commit my changes and you review it, whether it has sense. I just tested it and it's working as it was before.

**Comment by piotrzarzycki21** [comment]
I have added colors for console output whenever is being used one of the method from [ConsoleOutputter](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/plugin/console/ConsoleOutputter.as) accordingly: 
[error](https://github.com/prominic/Moonshine-IDE/blob/e3da27a2f6e84e32a85c596fcc7e48b273fe9ced/ide/MoonshineSharedCore/src/actionScripts/plugin/console/ConsoleOutputter.as#L50): 0xca2323 (red)
[warning](https://github.com/prominic/Moonshine-IDE/blob/e3da27a2f6e84e32a85c596fcc7e48b273fe9ced/ide/MoonshineSharedCore/src/actionScripts/plugin/console/ConsoleOutputter.as#L55): 0xFFBF0F (yellow)
[success](https://github.com/prominic/Moonshine-IDE/blob/e3da27a2f6e84e32a85c596fcc7e48b273fe9ced/ide/MoonshineSharedCore/src/actionScripts/plugin/console/ConsoleOutputter.as#L39): 0x348f37 (green)

**Comment by piotrzarzycki21** [comment]
During work on that problem I have found one issue in Apache Royale compiler. Because of that issue errors in code won't be colorized in the console issue for JSRoyale compilation. apache/royale-compiler#21

**Comment by rat-moonshine** [comment]
Can we make the colors friendly based on the darker background? As an example, the current red color value is little difficult to read keeping its darker background:

![image](https://user-images.githubusercontent.com/24370870/35431861-3ac88a50-02a4-11e8-98eb-772e37652b8b.png)

**Comment by piotrzarzycki21** [comment]
Let me play with that a bit more :)

**Comment by piotrzarzycki21** [comment]
I have changed color, let me know if it's better. :)

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/35433084-28a7eb78-02a8-11e8-89ae-4d62679b0e14.png)

Error color is much readable now. Can we do something for success color, too?

**Comment by piotrzarzycki21** [comment]
What's wrong with success color? It's readable instantly - It's distinguish a lot from white. Suggest something else.

**Comment by rat-moonshine** [comment]
> Suggest something else.

You asking for a different color value, or some other issue (related to this) ?

Maybe it is readable, but in a look I felt maybe it can be little brighten too.

**Comment by rat-moonshine** [comment]
Thanks for the reference link, @piotrzarzycki21 . I shall play with the colors a little more at some time.

**Comment by atinprominic** [comment]
Looking Good to me.

**Comment by JoelProminic** [comment]
I didn't have a problem with the colors during my testing today:

I noticed a case that did not trigger highlighting for FlexJS (with an SWF build).  I removed the closing '>' for the <js:Application, and the resulting errors were not highlighted.

```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
				xmlns:js="library://ns.apache.org/flexjs/basic" 
				xmlns:local="*"
				pageTitle="HelloWorld"
			   
	<fx:Declarations>
```


```
: /Users/joelanderson/Library/Containers/com.moonshine-ide/Data/Documents/TestFlexJS_NullPointerException/src/TestFlexJS_NullPointerException.mxml(7): col: 2 Syntax error: '<fx:Declarations' is not allowed here
: 	<fx:Declarations>
: 	^
: /Users/joelanderson/Library/Containers/com.moonshine-ide/Data/Documents/TestFlexJS_NullPointerException/src/TestFlexJS_NullPointerException.mxml(7): col: 2 Syntax error: '<fx:Declarations' tag (or tag before this tag, or non-tag inside this tag) is unclosed or tag not allowed here.
: 	<fx:Declarations>
: 	^
: /Users/joelanderson/Library/Containers/com.moonshine-ide/Data/Documents/TestFlexJS_NullPointerException/src/TestFlexJS_NullPointerException.mxml(7): col: 2 Syntax error: '<fx:Declarations' tag (or tag before this tag, or non-tag inside this tag) is unclosed or tag not allowed here.
: 	<fx:Declarations>
: 	^
: /Users/joelanderson/Library/Containers/com.moonshine-ide/Data/Documents/TestFlexJS_NullPointerException/src/TestFlexJS_NullPointerException.mxml(7): col: 2 Syntax error: '<fx:Declarations' is not allowed here
: 	<fx:Declarations>
: 	^
```

The highlighting works properly for Royale or AIR, though, so this is not a high priority unless it indicates a different problem.
