### ISSUE TITLE
Compiling FlexJS application to SWF throws error

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#128]
Platform: macOS (tested)
SDK: Apache FlexJS 0.6.0 FP 21.0

- Create a new project with FlexJS template
- Try to run the project with "`Projects > Build & Run`"
- Project compiles, starts browser to run the compiled _.swf_
- .swf throws error (requires FP debugger):

> TypeError: Error #1034: Type Coercion failed: cannot convert org.apache.flex.mobile::View@2d33592fb0d1 to org.apache.flex.core.IApplicationView.
> 	at org.apache.flex.utils::MXMLDataInterpreter$/generateMXMLProperties()[/Users/aharui/git/flex/release/flex-asjs/frameworks/projects/Core/src/main/flex/org/apache/flex/utils/MXMLDataInterpreter.as:400]
> 	at org.apache.flex.core::Application/generateMXMLAttributes()[/Users/aharui/git/flex/release/flex-asjs/frameworks/projects/Core/src/main/flex/org/apache/flex/core/Application.as:331]
> 	at NewFlexJSBrowserProject()

**Comment by piotrzarzycki21** [comment]
I think I won't be able to do to much here. In FlexJS 0.6.0 js:View class exists only in mobile module. Hello world app should contains js:ViewBase

```
<js:initialView>
		<js:ViewBase width="100%" height="100%">
			<js:Container width="100%" height="100%" >
				<js:Label id="lbl" text="Hello World" width="200" />
			</js:Container>	
		</js:ViewBase>
	</js:initialView>
```

Moonshine itself is showing in Problems view that we have some problem:

`In initializer for 'js:initialView', type org.apache.flex.mobile.View is not assignable to target type 'org.apache.flex.core.IApplicationView'.`

In FlexJS 0.7.0 issue doesn't exists cause View is present in Core module. I have no idea why compiler in FlexJS doesn't notify user about above problem and I think there is no point invest time into that.

**Comment by rat-moonshine** [comment]
I do remember there were some structural changes between earlier and recent FlexJS version (adding js:View or changing to js:View or something). What I was concern actually, what we need to make requisite modification in Moonshine FlexJS template - that work between older and newer FlexJS? 

Current template codes having this - 
```
<js:initialView>
		<js:View width="100%" height="100%">
			<js:Container width="100%" height="100%" >
				<js:Label id="lbl" text="Hello World" width="200" />
			</js:Container>	
		</js:View>
	</js:initialView>
```

@piotrzarzycki21 do you think we have nothing can do against FlexJS 0.6.0 compilation (with this above code) and keep this source as it is?

**Comment by piotrzarzycki21** [comment]
My recommendation is that we shouldn't bother FlexJS earlier than 0.7.0. Maybe try to discuss with Joel about that. Even if you decide to have another place witch some checks whether we are in earlier version of FlexJS it won't something on the top of my list to do.

**Comment by piotrzarzycki21** [comment]
I don't know what to do with compiler to give proper error in that case. Maybe we have some issue there.

**Comment by rat-moonshine** [comment]
I think we can live without doing much worry about 0.6.0. It's anyway very older and unstable than recent versions. I think we anyway want to encourage people to use latest SDKs, but thank you for clearing the scenarios present with this problem @piotrzarzycki21 .
