### ISSUE TITLE
Code Completion Listing Improvement

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#129]
At this moment CC list generated as follows:

![untitled](https://user-images.githubusercontent.com/24370870/34550529-b6083b6c-f137-11e7-8ec6-a6f8ecd8d75b.png)

The word 'Function' shows against almost all the entries here - I can understand it is because a field having GET/SET functions. This is somewhat vague to me and probably we can do something about distinguish/mark between method/properties (?)

Beside the above request, the CC list entries should also add the return types, i.e. String, int, void etc. This would be more helpful finding some particular type of method/property.

**Comment by piotrzarzycki21** [comment]
I just added "Property" instead of "Function" to the completion list. 
As for your second suggestion - currently when you hit Ctrl + Q on Windows and Cmd + F1 on Mac you will get tooltip with more detailed information about method/function/property. 

Do you suggest something more ? Where do you want to display it? How things are displayed in Flash Builder ?

**Comment by rat-moonshine** [comment]
In Eclipse or Flash Builder, it shows the return type beside the method/property name:

![image](https://user-images.githubusercontent.com/24370870/34570398-aeddaa20-f191-11e7-894d-b65a83420927.png)

As you see, since the return type available against all the entries, I can scroll between faster to determine what it returns beside hitting combination of keys against each items.

**Comment by rat-moonshine** [comment]
And.. maybe, we can avail the full method parameters as well (?)

**Comment by piotrzarzycki21** [comment]
What actually is the second information - That's blurry one ? For example near hasOwnProperty():Boolean - Object - What is that ?

**Comment by rat-moonshine** [comment]
I'm not very clear about that, too. I can do some guesswork, but I'm not clear either.

**Comment by piotrzarzycki21** [comment]
I think I can display easy return type for item, but not sure what about that details of method. We will see.

**Comment by piotrzarzycki21** [comment]
Could you show a screenshot in case of MXML variables in some components and in case of component choose ?

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/34571682-1f519d5e-f195-11e7-9815-8bbc870da9d7.png)

**Comment by piotrzarzycki21** [comment]
I have pushed changes to code completion. Take a look and let me know what do you think.

- Added signature method
- Added returned type always visible in CC

**Comment by rat-moonshine** [comment]
This looks very helpful and handy now. Thanks for this improvement @piotrzarzycki21 .

I'm closing this issue as complete.

**Comment by atinprominic** [comment]
I found that the code completion doesn't work if I type the tag name in different case. 

For example if I type <js:sim and then press CTRL+Space then it doesn't work. But if I type <js:Sim and then press CTRL+Space then it shows the context menu. 

Refer to attached screenshot for details:

![screen shot 2018-01-31 at 4 14 33 pm](https://user-images.githubusercontent.com/34882311/35618859-2e0da1a4-06a2-11e8-959c-ad735e9ee7b8.png)

**Comment by piotrzarzycki21** [comment]
@atinprominic please raise separate issue for that with screenshot above.
