### ISSUE TITLE
File Opens Incorrectly in Visual Editor After Restart

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#132]
I noticed this behavior during my testing today.
1. Create/Open a Visual Editor project
2. Open the main file in a tab
3. Create/Open another project (not visual editor)
4. Open a file from the second project.  It opens properly in the text editor
5. Restart Moonshine.  The files reopen because of #106
6. BUG:  The second file opens in a blank visual editor tab.
7. Close and reopen the second file.  It opens properly in the text editor

**Comment by piotrzarzycki21** [comment]
I have pushed fix for that. It looks like we still didn't make final build for release, so it can be added as well.

**Comment by JoelProminic** [comment]
I tested with this update, and I was not able to reproduce the bug.  This was included in the 1.8.0 release build.
