### ISSUE TITLE
Make It Easier to Open SDK Example Projects

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#133]
I would like to streamline the process of opening the example projects from the SDK.  I think this will be helpful for people who are new to Royale (or are just not familiar with how the examples are structured).

For example, to get the MDLExample working, I had to do the following:
1. File > New > Royale Browser Project
2. Browse to the MDLExample directory in Project Directory
3. Select the Royale SDK
4. Check "Project with existing source"
5. For "Main source folder", I had to select src/main/royale.   Since the files are not visble from the selector UI, I tried src and src/main first, but this gave me no results for "Main application file"
6. For "Main application file", I selected App.mxml.  I had to check build.xml and build_example.xml to determine which file I should select here.
7. Click Create
8. Open the project settings
9. Add this string in the Additional compiler options:  "-compiler.exclude-defaults-css-files=BasicJS.swc:defaults.css -html-template=src/main/resources/mdl-js-index-template.html".  I found this in @piotrzarzycki21's email, but it looks like I could also find them in src/main/config/compile-app-config.xml (if I were familar with this file).
10. Add a new resource directory, and select src/main/resources/assets.  I saw that this was necessary from the build.xml file.
11. Save

I would like to populate some of this information automatically to help new users get started.   

I'd like to avoid having this logic be hard-coded for the SDKs, but Moonshine may need to know the conventions used in the SDK examples in order to find the relevant files.

If we had some documentation in our wiki for how to open some of the examples, that could be sufficient (but less convenient).   Additionally, we could supply as3proj files for the example projects, but it may be more desireable to walk the users through the examples.

I thought that we had created an issue for this already, but I think this was in the Prominic JIRA.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I had from a long time task on my list where I'm adding to all examples Moonshine project files. PMCs who are using VSCode did that and there wasn't any problems from the community sight. I just haven't found community time for that. Since you have raised an issue for that - I propose to do this in that way. Any other options seems to be to me too complicated.

**Comment by piotrzarzycki21** [comment]
Once we create Royale project there are generated files which are helping open project in the browser if build is being done to SWF. Those files cannot be included to Apache Royale repository. 
When I removed following folders: **bin-debug**, **html-template**, **build** I was able to build project to SWF without the problem.

I preform also "Build & Run" and on my Windows system where I have environment variable `FLASHPLAYER_DEBUGGER = d:\flex_sdk\player\flashplayer.exe` swf run as Flash Player Content Debugger.
On Mac OSX it runs in the browser and I got nice information: 
![image](https://user-images.githubusercontent.com/24554795/34765841-e03f36c8-f5f2-11e7-9793-047b2400230d.png)

I believe we can live with this. JavaScript builds run without the problems.

**Comment by piotrzarzycki21** [comment]
I just added our files to most of the examples https://github.com/apache/royale-asjs/commit/74a4c12fd721cab4f2404916ba69fdc67e69141e . 
It looks like in the future we will need to handle also in Moonshine configuration of projects which are using Apache Cordova. - I omit those one cause I will have to spent some more time in order to know what to do to run it.

**Comment by JoelProminic** [comment]
Yeah, including the project files in the example projects would be the simplest solution for us, but I wasn't sure if it would be allowed.

SWF builds are still a bit problematic for my testing - I have to use a different default browser to open them properly.  I'll give these example projects a test after they are updated in the nightly builds to see if I have any trouble with the changes you made.

**Comment by piotrzarzycki21** [comment]
I just download nightly with my changes and found one problem. If I open any example file and perform "Build & Run as JavaScript" - It is trying to run my old path which is being hard-coded in *.as3proj file `<option urlToLaunch="D:\flex_sdk\Royale-Sources\royale-asjs\examples\royale\ChartExample\bin\js-debug\index.html"/>`

Obviously nightly has been downloaded in a different location. If I go to the "Settings" -> "Run" and make "Clear" on Url to Launch than "Save" location is staying as is. Clear is not working. - This is an issue - I should be able to Clear that one.

I clean manually that url in *.as3proj file and relaunch project. It automatically filled correct path into that place. I will raise separate issue for clearing and make manual corrections to all that files.

I will let you know once new nightly will be available.

**Comment by piotrzarzycki21** [comment]
[Nightly build] (http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/lastSuccessfulBuild/artifact/out/) with my changes is available.

**Comment by piotrzarzycki21** [comment]
Reopen if you see something more here.
