### ISSUE TITLE
Support for AS3 library project compilation

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#135]
At this moment Moonshine does not compile individual library projects. We need to add support to compile library project to `.swc`, along with requisite compilation options. 
  
The should involve providing new template options to create ActionScript and Flex library.

**Comment by rat-moonshine** [comment]
We'll need a new project template for producing SWC files, i.e. Flex/ActionScript Library Project.

**Comment by rat-moonshine** [comment]
Updates:
- New project template for library project creation updated
- New project creates with no source file inside but requisite folders - this is how Flash Builder handle the kind of project by not creating any particular source file inside. In that way we can also cut-down the needs of providing a file type between _.as_ and _.mxml_ (as opening file); Please, provide feedback what you think on this, though
- A new field being added inside `project/Settings/Run` section - Output Path; Here user can change the library project's _.swc_ output folder (if needed, and this generally became needed in many library project cases), default is "bin-debug"
- The above newly created field handling might requires minor fixes in other project type cases, though

**Comment by rat-moonshine** [comment]
- New configuration file generates against library project
- Compilation of .swc file using the generated config file

However, I'm having difficulty to generate a run-able config file which is bundled with any/another .swc (say SUB-SWC) file. The most closest command I could able to found is `-compiler.library-path [path-element] [...]`. Adding the command seems to include the given .swc (SUB-SWC) file codes into the compiling .swc (MAIN-SWC) (because of the increase in size of the compiled one); But the compilation always throws error if any class file being called from the SUB-SWC to MAIN-SWC's class file. It throws wired error like "The definition of base class BitmapAsset was not found". 

@piotrzarzycki21  do you have any idea how we can incorporate SUB-SWC files into the compilation process/config-file? Else, this needs to be investigated.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine do you need me to look into that or did you figure out something ?

**Comment by rat-moonshine** [comment]
Nothing fruitful yet. I'm still looking into different command attributes and trying to play with. I was wondering if you already has any idea about the kind of packaging @piotrzarzycki21 . Yes, you're welcome if you feel have some space from other tasks in your hand.

**Comment by piotrzarzycki21** [comment]
If I choose AS Library project - I can create SWC using Flex and Feathers SDK ? 
I think in case of Royale it can be a bit separate process - Maybe I will handle it.

**Comment by piotrzarzycki21** [comment]
I will start looking into it, but need to understand where the problem is. Probably will have more question to you soon.

**Comment by piotrzarzycki21** [comment]
In following scenario:
1) Creat AS Library
2) Add Flex SDK
3) Create MainClass.as
I got following exception in the console, not sure if we can do anything with that:

```
java.io.FileNotFoundException: D:\flex_sdk\Projects\Prominic.NET\Moonshine Tests\NewActionScriptLibraryProject\src\NewActionScriptLibraryProject.mxml
: 	at org.apache.flex.compiler.filespecs.FileSpecification.createReader(FileSpecification.java:79)
: 	at org.apache.flex.compiler.internal.caches.MXMLDataCache.createEntryValue(MXMLDataCache.java:85)
: 	at org.apache.flex.compiler.internal.caches.MXMLDataCache.createEntryValue(MXMLDataCache.java:38)
: 	at org.apache.flex.compiler.internal.caches.ConcurrentCacheStoreBase.get(ConcurrentCacheStoreBase.java:69)
: 	at org.apache.flex.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:52)
: 	at org.apache.flex.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:36)
: 	at org.apache.flex.compiler.internal.units.MXMLCompilationUnit.getMXMLData(MXMLCompilationUnit.java:281)
: 	at org.apache.flex.compiler.internal.units.MXMLCompilationUnit.handleFileScopeRequest(MXMLCompilationUnit.java:168)
: 	at org.apache.flex.compiler.internal.units.CompilationUnitBase.processFileScopeRequest(CompilationUnitBase.java:864)
: 	at org.apache.flex.compiler.internal.units.CompilationUnitBase.access$200(CompilationUnitBase.java:109)
: 	at org.apache.flex.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:288)
: 	at org.apache.flex.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:284)
: 	at org.apache.flex.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
: 	at org.apache.flex.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rat-moonshine** [comment]
I'm not surely really why its trying to open some file like this:

> java.io.FileNotFoundException: D:\flex_sdk\Projects\Prominic.NET\Moonshine Tests\NewActionScriptLibraryProject\src\NewActionScriptLibraryProject.mxml

When we only creates an _.as_ file. This can be investigate, though.

**Comment by rat-moonshine** [comment]
I'm checking for the above break, maybe I can address this.

**Comment by piotrzarzycki21** [comment]
If it is only Flex library project - It should be called: "Flex Library Project".

**Comment by rat-moonshine** [comment]
My intention was that user can use the template for Flex or ActionScript library project. But I didn't wanted to create multiple templates for the purpose (unless we find that is essential in coming days), so I take the name 'ActionScript Library Project'.

Being said that, we can also use 'Flex Library Project', since we have different templates for Flex and ActionScript projects, I was thinking if the name 'Flex Library Project' only points to creating MXML type of library project.

Thoughts?

**Comment by piotrzarzycki21** [comment]
It is the matter of figure out what will happen if you add Feathers SDK to your project. Maybe it will require some different approach. 
On the second thought I like ActionScript Library Project name - if we will have to make some more steps in order to have Feathers SWC - let's make Drop Down List during project creation. - Similar which we have in "Flex Browser Project (FlexJS)"

**Comment by rat-moonshine** [comment]
Hm.. I think having a dropdown for project type against library creation, that is a good idea. And if we do such way, we can even add a default class file (.as or .mxml) to the project source also! 

Thank you!

**Comment by rat-moonshine** [comment]
The above said null pointer exception now resolved. 

Also, a new _type_ dropdown introduced in library project creation dialog - to choose between Flex (.mxml) and ActionScript (.as). Since Feathers type also uses .as file, I didn't separately added any Feathers entry (to the dropdown). 

Based on the above selection, a default .as or .mxml file now creates with the new project creation.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I dig into that a bit more and here is how it looks like in case of Intellij. I can create following type of libraries there:

1) Desktop Adobe Air Library
2) Desktop Adobe Air pure ActionScript library
3) Mobile Adobe Air Library
4) Mobile Adobe Air pure ActionScript Library
5) Web Adobe Air Library
6) Web Adobe Air pure ActionScript library

I believe we should cover all of that cases and each should have additional compilation arguments filled accordingly. The same as I did [here](https://github.com/prominic/Moonshine-IDE/blob/f6c7e6859889f6cfc9483d6fa6eb33c627ae6522/ide/MoonshineSharedCore/src/elements/templates/projects/Flex%20Mobile%20Project%20(iOS%2C%20Android)/%24Settings.as3proj.template#L45)

Options: 1, 2: +configname=air
Options: 3, 4: +configname=airmobile
Options: 5, 6: +configname=flex

Intellij is calling the same as you compc and load config. I grab for each type of project compilation configs for you. 

[library_configs_files.zip](https://github.com/prominic/Moonshine-IDE/files/1668252/library_configs_files.zip)

I'm not sure why but I couldn't build web project library swc type of project, but maybe that is my fault. However I grabbed config files for that type of projects too.

Our current build of swc produces warnings, once you take a look to the configs and apply them in case of each build we may get rid of them.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 the zip is very helpful. In a fact, we was in need to have a formatted configuration file for compiling SWCs (other than investigate ourselves). I see the format also has examples to include other SWC files. Did you generate them through the IntelliJ?

The kind of different project types also available in Flash Builder. But I was unsure how much to go since the compilation process wasn't very well documented/exampled so I limited myself to have generic Flex and ActionScript libraries. 

With the availability of all types example configuration files, I think it'd become more easy to incorporate them with library creation process. 

Thanks!

**Comment by piotrzarzycki21** [comment]
Not sure what your question is. Those files has been generated by Intellij automatically. I had to grab them during build, because intellij immediately remove them after finished build. :)

**Comment by rat-moonshine** [comment]
Cleaver and jealous IntelliJ xD

**Comment by piotrzarzycki21** [comment]
Yes I had to be quick!!! :)

**Comment by rat-moonshine** [comment]
I'm closing this issue as completed. Please, reopen if you find some bug or amendment needs.

**Comment by AlHolden** [comment]
I know this story is pretty old, but did this ever make it into the IDE?

I have an old project to resurrect and possibly convert for a government deal, and it has 25 LIBRARY projects.
I do not see any _'Flex Library Project'_ option in the New templates here.
Version 3.3.3, Build 1250, Player: 33.1(Harman) Running On: Windows 10

Is anyone home? Thanks,
Al

**Comment by piotrzarzycki21** [comment]
> I know this story is pretty old, but did this ever make it into the IDE?
> 
> I have an old project to resurrect and possibly convert for a government deal, and it has 25 LIBRARY projects. I do not see any _'Flex Library Project'_ option in the New templates here. Version 3.3.3, Build 1250, Player: 33.1(Harman) Running On: Windows 10
> 
> Is anyone home? Thanks, Al

Hi @AlHolden ,

What issue exactly you have? Did you try open these libraries in Moonshine and it failed? Was that project before configured for other IDE? (Intellij, Flash Builder)

**Comment by AlHolden** [comment]
Hi @piotrzarzycki21 thanks for responding,

Originally in FlashBuilder 4.7 IDE, we would create the 25 projects as "Library Objects", and then include those somehow in the one parent AIR desktop project. 
The idea of a Royale conversion interests me, but I thought I'd try to prop up the original version first (as our FB is no longer installing or launching anymore).

This story/issue 135 implies that there should be an option in Moonshine's "New" dropdown now - to select "Flex Library Project" as the type. I don't see that in my installation. Maybe I misunderstood this part?

**Comment by rat-moonshine** [comment]
Hi @AlHolden , thank you for reaching out to us. 

If I understand correctly, there is an AIR project which you wants to run while the project is using 25 library projects as .SWC.

If my understanding is correct, please open/import the main AIR project in Moonshine-IDE. Right-click on project's root-node from sidebar and choose `Settings`. Under Settings, `Paths -> Libraries` - where you can browse and select different SWC files. Later, you can compile/run the AIR project in usual manner (i.e. `Project -> Build & Run`), that should compile and run your project using the configured SWCs.

On a separate note, if you wants to create library project - `File -> New ->Library Project (Flex)`. Moonshine-IDE is able to compile-out .SWC file. 

Hope this helps.

**Comment by piotrzarzycki21** [comment]
Just an additional explanation to what @rat-moonshine said is that - I have asked about previous configuration because Moonshine "understand" Flash Builder project files - if they are exists - you will be able to configure your project in a way as described above.

I believe additionally you can try open in Moonshine each of that libraries as separate projects if Flash builder configuration exists in each folders - If not let me know I will try play with similar case on my laptop and provide you solution. 

I'm using Moonshine in the last 2 years to code in Apache Royale so my memory is blurry in that case a bit. Good to hear that you are understand in Royale conversion if you will need any help with that let me know.

**Comment by AlHolden** [comment]
Thank you @piotrzarzycki21 and @rat-moonshine !

I see the problem now. It's a **UI or dumb user issue**, and might be worth a correction. Please consider:

ALL of your prior Flex options are consolidated alphabetically, prefaced with the word:
>New ->
>Flex Browser Project (SWF)
>Flex Desktop Project (MacOS, Windows)
>Flex Mobile Project (iOS, Android)

By this logic, I was searching for a label like this: "**_Flex Library Project (SWC)_**" - thinking that it would be _alphabetically adjacent_ to the others. Because this was an enhancement, I assumed it was not in the package yet.

But nooo, this option is here, and has been placed "below the fold", away from its siblings, and with a different label:
> Library Project (Flex)

This is what has led to my confusion. I have many projects to re-create now ;-]

AL

**Comment by piotrzarzycki21** [comment]
> Thank you @piotrzarzycki21 and @rat-moonshine !
> 
> I see the problem now. It's a **UI or dumb user issue**, and might be worth a correction. Please consider:
> 
> ALL of your prior Flex options are consolidated alphabetically, prefaced with the word:
> 
> > New ->
> > Flex Browser Project (SWF)
> > Flex Desktop Project (MacOS, Windows)
> > Flex Mobile Project (iOS, Android)
> 
> By this logic, I was searching for a label like this: "**_Flex Library Project (SWC)_**" - thinking that it would be _alphabetically adjacent_ to the others. Because this was an enhancement, I assumed it was not in the package yet.
> 
> But nooo, this option is here, and has been placed "below the fold", away from its siblings, and with a different label:
> 
> > Library Project (Flex)
> 
> This is what has led to my confusion. I have many projects to re-create now ;-]
> 
> AL

Good point with that. Thanks Alan. I don't see reason why not to change that. @rat-moonshine what do you think ? Change would be: **Library Project (Flex)** to **Flex Library Project**

**Comment by AlHolden** [comment]
Some UI folks might suggest a short period of time where you actually have _both the old and the new links_ there, like just for a release or two. That can help some (but not all) existing users adjust to the new pattern.

**Comment by rat-moonshine** [comment]
"Flex Library Project (SWC)" is a good option.
