### ISSUE TITLE
Auto-completion problem with XML attributes

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#136]
![ccproblem2](https://user-images.githubusercontent.com/24370870/34823436-55543f5a-f6f0-11e7-9697-3b7723e932c7.gif)

**Comment by piotrzarzycki21** [comment]
Can you change title to: Auto-completion problem with xml attributes ?

**Comment by rat-moonshine** [comment]
The wrong double-quote addition is now fixed.

However, can we add the parentheses shown in the code-completion list when the option selected?
![image](https://user-images.githubusercontent.com/24370870/35027231-9553f468-fb75-11e7-889c-08a6e097f1ad.png)

In above scenario, if I hit Enter against the highlighted option, the entry adds as 'abcd' (without parenthesis). Therefore user needs to add the parenthesis him/herself. I think it would be very convenient to add the complete parenthesis if no parameter is present, and only the first parenthesis if parameters are present (to the method).

Let me know your thoughts on this, @piotrzarzycki21 .

**Comment by piotrzarzycki21** [comment]
Actually I can do this in case of function/methods. It will be very useful! Let me raise separate issue for that small improvement.

**Comment by atinprominic** [comment]
The code completion feature is not working at all for me. I have tried many ways but its not working. It worked for a while then suddenly stopped working. Please test on various platforms to reproduce it.

**Comment by piotrzarzycki21** [comment]
What SDK are you using ? What Java version ? This is Mac OSX platform ?

**Comment by atinprominic** [comment]
@piotrzarzycki21  I got it. It was due to wrong SDK selected. Its resolved now.
