### ISSUE TITLE
[UI Builder] Opens same editor multiple time

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#139]
- Create a new Visual Editor mockup project
- The editor immediately opened after the project creation completes
- Double-click on the _.veditorproj_ file from the sidebar
- Editor opens the same file with another instance - now one can do different things in different editors but last editor's changes saving to the file

The above behavior can create unexpected confusions. The same editor should get focused if _.veditorproj_ file double-clicked instead of opening a new instance of the same file.

**Comment by atinprominic** [comment]
Seems to be resolved.
