### ISSUE TITLE
Building Royale application to SWF only doesn't work without custom sdk

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#141]
If we doesn't setup custom sdk for the Royale project building to SWF won't work.

1) Create Royale application
2) Setup main SDK (Do not setup custom sdk for project)
3) Choose **Project** -> **Build Project**

Result: Compilation won't start

**Comment by atinprominic** [comment]
There are no any details about resolution of this issue. Is it resolved? Also in the Issue Description its not clear that Royale Application should work without Custom SDK specification or not. As per my understanding we need to specify the Royale SDK for the Royale project and we need to specify it as Custom SDK. How its wrong? I am not able to understand

**Comment by piotrzarzycki21** [comment]
Hi @atinprominic ,

I'm sorry. I just make commit with Fix as you can see in the history and resolve it. In the description there is scenario where building Royale application to SWF won't work.

For the end user building project should work whether he specify "Custom SDK" or "Default SDK" in the Moonshine's settings. - Both way should allow build project. Unfortunately I discovered that if you specify only "Default SDK", build to SWF didn't work.

Your scenario for tests should be exactly as it is in the description. "Default SDK" (File -> Settings -> Default SDK) **specified**, "Custom SDK" (Project Settings -> Build Options) **not** - Check if it's working.

**Comment by atinprominic** [comment]
Ok. I understood. But can you please let me know that should I chose - "Flex Browser Project (FlexJS, Royale)"?

If I create the project then I am getting below error:

: Compiling FB
: Using Royale Compiler codebase: /Users/atin/Downloads/apache-royale-0.9.0-bin/royale-asjs/js/bin/../..
: Using Royale SDK: /Users/atin/Downloads/apache-royale-0.9.0-bin/royale-asjs/js/bin/../..
: MXMLJSC
: +royalelib=/Users/atin/Downloads/apache-royale-0.9.0-bin/royale-asjs/js/bin/../../frameworks
: -sdk-js-lib=/Users/atin/Downloads/apache-royale-0.9.0-bin/royale-asjs/js/bin/../../frameworks/js/Royale/generated-sources
: -load-config+=obj/FBConfig.xml
: -optimize=false
: -debug=true
: -o
: bin-debug/FB.swf
: -compiler.targets=SWF
: Loading configuration: /Users/atin/Downloads/apache-royale-0.9.0-bin/royale-asjs/frameworks/royale-config.xml
: Loading configuration: /Users/atin/Documents/FB/obj/FBConfig.xml
: /Users/atin/Documents/FB/src/FB.mxml(2): col: 1 Error: This tag could not be resolved to an ActionScript class. It will be ignored.
: <js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
: ^


Thanks
Atin
