### ISSUE TITLE
[1.8.0][Windows10] CodeCompletition just provides elements that starts with first typed character

### ISSUE THREAD

**Issue by olafkrueger** [prominic/Moonshine-IDE#142]
Hi,
I've installed 1.8.0 on Windows 7 and Windows 10, but on Windows 10 the code completition does not work properly for me:
When I type e.g. "<F", the code completition provides just elements whose leading first character is an "F" [1].
On WIndows7 it works fine., code completion e.g. also provides "VerticalFlexLayout" by typing "<F"
I've already removed Moonshine, installed it again, removed the moonshine-ide folder, reset the settings... nothing works for me.

Any ideas?

Thanks,
Olaf

[1] https://snag.gy/i8TdBr.jpg

**Comment by piotrzarzycki21** [comment]
Olaf,

Provide please version of Royale SDK: Is it SWF and JS or JSonly package?

**Comment by olafkrueger** [comment]
I used one of the latest JSOnly builds on the Windows10 machine.
(I am not sure at the moment which SDK version I used on the Windows7 machine)

Thanks,
Olaf

**Comment by olafkrueger** [comment]
Hmmm... I've just restarted my WIndows10 machine one more time and now it works... can't believe it.
Sorry for annoying you!

Olaf

**Comment by piotrzarzycki21** [comment]
Still something smells me that we still may have some problem. Will see if someone else notice anything. :)
