### ISSUE TITLE
Desktop flex application build with warnings doesn't launch

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#144]
I was trying to build [MockupVisualEditor](https://github.com/prominic/MockupVisualEditor) in Moonshine. During build of that app we have some desirable warnings, which seems to be the cause of not launching app. 

Scenario:
1) Setup application which produce warnings during build
2) Choose "Build & Run" or "Build & Debug"

Result: Application finishing the build but it's not starting

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Can you review my fix, whether it has sense. I was mention you the other day that for some reason "Build & Run" didn't work to me in the development version.
Later I couldn't reproduce it, unit I tried to setup build of MockupVisualEditor.

Basically "fcsh" through NativeProcess throw to us `ProgressEvent.STANDARD_ERROR_DATA`. We are searching in the event message "Error" and stop the build. However in the string event there are warnings only, so build should proceed farther without stop. 

We have that issue in 1.8.0.

**Comment by rat-moonshine** [comment]
I tried to give a test with earlier released 1.8.0 installed version in Windows. Although, I didn't noticed or able to reproduce the problem scenario described in this issue:
- Created a new Visual Editor mockup project
- Exported the project with some components in it, to a Flex desktop project
- "Build & Run" the Flex desktop project
- Project compiles properly and started the simulator

I'm not sure if this has the compiler has different implementation in case of macOS though, at this moment (I shall need to give a try there as well).

I seen your fix and that should be handy. If the process halts by the warning should bypass by your fix now. I will give the scenario a try on macOS.
