### ISSUE TITLE
Opening any children throws IOError if parent is being renamed

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#147]
- Create a class file inside a project folder
- Double-click opened the class file effectively. Close the file
- Rename the folder where the class file being created
- After rename is done try to open the same class file again
- Moonshine throws IOError

We need to update path references to every sub-folders/files from the parent folder (where rename performed), after a _folder_ rename event.

**Comment by rat-moonshine** [comment]
Updates:
- Rename file/folder process removed from TreeView to RenamePlugin
- [Bug] If an opened file (to editor) being renamed, double-clicking the file from sidebar was opening another instance to the editor without updating the opened one - Fixed - Opened file/tab now updates after a renaming event done

**Comment by rat-moonshine** [comment]
There are some changes in progress - tree view may show some visual distortion. Please raise any issue related to this if you have doubt, other than raising new separate issue.

**Comment by piotrzarzycki21** [comment]
Does that changes will eliminate that visual distortion ? - I saw it once but couldn't reproduce it.

**Comment by rat-moonshine** [comment]
Can you please clarify to which visual distortion you're pointing to, @piotrzarzycki21 ?

**Comment by piotrzarzycki21** [comment]
It's kind of hard to describe. Some of the branches overlay itself when I was scrolling or disappear.

**Comment by rat-moonshine** [comment]
Mmm.. Not sure about that, I never seen such distortion caused by the recent changes, though. But lets keep that in note, to test back when this development is over.

**Comment by JoelProminic** [comment]
I was able to reproduce some distortion behavior with these steps:
# Open multiple projects
# Rename the "obj" directory to "obj2" for one of the projects
# Check the tree behavior.  The tree still works properly
# Rename the "obj2" directory back to "obj".
# Check the tree behavior.  I saw overlaps, nesting of projects, and other wierd results.

When checking the tree behavior, make sure to open and close the obj/obj2 directory multiple times

Otherwise, the rename dialog seems to behave as a modal dialog.  I couldn't trigger any other actions (except Moonshine > Quit) while the dialog was open

**Comment by rat-moonshine** [comment]
- Tree folder now updates its children path if renamed
- Any opened editor respective to any children also updates accordingly

I have tried to reproduce the distortion problem @JoelProminic mentioned, but so far I haven't noticed any. Please, give some test, and let me know if you're still able to see those distortion, or any bug.

**Comment by JoelProminic** [comment]
I was not able to reproduce the distortion error after today's update.

I renamed a directory, and tried the following with a nested file
- Right-Click > Copy Path - UPDATED
- Right-Click > Open in Finder - UPDATED
- Updates in an open editor - UPDATED
- Opening the file from the RECENT list on the Home tab - ERROR

**Comment by rat-moonshine** [comment]
[BUG] Opening the file from the RECENT list on the Home tab - Fixed.

**Comment by JoelProminic** [comment]
The RECENT list seems fine as well now, and I re-tested and confirmed the other cases from my last comment.
