### ISSUE TITLE
Project deletion changes in Moonshine

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#148]
After a brief discussion on some procedural changes to the project deletion feature in Moonshine at #140 , we came up with the following ideas. 

Instead of deleting complete project folder (as it is now), Moonshine will perform following steps after a project deletion call from its sidebar:
- Delete all the files/folders which Moonshine can keep track of through its project object, i.e. bin-debug, bin, build, any project configuration files and its source folder
- Leave the project foot folder to the system from deletion
- Joel also suggested the following popup during project deletion for added transparency:
![image](https://user-images.githubusercontent.com/24370870/35428853-49cec81e-0297-11e8-8b0d-40f7f7d7a2e0.png)

Some notes from @JoelProminic as well on above design:
> - The tree would be collapsed by default so that the default case is easy to read
> - Show the actual directory names (to catch the Documents case Atin described)
> - The user can't select which files they want to delete or keep (though that could be a future improvement if there was interest)
> - This interface could be used for other directory or file deletes as well.
> - This doesn't display the absolute path, but the user could recognize other directories by the directory name or contents.

**Comment by rat-moonshine** [comment]
Updates:
- Delete list updated with most of the managed files/folders those we can allow to delete
- Alert updated
- Project deletion now deletes only the file/folders supplied during the course

Issues:
- Project reference yet to remove from the sidebar
- Needs to update some process part for template project deletion (silent)

**Comment by rat-moonshine** [comment]
I'm more or less done with this requirement. Once 1.11.0 released, we'll move to merge.

**Comment by rat-moonshine** [comment]
Codes merged to 'master'. Having language-server issue when project deletes:

> : org.xsocket.connection.ExtendedClosedChannelException: could not write. Channel is closed (id=676b18e3162e24194db7b328c0S1 (closed))
> : 	at org.xsocket.connection.AbstractNonBlockingStream.ensureStreamIsOpenAndWritable(AbstractNonBlockingStream.java:1529)
> : 	at org.xsocket.connection.AbstractNonBlockingStream.write(AbstractNonBlockingStream.java:1054)
> : 	at org.xsocket.connection.AbstractNonBlockingStream.write(AbstractNonBlockingStream.java:1039)
> : 	at moonshine.MoonshineLanguageClient.publishDiagnostics(MoonshineLanguageClient.java:58)
> : 	at java.util.HashMap$Values.forEach(HashMap.java:980)
> : 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkFilePathForAllProblems(ActionScriptTextDocumentService.java:5082)
> : 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkFilePathForProblems(ActionScriptTextDocumentService.java:4982)
> : 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkProjectForProblems(ActionScriptTextDocumentService.java:4970)
> : 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didChangeWatchedFiles(ActionScriptTextDocumentService.java:1347)
> : 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService$2.run(ActionScriptTextDocumentService.java:1472)
> : org.xsocket.connection.ExtendedClosedChannelException: could not write. Channel is closed (id=676b18e3162e24194db7b328c0S1 (closed))
> : 	at org.xsocket.connection.AbstractNonBlockingStream.ensureStreamIsOpenAndWritable(AbstractNonBlockingStream.java:1529)
> : 	at org.xsocket.connection.AbstractNonBlockingStream.write(AbstractNonBlockingStream.java:1054)
> : 	at org.xsocket.connection.AbstractNonBlockingStream.write(AbstractNonBlockingStream.java:1039)
> : 	at moonshine.MoonshineLanguageClient.publishDiagnostics(MoonshineLanguageClient.java:58)

**Comment by rat-moonshine** [comment]
The above language-server error now handled. Feature is ready for test.

**Comment by JoelProminic** [comment]
When a project is deleted, the base project directory is not deleted, which leaves unnecessary clutter on the fileystem.

In my original notes, I recommended that the new interface show the collapsed project tree initially.  The current implementation expands to show the first level of files/subdirectories in the project directory.  I think I like this behavior better - it provides some information about the target directory without showing too much detail (at least for simple projects).

I think the second deletion prompt is unnecessary.  Include a line that says "Are you sure you want to delete this project?":
![image](https://user-images.githubusercontent.com/24532731/39075212-4176e466-44ba-11e8-86a8-17ba133ffb24.png)


There should be a "Cancel" button on this prompt.   The close button works, but we should have explicit button in this situation.

I noticed that the deleted project briefly appeared in the RECENT list on Moonshine restart:
1. Delete a project
2. Check the home page - the project was removed from the RECENT section
3. Restart Moonshine
4. BUG:  the project is listed in the RECENT section on startup
5. Other editors open
6. Check the home page - the project was removed from the RECENT section

I confirmed that the prompt displays the actual directory name, even if it doesn't match the project name:
1. Create a new project
2. Close the project
3. Rename the project directory on the filesystem
4. Open the project in Moonshine again
5. Delete the project.  The prompt shows the directory with the new name.

**Comment by rat-moonshine** [comment]
Since this was a project deletion, I wanted the user to be absolute sure by prompting them with a 2nd alert against what they're going to do. The alert is removed now.

A new cancel button added. I have intentionally moved the 'Delete' button to left - so I want user needs to be sure what they're doing and reach to the button by moving their cursor/hand to left (and not clicking the delete button accidentally where the Cancel button is now).

Moonshine restart bring back deleted project reference - is now solved.

**Comment by piotrzarzycki21** [comment]
Additionally I think added CANCEL button should be default. If user do Enter it should make CANCEL.

**Comment by rat-moonshine** [comment]
We can do that. But what is the essence of Enter button in this form practically (?) Generally, when cancelling a popup we use the Esc key.

**Comment by piotrzarzycki21** [comment]
I think it is mainly if user accidentally hit enter having that window popped out. It happens to me from time to time.  

On the other hand I see that in the IDE like Intellij "Delete" button is default. Wondering how it looks like in FB ?

**Comment by rat-moonshine** [comment]
In Flash Builder, 'Delete' button is also default focused. However, with current dark button theme button focus in not very prominent in Moonshine.

**Comment by rat-moonshine** [comment]
But again we arise to the same question - why would an user would want to Enter, when there is no input field, or even the focus visibility is not clear against buttons.

If focus visibility is not clear with current theme, then perhaps hitting enter and cancelling the form may create some confusion to the user on what happened. Or, maybe we someway we need to clearly mark any of the button so user be sure what happened after the Enter button being hit.

**Comment by piotrzarzycki21** [comment]
My concerns were only for the accidental hit of enter. If you want you can leave it as is.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Yes the issue which you are experienced is a Bug, but in SDK -> [FLEX-26797](https://issues.apache.org/jira/browse/FLEX-26797). - It wasn't fixed.

In order to workaround it you shouldn't use FocusManager. You are using TitleWindow, so setup for title window default button - same as [here](https://github.com/prominic/Moonshine-IDE/blob/85109022abcc3e7f7afdb84aa5d22fd41a7f2129/ide/MoonshineSharedCore/src/components/popup/FindResourcesPopup.mxml#L31). Than in order to workaround the issue in `creationComplete` event set manually skin for the button - the same as [here](https://github.com/prominic/Moonshine-IDE/blob/85109022abcc3e7f7afdb84aa5d22fd41a7f2129/ide/MoonshineSharedCore/src/components/popup/FindResourcesPopup.mxml#L68).

As you can see I do not use focus on that button in FindResourcesPopup, but if you want to use in your right after setting sking make: `btnCancel.setFocus();`

Above solution working in FindResourcesPopup and it should work on your sight.

**Comment by rat-moonshine** [comment]
Thanks for the info link @piotrzarzycki21 .

The alternate solution you've mentioned, I see this is another way (along with using the `defaultButton` property to the TitleWindow). But in both the cases we need to update the button's skin and rendering again. 

I'm curious, why we shouldn't use FocusManager in this case?

**Comment by piotrzarzycki21** [comment]
I'm sorry probably I should be more clear here. I didn't mean that you shouldn't use at all FocusManager - I mean that in this solution you shouldn't use it because there is a way where you can pass whole responsibility to the Flex internal mechanism.  - defaultButton, but since there is problem in Flex itself you will have to manually set skin for button. - It is not so bad after all, you are setting that skin by CSS, so in that case you will just change the way how you do that. 

Does that make sense ?

**Comment by rat-moonshine** [comment]
Yes, that explains the view, @piotrzarzycki21 .

**Comment by rat-moonshine** [comment]
The design mainly proposed here keeping in mind the problem that Atin has faced in past. We did introduced other measure like updated path prompt in project creation dialog, but we really can't be 100% sure if an user choose to do strange things.

In that case, I think this new designed project deletion, might help (to an extend). 

I don't like an empty left directory on my system either. In that case, we can this following solution seems to best fit:

> Solution 1, but delete the root project directory if it is empty.

What do you think, @piotrzarzycki21 ?

**Comment by piotrzarzycki21** [comment]
I was always surprised that Moonshine is deleting whole project. I'm using IDE (Intellij) which absolutely do no delete source files. Imagine that you have really important old project, not stored anywhere and you do Delete. 
If current solution remove only Moonshine project related files - I'm fine with that. 
I had only strong comments to the code which seems to be not applied and I do have more.

**Comment by piotrzarzycki21** [comment]
I can say even more in Intellij even project files are not deleted. Each project is a "Module" in that IDE. Once you make Delete - IDE is asking you whether Module should be removed from the list. After delete you are seeing only such files:

![image](https://user-images.githubusercontent.com/24554795/39169013-56ba86be-4796-11e8-98a6-9ca802d16ef4.png)

Of course all the source code is still on the hard drive - it's just not visible in IDE. I like our solution more. :)

**Comment by rat-moonshine** [comment]
I do agree there are other IDEs which provide options between 'move to trash' or just remove the reference from their workspace. Like in Flash Builder it ask if we want to delete the files/folders or just remove the reference from its sidebar, or in XCode it asks if we want to remove the file to trash or just reference from the project (against a file). 

The delete project design however we started keeping simplicity in mind. But as we're growing to support many different users' behavior, we're also coming by including different complexities here or there. 

I'm open for suggestion, if we want to support likewise feature to choose between move to trash or just remove/close (however, the latter may only works as 'Close' in Moonshine).

**Comment by rat-moonshine** [comment]
If we are good with the current functionality, then we probably want to release this in next version. Please, re-open if any changes we need.

**Comment by JoelProminic** [comment]
As I use the Project Deletion action more, I find I am dissatisfied with the logic.  Generally what happens for me is:
1. I delete a project
2. Moonshine gives me a prompt to show all of the files that will be deleted
3. I choose to delete all
4. The project is deleted, but old files still remain (i.e. README.md, .svn, etc)

I don't like the combination of the confirmation prompt and the restricted file list - this just looks like a bug after I confirmed that I wanted to delete those files.

I'd prefer to use one of these solutions, compared to the current state:
- Remove the check on file types
- Remove the delete action entirely, and require users to delete the projects from the Finder/File Explorer.

Now that we have SVN and Git support, we could consider checking to see if there were any uncommitted files (for Git, unpushed changes would also be important - I'd need to research how to check this, though).  If unsaved changes were detected, the user should get an additional warning/cancel prompt before any files are deleted.

This is not a high-priority, since the delete action is dangerous and probably not heavily used ouside of our testing.

**Comment by rat-moonshine** [comment]
> This is not a high-priority, since the delete action is dangerous and probably not heavily used ouside of our testing.

I would like to oppose this thought. I personally many a time create small test projects to test different things, and when done I deletes them; This happens. I likes the IDE do this deletion for me as I feel very lazy or uninterested to open explorer, find the project and delete the folder manually. Saying that, I would prefer to have the IDE provide me option to delete the project.

On 'Remove the check of file types' - if that means to remove the current file-selection window during project-deletion, and to notify the user clearly that this will delete the whole project folder; And if they continue after that confirmation - I'm agree to this.

The other option is to keep the current file-selection window, show all the files/folders in the root of the project, pre-select the files those we manages as project-files, user can de/select more files/folders from that folder, and continue.
