### ISSUE TITLE
[Bug] File auto-opening against a project

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#152]
- Create a new desktop project
- After project creation succeeded Moonshine opens its main application file to the editor
- Having the file opened in the editor delete the project from the sidebar
- Project removes from the sidebar, and its file tab closed from the editor
- Create another new desktop project with same name and same project path
- After project creation succeeded Moonshine opens its main application file twice in two different editor - one opened by the regular project creation system, and another opened by the auto-file-open manager pretending that its the same project that opened earlier

Probable resolution: With the deletion of a project, its sidebar history also needs to be removed.

**Comment by piotrzarzycki21** [comment]
Issue is fixed. I had to remove from SharedObject also project files related to the project and project opened tree nodes.

**Comment by atinprominic** [comment]
I tested it and it working perfect.

**Comment by piotrzarzycki21** [comment]
Reopen for push one more change to make sure that removing files from shared object is during project delete only.

**Comment by JoelProminic** [comment]
I retested this for the 1.9.0 release.  This seemed to work properly
