### ISSUE TITLE
Prevent creation of Flex/MXML file in pure ActionScript type of projects

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#153]

**Comment by piotrzarzycki21** [comment]
@rat-moonshine how to recognize whether project is pure AS ?

**Comment by rat-moonshine** [comment]
I just pushed some updates with #135 against this. 

There is a new field added to determine if a project is pure ActionScript or not - `AS3ProjectVO.isActionScriptOnly`.

After inspecting different **Flash Builder** project configurations (between AS3/Flex), I think I added correct field lookout to determine between an AS3 and Flex, and its added to the `FlashBuilderImporter` class.

In case of **.as3proj** generation, I tried to look through the original configuration creations by FlashDevelop project itself. I see the only difference is Flex project containing the following tag where AS3 won't.

```
<intrinsics>		
    <element path="Library\AS3\frameworks\Flex4" />		
</intrinsics>
```

I've updated the project templates and project import codes to determine a pure ActionScript project based on above tag, in future. But so far Moonshine was used to generate its **.as3proj** files without this tag (or basically an empty tag). So, now if user opens any previously created project through Moonshine, chance is that Moonshine will find its `intrinsics` tag empty and marked the project as pure ActionScript.

I have an idea to handle the above situation, though.. I'm trying to implement shortly.

**Comment by rat-moonshine** [comment]
Hopefully the above said situation is handled now.

**Comment by atinprominic** [comment]
I tested it and now its working as expected.

**Comment by JoelProminic** [comment]
I tested this with:
- An Actionscript (AIR) project - I could only create .as files
- A Flex AIR project - I could create both .as and .mxml files
- A Royale project - I could create both .as and .mxml files

I also tried creating packages under the src directory, and these behaved the same way.
