### ISSUE TITLE
Scrollbar in Settings is unresponsive using scroll wheel

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#154]
**Scenario:**
1) Launch main settings or project settings
2) Go to the tab where scrollbar appears
3) Try to use mouse wheel to scroll

**Result:** Scrollbar is not responding. Hover on scrollbar allows for some usage, but it doesn't work very well either.

**Comment by JoelProminic** [comment]
The scrolling works, but the scroll bar movement does not seem smooth and linear, especially in the Settings > General tab.   This is not a high priority fix, but it was distracting in my test.

I also noticed a cutoff issue with Settings > General, which I reported here:  https://github.com/prominic/Moonshine-IDE/issues/160
