### ISSUE TITLE
[Bug] Main source folder management to a project

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#155]
1. Recently, @JoelProminic shown a scenario where he able to create source files - outside of the main source folder location. 

![image](https://user-images.githubusercontent.com/24370870/35577896-a163b6e2-0608-11e8-8f3e-5bafb9b43879.png)

I have tested that Moonshine does restrict source file creations in other folders like, bin-debug, build etc. but somehow tricked to create source file inside a folder where the folder's name starts with the main source folder name, i.e. main source folder name - "src", tricked folder name - "src2", "src3" etc.

2. Also, we need to build the system show clear enough that which folder is the main source folder. Example, there could be multiple folders from same project directory added inside the `project > Settings > Paths > Class Paths`. What if user deletes the main source folder from the entry.

**Comment by rat-moonshine** [comment]
1. Source file creation now restricted to source folder only
2. New icon added to sidebar tree component to point to the source folder against a project

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I like the icon. I did open Hello World Royale project and I see that:

![image](https://user-images.githubusercontent.com/24554795/35610126-75dc0710-0660-11e8-8c08-add0c97d7d8c.png)

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 , above visibility issue should be fix by now. Please, check.

**Comment by piotrzarzycki21** [comment]
Now it's working fine.

**Comment by rat-moonshine** [comment]
There are some other cases where setting up source folder manually are somewhat confusing and logically restricted. For now, I'm closing this issue for 1.9.0 release, we can re-visit this later if found a necessity.
