### ISSUE TITLE
Not working Superclass input in new AS3 file creation

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#157]

**Comment by piotrzarzycki21** [comment]
Popup for new AS3 class creation now contains two inputs:
Superclass and Interfaces.
Popup for new AS3 interface creation have one input to add other interfaces for extend.

**Comment by JoelProminic** [comment]
The new fields seem to work for me.  I had some trouble with the language server reporting errors for the interfaces, but I was able to compile the application normally.
