### ISSUE TITLE
Use SSL for Communication with moonshine-ide.com

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#159]
Moonshine has been calling moonshine-ide.com over HTTP for the updater logic.   moonshine-ide.com is not currently configured with an SSL certificate.

However, it sounds like Apple will require us to change this connection to HTTPS.

From the AIR 28 release:  https://helpx.adobe.com/flash-player/release-note/fp_28_air_28_release_notes.html

>App Transport Security
>With macOS 10.11, Apple has introduced App Transport Security (ATS) which mandates that applications use secure network connections over HTTPS only. Because this is a significant change, Apple has provided applications an override via NSAllowsArbitraryLoads which will allow insecure connections.
>
>
>With AIR SDK 27, all AIR applications built for macOS will automatically have the NSAllowsArbitraryLoads key set as true in their info.plist file. This is a temporary solution. Apple may reject your application during the review process or disable the usage of NSAllowsArbitraryLoads in future OS updates. We recommend using secure network connections over HTTPS in your applications.

From the Apple documentation: https://developer.apple.com/library/content/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html

>    App Transport Security (ATS) enforces best practices in the secure connections between an app and its back end. ATS prevents accidental disclosure, provides secure default behavior, and is easy to adopt; it is also on by default in iOS 9 and OS X v10.11. You should adopt ATS as soon as possible, regardless of whether you’re creating a new app or updating an existing one.
>
>    If you’re developing a new app, you should use HTTPS exclusively. If you have an existing app, you should use HTTPS as much as you can right now, and create a plan for migrating the rest of your app as soon as possible. In addition, your communication through higher-level APIs needs to be encrypted using TLS version 1.2 with forward secrecy. If you try to make a connection that doesn't follow this requirement, an error is thrown. If your app needs to make a request to an insecure domain, you have to specify this domain in your app's Info.plist file.

And here is more detailed Apple documentation:  https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW35

I will talk to Prominic Support to get an SSL certificate created and installed (and ask for a WordPress update at the same time).

**Comment by rat-moonshine** [comment]
I believe Moonshine website/hosting is purchased within a _premium_ type of category from the WordPress.

Generally, WordPress provides 'https' protocol by-default to all its domains. This shall be true for _premium_ type of hosting, too. I'm not really aware of the technicalities, but is the Moonshine website domain purchased from some other vendor and which cause this SSL trouble (?), @JoelProminic .

**Comment by piotrzarzycki21** [comment]
@rat-moonshine please remember switch back urls to https before final release build once this issue will be resolved.

**Comment by JoelProminic** [comment]
@rat-moonshine, at the moment the problem is that the SSL certificate is self-signed.    HTTPS is already enabled, but the self-signed certificate gives scary error messages in modern browsers.  I don't expect any further problems once we get an SSL certificate created.

I talked to the Prominic support staff about getting the certificate created, but I did not get a response back yet.  I expect they are swamped with customer stuff.  I'll keep reminding them about this.

**Comment by piotrzarzycki21** [comment]
Maybe let's wait max one more day, if it is going to take more let's try to push release with http and see whether it will pass App Store etc. Thoughts ?

**Comment by rat-moonshine** [comment]
The build that goes to the App Store do not update check - because App Store version do not updates AIR native way. The build that we distribute off-App-Store that has the check, but this do not falls into reviewer's headache, so we should be good if using 'http' works good.

**Comment by piotrzarzycki21** [comment]
Maybe Talk with Joel Today/Tomorrow and make a release build with all that stuff which we currently have. I still need CHANGELOG review before that build.

**Comment by JoelProminic** [comment]
I confirmed that the SSL certificate has been installed on moonshine-ide.com.

Make sure that NSAllowsArbitraryLoads is excluded or set to false on the MacOS builds, especially the App Store build.  

I'll plan to spend some time with CHANGELOG.md today.

**Comment by rat-moonshine** [comment]
Using 'https' call to the Moonshine website looks good on Windows and macOS and I haven't received any permission alert anymore on the Windows. I'm closing this issue as fixed until any problem found.

**Comment by labcerouno** [comment]
When opening Moonsine 1.9.0 on macOS High Sierra, it throws: The SSL certificate for this site is invalid. If I click Continue, it goes fine. If I click Cancel, it shows: Error downloading update file, try again later.
![moonshot](https://user-images.githubusercontent.com/2539666/36116061-c5f337f2-1013-11e8-86a1-a99bbb8977c2.png)

**Comment by JoelProminic** [comment]
Thanks for reporting this, @labcerouno.

It looks like this is the expected certificate for this site:
![image](https://user-images.githubusercontent.com/24532731/36119815-cba3a090-1006-11e8-9ea3-33d3cca9b15b.png)

My browser considers this certificate to be valid.  It looks like the above system does not recognize one of the intermediate certificates.  

@rat-moonshine , @piotrzarzycki21 , do you see the above error?

**Comment by piotrzarzycki21** [comment]
I'm not sure how to open such Page Info, but in Safari I see something like this:

![image](https://user-images.githubusercontent.com/24554795/36120443-7e9260d8-1043-11e8-9523-c768a171995e.png)

I just updated Moonshine on my mac and I didn't get certificate error. Can it be in somehow problem with OSX language ?

**Comment by rat-moonshine** [comment]
@labcerouno is the permission alert coming everytime you start Moonshine?

**Comment by labcerouno** [comment]
Hi @rat-moonshine . Yes, everytime I start Moonshine until yesterday. Now it has gone... The dialog wont' appear anymore... No clue... Thank's anyway.

**Comment by rat-moonshine** [comment]
@labcerouno thanks for reporting this, not very immediate but I also start getting similar error recently.

@JoelProminic , I'm not sure if this related to my country/ISP, but recently I have started getting this error while working locally:
![screenshot](https://user-images.githubusercontent.com/24370870/36203026-0c86c460-11ac-11e8-93fd-229e06a4c619.png)

Do you have any idea on this (?)

**Comment by JoelProminic** [comment]
I think this page describes the problem we are seeing:
https://support.apple.com/kb/PH25443?locale=en_US&viewlocale=en_US

So, the certificate authority's root certificate (GeoTrust RSA CA 2018) is not currently trusted by your Mac.  @rat-moonshine, please try to verify this in KeyChain before you follow the instructions in the above link.

I find it very strange that this root certificate is not automatically recognized as a certificate authority - maybe this is not a common certificate authority.   I am also surprised that the process to resolve the error is so complicated - I would not expect this process to be comfortable for a normal user.

**Comment by rat-moonshine** [comment]
I'm  not sure either why I had this error in a sudden day and now there it is no more. I'm not having this error anymore while running Moonshine. 

@JoelProminic , while I looked into mac keychain, I found this (seems all valid)!
![screenshot](https://user-images.githubusercontent.com/24370870/36293813-24ca6584-1302-11e8-9254-7be0f381a6a8.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine can we close it if it's no longer occurs ?

**Comment by rat-moonshine** [comment]
I haven't seen anymore problem related to this for a long time; so this can be closed unless we face issue related to this again.
