### ISSUE TITLE
General Settings Panel Cutoff in Default Resolution

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#160]
I noticed that the General panel in the Moonshine Preferences are cut off when using the default resolution.

![image](https://user-images.githubusercontent.com/24532731/35758794-57454816-083b-11e8-991b-2a68a2d53df5.png)

Also note that the bottom of the scrollbar is covered by the Save/Cancel button bar

This triggered for both MacOS and Windows.    I can also reproduce it with the full resolution by increasing the height of the console until  a scroll bar appears in the Settings panel

**Comment by piotrzarzycki21** [comment]
I have fixed that. Since we are waiting for https issue to resolve it can also be in the 1.9.0.
