### ISSUE TITLE
Maven Build for vscode-nextgenas_MoonshineModifications

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#161]
From:  #77 

@joshtynjala:
>@piotrzarzycki21 Ah yes, here's another situation where it would be nice if Moonshine built codecompletion.jar with Maven instead of ant. The dependencies have changed in the royale branch, so that means that if you want to build codecompletion.jar from this branch, you'll also need to manually update the JARs used as dependencies.

@piotrzarzycki21:
> This part is being build by ant just for the consistency with the rest part of the builds in Moonshine ? If there is no technical contraindications I will spend some time to prepare pom which is building codecompletion.jar by Maven. Maybe it will not be used by Bamboo, but at least we could avoid such problems. I can take a look as a starting point in your poms.

@joshtynjala
>The Ant build was created before I started contributing to Moonshine, so I can't really say the reason why it is used. My original build script for the language server used Ant and Ivy. Ivy can resolve dependencies for Ant from the same sources as Maven. As far as I know, that build script was never used. Instead, someone copied the dependency JARs into the repository, and they've been manually updated as needed.

We used Ant because it was more familiar to us.  I have rarely used Maven.

I can easily update the Bamboo build process to use a Maven script instead of an Ant script for codecompletion.jar, but I would need some help getting the Maven configuration set up for the vscode-nextgenas_MoonshineModifications project.

**Comment by joshtynjala** [comment]
I'm going to close this one because it's not relevant anymore. We update the as3mxml language server and all of its dependencies from official releases now, instead of building it manually.

Related instructions:

https://github.com/prominic/Moonshine-IDE/wiki/Updating-the-bundled-language-servers
