### ISSUE TITLE
Introduction of Hide/Un-hide option in macOS menu

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#162]
As a continuation of #151 reported by @fde101, here's on feature request to the macOS application menu:

> I also just noticed the the options to hide the application / hide others are missing from the application menu under Mac OS X.
> 
> Those menu items are described here: https://developer.apple.com/macos/human-interface-guidelines/menus/menu-bar-menus/
> 
> The "Hide" option is present in the Dock menu at least, so that helps.

This might force us to use some shell script to meet this feature, I'm not sure if we can pass the usage successfully through Apple reviewers though, at this moment. We need to look into that.

**Comment by JoelProminic** [comment]
I think there should be actions defined for Hide and Hide Others in XCode, but I don't know if it will be available.

If we have to implement these actions ourselves and convince Apple to allow us to run actions like this, then this feature will take a lot more time...

**Comment by rat-moonshine** [comment]
We can not use XCode object to build our native menu; the objects will be different and their command stamp (they shall different during type conversion in ActionScript).

I took another path, to get and extract from the default macOS menu that generates before we generates our custom menu. Following 3 menu options now extracted from the default application menu and updated to Moonshine custom menu:
- Hide Moonshine
- Hide Others
- Show All 
Tested working good in packaging, too. 

Please, check. Shall be released with next Moonshine release.
