### ISSUE TITLE
DropdownList background colour problem

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#163]
@piotrzarzycki21 , it looks like the last fix to the DropdownList component didn't fixed all, this is a screenshot taken in macOS run, please, check. 

![transparent](https://user-images.githubusercontent.com/24370870/35792232-189267be-0a72-11e8-95d4-ce8b16b0a3eb.png)

In above, I see the background to the DropdownList is transparent but opaque.

**Comment by rat-moonshine** [comment]
I also see dark opaque background to the template type dropdown, when I tried to create a new Library Project.

**Comment by piotrzarzycki21** [comment]
Yep I see it also! I'm on it! Fix is on the way! :)

**Comment by piotrzarzycki21** [comment]
I have added background color to the settings in following places:

- Creation of new library project
- In the settings of Mobile project
- Creation project from sources 

I hope I didn't miss anything. Thanks for the report!
