### ISSUE TITLE
Prepare Visual Editor for PrimeFaces components

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#165]
As part of this task I will be working on preparing [Visual Editor](https://github.com/prominic/MockupVisualEditor) to handle [Prime Faces](https://www.primefaces.org/) components.

- [x] Change folder structure in order to have place for PrimeFaces components (Visual Editor)
- [x] Change logic which easily translates code to PrimeFaces html (Visual Editor)
- [x] Create Main window (Div) and PrimeFaces Button as first component
- [x] Implement logic responsible for creation of new PrimeFaces type of project (Moonshine)
- [x] Implement logic responsible for creation of new files in PrimeFaces project (Moonshine) 
- [x] Editor should recognize *.xhtml files and colorize them (Moonshine)
- [x] Fix UI of Property Editor (Visual Editor) (separate issue: #191)
- [x] Export Visual Editor Project to PrimeFaces

**Comment by rat-moonshine** [comment]
As per our initial discussions with Andrii, here are few suggested components that should be part of the initial component editor to PrimeFace template:

> The sample JSF page that you've provided, based on that, we can start working on the following components (as a start):
> 
> - h:PanelGroup
> - p:InputText
> - p:OutputLabel
> - p:CommandButton
> - Div

As for the 'Div' component here are the thoughts from @piotrzarzycki21 ,

> As for the list of component - Div is an HTML component we don't care about that - It can be added behind the stage to something, but shouldn't be part of the UI of editor. 
> 
> For example h:PanelGroup - without any additional set of attributes probably will be equal to Div - If I understand correctly.

Here are the thought from me against above,

> Piotr, we might need "DIV" component, too. I don't think we should need to be worry about whether a DIV or PanelGroup renders as a DIV only when run inside a browser, but the mockup editor should produce codes with the reference of DIV or PanelGroup only. (Andrii, please correct me if I'm thinking the other way)
> 
> So, we can introduce a Container type of component with a dropdown to choose between DIV or PanelGroup or other such kind of containers, Piotr (as we can choose between Group, VBox, HBox etc. against the Container in current mockup editor). Changing the container type  through the dropdown shall update the property fields as well. Therefore, user can add them per their own requirement to the stage.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Thanks for the investigation. First of all there is no such thing like x and y in HTML. You can make following CSS:
```
div {
   position: absolute;
    left: 100px;
    top: 150px;
}
```

Than you may a bit think about left and top as it is x and y, but it is still not the same. We have currently [discussion in Royale](http://apache-royale-development.20373.n8.nabble.com/What-is-x-and-y-What-is-width-and-height-td2341.html) how to implement real x and y for the framework. - Maybe PrimeFaces have such thing.

Here is my explanation why I'm thinking that pure HTML components shouldn't appear in our editor. Let's say that you will put there Div - simple container. 
For that component you will need to give users some pure HTML options to manipulate those one - The question is Which one you would like to add ?
Which one is important ? Let's say that you will add  for users "position", "display" and "left", "right" etc. Are you able to predict how those div will behave if user put it in the following structure (pseudo code):

```
<div position="absolute"> 
    <div position="relative">
          <div position="absolute"> </div> - What has happen with that one in the Browser X  ?
    </div>
</div>
```

Different situation is with framework components - **You know how they work!!  We know how to simulate behavior of component X, because it's described in the documentation and internal framework mechanism take care of that.** 

Another thing is I don't see in PrimeFaces list of components h:PanelGroup, it means that also it shouldn't be in our interests. If someone come to our VE and wanted to build some layout he should go the [Panel](https://www.primefaces.org/showcase/) and use all of those components. - Not HTML one.

I believe that our direction is not building Editor for HTML, but building editor for PrimeFaces, so no native controls there.

Thoughts?

**Comment by rat-moonshine** [comment]
I agree that supporting varied HTML properties may not be possible at this stage. My thought process has started from where an usual PrimeFace user comes from. They used to work in PrimeFace (let's say), they practiced to manipulate and see layout in the manner they use to see in PrimeFace. 

So, when they shall wants to work the same thing inside Moonshine, they surely wanted some similarities between the way of doing things. Again, there is absolutely no way to debate that we can't support every other HTML properties inside the Moonshine editor. 

Being said that, it's probably more safe way to work with Flex SDK components and somehow translate the codes to valid and logical PrimeFace codes. Keeping ourselves in the existing x/y component hierarchy, I didn't found a way out, though. It could have overlapping problem, resizing problem etc. I thought, perhaps, we can restrict some of the current behavior, i.e. stopping x/y may overcome overlapping issue, and we may restrict the sizing by input field, like in pixels or percentage. 

`h:PanelGroup` I think Andrii did mentioned is not a native-PrimeFace component. I included that because I have seen its usage in his usual design. However, the PrimeFace native component also has enough containers, so I don't see any problem if we cut-down non-PrimeFace API reference. 

In either way, if you have a good way out to use Flex SDK component along with x/y co-ordinates and somehow able to translate logical PrimeFace codes (that sound valid to HTML output), my mind is also open to hear that, too! In any way, we need an editor that also not make PrimeFace users feel castaway. Definitely, I don't want a development that ruin our life as well by re-inventing the wheel :P

**Comment by piotrzarzycki21** [comment]
I did small reorganization in Visual Editor package structure. I have pushed those changes to the master, because we won't have any conflicts if in prime faces branch and master folder structure will the same. In case of any fixes it shouldn't be to much problems with merging. 
Changes:
- Folders propertyEditors and surfaceComponents has been moved to new folder "flex"
- New folder "interfaces" has been created to store all interfaces related to components
- component and skins folders has been introduceds in flex/surfaceComponents
- all skins related to components displayed for the user has been moved to view/flex/surfaceComponents/skins

![image](https://user-images.githubusercontent.com/24554795/35975005-863c26cc-0cdb-11e8-897f-7c2dfa0cfd70.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I analyzed a bit FlowBox and I think it can be our base container. I mean this could be container where user will be dropping controls. - Later it will be translated to Div where those control is being dropped.

<div>
   //here controls which will be translated to PrimeFaces
</div>

Now I need to configure some pure PrimeFaces project to make more experiments with UI and later will start implement something in our Visual Editor.

Many Thanks for your analysis it was really helpful! We will see where it will end up. :)

**Comment by rat-moonshine** [comment]
I'm glad that it able to make your life easier, @piotrzarzycki21 . Yes, that was the basic idea to make the FlowBox container as the base component/container (where with or without Div usage, HTML lays its children the same way).

Thank you!

**Comment by piotrzarzycki21** [comment]
I'm progressing with this task and come up with some thought. Probably we don't need FlowBox. If you look into the implementation it just extends [Box](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/mx/containers/Box.html) component from Flex 3. Setting orientation to "horizontal" for Box it is the same as using HGroup and VGroup accordingly. 
Probably we don't need library at all. 

I'm pretty close to finish:
1) Creation of new project
2) Reopen existing
3) Drag/Drop PrimeFaces Button - if I achieve this one we will be able to work together.

**Comment by rat-moonshine** [comment]
I maybe a little worry about using _TileLayout_ as the base component (i.e. Div etc.)

Per HTML UI rule, adding Div/Container, Table, tab-view etc. we do need to be them as a new row, and they should acquire 100% width to that row - Unless user choose to change its `display=inline` (_display=inline_ should render the component to available column).

I'd suggest, @piotrzarzycki21 , before going further with this base TileLayout class, investigate can we -
1. Change any given component's position to a new row and no other/next component to be added in that row
2. Change back the given component's position from row to column (display=inline)

Table, tab-view, Div etc. should automatically render as **_1_** mentioned above.

**Comment by piotrzarzycki21** [comment]
There is possibility that both options is something which we will have achieve in a custom TileLayout.

Whatever container you are going to create Grid, Table etc. It will be separate class which may extend our Container (TileLayout). Then it depends if TileLayout is capable mimic what you are saying (We will see and check) we will setup appropriate properties and make skin.

If not probably we will have to extend TileLayout and make our own implementation.

Really do not expect that everything what is in flex should give you an answer and mimic html/primefaces. Expect rather that you will have to write your own custom component.

FlowBox extends Box - documentation is saying that you should use HGroup, VGroup or BorderContainer and let's stick with that. No Flex 3 component if we don't have to.

**Comment by rat-moonshine** [comment]
Yes, that was the idea for having a base class or container type, which shall be use for every component which may represent a holder/div in HTML (basically where one can drag/drop other components).

Certainly we can't get the behavior I said from the base API of TileLayout - by looking into I meant about finding a way extending the used component only (TileLayout). 

Personally, I'm not a big fan of old version API either (Flex 3), also I don't know about 'if' performance difference issue between Box and HGroup or VGroup or anything, or its just an encouragement to use new API. Either way, if Flex 4 component do not provides us the flexibility without spending long time, then its here. Surely we don't want to reinvent the wheel.

**Comment by rat-moonshine** [comment]
By the way, while looking into the TileLayout API, it seems it distributes its row/columns in equally sized cells (https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/spark/layouts/TileLayout.html):

> The TileLayout class arranges layout elements in columns and rows of equally-sized cells. The TileLayout class uses a number of properties that control orientation, count, size, gap and justification of the columns and the rows as well as element alignment within the cells.

In our case the cells shall be variable, based on individual components' width. While looking into the APIs (TileLayout, TileGroup etc.), I came through this article - http://evtimmy.com/2009/06/flowlayout-a-spark-custom-layout-example/ (which uses the 'layout' way in Spark controls but something that tile layout with variable widths), and maybe, this can be easy for further customisation, too!

I gave a try in Moonshine IDE, and here's the basic example which they provided, and top of that I used the custom layout API inside a Spark Group, that worked too! 

You can give a look, @piotrzarzycki21 . Here's the source -
[flowtestpropsandscrolling2.zip](https://github.com/prominic/Moonshine-IDE/files/1753262/flowtestpropsandscrolling2.zip)

**Comment by piotrzarzycki21** [comment]
All the steps are ready. I'm moving forward to fix UI Property Editor.
