### ISSUE TITLE
Create new type of template project which will be used as Visual Editor - PrimeFaces

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#166]
Template should be created in templates folder.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine please analyze template from Andrii and create absolutely minimum. I will consume it in Visual Editor.

**Comment by piotrzarzycki21** [comment]
Task should be done in branch: features/visual_editor_prime_faces - I will create it after release 1.9.0

**Comment by rat-moonshine** [comment]
I'm not sure what you meant by minimum template requirement based on Andrii's .shtml project zip. Did you meant to create another clone of Visual Editor Project named something by PrimeFace? If I'm not wrong, structure-wise this shouldn't be different from the Visual Editor Project but with different language parsing, and different type of UI editor in place. 

Perhaps, we can provide a _type_ dropdown in project creation dialog against Visual Editor Project to choose between PrimeFace targeted or Flex. 

But anyway, let me know clearly what was your actual plan by creating minimum project template for PrimeFace. Do you have any plan already settled for the UI editor, too?

**Comment by piotrzarzycki21** [comment]
By that task I meant to have similar template like [this one](https://github.com/prominic/Moonshine-IDE/tree/master/ide/MoonshineSharedCore/src/elements/templates/projects/Visual%20Editor%20Project%20(Flex)/src) - Of course separate folder.

We don't need to go as part of that task so far by creating new type of project, but if you want to prepare this one make it so. - It is good idea have one generic project with DropDownList. - If you start create new type of project - You don't have to open Visual Editor for now - It would be enough if you open New main fail and we will see there PrimeFaces XML.

I will write separately about UI editor. There is a lot of preparation there I think so, before you jump into it and we will start work together.

**Comment by rat-moonshine** [comment]
I think it'd be more handy to have a dropdown in Visual Editor Project creation dialog to choose between PrimeFace and Flex. I shall create necessary folder/files for the purpose, and link them through project creation codes. 

A minimum of template file having following codes should be Okay?
```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>$projectName</title>
    </h:head>
    <h:body>

    </h:body>
</html>
```

**Comment by piotrzarzycki21** [comment]
I have no idea, because I didn't go to far with PrimeFaces. It looks good to me as a starting point. Lest's keep code in the separate branch. Create one as I suggested above if you are going to start working on that now.

**Comment by piotrzarzycki21** [comment]
I have created and pushed branches features/visual_editor_prime_faces in the [Moonshine](https://github.com/prominic/Moonshine-IDE/tree/features/visual_editor_prime_faces) repository and [Visual Editor](https://github.com/prominic/MockupVisualEditor/tree/features/visual_editor_prime_faces).

**Comment by rat-moonshine** [comment]
- New type dropdown added into Visual Editor Project creation dialog, to choose between Flex and PrimeFace type
- Added initial template files against PrimeFace type of project - main file extension set as _.shtml_

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I will merge master to that branch, so make sure that you are pull before the commit.

**Comment by rat-moonshine** [comment]
I think I able to successfully commit requisite template changes this time. @piotrzarzycki21 please, have a look.

**Comment by rat-moonshine** [comment]
By the way, "Visual Editor Project (Flex)" template now renamed to "Visual Editor Project".

**Comment by piotrzarzycki21** [comment]
I think it is enough what I got from you. I'm closing that one.
