### ISSUE TITLE
Highlight words/lines which are matched in the results of Global Search

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#169]
I see following options for that task. First one I think is a must have, but the second one not necassery.
1) Highlight the words/lines in opened file
2) Present lines which has been found as part of the Search window.

**Comment by rat-moonshine** [comment]
First draft commits highlights all instances to a file.

Known issue: This needs to deal when there are more than one instance of a search string in a single line.

**Comment by piotrzarzycki21** [comment]
I just look into that and one suggestion is, that selection color could be a bit more visible. Maybe should be done as it is in Replace ?

**Comment by rat-moonshine** [comment]
Are you pointing to this dark colour of selection?
![screenshot](https://user-images.githubusercontent.com/24370870/36096770-c34b8eb4-101d-11e8-9fd4-e9152a7f420c.png)

**Comment by piotrzarzycki21** [comment]
Rather to that pink color or even this yellow one. When I saw current selection for founded items I didn't notice it at the first time.

**Comment by rat-moonshine** [comment]
@JoelProminic reported an issue where he couldn't able to drag-select contents withing <fx:Script> tag, and same to the <s:WindowedApplication> tag. However, testing on Windows I couldn't able to reproduce the problem, macOS test is awaiting.

While testing above another issue come up with double-click selection to a word. While doing double-click on a word, the cursor seems moved to the word's end, also doing a keyboard copy seems copying to word properly to the clipboard but the selection. We noticed this is something introduced with today's changes, as 1.9.0 do not has this problem.

**Comment by rat-moonshine** [comment]
Fix:
- Double-click selection issue has been resolved

Updates:
- Multiple search instances in same line now highlights as well
- As @JoelProminic pointed, the purple colour in replace/review selection was quite deep, the colour has been toned down
- The same toned down purple colour is also using marking the selection against this issue as well (I found using purple is more clear over yellow)

As a separate incident, while working on the 'search in project' result listing, I found double-clicking on empty space area to the tree component, or to a folder item, Moonshine was throwing null pointer error. This has been fixed, as well.

**Comment by rat-moonshine** [comment]
> Present lines which has been found as part of the Search window.

By above, @piotrzarzycki21 did you meant this?
![34250730-02dbb810-e63e-11e7-8b90-281145ef3cdd](https://user-images.githubusercontent.com/24370870/36137659-3a305192-10bc-11e8-8091-b281600bba50.png)

**Comment by piotrzarzycki21** [comment]
Yes it would be great to have that in following way. Is it possible for you ?

**Comment by rat-moonshine** [comment]
As you also agreed, I would like to keep this in lower priority (considering other tasks/issues). Please, raise a separate enhancement issue as this would be a development on its own.

**Comment by piotrzarzycki21** [comment]
Ok I will do this.

**Comment by rat-moonshine** [comment]
I'm closing this as resolved, please reopen if any bug found.

**Comment by JoelProminic** [comment]
I'm a little concerned about how the search highlighting looks with the string literals:
![image](https://user-images.githubusercontent.com/24532731/36162759-f1ec16c8-10ac-11e8-8806-281c01bde951.png)

This is readable for me, but there is not a lot of contrast.  Does this look fine to the rest of you?
