### ISSUE TITLE
Deleted project is not removed from the section "Recent" of Home tab

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#172]
**Scenario:**
1) Create project
2) Close it and reopen
3) Delete project

**Results:** Project is still visible in the "Recent" section

**Comment by rat-moonshine** [comment]
Deletion of project now removes its entry from the splash screen.

**Comment by JoelProminic** [comment]
I confirmed that the project is removed from the RECENT section.  I also confirmed the behavior when the deleted project was not the most recent project in this list..

However, the files associated with the project were not removed from the RECENT list.  Trying to open the files gives an error "Can't import:  The file does not exist anymore."

**Comment by rat-moonshine** [comment]
Recently opened file list now updates upon a project deletion, as well.

**Comment by JoelProminic** [comment]
I tested the Recent File logic with multiple files, positioned in the middle of the RECENT list.  All of the files were removed.

I also checked the remaining recent file links, and they worked properly.
