### ISSUE TITLE
After "Reset to Default" one SDK is not removed from the list in "Select SDK" popup

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#174]
**Scenario:** 
1) Add two or more SDK in the main Settings
2) Save Settings
3) Perform "Reset to Default"
4) Open "Select SDK" popup

**Result:** One SDK left intact, once we select it and restart Moonshine we will be prompt to add new SDK, because current path is corrupted. 

![image](https://user-images.githubusercontent.com/24554795/35931435-e9d9cdb2-0c34-11e8-9cf2-bdcb0e1b0c88.png)

**Comment by rat-moonshine** [comment]
Fixed:
- Now SDK list is properly cleaned after a 'reset to default' event 
- However, SDKs those downloaded by Moonshine App Store Helper in macOS (and auto-detects by Moonshine during startup), do not removes in this process
