### ISSUE TITLE
Wrong name of the confirmation button in "New Folder/File" popup

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#179]
Name of the confirmation button in case of "New Folder/File" etc. popups should be different. Currently we have **Change**, but it should be **Create**

![image](https://user-images.githubusercontent.com/24554795/36013688-0971e02e-0d66-11e8-83aa-fdeb87b46951.png)

**Comment by JoelProminic** [comment]
I confirmed this for both new folders and files.   I can't think of any interfaces that would still need to use the "Change" label.
