### ISSUE TITLE
Can't change Platform from Web to Android

### ISSUE THREAD

**Issue by labcerouno** [prominic/Moonshine-IDE#181]
First of all: great work! Congratulations!!!

The issue: I need to import a folder containing a FlashDevelop project to Moonshine as a Feathers Mobile Project. Everything seems fine, except by the Project Settings Dialog, Category “Run”, where I can't change Platform from Web to Android/iOS. I noticed that if I create a new Feathers Mobile Project in Moonshine, a directory called build is created and some settings changed. I have copied build directory to the FlashDevelop project folder. Also, I added +configname=airmobile in Additional compiler options and build.xml path in Ant Build File. The SDK is also set equally: Feathers SDK 3.4.1 FP 28 AIR 28. 

Thank you very much.

**Comment by piotrzarzycki21** [comment]
Hi @labcerouno ,

Thanks! Just wanted to clarify, so the issue here for you is that you couldn't change after import type of the project, but after creation of new project and copy things there everything is all right ?

Thanks for trying Moonshine!
Piotr

**Comment by piotrzarzycki21** [comment]
@rat-moonshine if you could look into that, you are a bit closer than me in case of that part of the project.

**Comment by labcerouno** [comment]
Actually I tried the opposite. I copied all different files from the new project made in Moonshine to the imported project from FD. I mean, the ones I thought could affect the project config. The ones with the code I didn't copy. The result was that the platform combo box in Project Setting won't show any other option than Web. I'll try what you said and tell you the result. Thank you for the fast response! Regards

**Comment by rat-moonshine** [comment]
@labcerouno thanks for reporting this. 

Moonshine does uses an extended .as3proj than original FlashDevelop project configuration file. However, we would love to check where it is making difference (comparing to the original FlashDevelop file you has). Is it possible for you to share the .as3proj file with us?

Thanks!

**Comment by piotrzarzycki21** [comment]
@labcerouno if you don't want to share it public we can provide you email address etc. Just let us know!

**Comment by labcerouno** [comment]
Let's do it the right way!!!

No config seems to give the ability to change Platform field from Web to Android or iOS in Project Settings.

#### Issue
Opening a project folder made in FlashDevelop creates a project which output platform is Web. This option can't be changed. I added +configname=airmobile in Additional Compiler Options and copied the entire build directory from a new mobile project made in Moonshine, but Platform combo only shows "Web".

#### Expected Behavior
There should be always the option to change output platform from Web to Android, iOS, Desktop or tvOS (!).

#### Actual Behavior
The only option is Web. If I create a new mobile project, I have two options: Android and iOS. But this case is an imported project from another IDE (FlashDevelop).

#### Steps to Reproduce
1. Open Moonshine IDE
2. In Home tab, choose Open Apache Flex/JS Project
3. Find project folder and add it
4. Right click in Project Name - Settings
5. In "Run" category, platform field has only one option

#### Context
It won't allow to import mobile projects coded in another IDE to Moonshine. It should be high priority, since we are working with a mature technology (AS3 and AIR) and coders must have years of code to import.

#### Your Environment
* Moonshine Version used: 1.9.0
* SDK: Feathers 3.4.1, FP 28 AIR 28
* Operating System and version: macOS High Sierra

**Comment by labcerouno** [comment]
Sure, I can share it. 
[as3proj.zip](https://github.com/prominic/Moonshine-IDE/files/1716296/as3proj.zip)

**Comment by rat-moonshine** [comment]
@labcerouno Thank you for supplying the test .as3proj file, and we agree with you that project created with another IDE should open properly in Moonshine as well.

However, when I looked into the .as3proj file I noticed some oddity. 

A regular FlashDevelop created .as3proj file do not provides many information like if it's mobile, whether it should run as Android or iOS, and therefore on which device type (i.e. tablet, phone, versions etc.), certification information etc.

The .as3proj file that you've provided did not created originally by FlashDevelop. To have the above information available to the Moonshine, Moonshine adds these extended tags/information which reflects to a project's 'Run' section:
```
<moonshineRunCustomization>
    <option projectType="3"/>
    <option deviceSimulator="null"/>
    <option launchMethod="Simulator"/>
    <option targetPlatform="4"/>
    <option urlToLaunch="/Users/elder/Dropbox/RioSeguroApp/RioSeguro1.4.x/bin-debug/RioSeguro2.html"/>
    <deviceSimulator>null</deviceSimulator>
    <certAndroid>null</certAndroid>
    <certIos>null</certIos>
    <certIosProvisioning>null</certIosProvisioning>
</moonshineRunCustomization>
```
The above type numbers, and different values tells Moonshine to prepare Run section considering a web project but mobile. If you can take a look any originally created mobile project through Moonshine, you shall see the said tags has different values. Perhaps, you want to provide those mobile specific tag/information to your project configuration file, `+configname=airmobile` etc. and then give a try (?)

On a separate note, I noticed that you've added .ane files to the project's Settings/Paths/Library section as well. You may want to consider them to Settings/Paths/Native-Extension section instead.

**Comment by labcerouno** [comment]
Thank's @rat-moonshine . I guess this as3proj file has passed through many IDEs while testing an alternative to FlashDevelop. I thought I would find an intact file, but I guess this was not the right example. This another one, I'm sure by the modification date, it was generated by FlashDevelop:

[as3proj_2.zip](https://github.com/prominic/Moonshine-IDE/files/1721868/as3proj_2.zip)

Inside this one, I found: 
`<movie platform="AIR Mobile" />`

This is the attribute that will target to mobile dev in FlashDevelop. For choosing between Android or iOS, I would have to run a .bat file and take the right option.

If I try to import this project folder to Moonshine, it happens the same: in _Settings - Run_, there is only Web platform as an option. No Android or iOS.

I tried adding the tags you showed me above inside this as3proj. I changed _projectType_ and _targetPlatform_ according to your example, but no change. I even copied the same tags from a project made entirely in Moonshine which Platform field was set as I wanted: Android. The values for the attributes _projectType_ and _targetPlatform_ in that project were both 3. But in this imported project, if I set them to 3, nothing would change.

About the .ane files, as I remember, I added only the directories. The thing is that I keep ANE and SWC under the same directory. Would it be a problem?

**Comment by rat-moonshine** [comment]
@labcerouno thank you for pointing to the tag that manage by FlashDevelop to differentiate between type of projects, `platform`. When I looked through the configuration file created by Moonshine, I found Moonshine do not manage this tag (for some reason). 

Moonshine has other ways to determine a project whether its AIR or AIR/Mobile to keep the codes similarly used between FlashDevelop or Flash Builder project configuration file. 

However, I'm afraid because of any former decision taken (by Moonshine), later decisions may affected during a project load against the project type/type-of-Run etc. However, the tag might help Moonshine to determine between project types further - `platform`. We can work on this. Thank you!

Regarding SWC and ANE paths, as you may already know that during compilation they has different commands to make them in use. Paths mentioned under "Projects/Settings/Paths/Native Extension" has a whole lot of process to make the ANE run-able with the desktop simulator. I'm afraid passing the ANE paths within the 'Library' field wouldn't make them in use, actually.

**Comment by rat-moonshine** [comment]
I've added the `platform` tag mapping to determine between AIR/mobile/default. The new tag processing shall get precedence over existing others. Planned for the next release.

**Comment by labcerouno** [comment]
OMG I always thought desktop simulator didn't support ANEs. That was because of my mistake of putting them in the same folders as SWCs!! Thank you!

**Comment by rat-moonshine** [comment]
On ANE part, running ANE on desktop simulator needs more works than passing the paths to the compiler. I think Moonshine is the only IDE available at this moment which support this feature fully automated, user just needs to point the ANEs.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine did we finish with that issue ?

**Comment by rat-moonshine** [comment]
Some measure have taken, so let's push this to the next release (as mentioned), and then see how users test the cases, @piotrzarzycki21 .
