### ISSUE TITLE
Project description mentions FlexJS

### ISSUE THREAD

**Issue by Harbs** [prominic/Moonshine-IDE#182]
You might want to update the references to Royale, now that it's supported.

**Comment by piotrzarzycki21** [comment]
@Harbs apart of README, do you see something more ? 

I will update the README! Thank you!

**Comment by Harbs** [comment]
The description at the top of the repo as well:

> Moonshine is a free and open source middleweight IDE built with ActionScript 3 for ActionScript 3, Apache Flex®, Apache FlexJS® and Feathers development with Cloud and Desktop support. http://moonshine-ide.com/

**Comment by piotrzarzycki21** [comment]
@JoelProminic could you please update top description on GitHub. I don't have edit options for that.

> Moonshine is a free and open source middleweight IDE built with ActionScript 3 for AS3, Apache Flex®, Apache FlexJS®, Apache Royale® and Feathers development with Cloud and Desktop support.

Thanks!

**Comment by piotrzarzycki21** [comment]
Just for the note to myself. FlexJS references was removed App Store description. 
I will remove the rest one before 1.12.0.

**Comment by piotrzarzycki21** [comment]
@JoelProminic could you please remove FlexJS from the GitHub description along with the tag #flexjs.
Can we have also there following tags: #moonshineide #actionscript #apacheflex #apacheroyale #feathers #adobeair #cloud-support #ide

**Comment by JoelProminic** [comment]
I updated the GitHub descriptions and tags.  I did not remove the shorter versions of the tags that you listed above (i.e. #air, #flex, etc.

As for backwards compatibility, I don't want us to spend a lot of effort with this, but if there is something easy that we can support to offer some backwards compatibility, that would be nice.

For example, we might want to allow the user to open an old FlexJS project as Royale, and configure a FlexJS SDK instead of a Royale SDK (since I think these are mostly interchangeable for the last version of FlexJS).   Let me know if that is not as straightforward as I think.

**Comment by piotrzarzycki21** [comment]
Thanks! I think I'm done with changes in IDE. User still will be able to open FlexJS projects, but not create new one.
The only thing which is still to do is changing screenshot on the website, but I think I will do that once we will be closer to the next release.

**Comment by piotrzarzycki21** [comment]
I just finished updating sceenshot on website. I'm done here. If I missed anything please let me know.

**Comment by atingupta2005** [comment]
It seems that the modified description text as below is not updated on all 3 locations.

**Modified Text:**
Moonshine is a free and open source middleweight IDE built with ActionScript 3 for AS3, Apache Flex®, Apache FlexJS®, Apache Royale® and Feathers development with Cloud and Desktop support.

**Locations:**
**Location 1.**
On Website - http://moonshine-ide.com
Status: Modified. Refer to attached screenshot below:

![screen shot 2018-05-23 at 9 59 07 am](https://user-images.githubusercontent.com/3568735/40403587-668e67ea-5e70-11e8-87af-b795b0f551a3.png)

**Location 2. and Location 3.**
On Github Readme and Github Header
Status: Not modified. Refer to attached screenshot below:

![screen shot 2018-05-23 at 9 58 49 am](https://user-images.githubusercontent.com/3568735/40403557-3cabcf6c-5e70-11e8-80d3-fb727812a9c2.png)


Please suggest if I am doing any wrong testing.

**Comment by piotrzarzycki21** [comment]
@atingupta2005 on your screenshot I don't see any mention about FlexJS. Where are you seeing it ? The goal was to remove all FlexJS references.

**Comment by atingupta2005** [comment]
I wrongly understood the requirement. Now its clear to me and I found that its as expected. Please ignore my previous comment
