### ISSUE TITLE
Input field style problem

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#186]
1. Open Moonshine/Settings/Templating
2. Create a new custom file template
3. Try to rename the file in list

![screenshot](https://user-images.githubusercontent.com/24370870/36201149-08740fd8-11a5-11e8-96d0-7c449e19b3aa.png)

**Comment by JoelProminic** [comment]
I confirmed that the appearance is fixed, and that I can rename a custom template file.    I also confirmed that project templates do not have the originally reported issue.
