### ISSUE TITLE
Trying to use some latin5(turkish) characters in project name but keyboard does not type

### ISSUE THREAD

**Issue by nihavend** [prominic/Moonshine-IDE#188]
Trying to use some latin5 characters in project name but keyboard does not type.
e.g. : İŞĞÇÖ ıçşöğ

**Comment by piotrzarzycki21** [comment]
I did quick look into that and it looks like the problem is with paste and typing. In general TextInput is able to display all of that characters - I did check that.
Need to investigate why it is not working specifically in our IDE.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine @JoelProminic I know where the problem is and I partially know how to fix it. We are adding restriction to that text input `a-zA-Z0-9._`. I see two solutions:
1) Remove restriction and leave it to the user what he is typing there
2) Add some range to the characters, but it is hard to have such things. When I added for example range for lating `\u0020-\u007F \u0100-\u017F \u0180-\u024F \u00A0-\u00FF` - I could type text from @nihavend but additionally dots and other characters were allowed.

Thoughts ?

**Comment by piotrzarzycki21** [comment]
There is also second thought that I can implement TextInput which allows restrict using RegExp which may be the solution for that. I'm not in a favor of such resolution.

**Comment by piotrzarzycki21** [comment]
Btw. [TextInput and field restrict](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextField.html#restrict) do not allow usage of RegExp. Documentation do not mention that and I did check internal implementation. :)

**Comment by rat-moonshine** [comment]
We can't remove all restrictions from the project name. Many project files created by the name of the project, and OSs has several restrictions against a valid file naming by used characters.

**Comment by piotrzarzycki21** [comment]
Windows also have such restriction, should we bother about that ?

**Comment by piotrzarzycki21** [comment]
I can implement TextInput with RegExp support restriction. Add regexp which do not allow some specific characters which cannot be used for folder names and file names.

**Comment by rat-moonshine** [comment]
> Windows also have such restriction, should we bother about that ?

All OS has restrictions to file naming, so we surely need to careful about that.

**Comment by piotrzarzycki21** [comment]
I have found better solution. Instead restricting to some range of characters, better do not allow for some specific one which cannot be used for folder/filename.

**Comment by piotrzarzycki21** [comment]
Wait a moment, but this is very different than bug raised. Please open another one that we have problem with names of the file in Chinese or Lating and we have problem when we are using Chinese and Latin in Editor.

**Comment by rat-moonshine** [comment]
This is related to your recent fix, @piotrzarzycki21 . Since as an alternative solution you proposed and removed the existing character restriction, now one can input anything to the name field which causing errors like above. This is directly related to the fix you applied, and this fix is not right at this moment. Thus, you may need to do further work on the solution you've applied and make it full-proof.

**Comment by piotrzarzycki21** [comment]
To me previous resolution was wrong. Since we are doing an restriction to the field called Project Name which is also the name of the folder, we should be ready to the repercussions of having different characters than English. I will investigate whether this is the results of my changes.

**Comment by JoelProminic** [comment]
To reproduce @rat-moonshine's error, create a new ActionScript project with one or more periods in the name.  This is valid for the file name, but invalid for the generated main class:

![image](https://user-images.githubusercontent.com/24532731/36317682-641299cc-1303-11e8-802a-2803821b8703.png)


My thought is to use the "^" option for the restrict field, and then define a set of unallowed characters.  This should include the standard keyboard special characters, as well as the unicode characters for things like newline or carriage return.

**Comment by piotrzarzycki21** [comment]
I will add to the restriction some special characters.

**Comment by rat-moonshine** [comment]
I noticed the same all-character-acceptable behavior in FlashDevelop. When I tried to enter many special characters and create a project, it turned to fatal error as well. IDE like Eclipse also permits to enter only a few special characters to project name. Perhaps, we want to restrict things in same way.

**Comment by piotrzarzycki21** [comment]
I have pushed changes where I'm restricting all special characters from keyboard. Intellij has the same. I'm allowing only for `_`. We do not allow for new line, maybe by paste it is possible, but let's see what users has to say.  Take a look and let me know.

I see issue with building Royale projects with Turkish name. I'm looking into that.

**Comment by piotrzarzycki21** [comment]
@nihavend  I did more investigation and I would be careful with creating some project with Turkish names in the files. 
I did test scenario where project names along with main file was "TestFlexıçşöğ" and the results wasn't good.

1) Apache Flex 4.16.1/Adobe Air Desktop project was able to build but application wasn't able to start. I got exactly the same results not only in Moonshine but also in Intellij:

```
: (fcsh) 
: FSCH target: 1
: fcsh: Assigned 1 as the compile target id
: Loading configuration file D:\Work\flex-sdk-4.16.1_adobe_air_28\frameworks\air-config.xml
: Loading configuration file D:\Work\projects\Prominic.NET\Moonshine Tests\TestFlexıçşöğ\obj\TestFlexıçşöğConfig.xml
: Launching application...
: bin-debug/TestFlexıçşöğ.swf (1007980 bytes)
: (fcsh) 
: Project Build Successfully
: invalid application descriptor: invalid application identifier
```

2) Apache Royale project wasn't able to build at all:

```
: Using Royale SDK: D:\Work\royale_ide\royale_nightly_js_swf
: MXMLJSC
: -sdk-js-lib=D:\Work\royale_ide\royale_nightly_js_swf\frameworks\js\Royale\generated-sources
: -load-config+=obj/TestiçsögConfig.xml
: -optimize=false
: -debug=true
: -o
: bin-debug/Testiçsög.swf
: -compiler.targets=SWF
: command line Error: unable to open 'D:\Work\projects\Prominic.NET\Moonshine Tests\Testıçşöğ\obj\TestiçsögConfig.xml'.
: 
: 
: 
: 1.27495546 seconds
: Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
```

**Comment by piotrzarzycki21** [comment]
@JoelProminic , @rat-moonshine having above problems with major SDK which we are supporting I think I will revert my changes and get back to the restriction which we had. Let me know if you have other thoughts.

**Comment by piotrzarzycki21** [comment]
@joshtynjala do you have some thought about that ? Does Feathers project will have problems with building in case of let's say Turkish? 

I see that other IDEs doesn't have restriction as we had. Once I remove some of them I had problems as I described above. Intellij reported exactly the same errors in case of Flex.

I'm a bit torn between staying on guard with the restriction and give user more options.

@rat-moonshine does Flash Builder allow to type Turkish in the project name and new file name ? You have mention above Eclipse - FB is based on that, but does that rules apply also to that IDE.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 The Feathers SDK is forked from the Apache Flex SDK, and it shouldn't add any additional restrictions to allowed characters. As far as I know, it should be able to handle the Turkish if Flex can.

**Comment by nihavend** [comment]
When i was asking the question, i was really trying to learn the limits of the IDE.
In my opinion, it sholud at least be dependent to the language of the operating system. Should not care what the other ide's do or not.
I mean, if the OS is english, than it is expected to not support. But if it is turkish than it should.

**Comment by joshtynjala** [comment]
Checking what Flash Builder does is absolutely the right thing to do, in my opinion. Adobe knows their own platform best, and if they restrict certain characters (I don't personally know if they do or not), then it's for good reason. If Flash Builder restricts characters, but Moonshine does not, then we risk passing invalid data to the compiler that may cause unexpected problems.

**Comment by nihavend** [comment]
![image](https://user-images.githubusercontent.com/5983818/36798240-2497ccec-1cbb-11e8-908c-a13153437f52.png)
This is the view of Fb on windows  turkish

**Comment by piotrzarzycki21** [comment]
@nihavend as I understand it's building. Are you able to build that app with Apache Flex ?

**Comment by nihavend** [comment]
Yes builds and runs. I may try it with Apache Flex, if you guide.

**Comment by piotrzarzycki21** [comment]
I didn't revert changes for 1.10.0 release, can you try build your project with Apache Flex ? You can download it using [installer](https://flex.apache.org/installer.html).

**Comment by piotrzarzycki21** [comment]
If you will have any kind of problems with Installer, download SDK manually.
1. SDK [binaries](http://www.apache.org/dyn/closer.lua/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.zip)
1. Unpack it and run ant command `ant -f installer.xml -Dair.sdk.version=29.0 -Dflash.sdk.version=29.0`

**Comment by nihavend** [comment]
First i tried to compile and failed with error :

D:\dev\eclipse_workspaces\flash_builder\sdk_4.6.0\Şaşırtıcığ\src\Main.mxml(5): Error: Could not resolve <fx:Declarations> to a component implementation.

        <fx:Declarations>


Then I added the line -Duser.language=en -Duser.location=us to mxmlc.bat. Compilation is succesfully completed. 

Command :

D:\dev\Apache Royale\FlexEncodingTest>"D:\dev\Apache Royale\apache-flex-sdk-4.16.1-bin\bin\mxmlc" "D:\dev\eclipse_workspaces\flash_builder\sdk_4.6.0\Şaşırtıcığ\src\Main.mxml" -load
-config="D:\dev\Apache Royale\apache-flex-sdk-4.16.1-bin\frameworks\flex-config.xml"
Loading configuration file D:\dev\Apache Royale\apache-flex-sdk-4.16.1-bin\frameworks\flex-config.xml


Result :
D:\dev\eclipse_workspaces\flash_builder\sdk_4.6.0\Şaşırtıcığ\src\Main.swf (258382 bytes)

**Comment by piotrzarzycki21** [comment]
Can you try through Moonshine or is this stack trace from Moonshine ?

**Comment by nihavend** [comment]
This is the stacktrace of commandline compiler mxmlc in royale.
Here is the output of moonshine 1.10.0, Build 8

![image](https://user-images.githubusercontent.com/5983818/37738519-54db7df0-2d68-11e8-89c4-5dc21adef015.png)

**Comment by piotrzarzycki21** [comment]
@nihavend I just noticed that second character is a question mark on your screenshot. Can you paste here name of the file. I would like to try it out in Moonshine 1.11.0.

**Comment by piotrzarzycki21** [comment]
@nihavend I'm not sure whether I can do anything more. I won't revert that changes, so you will be able to use project name in Şaşırtıcığ, however I recommend using English names etc. 
I just tried to build with above name Desktop project with Moonshine 1.12.0 using Adobe Flex 4.6 and Apache Flex 4.16.1 and it went fine.
