### ISSUE TITLE
Source folder icon disappears after root refreshed

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#189]
- Open a project to Moonshine sidebar
- While expanding the project root, project tree properly marking its source folder by adding a rounded 's' icon
- Right-click on the project root and choose Refresh from the opening context-menu
- Source folder making icon disappears

**Comment by JoelProminic** [comment]
I can't reproduce the original bug on the latest build.  I tried some other variations on the procedure as well, but the bug did not trigger.
