### ISSUE TITLE
Hover: tooltip sometimes doesn't disappear

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#19]
Recently, Doug reported the issue (reference #17):

> Suggest set a timer (30 seconds is probably more than enough) on the mouse-over pop-ups. Sometimes they get orphaned and I have to close the IDE and re-open to remove them.

 I've created a screen recording demonstrating the problem at here: https://vimeo.com/234630627.

**Comment by joshtynjala** [comment]
I addressed a number of hover/signature/definition issues in commit 33e0dd601c620c1af71a0616869bc1a45fadf9f5

In particular, on roll out and on switch tab, they're all closed, so this should be good now.
