### ISSUE TITLE
"Define it now" doesn't work in project Settings - Custom SDK

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#190]
**Scenario:**
1. Define "Default SDK" by **File** -> **Settings** -> **Default SDK**
1.  Setup the same SDK in project settings and **Save**
1. Go to the **File** -> **Settings** -> Default SDK
1.  Click **Change** and remove from the list used SDK and **Save** settings
1.  Go to the project **Settings**, you should see:
![image](https://user-images.githubusercontent.com/24554795/36313075-c650760e-1330-11e8-8955-05d0d5fc0470.png)

1.  Define SDK and Save
1. Go to the project Settings again

**Current Result:**
Moonshine is prompting again that "This SDK is not defined."

**Expected Result:**
After step 6 user shouldn't be prompted for SDK again.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 you can give a test to the fix now.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine it's working, you can close the issue.

**Comment by JoelProminic** [comment]
Oddly, I get this prompt even when I select the same SDK directory:  
![image](https://user-images.githubusercontent.com/24532731/37234529-ed9acb90-23bd-11e8-858e-3da1e030734a.png)

I can still define the SDK, though.  I don't think this would seem unusual in a real use case.

**Comment by rat-moonshine** [comment]
Previously, the project used to save different values against custom SDK since the bug. After the new changes, its possible that Moonshine sees the values are different with the previously saved value, thus prompt the above alert. However, I shall give a 2nd look on the scenario later.
