### ISSUE TITLE
Not able to create Flex library project from sources where there is no Main application file

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#192]
I was trying to create library project using existing sources, where there is no Main application file. Unfortunately **Main application file** is always required.

In scenario where there is selected **Project with existing source**  - we should require only **Main source folder**.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I discovered that in attempt of creating library project using Visual Editor sources.

**Comment by rat-moonshine** [comment]
In general, in library project creation (as new), no main application file creates. I probably overlooked the Project with existing source part where this still asking for the main application file (which shouldn't be a restriction in library project case). I shall look into this, @piotrzarzycki21 . Thank you for reporting.

**Comment by rat-moonshine** [comment]
This is also related to #193 . The said issue needs to be resolve to fix this issue.

**Comment by rat-moonshine** [comment]
As #193 marked as resolved, and application source file requirement removed in case of library project creation, @piotrzarzycki21 please give a try with the latest source.

**Comment by piotrzarzycki21** [comment]
It's working.

**Comment by JoelProminic** [comment]
I confirmed that this works.   I did notice that if I did not set the source directory, I still got a prompt to set both the source directory and application file:  "Please provide the source folder and application file location to proceed."

**Comment by rat-moonshine** [comment]
I have updated the alert message.

**Comment by JoelProminic** [comment]
I confirmed that the message is updated for the Library import, and is not changed for the original application import.
