### ISSUE TITLE
[CRITICAL] Project creates in wrong directory with 'project with existing source' option

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#193]
I'm not sure when this issue introduced but probably because of recent-past changes. 

- Make sure you have a directory on /Desktop/NewFlexDesktopProject - along with its source application file
- Open new project creation dialog (i.e. Flex desktop project)
- If you choose Desktop in the "Parent Directory" section, you shall get an error notification saying that /Desktop/NewFlexDesktopProject folder already exists
- Selecting "Project with existing source" option changes the path information to "Existing Project Directory" to /Desktop/NewFlexDesktopProject, and the error message also removes - which is fine
- After providing main source folder/file option creating the project - Moonshine creates the project root at /Desktop instead of /Desktop/NewFlexDesktopProject, which is wrong

**Comment by rat-moonshine** [comment]
@JoelProminic reported following problem based on latest updates to this:

1. Create a new project in Desktop
2. Close the project in Moonshine
3. Delete the .as3proj file
4. Create a new project
5. Select Desktop as the base project directory
6. Enter the same project name. At this point, there should be an error for a duplicate project name
7. Select "Existing Project". The error clears
8. Select the source directory.
9. Select the main class
10. Create the project

The above produces duplicate directories and null named stuff in Moonshine:
![image](https://user-images.githubusercontent.com/24370870/36582821-01b7158c-1899-11e8-8cd9-0c4fcd4c8562.png)
![image](https://user-images.githubusercontent.com/24370870/36582825-07f05cb0-1899-11e8-81c1-499f050e4921.png)

I confirm the problem in Windows.

**Comment by rat-moonshine** [comment]
I have pushed some fixes. In the updated process, when user selects '**Project with existing source**' option, message in project path section changes to:

> (Note) Project with existing source directory is:
> /Users/.../Desktop

The above changes should more clearly tell user where the project is going to create (or the project root is). However, in smaller-monitor/application-window, while changing selection to '**Project with existing source**' option, this message may cut-off the screen - unless user scroll up and noted. We probably need to auto-scroll user to top against the option's selection change.

I still need to check some more test cases.

**Comment by rat-moonshine** [comment]
> The above changes should more clearly tell user where the project is going to create (or the project root is), so therefore user can change the path as necessary. However, in smaller-monitor/application-window, while changing selection to 'Project with existing source' option, this message may cut-off the screen - unless user scroll up and noted. We probably need to auto-scroll user to top against the option's selection change.

A temporary scroll-to-top now added to make the project path section visible (along with its final path message) every time 'Project with existing source' selection changes. 

So far, all looks good, I'm closing this, please reopen on bug found.

**Comment by JoelProminic** [comment]
If I follow the same procedure again (with a different workspace), then I end up creating the project in the workspace:
![image](https://user-images.githubusercontent.com/24532731/37233218-f1609404-23b7-11e8-8b52-94bfa7366ac6.png)
![image](https://user-images.githubusercontent.com/24532731/37233242-0b65fa06-23b8-11e8-84bc-63a37339aee1.png)

However, it looks like your new design is meant to show the users that they are about to create the project in the parent directory, and I think it does make this clear with the prompts and existing directory path.   

I still think it is a bit confusing to have the same combobox choose either the parent directory or the project directory, but this is fine for now.
