### ISSUE TITLE
Cannot create new MXML file in Flex library project

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#194]
I have found that I'm not able to create MXML file in Flex library project.

**Scenario:**
1) I have created library project with following options:
![image](https://user-images.githubusercontent.com/24554795/36669687-0c1107cc-1af6-11e8-9e23-327540bd487c.png)

2) I would like to create new MXML file, but it's disabled
![image](https://user-images.githubusercontent.com/24554795/36669708-1cd0d5e2-1af6-11e8-93ee-842b09684820.png)

I believe we should be able to create such file. It was tested in released 1.9.0 version and on my PrimeFaces branch.

**Comment by rat-moonshine** [comment]
Non pure-AS project now able to create MXML file as well.

**Comment by JoelProminic** [comment]
I confirmed I can now create both MXML and AS files within a Flex Library Project or a Mobile Library Project.    I can't create MXML files in an ActionScript library project, as expected.
