### ISSUE TITLE
Unable to build Flex library with MXML file

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#196]
**Scenario:**
1) I created Flex library project with following options:
![image](https://user-images.githubusercontent.com/24554795/36670562-0a577f26-1af9-11e8-98a3-0e74bf090970.png)

2) I wanted to create MXML file, but due to #194 I did it manually. Next I run "Build Project"

**Result:**
I'm getting following error
```
: INFO: server listening on 0:0:0:0:0:0:0:0:57963 (xSocket 2.8.15)
: Loading configuration file D:\Work\flex-sdk-4.16.1_adobe_air_28\frameworks\flex-config.xml
: Loading configuration file D:\Work\projects\Prominic.NET\Moonshine Tests\TestFlexLibraryProject\obj\TestFlexLibraryProjectConfig.xml
: D:\Work\projects\Prominic.NET\Moonshine Tests\TestFlexLibraryProject\src\MyView.mxml: Error: Unable to locate specified base class 'spark.components.Group' for component class 'MyView'.
: 
```

Sample project: 
[TestFlexLibraryProject.zip](https://github.com/prominic/Moonshine-IDE/files/1758582/TestFlexLibraryProject.zip)

**Comment by piotrzarzycki21** [comment]
My suggestion is first create exactly the same library project in Flash Build. Try to build it there.

**Comment by rat-moonshine** [comment]
Since the updates to #194, this should work as well.

**Comment by JoelProminic** [comment]
I did not see any errors when I tested a new project today with multiple MXML files.
