### ISSUE TITLE
Some Beads not being resolved by IDE

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#197]
In 0.9.2 Nightly Builds some of the Basic.html.beads are not available. For example <beads:SolidBackgroundBead ... /> generates the error 'This tag could not be resolved to an ActionScript class. It will be ignored.'

This worked before 0.9.2 and these beads are all correctly in all the latest nightly SDKs. Some beads new to 0.9.2 are okay, but several old beads can no longer be resolved by Moonshine.

Scanning throught the pop-up list that shows up after typing 'import org.apache.royale.html.beads.' I can see that several beads that are in the sdk are missing from the list.

Doug

**Comment by piotrzarzycki21** [comment]
Hi @doug777 ,

It depends what version of SDK are you using. Some beads are available only for SWF version and they won't be available probably in the JSonly. 
SolidBackgroundBead is one of such bead, it's available only in SWF. 
What version of SDK are you using ? JS only or SWF,JS ?

**Comment by doug777** [comment]
Hi Piotr,

Since I downloaded the js only sdk, I assumed this would contain only 
the items available to js.

So is it Moonshine that selects the js only classes from the sdk?

Doug

**Comment by piotrzarzycki21** [comment]
It looks like this is how it is working, which actually is good thing. In the end you did choose JS only SDK, so you shouldn't expect to see in code completion some classes which are SWF only.

**Comment by piotrzarzycki21** [comment]
@doug777 ,

Nope Moonshine doesn't select those classes, they are provided with swc as far as I know. 

I'm closing this one.
