### ISSUE TITLE
Preparing Moonshine for more proper update versioning check

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#198]
(This needs to be done before 1.9.0+ release)

**Comment by rat-moonshine** [comment]
New version comparison check based on Away Builder's update check, now in Moonshine replacing the older (comparison) logic. This shall be bundled with 1.9.0+ Moonshine versions. The newer version check also uses different URL to check from - https://moonshine-ide.com/wp-content/uploads/MoonshineUpdater.as.

However, older builds having old version check URL shall continue to check from the older URL (https://moonshine-ide.com/wp-content/uploads/updater.xml - we probably going to maintain this URL for some more time just for old builds like --1.9.0, before deprecating completely). Last stable 1.9.0 also checks this existing URL and with older comparison logic, incrementing to 1.10.0 shouldn't create any problem, though. 

The newer comparison logic tested with following cases:
Application Version | Update Check Version | Result - Shall Update
------------ | -------------  | ------------- 
1.10.0 | 2.0.0 | Yes
1.9.0 | 1.10.0 | Yes
1.10.0 | 1.0.19 | No
1.002.0 | 2.0.0 | Yes
1.9.0 | 1.9.0 | No
1.9.0 | 1.7.0 | No
1.9.0 | 0.190.0 | (Illogical since major version is not suppose to be 0 and lower than current) Yes

**Comment by rat-moonshine** [comment]
@JoelProminic please check, if this new comparison looks sense to you (https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/extResources/riaspace/nativeApplicationUpdater/NativeApplicationUpdater.as#L245) and meets our comparison needs.

**Comment by rat-moonshine** [comment]
Moonshine is continue using the older update URL (https://moonshine-ide.com/wp-content/uploads/updater.xml) instead any new.

@JoelProminic , when I tried this following logic, it failed when (1.9.0 > 1.10.0):
```
function shouldUpdate(int[] currentVersion, int[] newVersion) {
int minLength = currentVersion.length;
if (newVersion.length < currentVersion.length) {
minLength = newVersion.length;
}

for (int i = 0; i < minLength; i++) {
if (currentVersion[i] < newVersion[i]) {
return true;
}
else if (currentVersion[i] > newVersion[i]) {
return false;
}
else {
// continue
}
}

// Optionally, we could compare the length at this point to break a tie

// At this point, all checked version numbers are equal
return false;
}
```

I updated the check little differently, and [that](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/extResources/riaspace/nativeApplicationUpdater/NativeApplicationUpdater.as#L552) worked good so far. Following is my test matrix:

Application Version | Update Check Version | Result - Shall Update
------------------- | ----------------------  | ---------------------- 
1.10.0 | 2.0.0 | Yes
1.9.0 | 1.10.0 | Yes
1.10.0 | 1.0.19 | No
1.002.0 | 2.0.0 | Yes
1.9.0 | 1.9.0 | No
1.9.0 | 1.7.0 | No
1.9.0 | 0.190.0 | No
1.101.0 | 2.0.0 | Yes
2.0.101 | 2.1.0 | Yes

(Note: AIR application descriptor allows maximum 3 digit to major/minor/revision value)

**Comment by piotrzarzycki21** [comment]
It looks like we are good here.

**Comment by JoelProminic** [comment]
I don't see any problems with this logic.   Did you test this with updater.xml?  If you haven't done a full test yet, we should verify this before the official release.

**Comment by rat-moonshine** [comment]
@JoelProminic , test scenarios used a copy of the existing updater.xml file (to test by different version values), and there has no structural changes. So we can be assure that the new logic will work indifferently to the existing updater.xml, as well.
