### ISSUE TITLE
Add PrimeFaces components to Visual Editor pt. 1

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#199]
In the first version of Visual Editor with PrimeFaces we should add following components:

## Input
- [x] [InputText](https://www.primefaces.org/showcase/ui/input/inputText.xhtml) (@rat-moonshine)
- [x] [InputNumber](https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml)
- [x] [InputMask](https://www.primefaces.org/showcase/ui/input/inputMask.xhtml)
- [x] [InputTextarea](https://www.primefaces.org/showcase/ui/input/inputTextarea.xhtml) (@rat-moonshine)
- [x] [BooleanCheckbox](https://www.primefaces.org/showcase/ui/input/booleanCheckbox.xhtml) (@rat-moonshine)
- [x] [AutoComplete - DropDownList](https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml)

## Button
- [x] [Button](https://www.primefaces.org/showcase/ui/button/button.xhtml)

## Panel
- [x] [TabView](https://www.primefaces.org/showcase/ui/panel/tabView.xhtml)
- [x] [Fieldset](https://www.primefaces.org/showcase/ui/panel/fieldset.xhtml) 

## Misc
- [x] [OutputLabel](https://www.primefaces.org/showcase/ui/misc/outputLabel.xhtml)
- [x] Include (External xshtml include placeholder - need not to be rendered when _include_ as xshtml but double-clicking should open the xshtml file to UI editor. This is particularly useful when a large deeply nested page with multi-level tabs etc.) (@rat-moonshine) 
- [x] [Div](https://www.w3schools.com/tags/tag_div.asp) (Since we have an active use of Div tag as a container component, we can provide an entry to the component list as well) 

## Data
- [x] [Tree](https://www.primefaces.org/showcase/ui/data/tree/basic.xhtml) 
- [x] [DataTable](https://www.primefaces.org/showcase/ui/data/datatable/basic.xhtml)

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 , what is the relevance of having the following part when it does not affect anything code-wise? 
![image](https://user-images.githubusercontent.com/24370870/37267952-5c866a0a-25e9-11e8-992f-f573bd024f90.png)

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 , some of the components' checkbox change do not notify change to the editor (star mark to the editor tab). You may need to dispatch some event followed by the _set_ methods (as I did in InputTextarea.as).

**Comment by piotrzarzycki21** [comment]
I just finished basic TabView. It looks like I need to review now Main Container again, because I see it's not working as I expected. 
What area right now are you touching @rat-moonshine ? - I'm asking about code.

**Comment by rat-moonshine** [comment]
I've started to Include. Let me know which class files you may wants for Main Container changes, I shall try not to touch them until you done, @piotrzarzycki21 .

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just pulled your latest changes and I'm getting fail during Visual Editor build:

```
D:\Work\projects\Prominic.NET\MockupVisualEditor\src\utils\MoonshineBridgeUtils.as: Type was not found or was not a compile-time constant: IVisualEditorLibraryBridge.

		public static var moonshineBridge:IVisualEditorLibraryBridge;
		                                  ^

D:\Work\projects\Prominic.NET\MockupVisualEditor\src\utils\MoonshineBridgeUtils.as: Definition view.interfaces:IVisualEditorLibraryBridge could not be found.

	import view.interfaces.IVisualEditorLibraryBridge;
	                      ^

```

**Comment by rat-moonshine** [comment]
Can you give a build to the .swc with your local latest, @piotrzarzycki21 ?

**Comment by rat-moonshine** [comment]
I found I missed out the interface file to add (to Git). It's now added to committed. Please, check.

**Comment by piotrzarzycki21** [comment]
I did spent quite a lot of time yesterday on Div container. It looks like we won't be able to prepare our containers to work perfectly as Div behave.

When you put to the Div several different PrimeFaces components (in my test I put all of which we did implement) and export it - Everything is messed up. 

1. **Visual Editor view**

![image](https://user-images.githubusercontent.com/24554795/38132892-37a849a6-340d-11e8-8000-66cf481c06c0.png)

2. **Exported VE view**

![image](https://user-images.githubusercontent.com/24554795/38132920-51bdb416-340d-11e8-9ad7-23e44af1bea5.png)

I don't want to spent countless hours to mimic such messy behavior. I decided to take more modern approach. I will add to our default container Div [FlexBox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox) or [Grid](https://developer.mozilla.org/en-US/docs/Glossary/Grid). I'm not sure to which direction I will go, but my first test looks promising. This is how FlexBox container laid out exported project from Visual Editor:

3. **Export with FlexBox**

```
display:flex;
flex-direction: row;
flex-wrap: wrap;
flex-flow: row wrap;
```
![image](https://user-images.githubusercontent.com/24554795/38133082-f60732ea-340d-11e8-89ea-22a3d39e695c.png)

As you can see in above screenshot it almost perfectly synced with created view in Visual Editor.

**Comment by piotrzarzycki21** [comment]
You understand me perfectly and I did look into your previous work - it helped me a lot. I was trying to thing how to achieve default behavior in Flex, but it is really no worth to pursue that. Dealing for some components with width/height in an infinite custom cases is not the right direction - if we have nice solution. IMO with FlexBox we should have width/height exactly as you set up in Visual Editor.

**Comment by rat-moonshine** [comment]
You are right. We may also needs to give functionality to change this behavior in Div, though. Think in a situation where user may not wants flow layout but simple vertical or generic Div behavior.

In that case we may want to give a feature to change Div's style property (be it a dropdown or something). On a long run, you may want to provide style property against individual components as well, i.e. dusplay=inline (but this can wait).

Thanks!

**Comment by piotrzarzycki21** [comment]
@rat-moonshine You didn't understand me in one point. I would say the major one. I'm not going to give user any of that option `display: block, inline, inline-block` - Because it's hard to mimic properly such behavior in Flex. It is no worth to spent time on such messy behavior, where some children display width: 100% although they have set 150px. Even if I would somehow figure out how to achieve all of that, I can assure you that user which will be building his layout in Visual Editor really fast find some case where it's simply won't work. :) Try to build sophisticated layout using only DIV - block and inline - count your time - you will see what I'm talking about. 

I do prefer give user ability to choose in the drop down list modern display type like - FlexBox or Grid - which giving in the browser exactly what we have in Flex for several years out of the box. Ask yourself - Why do you like Flex? Why people so much miss Flex in the browser ? - Because when you put Button in the Group aligned to the left - It will be on the left -period! In HTML not, however such modern way like FlexBox or Grid finally giving an opportunity to be more pixel perfect.

**Comment by piotrzarzycki21** [comment]
After chat with Andrii I have removed PanelGrid from the list and start looking how to implement [Grid](https://www.primefaces.org/showcase/ui/panel/grid.xhtml). I will raise separate issue for that part.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Unfortunately FlowLayout which we are trying to use do not align children to bottom. I will try to spend some time on fixing that or use something else.

**Comment by piotrzarzycki21** [comment]
I have changed in case of FlowLayout to allow manipulate items only for left/right and center. I would like to move forward with the stuff. If there will be strong requirement I will get back to implement bottom align.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I will check this one without your code, but I doubt that I experienced any problem. One thing - Why you don't have any styling in that screenshot ? Maybe this is your problem.

**Comment by piotrzarzycki21** [comment]
I have added comments into your latest commit to VisualEditor repository

**Comment by atingupta2005** [comment]
I tested the basic form and found that the arrangement of the elements is distorted in exported project.

Please refer to below screenshots:

**The Output on Browser:**
![screen shot 2018-04-20 at 2 51 50 pm](https://user-images.githubusercontent.com/3568735/39043386-e75f733a-44aa-11e8-8871-ee0c0bb75d2d.png)


**The UI in Moonshine Designer:**
![screen shot 2018-04-20 at 2 54 47 pm](https://user-images.githubusercontent.com/3568735/39043387-e7963a64-44aa-11e8-9201-7fd66e8cd5da.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine what container is inside Fieldset ?

**Comment by piotrzarzycki21** [comment]
If there is no container, please raise issue that when you are using Fieldset without any container inside after export items are distorted.

In the meantime you can put inside Fieldset "Div" and add as many "Div" as you won't in order to create above UI.

**Comment by piotrzarzycki21** [comment]
@atingupta2005 any update on that ? Can you please raise the issue and address my question.

**Comment by atingupta2005** [comment]
Hi, 

While testing I found that all the UI components are reposition to the Left Top position if I Close and Open the Project again. Attached are the screenshots:


![screen shot 2018-04-24 at 12 35 59 pm](https://user-images.githubusercontent.com/3568735/39172478-8453f8f2-47bf-11e8-9f72-69d550468bcf.png)
![screen shot 2018-04-24 at 12 41 47 pm](https://user-images.githubusercontent.com/3568735/39172479-84949308-47bf-11e8-8f30-cf7b936e386f.png)



Below is the code:

<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui">
  <h:head>
    <link rel="stylesheet" type="text/css" href="resources/layout-styles.css"/>
    <title/>
  </h:head>
  <h:body>
    <div class="flexHorizontalLayout flexHorizontalLayoutLeft flexHorizontalLayoutTop" style="width:328.5px;height:288.5px;">
      <p:fieldset style="width:283.5px;height:225.5px;" legend="Basic" toggleable="false" toggleSpeed="200">
        <p:inputNumber style="width:100px;height:30px;" value="" thousandSeparator="" decimalSeparator=""/>
        <p:outputLabel style="width:44px;height:30px;" value="Name"/>
        <p:button style="width:100px;height:30px;" disabled="false" value="Save" title=""/>
        <p:outputLabel style="width:56px;height:32px;" value="Age"/>
        <p:inputText style="width:100px;height:30px;" value=""/>
      </p:fieldset>
    </div>
  </h:body>
</html>


Thanks
Atin

**Comment by atingupta2005** [comment]
I am further testing the other things on it and I also just put some more
issue in the thread.

**Comment by piotrzarzycki21** [comment]
@atingupta2005 I see on your screenshot that you are opening exported project in Moonshine. You should not do that. Exported project is not a Moonshine project but PrimeFaces.

**Comment by piotrzarzycki21** [comment]
I think I should propose exporting project not inside Visual Editor project directory, but in the parent. That's why you probably did that.

**Comment by rat-moonshine** [comment]
> I am further testing the other things on it and I also just put some more issue in the thread.

@atingupta2005 , I would suggest to create separate issues to each of your finding, so it'll be easy to keep track of thing.
