### ISSUE TITLE
Code completion list doesn't display style attributes in Flex components

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#200]
In components from Apache Flex SDK code completion doesn't display styles like fontFamily, borderVisible etc.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I checked that issue and language server doesn't return those properties, but it's not reproducible with v. 0.10.0 in VSCode. I hope once you provide next update to Moonshine we will be able resolve that one.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Okay, thanks for the info. I've assigned this to myself so that I remember to check that it's still working after I update vscode-nextgenas in Moonshine to v0.10.0.

**Comment by piotrzarzycki21** [comment]
@joshtynjala Today I have noticed also that some classes are also not visible in code completion. In that case it is apply both Moonshine and VSCode. Try to for example `ScrollerLayout`.

**Comment by joshtynjala** [comment]
`ScrollerLayout` has `[ExcludeClass]` metadata, so it's supposed to be hidden, as I understand it:

https://github.com/apache/flex-sdk/blob/ba414443032b49c45ff11b61db452c8a8f428bd8/frameworks/projects/spark/src/spark/components/supportClasses/ScrollerLayout.as#L37

**Comment by joshtynjala** [comment]
I updated vscode-nextgenas to v0.10 this week, so this should be working correctly now! Closing.

**Comment by piotrzarzycki21** [comment]
Just tested it and it's working. Just quick question Josh. Do we have in the API some function which allows me to display language version ? I would like to have such information in the console.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Do you mean the version of the language server?

**Comment by piotrzarzycki21** [comment]
Yes the version of language server.

**Comment by joshtynjala** [comment]
I don't think that's possible right now. I can think of some ways that we might expose the version string, but they're not ideal.
