### ISSUE TITLE
Jump to the next line by enter produce unwanted characters in code editor

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#202]
When I'm working in MXML and jump to the next line by enter code editor produce for me unwanted characters. 

![unwanted_characters_in_code_editor](https://user-images.githubusercontent.com/24554795/37393548-aa344fc2-2771-11e8-9b3c-c0c570d17599.gif)

**Comment by rat-moonshine** [comment]
This open and auto-closing of double-quote character designed back in days targeting scenarios in fx:Script editor (where double-quote and next line breaks are very regular things). Although a double-quote and line break is not valid in case of MXML, but this can be done in this manner:

`<s:ItemRenderer id="` and line break

Such circumstances probably need to be handled.

**Comment by piotrzarzycki21** [comment]
I'm not sure whether I wanted to improve the behavior or remove it completely. I will look into that soon and if it will very difficult fix- I probably remove it to simplify things. 

It's time to realize that we may not achieve some things in current state of editor, so better make step back and leave things as simple as is. I prefer have Notepad without such issue as you see above, than have buggy editor and loose time on fixing things after every release. - To me it is just lost time instead productive one.

Issue which you are seeing doesn't have any connection to feature with auto closing attributes.

**Comment by atingupta2005** [comment]
I have tested it and its working as expected
