### ISSUE TITLE
Language server do not prompt with newly created file

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#204]
(This problem can be found with recent 1.10.0 version as well)

- Create a new Flex desktop project
- Inside the **src** folder try creating a new MXML file - **TestMXML**
- Try to get it called inside the main application file's `fx:Script` area OR in the MXML tags area by code-completion
- Code-completion do not prompt for the newly created file
- Restart Moonshine, code-completion prompts with **TestMXML** file

**Comment by piotrzarzycki21** [comment]
Ahh yes I tempt to forgetting raise that issue. Thanks @rat-moonshine . Btw. It is enough if you close and reopen project - file will be visible, no need to restart Moonshine.

**Comment by joshtynjala** [comment]
See my comment in #201 for details.
