### ISSUE TITLE
Ability to CTRL+Click on Flex SDK items parent classes

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#205]
I'm not sure whether it is feature request or, a bug. It doesn't work in VSCode either. If I declare `<s:Group>` in my code I can go and see what is inside that class using CTRL + Click. However it completely doesn't work inside that class, I cannot easy navigate through the available variables/methods and cannot go to the parent classes. 

@joshtynjala that maybe something on the client sight with configuration, but if I would rather consider that as a feature.

**Comment by joshtynjala** [comment]
I consider it a feature request, not a bug. I'd like to support this feature, but I haven't yet figured out how to do it. It's something that I don't intend to investigate until after vscode-nextgenas 1.0.

**Comment by joshtynjala** [comment]
FYI: vscode-as3mxml v0.21.0 will support code intelligence in SDK files.
