### ISSUE TITLE
Fonts inside editor look fuzzy when using windows Scaling for HighDPI screens

### ISSUE THREAD

**Issue by radubirsan** [prominic/Moonshine-IDE#206]
For now I can disable the scaling by right-clicking the application icon and selecting "disable scalling on high DPI settings" the problem is that the font are to small in the IDE.

Adding <requestedDisplayResolution>high</requestedDisplayResolution> to the build parameters of AIR should fix the issue so that the fonts look crisp even  with windows scaling enabled.

**Comment by piotrzarzycki21** [comment]
I did push fix for that. Let's see it it helps for the next release.
