### ISSUE TITLE
Problem passing querystring vars to app

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#210]
I need to modify the index.html file (js only) in order to pass querystring variables into my app, but when I Build & Run as JavaScript, Moonshine overwrites the entire html file. Somehow I need it to leave the body section unchanged from before or insert body from a named external text file if it exists.

Or is there already some workaround for this?

Doug

**Comment by rat-moonshine** [comment]
At this moment Moonshine build complete project everytime you choose the project to build. There is no existing way to modify particular asset in compiled file system. 

However, in case of SWF compilation and if user choose to use their modified version of the wrapper HTML file, they can do it by editing `$Wrapper.html` as shown below:
![image](https://user-images.githubusercontent.com/24370870/37756208-a422489c-2dce-11e8-82cd-e4175fc73f5f.png)

The above is not applicable in case of FlexJS/Royale project, though.

**Comment by doug777** [comment]
Then for now I will build in Moonshine, modify the html file and run it from the browser.

Please consider this for a future upgrade.

Thanks,
Doug

**Comment by piotrzarzycki21** [comment]
@doug777 ,

Yes you can do that and it's part of Royale SDK feature. Here is the way:
- You can create your template html. Example of such template -> [mdl-js-index-template](https://github.com/piotrzarzycki21/TranspiledActionScript/blob/examples/Examples/MDLExample/src/main/resources/mdl-js-index-template.html)
- Next you are pointing in Moonshine that template file using following command in **Additinal compiler options**
`-html-template=src/main/resources/mdl-js-index-template.html`

**Comment by doug777** [comment]
Thanks Piotr, that works fine.
