### ISSUE TITLE
Misguided naming suggestion against FlexJS/Royale project

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#211]
While opening project creation dialog by named option "Flex Browser Project (FlexJS, Royale)", Moonshine pre-suggests project name as "NewRoyaleBrowserProject". However, changing template type do not updates the name suggestion:

![image](https://user-images.githubusercontent.com/24370870/37756366-3ce9cb54-2dcf-11e8-99b5-08cdaf74c01d.png)

Suggested options are:
- Update name suggestion based on template type change
- Suggest with general naming, i.e. NewJSBrowserProject

**Comment by rat-moonshine** [comment]
I've set a common name for the above project creation dialog to "NewJavaScriptBrowserProject". Feel free to change if one have better naming idea.

**Comment by piotrzarzycki21** [comment]
It doesn't feel right, because Royale is able to create also Flash applications. In the future there may be other outputs like WASM, TypeScript etc. We don't have to bother to much about that, FlexJS name I hipe won't live with us too long I think.

**Comment by rat-moonshine** [comment]
I was thought about too that both type of projects can produce swf as well; but giving the preference of its broad purpose I choose to set the naming with 'JavaScript' word. I agree, I am not happy with this naming either but this plan seems more economical than changing more in component level. This maybe true that FlexJS won't be there for long, but until then this fix.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I will make changes as part of that task #182

**Comment by rat-moonshine** [comment]
But why we are having a separate 'Royal Browser Project' entry in File > New, when we have the entry to choose between FlexJS/Royale by File > New > Flex Browser Project (FlexJS, Royale). This seems like a bug, and should be rectified.

**Comment by rat-moonshine** [comment]
"File > New" now showing same number of project templates comparing splash screen.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine , @JoelProminic Again I have it on my list. The changing UI is not the only thing which should be done. It is planned on the next release not that one.

**Comment by JoelProminic** [comment]
I confirmed that the Royale Browser Project template was removed from the menu.    I'm fine with waiting for further Royale updates until the next release.
