### ISSUE TITLE
Experiment with FileSystemTree component as a potential replacement for current project Tree 

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#212]
I have found [FileSystemTree](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/mx/controls/FileSystemTree.html) control and thought that we could experiment whether it is better than current project Tree.

**Comment by rat-moonshine** [comment]
So far by my test this component seems promising. However, since this meant only for AIR framework, I need to talk to @JoelProminic whether we want to manage two different components for desktop and web Moonshine (although we visit the web version less nowadays).

**Comment by rat-moonshine** [comment]
@JoelProminic wants to keep this in low priority as he thinks the current system is stable and also provides its purpose to web platform. Since the purpose of replacing current Tree component with FileSystemTree is to remove all the messy codes we use to update the Tree component time to time, to keep alive the web platform's component system - we anyway needs to keep those codes at somewhere.  Its true that we do not visit the web platform often these days, but we shall want to re-visit this at sometime.

However, @JoelProminic also thinks if the current Tree component would show more trouble in time, or any other reasons we would want the current component to be replaced, we shall look for this. This can be put to lower priority for now, we can create another branch to test the component in Moonshine codes and document its benefits and problems we may found.

**Comment by piotrzarzycki21** [comment]
Definitely create another branch to work on that. Let's see it in actions and check how it's simplify and how much messy code we will remove thanks to that.

**Comment by rat-moonshine** [comment]
Benefits:

- In-built feature request in form of #176 
- Less amount of parsing to populate tree file/folders - as population is in-build

**Comment by piotrzarzycki21** [comment]
That's interesting in case of #176. What about Tree refreshing, if you add some file to the folder outside Moonshine - do you get event  ?

**Comment by rat-moonshine** [comment]
This part is a bit confusing. Per the directoryChangeEvent description as mentioned the API doc, this never worked:
> directoryChange | Dispatched whenever the directory property changes for any reason.

While running my demo application and make a particular directory open and visible, changing anything inside that directory (i.e. file/folder creation/deletion/renaming) never fires the event for me. Those changes also not reflect to the UI unless I collapse and expand the said directory once. 

There is also one method didn't come up by expectation - findItem - https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/mx/controls/FileSystemTree.html#findItem(). Making the folder/item visible or non-visible, this never worked for me.

**Comment by piotrzarzycki21** [comment]
Your code is in the branch or are you talking about some example project ?

**Comment by rat-moonshine** [comment]
I'm talking about separate test project.

**Comment by piotrzarzycki21** [comment]
Did you setup this property in the test project ? [directory](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/mx/controls/FileSystemTree.html#directory)

**Comment by rat-moonshine** [comment]
Fun point is, you can even pass multiple File objects to its {{dataProvider}}, which renders multiple nodes (other than single by its {{directory}} property). But both usage demonstrate same behavior.

**Comment by piotrzarzycki21** [comment]
The recommended way seems to be using directory. If assign to directory one path makes events fire, try to play with that.

**Comment by piotrzarzycki21** [comment]
I see also couple of others controls [here](https://help.adobe.com/en_US/flex/using/WSacd9bdd0c5c09f4a-690d4877120e8b878b0-7ffe.html) related to Files/Folders in general

**Comment by rat-moonshine** [comment]
`FileSystemTree` didn't come up fully in my tests. Following is a basic list of what works and what not:
- File/Folder auto-generation upon given `directory` or `dataProvider` object - works
- File/Folder ordering mimics feature requested in #176 - works
- File/Folder creation/deletion/renaming outside of the application auto-updates the tree component - not works
- File/Folder creation/deletion/renaming outside of the application returns event - not works

In my opinion, the last functionality was important to work so we can keep continue more with this. If auto-updates is not works (or any event fire at least), then we can not cut off from manual refreshing to the tree nodes. 

The other controls you've suggested @piotrzarzycki21 , they seems good but for this issue requirement, we mainly needed `FileSystemTree` to be worked.

I'm closing this investigation now as not worked, please feel free to reopen if you want to revisit it.
