### ISSUE TITLE
Tour De Flex Broken after AwayBuilder Integration

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#213]
I noticed this behavior today:
1. Open Moonshine
2. Help > Tour De Flex
3. Open an entry from the Tour De Flex sidebar.  BUG:  This opens with a blank grey screen, and the tab does not have focus.   
![image](https://user-images.githubusercontent.com/24532731/37981256-c729a83e-31b2-11e8-9c3f-7fbbad917303.png)

4. Open an AWD file in the Away Builder editor 
5. Open an entry from Tour De Flex.  BUG:  A popup appears, with the message:  "addChild() is not available in this class.  Instead, use addElement() or modify the skin, if you have one." 
![image](https://user-images.githubusercontent.com/24532731/37981277-d62d7798-31b2-11e8-9719-0af703e0bdaa.png)

6. Close the alert.  BUG:  Note that a new tab has opened for the Tour De Flex entry, but it does not have focus.  
7. Open the tab.  BUG:  The tab displays the image from the Away Builder tab, but with no controls:  
![image](https://user-images.githubusercontent.com/24532731/37981289-e47d04b2-31b2-11e8-8324-ddddc996c7e9.png)

8. Open a different file type from the Projects sidebar
9. Open a Tour De Flex file again.  BUG:  the same behavior triggers again

This seems to be related to the Away Builder integration.   I confirmed that this behavior does not trigger with the official 1.10.0 release.

**Comment by rat-moonshine** [comment]
Fixed.

**Comment by JoelProminic** [comment]
I was not able to reproduce any of the issues I reported above.  The new tabs were created properly, with proper focus.

Since this bug is based on another new feature from this release (#89), it does not need to be included in the changelog.
