### ISSUE TITLE
Debugger view reorganization and improvement

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#214]
Currently it is really hard effectively using debugger as part of Project Tree.

My proposition:
- Move debugger to the console area
- Make console area Tab oriented - First Tab would be a Console, the second one Debugger
- Debugger Tab will be split to Stack trace area and Variables area

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 , please add some description towards this issue, along with your plan (if you have any).

**Comment by piotrzarzycki21** [comment]
This is where I end up:

![debug_view](https://user-images.githubusercontent.com/24554795/40486225-f611d67c-5f60-11e8-8498-ab3ddb668f4e.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine , @JoelProminic Any thoughts on that ? I would like to merge it to the master.

It's currently on the branch `features/issue_214_debugger_view_reorganization`

**Comment by rat-moonshine** [comment]
This looks much standard per other IDEs. Can you show us a frame with debugger running (and possibly with all its scrollbars). 

Also, can you show us a screen console view without 'debug' tab added (or, you plan to get the debug tab added from beginning)?

**Comment by piotrzarzycki21** [comment]
Without Debug:

![console_only_view](https://user-images.githubusercontent.com/24554795/40487322-1ad9064e-5f64-11e8-8cc6-797b276e4d06.png)

With Debugger running:

![with_debugger_running](https://user-images.githubusercontent.com/24554795/40487328-21bee6b8-5f64-11e8-8b7f-4d24414de5b7.png)

**Comment by rat-moonshine** [comment]
How you plan to close the debugger view. Do you plan to add close button to the view?

**Comment by piotrzarzycki21** [comment]
Current open/close is being done by menu View -> Debug View. Do you think that I should add close button or is it enough ? 

Does FB have some Tabs - Do you have there close button ? 
In intellij there is no close button on Debug or Console tabs. You can close them only through the menu.

**Comment by rat-moonshine** [comment]
In my opinion, having a close button to the tab would be handy, but probably not to the console tab. In FB it has close buttons to its tabs.

**Comment by rat-moonshine** [comment]
A few more suggestion after last night's discussion:

- New tab styles should follow the styles that in editor tab (i.e. font-size, background-color) so that it do not looks like off-IDE style
- A darker background color is suitable in "Variables" and "Call Stack" row

**Comment by piotrzarzycki21** [comment]
* The tab styles are follow the same rules as in editor tab - the difference is one - Gradient. Tabs in editor are MX controls where gradient has been made "manually". My Tabs are fully spark components and I have no idea how to replicate those gradient at all. Feel free to try it out once I finish work on that.

**Comment by rat-moonshine** [comment]
Please check its both font-size and background color/gradient. I think a close solid color would look decent, too.

**Comment by piotrzarzycki21** [comment]
I just a finished adding close button to bottom panel. I applied also your suggestion with font-size etc. It looks much closer to editors Tab.

![debug_incative](https://user-images.githubusercontent.com/24554795/40542314-017b16b2-6020-11e8-943e-3298561d2704.png)

![debug_active](https://user-images.githubusercontent.com/24554795/40542317-04cad67c-6020-11e8-963e-b181b3843328.png)

It think this darker background color in Grids can be changed once you see it on your end. I will merge that one soon.

**Comment by atingupta2005** [comment]
I tested and have few suggestions:

1. In Debug console, there are 2 TABS - Variables, Call Stack. These headers should be Centre Aligned, Bold and underlined.
2. "Variable" should be renamed to "Variable Name"

**Comment by atingupta2005** [comment]
While debugging I came across with few errors. Attaching the screenshots for your reference

![screen shot 2018-05-26 at 9 16 43 am](https://user-images.githubusercontent.com/3568735/40572315-47374864-60c6-11e8-8023-6e733e214c86.png)
![screen shot 2018-05-26 at 9 16 10 am](https://user-images.githubusercontent.com/3568735/40572316-4764170e-60c6-11e8-8c04-0ebe6ae21a25.png)

**Comment by piotrzarzycki21** [comment]
@atingupta2005 in the other way the debugger didn't work for you at all for Flex project ? Can you share console output ?

**Comment by atingupta2005** [comment]
It worked but out of 4 times it thrown the error reported

**Comment by atingupta2005** [comment]
Here is the console output:


: Compiling FD260518
: Sending to mxmlc: mxmlc -load-config+=obj/FD260518Config.xml -optimize=false +configname=air -debug=true -o bin-debug/FD260518.swf
: Apache Flex Compiler SHell (fcsh)
: Version 4.16.0 build 20170305
: Copyright 2017 The Apache Software Foundation.
: (fcsh) 
: FSCH target: 1
: fcsh: Assigned 1 as the compile target id
: Loading configuration file /Users/atin/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.0_AIR_25.0/frameworks/air-config.xml
: Loading configuration file /Users/atin/Documents/MoonshineProjects/FD260518/obj/FD260518Config.xml
: bin-debug/FD260518.swf (1007606 bytes)
: Project Build Successfully.

**Comment by piotrzarzycki21** [comment]
I was thinking about it more and I come to conclusion that we actually don't need at all "Variables" and "Call Stack" headers. No need to occupy spaces. - My proposition is to remove them.

I renamed also columns: "Variable" to "Variables", "Value" to "Values", "Stack Frame" to "Frames"

What do you think ? 

![debugger_without_headers](https://user-images.githubusercontent.com/24554795/40797378-45a87fea-6508-11e8-8f75-1886993995ca.png)

Above changes are not committed yet.

**Comment by rat-moonshine** [comment]
It's a good choice. Those acquiring spaces were looking weird. Now this looks much slimmer.
