### ISSUE TITLE
ANE folder setting lost

### ISSUE THREAD

**Issue by Nisaba** [prominic/Moonshine-IDE#216]
Hello,

Everytime I change project or when I launch Mooshine (1.10.0), the _project/Settings/Paths/Native extensions folder_ setting is cleared.

Please fix, thanks a lot.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine could you look into that. I'm off tomorrow. Would be great to fix that for the next release. 

Thanks!

**Comment by rat-moonshine** [comment]
Fixed. To be release in next version.

**Comment by JoelProminic** [comment]
This worked fine in my tests.
