### ISSUE TITLE
Double-Clicking Binary File Breaks Tabs

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#218]
I accidentally double-clicked a binary file in the Project sidebar while testing #215, and it caused Moonshine to stop working properly:
1. Open the MoonshineDESKTOPevolved project in Moonshine
2. Double-click build/ant-contrib-0.6.jar - nothing happens
3. Close another tab.  BUG:  Moonshine shows a grey screen
4. Try to open another tab.  BUG: Nothing happens 

In another test, Moonshine would not even close properly, and I had to kill the processes.  I could not reproduce this case, though.

In this case, I would expect Moonshine to report an error saying that it cannot open the file.   This would be something like "Unable to open %file%:  no suitable editor" or "Unable to open binary file %file%.", depending on the actual implementation of this logic.

**Comment by rat-moonshine** [comment]
On the context, I also able to notice the kind of grey tab open behavior when double-clicked a file with .scpt extension.

**Comment by rat-moonshine** [comment]
On .scpt file problem, I noticed that opening the file to any other text editor results non-readable or machine language:
![image](https://user-images.githubusercontent.com/24370870/38186272-bb88b0e4-366f-11e8-806f-b79ed2de9017.png)

Perhaps, this is the reason why it's failed somewhere in the Moonshine editor.

**Comment by rat-moonshine** [comment]
While looked into the binary file handling during file open command, I noticed that existing source was trying to open the content with an AIR HTML window. I'm not sure why this behavior was. Current behavior will alert user about the problem opening to Moonshine editor, and also give choice to open the file with its default application.

**Comment by JoelProminic** [comment]
I revisited this issue for the 1.11.0 release.  The current behavior looks good to me on macOS.
