### ISSUE TITLE
Interaction Between Global Search and Copy/Paste

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#219]
Follow these steps.
1. Global search ctrl-H for a phrase in an open project
2. Click on one of the files in which phrase has been found.
NOTE: This problem does not occur if you select the file from the Projects panel.
3. In the open file the phrase is highlighted. Select the phrase with the mouse and click ctrl-F.
4. Select something else in this file or another file and Copy.
5. Paste this into the Replace input on the Finder.
6. The original searched phrase is pasted.
7. Open Notebook or equivalent and Paste. The last copied phrase is pasted so Clipboard is correct.

Doug

**Comment by rat-moonshine** [comment]
Hello @doug777 , thank you for reporting. 

With my quick tests, I couldn't able to re-produce this issue in Windows. Step 5-6 always performed for me expectedly. Can you confirm if this problem is producible to you every time, or at a certain time?

Thanks!

**Comment by doug777** [comment]
You're right. I can't reproduce it today. When it occurred I tried with different phrases and it consistently produced the effect reported, but today it works perfectly. If it happens again, Ill try to find out what is triggering the problem.

Doug

**Comment by rat-moonshine** [comment]
Thank you for confirming this @doug777 . Please, do report if any other problem you would found, or reopen this issue. Thanks!
