### ISSUE TITLE
Failed to get compile settings for +configname=flex - in attempt of building library

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#221]
I'm getting from language server error `Failed to get compile settings for +configname=flex` when I'm trying to build library or open one of the class.

**Scenario:**
1. Open attached Flex library project in Moonshine
1. Open MyClass file - if error do not occur after a while
1. Try build project

![image](https://user-images.githubusercontent.com/24554795/38361770-c8ee85ea-38ce-11e8-824c-06ed781e54d3.png)

[TestLibProject.zip](https://github.com/prominic/Moonshine-IDE/files/1879610/TestLibProject.zip)

**Comment by joshtynjala** [comment]
This is probably the first time that someone has tried using code intelligence with a library project in Moonshine. 😄 

It was only working with app projects until now.

**Comment by piotrzarzycki21** [comment]
Hah! :) Daily usage of IDE that's the best tests ever. :) Thanks for fixing! :)

**Comment by piotrzarzycki21** [comment]
Working :)

**Comment by JoelProminic** [comment]
I get this error when opening the MoonshineSharedCore library project using the latest Moonshine 1.13.0 builds from Bamboo (on both MacOS and Windows):

    : Failed to get compile settings for +configname=flex.

I checked the official 1.13.0 release, and I do not see this error.
