### ISSUE TITLE
Doesn't work with AIR SDKs or macOS High Sierra 

### ISSUE THREAD

**Issue by mikewach-jamcity** [prominic/Moonshine-IDE#223]
Doesn't recognize any of the AIR SDKs and cannot compile with older SDKs on macOS High Sierra due to lack of 32-bit JVM support

**Comment by piotrzarzycki21** [comment]
Hi @mikewach-jamcity ,

Can you specify a bit more details on that ? Did you download pure [Adobe Air SDK](https://www.adobe.com/devnet/air/air-sdk-download.html) or are you talking about something else ?

**Comment by mikewach-jamcity** [comment]
Thanks for your response, @piotrzarzycki21 !

I am currently running macOS High Sierra 10.13.3 (however plan to update to 10.13.4 tonight). I have tried all of the following SDKs:

AIR19
AIR 22
AIR 25
AIR 26
AIR 27
AIR 28
AIR 29
Feathers SDK 3.3.0 FP26.0 AIR26.0 en_US
Flex 3.6A (Bundled with Flash Builder)
Flex 4.60 (Bundled with Flash Builder)

Out of all of the above, only the last three SDKS are recognized by Moonshine. When I try to use either of the two Flex SDKs, I can not compile because I do not have a 32-bit Java installation. After briefly searching the web for how to get that for High Sierra, I could not find any obvious solution, so ended up abandoning Moonshine on Mac :'(

As an aside, my goal was to compile the SWFInvestigator project using Moonshine:
https://sourceforge.net/adobe/swfinvestigator/wiki/Home/

**Comment by piotrzarzycki21** [comment]
Hi @mikewach-jamcity ,

It looks on the Moonshine sight everything is ok. First of all swfinvestigator is an Adobe Air Windowed application written in Flex framework. Moonshine do not recognize pure Adobe Air SDK. 
You need to download [Apache Flex SDK](https://flex.apache.org/) and setup project in Moonshine. 

[Apache Flex have installer](https://flex.apache.org/installer.html) which should help you download everything. Installer have some problems on Windows, but on Mac you should smoothly download everything.

1. Once you do that point in Moonshine folder with Apache Flex SDK. 
1. Checkout repository of swfinvestigatior -> https://svn.code.sf.net/adobe/swfinvestigator/code/trunk
All project in the repository are configured with Flash Builder - Moonshine is able to open such projects!
1. Open in Moonshine folder **SWFInvestigator** using in Home tab option: **Open Apache Flex/JS project...**
1. Right click on the opened project and choose **Settings**
1. Go to **Build options** and add in **Additional compiler options** -> `+configname=air`
1. Go to the tab **Paths** and configure the same as on my screenshot:
![image](https://user-images.githubusercontent.com/24554795/38664529-329cffa6-3e3a-11e8-85d6-25d119f0d143.png)
1. Choose **Project** -> **Build Project** - I'm getting following errors once I build - you have to probably figure out why does images are not being seen. 

```
Compiling SWFInvestigator
: Sending to mxmlc: mxmlc -load-config+=obj/SWFInvestigatorConfig.xml +configname=air -locale=en_US -debug=true -o bin-debug/SWFInvestigator.swf
: Apache Flex Compiler SHell (fcsh)
: Version 4.16.1 build 20171115
: Copyright 2017 The Apache Software Foundation.
: 
: (fcsh) 
: FSCH target: 1
: fcsh: Assigned 1 as the compile target id
: Loading configuration file D:\Work\flex-sdk-4.16.1_adobe_air_28\frameworks\air-config.xml
: Loading configuration file D:\Work\projects\Others\swfinvestigator\SWFInvestigator\obj\SWFInvestigatorConfig.xml
: D:\Work\projects\Others\swfinvestigator\SWFInvestigator\src\utils\AMFFuzzer.mxml(36): Error: unable to resolve 'assets/fuzzer/ErrorImage.jpg' for transcoding
: 
: 			[Embed(source="assets/fuzzer/ErrorImage.jpg")] 
: 
: D:\Work\projects\Others\swfinvestigator\SWFInvestigator\src\utils\AMFFuzzer.mxml(36): Error: Unable to transcode assets/fuzzer/ErrorImage.jpg.
: 
: 			[Embed(source="assets/fuzzer/ErrorImage.jpg")] 
: 
: D:\Work\projects\Others\swfinvestigator\SWFInvestigator\src\utils\xssFuzzer\xssPanel.mxml(30): Error: unable to resolve 'assets/fuzzer/ErrorImage.jpg' for transcoding
: 
: 			[Embed(source="assets/fuzzer/ErrorImage.jpg")] 
: 
: D:\Work\projects\Others\swfinvestigator\SWFInvestigator\src\utils\xssFuzzer\xssPanel.mxml(30): Error: Unable to transcode assets/fuzzer/ErrorImage.jpg.
: 
: 			[Embed(source="assets/fuzzer/ErrorImage.jpg")] 
: 
```

I'm providing you above instruction to guide how to use Moonshine. As you can see you have all things which you need. Let me know if you have any problems farther.

**Comment by mikewach-jamcity** [comment]
Wow, thank you so much for all of this information @piotrzarzycki21 !! So it seems I should try to migrate the SWFInspector project to a newer Apache Flex SDK, and this is indeed not an issue specific to Moonshine. I will give the above steps a try soon and report back my findings! Thanks again!!!

**Comment by rat-moonshine** [comment]
If this issue has been addressed can we close this now @piotrzarzycki21 ?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I think yes. @mikewach-jamcity please reopen if you have any problems and you will think it's related to Moonshine.
