### ISSUE TITLE
OSMF download failed

### ISSUE THREAD

**Issue by ehbarrioss** [prominic/Moonshine-IDE#224]
OSMF download failed
Instalación cancelada: http://flex.apache.org/track-installer.html?failure=true&label=Apache Flex SDK 4.16.1&version=4.16.1&os=windows&installerversion=1.10.0&info=&info=OSMF%20download%20failed

**Comment by piotrzarzycki21** [comment]
Hi @ehbarrioss ,

This is the issue in the installer of Apache Flex itself. I will probably get hands on that and try to fix it. In the meantime you got and download Apache Flex using ANT. I described instruction [here](http://apache-flex-users.2333346.n4.nabble.com/Flex-Installer-Air-29-OSMF-Fail-Windows-tp16774p16775.html).

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Generally yesterday I did push fix for that issue to the installer. However I see something more where downloading playerglobal.swc is failing and I'm not sure why. If I eliminate this one you can than take the code from develop branch of the installer and apply to our codebase. 
I will start release process in Apache Flex project, but it may take much more time. 

I will let you know once I sorted out issue with playerglobal.swc

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have finished tests. Installer for Windows has been fixed. I will start release process, but you can simply checkout latest changes from [develop](https://github.com/apache/flex-utilities/tree/develop) branch and apply in Moonshine.

**Comment by rat-moonshine** [comment]
Both Moonshine App Store Helper and in-build Apache SDK Installer (Windows Moonshine) applied by the patch fix on OSMF download. However, I couldn't able to run a proper test today as I'm having continuous download failing problem against AIR SDK. 

I have tried to download 28/29 AIR SDK multiple times across macOS and Windows system, but everytime it failed at following stage:

> Installer version 3.3.0 (windows)
> Using Locale: en_US
> Fetched the SDK download mirror URL from the CGI.
> SDK version Apache Flex SDK 4.16.1
> AIR version 29.0
> Flash Player version 29.0
> Creating Apache Flex home
> Creating temporary directory
> Downloading Apache Flex SDK from: http://www-us.apache.org/dist/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.zip
> Verifying Apache Flex SDK MD5 Signature
> The Apache Flex SDK MD5 Signature of the downloaded files matches the reference. The file is valid.
> Uncompressing: E:\ApacheFlexSDK\4.16.1_AIR_29.0_2\temp\apache-flex-sdk-4.16.1-bin.zip
> Finished uncompressing: E:\ApacheFlexSDK\4.16.1_AIR_29.0_2\temp\apache-flex-sdk-4.16.1-bin.zip
> Downloading Adobe AIR Runtime Kit for Windows from: http://airdownload.adobe.com/air/win/download/29.0//AdobeAIRSDK.zip
> Validating download: E:\ApacheFlexSDK\4.16.1_AIR_29.0_2/in/AdobeAIRSDK.zip
> AIR SDK download failed
> Installation aborted: http://flex.apache.org/track-installer.html?failure=true&label=Apache Flex SDK 4.16.1&version=4.16.1&os=windows&installerversion=3.3.0&info=&info=AIR%20SDK%20download%20failed

It's possible that I might having any strange network problem here. I have committed the updated SWC. @piotrzarzycki21 if you want you can download the latest SWC and test it on Windows.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just updated hash on the website and tested your installer update and it's working nicely! :) 

Fix was concerns only Windows in fact. I'm closing this one. If you will have any problem reopen.
