### ISSUE TITLE
Update Shortcut for Project > Search

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#225]
The previous shortcut for Project > Search was CMD-H / CTRL-H.  However, the MacOS shortcut was overwritten by the default Moonshine > Hide Moonshine action (See #162).

I discussed this with @rat-moonshine, and we propose to change the Project > Search shortcut to CMD-Shift-F.  

This shortcut was previously mapped to Edit > Find Previous, but we found that this action was obsolete.  Find Previous was supposed to go to for the previous match for the current search string, without opening the Find/Replace prompt.  CMD-F was the forward search version of this action, but we decided that we wanted this shortcut to always open the Find/Replace prompt instead.  (If there is interest in shortcuts for Next/Previous matches, we could create a separate issue.  IntelliJ uses CMD-G and CMD-Shift-G for these actions.)

Since the Windows commands are not affected by the command overlap, we could leave them the same.  I think CTRL-Shift-F is a more intuitive command, though.   

@piotrzarzycki21, @joshtynjala , do you use the current shortcut for the Project > Search functionality?  Do you have any objections to the above changes?

**Comment by rat-moonshine** [comment]
As discussed:
- "Search Previous" removed for now
- New shortcut keys associated to project search (Ctrl/CMD+Shift+F)

**Comment by piotrzarzycki21** [comment]
I'm sorry for the late response. I like shortcuts. It's the same as in Intellij :)
