### ISSUE TITLE
Search Order for Edit > Find

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#226]
While I was experimenting with the shortcuts for #225, I noticed that the result order for Edit > Find was strange.

I tested using our default Application class for Flex AIR projects:
```
<?xml version="1.0" encoding="utf-8"?>
<s:WindowedApplication xmlns:fx="http://ns.adobe.com/mxml/2009" 
					   xmlns:s="library://ns.adobe.com/flex/spark" 
					   xmlns:mx="library://ns.adobe.com/flex/mx" minWidth="955" minHeight="600">
			   
	<fx:Declarations>
	</fx:Declarations>
	
	<fx:Script>
		<![CDATA[
			
		]]>
	</fx:Script>
	
	<s:Label fontSize="24" fontWeight="bold" textAlign="center"
		horizontalCenter="0" verticalCenter="0"
		text="Hello World!"/>
</s:WindowedApplication>
```

In my tests, I put the cursor at the top of the file to start, so I would expect the search entries to be highlighted in the order that they appeared in the file.  

However, when I searched for "center", the first result was horizontalCenter, then textAlign="center", and finally verticalCenter.
![image](https://user-images.githubusercontent.com/24532731/38511706-8f4a0878-3bee-11e8-820f-b2ab75696750.png)

When I searched for "fx", the order was even more strange.  See my screenshot below.
![image](https://user-images.githubusercontent.com/24532731/38511696-89f11e3e-3bee-11e8-9bb6-9f251f32b534.png)

**Comment by rat-moonshine** [comment]
Fixed. Please, check.

**Comment by JoelProminic** [comment]
I ran some tests on the macOS build, and the search order seems fine now.  I tested with:
- Cursor at the top of the page
- Cursor in middle at page - the next match after the cursor was selected first
- Searching for one string, and then switching to a different string - Moonshine showed the first match of the new string after the current match of the old string.
