### ISSUE TITLE
Code Completion doesn't work with newly created project

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#230]
I have discovered that with all latest changes related to language server for newly created project code completion doesn't work.

Scenario:
1. Create new Flex/Royale project
2. Try to launch code completion in MXML

It doesn't work because of following error:
`unable to open 'D:\Work\projects\Prominic.NET\MoonshineTests\TestRoyaleProject\obj\TestRoyaleProjectConfig.xml'.`

However that file is being created once we build the project. If I make the build Code Completion is back again.

[TestRoyaleProject.zip](https://github.com/prominic/Moonshine-IDE/files/1902775/TestRoyaleProject.zip)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have assigned this one to you, because you know the logic around creation of config file, so maybe you will have some insight.

**Comment by rat-moonshine** [comment]
> It doesn't work because of following error:
> unable to open 'D:\Work\projects\Prominic.NET\MoonshineTests\TestRoyaleProject\obj\TestRoyaleProjectConfig.xml'.

Where did you able to get this error @piotrzarzycki21 , I didn't seen this error during my debug tests. 

However, I noticed server shutdown after opening a Royale/MXML file and when tried to write something:

> : Apr 12, 2018 5:54:13 PM org.xsocket.connection.Server$LifeCycleHandler onConnected
> : INFO: server listening on 0:0:0:0:0:0:0:0:62187 (xSocket 2.8.15)
> : Apr 12, 2018 5:54:25 PM org.xsocket.connection.Server$LifeCycleHandler onDisconnected
> : INFO: server (0:0:0:0:0:0:0:0:62177) has been shutdown

**Comment by piotrzarzycki21** [comment]
@rat-moonshine it's in the Problems View!

**Comment by rat-moonshine** [comment]
Ah, I did not noticed this. I'm wondering why its trying to look for the <project>Config.xml file when its not written. Perhaps we can add some condition to somehow prevent the language-server from check this. I need to look into this.

**Comment by piotrzarzycki21** [comment]
Let's wait also for a Josh insight, because maybe it's require right now for some reason.

**Comment by joshtynjala** [comment]
That config file is how the compiler options are passed to the compiler for a build, right? The language server needs to know the same options so it loads them from the same file.

I could check if the file exists or not, but I suspect that will cause some complier options to be missing.

**Comment by rat-moonshine** [comment]
@joshtynjala , generally this config file creates during project compilation. Do you think if we generates the config during project creation, and before language-server initiate against the project, that would fix the issue and also cover other necessities to code-completion?

**Comment by joshtynjala** [comment]
If there's another API for me to get a list of all of the same compiler options that are passed to the compiler, I can certainly use that instead.

Otherwise, this config file needs to be created or updated whenever changes to the project settings result in changes to the compiler options.

**Comment by rat-moonshine** [comment]
That is a good idea that if Moonshine can pass you the properties those you need, internally. This will eliminate the need of config file presence to run the code-completion menu. 

`actionScripts.plugin.actionscript.as3project.vo.MXMLCConfigVO` file is responsible to generate the config file. Can you please take a look if you can use the fields mentioned in `writeApplicationConfig()` to satisfy the needs to the language-server, @joshtynjala ?

**Comment by joshtynjala** [comment]
@rat-moonshine I worry that any changes to MXMLCConfigVO.writeApplicationConfig() in the future would not get reflected in both locations. I see that MXMLCConfigVO.writeLibraryConfig() appears to be used for library projects too. I would need to duplicate the subset of compiler options used by both of these methods in LanguageServerForProject. That seems like a pretty serious code smell to me. I had a similar issue in VSCode recently, and I consolidated the compiler options parsing between the language server and asconfigc so that they'd always be in sync.

I think it would be much better if the subset of compiler options written to this config file could be made available from a common API that MXMLCConfigVO.writeApplicationConfig() and LanguageServerForProject could both call.

Alternatively, I see that MXMLCConfigVO has a public write() method:

``` actionscript
public function write(pvo:AS3ProjectVO):void
```

Would it be possible for me to use this method when I need the config file in LanguageServerForProject? Maybe like this?

``` actionscript
var vo:MXMLCConfigVO = new MXMLCConfigVO(_project.config.file);
vo.write(_project);
```

That would guarantee that the file exists for the language server, and the subset of compiler options would be the same, even if changed in the future.

**Comment by rat-moonshine** [comment]
@joshtynjala , thank you for explaining this in length. 

If you have the AS3ProjectVO object, you can use its own declared MXMLConfigVO object as well. You probably want to check if the config file exists, and then you can call the `write` method this way:

```
_project.config.write(_project);
// - or -
_project.updateConfig(); 
```

**Comment by piotrzarzycki21** [comment]
I also noticed that debugging is not working properly in Flex. I don't get any values when I have break point in place. Maybe language server do not get enough information to launch debug mode.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 The language server is not used for debugging. The debugger is separate. I don't think I've modified the debugger in any way that would cause this behavior, though...
