### ISSUE TITLE
Away Builder tab remains open once project has been closed

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#233]
**Scenario:**

1. Create Away Builder project
2. Open *.awd file from assets
3. Right click on the project and close

**Results:** 
- Away Builder tab remains opened

**Expected Results:**
- Away Builder tab should close along with the project

![away_builder_project_issue](https://user-images.githubusercontent.com/24554795/38808696-5b0aa9ee-4181-11e8-8a98-1518cac34a31.gif)

**Comment by rat-moonshine** [comment]
Thank you for pointing to this side, @piotrzarzycki21 . This should be valid against project deletion, too. Initialising the editor (Away Builder) with a blank document in that case would be more acceptable, you think Piotr?

**Comment by piotrzarzycki21** [comment]
I actually like that some object is showing there initially, but I'm leaving to you decision. Don't have strong opinion on that.

**Comment by rat-moonshine** [comment]
Showing any initial object means that loads by any file, or an unsaved project that requires to save somewhere. When a project is closed or deleted, both the cases may create confusion. I think re-initialize the editor as a blank document would fit more in this case. I also talk on this with @JoelProminic when I'll have time.

**Comment by rat-moonshine** [comment]
Away Builder project close/deletion now updated with following changes:

- If the Away Builder editor has any modification, during project close Moonshine will prompt to save in a regular manner like it does for other modified editors. Based on the choice Moonshine will either save the Away Builder editor or just populate the editor with a new blank document
- During project deletion Moonshine will ask with project deletion prompt, upon accept Moonshine will delete the project files and populate the Away Builder editor with blank document

**Comment by piotrzarzycki21** [comment]
Unfortunately it is still doesn't work for me. The behavior is a bit different look to the gif. 

![away_builder_project_issue](https://user-images.githubusercontent.com/24554795/38856456-ce2740e0-4226-11e8-87bd-bc9dcc38d6df.gif)

**Comment by rat-moonshine** [comment]
I'm unclear with the difference you tried to mention. Can you please clarify?

**Comment by piotrzarzycki21** [comment]
Compare gif in the main description with new one. Once I choose "Close" from context menu in the original one object in Away Builder is staying. In new GIF object disappear.

**Comment by rat-moonshine** [comment]
I'm not sure what are you are expecting. If the project will close (that belongs to the file that you have opened to the Away Builder editor), the editing file also is closing. The Away Builder just populating with a blank document in this case since the tab is non-closeable at this moment.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just thought that when project is working Away Builder Tab is not being closed, but if user close/delete project we will close Tab no matter what.

**Comment by rat-moonshine** [comment]
If you tried to mean to close and re-open the Away Builder tab, that investigation is created as a separate [issue](https://github.com/prominic/Moonshine-IDE/issues/227). For this issue fix, we were discussing on populating the editor with a new document for now. Please confirm if that is working for you or not.

**Comment by piotrzarzycki21** [comment]
That part is working! Thanks! I'm sorry for the confusion.

**Comment by rat-moonshine** [comment]
I'm glad that the plan for this issue is now clear, @piotrzarzycki21 .

**Comment by JoelProminic** [comment]
The behavior seems to work fine for both closing and deleting a project.
