### ISSUE TITLE
Renaming a newly created project template is not working

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#238]
I have seen this during my recent tests to menu generation section. However, I don't think we need hold the 1.11.0 release for this. We can move this issue to the 'known issue' section for now.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Please update then CHANGELOG with your finding. For 1.11.0 there is section for that.

**Comment by piotrzarzycki21** [comment]
Cool you did it! :) Sorry about that!

**Comment by rat-moonshine** [comment]
I mistakenly thought that this issue is yet to be resolve, thus moved the issue to 'Feature' from 'Next Release' sprint. As I see it's already fixed, restored back to 'Next Release'.

**Comment by JoelProminic** [comment]
I confirmed that I can rename a template.  The template name is updated immediately under File > New.

I noticed that the custom templates do not appear on the Home screen.  Is this intentional?

**Comment by rat-moonshine** [comment]
> I noticed that the custom templates do not appear on the Home screen. Is this intentional?

Yes, it is intentional.
