### ISSUE TITLE
Improvement to Find/Replace

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#24]
When using Find/Replace if you can't Replace All it would save a lot of time if after clicking Replace One, it automatically stepped onto Next. At present you have to continually click Next>One>Next>One and so on.

Doug

**Comment by rat-moonshine** [comment]
Hi Doug,

'All' is the option particularly for this (replace all). Have you tried this out?

![image](https://user-images.githubusercontent.com/24370870/31326982-927e7ce8-ace9-11e7-82af-fae5dd5adbf5.png)
