### ISSUE TITLE
Make property panel in Visual Editor toggleable

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#240]
Property panel and list of components in Visual Editor is not always needed. This issue will be used for handle feature which allows close it - similar to the Console View in Moonshine.

**Comment by piotrzarzycki21** [comment]
Here is the result of changes:
![closeable_panels_ve](https://user-images.githubusercontent.com/24554795/40173170-3b31ab0a-59d1-11e8-8076-f66653338c51.gif)

**Comment by atingupta2005** [comment]
Its working as expected
