### ISSUE TITLE
All the UI components are reposition to the Left Top position

### ISSUE THREAD

**Issue by atingupta2005** [prominic/Moonshine-IDE#243]
Hi, 

While testing I found that all the UI components are reposition to the Left Top position if I Close and Open the Project again. Attached are the screenshots:

**The screenshot before closing:**

![screen shot 2018-04-25 at 12 23 43 pm](https://user-images.githubusercontent.com/3568735/39230518-60463482-4884-11e8-9459-bfce0482aae4.png)

**The screenshot after closing and then opening again:**

![screen shot 2018-04-25 at 12 23 58 pm](https://user-images.githubusercontent.com/3568735/39230519-608c7154-4884-11e8-9a7a-d5a87b6c1f15.png)

Below is the code:

<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui">
  <h:head>
    <link rel="stylesheet" type="text/css" href="resources/layout-styles.css"/>
    <title/>
  </h:head>
  <h:body>
    <div class="flexHorizontalLayout flexHorizontalLayoutLeft flexHorizontalLayoutTop" style="width:700px;height:450px;">
      <div style="width:476.5px;height:404.5px;" class="flexHorizontalLayout flexHorizontalLayoutLeft flexHorizontalLayoutTop">
        <p:fieldset style="width:441.5px;height:362.5px;" legend="Basic" toggleable="false" toggleSpeed="200">
          <p:inputText style="width:100px;height:30px;" value=""/>
          <p:inputText style="width:100px;height:30px;" value=""/>
          <p:inputText style="width:100px;height:30px;" value=""/>
          <p:inputText style="width:100px;height:30px;" value=""/>
          <p:inputText style="width:100px;height:30px;" value=""/>
          <p:outputLabel style="width:100px;height:30px;" value="Designation"/>
          <p:outputLabel style="width:100px;height:30px;" value="Email"/>
          <p:outputLabel style="width:100px;height:30px;" value="Contact No"/>
          <p:outputLabel style="width:100px;height:30px;" value="Name"/>
          <p:outputLabel style="width:100px;height:30px;" value="Address"/>
        </p:fieldset>
      </div>
    </div>
  </h:body>
</html>

Thanks
Atin

**Comment by piotrzarzycki21** [comment]
It happened because we are not care on the Flex sight x and y properties. It is because in HTML there is not such things. I'm going to put to the Fieldset Div component as default and give user ability to manipulate children as it we have currently in Div. 

I may break current project which you have created, but it should not be an issue since we were not released yet PrimeFaces stuff.

**Comment by piotrzarzycki21** [comment]
@atingupta2005 I just pushed fix for that issue. From now on Fieldset will have predefined behavior which we were able to mimic from HTML world. Let me know if it is satisfactory.

**Comment by piotrzarzycki21** [comment]
Reopen if it won't be enough.

**Comment by atinprominic** [comment]
But now the position of the UI controls can't be changed and all the elements are being positioned one after the other.

Please check the attached screen recording.
![vereposition090518](https://user-images.githubusercontent.com/34882311/39802397-89f6c852-538b-11e8-8658-f59ffea2891b.gif)

**Comment by piotrzarzycki21** [comment]
@atingupta2005 your Div is cut - I don't see any control in eat which you are dropping. Please record whole moonshine area. 

As for your concerns - Yes as default your controls will be laying out horizontally - you can change laying out them vertically in property editor etc. We are mimic partially Div behavior in browser.
