### ISSUE TITLE
Dragging the controls for repositioning does not work sometimes

### ISSUE THREAD

**Issue by atingupta2005** [prominic/Moonshine-IDE#244]
While I am dragging the UI controls on the design pane, it seems to be difficult as the dragging functionality doesn't work all the times. I need to try multiple times for dragging before it works.

**Comment by rat-moonshine** [comment]
Can you report this with some basic screen recording, @atingupta2005 ? You can use ScreenToGif tool to record the problem.

Also, please confirm if is this re-producible every time?

**Comment by atingupta2005** [comment]
Attached below is the recorded GIF.

![vedragging](https://user-images.githubusercontent.com/3568735/39292051-982f8672-4952-11e8-8b86-407f6fcc1d4f.gif)

**Comment by piotrzarzycki21** [comment]
@atingupta2005 I think you won't have anymore problems with Fieldset - because positioning is from now on like in Div component.
