### ISSUE TITLE
Label and InputText should be together

### ISSUE THREAD

**Issue by atingupta2005** [prominic/Moonshine-IDE#245]
The controls in control palate - Label and InputText should be together as the user mostly uses these 2 controls frequently together. Currently the user has to scroll up and down to pick each control one by one from the palate.

**Comment by piotrzarzycki21** [comment]
I'm not sure if we should do that. In most Visual Editors those components are separate. Even in PrimeFaces.

**Comment by rat-moonshine** [comment]
As we don't have any plan to introduce new component 'set' (multiple components in a group) I'm closing this issue. User can still group components and copy/paste them to reuse when #248 is over.
