### ISSUE TITLE
Some features to enhance Visual Editor

### ISSUE THREAD

**Issue by atingupta2005** [prominic/Moonshine-IDE#246]
- It would be very convenient to CTRL C and CTRL V to copy and paste the UI Controls. We can also provide CTRL D to duplicate the selected UI control.

- The UI control property to specify the validations like - Required, Range etc would be very helpful.

- The labels of the UI controls should be space separated. Refer to below screenshot:

![screen shot 2018-04-25 at 12 51 33 pm](https://user-images.githubusercontent.com/3568735/39231402-7eaef2bc-4887-11e8-91fb-408a4c95260a.png)

In this screen shot the InputMask should be written as - Input Mask, InputText as Input Text and so on.
 
- The Undo and Redo features are the one which are very much required in any IDE. I strongly recommend to have them. I have not found those in the Edit menu.

**Comment by piotrzarzycki21** [comment]
I believe name of the components should stay as it is, because they are the same as in PrimeFaces. The rest of the points are definitely valid.

**Comment by rat-moonshine** [comment]
Do we want to have a separate issue on this, @piotrzarzycki21 ?

> The UI control property to specify the validations like - Required, Range etc would be very helpful

Most of the suggestions has raised as separate issues, perhaps its good to close this one.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I think we should raise separate issue. What do you mean by validations ? In property editor ?

**Comment by rat-moonshine** [comment]
As one suggestion goes by @atingupta2005 , 

> The UI control property to specify the validations like - Required, Range etc would be very helpful

Do PrimeFaces components does have any such in-build validation methods, i.e. setting max characters etc. (although I'm not very sure about request either).

**Comment by piotrzarzycki21** [comment]
I haven't seen any validation mechanism in such components. In flex if you put errorString it will show red border around component. In PrimeFaces it seems that we need to use for example InputMask to achieve something.

**Comment by rat-moonshine** [comment]
If we're unsure about such thing, then let's close this issue. Other important issues already raised as separate issues and will follow separately.

**Comment by piotrzarzycki21** [comment]
Issues has been handled separately respectively #247, #248
