### ISSUE TITLE
Introducing Undo/Redo in Visual Editor

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#247]
[This is a sub-issue from features requested in #246 ]

From @atingupta2005,

> The Undo and Redo features are the one which are very much required in any IDE. I strongly recommend to have them. I have not found those in the Edit menu.

## Optional:
The undo/redo feature is already available to Moonshine text editor, however, the options are not in the application's `Edit` menu in a fashioned manner. I personally don't use this feature from menu options, but we can consider the features to be available in the menu section.

## Required:
Visual editor on the other hand lack this issue, so this needs to be implemented. 

## Phase 1 Component List (PrimeFaces)
- [x] Button
- [x] InputMask
- [x] InputNumber (@piotrzarzycki21 - #260 )
- [x] InputText
- [x] InputTextArea
- [x] SelectBooleanCheckbox
- [x] OutputLabel
- [x] AutoComplete
- [x] TabView
- [x] Tree
- [x] DataTable
- [x] FieldSet
- [x] Include
- [x] Div
- [x] Grid

**Comment by rat-moonshine** [comment]
While testing these @JoelProminic reported following issues:

1. Add a Div
2. Change the Width to 240 - hit Enter to apply the change
3. CTRL-Z - the Width value changes to "2", but the window size does not change
4. CTRL-Z - the Div is removed
5. Click in the editor window.  If I don't do this, then CTRL-Y does nothing in step 6
6. CTRL-Y - the Div is restored at the modified size

Along with the above, I also need to check a null pointer exception with following steps:

1. Add a Div
2. Add three OutputLabel
3. Delete last two added label components
4. Hit Ctrl+Z multiple time to return both of them
5. It returns only one label but the other - at this stage I seen an exception

**Comment by rat-moonshine** [comment]
> - Add a Div
> - Add three OutputLabel
> - Delete last two added label components
> - Hit Ctrl+Z multiple time to return both of them
> - It returns only one label but the other - at this stage I seen an exception

Fixed.

**Comment by rat-moonshine** [comment]
> Click in the editor window. If I don't do this, then CTRL-Y does nothing in step 6

Measure taken to preserve focus to the stage after an item deletes in order to keep listening key press events.

**Comment by piotrzarzycki21** [comment]
I decided to write more thoughts about implementation here. 
**PropertyChangeReferenceVO class:**
This class is definitely do not looks like VO or Model. It get's view and make changes on the view. In my opinion following changes should be done:
1. This class should be moved to [view/supportClasses](https://github.com/prominic/MockupVisualEditor/tree/visual_editor_undo_redo_ref_247/src/view/suportClasses)
1. The name should indicate the functionality: `PropertyUndoManager` , `PropertyChangeManager`
1. That class contains methods `reverse ` and `restore ` and taking main class. Those methods should not take any parameters instead do what they are designed for. If you need container which holds component use parent instead. 
1. Method `restore`, `reverse` should be called `undo`, `redo`

**Undo/Redo properties**:
1. Almost each component should have ability to undo, redo. There may have been some exception and we should be ready. We should absolutely do not change `ISurfaceComponent` Please introduce new interface called `IUndoableSurfaceComponent` with following require properties/methods:

```
function get surfaceComponent():ISurfaceComponent;
function get fieldName():String;
function get fieldPreviousValue():Object;
function get fieldNewValue():Object;
function get isUpdating():Boolean; - Do you need that outside ?

function undo();
function redo();
```

1. Whenever you need to do something with manager and you are not sure whether component is Undoable use casting to check. In the other words following condition should be removed:

```
if (event.target.hasOwnProperty("propertyChangeFieldReference") &&
    event.target.hasOwnProperty("isUpdating") && !event.target.isUpdating)
```
Changed to something like this:

```
var undoableComponent:IUndoableSurfaceComponent = (event.target as IUndoableSurfaceComponent);
if (undoableComponent)
{
   //do something
}
```

**Comment by rat-moonshine** [comment]
Thank you for placing your detailed opinion, @piotrzarzycki21 . Following are my thoughts in-line. Please, check.

> This class should be moved to view/supportClasses

Sounds Okay to me. 

> The name should indicate the functionality: PropertyUndoManager , PropertyChangeManager

Although, this does created value object in mind, but it also has methods to affect view. I don't have any strong opinion to not to change the name, this will hardly affect the design.

> That class contains methods reverse and restore and taking main class. Those methods should not take any parameters instead do what they are designed for. If you need container which holds component use parent instead.

I do need to access `EditingSurface` component's `deleteItem(..)` method. Do you have a better idea how to access that without passing the reference as a parameter to reverse() restore()?

> Method restore, reverse should be called undo, redo

I agree. 

> Almost each component should have ability to undo, redo. There may have been some exception and we should be ready. We should absolutely do not change ISurfaceComponent Please introduce new interface called IUndoableSurfaceComponent with following require properties/methods

I probably agree to create a new interface `IUndoableSurfaceComponent` but I may not want to break the parts to many methods pieces. The current designed method `propertyChangeFieldReference` suppose to supply all we need.

> Whenever you need to do something with manager and you are not sure whether component is Undoable use casting to check. In the other words following condition should be removed

I already mentioned about this, until we implement the methods/properties to standard interface class we're doing `event.target.hasOwnProperty("propertyChangeFieldReference")` etc. just to keep our tests limited to a few certain components. These will be replace with proper codes in future.

**Comment by piotrzarzycki21** [comment]
> Although, this does created value object in mind, but it also has methods to affect view. 

It does create VO in mind, but it does not a VO. Value object or models are holding data and moving them to the other places. They are not doing anything with the data. This class is more like a controller or manager.

> I do need to access EditingSurface component's deleteItem(..) method. Do you have a better idea how to access that without passing the reference as a parameter to reverse() restore()?

You have and ISurfaceComponent in that manager. Since you do have it it means that you do have also the parent container to which that component has been added. You are not always adding component to the EditingSurfaces. Sometimes you are adding component to other compnent ex.

<Fieldset></Fieldest> - Added to EditingSurfaces - his parent should be EditingSurface
<Fieldset><Div></Div></Fieldset> - Div has been added to Fieldset, so parent is Fieldset. If you do CTRL+Z and than CTRL+Y where do you want to add back that component ? 
If I'm correct your solution of undo/redo is working like that. - Adding/Removing component from his parent - Am I right ? 

> I already mentioned about this, until we implement the methods/properties to standard interface class we're doing event.target.hasOwnProperty("propertyChangeFieldReference") etc. just to keep our tests limited to a few certain components. These will be replace with proper codes in future.

Agree, but It should not land in the master. In the other words after you test everything and you will be ready for the merge - That code should be change. Let's have clean code in the master.

**Comment by rat-moonshine** [comment]
You did not get me entirely. I do have its parent in an `ISurfaceComponent` class. But that need not to be EditingSurface (as you also pointed out) and I don't want to get in a logical check to understand which class' parent could be EditingSurface and in which case it's not. To call the deleteItem(..) method resides in EditingSurface, I need an easy access to the EditingSurface - my point is not here to just to addElement or removeElement call - I would suggest to check the deletion code suggestion on this case written in EditingSurface - 

```
/**
 * Do not call removeElement(). Calling deleteItem() will ensure that
 * everything is cleaned up properly.
*/
public function deleteItem(item:ISurfaceComponent):void
```

The hasOwnProperty methods will be replaced with proper interface methods when we will have them.

**Comment by piotrzarzycki21** [comment]
I got you what do you mean by using EditingSurface. In that case please use inside methods events for that purpose. Once you need to call deleteItem use:

`yourcomponent.dispatchEvent(new SurfaceComponentEvent(SurfaceComponentEvent.ComponentAdded, [mycomponent]))`

In case of remove item use `SurfaceComponentEvent.ComponentAdded` - You should be able to remove parameters thanks to that events from undo/redo methods.

Merge master to you branch in order to use those events.

**Comment by rat-moonshine** [comment]
I need to think about this your suggestion:

yourcomponent.dispatchEvent(new SurfaceComponentEvent(SurfaceComponentEvent.ComponentRemoved, [mycomponent]))

This will make the EditingSurface add a listener against the ISurfaceComponent. While in undo/redo a chain of process can be broken with newer chains. In that case its possible the EditingSurface left with non-garbage listeners. There could be another possibility - a parent container having multiple children, and EditingSurface listens to all those children for SurfaceComponentEvent.ComponentRemoved - if parent itself removed from the stage it'll remove all with its children. Which in turn can raise another non-garbage listeners. 

BTW, who is listening to these events anyway? I didn't found any handler method against this event! i.e. in FieldSet.as:

`dispatchEvent(new SurfaceComponentEvent(SurfaceComponentEvent.ComponentAdded, [this.div]));`

**Comment by piotrzarzycki21** [comment]
[EditingSurface is registering for that events](https://github.com/prominic/MockupVisualEditor/blob/51a0313202512c60b20588381dabf80d18dfffe1/src/view/EditingSurface.mxml#L229). They were created in case when you have some internal components which should be part of the Drag/Drop mechanism. 
I would think about cleaning up them, for now I'm interested if that type of communication can work for you. I'm using this mechanism in Grid and Fieldset.

**Comment by rat-moonshine** [comment]
I'm still a bit uncomfortable with the amount of events that needs to run Moonshine many features. I generally oppose of having too many event listeners but this is the case at this moment. 

I will think about this @piotrzarzycki21 . Thank you for suggesting.

**Comment by piotrzarzycki21** [comment]
I believe some framework like Parsley or Switz could help us with communication between layers. Since we do not have it - events are the cleanest way, they just keep things loosely coupled. 

Maybe some day once we will be enough big we will start rewrite things from scratch - then we use some framework.

**Comment by piotrzarzycki21** [comment]
1. What was the scenario for that - did you just removed Grid from the editing surface ?

**Comment by rat-moonshine** [comment]
> events are the cleanest way, they just keep things loosely coupled.

I basically likes protocol driven coding more than than events driven. Which is also now most practiced ways in newer language like react, swift, angular etc.

**Comment by rat-moonshine** [comment]
> There are few attributes in the UI Component Properties. For those attributes undo/redo is not working. I came across with 2 properties so far - Value property and ID property.
> 
> If I change the ID or value of the UI component then CTRL+Z do not undo the changes.

Please, provide more information with specific steps to produce against which component(s).

**Comment by atingupta2005** [comment]
Hi

Its happening for all the UI components. The 2 properties - "ID" and
"Value" are not being handled by Undo/ Redo

Please test

Thanks
Atin

**Comment by rat-moonshine** [comment]
Thank you for reporting this @atingupta2005 . I shall check this.

**Comment by rat-moonshine** [comment]
@atingupta2005 , I have tested by following components which has both ID and Value attributes, and mostly all worked expectedly in my tests, though.

- inputMask
- inputNumber (may not work expectedly until #260 resolve)
- inputText
- inputTextArea

**Comment by JoelProminic** [comment]
@atingupta2005, Undo/Redo works fine for me when I use this procedure.

1. Add a new InputText
2. Type in a value for "Value"
3. Hit Enter, or click on a different UI element to submit the value
4. Press CMD-Z

If I exclude step 3, the entire InputText will be removed.  However, you can also see that the InputText was not updated in the UI, so the value was never actually updated.

Can you reproduce the problem with my steps above?

**Comment by rat-moonshine** [comment]
On a side note, I wouldn't recommend to mark this as a 'problem' rather expected behavior. For many different reasons, we not allow updating the related fields as user typed or by text change. A field only updates when user done his/her input by hit Enter, Tab, or focus out from the input component. 

Considering the above requirement/rule excluding step 3 and press CMD-Z does what it was actually require to does.

**Comment by rat-moonshine** [comment]
As #260 now closed, undo-redo management re-updated to InputNumber component, and its stable now.

I'm closing this issue as the initial implementation for phase 1 components has done. Open separate issue for any problem/bug.

**Comment by JoelProminic** [comment]
Undo/redo seems to work fine for inputNumber
