### ISSUE TITLE
Introducing Copy/Paste of components in Visual Editor

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#248]
Extracted from #246, raised by @atingupta2005

> It would be very convenient to CTRL C and CTRL V to copy and paste the UI Controls. We can also provide CTRL D to duplicate the selected UI control.

**Comment by piotrzarzycki21** [comment]
CTRL+D is taken by Debug & Build - any suggestion for duplicate shortcut ?

**Comment by piotrzarzycki21** [comment]
I have added for now CTRL + H for duplicate.

**Comment by piotrzarzycki21** [comment]
I will change that shortcut if someone come up with better one.

**Comment by atinprominic** [comment]
CTRL + H seems to be for Hide functionality.

What about CTRL+T?

**Comment by piotrzarzycki21** [comment]
CTRL+T is being used for Stopping debug.

**Comment by piotrzarzycki21** [comment]
@atinprominic CMD + H is being used by something on Mac ?

**Comment by atinprominic** [comment]
Yes. Its being used for Hiding/Minimizing the current opened windows.

 

----- Original message -----

**Comment by piotrzarzycki21** [comment]
@atinprominic  What about CMD + R ?

**Comment by atinprominic** [comment]
Yes. We can use it.

 

 

----- Original message -----

**Comment by piotrzarzycki21** [comment]
Changed.

**Comment by JoelProminic** [comment]
Neither CMD-R or CTRL-R work on macOS (testing with 10.10.5).

Is this shortcut listed somewhere in the interface?   "Duplicate" is not a common shortcut, and this shortcut is not intuitive (and I don't have a better suggestion).   If we have a menu entry for the "Duplicate" action (either in the normal menu or the context menu), then we could list the shortcust next to the action.

I encountered an issue while testing duplication.  If this is not related to duplication we can move this to a separate issue:
1. Create and open a blank Visual Editor file
2. Add a DataTable
3. Set the "Var" value to "Test" and hit Enter. This works properly
4. Update the "Var" value to "Test2" and hit Enter. This works properly
5. Duplicate the DataTable
6. Update the "Var" value in the new DataTable to "Test3" and hit Enter. This works properly
7. Update the "Var" value in the original DataTable to "Test4" and hit Enter. This throws an exception:

    : Error #1009
    : TypeError: Error #1009
    : 	at view.primeFaces.forms::DataTableForm/onTableVarUpdated()
    : 	at MethodInfo-26261()
    : 	at mx.binding.utils::ChangeWatcher/wrapHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at view.primeFaces.surfaceComponents.components::DataTable/set tableVar()
    : 	at view.forms::TextForm/textInput_changeHandler()
    : 	at view.forms::TextForm/__textInput_enter()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at spark.components.supportClasses::SkinnableTextBase/textDisplay_enterHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at spark.components::RichEditableText/http://www.adobe.com/2006/flex/mx/internal::keyDownHandler()
    : 	at spark.components.supportClasses::RichEditableTextContainerManager/keyDownHandler()
    :
    : Click here to Report a Bug

I could not repeat this result with the Button and InputNumber controls.

**Comment by piotrzarzycki21** [comment]
@JoelProminic that's super weird what is happening. I just debug it on my Mac and I have following weird results.

When I'm doing CMD+R I'm getting correct command button but as a key code I should get [82](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/ui/Keyboard.html#R), but I'm getting [71](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/ui/Keyboard.html#G) which is equal to letter G. 

Any idea why it is working like that on Mac ? Maybe there are some specific settings.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have changed shortcut for duplication to CMD + U. I will leave this issue opened for the next release. 
- I will add options to menu
- Check above issue

**Comment by piotrzarzycki21** [comment]
Following changes has been done:
- I have added option Duplicate to Menu File
- I have fixed issue `TypeError: Error #1009`

**Comment by atinprominic** [comment]
I tested both the below issues and working fine

I have added option Duplicate to Menu File
I have fixed issue TypeError: Error #1009


Thanks
Atin

**Comment by atinprominic** [comment]
I tested the issue in windows version of Moonshine.

Below are the steps:

1. Created a Data Table and Update the name of Var to Test.

2. Again updated the value of Var to Test2

Thrown below error:

: Error #1009

: TypeError: Error #1009

:               at view.primeFaces.forms::DataTableForm/onTableVarUpdated()

:               at MethodInfo-26096()

:               at mx.binding.utils::ChangeWatcher/wrapHandler()

:               at flash.events::EventDispatcher/dispatchEvent()

:               at mx.core::UIComponent/dispatchEvent()

:               at view.primeFaces.surfaceComponents.components::DataTable/set tableVar()

:               at view.forms::TextForm/textInput_changeHandler()

:               at view.forms::TextForm/__textInput_enter()

:               at flash.events::EventDispatcher/dispatchEvent()

:               at mx.core::UIComponent/dispatchEvent()

:               at spark.components.supportClasses::SkinnableTextBase/textDisplay_enterHandler()

:               at flash.events::EventDispatcher/dispatchEvent()

:               at mx.core::UIComponent/dispatchEvent()

:               at spark.components::RichEditableText/http://www.adobe.com/2006/flex/mx/internal::keyDownHandler()

:               at spark.components.supportClasses::RichEditableTextContainerManager/keyDownHandler()

:

: Click here to Report a Bug

**Comment by piotrzarzycki21** [comment]
@atinprominic  you were using wrong Moonshine version. Use from bamboo. Look into the email which I have sent you.

**Comment by atinprominic** [comment]
@piotrzarzycki21 the version from Bamboo is working as expected.

**Comment by atinprominic** [comment]
@piotrzarzycki21 I found the issue again. Please check the below details and attached video recording:


OS: Windows 7

Moonshine Build # 337

Error Log:
: Moonshine IDE 1.14.0
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 30.0.0.107
: Error #1009
: TypeError: Error #1009
: 	at MethodInfo-25593()
: 	at Array/http://adobe.com/AS3/2006/builtin::some()
: 	at actionScripts.ui.renderers::FTETreeItemRenderer/populateTemplatingMenu()
: 	at flash.display::NativeMenu/display()
: 	at flash.ui::ContextMenu/display()
: 	at flash.display::InteractiveObject/onContextMenuEvent()
:
: Click here to Report a Bug

Video: 
![moonshine issue 1009](https://user-images.githubusercontent.com/34882311/43824759-81ac258a-9b10-11e8-9ea7-0be7ebb87a2f.gif)

**Comment by piotrzarzycki21** [comment]
@atinprominic This is not connected with Visual Editor. Please raise issue: "Null Pointer Exception during open project with source"

**Comment by JoelProminic** [comment]
I found that the Duplicate feature was very useful when testing #333.  This seems to be working reliably.

I have a couple clarifications after reviewing this issue for the 1.15.0 release:
- The shortcut for duplication is CTRL-U on Windows and CMD-U on macOS.  
- Copy and Paste are not implemented currently.  It looks like we implemented Duplicate instead.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I just tried CTRL+C and CTRL+V on Windows and it's working. What problems did you have ?
