### ISSUE TITLE
Issue while moving the UI Controls using Keyboard Arrow Keys

### ISSUE THREAD

**Issue by atingupta2005** [prominic/Moonshine-IDE#249]
Hi,

While I select a UI control and use keyboard arrow keys to reposition it, the entire design pane is moving right or left. Also the focus is shown wrongly if I use mouse and scroll the screen. 

I have recorded the video in GIF to show:

![vedraggingkb](https://user-images.githubusercontent.com/3568735/39292315-709d1b3c-4953-11e8-9f50-b6fd8d1f61aa.gif)

**Comment by piotrzarzycki21** [comment]
It should be fixed with changes in #243 and #244 - You basically won't be able to move components inside containers.

**Comment by piotrzarzycki21** [comment]
Actually I have also check with Flex Visual Editor and there is no issue here. In Flex you will still be able to move components by arrows. As you can see on the GIF surface area for main window is smaller, so there are horizontal/vertical scrollbars. When I'm doing movements scrollbars react for the arrows - which is perfectly fine.

![move_controls_flex](https://user-images.githubusercontent.com/24554795/39359033-99b21f98-4a18-11e8-82da-5e57f9d934a8.gif)
