### ISSUE TITLE
Misc bugs in new file popups

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#250]
- **New ActionScript File** popup showing multiple warnings against user input:
![image](https://user-images.githubusercontent.com/24370870/39302476-5ac51266-4970-11e8-9b6c-90b98db73817.png)
- **New File** popup do not showing duplicate file warning

**Comment by rat-moonshine** [comment]
As @JoelProminic reported that we probably want to ignore case sensitive check against duplicate file check (in a case-sensitive system), I adjust something to overcome this problem in a case-sensitive machine. However, I don't have any system that is case-sensitive so I leave this issue for a test.

**Comment by rat-moonshine** [comment]
We're using standard API library to adjust between cases, along with the 'exists' method to determine if the 'adjusted case' file is exists.

**Comment by JoelProminic** [comment]
I ran a test on a case-sensitive workstation, and I can create files and directories that differ only by case (TestClass.as vs testclass.as, src vs SRC).  This looks fine to me.
