### ISSUE TITLE
Grid particular cell accepts component

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#253]
- Create a Grid component
- Create 2nd Row - R2
- Create 2nd Column in 'R2' - C2
- Drag any component to the R1/C1 cell - it accepts and add the component
- Drag any component to R2/C1 or R2/C2 - cell do not accepts dragged component
- Dropped components added outside of Grid component

**Comment by rat-moonshine** [comment]
![ccproblem3](https://user-images.githubusercontent.com/24370870/39520965-2cd982e2-4e2a-11e8-8b9c-457b92c3f701.gif)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have pushed updated version of Visual Editor. Please try now. I have made changes in that area.

**Comment by rat-moonshine** [comment]
Latest push seems fix this problem. I'm closing this issue.

**Comment by piotrzarzycki21** [comment]
Thanks for looking into that.

**Comment by rat-moonshine** [comment]
I've created another related issue, please check at #254 .

**Comment by atinprominic** [comment]
I have tested it. Its working as expected now.
