### ISSUE TITLE
Grid property editing affects only cell

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#254]
![ccproblem34](https://user-images.githubusercontent.com/24370870/39521670-213a4414-4e2d-11e8-9857-4b788f6b0bcb.gif)

**Comment by piotrzarzycki21** [comment]
I see that between drop and edit you have deselected Grid which go back to R1/C1 selection. That's why changes to the cell affects only R1/C1 instead R2/C2. 

Do you want me somehow remember last selected Row/Cell ?

**Comment by rat-moonshine** [comment]
I think while setting properties against a particular selected cell (i.e. R2/C2), that remains available even after deselecting Grid. Practically you probably wants to have individual property editing value for every cell created, so you can preserve those options even after Grid deselects, and re-populate the editing UI based on cell selection.

**Comment by piotrzarzycki21** [comment]
Selected row/column from now on is remembered. You should not experience that issue anymore.

**Comment by rat-moonshine** [comment]
I gave some tests. I confirm cells now remembers individual property assignment values.

I also noticed change of property assignment is not possible unless deselect the Grid component, and re-select the component with target cell selection. Following were my test procedures:

1. Create two rows - R1, R2
2. Create three columns in R2 - C1, C2, C3
3. While having the selection on R2/C1, select "Wrap" option
4. Select R2/C2, property editor continue showing the values for R2/C1 [Bug]
5. Deselect the Grid component
6. Re-select the Grid component with current selection at R2/C2, now I can change property against R2/C2
7. Select R2/C3 - property editor continue showing the value of R2/C2 unless I do 5-6 again [Bug]

Other than the property editor update problem, I can add components to the cell with the cell's last known property value.

**Comment by rat-moonshine** [comment]
I also noticed something which may not be very critical, but this may lead some visual confusion between current selected and non-selected cells. In following image I able to multiple red border colored cell. If the color is suppose to point the current selected cell, then this maybe not working unexpectedly. However, if this would take long time to fix, we can choose to stop this color selection for upcoming release.

![image](https://user-images.githubusercontent.com/24370870/39573410-b8b6e27a-4ef0-11e8-8b03-28521660ef50.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Those colors are only pointing to express better visibility of rows/cells. It's not points which row/cell is selected.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just pushed fixes for those issues. Please check.

**Comment by rat-moonshine** [comment]
I'm not sure if I'm missing something, but I pull latest codes and swc multiple time with 'master', but I don't see any difference from my earlier result/report. I also see the presence of red borders to random cells.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I didn't remove red borders yet. I will look at it again.

**Comment by rat-moonshine** [comment]
In my tests I didn't find any differences that I reported as step 1- 7, though.

**Comment by piotrzarzycki21** [comment]
Please try again and let me know if something changed.

**Comment by rat-moonshine** [comment]
I have re-tested with newer SWC and I confirm:
- Selecting a particular cell in property editor repopulates its existing property values
- Deleting any cell reset the selection to first item in the panel and shows the selected cells existing property values
- Adding any cell auto-selects the newly created cell and shows its default property editing values

This looks good in my tests. The random red borders are still available. Perhaps you want to remove them as well.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have changed color to #7096ab
