### ISSUE TITLE
Unexpected Drag Behavior with Layout in Visual Editor

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#255]
I noticed some examples with the moving elements in the current layout logic.  For example, starting from this layout:

![image](https://user-images.githubusercontent.com/24532731/39538535-bf35ee78-4e02-11e8-9aaa-1453c27035e7.png)

If I grab the one/two/three Div and move it slightly to the right, then it snaps to the far right.

![image](https://user-images.githubusercontent.com/24532731/39538567-d17a2478-4e02-11e8-8ad0-02558fa77b0c.png)

I can't move the one/two/three Div back to the left by dragging.  Instead, I need to move the other divs.

Similiarly, if I drag the "One" label slightly downward, it moves to the very bottom:

![image](https://user-images.githubusercontent.com/24532731/39538573-d8b7402c-4e02-11e8-8893-05f1a79e41e3.png)

And I can't drag it back to its original position.

In addition to the strange movement, I found that it is really easy to accidentally move an element when selecting it.  I think we need to have a larger movement threshold before the element position is changed.

**Comment by JoelProminic** [comment]
Note that reordering is currently completely broken.  See #297.  I will leave this issue open in case the bug resurfaces after #297 is resolved.

**Comment by piotrzarzycki21** [comment]
Just checked and cause of that issue is exactly the same -> https://github.com/prominic/Moonshine-IDE/issues/297#issuecomment-402709978

**Comment by JoelProminic** [comment]
#297 has been resolved, but now I am seeing the drag behavior I reported in this issue again.  If the components are dragged at all, they are moved to the end of the component list, and they can not be dragged to an earlier position.

**Comment by piotrzarzycki21** [comment]
@JoelProminic If I correct understand #297 is fixed cause repositioning is working, but the general behavior is still not as it should be? 
I will check it, but it has to wait for the next release unfortunately.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I looked into that problem closer and I think it is actually behavior which in current way how we handle containers is not solvable by drag and drop. 
Each container in Visual Editor has horizontal or vertical layout. In the moment when you dropping something it has been added to the container, but since there is not x, y position it will be added according layout requirements - at the end in that case, because we are using simply [addElement](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/mx/core/IVisualElementContainer.html#addElement()) function in the component.

Here is an example from Flex Visual Editor where I can use BasicLayout and X, Y is available.

![drag_drop_flex](https://user-images.githubusercontent.com/24554795/43456727-e77025c6-94c4-11e8-808a-c17edc2fcc75.gif)

The only think which come up to my mind for having ability to switch places for elements is add some options when element is selected - in context menu - "Move right", "Move left" - . Do we want to have such things ?

**Comment by JoelProminic** [comment]
@piotrzarzycki21,

I can see why reordering the components with a horizontal or vertical layout is a problem.  We could use Move Right/Left/Up/Down buttons as a simple solution for this, but I don't think it will be very intuitive.  I think we would still need to be able to drag the components for nesting, but it would be confusing if this didn't work for reordering as well.

Could we estimate the target position based on the width/heght of the container and the width/height of each child?  I had some inspiration for this algorithm, so I created some pseudocode (hopefully my intention is clear, even if I made some silly mistake):

```
/**
 * Determine the index of the given location within the parent container's child list.
 */
function int getNewPosition(int x, int y, Container parent) {
    // Make the position relative to the top-left of the parent.
    // This would need to be adjusted for other alignment options
    int relativeX = x - parent.x
    int relativeY = y - parent.y

    boolean newRow = true;
    int rowMaxY = 0; // the max y of the current row
    int curX = 0;  // the relative x position of the right side of the current component
    int curIndex = 0;  // the index of the current child

    while (curIndex < parent.children.size()) {
        if (newRow) {
            // calculate the bottom of the current row.
            rowMaxY += getRowHeight(curIndex, parent);
            curX = 0;
            newRow = false;
        }

        // calculate the new right-most position
        int newX = curX + parent.children.getItemAt(curIndex).width;
        if (newX > parent.width) {
            // the item wraps
            if (curX <= 0) {
                // ... unless it is the only component on the row.
                // Create a new row on the next iteration
                newRow = true;
            }
            else {
                // continue to the next row without incrementing the index
                newRow = true;
                continue;
            }
        }
        curX = newX;

        if (relativeX < curX && relativeY < rowMaxY) {
            // insert the new component before the current component
            // NOTE:  If the dragged component is in the children list before this index, then you will need to reduce the index by 1
            return curIndex;
        }
        // otherwise, keep checking


        curIndex++;
    }

    // otherwise, the new position is after the last element.
    return curIndex;
    
}

/**
 *  Determine the height of the the row of children starting at the current index.
 */
function int getRowHeight(int startIndex, Container parent) {
    int maxHeight = 0;
    int curWidth = 0;
    int curIndex = startIndex;

    while (curIndex < parent.children.size()) {
        // determine where the current component ends
        curWidth += parent.children.getItemAt(curIndex).width;
        if (curWidth > parentwidth) {
            // this component will wrap
            if (maxHeight == 0) {
                // unless this is the only component on the row.  In this case, use the height of the current component
                return parent.children.getItemAt(curIndex).height;
            }
            else {
                // return the maxHeight of the components before this.
                return maxHeight;
            }
        }
        else {
            maxHeight += parent.children.getItemAt(curIndex).height;
        }

        curIndex++;
    }

    // All remaining components will be on this row.
    return maxHeight;
}
```

**Comment by piotrzarzycki21** [comment]
I'm closing that one because reordering will be part of #350. @rat-moonshine you can take a look here - maybe something will be useful.
