### ISSUE TITLE
Library added to "Libraries" are saved in "external-library-path" instead of "library-path"

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#258]
I'm working on setup large Flex application in Moonshine. During setup one of the swc I have discovered that adding links do some libraries in "Libraries" section of settings are landed in "extenral-library-path" instead "library-path".

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I did fix for that. You can take a look into the commit. If it's possible it will be great to have it in 1.12.0.

**Comment by rat-moonshine** [comment]
Looking into the code commits, this shouldn't break anything. I did a test to ensure that existing libraries path section is still working good, I tested by creating a Feathers project and adding its theme .swc file. Project worked good even after a close and reopen. 

Let's move this to the release.
