### ISSUE TITLE
Language Server Protocol: Moonshine does not conform with official protocol

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#259]
Justin has requested that I work on adding some new languages to Moonshine. To move forward, Moonshine needs to be modified to conform with the Language Server Protocol specification. Currently, it speaks something only loosely based on the protocol.

Excerpt from my email to Justin explaining what is required:

> Right now, Moonshine speaks a slightly modified version of the language server protocol, and it uses a light wrapper around the ActionScript/MXML language server to account for the differences. This was a decision made before I started contributing directly to Moonshine. Since what was originally implemented seemed to work well enough, I didn't bother modifying this code to make it strictly follow the language server protocol. If we were to add additional languages, I would want to finally fix that so that we can include new language servers with as few modifications as possible.
> 
> Additional language servers may require Moonshine to implement some new APIs that the ActionScript/MXML language server doesn't use. I won't know for sure until I start trying to add the other language servers.

Link to official language server protocol specification:

https://microsoft.github.io/language-server-protocol/specification

**Comment by piotrzarzycki21** [comment]
@joshtynjala your changes increased speed of code completion a lot! I finally can use it without lags! Thank you!

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Wow, I didn't expect that to happen!

**Comment by piotrzarzycki21** [comment]
Each time the very first run of code completion has some lag, but it's nothing compare to what was previously. But the next runs are super fast! I was testing it today a lot with some Flex project.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I'm getting following warning in the console when I'm building Moonshine in IDE. It doesn't occur on the installed version.

```
Jun 15, 2018 9:36:34 AM org.xsocket.connection.IoAcceptor <init>
: WARNING: could not bind server to 0.0.0.0/0.0.0.0:54665. Reason: java.net.BindException: Address already in use: bind
: 	at sun.nio.ch.Net.bind0(Native Method)
: 	at sun.nio.ch.Net.bind(Net.java:433)
: 	at sun.nio.ch.Net.bind(Net.java:425)
: 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
: 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
: 	at org.xsocket.connection.IoAcceptor.<init>(IoAcceptor.java:117)
: 	at org.xsocket.connection.IoAcceptor.<init>(IoAcceptor.java:94)
: 	at org.xsocket.connection.IoProvider.createAcceptor(IoProvider.java:453)
: 	at org.xsocket.connection.Server.<init>(Server.java:492)
: 	at org.xsocket.connection.Server.<init>(Server.java:169)
: 	at moonshine.Main.main(Main.java:46)
: 
: java.net.BindException: Address already in use: bind
: 	at sun.nio.ch.Net.bind0(Native Method)
: 	at sun.nio.ch.Net.bind(Net.java:433)
: 	at sun.nio.ch.Net.bind(Net.java:425)
: 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
: 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
: 	at org.xsocket.connection.IoAcceptor.<init>(IoAcceptor.java:117)
: 	at org.xsocket.connection.IoAcceptor.<init>(IoAcceptor.java:94)
: 	at org.xsocket.connection.IoProvider.createAcceptor(IoProvider.java:453)
: 	at org.xsocket.connection.Server.<init>(Server.java:492)
: 	at org.xsocket.connection.Server.<init>(Server.java:169)
: 
: 	at moonshine.Main.main(Main.java:46)
: Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
```

**Comment by piotrzarzycki21** [comment]
@joshtynjala ignore previous comment - That's my fault!

**Comment by piotrzarzycki21** [comment]
@joshtynjala I have removed isMethod, isEvent, isProperty, isVariable and isClass from CompletionItem.

**Comment by joshtynjala** [comment]
Thanks, Piotr!

**Comment by piotrzarzycki21** [comment]
@joshtynjala I have noticed that properties are incorrect recognized by language server. We are receiving CompletionItemKind.FIELD instead CompletionItemKind.PROPERTY.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Okay, I'll try to improve that in the next version.
