### ISSUE TITLE
ClassCastException when adding experimental component in MXML

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#261]
Moonshine is throwing ClassCastException when I'm trying to use component from Flex experimental package.

```
java.lang.ClassCastException: java.lang.String cannot be cast to com.google.gson.JsonPrimitive
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.executeAddMXMLNamespaceCommand(ActionScriptTextDocumentService.java:6206)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.executeCommand(ActionScriptTextDocumentService.java:1134)
: 	at moonshine.xSocketDataHandler.onData(xSocketDataHandler.java:282)
: 	at org.xsocket.connection.HandlerAdapter.performOnData(HandlerAdapter.java:242)
: 	at org.xsocket.connection.HandlerAdapter.access$200(HandlerAdapter.java:42)
: 	at org.xsocket.connection.HandlerAdapter$PerformOnDataTask.run(HandlerAdapter.java:210)
: 	at org.xsocket.SerializedTaskQueue.performPendingTasks(SerializedTaskQueue.java:161)
: 	at org.xsocket.SerializedTaskQueue.access$100(SerializedTaskQueue.java:40)
: 	at org.xsocket.SerializedTaskQueue$MultithreadedTaskProcessor.run(SerializedTaskQueue.java:189)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
```

![class_cast_exception](https://user-images.githubusercontent.com/24554795/40003233-16d98808-5793-11e8-8d88-031a4ac7f4c1.gif)

VSCode doesn't show in code completion the same component at all. 

![no_component_in_cc](https://user-images.githubusercontent.com/24554795/40003436-9f88a4ae-5793-11e8-8700-066e4f576e83.gif)

**Comment by joshtynjala** [comment]
> Moonshine is throwing ClassCastException when I'm trying to use component from Flex experimental package.

Confirmed. It looks like some other things broke too. Automatic imports is another big one.

> VSCode doesn't show in code completion the same component at all.

I don't think your project in VSCode is configured correctly.

**Comment by piotrzarzycki21** [comment]
Lately I have configured quite a big project in VSCode which has several swcs as and dependency. Maybe there is something which I'm missing there. I will try to check in a clean project. 

However if my configuration is wrong, why I'm seeing other classes like HGroup, Group etc.

**Comment by joshtynjala** [comment]
HGroup and other symbols are not showing with the correct icons in your GIF. VSCode appears to be using its fallback completion that just adds random strings from the current file instead of using full code intelligence.

**Comment by piotrzarzycki21** [comment]
Good to know. It looks like I need to work more on that setup. I'm using workspace in general where I'm gathering all those project. For example this is configuration for project where I have recorded above gif. 
![conf_vscode](https://user-images.githubusercontent.com/24554795/40008933-e11fafc2-57a0-11e8-8b29-0995ebfb59d8.png)

**Comment by joshtynjala** [comment]
> I'm using workspace in general where I'm gathering all those project. 

The ActionScript & MXML extension does not yet support workspaces with multiple root folders. Only the first root folder in a workspace will have code intelligence.
