### ISSUE TITLE
Avail Home tab's Recent section in Moonshine menu

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#265]
[This is a sub-issue of what discussed in #262 ]

Avail recent opened projects section to Moonshine menu bar, so the feature can easily accessible when Home tab closed. 

Suggested area for recent projects are:
`Moonshine > File > Open Recent -> ...`

@JoelProminic , do you also wants separate group/menu-section for recent files, too?

**Comment by JoelProminic** [comment]
I would suggest separating the Recent Projects from the Recent Files in the menu.
- There will be more space available for other recent files/projects in the list
- The user will not need to move the mouse halfway down the list to reach the files section.   This is fine on the home screen, but it would be annoying in the menu.

I suggest these menu paths.  
- File > Recent Projects
- File > Recent Files

You could also nest these under File > Recent, if that looks better.  This would be an extra submenu to navigate, though.
- File > Recent > Projects
- File > Recent > Files

I expect we will also want a menu entry for Recent Workspaces, once we have added that feature (no issue found).

**Comment by rat-moonshine** [comment]
We might want something like this than generic scroller to the menus - http://flexponential.com/2009/10/09/changing-the-position-of-the-scroll-bars-in-a-spark-list/.

**Comment by JoelProminic** [comment]
The scrolling menu looks pretty good on macOS already:  
![image](https://user-images.githubusercontent.com/24532731/40247441-0098e1ea-5a92-11e8-9c7a-e4537c1a74d6.png)

On Windows, they have a scrollbar, which is not as good:
![image](https://user-images.githubusercontent.com/24532731/40247449-09fbe818-5a92-11e8-8111-e1da377e8cc0.png)

**Comment by rat-moonshine** [comment]
@JoelProminic  also reported menu disabling bug when project selection moved between Visual Editor and non-visual-editor projects:

> 1. Open Visual Editor Project
> 2. File > Recent Project > <selectanother-project>
> 3. Close the additional project. The VisualEditor project is now selected
> 4. File > Recent Project. BUG: menu items are disabled

**Comment by JoelProminic** [comment]
The updated Windows menus look good:
![image](https://user-images.githubusercontent.com/24532731/40316350-abca40ba-5ce3-11e8-8335-b299c97a90ea.png)

I found another variation on the menu disable bug:
1. Select a VisualEditor project in the tree
2. File > Recent Files.  BUG:  all submenu items are disabled
3. Select a non-VisualEditor project
4. File > Recent files - this works

**Comment by piotrzarzycki21** [comment]
Wow! It looks super weird to me! I didn't follow that discussion to much. Can't we have nicely skinned scrollbar with max height for the menu ? In order to scroll that menu I need to click on those arrows ?

**Comment by JoelProminic** [comment]
You just need to mouse over the arrows to scroll the menu.  This works similar to the MacOS menus above, but the Windows scroll buttons have a border which makes them look a bit strange.

The menu height is limited based on the height of the application window, so normally this menu is a lot taller.  I shrunk my window for ease of testing.

**Comment by rat-moonshine** [comment]
> Wow! It looks super weird to me!
How would you define regular macOS menus with arrows - super weird?

Windows scroll buttons have a border which makes them look a bit strange.

> The menu height is limited based on the height of the application window, so normally this menu is a lot taller. I shrunk my window for ease of testing.

Arrow borders generally to make the area to more stand out, but the border color or alpha can be changed. So do the maximum height to the menu box.

**Comment by rat-moonshine** [comment]
Arrow background color now replaced with solid color (as in macOS) to have more linear effect. I'm closing this please reopen if we have problem.

**Comment by atingupta2005** [comment]
When I open a non existing file/project using "File\Recent Projects" or "File\Recent Files", it throws an error - "Can't import: The file does not exist anymore."

To reproduce the error remove the Project/File using OS file system and then open it in Moonshine.

If I am opening project then it should show the error - "Can't open: The project/file does not exist anymore."

Also it should confirm to remove the entry from recent list for non existing project or file.

**Comment by rat-moonshine** [comment]
@atingupta2005 , I see two parts in your observation/suggestion:

1. Updating the error text
2. Removing the entry when above scenario happens

While the former is not difficult to change as it's a text. For the latter, you should want to open a new issue with given details.
