### ISSUE TITLE
Primefaces Grid Enhancements

### ISSUE THREAD

**Issue by atingupta2005** [prominic/Moonshine-IDE#266]
I have tested the Grid component specifically and found it very useful to arrange the UI components on the screen.

- [x] There should an option to the user to select the individual cell just by clicking on the cell in the design pane. Currently user need to click on the respective rows/columns in the properties section to change the direction and alignment properties.

- [x] The user should be able to add the columns to all the rows at once. Currently the user has to select each row one by one and add the columns for each row. 

- [x] The cell selected via the properties section should be highlighted in a different colour so that the user will know on which cell its currently on. Currently it very confusing as the user need to check the Rows / Columns properties to make sure which cell is active.

**Comment by piotrzarzycki21** [comment]
@JoelProminic , @rat-moonshine What do you think for the second improvement from @atingupta2005 to have following addings: **Amount of Rows** and **Amount of Columns**

![image](https://user-images.githubusercontent.com/24554795/42172867-a1958504-7e1d-11e8-9bdb-4b01d50534c1.png)

Increasing value and choosing **+** will generate selected amount of rows, columns. 

Thoughts ?

**Comment by JoelProminic** [comment]
I think what @atingupta2005 requested was to be able to fill out the cells in the grid as we add more rows or columns.  For example if I were making a 3x3 grid:

![image](https://user-images.githubusercontent.com/24532731/42178228-2191b882-7df5-11e8-9366-ffc53aad8de7.png)

Currently, we would have to select each row and add the additional two columns.  If we wanted to create a 12x12 grid, this would take 144+ clicks.  Your proposed control would reduce this to something like 36 clicks, with a lot of repetitive typing.

If the only case we plan to support for Grid is a full grid of elements, then it would be better to automatically populate the additional cells to make a full grid whenever we add a new row or column.  In this case, the 12x12 grid would take 22 clicks.  

However, this would remove support for cases like in my image above.  That said, I don't think this layout is very useful, and you could still arrange the fields in this manner with the full grid.

Keep in mind that Grid CSS gives a lot more options than what we are doing with this control.  For example, we could have the cells stretch for the full width of the grid on rows that only have one column.  Indeed it looks like the generated xhtml code is trying to do this, but it is not reflected in the Moonshine UI.  (I could not get a screenshot of the end result because Grid is not working with the Grails PrimeFace project for now - this seems to be a problem on the server side which Bing and I will need to investigate.)

If we want to continue supporting stretching the cells, then we should not use the cell auto-population strategy I described above.  However, we would need to show this behavior in the Visual Editor UI.

**Comment by piotrzarzycki21** [comment]
Ok I hear you right now. I will introduce in the UI two fields and button Create.

R: [1] x C: [2] Create

Above UI should simplify everything and you will be able to create Rows/Columns in an efficient way. However I'm aware that above simplification introduce cases where user having some components in the cells, can erase them doing Create with new parameters.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed changes - if you have a time take a look and tell whether it's ok.

**Comment by atinprominic** [comment]
I think the deletion of rows/columns will be confusing process. The user will not know which specific row, column is going to be deleted until its actually deleted. Also it will be unclear that it will delete the rows/columns based on the count specified or will delete only 1.


I suggest below extra features to be implemented:

1. Show the row and column number in the background of the grid.
2. While deleting confirm the user to delete the row, columns. We can ask them by referring to the row, column number.
3. Highlight the row/column to be deleted with red colour and then take confirmation from the user.
4. Provide the message to user at the confirmation box that he can undo it using CTRL+Z.
6. Take another level of conflation from user in case the rows, columns being deleted have other UI components. Warn the user that all the components inside it will be removed as well.

If you are agree with any of the above suggestions then you can take it as a separate task.

**Comment by piotrzarzycki21** [comment]
I will think about it more after my vacation. This task is definitely good place to make farther improvements to the Grid. Thanks!

**Comment by atinprominic** [comment]
I assume that more detailed integration testing is to be done of the Grid component by the developer.

I have found couple of issues including a runtime error the logs of which are as below:

 Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 28.0.0.125
: Index '4' specified is out of bounds.
: RangeError: Index '4' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view.primeFaces.forms::GridForm/deleteColumnButton_clickHandler()
: 	at view.primeFaces.forms::GridForm/__deleteColumnBtn_click()
:
: Click here to Report a Bug
: Index '4' specified is out of bounds.
: RangeError: Index '4' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view.primeFaces.forms::GridForm/deleteColumnButton_clickHandler()
: 	at view.primeFaces.forms::GridForm/__deleteColumnBtn_click()
:
: Click here to Report a Bug
: Index '4' specified is out of bounds.
: RangeError: Index '4' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view.primeFaces.forms::GridForm/deleteColumnButton_clickHandler()
: 	at view.primeFaces.forms::GridForm/__deleteColumnBtn_click()
:
: Click here to Report a Bug
: Index '4' specified is out of bounds.
: RangeError: Index '4' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view.primeFaces.forms::GridForm/deleteColumnButton_clickHandler()
: 	at view.primeFaces.forms::GridForm/__deleteColumnBtn_click()
:
: Click here to Report a Bug
: Index '4' specified is out of bounds.
: RangeError: Index '4' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view.primeFaces.forms::GridForm/deleteColumnButton_clickHandler()
: 	at view.primeFaces.forms::GridForm/__deleteColumnBtn_click()
:
: Click here to Report a Bug
: Index '4' specified is out of bounds.
: RangeError: Index '4' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view.primeFaces.forms::GridForm/deleteColumnButton_clickHandler()
: 	at view.primeFaces.forms::GridForm/__deleteColumnBtn_click()
:
: Click here to Report a Bug
: Index '4' specified is out of bounds.
: RangeError: Index '4' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view.primeFaces.forms::GridForm/deleteColumnButton_clickHandler()
: 	at view.primeFaces.forms::GridForm/__deleteColumnBtn_click()
:
: Click here to Report a Bug
: Index '4' specified is out of bounds.
: RangeError: Index '4' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view.primeFaces.forms::GridForm/deleteColumnButton_clickHandler()
: 	at view.primeFaces.forms::GridForm/__deleteColumnBtn_click()
:
: Click here to Report a Bug
: Index '5' specified is out of bounds.
: RangeError: Index '5' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view.primeFaces.forms::GridForm/deleteColumnButton_clickHandler()
: 	at view.primeFaces.forms::GridForm/__deleteColumnBtn_click()
:
: Click here to Report a Bug
: Index '5' specified is out of bounds.
: RangeError: Index '5' specified is out of bounds.
: 	at mx.collections::ArrayList/removeItemAt()
: 	at view.primeFaces.forms::GridForm/deleteColumnButton_clickHandler()
: 	at view.primeFaces.forms::GridForm/__deleteColumnBtn_click()
:
: Click here to Report a Bug

**Comment by piotrzarzycki21** [comment]
Are you able to describe scenario which causes that issue ?

**Comment by atinprominic** [comment]
I just added a Datagrid and then added/ removed the columns multiple times. Specially I keep on clicking "-" for removing the columns even after all the columns are removed. Then I added columns again. Then I also added few rows. Then removed columns and clicked "-" multiple times. Then added a new row and added columns to it.

In nutshell, if you keep doing the sequence as specified above, you will get the issue.

**Comment by atinprominic** [comment]
@piotrzarzycki21 I got errors again. For the convenience, I have created a video.

![vegridtesting170718](https://user-images.githubusercontent.com/34882311/42815101-0b370ad8-89e4-11e8-8c95-d50d105200bd.gif)

**Comment by JoelProminic** [comment]
I was able to reproduce Atin's issue.  When I create multiple rows with different numbers of columns, I find that all rows show the same number of columns in the properties panel.  In a different attempt, I saw that all rows reported only one column.

**Comment by piotrzarzycki21** [comment]
> I was able to reproduce Atin's issue. When I create multiple rows with different numbers of columns, I find that all rows show the same number of columns in the properties panel. In a different attempt, I saw that all rows reported only one column.

I think I have fixed that issue. I couldn't reproduce Atin's failure and it may not occur anymore. I have changed a lot Grid component.
