### ISSUE TITLE
Projects Do Not Open On Startup

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#267]
In my recent testing in Moonshine, I noticed that #106 is not longer working for me.   I am using hte latest Bamboo builds on MacOS Yosemite.
1. Start with a project open in Moonshine.  I noticed this with both a Visual Editor project and a Flex Library project.
2. Restart Moonshine
3. No projects are opened on startup

However, @rat-moonshine could not reproduce this problem.

I checked my settings and confirmed that they are still set to reopen projects on startup.

@rat-moonshine told me that this was the relevant file for determining the starting project list.  I see it contains a lot more projects than the ones I had open, though:  ~/Library/Containers/com.moonshine-ide/Data/Library/Application Support/com.moonshine-ide/Local Store/#SharedObjects/bin-debug/Moonshine.swf/moonshine-ide-project.sol 
[2018_05_17__moonshine-ide-project.sol.zip](https://github.com/prominic/Moonshine-IDE/files/2014536/2018_05_17__moonshine-ide-project.sol.zip)

I have not yet tried to clear the ~/Library/Containers/com.moonshine-ide directory, but I could try that if we don't have any ideas to fix this.   Are there any other files that would be useful for debugging this problem?

**Comment by JoelProminic** [comment]
After @rat-moonshine implemented #268, I see this error on the console on startup:

    : Error: Error: Error #3001
    : 	at actionScripts.plugin.errors::UncaughtErrorsPlugin/uncaughtErrorHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at MethodInfo-14670()
    : 	at SetIntervalTimer/onTimer()
    : 	at flash.utils::Timer/tick()

Unfortunately, this error looks pretty generic.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I'm reading that error could means: Error 3001 is "File or directory access denied."

**Comment by piotrzarzycki21** [comment]
@JoelProminic any strange behavior around that with latest build from bamboo ?

**Comment by JoelProminic** [comment]
I still see similar results to what I reported in my test procedure above.  On this attempt, I did not see either ProjectA or ProjectC open on step 8:
7. Add Access for ProjectA's parent directory
8. Restart Moonshine - Only ProjectA opens, and an error appears on the console

This looks like the original behavior I reported but could not reproduce.

**Comment by piotrzarzycki21** [comment]
Let's close this one and see whether we will reproduce it.
