### ISSUE TITLE
Component AutoComplete should expose fields in property editor which allows fill up control by data

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#269]
AutoComplete component should be filled by the data once user export project from Visual Editor. In order to allow that add following properties in property editor.

(https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml) component:
* **value** - 
* **completeMethod** - It's taking array do display in AutoComplete

In order to handle objects instead of text expose
* **var**
* **itemLabel**
* **itemValue**
* **playerConverter**

Please refer to the documentation about AutoComplete.

**Comment by rat-moonshine** [comment]
Are you planning to generate AutoComplete/ThemeConvereter.java etc. files at the time of exporting project?

**Comment by piotrzarzycki21** [comment]
Absolutely not. It is only place which user can fill up to have it working with his already written converter.

**Comment by rat-moonshine** [comment]
value, completeMethod, var, itemLabel, itemValue, converter - all these will be text input components, or you have something other in mind?

**Comment by piotrzarzycki21** [comment]
Nope, this is exactly what we should have in property editor.

**Comment by rat-moonshine** [comment]
I think you didn't understood me. These properties should pose as text input in the property editor of AutoComplete?

**Comment by piotrzarzycki21** [comment]
Yes they should appear as Text inputs in property editor of AutoComplete. They should help user fill up by data autoComplete when it will be exported.

**Comment by rat-moonshine** [comment]
New fields have added to the AutoCompleteDropdownList and to its history manager. 

@piotrzarzycki21 you can add the fields to documentation API, now.

**Comment by piotrzarzycki21** [comment]
From now on Anyone who is adding new features/properties should add documentation.

**Comment by piotrzarzycki21** [comment]
I have added couple of comments which need to be fixed. Apart of that when I add autoComplete I see null in both properties.

`<p:autoComplete dropdown="true" multiple="false" value="null" completeMethod="null" />`

Another thing is var and value or other methods are not seems to be optional. The question is if user do not type anything in var or value we should prevent from outputing it to the XML ? 

OR should it stay as an information `var=""` or `value=""`

We need to be consistent.

**Comment by rat-moonshine** [comment]
I have no strong opinion where `var` and `completeMethod` needs to be always available or not. Looking to the example at https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml, `autoComplete` seems have a use to both of the properties in each cases, though.

`null` problem now resolved against these said properties.

**Comment by piotrzarzycki21** [comment]
Let's have an agreement for that that in case of var, value and itemLabel properties are present only if they are filled. I will adjust other components to make it happen. In the documentation we will have additional which indicates that those one are optional. Example [here](https://github.com/prominic/MockupVisualEditor/blob/a25791fdf5dbf1681f16f6624df9f378113662ca/src/view/primeFaces/surfaceComponents/components/InputText.as#L106)

**Comment by rat-moonshine** [comment]
The most basic example of [autoComplete](https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml) is shown the use of `value` and `completeMethod`. As I said I do not have any strong opinion on this, whichever prefer can be done as non/optional.

Can you list down the following components between non/optional (?)

- value
- completeMethod
- var
- itemLabel
- itemValue
- converter

**Comment by piotrzarzycki21** [comment]
Let's make it clear - by optional I mean to have or not have it in Visual Editor/PrimeFaces XML. - in that case. However we have two options.

1. Looking into such properties from [PrimeFaces documentation](https://www.primefaces.org/docs/guide/primefaces_user_guide_6_2.pdf) point of view.
2. Making some properties always present the other one if they filled.

Option 1.
value (Optional)
var (Optional)
completeMethod (Optional)
itemLabel (Optional)
itemValue (Optional)
converter (Optional)

Option 2.
value - present in XML as value=""
var - present in XML as var=""
completeMethod (Optional)
itemLabel (Optional)
itemValue (Optional)
converter (Optional)

I'm not so sure what is the best option.

**Comment by piotrzarzycki21** [comment]
Let's move with that forward. I will make the changes, where we won't control about value and var, but the rest of the option will be optional. From property editor point of view we won't force to type anything.

**Comment by piotrzarzycki21** [comment]
Here is the results:

completeMethod (Optional)
itemLabel (Optional)
itemValue (Optional)
converter (Optional)

Above properties will be output to the xml only if someone provide any of them.
