### ISSUE TITLE
Add option "Reset Application" to Moonshine's settings

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#27]
In order to get back application to the state from the first clean installation we should add option "Reset Application" in the settings.

Reset:
- Once user choose option "Reset Application" we need to have clean information message what will happen
- Moonshine will be restarted

**Comment by rat-moonshine** [comment]
Some things yet to look into:
- Upon cleaning settings, bottom SDK notification yellow patch is not showing (display not updating)
- Needs to think about how to handle Template settings reset

**Comment by rat-moonshine** [comment]
- Upon resetting, bottom SDK notification strap now showing properly
- After resetting startup prompt sequences re-initiated - SDK, Java etc.

**Comment by rat-moonshine** [comment]
- In Windows, everything shall reset including saved SDK list
- In Mac, except the bundled SDKs (~/Downloads/MoonshineSDKs) all other SDK will be removed from the list
- Per existing logic in Mac, one SDK will always set to default if any bundled SDK is present - after `Clear` (Moonshine > Settings > Default SDK) or `Reset` (Moonshine > Settings > General) happen

**Comment by JoelProminic** [comment]
I ran some tests for resetting the template data.

I added a comment line to each of the file templates, and then reset the settings.  My changes were cleared.

I added a new file template with "Create new".  After I reset the settings, this was cleared.  (NOTE:  I could not change the new file name, and I'm not sure how this would integrate with the current UI anyway.  We may need to revisit this feature at some point).

For the project templates, I added a comment to the main file for each of the projects.   I verified that my changes were reverted after running "Reset Everything".

**Comment by rat-moonshine** [comment]
> I could not change the new file name, and I'm not sure how this would integrate with the current UI anyway. We may need to revisit this feature at some point

I think we could have a new issue reported on this, as an enhancement.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine can we raise the new issue for that one and close #27 ?

**Comment by rat-moonshine** [comment]
That is how we agreed in fact in our last discussion with Joel. So yes, we can proceed that way, @piotrzarzycki21 .

**Comment by piotrzarzycki21** [comment]
Issue mentioned by @JoelProminic has been extracted #62
