### ISSUE TITLE
Moonshine trying to locate playerglobal.swc

### ISSUE THREAD

**Issue by t4e192** [prominic/Moonshine-IDE#273]
Trying to figure out how to import an Adobe Flex Project for Flash Builder 4.6 and get it running in Moonshine IDE.
Unable to find Adobe Flash Player 27.0 playerglobal.swc

**Comment by piotrzarzycki21** [comment]
Hi Jemmy,

So do you using Adobe Flex 4.6 SDK ? Is it desktop or browser application?

**Comment by t4e192** [comment]
Hi there

It is a browser application that is developed on FB 4.6
I was thinking about using moonshine to continue the latter developments.

Jemmy

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________

**Comment by piotrzarzycki21** [comment]
Let me pickup tomorrow some old 4.6 SDK and try to create Moonshine project. 

In the meantime - can you show me console log if it's possible.

Right click on project - Settings - show me Paths.

Do you have globally setup Flex SDK or in project settings?

**Comment by rat-moonshine** [comment]
@t4e192 , make sure your results are not related anything to this - https://github.com/prominic/Moonshine-IDE/issues/36.

**Comment by piotrzarzycki21** [comment]
I discovered that w I have removed ability to create Flex Browser Project in Moonshine during work on #182. I just bring back it. 

I did simple test and created Flex Browser project with [Adobe SDK 4.6](https://www.adobe.com/devnet/flex/flex-sdk-download.html) and everything seems to be working. 

@t4e192 I need a bit more information and answers to my question. 
Are you using Mac or Windows ?

**Comment by t4e192** [comment]
Hi there,

I’m using Windows 10 64-bits.

--Jemmy

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by piotrzarzycki21** [comment]
@t4e192 Did you try the newest version ? Do you have the same problem ?

**Comment by t4e192** [comment]
Hi Piotr,

I’ll give it another try, and let you know.

--Jemmy


________________________________

**Comment by atinprominic** [comment]
Hi

I give a test to this for the Flex Desktop. The build wad successful but while running it, it failed.

Check below logs for more details.

: Compiling NewFlexDesktopProject030818

: Sending to mxmlc: mxmlc -load-config+=obj/NewFlexDesktopProject030818Config.xml -optimize=false +configname=air -debug=true -o bin-debug/NewFlexDesktopProject030818.swf

: Adobe Flex Compiler SHell (fcsh)

: Version 4.6.0 build 23201

: Copyright (c) 2004-2011 Adobe Systems, Inc. All rights reserved.

:

: (fcsh)

: FSCH target: 1

: fcsh: Assigned 1 as the compile target id

: Loading configuration file C:\Users\Atin\Downloads\flex_sdk_4.6\frameworks\air-config.xml

: Loading configuration file C:\Users\Atin\Documents\MoonshineProjects\NewFlexDesktopProject030818\obj\NewFlexDesktopProject030818Config.xml

: bin-debug/NewFlexDesktopProject030818.swf (969808 bytes)

: (fcsh)

: Project Build Successfully.

: Launching application NewFlexDesktopProject030818.

: Application NewFlexDesktopProject030818 started.

: invalid application descriptor: Unknown namespace: http://ns.adobe.com/air/application/11.0


Also I have captured a screenshot for your reference.



![m3](https://user-images.githubusercontent.com/34882311/43642213-4e694560-9744-11e8-9720-0ff49a79a4cf.png)



Thanks
Atin

**Comment by rat-moonshine** [comment]
@atinprominic , you should use same Adobe AIR version number you are using. https://helpx.adobe.com/x-productkb/multi/how-overlay-air-sdk-flex-sdk.html probably bit older. It referenced to set the application descriptor value to `xmlns="http://ns.adobe.com/air/application/3.4">` but please check which Adobe AIR SDK version you're using actually.

Also, can you please share the value that write inside `/bin-debug/NewFlexDesktopProject030818-app.xml` file?

I believe a project once used with Flex SDK 4.6 should run with newer Apache Flex 4.16.1 (this might require some fundamental changes to code between old and new SDKs, though). If this wouldn't work and report unknown error, then we should look into that. Personally, I think we should concentrate with more recent SDKs.

I can give some test if I would found any older browser project that I may wrote in Flex SDK 4.6 days, and try to run in Moonshine, with recent SDKs.

**Comment by rat-moonshine** [comment]
It looks like the browser Flash support itself is terribly broken or much trickier to enable across the browsers nowadays. 

I took out following tests on Windows 10 x64 system, in Edge and Firefox browsers. 

- Created one web project "WebProjA" in Flash Builder with Apache Flex 4.16.1 with Flash Player 23.0
- Created another web project "WebProjB" in Flash Builder with its legacy Flex SDK 4.6 with min Flash Player requirement of 11.1
![image](https://user-images.githubusercontent.com/24370870/43644100-26c1c2f6-974b-11e8-9a8b-fd0dd1747610.png)
- Ran both the projects in both the browsers
- None of the projects ran in Edge
- Since Flash Player comes pre-integrated to Edge, I followed [this](https://helpx.adobe.com/flash-player/kb/flash-player-issues-windows-10-edge.html) instructions to make sure Flash enabled - but now no browser projects ran
- I moved to Firefox - I installed Flash Player 30.0 from the Adobe website - which should be sufficient for the tests
- I confirm I have the plugin installed:
![image](https://user-images.githubusercontent.com/24370870/43644349-0cbb8df0-974c-11e8-9811-611f0817282a.png)
- Even after multiple restarts none of the projects ran and shown silly messages:
**WebProjectA**:
![image](https://user-images.githubusercontent.com/24370870/43644404-348887de-974c-11e8-92fe-eb8c71c8e706.png)
**WebProjectB**:
![image](https://user-images.githubusercontent.com/24370870/43644421-4191cf4e-974c-11e8-95d9-089fad45ec7c.png)

I'm not sure if current provided `html-template` source are out-of-date considering latest browsers' requirement or not.

**Comment by atinprominic** [comment]
@devsena, I tried specifying the same version as well, but the same result. In fact irrespective of the version number I specify there, it always results the same.

 

I checked the version number  inside /bin-debug/NewFlexDesktopProject030818-app.xml file and found that its 11.0 value

 

I think there is some configuration we need to do in Moonshine to resolve it. But I am not sure.

 

Can you please guide further?

 

Thanks

Atin

 

 

----- Original message -----

**Comment by rat-moonshine** [comment]
You looped wrong 'devsena' @atinprominic .

**Comment by rat-moonshine** [comment]
Further investigating on this, @JoelProminic  helped me to remember about once taken investigation on this (browser project run), we found that newer browsers/OS only permits to run SWF locally _if_ ran through a server.

Testing further on this, I confirm Windows Edge remain shows broken in following all the tests. I have tested on Firefox and Chrome on Windows 10/64-bit.

I have installed Flash Player 30.0 in both the said browsers. 

SDK | Browser | Ran locally | Ran in server (Tomcat)
----- | -------- | ------------------ | ------------------
28.0 / 4.6 | Edge | Broken | Broken
28.0 | Firefox | Keep showing FP version requirement link | Success
4.6 | Firefox | Keep showing FP version requirement link | Success
28.0 | Chrome | Showing FP version requirement link - once clicked on the link, it asks for permission to run - given permission - success | Same as local run
4.6 | Chrome | Same as above | Same as above

So in my finding, I see the Moonshine wrapper HTML codes are still valid, but behaviour and run process differs between the browsers. Browser like Chrome is more open-hearted, Firefox seem restrict to run only through a web-server, Edge is completely broken for me.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine this is probably connected with that old issue #36 . I don't think above problems which you come into is part of problem which user reported. I'm proposing close this one. Thoughts ?

**Comment by piotrzarzycki21** [comment]
Let's close it, we don't have to focus too much on the browser. If it's working as you mentioned above it's ok to me.

**Comment by atinprominic** [comment]
Is there any update to resolve the issue of Flex Desktop project not opening after its build? Please let me know so that I can test it further. Currently Flex Desktop project is being built but not able to run it.

**Comment by piotrzarzycki21** [comment]
Atin please raise separate issue for that case. Specify OS, console log, SDK version.
