### ISSUE TITLE
Long project name makes "Recent" invisible on Home Tab

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#277]
If we have very long project name and it appears in Recent section of Home tab it makes list not visible. 

![long_project_name](https://user-images.githubusercontent.com/24554795/40359708-f6579fe8-5dc3-11e8-8af4-25d653301b80.png)

In order to test it open Royale project available in repository [BE0007_Selecting_options_from_a_group_of_jewel_checkbox_controls](https://github.com/apache/royale-asjs/tree/develop/examples/blog/BE0007_Selecting_options_from_a_group_of_jewel_checkbox_controls) or download [Nightly build](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/lastStableBuild/) where it will be available as well.

**Comment by rat-moonshine** [comment]
I see a problem in this non-maximized view:

![image](https://user-images.githubusercontent.com/24370870/40362482-46d18a80-5dea-11e8-8cc8-aeb61fde3431.png)

In above image, when restored from maximized state, 'Recent Projects' section continue to maintain a gap before its scroll, but 'Recent Files' section failing to maintain this somehow. However, when maximized, 'Recent Files' section continue to maintain this gap. Loosing this gap makes the items cropped behind the scrollbar in 'Recent Files'. 

On a second thought on long file name, I wonder if showing the name in wrapped line would look good or not, in most of the cases (other IDEs) I guess the names are truncated with dots.

**Comment by rat-moonshine** [comment]
This should have being fixed by now. Please, check.

**Comment by piotrzarzycki21** [comment]
It's working nicely now! Thanks!

**Comment by JoelProminic** [comment]
This works for me as well.   I found that the project names are being truncated in the macOS menu as well, but @rat-moonshine reported that this was a native menu feature.
