### ISSUE TITLE
Delete Project do not work for non existing projects

### ISSUE THREAD

**Issue by atingupta2005** [prominic/Moonshine-IDE#278]
When I use context menu to Delete the project listed in the Projects window, it does nothing for the non existing project. It should instead confirm the user to delete the entry from Projects window as the project directory is not physically available on the OS file system.

**Comment by rat-moonshine** [comment]
If I understood your situation clearly,

1. You opened a project to Moonshine
2. You deleted the project folder off-Moonshine
3. When you tried to delete the loaded project instance from Moonshine sidebar, it did nothing

Please, confirm if the above perception is true, then we shall need to handle this.

**Comment by atingupta2005** [comment]
Yes. Your understanding is correct

**Comment by rat-moonshine** [comment]
The incident opened up a much larger case of enhancement that requires to fit in current structure, to its File system. There are many other areas related to File management which may require to notify user about file unavailability and not limiting to the above incident @atingupta2005 reported. This non-exists file notification management should also needs to be in a structural way so we not end up alerting here and there. 

I've updated to the following issue as a fix for the time being. I shall follow up the possible enhancement in #287 .

**Comment by JoelProminic** [comment]
I have some minor grammar fixes.   These may become obsolete after #287 is implemented.

If I try to perform an action on a file and that file is missing (also if the parent directory is missing), I get this error:

    build.xml does not exists anymore.

Change this to:

    build.xml does not exists on the filesystem.  Operation canceled.


For a missing project, the current error is:

    TestDeleteMissing does not exists anymore. Click on OK to remove the project.


Change this to:

    The TestDeleteMissing project does not exist on the filesystem.  The project will be removed from Moonshine.

**Comment by rat-moonshine** [comment]
Messages has been updated. Please, check.

**Comment by JoelProminic** [comment]
The updated error messages look good to me.
