### ISSUE TITLE
Visual Editor submitted value not recorded by the history manager

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#279]
@JoelProminic reported this following scenario (which applies for all components):

1. Open a PrimeFaces Visual Editor project with its empty stage
2. Add DataTable component to the editor stage
3. While DataTable having the current selection, input some value in its "Empty Message" property value in property editor panel
4. Do not press Enter or Tab - this is important
5. Mouse click on the editor stage (that is the stage Div)
6. This will unselect DataTable and selects the stage Div
7. Changing to 'Code' pane shows the updated value again 'Empty Message' property to the DataTable
8. Returning from 'Code' pane and doing a Ctrl+Z removes the DataTable from stage - instead of restoring value to the 'Empty Message' [Bug]

**Comment by atinprominic** [comment]
@JoelProminic I am not able to find the "Empty Message" property at step # 3. Can you please support with some screenshot?

**Comment by JoelProminic** [comment]
@atinprominic , this should have been "No data to display"
![image](https://user-images.githubusercontent.com/24532731/40791023-0f1cf506-64bc-11e8-9d86-521e4ec4e80d.png)

I confirmed that this issue does not trigger for me after the update.
