### ISSUE TITLE
Add option to settings which allows change Java JDK path

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#28]
Add in the Moonshine's settings option which allows change path to Java JDK which being used by code completion.
- It allows change path in case when Moonshine was already configured with some version of JDK and we make an upgrade in the OS

**Comment by joshtynjala** [comment]
It might also be helpful if Moonshine checked if the saved JDK path still exists on startup.

If the path no longer exists, Moonshine could possibly clear the old value from settings and behave as if it were a clean install and the path had never been set.

**Comment by piotrzarzycki21** [comment]
I just added checks whether path to java still exists. If user had configured Moonshine with code completion and for some reason path to java changed - He will be prompted by standard popup:

![image](https://user-images.githubusercontent.com/24554795/32091387-3b8b2d78-baf4-11e7-95b7-de3ca410f266.png)
 
@rat-moonshine, @JoelProminic  Do you think that adding options to change Java path in "Settings" -> "General" is a good choice ? 
Since we have "Reset to Default" option now maybe we should not add additional settings for change Java Path ? Of course "Reset to Default" is doing much more, but still I prefer to ask what do you think guys.

**Comment by rat-moonshine** [comment]
IMO, setting Java path is a separate section of item than general. 'Reset to Default' does resets everything; if any user wants to change the Java path only, then using 'Reset to Default' could be an over-kill. 

Perhaps we setup a new Plugin section inside "Moonshine > Settings" against Java path setup, and it's reset option. I also noticed recently that using debugger also requires the Java path to be available. Previously we were only forcing the Java path against code-completion.

**Comment by JoelProminic** [comment]
Another option would be to add it to the "Default SDK" tab, and change the name to be something like "SDKs".

I don't have a really strong opinion on this, but my preference would be to create a new "Java" plugin section.  Admittedly, this would be a bit overkill unless if we needed to add more settings related to the Java configuration.

**Comment by rat-moonshine** [comment]
If we shall have a Java path selector option (somewhere in 'Default SDK' section), then we probably do not need any other 'Reset Java Path' option because the selector should do the job.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine , @JoelProminic ,

I was thinking about it more and come up to conclusion that we shouldn't put those setting "Java path" to "Default SDK"/"SDKs". This java path is require for code completion, "Default SDK" tab contains settings require for build project. If we won't setup Java path we will still be able to run our application without the problem.
Currently I'm all for having that settings as separate option called "Code Completion" or in "General" where section would be called "Code Completion" and there first settings related to that work:

"Code completion requires the Java Development Kit 1.8"     
"Path to JDK"                                                                        "Reset Java Path"

Where "Reset Java Path" will ask "Are you sure you want to reset path to the Java Development Kit?" - If yes user will go with existing flow where he will be asked for setting JDK.

We may have in the future more settings related to Code Completion.

Let me know what do you think.

**Comment by rat-moonshine** [comment]
Having Java to Moonshine is not only for code-completion. Java now uses in multiple sections -
- Code-completion
- Debugging
- Device installation through USB (https://github.com/prominic/Moonshine-IDE/issues/10)

Even the first and last feature could be ignored by an user, I think debugging is a basic development practice. But my point is, we're now using Java in multiple areas, for several stuff. 

As Joel suggested, we may not want to make this as *required* but definitely mention as something *important*. If that requires changing messages in opening Java prompt, we may need that. Also, since Java now uses in multiple sections, we may want to keep that in a area where it can attract user's eye (i.e. Default SDK).

**Comment by piotrzarzycki21** [comment]
@rat-moonshine ,

That is more clear to me. I will put it into Default SDK and I believe we need to change that initial message as you suggest. Maybe we should omit that message where we have "Moonshine optionally supports code completion..." and just started from Java setup with some message: "Would you like to have full experience with Moonshine like Code-completion, Debugging etc. ...". Please discuss closely this one with Joel. In the mean time I will add option to Default SDK as a starting point.

**Comment by piotrzarzycki21** [comment]
I have added option for reset Java JDK Path:
![image](https://user-images.githubusercontent.com/24554795/32180647-d0cd9358-bd92-11e7-8480-96217b89ab7a.png)

Once user click on reset gets question:
![image](https://user-images.githubusercontent.com/24554795/32180799-38a98b76-bd93-11e7-975a-367e72fefacf.png)

After confirm reset I'm going with existing flow where is displayed popup with question  "Moonshine optionally supports code completion..."

Please correct me if we would like to have it differently visually and text should be changed.

**Comment by piotrzarzycki21** [comment]
As we [discussed ](https://github.com/prominic/Moonshine-IDE/commit/b3a0c4ce78731be71ec638fc8dead2fdcec6ef53#commitcomment-25303707) Option has been changed to simple path setting where user can "Clear/Change" path to Java.

![image](https://user-images.githubusercontent.com/24554795/32228798-8b70012a-be4f-11e7-9a52-85553a333f91.png)
