### ISSUE TITLE
Closing Visual Editor tab throws exception

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#281]
- Run a Visual Editor project in Moonshine
- Do some activity to the editor stage
- Click on the close button in the editor tab
- Thanks to #268 Moonshine now throws an exception which probably we missed previously

> : Error #1010
> : TypeError: Error #1010
> : 	at actionScripts.ui.menu::MenuPlugin/ensureHideUnhideMenuOption()
> : 	at actionScripts.ui.menu::MenuPlugin/applyNewNativeMenu()
> : 	at actionScripts.ui.menu::MenuPlugin/onMacNoMenuStateChange()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at actionScripts.controllers::CloseTabCommand/execute()
> : 	at actionScripts.locator::IDEController/execCommand()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at actionScripts.ui::MainView/handleTabClose()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at mx.core::UIComponent/dispatchEvent()
> : 	at actionScripts.ui.tabview::TabView/onTabClose()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at mx.core::UIComponent/dispatchEvent()
> : 	at actionScripts.ui.tabview::TabViewTab/closeThisTab()
> : 	at actionScripts.ui.tabview::TabViewTab/closeButtonClicked()

**Comment by piotrzarzycki21** [comment]
If it's occurs on Mac only add some label. I haven't seen that one on Windows.

**Comment by atinprominic** [comment]
I tested it and its working as expected now. No any issue of error being thrown in the console.
