### ISSUE TITLE
PrimeFaces Grid component throws range error

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#282]
@JoelProminic reported the following scenario:

1. Add a new Grid component to the stage
2. Add a new row
3. Create three column to the new row
4. Remove the new row 
5. Exception throws

**Comment by atinprominic** [comment]
No any error is now being thrown. Its working as expected.

**Comment by JoelProminic** [comment]
I can't trigger the error any more either.  I tested with first, last, and middle rows, but they all could be removed with no errors.
