### ISSUE TITLE
Visual Editor history operation CMD-Z/Y do not works on macOS

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#284]
CMD-Z/Y not functioning expectedly on macOS but CTRL-Z/Y. This needs an investigation.

**Comment by atinprominic** [comment]
Getting the error log on console when doing CTRL+Z on GRID.

Step to reproduce:

1. Create Visual Editor Project
2. On the Form drop a Grid Component
3. Add few rows and columns to the Grid.
4. Press CTRL+Z.
5. Below log is thrown is console log:


: Error #2006
: RangeError: Error #2006
: 	at mx.core::Container/getChildAt()
: 	at mx.core::Container/getElementAt()
: 	at view.primeFaces.forms::GridForm/getSelectedCell()
: 	at view.primeFaces.forms::GridForm/onGridFormCreationComplete()
: 	at view.primeFaces.forms::GridForm/onGridUpdated()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at view.primeFaces.surfaceComponents.components::Grid/restorePropertyOnChangeReference()
: 	at view.suportClasses::PropertyChangeReferenceCustomHandlerBasic/changeItem()
: 	at view.suportClasses::PropertyChangeReference/undo()
: 	at actionScripts.plugins.ui.editor.text::UndoManagerVisualEditor/undo()
: 	at actionScripts.plugins.ui.editor.text::UndoManagerVisualEditor/dispatchPendingEvent()
: Error #2006
: RangeError: Error #2006
: 	at mx.core::Container/getChildAt()
: 	at mx.core::Container/getElementAt()
: 	at view.primeFaces.forms::GridForm/getSelectedCell()
: 	at view.primeFaces.forms::GridForm/onGridFormCreationComplete()
: 	at view.primeFaces.forms::GridForm/onGridUpdated()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at view.primeFaces.surfaceComponents.components::Grid/restorePropertyOnChangeReference()
: 	at view.suportClasses::PropertyChangeReferenceCustomHandlerBasic/changeItem()
: 	at view.suportClasses::PropertyChangeReference/undo()
: 	at actionScripts.plugins.ui.editor.text::UndoManagerVisualEditor/undo()
: 	at actionScripts.plugins.ui.editor.text::UndoManagerVisualEditor/dispatchPendingEvent()

**Comment by atinprominic** [comment]
CMD-Z/Y is working along with CTRL-Z/Y as expected.
