### ISSUE TITLE
The Source code of Visual Editor Project is not Editable

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#290]
Hi

I noticed that the source code of Visual Editor project is not editable at all.

I have recorded a video.

![vecodenotedit310518](https://user-images.githubusercontent.com/34882311/40769731-5c2cabce-64d6-11e8-83dd-3564b799da23.gif)

Thanks
Atin

**Comment by rat-moonshine** [comment]
It is intended to.

**Comment by piotrzarzycki21** [comment]
We are not going to give user ability to manipulate generated code by Visual Editor. This the most important rule in all of that effort.
