### ISSUE TITLE
Do you have any plan for git integration ?

### ISSUE THREAD

**Issue by nihavend** [prominic/Moonshine-IDE#291]
When i am using moonshine as development environment, i need git and had to use vscode for git. 
I tried FB but crashed.

Thank you very much for your help.

**Comment by piotrzarzycki21** [comment]
@nihavend Workaround which I can recommend you before with the Team we dive into that feature is [SourceTree](https://www.sourcetreeapp.com/). I believe it would be much easier for you have it opened than VSCode. 

In general the answer is yes - We may some day bring to the Moonshine Git support, but I'm not sure how it would looks like. We may end up with basic support where you will be able to type in console Git related commands. Not sure about that yet.

**Comment by nihavend** [comment]
SourceTree requires atlassian or bitbucket registration. Is it posssible to make it work with github ?

**Comment by piotrzarzycki21** [comment]
Yes it is possible. I'm using it every day.

**Comment by nihavend** [comment]
Let me find out.

**Comment by piotrzarzycki21** [comment]
@nihavend however you probably won't avoid signup first to attlasian, than you will be able to configure GitHub repositories.

**Comment by rat-moonshine** [comment]
@nihavend thank you for bringing the request in. 

We don't have any current plan or time-schedule against this, but we have created a separate issue against this as a future feature implementation #295 . You can track the issue as progress. For the time being its suggested to keep using 3rd party tool for the purpose.

In an effort to get the opened issues on this repo under control I'm closing this one as investigation. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to ask us from this channel or create a separate issue if any bug. Thank you!

**Comment by piotrzarzycki21** [comment]
Thanks @rat-moonshine
