### ISSUE TITLE
Improve console view to render rich text elements like hyperlink etc.

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#292]
As finding a way to #268 link rendering, current console view does not has the ability to render a text links. It'd be great if we can provide more rich text formatting options through this view.

**Comment by rat-moonshine** [comment]
After reviewing the current structure for a period of time, I have found its hard to make it more flexible without modifying the current flow in an extended way. Since the current structure is anyway much stable now, I don't think its wise to restructure the flow in a large way. 

I have made some changes, though, which will avail us the way to print any custom structured contents. I have tested to print report a bug link to the console after any un-caught error throws, and that goes well. I shall keep working on finalizing this report a bug link click flow.

**Comment by piotrzarzycki21** [comment]
Are you saying that you simply need to wrap up some text with ParagraphElement and send to console outputter ?

**Comment by rat-moonshine** [comment]
The current component uses rich text elements which is adequate to render rich HTML tags like span, link element etc. But as I've mentioned doing the way I was previously envisioned this does not fitting _without_ doing adequate changes to the current structure/format. I don't want to do that much of changes just to print a link element for this purpose, that would be over-doing.

Feel free to jump in if you have some nice plan (which you often do), else the current settlement should adequate to open the report a bug window and post the event.

**Comment by piotrzarzycki21** [comment]
The things how you did handle that right now is ok. I don't have any plan to work on that more.

**Comment by rat-moonshine** [comment]
I don't have any further plan against this. Closing.
