### ISSUE TITLE
Moonshine background image copyright removal and introducing additional information

### ISSUE THREAD

**Issue by JustinProminic** [prominic/Moonshine-IDE#294]
Per the request placed by Justin,

> We now have official legal permission to put back the image we have been using on the moonshine-ide.com website and the Moonshine IDE software.
> 
> We can also now REMOVE the copyright (c) Cristian F. from the homepage of Moonshine IDE and the website, since it is confusing.
> 
> I would, however, like to have the English text description of the picture and a reference to the author somewhere in the About, Help, or other menu since I would like people to know the history of this picture.

Copyright information from the splash screen was removed. 

We need to decide on where one can access the image information from Moonshine menu. Please place your recommendation.

**Comment by JoelProminic** [comment]
The new link and popup look like this:
![image](https://user-images.githubusercontent.com/24532731/40947551-e4176b5a-6828-11e8-9711-f7d387fcd85a.png)

The link should be updated to "About the background image".

**Comment by rat-moonshine** [comment]
I've updated the link text and title.

**Comment by JoelProminic** [comment]
Confirmed.  I am not 100% happy with the link message I selected, but I think it looks reasonable.
