### ISSUE TITLE
Basic GitHub support to Moonshine

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#295]
This would be an initial brainstorming and future implementation place for the said functionality to the Moonshine. The initial target should be basic (as we have for SVN), i.e. checkout, commit, push (including on-screen notification to the files those may have changes, ability to select through files, etc.).

Following is some basic features those supports by XCode against a project (through its in-built menu). My recommendation to target for the same basic functionalities excepts those are red-strike-through.

![image](https://user-images.githubusercontent.com/24370870/41025819-8adaec7e-6990-11e8-93f7-f03d6f765f23.png)

For `Checkout` we could also ask for user input (this might requires user authentication details as well - we need to investigate if the authentication is more complex than simple query request):

![image](https://user-images.githubusercontent.com/24370870/41026000-fbf2760c-6990-11e8-8f2a-cbafdc939331.png)

For `Commit`, my plan is to run `diff` and give a choice to select from the modified files before a commit.

New files wouldn't tracked by `diff`, for that user needs to add the file through `Add selected Files` command.

------------------------------

- [x] Clone
- [x] Checkout
- [x] Commit
- [x] Push
- [x] Pull
- [x] Revert
- [x] New Branch
- [x] Switch to Branch

**Comment by piotrzarzycki21** [comment]
@rat-moonshine we already have such issue - can you resolve duplication ? This one or raised by the user #291 - I prefer always have such things under the user issue.

**Comment by rat-moonshine** [comment]
I agree with you @piotrzarzycki21  when its a bug report and user shall keep updated with ongoing commits (posts) and the status. For new feature implementation, it might not be good to bomb user's email with lots and lots of status updates throughout a long running development. That might irritate the user :)

**Comment by piotrzarzycki21** [comment]
I don't see here problems at all, because you have "mute the thread." option. Still if user open feature request let's work there. In that case let's stay with following issue.

**Comment by rat-moonshine** [comment]
- Git availability check added
- Git clone function now working (tested in Windows)

**Comment by JoelProminic** [comment]
The updated code uses xcode-select to determine the location of the XCode installation that is currently in use:

    host-0653jcamacminiprominicnet:Downloads joelanderson$ xcode-select -p
    /Applications/Xcode.app/Contents/Developer
    host-0653jcamacminiprominicnet:Downloads joelanderson$ echo $?
    0


The Git executable is available underneath this directory:

    host-0653jcamacminiprominicnet:Downloads joelanderson$ /Applications/Xcode.app/Contents/Developer/usr/bin/git --version
    git version 2.4.9 (Apple Git-60)


This can also point to an installation of the XCode Command Line Tools. 

    host-0879lmcamacpro:~ luisalcantara$ xcode-select -p
    /Library/Developer/CommandLineTools
    host-0879lmcamacpro:~ luisalcantara$ echo $?
    0
    host-0879lmcamacpro:~ luisalcantara$ /Library/Developer/CommandLineTools/usr/bin/git --version
    git version 2.14.3 (Apple Git-98)


If XCode is not installed, you will see:

    host-0721kdcmacproprominicnet:~ treaddesk$ xcode-select -p
    xcode-select: error: unable to get active developer directory, use `sudo xcode-select --switch path/to/Xcode.app` to set one (or see `man xcode-select`)
    host-0721kdcmacproprominicnet:~ treaddesk$ echo $?
    2

You can detect this case by the non-zero exit code, or by the error message.

**Comment by JoelProminic** [comment]
In my test today, I was able to configure the XCode installation directory after clicking GitHub > Clone.  However, the clone operation itself failed with no error - I did not even get the prompt.  I checked Access Manager, and there was no entry for /Applications/XCode.app.

However, once I restarted Moonshine, I was able to use the GitHub > Clone operation successfully.

I would like to see the full clone path in this dialog, so that it is clear that I am defining the parent directory for the clone.  In the future, we may want to support selecting a different name for the cloned project.:
![image](https://user-images.githubusercontent.com/24532731/41552365-274b3e08-72f4-11e8-84b1-79590cdfe6f9.png)

**Comment by rat-moonshine** [comment]
- Updated git output listener based on Git behavior (internal)
- Clone now returns detailed result of the download process
- Added validation to test repository URL is valid Git URL (format: https://github.com/{org/author}/{project} (submission button enable/disable)
- 'target' path field now shows the formatted path (i.e. c:/user/desktop/{project})
- Menu type updated and all git menu options activates against the project has '.git' and '.git/index' file
- After setting up XCode for Git, Git Clone window do not opens in the same application session - fixed
- Added condition to test path with 'CommandLineTools' as a valid option for Git path on OSX
- Access Manager was failing to populate with the bookmarked paths - fixed

**Comment by JoelProminic** [comment]
I figured out how to test the other xcode-select cases from my workstation.  Before you use these commands, make sure to save the original value.

To test with the Command Line Tools, use this command:

    sudo xcode-select -s /Library/Developer/CommandLineTools


To simulate no installed XCode SDK, change the directory names for both Xcode.app and CommandLineTools.  Rename the directories when you are done

And then reset to the original state using one of these commands 

    sudo xcode-select -r
    # substitute your own directory here
    sudo xcode-select -s /Applications/Xcode.app/Contents/Developer


XCode Status | Result
------------ | ------
Full XCode installation | Works 
Command Line Tools | Failed - I can't select the CommandLineTools directory in the Filechooser 
No Installation | Reports error to console (no highlighting):  ": xcode-select: error: unable to get active developer directory, use `xcode-select --switch` to set one (or see `man xcode-select`)"

**Comment by JoelProminic** [comment]
> Clone now returns detailed result of the download process

This works.  The command output spams the console, since it can't overwrite the text on the console, but this is fine for now.

> Added validation to test repository URL is valid Git URL (format: https://github.com/{org/author}/{project} (submission button enable/disable)

I confirmeed that "github.com" and "{org/author}/{project}" are checked.  The protocol ("https://") is not checked.

Do we need to specialize this for GitHub?  Prominic does not have a Git server, and I don't have another convenient server to test on, but other users could have their own servers that they are using.  That said, other servers may require authentication.

> 'target' path field now shows the formatted path (i.e. c:/user/desktop/{project})

The "/Moonshine-IDE.git" path is displayed in the directory field.  This looked strange to me initially, but I think it makes sense.

> Menu type updated and all git menu options activates against the project has '.git' and '.git/index' file

This does not work for Moonshine-IDE because the projects we want to open with Moonshine do not have the .git directory

I was able to get this to work with a new project initialized with "git init".

It looks like the other GitHub menu actions have not been implemented yet.  

> After setting up XCode for Git, Git Clone window do not opens in the same application session - fixed

This works, but I have to use the GitHub > Clone menu a second time:
1. GitHub > Clone
2. Go thorugh the process to setup git
3. BUG:  The Clone dialog does not open
4. GitHub > Clone.  This works properly

> Access Manager was failing to populate with the bookmarked paths - fixed

Confirmed

**Comment by rat-moonshine** [comment]
XCode Status | Result | Revised
------------ | ------ | -------
Command Line Tools | Failed - I can't select the CommandLineTools directory in the Filechooser  | I overlooked the need of different method in case of directory selection but file selection. Should be fixed in newer build
No Installation | Reports error to console (no highlighting):  ": xcode-select: error: unable to get active developer directory, use `xcode-select --switch` to set one (or see `man xcode-select`)"  | Should be reported in newer build as error

**Comment by rat-moonshine** [comment]
Do we need to specialize this for GitHub? Prominic does not have a Git server, and I don't have another convenient server to test on, but other users could have their own servers that they are using. That said, other servers may require authentication.

The current URL test goes through simple regexp condition - at present, the condition is set as `github.com/.*/.*.$` which covers following cases:

1. The URL must have `github.com` reference
2. There must be two front-slash followed by the `github.com` reference - `https://github.com/{org/author}/{project}`
3. After second front-slash there must be some character/word

I'm not sure about what you tried to point by specialised Git server, but generally cloning from Git do not asks for any authentication. _Pull_ will do.

**Comment by rat-moonshine** [comment]
> > Menu type updated and all git menu options activates against the project has '.git' and '.git/index' file
> 
> This does not work for Moonshine-IDE because the projects we want to open with Moonshine do not have the .git directory

Process updated to test a folder with standard _Git_ command if a Git repository. This will allow us to validate even if the folder do not contains a '.git' directory.

**Comment by rat-moonshine** [comment]
Initial commits added against `Git > Commit` functionality.

At this moment, the opening window is suppose to show all those files has changed ran by `git diff` command. Commit button is non working.

**Comment by rat-moonshine** [comment]
**Following things have only tested on OSX. Windows tests are pending**

**Fixed issues**

1. @JoelProminic  reported that opening a Git type of project in Moonshine disables its `File > New` context menu items (in sidebar) - fixed
2. Git type of project opens do not immediately enables all options under `Git` menu - fixed
3. During our nightly tests I noticed _git_ repository detection (detect a folder is a _git_ repository) was not working for me on sandbox Moonshine, but it was worked good for @JoelProminic . Following are detail finding and fixes.

After some investigation I have noticed that git repository test command was failing in sandbox Moonshine, in following situation:

```
    /User/Desktop/MoonshineGIT/ide/MoonshineDESKTOPevolved ------- bookmarked (has access)
    /User/Desktop/MoonshineGIT/.git ------------------------------------ not-bookmarked (has no access)
```

In @JoelProminic 's case, he might had access to the root path of the repository as well, during his tests. Thus, he didn't had any problem running repository test command in his test. In my case, I only had access to the `MoonshineDESKTOPevolved` project folder. Once added `/User/Desktop/MoonshineGIT` to the Access Manager, I also able to run the command without any problem in sandbox.

So I made some changes to Moonshine. During project opening, Moonshine will anyway try to determine if the project is part of a _git_ repository, and asks for permission if user wants to access Moonshine Git functionalities, to give access to the repository root URL; with following window:

![image](https://user-images.githubusercontent.com/24370870/41718864-e4d4acd2-757b-11e8-8599-c22f61160c7c.png)

User can optionally provide permission, or ignore the choice - Git functionality will not be available to the project.

**Continuing functionalities**

1. Based on Commit selection window, Moonshine now commits selected file with dummy comment - _Note:_ this isn't the complete state of the `commit` process but an on-going process to test `commit` functionality, I have more plan for this
2. Basic `push` now works as well - _Note:_ at this moment during my tests, Moonshine auto-fetch my saved Git credential from OSX and submits the process - without asking for any credential. I shall need to investigate what kind of prompt `git push` asks when no credential is present, and therefore design the prompt to ask credential. I did my initial homework to test `push` with credential and that is working

**Comment by rat-moonshine** [comment]
- All the existing running commands adjusted to run on Windows
- New authentication window introduce to run on Windows prior to push
- Push now runs with the given authentication
- Git diff logic re-written to get the change details more easily and properly: Previously we were using `git diff` to get the change details. After some more investigation it turned out that parsing paths and file status from the output is quite difficult and error-prone. The output returns different type of formats between file modification, deletion and addition, along with differences between text and binary files. The path detection also became quite troublesome in certain scenarios, as well. Moonshine now uses different command to get the expected results in a more fluid way and easy to parse.
- Git commit window now red-colors deleted files as well which can be included into the git commit process

**Comment by JoelProminic** [comment]
I found this command to list the modified files for a git project:

    git status --porcelain
    
    # example
    host-0653jcamacminiprominicnet:TestLocalGit joelanderson$ git status --porcelain
     M src/TestLocalGit.mxml
    ?? src/TestAdditional.as
    ?? testadd/

This option is intended for machine readability, and the format is constant between versions and documented:  https://git-scm.com/docs/git-status#_porcelain_format_version_1

**Comment by rat-moonshine** [comment]
- Change command to get modified file list with `git status --porcelain`
- Git Commit window now reports newly un-tracked files as reported from the above command, user can adds the new files from the same window
- First commit against `Git > Switch to Branch` - this shall report available branch and change branch upon list selection (_Note_: File conflict tests not done in this version)

**Comment by rat-moonshine** [comment]
After updating the git list fetch command, Moonshine successfully able to switch between Moonshine Git branches. However, there are occasion when the process breaks, as described in #315 .

While introducing to new branch feature, I see there is a lot of re-structure may needed to make things more structural in a way. I'm working on those re-structuring areas now.

**Comment by rat-moonshine** [comment]
Following things which have updated today:

- Commit fix on OSX
- Git authentication window now provides an option to save auth against project's session (I'm not sure if we want to save only auth in Moonshine session or multiple - at present, this planned to save each project basis)
- New branch creation, immediate _push_ as an optional option
- Switch to branch option
- After _pull_ and switch branch, project's file tree refreshed
- While _pull_ and switch branch, language-server requests to stop and restart (when Git process completes) - but this is broken at this moment, details below
- Lots of restructuring in Git process management

While testing with a fresh Git project, all of the above process ran well between the OS, but using with Moonshine Git projects and still throwing different file system error with language-server due to non-working of stop/restart language server process. 

As per our discussion, I was trying to stop and restart language-server in the occasion of _pull_, checkout etc. events (to overcome different problems as one reported in #315 ), but this is working effectively. I may need Josh's guidance. 

@joshtynjala , due to the file-system error that reported recently at [here](https://github.com/prominic/Moonshine-IDE/issues/315#issuecomment-400190959), we decided to stop the language-server internally before such Git event, and restart the server again when the event completes. I tried to start/stop the running server, but I noticed the running Java process in Task Manager is not closing but creates a new one (probably when I tries to restart the server).

Can you guide me how to effectively close the server against a project and restart again?

At this moment, I've added two new events in [TypeAheadProcess](https://github.com/prominic/Moonshine-IDE/blob/5f0ba968b7e19c65d608941c21a818066c6d25ef/ide/MoonshineDESKTOPevolved/src/actionScripts/utils/TypeAheadProcess.as#L36) class and using to stop/restart during Git process:

```
dispatcher.addEventListener(TypeAheadEvent.EVENT_START_AGAINST_PROJECT, addProjectHandler);
dispatcher.addEventListener(TypeAheadEvent.EVENT_STOP_AGAINST_PROJECT, removeProjectHandler);
```

I didn't wanted to use existing `ProjectEvent.ADD_PROJECT` and `ProjectEvent.REMOVE_PROJECT` event as dispatching them might affect in other unintentional areas also. But this do not exists the running Java process effectively.

**Comment by joshtynjala** [comment]
@rat-moonshine I will be looking into the file system errors over the next few days. Hopefully, your workaround will not be required at all. Please avoid trying to restart the language server unless I determine that it's necessary.

**Comment by rat-moonshine** [comment]
Okay. Thank you for confirming, @joshtynjala .

**Comment by rat-moonshine** [comment]
Since Moonshine do not gives any Git file conflict/resolve feature, I have introduced Git Revert (as it is in TortoiseGit) which become handy many a time in my use. Revert option is applicable against the files those were deleted, modified or newly added (un-tracked).

I don't know what Refresh Status is suppose to do - so I removed it. 

Checkout option now works. Removed extra stop/restart events against language-server after suggested by Josh.

**Comment by rat-moonshine** [comment]
While creating a new project with Moonshine project templates, Moonshine was throwing following error - this is now fixed. I wanted this to be documented somewhere. 

```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at actionScripts.plugins.git::GitProcessManager/getGitRemoteURL()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\plugins\git\GitProcessManager.as:150]
	at Function/http://adobe.com/AS3/2006/builtin::apply()
```

**Comment by JoelProminic** [comment]
@rat-moonshine and I noticed this error while testing GitHub > Revert with the MoonshineDESKTOPevolved project:

    :  M ide/MoonshineDESKTOPevolved/libs/VisualEditor-0.2.0.swc
    : error: pathspec 'ide/MoonshineDESKTOPevolved/libs/VisualEditor-0.2.0.swc' did not match any file(s) known to git. 

Instead, we need to use the relative path:

    git checkout libs/VisualEditor-0.2.0.swc

I think that there should be an option or format to make git treat the given path as relative to the root of the project, but I could not find this in the documentation:
https://git-scm.com/docs/git-checkout
https://git-scm.com/docs/gitglossary (see "pathspec")

**Comment by rat-moonshine** [comment]
The above problem is solved by running _NativeProcess_ to local Git root, instead of project root. In that way a given path like `ide/MoonshineDESKTOPevolved/libs/..` runs true without throwing the above error.

Except that few other things also fixed:

1. Parsing a larger list consists of 300-400 items during Git Revert was failing to list properly in the opening selection window (I able to get 409 items by changing between different branches)
2. Revert/Commit popup selection list was cropping large item value horizontally

While Git Revert a number like 409 of items, I came up by other problems towards process and UI freezing. This turned out that running following command with a quite large list of files failing with error.

```
git checkout fileA fileB fileC fileD .... [large number of files]
// thrown error
Error #3219: The NativeProcess could not be started. 'The filename or extension is too long.
```

Debugging the files' references I didn't found anything un-natural, though, which can break the command. There is also no convenient way to determine till which number of files' reference the above command is good to go.

Beside that, when running `git reset` command (which runs against individual files only) against a large set of files, running _NativeProcess_ in a large looped way (asynchronous) makes the UI anyway unresponsive for an unrecorded time. 

During the above two problems, and if we want to run _NativeProcess_ as a chain of process against a large amount of files, it might be wise to run them in a different thread. The same way we have parsed files in case of `Project > Search` command and result the output to Moonshine UI, as necessary. I am still trying to fix the codes to make the procedures more generic between the worker class and the main Moonshine thread.

**Comment by rat-moonshine** [comment]
- Complete process decoupled to work with Moonshine worker class 
- Large amount of Git checkout/revert now supported without freezing UI in an extended manner
- Statusbar busy notification now shows in case of certain Git processes

**Comment by rat-moonshine** [comment]
Following two errors that we found during opening Moonshine with Git/non-Git type of projects on sandbox, are fixed:

#### Case A
```
: Error #1009
: TypeError: Error #1009
: 	at actionScripts.plugins.git::GitProcessManager/getCurrentBranch()
: 	at actionScripts.plugins.git::GitHubPlugin/onGitRepositoryPermissionClosed()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at components.popup::GitRepositoryPermissionPopup/closeButtonClicked()
: 	at components.popup::GitRepositoryPermissionPopup/closeButtonClickedRequest()
```

#### Case B
```
: Error #1009 
: TypeError: Error #1009
: at actionScripts.plugins.git::GitProcessManager/initiateSandboxGitRepositoryCheckBrute()
: at actionScripts.plugins.git::GitProcessManager/shellData()
: at actionScripts.plugins.git::GitProcessManager/onWorkerValueIncoming()
: at flash.events::EventDispatcher/dispatchEvent()
: at actionScripts.locator::IDEWorker/onWorkerToMain()
```

There were cases when opening Moonshine with multiple-project wasn't enable/disable Git menu effectively between the projects. This current condition should be improved by now.

### Something may requires separate issue to track

In sandbox, I noticed if a project opens with other linked-projects and they do not have bookmark access, language-server throws file access errors. Here's a simple test case to this,

1. Revoke all access by going into `File > Access Manager`
2. Give a restart to Moonshine
3. Open MoonshineDESKTOPevolved with file browser in Moonshine - this will add the project folder to bookmark
4. Language-server throws error against the linked project path _MoonshineSharedCore_ - which is not bookmarked
5. Once bookmarked manually, MDE do not throws that error anymore. 

```
: Failed to watch source path: /Users/santanu/Documents/Adobe Flash Builder 4.7/ProminicGITBranch/ide/MoonshineSharedCore/src
: java.nio.file.FileSystemException: /Users/santanu/Documents/Adobe Flash Builder 4.7/ProminicGITBranch/ide/MoonshineSharedCore/src: Operation not permitted
: 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
: 	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:406)
```

**Comment by rat-moonshine** [comment]
I noticed a strange situation between Windows and macOS. I able to produce this in Moonshine Git download but in other test download.

Generally, if you have any uncommitted change locally, before changing branch _git_ throws error to commit the changes first. You can then either commit or revert the changes by following command:

`git checkout <fileName>`

Once files are restored, you can change the branch without any problem. This tested works good on Windows. To restore back a file from repository the above is the valid option as well as discussed in online articles.

In my El Capitan tests on Terminal, I noticed strange behaviour, though.

1. I know I has three uncommitted changes locally
```
$ git status --porcelain
 M ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IVisualEditorLibraryBridgeImp.as
 M ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ui/editor/VisualEditorViewer.as
 M ide/MoonshineSharedCore/src/actionScripts/ui/menu/vo/ProjectMenuTypes.as
```

2. I ran to restore one file from repository
`$ git checkout ide/MoonshineSharedCore/src/actionScripts/ui/menu/vo/ProjectMenuTypes.as`

This above didn't thrown me any error

3. While running `git status --porcelain` again, I noticed it still reports all three files
4. Since above situation I never able to change my branch

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/42308398-117d9bd6-8053-11e8-9300-f6346fe4843f.png)

I couldn't able to reproduce the above window still coming when git root has already bookmark access, in sandbox. 

Generally, the window triggers when git repository test commands returns fatal error - that happens when the parent git root do not has bookmark access. If has access, then the fatal error do not comes followed by triggering this window.

**Comment by rat-moonshine** [comment]
I think we're more or less done to these basic functionalities to Git. Please, reopen if you found some problem, or open separate issue; I'm closing this to go with the next release.

**Comment by rat-moonshine** [comment]
I remember one thing to change - I shall talk with Joel once we have a time to discuss - to change to 'Revert' word/option to something more meaningful.

**Comment by piotrzarzycki21** [comment]
In the source tree is being used "Reverse commit..."

**Comment by JoelProminic** [comment]
Here are some text changes I would like to see changed in the Moonshine Git features.

The "GitHub" menu should be renamed to "Git".

Rename Git > Revert to Git > Status.  Change the prompt title to "Modified Files".  Remove the "Select files(s) to continue:" line.

The New Branch prompt does not need the "Note" line on the bottom, now that you have a checkbox.
![image](https://user-images.githubusercontent.com/24532731/42392716-5aa8fe06-8119-11e8-9116-1e794734320a.png)



I have multiple changes for the prompt that appears when Mooonshine needs access to the "root" Git directory:
![image](https://user-images.githubusercontent.com/24532731/42392724-62f9b848-8119-11e8-8e5b-d63e203411e3.png)

Original Text:
>It appears that the project MoonshineDESKTOPevolved is a Git repository project. Due to Apple sandbox, Moonshine do not has access to the root location of the Git repository, unfortunately.  
>
>You can allow permission to access to the location by clicking on Allow Access button below, to avail Moonshine Git functionalities. In the opening window click on "Open".  
>
>/Users/joelanderson/Documents/Flex/temp_workspace/Moonshine-IDE

Change this to:
>Moonshine has detected that the project <project> is part of a Git repository.  However, the Apple Sandbox has blocked access to the root directory of this project, so Moonshine will not be able to erform any Git actions.
>
>To enable the Git menu actions for this project, click "Allow Access" below.  Browse to the directory listed below and click "Open".
>
>Root Directory:  <directory>

Update the "I Don't Want Git Feature" button to "Skip".

**Comment by JoelProminic** [comment]
GitHub > Switch Branch does not open a prompt for me on Mac OS.  The only action I see is this line on the console:

>: Fetching branch details...

**Comment by JoelProminic** [comment]
I noticed these file access errors in my testing today on Mac OS:

1. Clear the file access from File > Access Manager
2. Open MoonshineDESKTOPevolved
3. Allow access to the "root" directory - now Moonshine should have all the access it needs
4. GitHub > Pull - See Error #1009 below
5. Try to revert a file with GitHub > Revert - See Error #1010 below
6. Restart Moonshine
4. GitHub > Pull - This works fine
5. Try to revert a file with GitHub > Revert - This works fine

Push error:

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugins.git::GitProcessManager/pull()
    : 	at actionScripts.plugins.git::GitHubPlugin/onPullRequest()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
    : 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
    : 	at actionScripts.ui.menu::MenuPlugin/redispatch() 

Revert error:

    : Error #1010
    : TypeError: Error #1010
    : 	at actionScripts.plugins.git::GitProcessManager/revert()
    : 	at actionScripts.plugins.git::GitHubPlugin/onGitRevertWindowClosed()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at components.popup::GitCommitSelectionPopup/onSubmit()
    : 	at components.popup::GitCommitSelectionPopup/__btnCommit_click()

**Comment by rat-moonshine** [comment]
- All the text changes - done
- `Error #1009 and #1010` - fixed

Following is a test matrix after today's fix on macOS:

Tested Project | Method | Access Manager State | Output
----------- | ------- | -------------------| ---------
Test Project | Commit | Normal | OK
Test Project | Push | Normal | OK
MDE | Pull | Normal | OK
MDE | Status | Normal | OK
MDE | Switch to Branch | Normal | After branch selection, Moonshine thrown error ```
error: Your local changes to the following files would be overwritten by checkout:
: 	ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IVisualEditorLibraryBridgeImp.as
: 	ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ui/editor/VisualEditorViewer.as
: 	ide/MoonshineSharedCore/src/actionScripts/ui/menu/vo/ProjectMenuTypes.as
: Please commit your changes or stash them before you can switch branches.
```
Test Project | New Branch | Normal | OK

**Comment by rat-moonshine** [comment]
> GitHub > Switch Branch does not open a prompt for me on Mac OS. The only action I see is this line on the console:
> 
> : Fetching branch details...

I couldn't able to reproduce the issue with my tests on sandbox, however, some commands some time takes longer to completes. This is probably related to a given time's network state.

**Comment by rat-moonshine** [comment]
> In my El Capitan tests on Terminal, I noticed strange behaviour, though.
> I know I has three uncommitted changes locally
> $ git status --porcelain
>  M ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IVisualEditorLibraryBridgeImp.as
>  M ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ui/editor/VisualEditorViewer.as
>  M ide/MoonshineSharedCore/src/actionScripts/ui/menu/vo/ProjectMenuTypes.as
> I ran to restore one file from repository
> $ git checkout ide/MoonshineSharedCore/src/actionScripts/ui/menu/vo/ProjectMenuTypes.as
> This above didn't thrown me any error
> While running git status --porcelain again, I noticed it still reports all three files
> Since above situation I never able to change my branch

The above behaviour which I reported some time back, and also @JoelProminic able to reproduce in his tests, I was looking for some reason causing this trouble, today. 

The most common ground against this problem through different article I've found is **line ending difference to a file**.

https://dzone.com/articles/git-showing-file-modified-even
https://stackoverflow.com/questions/2016404/git-status-shows-modifications-git-checkout-file-doesnt-remove-them

Following the StackOverflow link I tried to run some suggested command on Terminal, but `git status` keep reporting about files:

```
$ git config --global core.autocrlf false
// or
$ git config --global core.filemode false
```

For some, the above command works and for some not. I couldn't able to properly trigger out those commands against file(s) and having `git status` not to report against unexpected files.

**Comment by joshtynjala** [comment]
If you remove **--global**, it will override that setting for the local repository. It's possible that changing the global setting fails in repositories where it has already been overridden locally.

**Comment by rat-moonshine** [comment]
@joshtynjala , using the above command(s) with or without  '--global' keyword didn't affect result of git status for me (if that is what was suppose to be). Joel also had the similar results in his tests.

@JoelProminic also pointed my attention to one area which were require to re-visit - git authentication during _push_. Until now, an authentication window/popup always programmed to ask user to login before a _push_ command, on Windows. I previously noticed in my Windows' tests that it always requires me to authenticate through command line before a _push_ process. However, on macOS I have the push command always auth by stored credential in keychain. Thus, we didn't program the auth window to popup on macOS but we wanted to re-visit this - to ensure _push_ didn't terminate if there's no credential saved to keychain.

This article mentioned the process how one can remove saved Git credential from keychain and test:
https://help.github.com/articles/updating-credentials-from-the-osx-keychain/

After today's change, Git authentication window is suppose to come in both Windows and macOS based on command output:

1. Moonshine will try to _push_ without any credential
2. If the returning result shows it needs to authenticate, it'll popup the auth window; If the result shows no authentication needed (possibly because of system has saved credential), next steps will not execute
3. User can save the credential for that application session if they want from that popup window
4. Moonshine will re-try _push_ with the given credential

I also noticed, once a successful authentication happen and the command executed, macOS stores the credential to its keychain automatically. Therefore, from next time, only above \#1 step seems do the job.

The above process is also applicable in case of create new branch and push.

There were couple of other bugs fixed:

1. Clone wasn't working on macOS
2. Git commit was failing _add_ file with space (on macOS)
3. After any fatal output event, the very next command output wasn't validated (internal)

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/42621992-d9920a1a-85dc-11e8-8bb8-271cbbfff20e.png)

**Comment by JoelProminic** [comment]
I found this article about escaping command line arguments:  https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

The Windows special characters can be escaped with '^'.  The article also has an algorithm (written in C) for escaping characters with " and \\, which should work for macOS

**Comment by rat-moonshine** [comment]
https://stackoverflow.com/questions/19365843/passing-quotes-and-other-special-characters-literally-through-bash-and-ssh

**Comment by JoelProminic** [comment]
I tried testing commits with this string:

    Test "Escaped".  \"Special characters\".   `!@#$%()-_=+\;'",./?

The commit log matched this message exactly on both macOS and Windows.

While testing this, I noticed some discrepancies with the username and email address and the global configuration.  See #328.

**Comment by rat-moonshine** [comment]
I'm closing this issue to go with next release as mostly stable at this stage. Please, raise new issues if found something is not working.
