### ISSUE TITLE
InputNumber does not handle properly numbers greater than 999999999999999.

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#296]
This issue is extracted from  #260.

![ve35_1](https://user-images.githubusercontent.com/24370870/40978770-ae5e77fa-68f1-11e8-8666-c4630cb61444.gif)

We are using NumericFormatter which doesn't handle correctly numbers which are greater than 999999999999999. We need to investigate whether it is possible manipulation of numbers greater than 999999999999999.

**Comment by atinprominic** [comment]
I checked with multiple combinations and found no issue.

Its working as expected.
