### ISSUE TITLE
Re positioning of UI control on surface area is not working in Visual Editor

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#297]
Hi

I was creating Visual Editor project and found the issues related to UI controls placement.

Prime Faces:
Once the UI controls are placed, the user is not able to reposition the UI controls. If I place 2 controls and there after I want to exchange their positions then there is no way but to delete the first positioned UI control and then again place a new control.

Flex:
Once the UI controls are placed, the user can only reposition the controls using keyboard arrow keys. If the user tries to reposition the UI control using mouse drag and drop, it doesn't work. Mouse drag and drop is widely used in all the UI designers and every user is used to reposition using that. So we must provide this feature.

Please refer to below screenshot also:

![screen shot 2018-06-07 at 5 21 29 pm](https://user-images.githubusercontent.com/34882311/41099630-b633d4e8-6a7c-11e8-9e7a-8034bf812896.png)

Thanks
Atin

**Comment by JoelProminic** [comment]
When I was testing this for the last release, component reordering worked, but there were some issues (#255)

I confirmed that I cannot reorder the controls in the PrimeFaces Visual Editor with the latest build.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine above issue occurs because of that commit https://github.com/prominic/MockupVisualEditor/commit/9c956804e22aed42ab0019bf4db203e65297e79d line added in [EditingSurface.mxml](https://github.com/prominic/MockupVisualEditor/blob/46447768c740748349acefea6f6036da759a2790/src/view/EditingSurface.mxml#L522). I did remove line locally and it started to work, but I'm not sure what consequences we do have doing that ?

**Comment by rat-moonshine** [comment]
Yes, I'm afraid probably removing that throws error at certain point. If having that return statement makes other areas works good, then I shall need to re-visit again what was the exception, and find some workaround to it.

**Comment by piotrzarzycki21** [comment]
I did some small changes in undo/redo - in the places where I had null pointer or index out of bounds after repositioning components. If there will be some unwanted behavior in that area raise separate issue.
