### ISSUE TITLE
[CRITICAL] PrimeFaces Include component xhtml list do not updates effectively

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#300]
Since recent changes to file system update policy against Include component, it seems the xhtml list do not updates effectively anymore upon new file creation and deletion of existing file. Following are the test cases against the breaks:

## Case A

- Drag and drop an Include component to the editor
- xhtml list at this point shows all the existing xhtml files properly
- Create a new folder inside the source folder "mySubFolder"
- Create a new Visual Editor PrimeFaces file inside the newly created folder "myNewPrimeFacesFile.xhtml"
- Return to the Include component that created in first step
- Check the xhtml list - its updated with the new xhtml entry but showing the path and SETs the path wrongly: `src/mySubFolder` - omitting the file name

## Case B

- Drag and drop an Include component to the editor
- xhtml list at this point shows all the existing xhtml files properly
- Deletes an existing xhtml file from the source folder
- Return to the Include component xhtml file list
- The list didn't updated against recent file deletion

**Comment by piotrzarzycki21** [comment]
> Create a new folder inside the source folder "mySubFolder"

@rat-moonshine is this the case where for some reason during the export whatever additional file is created it landing to **includes** folder ? I need that following bug to be fixed. In the other words if user create file in visual editor src/dog/dog.xhtml after the export it should be still in such folder dog/dog.xhtml.

One more thing if you are going to work on that changes It would be the best if you can bring them today and I have them on Monday. I will be working in export area from Monday very extensively (I will raise new bug with description). My changes won't be part of 1.13.0.

**Comment by rat-moonshine** [comment]
> is this the case where for some reason during the export whatever additional file is created it landing to includes folder ?

I'm not sure if I understood clearly which problem you're pointing to. There was problem related to `Include` where exported project's xhtml files also get listed to the xhtml file list - which is resolved. But I don't think this is the same problem you're talking of. 

This issue related problems has resolved. You can start work with the class files from Monday.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine so can I go and make changes for Include ?

**Comment by rat-moonshine** [comment]
Sorry, I haven't noticed your comment @piotrzarzycki21 . You can proceed and make changes.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I will merge all stuff to master before. Do you have something to commit today ?

**Comment by rat-moonshine** [comment]
I shall probably. If you think, then I can hold my commits today and update after you merge.

**Comment by piotrzarzycki21** [comment]
Just the opposite go ahead and commit whatever you have!

**Comment by rat-moonshine** [comment]
This may take time, probably sometime at evening today I shall do that. Is that good with you?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine that's works! :)

**Comment by rat-moonshine** [comment]
I did some commit. You can go ahead and merge the latest @piotrzarzycki21 .
