### ISSUE TITLE
Error: #3219

### ISSUE THREAD

**Issue by apintex** [prominic/Moonshine-IDE#303]
Hello, this morning I updated to v1.13.0 and added a new project (MimobDisplay) to test. Here is the result:
![captura de ecra 2018-06-12 as 09 15 07](https://user-images.githubusercontent.com/6188954/41280200-45a88e82-6e26-11e8-9f43-3ba9cd3ef418.png)

PS: Report a Bug Does Not Work

Tanks
António Pinto

**Comment by rat-moonshine** [comment]
Can you give us some more information on this, @apintex ,

1. This looks like a regular Flex Desktop Project template that creates by Moonshine menu options - did you made any special changes to this project except setting a SDK?
2. Did you had anything trouble running before this event?

I have tried with my present available Apache Flex 4.16.1 and with Adobe AIR 29.0 on macOS and Windows system, but I couldn't able to produce the above scenario.

@piotrzarzycki21 can you give a try at your workstation (?)

Thanks!

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just tried and after "Build & Debug" application run without the problem. It's Flex Desktop app.

```
: Apache Flex Compiler SHell (fcsh)
: Version 4.16.1 build 20171115
: Copyright 2017 The Apache Software Foundation.
: (fcsh) 
: FSCH target: 1
: fcsh: Assigned 1 as the compile target id
: Loading configuration file /Users/piotr/Downloads/flex_4.16.1_air_29/frameworks/air-config.xml
: Loading configuration file /Users/piotr/Documents/NewFlexDesktopProject/obj/NewFlexDesktopProjectConfig.xml
: bin-debug/NewFlexDesktopProject.swf (1007914 bytes)
: (fcsh) 
: Project Build Successfully.
```

**Comment by piotrzarzycki21** [comment]
However something bothers me, because I think I should see after "Project Build Successfully." some console information that project is starting. Need to go step by step on my through whole that process. I'm occupy by other task, so feel free to look into that.

**Comment by rat-moonshine** [comment]
I'm not very sure about the notification system after compilation over in case of debug, but we probably can investigate more on this and allow some more information as you have pointed. We can track the requirement with a separate issue, though.

**Comment by piotrzarzycki21** [comment]
But we do have notifications, as you can see on @apintex screen, I'm just wondering why it is not displayed on my end. That's can be some hint to this error.

**Comment by apintex** [comment]
Hi @rat-moonshine , 
I did not make any changes. I just created the Flex and Build anda Run project.
The SDK is the same as Piotr sent me for previous tests: flex_4.16.1_air_29
I have installed Air Player 30

**Comment by piotrzarzycki21** [comment]
Ahh ok it was "Build and Run" I just checked with my machine and it also working:

```
: (fcsh) 
: FSCH target: 1
: fcsh: Assigned 1 as the compile target id
: Loading configuration file /Users/piotr/Downloads/flex_4.16.1_air_29/frameworks/air-config.xml
: Loading configuration file /Users/piotr/Documents/NewFlexDesktopProject/obj/NewFlexDesktopProjectConfig.xml
: bin-debug/NewFlexDesktopProject.swf (1007913 bytes)
: (fcsh) 
: Project Build Successfully.
: Launching application NewFlexDesktopProject.
: Application NewFlexDesktopProject started.
```

What about "Build & Debug" - Do you have the same experience ?

**Comment by apintex** [comment]
I changed the SDK to version 4.16.1 AIR 28 and it compiles and runs successfully

![captura de ecra 2018-06-12 as 12 15 30](https://user-images.githubusercontent.com/6188954/41287416-8b05ff3c-6e3a-11e8-895f-8216d3bf603f.png)
![captura de ecra 2018-06-12 as 12 14 20](https://user-images.githubusercontent.com/6188954/41287426-94099ee0-6e3a-11e8-84d5-1fb48c783ce6.png)

**Comment by apintex** [comment]
With SDK(flex_4.16.1_air_29), Build & Debug:

![captura de ecra 2018-06-12 as 12 24 57](https://user-images.githubusercontent.com/6188954/41287878-262596d4-6e3c-11e8-96ad-78828347946c.png)

**Comment by rat-moonshine** [comment]
> I got it I think so. The issue is probably in the descriptor. Can you check in your descriptor file -app.xml what version of AIR do you have ? You should probably have 29.0

The application descriptor file can hold any version figure for AIR, Moonshine adjust/update the version to copied application descriptor file to "bin-debug" based on current running SDK/AIR. So I don't think this area should create any problem.

**Comment by apintex** [comment]
I think there may be a problem in the SDK. The installer SDK (Apache Flex) does not work :( and I can not install a clean version of the SDK with AIR 29

**Comment by piotrzarzycki21** [comment]
There is a discussion on Flex Dev list about [installer issue](http://apache-flex-development.2333347.n4.nabble.com/Installer-is-Timing-Out-td65293.html). I hope it will be handled soon.

**Comment by apintex** [comment]
The same Flex project, the same framwork Flex 4.16.1 Air 29.
Build with Apache Ant, create ok the MimobDisplay.air, with some errors. 
I installed macos and it worked. Very strange!!!

![captura de ecra 2018-06-12 as 16 24 58](https://user-images.githubusercontent.com/6188954/41300625-1762e9d6-6e5e-11e8-9b22-a2a620d663a7.png)

**Comment by apintex** [comment]
Hello everyone, the same project to run perfectly, after updating the Flex Installer 3.3.2 and upgrading the SDK to 4.16.1 Air 30

![captura de ecra 2018-07-17 as 10 26 13](https://user-images.githubusercontent.com/6188954/42809060-90db04b0-89ac-11e8-8fb8-c4c464e519d7.png)
