### ISSUE TITLE
SVN process is broken

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#307]
Current SVN process is broken. It needs to re-visit the existing procedures and investigate what changes it needs to apply to work with current code-base.

**Comment by rat-moonshine** [comment]
I didn't liked the existing structure to SVN in Moonshine, but I don't want to waste effort to recreating the wheel completely. Instead, I chose to keep in the way it had been, fixed problems and modified some areas to use newer checkout and selection/commit windows that used in Git, with updated logic.

Following things has only tested on Windows so far:

- SVN options other than 'Checkout' now part of the top menu only, i.e. Commit, Update etc. - like Git menu options - they enables/disables upon testing the current project if SVN repository:
`svn ls <projectFolder>`
- Previous context-menu options for SVN to sidebar now removed
- SVN Checkout now uses existing Git checkout window with conditional logic - checkout procedure fixed - I'm not sure about more fine-tuned validation (like we have in Git checkout) on this case, though
- SVN Commit now uses existing Git selection/commit window. Requisite logic updated in SVN files to work with the popup codes - tested against file deletion, addition (unversioned) and modification

**Comment by rat-moonshine** [comment]
### Todo:

- [ ] Append possible folder name at the end of the target path in Checkout dialog

### Bugs:

- [ ] Setting binary on macOS throws error (`/usr/bin/svn`)

**Comment by rat-moonshine** [comment]
Debugging more on `/usr/bin/svn` file selection through Objc-c file dialog in sandbox, it returns following error:

```
"Error Domain=NSCocoaErrorDomain Code=256 "Could not open() the item"
UserInfo={NSURL=file:///usr/bin/svn, NSDebugDescription=Could not open() the item}"
```

The closest reason found at https://stackoverflow.com/questions/49206548/error-domain-nscocoaerrordomain-code-256 which match the using file format (`/usr/bin/svn` vs `file:///usr/bin/svn`); However, looking into the Obj-C codes I'm not at this moment sure where the said type-casting is happening. I need to look more into this.

**Comment by rat-moonshine** [comment]
Reading different discussion from here and there, the one most close scenario that found can cause `Error Domain=NSCocoaErrorDomain Code=256 Could not open() the item` error is when try to access a file with not properly construct as NSURL/URL for the file system purpose, i.e.

`URL(string:{systemPath});`

instead of 

`URL(fileURLWithPath: dataURLString)`

But every items returned by `NSOpenPanel` are fully-compliant `NSURL` objects. We are not preparing or constructing any NSURL/URL manually so we could have a chance of creating/using problematic `NSURL` pointer. 

I find out that the error throws when the URL/NSURL tries to add with bookmark scope in the Obj-c code. I even created new `NSURL` object constructing with suggested API and tried to add to bookmark scope, but `/usr/bin/svn` continued to throw same error. 

I tried a little hacky way. I know this may not be a right way of doing this, but we can take this as ethical hacking for the purpose. When `/usr/bin/svn` returns the file access error, I tried to auto-bookmark the parent directory of it `/usr/bin`. That did go well and didn't thrown any error. I have checked in Access Manager list (as returns by the extension) added with `/usr/bin` path.

When I tried to checkout a SVN path to my system, the execution thrown following error on console:
`: xcrun: error: cannot be used within an App Sandbox.`

I can remember we had such `xcrun` error situation in past, but I can't able to remember now where and when; or what was the resolution.

For the time being, I'm restoring the extension to all old codes.

**Comment by rat-moonshine** [comment]
> : svn: E170013: Unable to connect to a repository at URL 'https://svn-mysite.com/svn/trunk/AIRAppNapTest'
> : svn: E230001: Server SSL certificate verification failed: issuer is not trusted

**Comment by rat-moonshine** [comment]
There were two problems reported by @JoelProminic earlier against tests on sandbox Moonshine with SVN:

1. Subversion options do not enables except 'Checkout' for a SVN repository folder
2. The following permission window appears on his test, but didn't seem fix checkout problem with Prominic SVN server:
![image](https://user-images.githubusercontent.com/24370870/43705416-046764cc-9980-11e8-9186-8fbab1f248dd.png)

Against (1), I noticed some problem in event flow which modified now, that should improve the repository testing problem across Windows and macOS. However, running in sandbox, and testing against project from Prominic SVN, the command keeps throwing me certificate errors - thus project opened in Moonshine never enables all the options under `Subversion` menu.

Running command: `svn ls \Users\username\Desktop\SomeSVNProject`
Throws error in sandbox: 
```
: svn: E170013: Unable to connect to a repository at URL 'https://svn-mysite.com/svn/trunk/AIRAppNapTest'
: svn: E230001: Server SSL certificate verification failed: issuer is not trusted
```

On (2), looking into the existing codes, I see during checkout if the call runs through its error handler, it checks for following string output and therefore opens the `Allow Temporary|Permanent` window:

`Error validating server certificate for`

But I couldn't able to get the kind of error in my machine tests, thus not able to give physical test with the said window procedures.

**Comment by JoelProminic** [comment]
Running "svn help <command>", I can see these options avaialble for SVN on Mac OS X 10.10.5 (Yosemite):

    Global options:
      --username ARG           : specify a username ARG
      --password ARG           : specify a password ARG
      --no-auth-cache          : do not cache authentication tokens
      --non-interactive        : do no interactive prompting
      --trust-server-cert      : accept SSL server certificates from unknown
                                 certificate authorities without prompting (but only
                                 with '--non-interactive')
      --config-dir ARG         : read user configuration files from directory ARG
      --config-option ARG      : set user configuration option in the format:
                                     FILE:SECTION:OPTION=[VALUE]
                                 For example:
                                     servers:global:http-library=serf


@rat-moonshine reported that he saw an additional option on his machine:

   --trust-server-cert-failures unknown-ca,cn-mismatch,expired,not-yet-valid,other 


Note that the certificate checks are intended as a security measure, so we should not disable them by default.  Instead, we should give the user a checkbox (called something like "Ignore certificate errors") to add the certificates from the Moonshine Settings or from the Subversion panels.  The "--non-interactive" argument may be useful for all SVN commands from Moonshine.

**Comment by rat-moonshine** [comment]
With Command | Keychain against COMODO | Result
---------------- | ----------------- | --------------------------
--non-interactive | System default | : svn: E170013: Unable to connect to a repository at URL 'https://***.prominic.net/svn/***/trunk/AIRAppNapTest'
: svn: E230001: Server SSL certificate verification failed: issuer is not trusted
--non-interactive | Always trust | Same as above

**Comment by rat-moonshine** [comment]
Following were tested against `svn ls ${projectpath}` command in sandbox:

With Command | Keychain against COMODO | Result
---------------- | ----------------- | --------------------------
--non-interactive | System default | `: svn: E170013: Unable to connect to a repository at URL 'https://***.prominic.net/svn/***/trunk/AIRAppNapTest' : svn: E230001: Server SSL certificate verification failed: issuer is not trusted`
--non-interactive | Always trust | Same as above
--non-interactive --trust-server-cert | System default | `: svn: E170013: Unable to connect to a repository at URL 'https://***.prominic.net/svn/***/trunk/AIRAppNapTest' : svn: E215004: No more credentials or we tried too many times. : Authentication failed`
--non-interactive --trust-server-cert | Always trust | Same as above
--non-interactive --trust-server-cert --trust-server-cert-failures unknown-ca,cn-mismatch,expired,not-yet-valid,other | System default | Same as above
--non-interactive --trust-server-cert --trust-server-cert-failures unknown-ca,cn-mismatch,expired,not-yet-valid,other | Always trust | Same as above
--non-interactive --trust-server-cert-failures unknown-ca,cn-mismatch,expired,not-yet-valid,other | Always trust | Same as above
--non-interactive --trust-server-cert-failures unknown-ca,cn-mismatch,expired,not-yet-valid,other | System default | Same as above
 --trust-server-cert | System default | Same as above
 --trust-server-cert | Always trust | Same as above
--trust-server-cert-failures unknown-ca,cn-mismatch,expired,not-yet-valid,other | Always trust | Same as above
--trust-server-cert-failures unknown-ca,cn-mismatch,expired,not-yet-valid,other | System default | Same as above

**Comment by rat-moonshine** [comment]
`Subversion` menu options now enables upon existence checking of `./svn/wc.db` file to the project root.

In macOS, if an auth already present against certain SVN URL to keychain, Moonshine will continue using that information while `Update` and `Commit` from/to the URL.

However, if no auth present and update/commit returned by authentication failure message, Moonshine now open the same authentication window that used to Git auth. Upon providing necessary information, Moonshine will re-try to complete previously failed process. 

Once a _successful_ auth stored to keychain, user will not require to provide auth information again against certain SVN URL.

The above changes can be done by deleting named SVN password entry from the keychain in macOS. 

[_NOTE_: All tests done to macOS so far, Windows' tests pending. The way codes have done to SVN process is a mess and worst to an height - I only tried to fix the parts which requires to support above process, instead of re-inventing the full-workflow.]

**Comment by JoelProminic** [comment]
I got a certificate validation prompt on my checkout attempts:

    : Error validating server certificate for 'https://<censored>:443':
    :  - The certificate is not issued by a trusted authority. Use the
    :    fingerprint to validate the certificate manually!
    : Certificate information:
    :  - Hostname: <censored>
    :  - Valid: from Mon, 19 Mar 2018 00:00:00 GMT until Tue, 11 Jun 2019 23:59:59 GMT
    :  - Issuer: COMODO CA Limited, Salford, Greater Manchester, GB
    :  - Fingerprint: <censored>
    : (R)eject, accept (t)emporarily or accept (p)ermanently? 

I don't see an option to add the additional certificate arguments.


I manually checked out a project, but my authentication were rejected when I did an Update or Commit:

    : svn: E170001: 
    : Unable to connect to a repository at URL 'https://<censored>/svn/sh-flex/branches/TestMoonshineSubversionJoel'
    : svn: E170001: OPTIONS of 'https://<censored>/svn/sh-flex/branches/TestMoonshineSubversionJoel': authorization failed: Could not authenticate to server: rejected Basic challenge (https://<censored>)

I didn't get an authentication popup in my tests.

**Comment by rat-moonshine** [comment]
The prompt for authentication triggers based on certain message type, i.e. authentication failed. In this case it's rejection against some challenge - probably the challenge were in form of Reject, Accept and Accept Permanently. 

I noticed that checkout command was missing the extra arguments like `--non-interactive` etc. when other commands were added with them. You can give a try with the newer build, @JoelProminic , although since Update and Commit already has those extra arguments, I'm not sure why they're not trusting certificate and turning to challenge failure. (Maybe that is because the Accept|Reject prompt didn't affect at first place (?))

I'm not sure how to get this Accept|Reject error - maybe removing the Comodo certificate completely from Keychain would avail that - I'm not sure.

**Comment by rat-moonshine** [comment]
To able to get the error report containing `Accept | Reject | Accept Permanently`, I tried following things:

1. I had following items in my system's keychain (ignore the date values - screenshot taken after completing all these steps)
![image](https://user-images.githubusercontent.com/24370870/43882567-b88c5cce-9bcd-11e8-89f6-b706cced7a5a.png)
2. I only able to delete the last item from the list - other two items simply not deletes - while the first item thrown - `UNIX[Operation not permitted]`
3. I tried to checkout with Moonshine but I didn't reported by the `Accept | Reject` error with current build
4. I also changed the trust mode of the existing certificates to 'Never Trust' - but that didn't make any difference either 

I'm not sure at this moment how to get into the environment when the said type of error fires, so I can debug further.

**Comment by JoelProminic** [comment]
I have retested the SVN certificate issue, and it no longer triggers for me on either OS X Yosemite or macOS High Sierra.   

@rat-moonshine reported that Moonshine is currently using --trust-server-cert.  This setting should not be enabled by default, so please allow this to be enabled in a checkbox (similar to how authentication is working for the Checkout prompt).  

This selection can be persisted in the application or project settings.  Putting it in the project settings will allow the setting to be controlled for individual projects, so that the certificate will be  consistently ignored for a specific project.  Saving it at the application level will be convenient if all of the projects are from the same repository, but it is problematic if the user uses multiple SVN servers with different certificates.  I think using the Project settings is probably better, but I am open to discussion on this.

**Comment by rat-moonshine** [comment]
New option added to project's Settings: `Subversion > Trust server certificate` (default false?)

The above option is suppose to available if user has subversion configured (to Moonshine) and the project is a subversion project. I yet to connect the property to related SVN commands in Moonshine.

**Comment by rat-moonshine** [comment]
- Trust certificate option now relocated to the Checkout window from Moonshine Settings
- Checkout window now waits until the first response back from Git - to determine if its an error or results - based on that the window either report to check error details on console (as user may have console minimized or shrink to minimal height) and remain the inputs intact, or, close the window

**Comment by JoelProminic** [comment]
I updated this in CHANGELOG.md.   

Have you updated Windows with the "Trust certificate" option?   I thought of this at the end of the day and did not have a chance to test.
