### ISSUE TITLE
Project Directory Combobox Discrepancy

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#309]
@rat-moonshine and I noticed this error while testing Moonshine today.

When creating a new project, we found that the Parent Directory combobox showed the first parent directory in the list, rather than the most recently used directory (in my case, temp_workspace).  However the computed text below the combobox showed the most recently used directory.

![image](https://user-images.githubusercontent.com/24532731/41481205-bc98d9d0-7096-11e8-95de-3545512b01da.png)

We suspect that this is related to the export updates in #302, since the Export interface is using the same Project Directory field.

**Comment by piotrzarzycki21** [comment]
Actually I doubt that is problem which occurs after my changes. I saw that issue couple of times. I'm not using the same field to display export path - I've introduced new one.

**Comment by piotrzarzycki21** [comment]
I believe I have fixed it. Let's pay attention to that area.

**Comment by JoelProminic** [comment]
I did some quick tests with the parent directory, and I couldn't reproduce the original issue.  I'll update the issue if I see this bug again.
