### ISSUE TITLE
Access Manager throws exceptions

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#310]
After removing all existing bookmarks from `File > Access Manager` on macOS Moonshine, restarting Moonshine throws two different errors at different time:

When Moonshine revokes all access to system folders, opening Moonshine with any previously opened project throws the following - this also true when close and open the project during no access to file systems (this is possibly a side-effect after #287 changes and when revoked all file system access),

```
: Running on Adobe AIR 28.0.0.125
: Error #3001
: Error: Error #3001
: 	at actionScripts.impls::IFileBridgeImp/save()
: 	at actionScripts.plugin.actionscript.as3project.vo::MXMLCConfigVO/writeApplicationConfig()
: 	at actionScripts.plugin.actionscript.as3project.vo::MXMLCConfigVO/write()
: 	at actionScripts.plugin.actionscript.as3project.vo::AS3ProjectVO/updateConfig()
: 	at actionScripts.utils::LanguageServerForProject/sendProjectConfiguration()
: 	at actionScripts.utils::LanguageServerForProject/sendInitialized()
: 	at actionScripts.utils::LanguageServerForProject/parseMessage()
: 	at actionScripts.utils::LanguageServerForProject/parseMessageBuffer()
: 	at actionScripts.utils::LanguageServerForProject/onIncomingData()
:
: Click here to Report a Bug
```

While opening `File > Access Manager` window:

```
: Error #1009
: TypeError: Error #1009
: 	at components.popup::DefineFolderAccessPopup/updateBookmarkedPaths()
: 	at components.popup::DefineFolderAccessPopup/onCreationCompletes()
: 	at components.popup::DefineFolderAccessPopup/___DefineFolderAccessPopup_Canvas1_creationComplete()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at mx.core::UIComponent/set initialized()
: 	at mx.managers::LayoutManager/doPhasedInstantiation()
: 	at mx.managers::LayoutManager/doPhasedInstantiationCallback()
:
: Click here to Report a Bug
```

**Comment by rat-moonshine** [comment]
Since the former issue is more related to file process handling than Access Manager exception, and the latter one resolved, I'm closing this issue.

**Comment by JoelProminic** [comment]
I tested this, and I confirmed that the #1009 error does not trigger.

However, I noticed this error even when all of my projects opened in the sidebar.

    : Error #3001
    : Error: Error #3001
    : 	at actionScripts.impls::IFileBridgeImp/save()
    : 	at actionScripts.plugin.actionscript.as3project.vo::MXMLCConfigVO/writeApplicationConfig()
    : 	at actionScripts.plugin.actionscript.as3project.vo::MXMLCConfigVO/write()
    : 	at actionScripts.plugin.actionscript.as3project.vo::AS3ProjectVO/updateConfig()
    : 	at actionScripts.languageServer::ActionScriptLanguageServerForProject/sendProjectConfiguration()
    : 	at actionScripts.languageServer::ActionScriptLanguageServerForProject/languageClient_initHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.languageServer::LanguageClient/sendInitialized()
    : 	at actionScripts.languageServer::LanguageClient/parseMessage()
    : 	at actionScripts.languageServer::LanguageClient/parseMessageBuffer()
    : 	at actionScripts.languageServer::LanguageClient/input_onData()
    :
    : Click here to Report a Bug


After some investigation, I found that the problem was that I had a project open in ~/Downloads.  This directory is accessible without a bookmark because of an entitlement added for the application, but it was still triggering an error until I added an entry in Access Manager for the project.

I don't expect a fix for this, since the file access errors are expected after clearing the bookmarks, but I wanted to report this as a special case of the #3001 error.
