### ISSUE TITLE
Improve visibility of hidden files/folders in the project

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#312]
Justin raise and idea where we should be more transparent in case of our hidden files/folders. Here is my plan to full fill that requirements. 

User should be able to:
1. Show hidden files/folders in IDE **Settings** -> **General** -> **Show hidden files/folders**.
1. Mark files/folders as hidden.

User shouldn't be able to:
1. Mark files/folders in source folder as hidden (I think that's a simplification, because if we hide folder the expectation could be that it won't be part of compilation. - I think excluding files/folders from compilation may be difficult)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine , @JoelProminic Let me know if above requirements has sense to you.

**Comment by rat-moonshine** [comment]
> 2. Mark files/folders as hidden.

I'm unclear of the plan of marking file/folder as hidden. Is marking as hidden process is something native to Moonshine tree (i.e. that will/not be shown in the sidebar), or marking shall affect at system level file.

**Comment by piotrzarzycki21** [comment]
It affect only in Moonshine tree. If you let's say don't want to see bin folder you will be able to hide it.

**Comment by piotrzarzycki21** [comment]
> To clarify for this issue, @JustinProminic's request was to have better transparency for the hidden directories and files used by Visual Editor (i.e. visualeditor-src). We could apply this logic to files hidden at the OS level as well - I don't have a strong opinion on this at the moment.

I think we shouldn't touch files/folders physically on the hard drive.

> I think this is outside of the scope of @JustinProminic's request. This could be desired for hiding bin, build, obj, etc., though, so it might be an interesting feature.

Yes I remember that and we were also talking about changing folder name to "hidden" or something like that. - I'm not in favor of changing for now anything. Above option can give users flexibility. In the above approach I won't have to change any structures of our current Visual Editor project. The only thing which will appear is some kind of UI colors which indicates that this folder is "special" one. - In similar way as we are marking folders in Intellij. 

Let see how it will work. I'm more interested to have perfectly working exporting. This one can be improved once @JustinProminic review it on some call.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine from where did you get icon [icoSource.png](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/elements/images/icoSource.png) ? I would love to use similar one which indicates folder marked as hidden.

**Comment by rat-moonshine** [comment]
I had drawn this on Photoshop, but I don't think I stored any PSD against this, and only exported the PNG.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine any chance to draw something similar with letter "H" ?

**Comment by piotrzarzycki21** [comment]
First bunch of changes has been committed:
1. Option for showing hiding hidden files/folders is available in the settings
1. Hidden Files/folders has been marked by red color (the same as errors in the console)

I will try to work in the next days on option **Mark files/folders as hidden**:

> Mark files/folders in source folder as hidden (I think that's a simplification, because if we hide folder the expectation could be that it won't be part of compilation. - I think excluding files/folders from compilation may be difficult)

I think I won't restrict all of that to above. Visual Editor does have files inside src marked as hidden. I'm thinking right now that even if someone mark files as hidden inside src it doesn't mean that I should take care and exclude that files from compilation in case for example Flex project. 

If anyone will have time and can take a look on the current state that would be good. :)

**Comment by piotrzarzycki21** [comment]
Introduced changes:
1. Options for showing/hiding files in project tree has been added to the settings. Once user select **Show hidden files/folders** - Project need to be restarted (close/reopen) to apply that settings.
1. Options **Mark as Hidden**, **Mark as Visible** has been added to the context menu for opened project. Those options are available if **Show hidden files/folders** is selected
1. Hidden files/folders are marked by red color

**Comment by piotrzarzycki21** [comment]
Reopen if I need to implement something more or different.

**Comment by atinprominic** [comment]
Working good and as expected

**Comment by JoelProminic** [comment]
I confirmed that "Mark as Hidden", "Mark as Visible" and "Show hidden files/folders" are working as specified above on macOS.

The requirement to reopen the project after changing the "Show hidden files/folders" options is unintuitive, but it is sufficient for now.
