### ISSUE TITLE
Language-server break and leftover Java processes

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#313]
_Note: I'm not sure how to properly define the subject to this issue, please feel free to change the wordings if requires._

Recently, I started noticing again lots of Java processes keep running on Windows Taskbar resulting a slower system. While investigating, I found in two occasion Moonshine failed to stop Language-server Java processes when exit. When one possibly needs a fix, the other I'm wondering if possible somehow if we can handle it.

1. Language-server throws exception when parsing project with `{locale}` path - to test this you can open MoonshineDESKTOPevolved project on Moonshine, it has a path defined to its settings as "../MoonshineSharedCore/src/locale/{locale}":

```
: Failed to watch source path: E:\DevareaLocal\Moonshine-IDE\ide\MoonshineSharedCore\src\locale\{locale}
: java.nio.file.NoSuchFileException: E:\DevareaLocal\Moonshine-IDE\ide\MoonshineSharedCore\src\locale\{locale}
: 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
: 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
: 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
: 	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
: 	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
: 	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
: 	at java.nio.file.Files.readAttributes(Files.java:1737)
: 	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
: 	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
: 	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
: 	at java.nio.file.Files.walkFileTree(Files.java:2662)
: 	at java.nio.file.Files.walkFileTree(Files.java:2742)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.watchNewSourcePath(ActionScriptTextDocumentService.java:1477)
........
........
: 	at java.lang.Thread.run(Thread.java:745)
```

After above scenario, closing Moonshine do not exits the Java process language-server started against the project.

2. While debugging Moonshine, and opening a project inside it (Moonshine) starts the project's language-server Java process. Terminating debugging process do not exits the started Java process, though. I'm not sure though if its somehow possible to listen a debug-termination process in Moonshine code and let stop any running process, so this can remain in low priority

**Comment by joshtynjala** [comment]
This issue should now be fixed with the latest language server update that I committed.
