### ISSUE TITLE
Primefaces "Include" Component causes the Runtime error in Exported Project

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#314]
Below are the steps and required details:

OS Version: MAC

Steps:
1. Created a Visual Editor\Primefaces Project
2. Added UI component - "Include" to the project
3. Exported project using - Project\Export Visual Editor Project\Primefaces Browser Project
4. Compiled the exported project using "mvn clean install"
5. A war file is created named - VEPF250618_exported-0.1.0-SNAPSHOT.war
6. Deployed was file on Tomcat server running on Mac
7. Hit the URL: http://localhost:8080/VEPF250618_exported-0.1.0-SNAPSHOT/
8. The error is thrown as below:
-----------------------------------------------------
```
HTTP Status 500 – Internal Server Error

Type Exception Report

Message /index.xhtml @9,77 <ui:include src="VEPF250618.xhtml"> Invalid path : VEPF250618.xhtml

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: /index.xhtml @9,77 <ui:include src="VEPF250618.xhtml"> Invalid path : VEPF250618.xhtml
	javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

javax.faces.view.facelets.TagAttributeException: /index.xhtml @9,77 <ui:include src="VEPF250618.xhtml"> Invalid path : VEPF250618.xhtml
	com.sun.faces.facelets.tag.ui.IncludeHandler.apply(IncludeHandler.java:129)
	javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202)
	javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93)
	com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87)
	com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:161)
	com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:1004)
	com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:99)
	com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Note The full stack trace of the root cause is available in the server logs.
```

Apache Tomcat/9.0.7

**Comment by piotrzarzycki21** [comment]
Related to #302

**Comment by piotrzarzycki21** [comment]
It looks like I need to exclude main file of the project from Include component, or rather exclude from the list which we have opened. In the other world if you have opened file "VEPF250618.xhtml" you shouldn't be able add that file in Include component. 
I will work on that changes.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I need a bit of advice, where actually I could filter for Include file which is currently opened? I need to simply that file exclude from the list.

**Comment by piotrzarzycki21** [comment]
I was able to figure out something, but it's not a nice solution. I have noticed that when I'm adding new file to the project, list in Include component is not being updated with added file. I have close and reopen project. Not sure how it should actually work.

**Comment by rat-moonshine** [comment]
I have tested the reported problem (above) with a/two days' old build downloaded from Bamboo, I see the source folder location has changed to a PrimeFaces project - `[project]/src/main/webapp`. While creating and deleting .xhtml files, I see an Include component's available file list successfully updated upon the events. I couldn't able to reproduce the problem during my tests, though; I shall plan to test this with latest source - if that something changed by two days.

**Comment by atinprominic** [comment]
Hi @piotrzarzycki21 

I tested with latest build and again found the below issue on Tomcat:



HTTP Status 500 – Internal Server Error

Type Exception Report

Message /index.xhtml @31,65 <ui:include src="null"> Invalid path : null

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: /index.xhtml @31,65 <ui:include src="null"> Invalid path : null
	javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

javax.faces.view.facelets.TagAttributeException: /index.xhtml @31,65 <ui:include src="null"> Invalid path : null
	com.sun.faces.facelets.tag.ui.IncludeHandler.apply(IncludeHandler.java:129)
	javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202)
	javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93)
	com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87)
	com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:161)
	com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:1004)
	com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:99)
	com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/9.0.7

**Comment by piotrzarzycki21** [comment]
I will check that today!

**Comment by piotrzarzycki21** [comment]
@atinprominic I took over that problem. If there is only one file in the project (Main file) I don't "translate" Include component to the code. 

In the other words if you drop Include, there won't be any files on the list and switching to Code Include won't be placed.
![no_include](https://user-images.githubusercontent.com/24554795/42044475-6ce72adc-7af9-11e8-8878-eddf1b80b057.gif)

**Comment by atinprominic** [comment]
@piotrzarzycki21 now there is no any runtime error on Tomcat but there is no any trace of the include component on browser. I think its the expected behaviour. Please confirm.

**Comment by piotrzarzycki21** [comment]
Yes this is how I implemented it. Not sure if it's correct behavior. Let's see what happened.
