### ISSUE TITLE
Project returning to sidebar from the past

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#318]
We can say this `ghost from the past`. Steps to reproduce this:

- Create a new project to desktop "C:\Desktop\MyNewProject"
- Restart Moonshine, sidebar re-populates with the project opened
- Close Moonshine
- Navigate to desktop and either rename or move the project to somewhere else
- Restart Moonshine - sidebar do not populates with the project anymore nor thrown any error which looks fine
- Close Moonshine
- Restore the project name or return (if moved) to the same location again
- Starting Moonshine again re-populates with the project in sidebar

In above case, having the project re-populated again was unexpected. In my opinion, Moonshine was not suppose to re-populate the project again (from past) once it was disappeared. I was in impression that Moonshine sidebar cookies delete the project reference once not opened to the sidebar, for any reason; and rely on the last-most saved state.

**Comment by piotrzarzycki21** [comment]
I have pushed changes where files and projects are being removed from cookies if they doesn't exists.

**Comment by atinprominic** [comment]
As per me, the project bookmark in sidebar should not be removed even if the project has been removed/renamed/moved from OS filesystem level. Instead the bookmark should be having a red cross to indicate that the project files no longer exist on the file system and the user can right click on it to remove the bookmark or the user should be asked to delete bookmark if user tries to open the project using bookmark. This way the bookmarks will be consistent irrespective of the changes at file system level. To remove the project bookmarks from sidebar without asking the user will be a sort of inconsistency. Consider the scenario where the project files are moved/removed/renamed on the OS filesystem level out of accident. In that case the user might not be aware about it for longer time and it will come into his notice only when he needs to work on that project.

**Comment by piotrzarzycki21** [comment]
@atinprominic Agree with you. It's really good point. @rat-moonshine what do you think to have such enhancements ?

**Comment by rat-moonshine** [comment]
I wonder why I missed this discussion. I can't remember if I had any notification when the issue being closed as fixed.

I liked @atinprominic plan. This is closure to the ways how we used to see things in Eclipse, too. We probably want to track this as a separate issue, though; and probably this should be kept in low priority.

**Comment by piotrzarzycki21** [comment]
Issue has been raised.

**Comment by rat-moonshine** [comment]
The original issue I see still occurring during my Windows test. I'm reopening this to investigate.

**Comment by piotrzarzycki21** [comment]
I meant here that there is an issue raised where we won't remove items from sidebar at all - rather marking them as removed.

**Comment by rat-moonshine** [comment]
The proposed issue raised may take time. If you don't want to spend more time on this that is also fine. I just wanted to be make sure you know that the said issue is still exists and the applied fix is not working. Therefore, you can close the issue, Piotr.

**Comment by piotrzarzycki21** [comment]
I just tried scenario on my Win 10 and cannot reproduce the problem. I have close the Moonshine and renamed previously opened project. Once Launch it project wasn't on the list latest opened. Have you done anything different than in scenario ?

**Comment by piotrzarzycki21** [comment]
Btw. I did that test on fresh installed version of Moonshine.

**Comment by rat-moonshine** [comment]
Piotr, I didn't anything extra but the same steps with I reported. I renamed the project folder instead of moving/deleting.

I'm on Windows 7, but I'm not sure if that reason of our test result differences. I was testing with latest source from Git.

**Comment by piotrzarzycki21** [comment]
I'm really wondering whether it is some differences between Win 7 and Win 10, because everything is working on Win 10 and Mac.

**Comment by rat-moonshine** [comment]
I have recently fresh installed Windows 10 on my system. I can still reproduce the original reported steps in Moonshine.

We can move the fix requirement to trivial if you have better plan for future, though.

**Comment by rat-moonshine** [comment]
I able to create a screen recording for you. Incidentally, the recording also demonstrated the problem reported in #325 , please check.

![ref_318_recording](https://user-images.githubusercontent.com/24370870/42806876-06ece0ae-89cd-11e8-844e-eff0797567d1.gif)
