### ISSUE TITLE
IO/Error during project deletion [Windows]

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#319]
While testing #315 on Windows, I noticed a new error I haven't noticed before - Moonshine throws IO/Error while deleting a project:

```
Error #2044: Unhandled IOErrorEvent:. text=Error #2038: File I/O Error.
	at flash.filesystem::File$/getFile()
	at flash.filesystem::File$/get desktopDirectory()
	at actionScripts.impls::IFileBridgeImp()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\impls\IFileBridgeImp.as:57]
	at actionScripts.factory::FileLocation()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\factory\FileLocation.as:37]
	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/parse()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\plugins\as3project\importer\FlashDevelopImporter.as:53]
	at actionScripts.plugins.as3project::CreateProject/createFileSystemBeforeSave()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\plugins\as3project\CreateProject.as:822]
	at actionScripts.plugins.as3project::CreateProject/createSave()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\plugins\as3project\CreateProject.as:555]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at mx.core::UIComponent/dispatchEvent()[D:\flex_sdk\Sources\flex-sdk\frameworks\projects\framework\src\mx\core\UIComponent.as:13688]
	at Function/actionScripts.plugin.settings:SettingsView/actionScripts.ui:IContentWindow:save/actionScripts.plugin.settings:goSave()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\SettingsView.mxml:173]
	at actionScripts.plugin.settings::SettingsView/save()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\SettingsView.mxml:163]
	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\SettingsView.mxml:463]
```

I noticed [this](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/core/ProjectBridgeImplBase.as#L55) line throws error:

```
// when done check if the root folder is empty
// if it is, go delete it irrespective of 'isDeleteRoot' value
if (projectWrapper.file.fileBridge.getDirectoryListing().length == 0)
{
	projectWrapper.file.fileBridge.deleteDirectory(true); // <--------- root folder deletion
}
```

I'm not sure why it's suddenly starts giving this problem but commenting off the `deleteDirectory(true)` do not throws the problem anymore. 

I also noticed towards deleting the root directory (under `deleteDirectory(..)`), it fails to delete with `_file.deleteDirectory(true)`, and next with `_file.deleteDirectoryAsync(true)`. This looks like some permission issue suddenly shown up but I don't know why at this moment.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 , can you please give a try, if this valid in your case, too (?) Thanks!

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Yes I'm getting the same issue.

**Comment by piotrzarzycki21** [comment]
I think we should rewrite deleting of project to async completely. If you are looping through the files and deleting directories one by one, why not delete parent project directory ? 

If there is no exception from what files are deleted - we are deleting whole project - than there is not point looping.

**Comment by piotrzarzycki21** [comment]
We may suddenly have situation with that issue, where you are deleting files/directories one by one and once you are about to delete the root dir of the project - we have above issue.

**Comment by rat-moonshine** [comment]
> I think we should rewrite deleting of project to async completely. If you are looping through the files and deleting directories one by one, why not delete parent project directory ?
> 
> If there is no exception from what files are deleted - we are deleting whole project - than there is not point looping.

This is possible that in Windows the root project directory not released (for deletion) until its children being deleted; But I'm wondering why this is suddenly.

Regarding file/folder deletion logic, Moonshine deletes only first level of file/folders in a loop - that means it does not delete contents of those first level of folders' separately. To explain this more clearly, this following chart maybe help the situation:

File/Folder | Level | Used Method
---------- | -------- | --------------
bin-debug | root | File.deleteDirectory()
build | root | File.deleteDirectory()
obj | root | File.deleteDirectory()
src | root | File.deleteDirectory()
.as3proj | root | File.deleteFile()

After the above loop completion, if root directory found empty, then only we try to delete that directory; But I wonder why its certainly having a problem.

**Comment by piotrzarzycki21** [comment]
Yep, I saw that logic, but imagine that if one of those deletion didn't finished and we are trying to delete root ? That's possible yes ? That's why maybe all should be async and wait for each deletion.

**Comment by rat-moonshine** [comment]
Yes, that is what I'm fearing, too. I agree with your fear against this.

**Comment by rat-moonshine** [comment]
I made some changes to the selective file/folder delete loop. I made sure that next deletion occur after the earlier process completes. However, the given `Event.COMPLETE` event against `File.deleteDirectoryAsync(..)` seems not that dependable, yet. Being triggered by the event when all the selective file/folder in the row completes, I'm trying to reach to the root folder to delete if its empty.

But not sure why, it's still throwing with following process hold-up error:

[IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #3013: File or directory is in use." errorID=3013]

Strangely, even if I tried to delete the root folder after a few seconds' gap (that should be adequate to ensure the folder's fewer files/folders being deleted), I continue to get the above error. I tried to close the project's Java process manually by going into Task Manager (prior to delete), that turned to the `error/catch` blog at [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IFileBridgeImp.as#L260).

**Comment by piotrzarzycki21** [comment]
@rat-moonshine As I understand you didn't commit that changes yet ?

**Comment by piotrzarzycki21** [comment]
>  I made sure that next deletion occur after the earlier process completes.

How are you make sure about that ? Do you use to make sure Async methods from Adobe Air File API ?

**Comment by rat-moonshine** [comment]
I didn't commit because the codes were not working anyway as expected. Here's the current investigation state of the code, if you're interested:

```
private function deleteFilesAsync():void
		{
			if (filesToBeDeleted && filesToBeDeleted.length != 0)
			{
				var tmpWrapper:FileWrapper = filesToBeDeleted[0] as FileWrapper;
				tmpWrapper.file.fileBridge.getFile.addEventListener(Event.COMPLETE, onFileFolderDeleted);
				tmpWrapper.file.fileBridge.getFile.addEventListener(IOErrorEvent.IO_ERROR, onFileFolderDeletionError);
				tmpWrapper.file.fileBridge.getFile.addEventListener(SecurityErrorEvent.SECURITY_ERROR, onFileFolderDeletionError);
				
				if (tmpWrapper.file.fileBridge.isDirectory) tmpWrapper.file.fileBridge.deleteDirectoryAsync(true);
				else tmpWrapper.file.fileBridge.deleteFileAsync();
			}
			else
			{
				if (deletableProjectWrapper.file.fileBridge.getDirectoryListing().length == 0)
				{
					setTimeout(function():void{
						if (deletableProjectWrapper.file.fileBridge.exists)
						{
							deletableProjectWrapper.file.fileBridge.getFile.addEventListener(Event.COMPLETE, onFileFolderDeleted);
							deletableProjectWrapper.file.fileBridge.getFile.addEventListener(IOErrorEvent.IO_ERROR, onFileFolderDeletionError);
							deletableProjectWrapper.file.fileBridge.getFile.addEventListener(SecurityErrorEvent.SECURITY_ERROR, onFileFolderDeletionError);
							deletableProjectWrapper.file.fileBridge.deleteDirectoryAsync(false);
						}
						
					}, 1000);
					
					projectDeleteCompletionMethod(deletableProjectWrapper);
				}
				
				/*filesToBeDeleted = null;
				deletableProjectWrapper = null;
				projectDeleteCompletionMethod = null;*/
			}
		}
		
		private function onFileFolderDeleted(event:Event):void
		{
			onFileFolderDeletionError(event, false);
			filesToBeDeleted.shift();
			deleteFilesAsync();
		}
		
		private function onFileFolderDeletionError(event:Event, showError:Boolean=true):void
		{
			if (showError) Alert.show(event.toString());
			
			if (event)
			{
				event.target.removeEventListener(Event.COMPLETE, onFileFolderDeleted);
				event.target.removeEventListener(IOErrorEvent.IO_ERROR, onFileFolderDeletionError);
				event.target.removeEventListener(SecurityErrorEvent.SECURITY_ERROR, onFileFolderDeletionError);
			}
			else
			{
				filesToBeDeleted[0].file.fileBridge.getFile.addEventListener(Event.COMPLETE, onFileFolderDeleted);
				filesToBeDeleted[0].file.fileBridge.getFile.addEventListener(IOErrorEvent.IO_ERROR, onFileFolderDeletionError);
				filesToBeDeleted[0].file.fileBridge.getFile.addEventListener(SecurityErrorEvent.SECURITY_ERROR, onFileFolderDeletionError);
			}
		}
```

**Comment by piotrzarzycki21** [comment]
In above code you are trying to delete one item from filesToBeDeleted - Array - Am I understand correctly ?

**Comment by piotrzarzycki21** [comment]
Ahh sorry I haven't seen that one -> filesToBeDeleted.shift();

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Maybe try to recreate that scenario in a separate project, to see if it is some general problem.

**Comment by piotrzarzycki21** [comment]
I have spent some time and created simple application which deleting files Async inside some directory one by one. In general the same what we are trying to do in Moonshine. - There is no problem with deletion at all. We probably over complicated something, but not sure what. 

[FilesRemovingTest.zip](https://github.com/prominic/Moonshine-IDE/files/2162871/FilesRemovingTest.zip)

I can look into that deeper if you won't move forward with that. Let me know.

**Comment by rat-moonshine** [comment]
Thank you for taking some time out, and build a test project against this, Piotr. 

I gave some tests with the project in Moonshine, and following were my test results:

###Case A
1. Run FilesRemovingTest project
2. Point the file selection dialog to an existing project folder 
3. Upon selection, FilesRemovingTest removed everything successfully 

###Case B
1. Run FilesRemovingTest project
2. Open an existing project to Moonshine
3. Try to delete that existing project folder with FilesRemovingTest
4. It able to deletes all the containing files/sub-folders inside the existing project (as same behavior we've noticed in Moonshine), but thrown IO/Error when deleting the root folder

###Case C
1. Run Moonshine 
2. Open an existing project to Moonshine (do this first so we can be sure which Java instance running against this project in Task Manager)
3. Open Task Manager - at this point it has only Java instance running - close it forcefully
4. Run FilesRemovingTest 
5. Point the existing project to delete in next steps
6. Existing project folder deletes successfully along with its root folder

**Comment by piotrzarzycki21** [comment]
In the other words you have probably found what is the cause of the issue. Project is simply being held by language server - if I correctly understand yes ? Maybe we have to close first project and then delete it.

**Comment by rat-moonshine** [comment]
I think that would be a valid option to choose from - to close the project first. But I'm not sure how sooner the server close. If an immediate trigger of deletion after close event happens, it's possible that there will be a chance of above issue again. Probably listening to the language server's any CLOSED event will help to trigger the next deletion process.

Do you know if is there any such event dispatch by the language-server client codes?

The best I only found is [this](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/languageServer/LanguageClient.as#L183). But when it calls `_shutdownID = sendRequest(METHOD_SHUTDOWN, null)` it already removed its all listeners to practically know when the server closed completely.

**Comment by piotrzarzycki21** [comment]
There is a Wiki where Josh describing how to connect and use Language Server, maybe it will help [Connect to a custom language server](https://github.com/prominic/Moonshine-IDE/wiki/Connect-to-a-custom-language-server)

**Comment by rat-moonshine** [comment]
I'm unclear between why we want a custom language server and listening a CLOSED event from a closing `LanguageClient`/server. 

I think we probably need to listen for the CLOSE event fires [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/languageServer/LanguageClient.as#L501); This triggers after a few seconds (depending on how huge the project is) from [SHUTDOWN](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/languageServer/LanguageClient.as#L202) call.

**Comment by piotrzarzycki21** [comment]
Essentially this is exactly what you should do - listen to the Close event - Do you have access to the language server during deleting ? 

If I understand correctly the custom Language server probably is needed to support some day other languages than ActionScript. - This what Justin wanted it in the future.

**Comment by rat-moonshine** [comment]
I don't think projects has direct access to the `TypeAheadProcess` where `ActionScriptLanguageServerForProject` stores. 

Maybe `ActionScriptLanguageServerForProject` which listens to that CLOSE event, should also dispatch a global event to let others know that server has closed, at [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/languageServer/ActionScriptLanguageServerForProject.as#L304). The class file `ActionScriptLanguageServerForProject` seems creates against each project, so we can have reference of the project VO as well to ensure - against which project that event fired.

**Comment by piotrzarzycki21** [comment]
@joshtynjala do you have any suggestion to that ?

**Comment by joshtynjala** [comment]
Yes, I think that some kind of global event to indicate when the language server has fully shutdown for a project makes sense.

**Comment by joshtynjala** [comment]
I just thought of a possible reason why the language server might be keeping files open. I'll investigate after I return from vacation in one week.

**Comment by rat-moonshine** [comment]
This issue reported sounds similar to the above problem you've mentioned, though #322 . 

Also, please let me know if you have a plan to add a global event on server shutdown, or I should go ahead and add one, at [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/languageServer/ActionScriptLanguageServerForProject.as#L304).

**Comment by joshtynjala** [comment]
You can add it, if you'd like. Hopefully, if my intuition is correct about why the language server is keeping files open, it may not be needed for long.

**Comment by rat-moonshine** [comment]
That sounds great, Josh. 

Okay, I shall plan to add an event myself and therefore test the modified procedure for project deletion. Later, we can remove it when you feel right.

**Comment by rat-moonshine** [comment]
Listening to the language server's complete shutdown event worked like a charm. This didn't required to trigger close command additionally as delete command also include part of the close command. 

I also noticed that triggering the old synchronous deletion process after the server's complete shutdown event, also working. But let's keep the current asynchronous process, which is good.

**Comment by rat-moonshine** [comment]
I have noticed that actual delete process file count is not matching with the files/folders shown into this window:

![image](https://user-images.githubusercontent.com/24370870/42392407-5b35fd0e-8170-11e8-8d63-bda1c81635e9.png)

Thus, when checking if the root folder has 0 children, that condition always turning _false_. I have noticed this during a Flex Desktop project creation and deletion. 

I need to check why different number of items passing to the deletion process, starting from that above window.

**Comment by rat-moonshine** [comment]
@JoelProminic also reported that during a project deletion, the process also close other projects' any opening tab. This needs to be fixed.

**Comment by rat-moonshine** [comment]
- Not all the items were deleting during deletion process which have shown in project deletion popup - fixed
- Deletion of a project also closes other opened projects' tabs - fixed

I also noticed a situation. Since the project deletion process now depends upon call-back from the language-server to determine when the server completely shutdown - it needs the language server to run against a project. When language server not setup (ideally when a fresh install or removed all application data), the process failed at certain part. 

I've updated the process to check if language server is running or not, and therefore take action to continue the process. However, I don't know how to determine effectively if a language server is running against a project. (@joshtynjala can you suggest on this part?) At this moment, I'm only checking a global flag to determine if the language-server has started/present against any project - stopping Java instance manually from Task Manager won't help to update this flag, though.

Except the above, deletion process seems working good in my tests, on Windows 10.

**Comment by rat-moonshine** [comment]
I'm closing this as fixed. We can revisit this later, if necessary.
