### ISSUE TITLE
Editor Overlaps with Console Divider

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#32]
While testing today, I noticed this issue:
![2017_10_04__divider_display_issue](https://user-images.githubusercontent.com/24532731/31195930-818845a8-a911-11e7-8ec9-63c81b97fe87.jpg)

This only triggers when the window is maximized, and the opened file has enough lines that it can scroll down.

Some initial findings from @rat-moonshine

> 11:48:06 AM:  Looking through the base SDK divider class, it seems it has a default alpha of .75 
> 11:48:24 AM:  It has a style property to set the alpha, but its not affecting.  
> 11:48:48 AM:  That is the only API is exposed for me at this point.  
> 11:49:07 AM:  I don't see if any other quick workaround at this moment, unfortunately.  
> 11:50:00 AM:  Maybe some more investigation it may needed, its not changing at this moment.  
> 11:58:43 AM:  I'm still trying to understand the style behavior of this divider classes.  
> 12:02:45 PM:  Okay. This problem seems related with the editor's masking functionality.  
> 12:03:02 PM:  This is something that I probably mentioned few times in past, during different discussions. 
> 12:04:40 PM:  I'm not quite sure how this masking range helps the editor, but in past I've seen Dhwani/Kinjal changing this masking range when some text mask issue happened.  
> 12:05:00 PM:  Like when you scroll some block of texts do not shows properly in the editor. I think you remember such problem.  
> 12:07:13 PM:  But anyway, the divider should affect with the given alpha value... this is coming out a little weird to me why its happening, and how come this editor extends a few pixels more in height when the editor's height is 100% 
> 12:07:28 PM:  Is it because of the masking thing that it has (?) Not sure..  
> 12:24:55 PM:  I think we shall need to look into this masking this more closely sometime later.. or how it affects in the whole scenario, as its generating in a loop

**Comment by rat-moonshine** [comment]
I've removed the masking codes from the `TextEditor` class, and that seems fixed the https://github.com/prominic/Moonshine-IDE/issues/9 issue. I couldn't able to notice any new masking issue so far with my tests, but we should keep an eye open on this.

**Comment by rat-moonshine** [comment]
Its fixed now.
