### ISSUE TITLE
Hello everyone, the same project runs perfectly, after updating the Flex Installer 3.3.2 and upgrading the SDK to 4.16.1 Air 30

### ISSUE THREAD

**Issue by apintex** [prominic/Moonshine-IDE#327]
![captura de ecra 2018-07-17 as 10 26 13](https://user-images.githubusercontent.com/6188954/42808975-59c3217e-89ac-11e8-823f-8a87aad0d308.png)

**Comment by apintex** [comment]
Sorry this concerns to issue #303

**Comment by rat-moonshine** [comment]
Thank you for reporting this @apintex . Glad that the newer SDK worked for you. I don't think we have any immediate thought on the earlier SDK you were using, we're closing this issue for now. Please, feel free to open a new issue if any functional problem you'd face.
