### ISSUE TITLE
Add PanelGrid to visual editor as representation of simple HTML Table

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#329]
In order to represents some simple HTML Table we would like to add [PanelGrid](https://www.primefaces.org/showcase/ui/panel/panelGrid.xhtml) to Visual Editor. 

In order to mimic Table on the Flex sight we could use TLF Table. Unfortunately implementation of that component is not finished in 100%. The missing element is Table header. 

I would spent some time in order to figure out whether I will be able to add that feature to [TLF Framework](https://github.com/apache/flex-tlf/tree/develop). It is worth to mention that some initial work has been done there.

**Comment by rat-moonshine** [comment]
Being interested to know what is TLF Table, I found only this Git link - https://github.com/Harbs/TLF-Table-Work. Do you have any URL/example/screenshot handy to understand how close the existing implementation is to PanelGrid and what is missing (i.e. header) (?)

**Comment by piotrzarzycki21** [comment]
I can give you working example and you can have a look 
[TLFTableTest.zip](https://github.com/prominic/Moonshine-IDE/files/2213898/TLFTableTest.zip) - Shot me with your thoughts.

**Comment by piotrzarzycki21** [comment]
Some additional [notes](https://docs.google.com/document/d/1sT0IAiMfIOBVgmo8wwF6ZZviuNFcW2bUfQoj0zDmSog/) from Harbs.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Mentioned repository by you is outdated - everything what is inside was merged into Apache TLF repository and Apache Flex repository.

**Comment by piotrzarzycki21** [comment]
Let me know what do you think before I really jump into the code.

**Comment by rat-moonshine** [comment]
I have gone through both [PanelGrid](https://www.primefaces.org/showcase/ui/panel/panelGrid.xhtml) and the [notes](https://docs.google.com/document/d/1sT0IAiMfIOBVgmo8wwF6ZZviuNFcW2bUfQoj0zDmSog/) section to understand better what are the requirements and what are in offering. I also tried to explore what are the options do we have to mimic the behaviour of PanelGrid in Flex/ActionScript, other than TLFTable; followed by some of my thoughts.

If I'm not very wrong, three elements which are mainly essential to this implementation, to mimic PanelGrid in Flex:

1. Header
2. Row Span
3. Column Span

Beside above numbers, there is also optional elements like border, background color etc. 

I go through the TLFTable _notes_ documentation and my initial impression was this needs some tricky works. Although, the API already provides border, background color etc., a few things are not available which needs investigation and therefore implementation:

1. No header - you already mentioned about this
2. I see the notes also mentioned that row span is not possible
3. Is the following means (under Current Bugs section) that it needs static size values (?)

> If no size data is set, all the cells are rendered bunched on top of each other. There’s a couple of problems here: In the composeTableDataCellElement function in BaseCompose, the floowing line causes the new parcel to be removed:             if ( tableElement.totalRowDepth + rowElement.iMaxRowDepth > currParcel.bottom) 
> This causes each row to render in the previous row location. It should compare to newParcel.bottom instead. Additionally, the table column widths are not automatically calculated so all cells in a row are rendered in the same location. 

We probably can live with no.3 (above) but having row span and header mechanism may demand some and mostly tricky works.

I continued to explore if some more options are available to ActionScript, I mostly found AdvancedDataGrid and Grid.

While AdvancedDataGrid by look-n-feel probably most close-aid to the PanelGrid (and which is already implemented) but you probably do not want to returned to this very old mx implementation:
![image](https://user-images.githubusercontent.com/24370870/43060152-48b63ae0-8e6d-11e8-97cd-c28e1dede0cb.png)

Next thing which we probably have at this moment is Grid, which provides column and row span built-in, but I don't see it offers any column header solution, though; I think showing border around the column/rows is not very straight-forward either, except background colors:
![image](https://user-images.githubusercontent.com/24370870/43060231-a0d90c84-8e6d-11e8-8d9a-7450d929ee48.png)

There was some Flex [Spreadsheet](https://code.google.com/archive/p/flexspreadsheet/) source which manages col/row span but the source is not available anymore.

Having above findings, I do not have any strong opinion on these at this moment. Between TLFTable and Grid I see each of the component has something in strength and something in weakness. Being said that, the current state of TLFTable might be one of the choice to incorporate, but fixing header and row span might take time. If in practice, row span is not needed at all, then it'll limited to only header implementation.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Many Thanks for this review! I was going through the code of TLF Table and I think I will use Grid instead. It could be a lot of work to have properly working header implemented and column/row span. If at least column/row span would work there I could try to fight with implementation of TLF Header, but adjusting Grid to our need could be much easier. I will try to have some first results by Wednesday. 

I have found sources of Flex [Spreadsheet on GitHub](https://github.com/jigar6800/flexspreadsheet), but  I think we don't need so much sophisticated control. I'm not sure also where is the code of MecGrid in that sources.

**Comment by rat-moonshine** [comment]
Since the implementation is mainly for mockup usage purpose and no direct UI implementation to Moonshine, you might want to take a look to AdvanceDataGrid _if_ other would take longer time to finalize. But I should leave this on your best decision.

**Comment by piotrzarzycki21** [comment]
Yep, definitely. I will experiment with that options as well.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Above pictures are taken from [Flexicious DataGrid](http://blog.flexicious.com/post/Flex-DataGrid-RowSpan-ColSpan-and-Cell-Merge.aspx) ? - AdvancedDataGrid doesn't have default such options like row/column span. I think we should have it for future use.

**Comment by rat-moonshine** [comment]
Yes, but I think the source zip link is not working from the page. I didn't searched much, though.

**Comment by piotrzarzycki21** [comment]
Flexicious cost at minimum 400$, so it's probably not an option for us, although they have very good components, cause I have an opportunity to work with them. In the project where I'm working on we are not using DataGrid - I can of course check if our expectations will be higher and higher.

**Comment by rat-moonshine** [comment]
Ah, thank you for pointing me to this. I overlooked that the components are commercial. I agree that the purpose of which we're looking for this, and its price tag, makes the solution out of the box, in my opinion.

**Comment by JoelProminic** [comment]
I experimented briefly with PanelGrid on macOS and I noticed that the column titles were not saving:
1. Create a new XHTML file
2. Add a Panel Grid
3. Click on the "Title" row in Columns, and change the value to "Foo".  Hit Enter.   The column header updates properly
4. Save the XHTML file
5. Close and reopen the file.  The column header is reset to "Title"

The "Rows" list doesn't seem to do anything in the Header Rows/Columns section.   It looks like multiple header rows are suppored in PanelGrid, but I don't see how to use them in the current Visual Editor interface.

I'm not sure how we would use the Value property with a PanelGrid.  Do you have a use case in mind for this?

Otherwise, the UI and controls seem to work pretty well, so far.

**Comment by piotrzarzycki21** [comment]
Actually I'm aware of that. Yesterday I give @rat-moonshine tasks to add History management to PanelGrid - without that noatter what you are doing is not being noticed as changes. 

Make the same steps, but at the end try to add some button to the surface and than save everything. Probably title columns will be preserved. All of that is caused by missing history management there.

**Comment by rat-moonshine** [comment]
While testing by @JoelProminic 's steps, I also noticed column titles resets when deselect the `PanelGrid` and re-select. Looking into the codes, this doesn't seems related to history management requirement but following reasons:

1. While re-generating the properties editor panel, header information generates with [static](https://github.com/prominic/MockupVisualEditor/blob/master/src/view/primeFaces/forms/PanelGridForm.mxml#L265) value
2. I didn't seen `fromXML()` method reads column title in PanelGrid while opening the file to the editor

These problems can be address anyway, I'll fix these while working on history manager implement to the PanelGrid.

**Comment by piotrzarzycki21** [comment]
Partially probably it's true, but if you have clean component like PanelGrid which doesn't have at all history management, there is no way save any value which you have changed in property editor. Mechanism is not able to discover that you changed something, so do not allow for saving.  - Maybe that should be a BUG. Maybe we shouldn't restrict to such things.

One good example is right now ability to switch off width/height for Div - Checkboxes near width/height inputs. - Without adding history management to that checkboxes I won't be able to save changes.

**Comment by rat-moonshine** [comment]
Here are few questions for @piotrzarzycki21 :

1. What is the implementation of **Rows** list item (shown under 'Header Rows/Columns')
![image](https://user-images.githubusercontent.com/24370870/44204373-e9c14780-a16f-11e8-940e-d88793c9a013.png)
2. Where the 'Value' section needs to get affect in generated code? I don't see the value adding in the current generated codes, though
3. On a higher note, do we want to have something like this against PanelGrid columns as we have in DataTable in regards of 'Value' field?
![image](https://user-images.githubusercontent.com/24370870/44204440-2bea8900-a170-11e8-978d-38dc21e53f80.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine here is the answers:

Ad. 1
Header in PanelGrid is represented by class [HeaderGrid](https://github.com/prominic/MockupVisualEditor/blob/master/src/view/primeFaces/supportClasses/table/HeaderGrid.as). Currently I'm allowing to have one row in header, but it will be possible to have more rows - if such requirements comes. HeaderGrid is being created in [Table](https://github.com/prominic/MockupVisualEditor/blob/5208ead2e99b1b3dc9a9e84b029e3a281a89be7e/src/view/primeFaces/supportClasses/table/Table.as#L31) class which PanelGrid extend. 

If you add column in PanelGrid using property editor - I'm calling from HeaderGrid `addColumn ` method to have exactly the same amount of columns in the headers as it is in the body. 

Not sure what's more I can show, you. Shot me more specific question if it's not enough.

Ad. 2
I'm pretty sure it was working. It looks like this is a bug - I will try to fix that today.

Ad. 3 
I'm not fully familiar with how Java binding works, but I was thinking if I will provide following structure - it will be easier to generate data in Table. Will it be ? 

```
<p:panelGrid>
        <f:facet name="header">
          <p:row>
            <p:column>Title</p:column>
            <p:column>Title</p:column>
          </p:row>
        </f:facet>
        <p:row>
          <p:column>#{mypropertyname}</p:column>
          <p:column>#{mypropertyname}</p:column>
        </p:row>
        <p:row>
          <p:column>#{mypropertyname}</p:column>
          <p:column>#{mypropertyname}</p:column>
        </p:row>
</p:panelGrid>
```

**Comment by JoelProminic** [comment]
To facilitate discussion of the third point, here is a panelGrid example that we are using in the Grails PrimeFaces tests:

```
        <h:form id="authorForm">
        <p:dialog header="author Form" widgetVar="authorDialog" closable="false" resizable="false" modal="true" closeOnEscape="true" >
            <h:panelGrid columns="2" cellpadding="5">

                
                <h:outputLabel for="authorID" value="authorID" />
                <p:inputText id="authorID" value="#{authorMB.author.authorID}" label="authorID"/>

                <h:outputLabel for="penNames1" value="penNames1" />
                <p:inputText id="penNames1" value="#{authorMB.author.penNames1}" label="penNames1">
                    <f:converter converterId="vectorToStringConverter" /> 
                </p:inputText>
                
                <h:outputLabel for="dateOfBirth" value="dateOfBirth" /> 
                <p:calendar  id="dateOfBirth" value="#{authorMB.author.dateOfBirth}"  label="dateOfBirth" />

                <h:outputLabel for="nameFirst" value="nameFirst" />
                <p:inputText id="nameFirst" value="#{authorMB.author.nameFirst}" label="nameFirst"/>

                <h:outputLabel for="nameLast" value="nameLast" />
                <p:inputText id="nameLast" value="#{authorMB.author.nameLast}" label="nameLast"/>
                
                <f:facet name="footer">
                    <p:commandButton update=":authorsForm:authorsDT" value="#{message.i18n('default.save.button')}" action="#{authorMB.save}" ajax="false" icon="ui-icon-disk" />
                    <p:commandButton value="#{message.i18n('default.reset.button')}" actionListener="#{authorMB.reset}" ajax="false" icon="ui-icon-cancel" />
                </f:facet>
            </h:panelGrid>
        </p:dialog>
    </h:form>
```
The resulting form looks like this:
![image](https://user-images.githubusercontent.com/24532731/44222567-91c41a00-a14a-11e8-8ca1-71873514a1ad.png)

The expressions for data binding look like this:  #{authorMB.author.nameFirst}.  authorMB.author is the currently selected Author object.

@piotrzarzycki21, are you suggesting that we set Value to be "#{authorMB.author}" and then automatically use this as the base object for any expressions used in the children of the table?   This could be a nice convenience, but I am concerned that it would be confusing instead, especially for someone who is familiar with PrimeFaces and the expression language.

**Comment by piotrzarzycki21** [comment]
@JoelProminic yes that was my intention in case of Value. Is it satisfactory for now current generation from below? If someone generated below structure PanelGrid right now should work.

Option 1
<p:row>
          <p:column>Text</p:column>
          <p:column>Text</p:column>
</p:row>

I will definitely work on that more hopefully next week and make happen to have inside <p:column> some controls, since it not necessary  working by drag and drop. However I'm wondering what will happen if you put inside manually by editing Visual Editor XML following control?

<p:column><p:inputText id="nameFirst" value="#{authorMB.author.nameFirst}" label="nameFirst"/></p:column>

**Comment by rat-moonshine** [comment]
Two of the following problems were taken a large portion of my interests today - 

### Case A

1. PanelGrid selected on the stage
2. PanelGrid deselected on the stage - and reselect
3. Do any changes to its property editor
4. Initiate an Undo by pressing Ctrl+Z
5. null exception thrown by selectedItem in PanelGridForm

### Case B.1
1. Deletes any column in property editor of PanelGrid
2. Panel header title list do not updates

### Case B.2
1. Create a new column item in property editor of PanelGrid
2. Do an Undo
3. Panel header title list disappears 
4. Do a Redo - list appears again

All of the above issues now managed, thankfully.

Other things covered in today's commit:
1. Header title edit now saves to project XML upon saving
2. Header titles now loads from XML based on row/column formula

@JoelProminic and me noticed last night that either CMD+Z or Ctrl+Z wasn't working on macOS sandbox build. However, there were no changes from long time on this side, as far I know.

Today I created a sandbox build locally and ran, I confirm both CMD+Z and Ctrl+Z found working by the installation. I'm not sure what caused the problem last night downloaded from Bamboo; I confirm both Bamboo and my local build system uses same SDKs to build. I haven't tested with any newer build from Bamboo until now.

**Comment by rat-moonshine** [comment]
I don't have anything further to do with history management to PanelGrid, unless you pointed out if something missed out or broken. There could be minor code level changes, but that shouldn't affect main functionality of the current working, I hope.

If all looks well, you can proceed to work on this further, Piotr.

Thank you!

**Comment by piotrzarzycki21** [comment]
I have added drag and drop ability for PanelGrid. I think basic component is ready. Let's wait for tests results in connection with converter.
