### ISSUE TITLE
Debug > Stop Does Not Work

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#33]
I noticed that Debug > Stop does not work
1. Open a project in Moonshine
2. Debug > Build & Debug
3. Debug > Stop - BUG:  The application remains open and the debugging session doesn't close
4. Click the "Stop" button in the Debug panel - this works

I tested this with Mac OS 10.10.3 and both an AIR and SWF project.

**Comment by rat-moonshine** [comment]
Addition: Debug > Resume, Debug > Step Over - none are working.

**Comment by rat-moonshine** [comment]
Following menu options are now functional:
- Debug > Step Over
- Debug > Resume
- Debug > Stop
