### ISSUE TITLE
Cannot Configure XCode for Git on macOS.

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#335]
I tested on Git support (#295) on a different macOS workstation today, and I found that it did not work when I tried to use the Commmand Line Tools instead of XCode.

1. Install Command Line Tools and set as defauilt with xcode-select (see below)
2. Reset the Moonshine settings from Settings > General
3. Open a Git Project
4. Git > Status.  Moonshine prompts you to setup Git.  The path should be something like:  /Library/Developer/CommandLineTools
![image](https://user-images.githubusercontent.com/24532731/43424710-e692f264-9415-11e8-9344-7bbb94b13586.png)
5. Select the path in the file chooser, and submit the form
6. Git > Status.   BUG:  Status interface is blank.   Console shows the below error

![image](https://user-images.githubusercontent.com/24532731/43424725-f0760500-9415-11e8-9ac5-d6bb5c078c59.png)

    : /bin/bash: /Library/Developer/CommandLineTools/Contents/Developer/usr/bin/git: No such file or directory

For CommandLineTools, the correct path is:  /Library/Developer/CommandLineTools/usr/bin/git

However, I also got an error when I tried to switch back to an Xcode path:
1. Set an Xcode path with xcode-select.
2. Reset the Moonshine settings from Settings > General
3. Open a Git Project
4. Git > Status.  Moonshine prompts you to setup Git.  The path is:  /Applications/Xcode.app
![image](https://user-images.githubusercontent.com/24532731/43424669-bf39d82c-9415-11e8-9f01-4788ceb50f94.png)
5. Click "Allow Access".  BUG:  The "Open" button is not clickable.
![image](https://user-images.githubusercontent.com/24532731/43424686-caac039c-9415-11e8-9bb3-31ee2222a560.png)

If we use the full Xcode path here (i.e. /Applications/Xcode.app/Contents/Developer), this avoid this problem, and allow us to access Git from the relative path (<xcode-dir>/usr/bin/git).

We previously discussed xcode-select here:  https://github.com/prominic/Moonshine-IDE/issues/295#issuecomment-398133883

To test CommandLineTools, you can install CommandLineTools with these instructions, if you haven't already:  http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

And then reset the xcode path like this:

    # Show the current path - save this for later
    $ xcode-select -p
    /Applications/Xcode.app/Contents/Developer

    # Change the path
    sudo xcode-select -s /Library/Developer/CommandLineTools

**Comment by rat-moonshine** [comment]
> : /bin/bash: /Library/Developer/CommandLineTools/Contents/Developer/usr/bin/git: No such file or directory
> For CommandLineTools, the correct path is: /Library/Developer/CommandLineTools/usr/bin/git

Moonshine do not constructs the CommandLineTools path at all. It runs only following command to request possible path:

`xcode-select -p`

Since in my system XCode is installed it turns to the XCode provided git path instantly, I couldn't able to test with CommandLineTools. I shall give a test now with the `reset` commands you provides @JoelProminic .

I also fear now that if sandbox environment causing the CommandLineTools with additional "Contents/Developer" path.

**Comment by rat-moonshine** [comment]
### Todo: 

1. We need to get rid of the git permission prompt on Moonshine startup

### Bugs:

1. Git menus do not enables immediately (unless a restart) when used with CommandLineTools

**Comment by rat-moonshine** [comment]
@JoelProminic pointed following problem:

1. Clear Moonshine settings
2. Restart Moonshine
3. Git > Grant Permissions
4. Restart Moonshine
5. Git > Grant Permissions is still in the menu
6. Click Git  > Grant Permissions. This opens the Git > Clone action
