### ISSUE TITLE
Error # 3218 when doing copy/paste of code multiple times

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#339]
Hi,

While testing Moonshine version from the below URL, I found the error # 3218.

Test Steps:
1. On MS Windows, Opened the project named "GridContainerTest" as provided by @piotrzarzycki21 
2. Copied 4-5 lines of code of <mx:GridTest> and pasted multiple times.
3. While pasting the code, it started to throw the error in console as reported.

I tested the moonshine version downloaded from below URL:
https://1drv.ms/u/s!ApVpLyjpHDC2hZZvrmpAVob-sGVXtQ

Video Recording: 
**Part 1:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34882311/43703449-6fd809a6-997a-11e8-89ab-477cbb069cbf.gif)

**Part 2:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34882311/43724113-d9b07d86-99b6-11e8-8548-29af84b6f205.gif)

OS: Windows 7 64 Bit
Moonshine IDE: 1.15.0
SDK Version: Apache Flex 4.16.1 FP30.0 AIR30.0 en_US
Console Logs:
: Moonshine IDE 1.15.0
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 30.0.0.107
: Error #3218
:
: Click here to Report a Bug
: Error #3218
:

**Comment by atinprominic** [comment]
Hi

There are 2 parts of the video. 

I have just uploaded the Part 2.

Please check both.

Thanks
Atin

**Comment by piotrzarzycki21** [comment]
@joshtynjala I got that one testing it. Does it saying to you anything ? 

```
: Exception in thread "Thread-3" java.util.ConcurrentModificationException
: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
: 	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
: 	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:4751)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:4741)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didChangeWatchedFiles(ActionScriptTextDocumentService.java:1375)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService$3.run(ActionScriptTextDocumentService.java:1604)
```
Later I got that from Atin's description:

`: Error #3218: Error while writing data to NativeProcess.standardInput.`

**Comment by joshtynjala** [comment]
ConcurrentModificationException indicates a thread conflict. This should be resolved when we update the language server to v0.14.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I think you did update Moonshine to v0.14 - Can @atinprominic test it ?

**Comment by atinprominic** [comment]
@piotrzarzycki21 I am testing it Moonshine 1.15.1 from Bamboo and its throwing the same issue. 

I am following the same steps to reproduce the error.

If you need any further details please let me know

**Comment by piotrzarzycki21** [comment]
I think it's a bamboo problem. Can you confirm @rat-moonshine ?

**Comment by rat-moonshine** [comment]
I think nightly build versions will remain under 1.16.0, until we release 1.16.0 as a stable version.

**Comment by piotrzarzycki21** [comment]
I think it doesn't occurs anymore.
