### ISSUE TITLE
Interrupting an Existing Debugging Session

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#34]
I also noticed that Moonshine gave an error if I tried to start a new debugging session while the old session was still open
1. Start a session with Debug > Build & Debug
2. Try to start a new session with Debug > Build & Debug
3. The existing session closes, and the application closes (AIR only)
4. BUG:  Moonshine reports the error below.  The debugger does not start
5. Run Debug > Build & Debug again.  This time, the session opens properly.
![2017_10_04__debugger_session_error](https://user-images.githubusercontent.com/24532731/31196961-2c3b1e1e-a915-11e7-81f4-e1d002e8062d.jpg)

I tested this with Mac OS 10.10.3 and both an AIR and SWF project.

I suggest we make Moonshine show a dialog like this:

> You are already debugging an application. Do you wish to terminate the existing debugging session and start a new session?
Options:  Yes, Cancel

So, the process would look like this:
1. Start a session with Debug > Build & Debug
2. Try to start a new session with Debug > Build & Debug
3. Show the dialog described above.  Preferably, this should happen before Moonshine builds the application.
4. If the user clicks Yes, then close the old session and start a new session.  If the user clicks Cancel, then keep the existing session open

**Comment by rat-moonshine** [comment]
Alert added against re-debugging request (when a debug session is already active). User can choose to terminate the running session and start a new one.
