### ISSUE TITLE
Primefaces: The type of UI component should be specified in Properties box

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#340]
Currently when we select any UI component its properties are shown in the right bar. 

It would be convenient if the name of selected component type is also listed there in properties box.

**Comment by rat-moonshine** [comment]
Header added, please check.

**Comment by JoelProminic** [comment]
The header looks like this:
![image](https://user-images.githubusercontent.com/24532731/43910289-0422b05e-9bc2-11e8-98b8-f3d9a9a21b30.png)

I see that a header is visible for each of the components.

**Comment by atinprominic** [comment]
Its working as expected.
