### ISSUE TITLE
Project with Existing Source dialog do not list sub-folders under 'Main source folder'

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#342]
_[Tested with Windows build 1.14.0]_

1. Create a folder named **MyNewProject** on desktop
2. Create a sub-folder inside the newly created folder named 'src'
3. Try to open MyNewProject with **Open Apache Flex/Royale Project..** option in Moonshine
4. In opening alert choose 'Yes'
5. **Existing Project Directory** field will show `C:\Users\user\Desktop\MyNewProject` which is right
6. Click on the 'Browse dir' button against **Main source folder** field
7. This will open a dialog listing sub-folders under `MyNewProject` - [Bug] no sub-folders are listed
8. Project do not creates

**Comment by rat-moonshine** [comment]
[BUG] In latest source, **Existing Project Directory** is also populating wrong.

**Comment by rat-moonshine** [comment]
Both of the above issues are now resolved.

**Comment by rat-moonshine** [comment]
Yes, @atinprominic can you please give this a try (?)

Thanks!

**Comment by atinprominic** [comment]
Hi @rat-moonshine 

Yes, this is fixed. But while testing I found another error#1009 which I reported in a separate issue.


Thanks
Atin

**Comment by rat-moonshine** [comment]
Thank you Atin, I'm closing this issue for now.
