### ISSUE TITLE
Properties Panel being distorted

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#344]
OS: MAC
![screen shot 2018-08-08 at 1 49 02 pm](https://user-images.githubusercontent.com/34882311/43825472-778f8f68-9b12-11e8-90d1-8d110775b37b.png)

When we resize the console pane, the properties panel of DataTables is distorted.

See attached screenshot.

**Comment by piotrzarzycki21** [comment]
It should work now.
