### ISSUE TITLE
Should prompt before removing TABs in TabView

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#346]
OS: MAC

While removing TABs from the TABView using the properties panel, it removes the TAB without any confirmation. 

There are many cases where there are controls inside the TAB being removed.

If there are controls inside the TAB being removed, it should ask before deleting the TAB for confirmation as a warning that all the UI controls inside the TAB will be removed.

**Comment by rat-moonshine** [comment]
In my opinion, while in the design view you edit something - everything is volatile. I don't think any other UI builder view prompts against removing any column/tab/components while in-designing. 

As an workaround, a history Undo can be done in this case (CMD+Z) preferably.

**Comment by piotrzarzycki21** [comment]
Agree with @rat-moonshine - I don't want to be distracted in case when I need to remove something. CMD + Z should do the job, if it's not working as it is we should fix it.
