### ISSUE TITLE
Null Pointer Exception during open project with source

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#348]
OS: Windows 7

Moonshine Build # 337

Error Log:
: Moonshine IDE 1.14.0
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 30.0.0.107
: Error #1009
: TypeError: Error #1009
: at MethodInfo-25593()
: at Array/http://adobe.com/AS3/2006/builtin::some()
: at actionScripts.ui.renderers::FTETreeItemRenderer/populateTemplatingMenu()
: at flash.display::NativeMenu/display()
: at flash.ui::ContextMenu/display()
: at flash.display::InteractiveObject/onContextMenuEvent()
:
: Click here to Report a Bug
![43824759-81ac258a-9b10-11e8-9ea7-0be7ebb87a2f](https://user-images.githubusercontent.com/34882311/43826483-0adaa13e-9b15-11e8-9d2d-5cf5b9441b5e.gif)

**Comment by rat-moonshine** [comment]
Thank you for taking time to record and report this @atinprominic ; I did seen this error at some time but distracted by other todos.

**Comment by rat-moonshine** [comment]
I couldn't able to reproduce the null pointer exception while creating a project with existing source code with the latest version from Bamboo. Following ismy test matrix:

SDK & language-server Present | Action | Results
------------------- | ------------------------| -------------------
Yes | Created project with existing source along with the steps shown in recording | No error
Reset everything to default from Moonshine Settings | Same as above | No error
Deleted com.moonshine-ide folder from c:\Users\user\AppData\Roaming folder | In restarted Moonshine taken steps same as above | No error

@atinprominic can you please test if the reported error is still valid with latest build at Bamboo (?)

Thanks!

**Comment by atinprominic** [comment]
@rat-moonshine I tested it and the issue is no longer there. As per my testing its now resolved.

**Comment by rat-moonshine** [comment]
Thank you for confirming this, @atinprominic . I'm closing the issue, please reopen if problem found again.
