### ISSUE TITLE
Visual Editor 'Code' pane search broken

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#349]
- Open a Visual Editor Primefaces project to Moonshine
- Change to 'Code' pane
- Try search something by pressing Ctrl+F (Windows)
- Moonshine throws exception:

```
: Error #1009
: TypeError: Error #1009
: 	at actionScripts.ui.editor.text::TextEditor/search()
: 	at actionScripts.ui.editor::BasicTextEditor/search()
: 	at actionScripts.plugin.findreplace::FindReplacePlugin/dialogSearch()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at actionScripts.plugin.findreplace.view::SearchView/find()
: 	at actionScripts.plugin.findreplace.view::SearchView/__findButton_click()
:
: Click here to Report a Bug
```

**Comment by rat-moonshine** [comment]
`SearchManager` now relieved from not initiating in case of Visual Editor projects.

**Comment by JoelProminic** [comment]
Note that this bug is associated with Edit > Find rather than Project > Search.

Edit > Find is disabled for the Code tab on both macOS and Windows.

CMD-F does not work on macOS, but CTRL-F does work.

**Comment by rat-moonshine** [comment]
I see the problem is much more fundamental but limited to search. The problem is even tricky, too.

I see menus those have shortcut-keys and disabled - can also triggered irrespective of the active project's type, i.e. one can trigger "Build & Run" (Ctrl+B) to a Visual Editor project. 

Upon investigation I found, despite of each menu has their enables types against project types - shortcut events do not filters through against active project's enable types. There are other test cases, too. I think we need to track this problem with a separate [issue](https://github.com/prominic/Moonshine-IDE/issues/368).

Regarding `Edit > Find` in Visual Editor project, I choose to disable the menu option as finding through the search dialog when staying on the "Design" pane doesn't make sense. User can use `Project > Search` to find string values anyway. So I'm closing this issue. @JoelProminic , please open this if you think otherwise.
