### ISSUE TITLE
Issues related to Include component

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#351]
[_Tested with Moonshine 1.14.0 Windows_]

The current usage of `Include` component in Visual Editor works a little strangely for me. Following are test results, and thoughts. 

- Create a new Visual Editor project
- At this stage we have only `xhtml` file "NewVisualEditorProject.xhtml"
- Drag an `Include` component to the stage
- This is little strange to understand why its dropdown do not populates with any value until Piotr pointed that you requires more files in the project; In a way this sounds right, because same file holds the `Include` component can not re-load _self_ in that component
- Moving to the 'Code' pane I see no codes generated against the `Include` component - this felt not visually and physically right to me; As I'm seeing a physical placeholder placed in the 'Visual' stage against the `Include` component, 'Code' was suppose to populate minimal codes pointing to the space holds by it - which is not happening at this time

The above issue is more for brainstorming, I expressed my opinion, others' opinions also does matter. 

I moved forward with further tests:

- Created a new `xhtml` file "ABCD.xhtml" in the same project
- Returning to the _NewVisualEditorProject.xhtml_ tab, I see the file dropdown generated against the `Include` component this time
- The only file generated to the component is _NewVisualEditorProject.xhtml_ [Bug]
- 'Code' pane now generated with codes against the `Include` component, but pointing the _NewVisualEditorProject.xhtml_ file [Bug]
- Restarting Moonshine now shows _ABCD.xhtml_ only to the file dropdown on `Include`

**Comment by rat-moonshine** [comment]
> In case of above, if you generate empty Include, you will get exception after export to PrimeFaces project

I assume that is the reason. My point was, this do not sync between code and visual stage. 

Can we add a comment tag into the code where it was suppose to get added, mentioning the reason why the `Include` component not generates, to make things more clear (?)

**Comment by piotrzarzycki21** [comment]
Hmm..Interesting, how to add comments using XML class ? :) - Adding comments can be solution.

**Comment by rat-moonshine** [comment]
> how to add comments using XML class

Talking on how to insert a comment to generated XML, you can to your XML in [this](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/exporter/FlashDevelopExporter.as#L71) way.

**Comment by rat-moonshine** [comment]
I have discussed on first part of this issue to @JoelProminic ; When he's more on to showing some error message (or error tooltip) in property editor to clearly mention that a non-selection of file to `Include` component shall not generate requisite codes, he's also think adding a comment section to the generated code explaining why no content generated on a secondary measure.

As this part can wait until any final decision, the second part (bug) needs a fix soon. @piotrzarzycki21 do you want me to look into the 2nd part to see what have changes?

**Comment by piotrzarzycki21** [comment]
Yes please proceed!

**Comment by rat-moonshine** [comment]
Can you precisely tell me what part have you changed to restrict the files to Include dropdown, @piotrzarzycki21 ?

**Comment by rat-moonshine** [comment]
The second part of this issue - file list generation bug, should have fix now.

@atinprominic , you can test the bug fix part as well.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Sorry for the delay, it seems that you figure out what is all about. I just did quick test and it seems to be working. However let Atin make final review.

**Comment by JoelProminic** [comment]
I noticed that the file list for the Include component was populated from the first project visual editor project where I opened an Include component during a Moonshine session:

1. Open a project with additional xhtml files
2. Add an Include component to a Visual Editor mockup.  The options are populated properly.
3. Open a project with no additional XHTML files
4. Add an Include component to a Visual Editor mockup
5. BUG:  The combobox shows the same list of files from the other project  

I also tried it the other way around:

1. Open a project with no additional XHTML files
2. Add an Include component to a Visual Editor mockup.  The combobox is blank
3. Open a project with additional xhtml files
4. Add an Include component to a Visual Editor mockup.  
5. BUG:  the combobox shows only the single XHTML file from the first project

**Comment by JoelProminic** [comment]
I also noticed a problem with the combobox with more than one option:
1. Set up a project with at least 3 XHTML files
2. Open one of the XHTML files
3. Add an Include component.  Note the default file
4. Switch to the code view.  The correct file is displayed: 
5. Switch back to the Visual view, and change the selected file to another file
6. Switch back to the Code view.  The correct file is displayed
7. Switch back to the Visual view.   BUG:  The combobox shows the default file.  The Include component shows the correct file in its label:
![image](https://user-images.githubusercontent.com/24532731/44356526-39a45500-a475-11e8-8a5d-c6aef9073c3b.png)

**Comment by rat-moonshine** [comment]
Both of the two above reported issues now handled. But I'm looking for more bugs, if found. Please, report.

**Comment by atinprominic** [comment]
@rat-moonshine I tested it and not found any issue.

**Comment by rat-moonshine** [comment]
Comment XML now generates to _Code_ section when an _Include_ component do not have any target defined.

I also noticed one problem during my tests today towards proper file liste generation to _Include_. This was happening time to time when tab ordering and editor creation completion event out of sync. 

- Open multiple visual editor projects and their files opened at a time
- Make sure some files from both the projects are in viewable tabs - not inside hamburger menu
- Make sure each project has more than one editor files
- Restart Moonshine
- Without toggling to any tab - sometime - when tab ordering and editors' creation complete event out of sync - adding an _Include_ component to last displaying project's editor populates files list to dropdown from the other project's list

The above problem come out a bit tricky; this is handled anyway. 

Please, report if any related issue come up again in yours tests.

**Comment by piotrzarzycki21** [comment]
If there is no more work here, please close it.

**Comment by rat-moonshine** [comment]
Yes, I think we can close it for now.
