### ISSUE TITLE
Undo/Redo Does Not Work with Multiple Visual Editor Tabs

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#353]
After retesting the macOS Undo/Redo errors I mentioned yesterday, I found that CMD-Z only works on the first Visual Editor tab I have open.
1. Open Moonshine
2. Close all tabs
3. Open a Visual Editor tab
4. Add a Button
5. CMD-Z - the button is removed
6. Open a different Visual Editor tab
7. Add a Button
8. CMD-Z - BUG: nothing happens

**Comment by rat-moonshine** [comment]
This issue now also addressed. @atinprominic you can give a test to this, too.

**Comment by piotrzarzycki21** [comment]
If it's addressed please close it. We will reopen if needed.

**Comment by JoelProminic** [comment]
This behavior is still triggering for me on today's Bamboo build.

**Comment by rat-moonshine** [comment]
I noticed the problem triggers for me when editors between multiple projects are opened and some editors are hidden to hamburger menu; However, testing between non-hidden editors and from same project didn't trigger me the issue.

I have added requisite changes, please have a look, @JoelProminic .

**Comment by JoelProminic** [comment]
I noticed that I got errors with undo/redo after closing a visual editor tab

1. Close all tabs and restart Moonshine
2. Open an xhtml file
3. Add a component
4. Undo the change.  This works
5. Close the tab without saving
6. Open the same file again
7. Add a component
8. Undo the change.  BUG:  this throws the error below

    : TypeError: Error #1009
    : 	at actionScripts.plugins.ui.editor.text::UndoManagerVisualEditor/markEventAsPending()
    : 	at actionScripts.plugins.ui.editor.text::UndoManagerVisualEditor/handleKeyDown()
    :
    : Click here to Report a Bug

**Comment by rat-moonshine** [comment]
Measure taken against above problem. Please, check.

**Comment by rat-moonshine** [comment]
I'm closing this as fixed. Re-open if related problem found again.

**Comment by atinprominic** [comment]
I tested both the scenarios and its working good in both cases below.

https://github.com/prominic/Moonshine-IDE/issues/353#issue-351648919
https://github.com/prominic/Moonshine-IDE/issues/353#issuecomment-414747347
