### ISSUE TITLE
TabView doesn't work correctly when height is dynamic

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#354]
When `height` and `percentHeight` is set to `NaN` for TabView component - main container always have height 0.

**Comment by piotrzarzycki21** [comment]
It looks like I was able to fix that. @atinprominic Can you test and provide feedback in following cases:
- Switch off height for TabView in property editor
- Add some components to TabView with height, restart project and obeserve whether TabView take height of children inside Tab

Do other test which come up to your mind.

**Comment by piotrzarzycki21** [comment]
Thanks @atinprominic I will look into that.

**Comment by piotrzarzycki21** [comment]
@atinprominic Issue has been resolved. You can test it, but remember to have unselected width/height for TabView to make it working.

**Comment by atinprominic** [comment]
I tested and its working good now
