### ISSUE TITLE
Exported PrimeFaces Visual Editor project to Grails PrimeFaces doesn't work correctly due to missing moonshine-layout-styles.css

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#355]
When we export project to Grails PrimeFaces because moonshine-layout-styles.css is copied to incorrect folder. After copying operation in html file w have 

`<link rel="stylesheet" type="text/css" href="resources/moonshine-layout-styles.css"/>`

Correct path should be:

`<link rel="stylesheet" type="text/css" href="/assets/moonshine-layout-styles.css"/>`

**Comment by piotrzarzycki21** [comment]
This should be discussed with @JoelProminic , because I have implemented that moonshine-layout-styles.css is being copied to that location [grails-app/assets/stylesheets](https://github.com/prominic/grails3-primefaces-demo/tree/master/grails-app/assets/stylesheets), based on the [demo](https://github.com/prominic/grails3-primefaces-demo) which we have.

**Comment by JoelProminic** [comment]
I confirmed that moonshine-layout-styles.css is being copied to grails-app/assets/stylesheets when exporting to a Grails project, but not when exporting to a blank project.  Is this copy based on the existance of grails-app/assets/stylesheets?

The issue I reported while testing the Visual Editor exports was that the stylesheet link was always defined like this, which does not work on Grails:

```
    <link rel="stylesheet" type="text/css" href="resources/moonshine-layout-styles.css"/>
```

I was able to resolve this issue in my test by changing the link to:
```
    <link rel="stylesheet" type="text/css" href="/assets/moonshine-layout-styles.css"/>
```

Note that I added a leading slash here, since in Grails PrimeFaces, the PrimeFaces pages are all located underneath /faces:

    /faces/index.xhtml
    /assets/moonshine-layout-styles.css

As I was playing with this today, though, I realized that this new link won't work when I compile the Grails application as a WAR and upload it to a development Payara server.  In this case the paths are something like:

    /grailsfish-0.1/faces/index.xhtml
    /grailsfish-0.1/assets/moonshine-layout-styles.css

I can resolve this with a relative link like this:
```
    <link rel="stylesheet" type="text/css" href="../assets/moonshine-layout-styles.css"/>
```

However the relative path is dependent on the nesting of the XHTML file.  This affects both the Grails and Maven builds.   For example, if I defined a Visual Editor project and created an XHTML file at test/Test.xhtml:

    // Maven + Tomcat
    .../index.xhtml
    .../test/Test.xhtml
    .../resources/moonshine-layout-styles.css

    // Grails
    .../faces/index.xhtml (Grails)
    .../faces/test/Test.xhtml (Grails)
    .../assets/moonshine-layout-styles.css

The links would need to look like this:
```
    <!-- Maven + Tomcat -->
    <link rel="stylesheet" type="text/css" href="../resources/moonshine-layout-styles.css"/>

    <!-- Grails -->
    <link rel="stylesheet" type="text/css" href="../../assets/moonshine-layout-styles.css"/>
```


So, I think Visual Editor will need to adjust these paths for the XHTML files in subdirectories automatically.

As for the Grails differences, if we are already detecting if the target project is a Grails project, we could change the <link> for each XHTML page to use the Grails path during export.

I'm open to other possibilities if you have a good way to work with the relative/absolute links.  I think my proposed solution above should work, but I'm not sure if it is a "best practice".

**Comment by piotrzarzycki21** [comment]
> I confirmed that moonshine-layout-styles.css is being copied to grails-app/assets/stylesheets when exporting to a Grails project, but not when exporting to a blank project. Is this copy based on the existance of grails-app/assets/stylesheets?

@JoelProminic Yes it is based on existence `grails-app/assets/stylesheets` folder. I'm not copying to a blank project because it doesn't make sens in my opinion in that case. Blank project can be setup in some IDEs or build by Maven.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine We don't have some general rules in case of detecting whether something is grails or not and I believe we shouldn't have. The only difference between Maven and Grails project is that css files should landed in different place. 

In order to export to Grails project you need to select that project is being exported to existing one. Next I'm checking whether folder `grails-app/assets/stylesheets` [exists](https://github.com/prominic/Moonshine-IDE/blob/f7a46557eba169fcbbf7dc318a20fced75ddeb97/ide/MoonshineSharedCore/src/visualEditor/plugin/ExportToPrimeFacesPlugin.as#L329). 

In my opinion first part of the changes should be that in this place we need to check whether `grails-app/assets` exists - that's all.

The second part of the changes should have place during Visual Editor File creation. I think we can have two links in each created file without thinking whether it is project for Maven or Grails export.

For the main file we should add in [following place](https://github.com/prominic/Moonshine-IDE/blob/f7a46557eba169fcbbf7dc318a20fced75ddeb97/ide/MoonshineSharedCore/src/elements/templates/projects/Visual%20Editor%20Project/src_primeface/main/webapp/%24ProjectName.xhtml.template#L9) two lines:

`<link rel="stylesheet" type="text/css" href="resources/moonshine-layout-styles.css"></link>`
`<link rel="stylesheet" type="text/css" href="/assets/moonshine-layout-styles.css"></link>`

This will work for main file, but in the second step we should take care of nested files etc. In [this place](https://github.com/prominic/MockupVisualEditor/blob/16107c0df02586108db9341b72a540c462fe0149/src/utils/MainApplicationCodeUtils.as#L102) we have to get information in which location our file is being created and add appropriate path.

This one:
`../assets/moonshine-layout-styles.css`
or this one:
`../../assets/moonshine-layout-styles.css`

**Comment by rat-moonshine** [comment]
If we want to add following two styles references irrespective of the project is for Maven or Grails:

```
<link rel="stylesheet" type="text/css" href="resources/moonshine-layout-styles.css"></link>
<link rel="stylesheet" type="text/css" href="/assets/moonshine-layout-styles.css"></link>
```

..do we have a need to test if the `grails-app/assets` folder exists (as first part of the change you suggested, @piotrzarzycki21 ) at all? I see you already have a file existence test for `grails-app/assets/stylesheets` at [here](https://github.com/prominic/Moonshine-IDE/blob/f7a46557eba169fcbbf7dc318a20fced75ddeb97/ide/MoonshineSharedCore/src/visualEditor/plugin/ExportToPrimeFacesPlugin.as#L329).

**Comment by rat-moonshine** [comment]
@JoelProminic helped me through a long walkthrough to help me setup Gradle/Grails and run the demo Grails project to my system and understand how the folder structure works within a Grails application/server, how we can export Visual Editor projects and the necessities with the stylesheet path changes. Can't thank him much )

@piotrzarzycki21 , you can always jump into the issue if you have some plan and want to manage this by that way; Else, I can offer my effort to find a way. At least, I'm clear now how the application structure and what needs to be done; many thanks to Joel.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Let me jump into that issue today and see whether my plan to fix that will work ok ?

**Comment by piotrzarzycki21** [comment]
The task is a bit more difficult then I thought. In order to be able to generate path to assets in following manner:

../assets or ../../assets depends where we currently are I will have to give to the Visual Editor a bit more information from outside. 

1) Current file which is being opened 
2) Source folder path

Than maybe I will be able to get that relative path by `getRelativePath ` from `File ` class.

**Comment by rat-moonshine** [comment]
You can create a new GET method in bridge class `MoonshineBridgeUtils` to get the active `AS3ProjectVO` (or folder path only) to get the root path level information and then-after use `getRelativePath` against available xhtml files' to generate their relative paths.

**Comment by rat-moonshine** [comment]
On a side note, you probably also update to any available .xhtml file upon exporting project, or when you call [this](https://github.com/prominic/MockupVisualEditor/blob/16107c0df02586108db9341b72a540c462fe0149/src/utils/MainApplicationCodeUtils.as#L102) class. At this moment I noticed the method calls only once - we need to make the update process to each xhtml file exists.

**Comment by piotrzarzycki21** [comment]
It's being updated whenever you go to the Code tab.

**Comment by rat-moonshine** [comment]
Right. But this is suppose to get called against every xhtml file exists - isn't it? At this moment, if I have multiple xhtml files in a project, and I do an export, the method calls only once. Or, am I thinking it otherwise (?)

**Comment by piotrzarzycki21** [comment]
It will be handled during file creation, once file will be created I will update what is needed.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I did changes which generates path to `moonshine-layout-styles.css`. However I have problem with testing that using `grails3-primefaces-demo`. Please test it on your sight and try `grails3-primefaces-demo` as well. 

I'm not sure whether project which you currently have will work. Try to create new one or change something in file - it will overwrite edited file with new paths to `moonshine-layout-styles.css`.

**Comment by JoelProminic** [comment]
I tested exporting a PrimeFaces Visual Editor project to a fresh Grails application.  The <link> lines looked like this:

    <link rel="stylesheet" type="text/css" href="resources/moonshine-layout-styles.css"/>
    <link rel="stylesheet" type="text/css" href="../../../../assets/moonshine-layout-styles.css"/>

The second line has too many parent references, so it did not work.  I updated this to:

    <link rel="stylesheet" type="text/css" href="../assets/moonshine-layout-styles.css"/>

In addition, moonshine-layout-styles.css was copied to grails-app/assets/ rather than grails-app/assets/stylesheets as expected.  Note that "stylesheet/" directory is not referenced in the <link> - this is unintuitive, but it is the expected Grails behavior.

If I add a nested mockup (test/TestNested.xhtml), then the links look like this:

    <link rel="stylesheet" type="text/css" href="resources/moonshine-layout-styles.css"/>
    <link rel="stylesheet" type="text/css" href="../../../../../assets/moonshine-layout-styles.css"/>

The nesting was updated for the second link, but the original path was wrong.   Also, the first linkll is not correct, because it did not account for the path change in the URL.  The correct links are:

    <link rel="stylesheet" type="text/css" href="../resources/moonshine-layout-styles.css"/>
    <link rel="stylesheet" type="text/css" href="../../assets/moonshine-layout-styles.css"/>

**Comment by JoelProminic** [comment]
What problem are you having with the grails3-primefaces-demo project?   The Grails project works really well for testing once it is setup, so let me know if you are having any trouble with Grails.

**Comment by piotrzarzycki21** [comment]
@JoelProminic On my end [grails3-primefaces-demo](https://github.com/prominic/grails3-primefaces-demo) is working fine. Current path to moonshine-layout-styles.css are also working for me -> `../../../../../assets/moonshine-layout-styles.css`. 

Here is my steps, grails3-primefaces-demo displaying following file once it's started -> [home.xhtml](https://github.com/prominic/grails3-primefaces-demo/blob/master/src/main/webapp/anagraphic/home.xhtml).
1. I have created VE project and folder "anagraphic" and file home.xhtml inside folder - to reflect demo structures.
2. I have exported project pointing [root folder](https://github.com/prominic/grails3-primefaces-demo) of the demo 
3. File home.xhtml has been replaced by mine from project
4. I run application by `grailsw run-app` and everything was working fine 

The question is - What is your folder structure ? What is different in your project in connection to demo?

**Comment by piotrzarzycki21** [comment]
If after export those paths are actually changing, how I can calculate it ? Right now I'm base my calculation on structures which is in the project. 

Here is the algorithm:
1) I'm taking path to the project folder Ex: `D:\Work\projects\VEGridTest`
2) Taking path to current file `D:\Work\projects\VEGridTest\src\main\webapp\anagraphic\home.xhtml`
3) I'm making `currentFile.getRelativePath(projectFolder)` -> [getRelativePath](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filesystem/File.html#getRelativePath())

**Comment by rat-moonshine** [comment]
Based on my earlier discussion on Grails3 URL structure, we need to calculate the dotted relative path based on URL system rather than physical system. 

So, as Joel mentioned this earlier (in this thread), the expected path structure should be like this:

> The links would need to look like this:
> > 
> >     <link rel="stylesheet" type="text/css" href="../resources/moonshine-layout-styles.css"/>
> > 
> >     
> >     <link rel="stylesheet" type="text/css" href="../../assets/moonshine-layout-styles.css"/>

Joel confirmed that we can't browse directories through browser in Grails server - but we need to know the convention where 'assets' folder is suppose to exit. 

One "../assets" is fine for root level xhtml file. The number of "../" shall get added based on sub-folder numbers. Based on that convention the path system will look like this:

```
File: http://localhost:8080/faces/index.xhtml
Link: <link rel="stylesheet" type="text/css" href="../assets/moonshine-layout-styles.css"/>

File: http://localhost:8080/faces/test/test/index.xhtml
Link: <link rel="stylesheet" type="text/css" href="../../../assets/moonshine-layout-styles.css"/>
```

So based upon that one "../assets" for root-level xhtml file, do you think you can calculate between project's folder location relative path dotted numbers and requisite URL level path, @piotrzarzycki21 ?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine what is 
> based on URL system rather than physical system. 
?

> Or, even just starts adding one more "../" to sub-folder items and see how it works.
Do you mean hard code something ?

**Comment by piotrzarzycki21** [comment]
@JoelProminic I just pushed some fix. Take a look if it's working now.

**Comment by JoelProminic** [comment]
After today's update, the links for index.xhtml look like I expect:
```
    <link rel="stylesheet" type="text/css" href="resources/moonshine-layout-styles.css"/>
    <link rel="stylesheet" type="text/css" href="../assets/moonshine-layout-styles.css"/>
```

For an xhtml file with nesting (i.e. test/TestNesting.xhtml), the assets link looks correct, but the resources link is not updated:

```
    <link rel="stylesheet" type="text/css" href="resources/moonshine-layout-styles.css"/>
    <link rel="stylesheet" type="text/css" href="../../assets/moonshine-layout-styles.css"/>
```

This will cause the browser to look for the stylesheet in /test/resources/moonshine-layout-styles.css, which is incorrect.

Also moonshine-layout-styles.css is placed in grails-app/assets for Grails projects, but the correct path is grails-app/assets/stylesheets.  "../assets/moonshine-layout-styles.css" will still be the correct link path.

**Comment by JoelProminic** [comment]
After the latest updates, the "assets" path is correct for the default index.xhtml, but the "resources" path has an extra "../":
    <link rel="stylesheet" type="text/css" href="../resources/moonshine-layout-styles.css"/>
    <link rel="stylesheet" type="text/css" href="../assets/moonshine-layout-styles.css"/>

Both paths are updated for nesting, but the "resources" path still has an extra "../":
    <link rel="stylesheet" type="text/css" href="../../resources/moonshine-layout-styles.css"/>
    <link rel="stylesheet" type="text/css" href="../../assets/moonshine-layout-styles.css"/>

To clarify, grails-app/assets/stylesheets is the correct folder for the stylesheet in a Grails project.  I was trying to point out that this was correct event though the resulting URL (../assets/moonshine-layout-styles.css) does not include "stylesheet".

**Comment by piotrzarzycki21** [comment]
Path to `grails-app/assets/stylesheets` is back. In the older project probably you will have to change something in file and save it in order to apply that changes. I'm waiting for your more input in case of resources.

**Comment by JoelProminic** [comment]
The links currently look like this.  

    <link rel="stylesheet" type="text/css" href="../resources/moonshine-layout-styles.css"/>
    <link rel="stylesheet" type="text/css" href="../assets/stylesheets/moonshine-layout-styles.css"/>

The first link will fail for Maven/Tomcat builds because there is an extra "../" at the beginning.  The second link will fail because the Grails URL does not include "stylesheets/".

The default links should look like this:

    <link rel="stylesheet" type="text/css" href="resources/moonshine-layout-styles.css"/>
    <link rel="stylesheet" type="text/css" href="../assets/moonshine-layout-styles.css"/>


If the XHTML files are nested, then both links should be updated to reference the parent directory:

    <link rel="stylesheet" type="text/css" href="../resources/moonshine-layout-styles.css"/>
    <link rel="stylesheet" type="text/css" href="../../assets/moonshine-layout-styles.css"/>

**Comment by piotrzarzycki21** [comment]
@JoelProminic 
Just one last thing - Where moonshine-layout-styles.css file should be copied physically (on disk) in case of Grails ?

1) assets/stylesheets/moonshine-layout-styles.css
OR
2) assets/moonshine-layout-styles.css

I have fixed Maven part but I will commit changes once release 1.15.0 will be out.

**Comment by piotrzarzycki21** [comment]
I have pushed changes which should fix this finally. Take a look once you get a chance.
