### ISSUE TITLE
Grid Column Count Does Not Update On Row Selection

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#360]
While testing #333, I noticed that the Grid Columns list did not update properly for a Grid component
1. Add a Grid component to a Visual Editor mockup
2. Add a row
3. Select the first row
4. Add two columns
5. Select the second row.  BUG:  Three columns are displayed in the properties, but only one column is visible
6. Add a column.  Now the properties panel correctly displays two columns

**Comment by piotrzarzycki21** [comment]
I have fixed very last problems with UI in property editor. I think it's ready for tests.

**Comment by atinprominic** [comment]
Its working good as expected

**Comment by JoelProminic** [comment]
I tested this, and I see that the logic generally works, and that I can select a specific cell in this UI.

However, I noticed a remaining issue when selecting rows from the properties panels
1. Open this project (from #333):  [2018_08_29__TestVisualEditor_08_29.zip](https://github.com/prominic/Moonshine-IDE/files/2350493/2018_08_29__TestVisualEditor_08_29.zip)
2. Open TestVisualEditor_08_29.xhtml
3. In the mockup, select the second column of the second to last row (Labeled "2")
4. In the properties, change the Row selection from R4 to R5
5. BUG:  The below error appears on the console, and the selection does not update properly

    : Error #2006
    : RangeError: Error #2006
    : 	at mx.core::Container/getChildAt()
    : 	at mx.core::Container/getElementAt()
    : 	at view.primeFaces.forms::GridForm/getSelectedCell()
    : 	at view.primeFaces.forms::GridForm/updateDisplayList()
    : 	at mx.core::UIComponent/validateDisplayList()
    : 	at mx.managers::LayoutManager/validateDisplayList()
    : 	at mx.managers::LayoutManager/doPhasedInstantiation()
    : 	at mx.managers::LayoutManager/doPhasedInstantiationCallback()
    :
    : Click here to Report a Bug

![image](https://user-images.githubusercontent.com/24532731/45061287-76716e00-b069-11e8-9ef2-1b0548d8d019.png)

I also noticed this case:
1. Open the above project
2. Open TestVisualEditor_08_29.xhtml
3. Select the "1" label in the last row
4. Now select the grid cell containing the "1" label.  
5. BUG:  The grid properties show 5 rows.

![image](https://user-images.githubusercontent.com/24532731/45061293-7d987c00-b069-11e8-80d0-d6fff77e29b2.png)

**Comment by piotrzarzycki21** [comment]
I have fixed both issues. Thanks for catching them!

**Comment by JoelProminic** [comment]
I confirmed that the two issues I reported are fixed, and I couldn't trigger any other issues after clicking around for a while.
