### ISSUE TITLE
Not able to use Git Clone feature

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#361]
When I use Git Clone feature it does not allow for that. It gives the message
- You need Git installed on your system to continue.

Please refer to attached screenshot

![screen shot 2018-09-03 at 11 27 07 am](https://user-images.githubusercontent.com/34882311/44970065-899f1380-af6d-11e8-9425-429b43c72493.png)

**Comment by rat-moonshine** [comment]
As shown in following screenshot, having Git and Subversion options available - you need to first grant permission to Moonshine to access Git or Subversion binaries:
![image](https://user-images.githubusercontent.com/24370870/45011646-44dcb080-b031-11e8-893f-4652fda09fda.png)

Clicking on the above option should open you a prompt mentioning some details about the permission requires:
![image](https://user-images.githubusercontent.com/24370870/45011689-72295e80-b031-11e8-871f-c2782a7c1e6e.png)

Clicking on the 'Allow Access' button is suppose to open you a file browsing dialog where you accept to grant the permission (as mentioned in the above screenshot).

If you had chosen some different directory in the above process, Moonshine will not able to access requisite executable files to run Git - in that case its possible that you receive such error message as you have reported. 

Moreover, the other Git options are not suppose to be opened if you hadn't go through 'Accept Permission' dialog. Can you detail what steps had you taken in that course?

**Comment by rat-moonshine** [comment]
@atinprominic , on a side note, you can do fresh tests (if requires) by resetting Moonshine to default (Moonshine > Settings > General > Reset all settings (Hard)

**Comment by atinprominic** [comment]
I have followed all the steps suggested but still not able to use the Clone feature.

Please refer to attached GIF.

![040918-moonshinegit](https://user-images.githubusercontent.com/34882311/45016574-af4a1c80-b042-11e8-855a-f4dae2e89ed1.gif)

**Comment by rat-moonshine** [comment]
The 'Developer' folder - I see in your screen recording, @atinprominic , is blank - how can that be (!) 

Can you take a look inside the path mentioned in the prompt after 'Grant Permission' option manually, and see if there are files? (`/Applications/XCode.app/Contents/Developers`)

**Comment by atinprominic** [comment]
@rat-moonshine I am not sure what should be there in Developer folder. Please suggest.

**Comment by rat-moonshine** [comment]
In a simple word, do you have any files/folders inside `/Applications/XCode.app/Contents/Developers` path? (As I see in your recording its empty)

**Comment by rat-moonshine** [comment]
@atinprominic can you please confirm on the state of your `/Applications/XCode.app/Contents/Developers` folder. If my assumption is correct you possibly has a broken XCode installation. If you confirm, then you would need a re-installation, and I'll close this issue.

**Comment by atinprominic** [comment]
@rat-moonshine I now installed XCode and working fine. But I found another bug which I will report as a separate issue.

**Comment by rat-moonshine** [comment]
Sounds good @atinprominic . I'm closing this issue now.
