### ISSUE TITLE
User need to move mouse pointer unnecessarily while deleting tabs

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#366]
While deleting tabs from the tabview, the user need to move mouse pointer at the properties panel resize itself to fit the contents. Its a usability issue. We need to move the add/delete buttons to some different location to avoid the movement of mouse pointer. 

Also please check other container controls if they also have the same kind of issue.

Please refer to the attached video.
![050918-moonshine tabview](https://user-images.githubusercontent.com/34882311/45100390-ff120c00-b146-11e8-92f2-072d4533742f.gif)

**Comment by piotrzarzycki21** [comment]
The only resolution which I see is to have fixed height of Table. What do you think @rat-moonshine ?
