### ISSUE TITLE
Cannot create Flex library project form existing sources

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#367]
I have started to look into issue #195 and play with process of creation Flex library which we have already in Moonshine. 

I have project which is library type, but there is no Moonshine files. 
1. I clicked on **Library Project**
2. Choose folder FlexLibraryProject
3. Selects **Project with existing source**
4. Click on **Browse** in **Main source file** section

Results:
I'm seeing some weird file with project name **FlexLibraryProject** instead of list of the file from source folder.

Expected:
I should see list of files in source folder.

I'm attaching project and file.

![weird_file](https://user-images.githubusercontent.com/24554795/45169366-c7b26680-b1fd-11e8-8859-d13594bc768c.png)

[FlexLibraryProject.zip](https://github.com/prominic/Moonshine-IDE/files/2357733/FlexLibraryProject.zip)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine This issue seems to be important, so please focus on it today if you are available.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21  check, if this now works for you.

**Comment by piotrzarzycki21** [comment]
It looks like it's working. If I found anything in that area I will reopen it. Thanks!
