### ISSUE TITLE
Search "Backward" doesn't work

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#369]
I have tried to search some phrase in MXML and as file "Backward" but it doesn't work.

Scenario:
1. Open project file
2. Open search dialog by CTRL + F
3. Select "Backward" and try to find some phrase

Result: 
Nothing happen when I'm clicking Find.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I looked into that - Why [this](https://github.com/prominic/Moonshine-IDE/blob/6e9af4363a2e00b1d5d5fd8b06d553842e935f6e/ide/MoonshineSharedCore/src/actionScripts/plugin/findreplace/view/SearchView.mxml#L42) line is commented ? It is doesn't work because of that.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine any update on that ? Can I bring back that line ?

**Comment by rat-moonshine** [comment]
Probably yes, this make sense to dispatch the previous_step event if radio is present and backward is selected. I can't remember now why if I commented that line, please go ahead and uncomment it (if you have chance), I shall give this tests to find/search process throughout the application at some time when you done.

Thank you!
