### ISSUE TITLE
Switch Moonshine sources to newest Apache Flex 4.16 and Adobe Air 27

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#37]
In order to provide best performance of Moonshine IDE we should switch our development to [Apache Flex 4.16](https://flex.apache.org/download-binaries.html) and [Adobe Air 27.0](https://www.adobe.com/devnet/air/air-sdk-download.html).

Installation of Apache Flex 4.16 with Adobe Air 27.0 can be perform using [Ant-based installer](https://cwiki.apache.org/confluence/display/FLEX/Installation+help#Installationhelp-Ant-basedinstaller).

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I will make some initial work and see whether Ant-based installer is working for me.

**Comment by piotrzarzycki21** [comment]
I did check Ant-based installer and was able to download Apache Flex 4.16 with Adobe Air 26 and Flash Player 26.0. Unfortunately the [installer config ](http://flex.apache.org/installer/sdk-installer-config-4.0.xml?ts=201710241134) is not updated with the newest version of Adobe Air. I will probably start thread on the Dev list how to update that file. 
Still if we want we can for now jump at least to the Air 26. Instruction which is working on Windows:
1) Download [Apache Flex 4.16](https://flex.apache.org/download-binaries.html) binaries and upack them
2) Some Flex dependencies has been downloaded from sourceforge where there is some problem with SSL certs. In order to resolve that I have downloaded following [java files](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) and copied them to {JAVA_HOME}/jre/lib/security. I have to admit that I don't have to much knowledge about Java, but it helps me.
3) Type in the console where you upacked Apache Flex: 
`ant -f installer.xml -Dair.sdk.version=26.0 -Dflash.sdk.version=26.0`

Confirm license agreement and it download additional dependencies.

**Comment by rat-moonshine** [comment]
Since the said AIR 26.0 downloads with Apache Flex 4.16 involves a trail of process, we probably wait till Apache or Adobe fix the downloading problem through Apache Flex SDK Installer. We want to simply the setup process for the users, can not push them through a complex process to setup/download requisite things - that was an often discussed target to Moonshine. 

If Apache Flex SDK Installer can able to download the said SDKs without any problem, then I think we shouldn't have any problem distributing source packaged with the same SDK versions, as well.

**Comment by piotrzarzycki21** [comment]
The problem is that Adobe is still haven't release Adobe Air 64bit version for Windows and it's been a year or so since they have it as an Beta version. We don't know how long we will be waiting.
I have just tried built installer with Adobe Air 64bit beta for windows, but have the same error as always during upacking Adobe Air. 

@joshtynjala did you try [64bit beta](https://fpdownload.macromedia.com/pub/labs/flashruntimes/air/win64SDK/air26_win64SDK_releasenotes.pdf) version ? Maybe I'm missing something. I was curious whether building Flex Installer with that SDK resolve our issue.

**Comment by joshtynjala** [comment]
I built one of my AIR apps with the 64-bit beta, and it seemed to work fine. I saw that some folks were able to build the Flex SDK Installer with the 64-bit beta and it fixed the issue with using too much memory. Unfortunately, I haven't heard any plans from Adobe to release a stable version yet.

For the Feathers SDK Manager, I was able to modify the AntOnAIR library to use PowerShell on Windows to unzip files outside of AIR. My changes are here on Github:

https://github.com/BowlerHatLLC/feathers-sdk-manager/blob/3a5fcd7015f102e66a2ab10f1bc21a0e67485e71/ant_on_air/src/org/apache/flex/ant/tags/Unzip.as#L143

The Flex SDK Installer should also be able to use this change. However, one difference between the Flex SDK Installer and the Feathers SDK Manager is that the Flex SDK Installer also verifies the md5 hash of the files it downloads. As I understand it, that can also use too much memory on Windows. I remember a quick Google search seemed to indicate that PowerShell can also verify md5 hashes, so it should be possible to make the Flex SDK Installer work on 32-bit AIR without running out of memory. I've just never had the time to give it a shot.

**Comment by piotrzarzycki21** [comment]
@joshtynjala ,

I was able to built successfully installer and it is strange to me that it didn't help. PowerShell is really powerful cause you can run almost all things which are in the .NET framework through that layer. :)  
Thanks for your link I will put my hands on fixing installer in that way we will see what happen. 

Piotr

**Comment by joshtynjala** [comment]
@piotrzarzycki21 If you try to handle the md5 verification with PowerShell, be sure to check that you're using APIs that existed in the default version of PowerShell that is installed in Windows 7. AIR still runs on Windows 7, so it's important that the installer works there. When I first implemented unzip with PowerShell, I accidentally used newer APIs that didn't exist on Windows 7, and I wasted a day!

**Comment by piotrzarzycki21** [comment]
After copying your code and my first tests it looks promising, Adobe Air is unzipping nicely! I have some other failure but I hope I will pass through them. 

MD5 checks do not fail, but will see once I test more. 

Thanks a lot @joshtynjala - You have just fixed Apache Flex Installer! :)

**Comment by joshtynjala** [comment]
@piotrzarzycki21 It's possible that the md5 tests don't have any issues. I remember that Alex mentioned that they might fail because they also require loading large files into memory, but the unzip issue happens first, so I don't think anyone has had a chance to test md5 until now.

**Comment by piotrzarzycki21** [comment]
Here is where I end up today:
- Your code @joshtynjala nicely working and I have pushed it to the installer as part of [FLEX-35295](https://issues.apache.org/jira/browse/FLEX-35295)
- During work on that issue I have found another one in Flex SDK itself and fixed it [FLEX-35364](https://issues.apache.org/jira/browse/FLEX-35364). Script installer.xml which has been used by installer separately now working ok, but I have to fix nightly build of sdk and nightly build of installer in order to test everything. I have started to ask more for some guide in that on [Flex Dev list](http://apache-flex-development.2333347.n4.nabble.com/Flex-Installer-and-fix-for-downloading-an-Adobe-Air-td64754.html).

Thank you!

**Comment by joshtynjala** [comment]
> but installer failed later on OSMF
> Error HRESULT E_FAIL has been returned from a call to a COM component.
> At line:1 char:93
> + ... ComObject shell.application;$zip = $shell.NameSpace($zipPath);New-Ite ...

@piotrzarzycki21 That looks like my code from the PowerShell script. It seems to be failing to unzip something. Maybe it's incorrectly trying to unzip osmf.swc?

**Comment by piotrzarzycki21** [comment]
@joshtynjala Ahh yes! Ok let me dig into that.

**Comment by piotrzarzycki21** [comment]
Installer has been fixed! - More information on [Dev list](http://apache-flex-development.2333347.n4.nabble.com/Flex-Installer-and-fix-for-downloading-an-Adobe-Air-tp64754p64769.html). 
Currently it will be working only with Apache Flex Nightly build. I need to start discussion about releasing both Installer and Apache Flex, but that part I will leave as out of scope of that tasks. Once SDK will get release we will be able to switch Moonshine to the newest version.

**Comment by rat-moonshine** [comment]
I see the installer is not available anymore by the link (given at Dev list). Furthermore, is it possible to get a Mac build somehow?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have sent you by email link to Windows and Mac version. I built Mac version on my own. Unfortunately sometimes those link on dev doesn't work and I'm not sure why. Try nightly build of SDK in your tests.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have started official process of release [Apache Flex Installer](http://apache-flex-development.2333347.n4.nabble.com/VOTE-Release-Apache-Flex-SDK-Installer-3-3-RC1-td64831.html) - you can try binary distributions.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have pushed [Apache Flex Installer RC2](http://apache-flex-development.2333347.n4.nabble.com/VOTE-Release-Apache-Flex-SDK-Installer-3-3-RC2-td64858.html) - It would be great if you could try it on Windows. Install Apache Flex SDK 4.16.1 RC1 with Adobe Air 27. - This version of SDK is under nightly build. 
Release process for new SDK is also started so I'm waiting for the voters. :)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Flex SDK 4.16.1 has been released. I have to make an announcement, but we can move forward with this one. You have available Installer 3.3 - uninstall previous version on Windows.
We will need to upgraed "ApacheFlexSDKInstallerLib.swc" in our repositories - Can you make that upgrade ?

**Comment by rat-moonshine** [comment]
If you can provide me the exact changes that you did in the SDK installer code (to fix AIR download issue), then I can incorporate and release the updated swc file. Please, let me know.

**Comment by rat-moonshine** [comment]
I've installed SDK installer version 3.3 from Apache website, and tried on my El Capitan. I confirm, AIR download completes this time, but the installation failed anyway:
![screenshot1](https://user-images.githubusercontent.com/24370870/33197263-5eb0e76c-d10a-11e7-8709-ce0b4a0fb4e9.png)

Here's the full log details:

> Installer version 3.3.0 (mac)
> Using Locale: en_IN
> Fetched the SDK download mirror URL from the CGI.
> SDK version Apache Flex SDK 4.16.1
> AIR version 27.0
> Flash Player version 27.0
> Creating Apache Flex home
> Creating temporary directory
> Downloading Apache Flex SDK from: http://www-eu.apache.org/dist/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.tar.gz
> Verifying Apache Flex SDK MD5 Signature
> The Apache Flex SDK MD5 Signature of the downloaded files matches the reference. The file is valid.
> Uncompressing: /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/temp/apache-flex-sdk-4.16.1-bin.tar.gz
> Finished uncompressing: /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/temp/apache-flex-sdk-4.16.1-bin.tar.gz
> Downloading Adobe AIR Runtime Kit for Mac from: http://airdownload.adobe.com/air/mac/download/27.0//AdobeAIRSDK.dmg
> Validating download: /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/AdobeAIRSDK.dmg
> Should unzip: ${shouldUnzip}
> Mounting dmg
> IS WINDOWS: ${isWindows}, IS MAC: mac
> Copying AIR SDK from mounted volume
> Unmounting AIR SDK
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/frameworks/libs/air to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/frameworks/libs
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/frameworks/projects/air to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/frameworks/projects
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/include to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/lib/android to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/lib
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/lib/aot to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/lib
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/lib/nai to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/lib
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/runtimes to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/samples/badge to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/samples
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/samples/icons to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/samples
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/templates/air to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/templates
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/templates/extensions to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/templates
> Copying files from /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/airsdk/templates/sdk to /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/templates
> Installing Adobe Flash Player playerglobal.swc from: http://fpdownload.macromedia.com/get/flashplayer/updaters/27//playerglobal27_0.swc
> Validating download: /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/frameworks/libs/player/27.0/playerglobal.swc
> Downloading 2.2.zip from: https://github.com/swfobject/swfobject/archive
> Validating download: /Users/santanu/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_27.0/in/swfobject_2_2.zip
> Download complete
> Downloading OSMF2_0.swc?format=raw from: http://sourceforge.net/adobe/flexsdk/code/HEAD/tree/trunk/frameworks/libs
>       [get] [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032" errorID=2032]
> Installation aborted: http://flex.apache.org/track-installer.html?failure=true&label=Apache Flex SDK 4.16.1&version=4.16.1&os=mac&installerversion=3.3.0&info=&info=%20%20%20%20%20%20%5Bget%5D%20%5BIOErrorEvent%20type%3D%22ioError%22%20bubbles%3Dfalse%20cancelable%3Dfalse%20eventPhase%3D2%20text%3D%22Error%20%232032%22%20errorID%3D2032%5D

**Comment by piotrzarzycki21** [comment]
@rat-moonshine please take a look into the suggestion from Alex [here](http://apache-flex-development.2333347.n4.nabble.com/DISCUSS-Release-Apache-Flex-SDK-4-16-1-RC2-tp64936p64973.html).

**Comment by rat-moonshine** [comment]
This may not be the best place to report this, since @piotrzarzycki21 here, I'm bringing this issue with Apache Flex SDK Installer - 
- Application window do not resize - do not maximize
- Long dropdown items cut-off the screen and I found no easy way to scroll them through (except enabling key focus somehow and using up/down arrow key)

![image](https://user-images.githubusercontent.com/24370870/33923575-f2363216-dff7-11e7-81d8-b5ca869983fe.png)

I see Adobe AIR released 28.0 but Apache SDK Installer shows 27.0 as last. I'm just curious, how quick this update happens to the installer data?

**Comment by rat-moonshine** [comment]
I'm still having download problem with AIR 27.0 in newer SDK installer:
![image](https://user-images.githubusercontent.com/24370870/33925066-a94fd2a8-dffe-11e7-8494-cab9b59752db.png)

I've installed JCE 8.0 following instruction the given Apache forum. I have Java 1.8.0_102 installed.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Can you send full logs ? I don't see installer version.

**Comment by piotrzarzycki21** [comment]
After install JCE do you have still problem with downloading SDK on Mac ?

**Comment by piotrzarzycki21** [comment]
As for the updating installer with new Adobe Air - in most cases Alex was doing that, but I will try to do this time.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 I shall try to re-do the download process at sometime and send you the full log. The installer version is latest 3.3.2.

> Installer version 3.2.0 (windows)
> Using Locale: en_US
> Fetched the SDK download mirror URL from the CGI.

Testing and installing JCE 8.0 is done in Windows.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine the latest installer version is 3.3.0, that's why you have this error 1000. Uninstall previous version of installer and try to install again SDK. I'm working on adding Adobe Air 28. I will let you one I finish.

**Comment by rat-moonshine** [comment]
I see the downloading problem with newer version (3.3.0), too - 

> Installer version 3.3.0 (windows)
> Using Locale: en_US
> Fetched the SDK download mirror URL from the CGI.
> SDK version Apache Flex SDK 4.16.1
> AIR version 28.0
> Flash Player version 28.0
> Creating Apache Flex home
> Creating temporary directory
> Downloading Apache Flex SDK from: http://www-us.apache.org/dist/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.zip
> Verifying Apache Flex SDK MD5 Signature
> The Apache Flex SDK MD5 Signature of the downloaded files matches the reference. The file is valid.
> Uncompressing: E:\DevareaLocal\ApacheFlexSDK\4.16.1_AIR.28.0\temp\apache-flex-sdk-4.16.1-bin.zip
> Finished uncompressing: E:\DevareaLocal\ApacheFlexSDK\4.16.1_AIR.28.0\temp\apache-flex-sdk-4.16.1-bin.zip
> Downloading Adobe AIR Runtime Kit for Windows from: http://airdownload.adobe.com/air/win/download/28.0//AdobeAIRSDK.zip
> Validating download: E:\DevareaLocal\ApacheFlexSDK\4.16.1_AIR.28.0/in/AdobeAIRSDK.zip
> Finished uncompressing: E:\DevareaLocal\ApacheFlexSDK\4.16.1_AIR.28.0/in/AdobeAIRSDK.zip
> Installing Adobe Flash Player playerglobal.swc from: http://fpdownload.macromedia.com/get/flashplayer/updaters/27//playerglobal28_0.swc
>       [get] [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032" errorID=2032]
> Installation aborted: http://flex.apache.org/track-installer.html?failure=true&label=Apache Flex SDK 4.16.1&version=4.16.1&os=windows&installerversion=3.3.0&info=&info=%20%20%20%20%20%20%5Bget%5D%20%5BIOErrorEvent%20type%3D%22ioError%22%20bubbles%3Dfalse%20cancelable%3Dfalse%20eventPhase%3D2%20text%3D%22Error%20%232032%22%20errorID%3D2032%5D
>

**Comment by piotrzarzycki21** [comment]
Yep that is expected, cause I didn't give you an info that I have finished work on that :)  Now I'm giving you. :) Try again.

**Comment by rat-moonshine** [comment]
Installation worked this time, thanks!

Just curious, what you required to did (to fix this)? As I have seen the entry for downloading AIR 28.0 was already available to the interface!

**Comment by piotrzarzycki21** [comment]
We have on the website following [file](http://flex.apache.org/installer/sdk-installer-config-4.0.xml) - It's need to be updated once new SDK come out.

**Comment by rat-moonshine** [comment]
Since Apache Flex 4.16.1 released, and SDK installer also working (after some hack), do you think it's good to port Moonshine to the latest SDKs (4.16.1, AIR 28.0) now @piotrzarzycki21 ?

**Comment by piotrzarzycki21** [comment]
Yes please proceed. W should upgrade if not to Air 28, at least to Air 27. Please report any issue here.

**Comment by rat-moonshine** [comment]
So far, all looks great. I will give couple more tests after updating Bamboo build SDKs.

**Comment by piotrzarzycki21** [comment]
When I'm compiling in IDE I have following error with AIR 28:

`Error:(65, 0) [MoonshineSharedCore]: unable to open 'D:/flex_sdk/flex_4.16.1/frameworks/libs/air/crosspromotion.swc'`

I copied that file from previous version and it's working. I'm wondering whether this is not some issue with Air package.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine repository where you can find installer sources are [here](https://git-wip-us.apache.org/repos/asf/flex-utilities.git).  You can switch to tag "apache-flex-sdk-installer-3.3.0", folder [flex-installer](https://github.com/apache/flex-utilities/tree/apache-flex-sdk-installer-3.3.0/flex-installer). I'm not sure how you are preparing installer swc, but build first [ant_on_air](https://github.com/apache/flex-utilities/tree/apache-flex-sdk-installer-3.3.0/flex-installer/ant_on_air) which have most of the changes.

**Comment by rat-moonshine** [comment]
Thank you @piotrzarzycki21 . I shall look into this once I get some time. I'll get back to you if need something to clarify.

**Comment by rat-moonshine** [comment]
As 1.8.0 ported with the latest SDKs (Apache Flex 4.16.1 with AIR 28.0), can we close this issue (?) Or, this has something in detail for which we want to keep this open for sometime.

**Comment by piotrzarzycki21** [comment]
Let's close it. We are handling update of the internal installer as a separate issue.

**Comment by piotrzarzycki21** [comment]
We should also update information on the website and in Readme what we are using for the source building.

**Comment by rat-moonshine** [comment]
> We should also update information on the website and in Readme what we are using for the source building.

That is a good point. I can check this. Thanks!
