### ISSUE TITLE
Copy/Paste in Grid type of components is failing

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#371]
When I'm trying to Copy and Paste some elements from one Cell to another in Grid we are getting exception.

`[Fault] exception, information=TypeError: Error #1034: Type Coercion failed: cannot convert view.primeFaces.surfaceComponents.components::OutputLabel@1b40dc29 to mx.containers.GridRow.`

Copy/Paste need to be checked in PanelGrid and Table as well.

**Comment by JoelProminic** [comment]
We had to create a new 1.15.0 build, so this issue was included.  Copy-paste seems to be working now, but I noticed an issue with the update chain that I reported in #372.
