### ISSUE TITLE
Undo/Redo Does Not Work With Copy/Pasted Components

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#372]
I noticed that I can not undo a pasted component (see #248):
1. Open a Visual Editor tab
2. Add a label and a panel (Note that these specific components are not necessarily relevant, but they make it easier to confirm the behavior)
3. Select and copy the label
4. Select the panel, and paste the label into the panel.  It should look something like this: 
![image](https://user-images.githubusercontent.com/24532731/45442427-99160f00-b687-11e8-995b-77d3c2272929.png)

5. Use CTRL-Z/CMD-Z to undo the action.  BUG:  The panel is removed instead of the pasted label.  Note that adding the panel was the last change to the mockup before the paste.

**Comment by JoelProminic** [comment]
I confirmed that undo and redo work with copy-pasting a single component.

When I copy and paste a Div with multiple children, I see this behavior:
# Create a Div with two children (I tested with labels and buttons)
# Select the Div and press CMD-C
# Select the base component and press CMD-P.  Both the Div and its children are duplicated, as expected.
# CMD-Z.  The Div and its children are removed.
# Press CMD-Z twice more.  Nothing happens.  I think this is because it is trying to undo all three components.
# Press CMD-Z.  The last child of the Div is removed.

I was occasionally seeing that the Organizer tree was distorted while running this procedure (two buttons appeared outside of the stage).  However, I could not trigger this consistently.

**Comment by rat-moonshine** [comment]
@JoelProminic reported the following issue reproduceable against GridBase components:

1. Create two Grid components. Make the first one larger
2. Select and copy the second Grid
3. Select the first grid and paste the second
4. Pasted grid component added as direct children to the grid where its pasted - instead to a cell
4. CMD-Z. The grid disappears in the interface, but remains in Organizer 

The above problem should be fixed now. 

**Added** (applied for both Grid and PanelGrid):

1. Add a panelgrid component to the stage
2. Have the component multiple column/row
3. Drag any component to stage and press Ctrl/CMD+C to copy
4. Click on the panelgrid component - we can not select certain column/row at this point
5. Open Organizer and select any particular column/row/cell in panelgrid component
6. Do a paste (Ctrl/CMD+V) - the component should paste to the selected cell/row/column only

**Comment by rat-moonshine** [comment]
Any removal of component (manual or by undo/redo) from stage seems was failing to update states in Organizer. This should be fixed now. Please, check.
