### ISSUE TITLE
Add PrimeFaces p:textEditor component to Visual Editor

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#376]
More information about -> [p:textEditor](https://www.primefaces.org/showcase/ui/input/textEditor.xhtml)

**Comment by JoelProminic** [comment]
The textEditor component is mostly working in the visual editor, but I noticed that the height and width are not saved properly.  If I close and reopen the editor tab, any changes to the height and width reset.  This triggers both when I set the values manual and when I drag the component.
