### ISSUE TITLE
Code Completion For ActionScript Files Dialog Fails To Store Java Path

### ISSUE THREAD

**Issue by angelhdz** [prominic/Moonshine-IDE#380]
Hello guys!

I have latest Moonshine version. I'm new to Apache Royale. I managed to build and run a Javascript project.
My issue is that everytime I open Moonshine it shows me a dialog to add auto-complete for actionscript files, I selected Java path, and next time I open Mooshine, the dialog still showing. I fixed it by going to settings and adding Java path directly.

**Steps to replicate:**

- Open Moonshine
- **Moonshine optionally supports code completion for ActionScript(.as) files. Would you like to enable this now?** dialog appears.
-  I click on **Configure & Enable** then **Allow Access**.
- I choose Java path and click **Select Folder**.

**Expected Results:**

- Choosing Java path will save the path and the dialog won't appear next time Moonshine starts.

**Behavior:**

- Choosing Java path fails to save Java path and the dialog will appear every time Moonshine starts.

Thanks!

**Comment by piotrzarzycki21** [comment]
@angelhdz Could you specify OS ? Is it Windows or Mac ?

**Comment by rat-moonshine** [comment]
@angelhdz please provide the Java path you selects in the process, also. Thank you for reporting!

**Comment by angelhdz** [comment]
> @angelhdz please provide the Java path you selects in the process, also. Thank you for reporting!

C:\Program Files (x86)\Java\jre1.8.0_181

**Comment by angelhdz** [comment]
> @angelhdz Could you specify OS ? Is it Windows or Mac ?

Windows 10 64bit

**Comment by piotrzarzycki21** [comment]
@angelhdz could you use JDK instead JRE - I'm not sure whether there is some problem with it, but we are not using JRE.

**Comment by angelhdz** [comment]
> @angelhdz could you use JDK instead JRE - I'm not sure whether there is some problem with it, but we are not using JRE.

Yup, silly me. JRE is the runtime plugin, it requires the Java SDK. I'm downloading it right now and see if this solves the issue. Thanks.

**Comment by angelhdz** [comment]
Alright guys. 

That was source of the issue, I added the **JRE** path instead of the **JDK**. Installing the JDK and selecting it when the dialog shows, successfully adds the JDK path, and the dialog won't appear next time Moonshine starts.

Thank you for your time and sorry for my silliness!
