### ISSUE TITLE
Cannot build to JS MX Apache Royale examples

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#382]
Following options in menu Project are disabled when I'm trying to build [MX Royale example](https://github.com/apache/royale-asjs/tree/develop/examples/mxroyale/HelloWorld):

![mx_royale](https://user-images.githubusercontent.com/24554795/46009220-26615680-c0bf-11e8-9818-b074f34d776d.png)

**Comment by atinprominic** [comment]
I tested by creating the new Royale Browser Project and also I imported the project from Git. In both cases the options are now enabled. Please check below screenshot

![image](https://user-images.githubusercontent.com/34882311/46397418-d3ffe580-c70f-11e8-8fff-ca0d1bfea86c.png)
