### ISSUE TITLE
Unable to create new MXML and AS file in Royale project

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#383]
In Royale type of project I'm not able to create New MXML and AS file, all those options are disabled.

![royale_project](https://user-images.githubusercontent.com/24554795/46026872-ac47c680-c0ec-11e8-9609-7f041fd0a393.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine this is critical for me. We need to release new version once I fix that one.

**Comment by rat-moonshine** [comment]
And we noticed this now! 

Glad you fixed the problem, by moving ahead.

**Comment by piotrzarzycki21** [comment]
@joshtynjala do you think we could release version having current state of Java support ? I don't see any harm with that, but just wanted to make sure.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Maybe you should branch at the previous version and cherry pick your commit. I'm not comfortable releasing my recent changes yet.

**Comment by rat-moonshine** [comment]
On a side note, I don't comfortable for a hurried release either. Its already month's end, and we should try to go with usual release schedule on beginning of the month; after every recent commits/changes reviewed properly. It's a good thing people haven't reported this yet.

**Comment by atinprominic** [comment]
I tested and its working as expected. Check screenshot:

![image](https://user-images.githubusercontent.com/34882311/46397512-0d385580-c710-11e8-942b-df3020c319f0.png)
