### ISSUE TITLE
Cannot delete character in code editor from second line of code in MXML file

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#386]
Code editor behave weird when I'm trying to delete last character in the second of code. Below short movie with that behavior. I'm hitting Backspace all the time. 

![cannot_delete_last_char](https://user-images.githubusercontent.com/24554795/46030829-8bd13980-c0f7-11e8-9433-069167b99dbc.gif)

It's not reproducible with released 1.15.0 version.

**Comment by piotrzarzycki21** [comment]
@joshtynjala , @rat-moonshine Any changes lately which could cause that issue ?

**Comment by joshtynjala** [comment]
I also noticed that using the arrow keys to move the caret isn't always able reach the end of a line (or sometimes the beginning).

I don't think any of my changes would cause these issues...

**Comment by joshtynjala** [comment]
I figured it out! I made a silly copy/paste mistake. Sorry about that!
