### ISSUE TITLE
Update History and Value Bugs with Calendar Component

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#389]
I did some testing with the new Calendar component (#377):

I found that I got this error whenever I tried to undo changes made to the Calendar properties (except for Width and Height):
1. Add a Calendar component to the mockup
2. Set a property besides Width or Height
3. Undo.  BUG:  I get the error below
4. Undo.  The Calendar control is removed

    : Error #1034
    : TypeError: Error #1034
    : 	at view.suportClasses::PropertyChangeReferenceCustomHandlerBasic/changeItem()
    : 	at view.suportClasses::PropertyChangeReference/undo()
    : 	at actionScripts.plugins.ui.editor.text::UndoManagerVisualEditor/undo()
    : 	at actionScripts.plugins.ui.editor.text::UndoManagerVisualEditor/dispatchPendingEvent()
    :
    : Click here to Report a Bug

I experimented with changing the Pattern property, and I found a couple cosmetic issues:
- The Date property format in the sidebar was not affected by the date format
- If you set a value for the field in the Mockup area, it will only use the updated Pattern if there was no existing value.

I also noticed that changing the date value in the mockup does not update the Date property, but updating the date property changes the value displayed in the mockup.

**Comment by piotrzarzycki21** [comment]
Main issue which is raised here seems to be fixed. I did following changes additionally:

1. Changing **Pattern** in property editor now reflects immediately to selected date both on mockup area and property editor
2. Changing min/max date reflects to mockup and property editor.

I decided do not reflect changes from Mockup to property editor, cause I think it shouldn't be actually possible. However it requires a bit more work to disable Flex DateField control so I will leave it for now as is.
