### ISSUE TITLE
Wavy underlines do not scroll horizontally

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#39]
When moving pages from a Spark project into a FlexJS project, many tags and attributes are wavy underlined as expected. If you then horizontally scroll the page, the wavy underlines do not scroll with the rest of the page. Example image attached.

Doug
![moonshine horiz scroll problem](https://user-images.githubusercontent.com/32083838/31420995-63700bb2-ae77-11e7-84d9-8f6bdc65982e.png)

**Comment by piotrzarzycki21** [comment]
Hi @doug777 ,

Could you tell in which version of Moonshine you experienced that issue ? 

Thanks,
Piotr

**Comment by doug777** [comment]
I'm using 1.5.1 in Win 10 Pro 64-bit and the project is using FlexJS 0.8.0 FP23.0 AIR23.0 en_US.

I have replied to emails from other issues I started, but looks like you have to sign in here and comment. Is that right?

Doug

**Comment by piotrzarzycki21** [comment]
@doug777 ,

Could you check whether you experienced that issue with our fresh released 1.6.0 version. 

I'm not sure what do you mean by "sign in here and comment".

**Comment by doug777** [comment]
Yes it's exactly the same in 1.6.0.

Doug

**Comment by JoelProminic** [comment]
I was able to reproduce the horizontal scroll issue like this:

1. Create a new FlexJS Project
2. Make sure that the project is using a FlexJS SDK
3. Add a long line of code with an error.  The line needs to be long enough that it will require a horizontal scroll.  I added an example below that will trigger both an error and a warning
4. Slide the horizontal scroll bar.  You should see that the wavy lines do not move

```
	<fx:Script>
		<![CDATA[
		private var  foo:String = doesNotExist + "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." + doesNotExist2 + " Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";
		private var bar = "";
		]]>
	</fx:Script>
```

Unfortunately, I also noticed that the code overlaps with the sidebar.  
![2017_10_12__sidebaroverlap](https://user-images.githubusercontent.com/24532731/31523894-e2ae5f00-af7b-11e7-99db-ddc5d2d7546d.jpg)


Here is my test project, if you need it.  I tested with Moonshine 1.6.0 on Mac OS 10.10.5:
[2017_10_12__TestHorizontalScroll.zip](https://github.com/prominic/Moonshine-IDE/files/1381023/2017_10_12__TestHorizontalScroll.zip)

**Comment by JoelProminic** [comment]
I noticed the update from @joshtynjala after I had written up my findings.

Testing with his updates, I found that the wavy underlines scrolled properly.  However, I still see the new overlap issue I reported.

If this is an independent problem, then we should move it to a separate issue.

**Comment by rat-moonshine** [comment]
I think the masking issue then a separate problem since @joshtynjala fix now moves wavy underlines properly. We should take the masking problem to a separate issue.

**Comment by rat-moonshine** [comment]
I've created a new issue on horizontal scroll masking here - #42 .
