### ISSUE TITLE
Set perecentWidth/percentHeight for component in Visual Editor makes it shrink to width of the children

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#392]
When user set for some component percentWidth/percentHeight it makes it shring instead take whole available space of the parent.

![percentwidth_height_problem](https://user-images.githubusercontent.com/24554795/46127769-f9818080-c231-11e8-8135-ca25796748dc.gif)

**Comment by piotrzarzycki21** [comment]
EditingSurface didn't take full available space and it causes that weir behavior where instead taking whole available space it shrinks to the children's size. 

The problem with above fix is that, when Main application has width/height=100% and some of the components inside takes more than available space - scrollbar won't appear. I'm not sure how to overcome that one yet. I may try to add another scrollbar - this time for Main application. 

I will add as well change where if we won't provide for the **Div** width/height or percentWidht/percentHeight: It will expand to width =100%, height won't be setup (it will shrinks to children sizes). - This behavior is on HTML sight.

![div_width_height_changes](https://user-images.githubusercontent.com/24554795/46139325-8d614580-c24e-11e8-958e-c54550964901.gif)

**Comment by piotrzarzycki21** [comment]
Here is the detailed description of my problem. We have following structures on Flex sight for our surface area (the area where components are being dropped)

```
<s:Scroller percentWidth="100">
      <!--Above scroller is for that Group.--->
      <s:Group>
             <!--Surface area - components are being dropped here. First is Main app.--->
             <s:Group id="surfaceArea" left="0" right="0" top="0" bottom="0"> <!-- <--- Those values allows you to use percentWidth/percentHeight for your main application. Without it we have above issue. -->
              <s:Group>
      </s:Group>
</s:Scroller>
```

1. You are placing Main application inside surface area with `percentWidth/percentHeight=100`
2. This is really important what is happening now. **Main application will take whole available space.** By whole available space I'm talking about those one which is given by Moonshine. **Scrollbars disappear**. If content inside Main application is greater than that area unfortunately it won't be visible. - Will be cutted. 

This is Flex behavior, however Browser will handle that situation differently. Main application is width/height=100% all content will be displayed, because Browser itself shows you scrollbars, so there is not effect of cutted content. Try to make such exercises with our latest examples which has lot's of content inside main application. Export it and siplay.

**Potential solution:**
If main application which is actually Flex `BorderContainer` won't have set `percentWidth/percentHeight` scrollbars appears and content greater than available space will be visible. **I could stop assigning values which users provide thorough property editor or which comes from Visual Editor XML if those are percent values.** However going with that path we are getting back to the beginning where Main application is shrink to the children's width/height. The only solution which comes to my mind is observe whether content inside main application expands over available space. 

1. Once user setup `percentWidth/percentHeight` I'm assigning it to the main app only if content `height/width` is smaller than available space. 
2. If content is bigger than available space I'm setting `percentWidth/percentHeight` to `NaN ` accordingly, but user still see 100% in property editor and Visual Editor XML have those values as well.

The second step allows to show scrollbars if needed, at least this is in theory.

**Comment by piotrzarzycki21** [comment]
I have made following progress: If main application have percentWidth/percentHeight scrollbars should appear if content is bigger than visible area. 
Side effect of my changes right now is that: In property editor percentWidth/percentHeight is replaced by values in pixels instead percentage, although Visual Editor XML provides those values. - I'm working to fix that effect.

**Comment by piotrzarzycki21** [comment]
I just made an update where I have tried to fix displaying of percentWidth/percentHeight in property editor - which was broken after my previous update.

**Comment by rat-moonshine** [comment]
I'm trying to understand the proposed mechanism; Is the new scroller updates is valid only for files opened with saved data? Or, the width/height calculations are runtime feature. 

When I opened an xhtml file (provided by Andrii) I noticed it opens with vertical scrolls properly. 

Later in a new editor, shrinking the `rootDiv` size, and adding lots of contents inside it, I didn't found the items cropping exceeds the `rootDiv` frame or there were any scrolls. 

![image](https://user-images.githubusercontent.com/24370870/46329446-f409a900-c62a-11e8-9502-a6d130baf77c.png)

So is the inner children are supposed to be calculated and avail the scrolls during opening a file only, or there are things you're still you're working on?

**Comment by piotrzarzycki21** [comment]
This mechanism triggers only when you open the files, what user do later on it depends on him. Are you expecting for the above scenario that when you put some component inside control it will expand ? What do you have selected in property editor when you are doing that ?

**Comment by atinprominic** [comment]
I found many improvements while testing and also the initial issue reported is fixed.

But I found another issue which I think should be addressed.

When we remove the checkbox against the Width and Height properties, the div size is reset to 20 px. Then again if I enable the check-mark then it becomes 20 px. As a user its not good and the initial value prior to resetting the checkbox should be maintained. This current behavior is not expected.

I have recorded a video attached for your reference.

![021018](https://user-images.githubusercontent.com/34882311/46335858-85d2df80-c646-11e8-8050-75a82e059581.gif)

**Comment by piotrzarzycki21** [comment]
@atinprominic Please attach that project in this issue, cause something is wrong with it. I cannot reproduce that issue. I mean my containers are shrinks to smaller sizes, but not so drastically.

**Comment by atinprominic** [comment]
@piotrzarzycki21 I beleive the issue should occur for you as well. Please follow the exact steps I have recorded again in the attached GIF.

Also I am attaching the compressed ZIP of the project as requested by you.


[Issue#392.zip](https://github.com/prominic/Moonshine-IDE/files/2440762/Issue.392.zip)


![031018](https://user-images.githubusercontent.com/34882311/46392716-effb8b00-c6ff-11e8-87f4-6826c05e1d86.gif)

**Comment by piotrzarzycki21** [comment]
@atinprominic Thanks for testing. I think this is similar issue to above one, but a bit different. Main container shrinks when we have setup percentWidth/percentHeight, but this one shrinks when we remove completely width/height. I'm not sure what is the recommendation in that case. I will raise separate issue after todays call if we decide to do something with that. However I'm not sure what can we do, cause this is probably standard Flex behavior.

**Comment by piotrzarzycki21** [comment]
Reopen in order to commit one more fix for that case.

**Comment by JoelProminic** [comment]
I tested this.  I can get the basic functionality to work if I refresh src/main/web-app, but I found a couple issues:
- The XHTML file only appears if I refresh src/main/web-app.  If I refresh a parent directory, nothing happens
- Refresh does not work for other files in the project.

Here is an example test procedure:
1. Create a new Visual Editor project (I'll call it "TestRefresh" in this procedure)
2. Outside of Moonshine, copy a valid VisualEditor XML file to TestCopy/visualeditor-src/main/webapp
3. Also copy the XML file to these directories in the project:  TestCopy, TestCopy/src, TestCopy/src/main, and TestCopy/src/main/webapp
4. In Moonshine, right-click on TestCopy and click Refresh.  BUG:  the project tree does not update
5. Right-click on TestCopy/src and click Refresh.  BUG:  the project tree does not update
6. Right-click on TestCopy/src/main and click Refresh.  BUG:  the project tree does not update
7. Right-click on TestCopy/src/main/webapp and click Refresh.  The expected xhtml file is created.  BUG:  The XML file does not appear


I tried this feature both with Andrii's latest examples (using <MainApplication> for the base component) and with more recent files created from another VisualEditor project (using <Div> for the base component).  I got the same behavior with both examples.

**Comment by JoelProminic** [comment]
Yes, it was supposed to be on #396 .   Sorry about that.
