### ISSUE TITLE
Drag and drop files into Moonshine to open them

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#393]
As reported by _Walker_,

### Part 1

This is a basic feature that many applications use to leverage the opening of files.
- The user should be able to click - and drag - any 'acceptable' file onto the Moonshine window to trigger Moonshine to open that file.
- An 'acceptable' file would be any file under the file formats supported by Moonshine.

If we do not have an existing list of supported file formats, please provide feedback and I will create the list for this issue as well as document it for the future.

### Part 2

The user should be able to choose Moonshine from the dropdown dialog that is presented when they attempt to open a .AS file.
- Select a .AS file in the Filesystem
- Right-Click -> Open With...
- Scroll until 'Moonshine.app' is visible in the list

The result is that 'Moonshine.app' is greyed-out and cannot be selected by the user for opening .AS files.

This issue may be more widespread than just ActionScript files. So in such case, we should find out how to add Moonshine's list of supported file-types to the Filesystem.

**Comment by rat-moonshine** [comment]
In my opinion, file association is supported by Adobe AIR. I never explored this feature very closely, possibly this is doable, though.

There are list of file types which opens by Moonshine (mostly _text_ type of files and those are related to ActionScript development mainly), i.e. .as, .mxml, .css etc. (file types can be found in file browse dialog by going into `Moonshine > File > Open`). 

Since opening Away Builder files also now possible within Moonshine, so we can consider .awd file type, too.

On project _type_, .as3proj file for most of the Moonshine projects, and .veditorproj file for Visual Editor project. The latter is completely custom type by Moonshine. 

@piotrzarzycki21 if you remember any other file types that I missed, please add.

**Comment by rat-moonshine** [comment]
I'm starting with initial phase of investigation and requisites for this, but this is not targeted for v1.16.0.

**Comment by JoelProminic** [comment]
Opening a .as file in Moonshine with "Open With" works fine when Moonshine is already open.  

However, when we try this when Moonshine is not currently running, the Moonshine menubar displays, but the application does not fully load.  The Moonshine application cannot be closed normally, and it needs to be killed from Activity Manager.   @rat-moonshine reported similar behavior on Windows.

I checked the macOS Console (/Applications/Utilities/Console.app), and I saw these lines when I tried to open a .as file with Moonshine when Moonshine was not running.

    10/5/18 10:43:05.774 AM Mumble[50334]: warning: failed to get scripting definition from /Applications/Moonshine.app; it may not be scriptable.
    10/5/18 10:43:05.774 AM Mumble[50334]: AppleEvents: Send port for process has no send right, port=( port:72551/0x11b67 rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
    10/5/18 10:43:05.788 AM Mumble[50334]: AppleEvents: Send port for process has no send right, port=( port:72551/0x11b67 rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread

I don't see any messages on the console if I try to open a .as file while Moonshine is already running.

**Comment by rat-moonshine** [comment]
I tested the procedure with a separate application packaged with usual certification on macOS. 

The application opened without any trouble when a given file choose to 'Open with' by the application from Finder. This gave impression that in Moonshine case, some exception may throws by some reason while opening a file by 'Open with' command when Moonshine already not opened - during startup a lot of process happens in Moonshine, I need to find where this breaks.

**Comment by JoelProminic** [comment]
I confirmed that Open With now works when Moonshine is closed.  However, I found that with the latest build of Moonshine on macOS, the bookmarks reset every time that Moonshine was restarted.

I also did some tests with the various file extensions associated with Moonshine on macOS.  I tested Open With only with Moonshine already open, to avoid the above error.

Extension | Open With | Drag to Moonshine | Notes
--------- | --------- | ----------------- | -----
.as | Works | Works | 
.xml | Works | Works | 
.css | Works | Works | 
.txt | Works | Works | 
.mxml | Mixed results | Mixed results | If the current open project is a visual editor project, the mxml file opens with the visual editor.  If the current open project is a Flex project, it opens with a normal editor
.as3proj | Unavailable | Works | 
.veditorproj | Unavailable | Works | 
.xhtml | Unavailable | Opens blank editor | This case may not make sense, since the visual editor is actually using the hidden .xml file to display its contents

**Comment by rat-moonshine** [comment]
For the basic first release, I have relaxed existing conditional tests to check Visual Editor project etc. in open command, for the files open off-Moonshine. In next phase, when we shall do more tailored processes for these functions (i.e. opening project when double-clicked .as3proj etc.), we'll do more detailed planning on file open conditions. We shall raise the requirement in separate issues.
