### ISSUE TITLE
'File -> Open' Dialog in Moonshine does not retain last-opened directory

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#394]
As reported by _Walker_,

When using the File -> Open dialog in Moonshine, the 'Open' dialog will always start at the Desktop folder. It would be useful if the 'Open' dialog could start from the last-opened location.

1. Go to 'File -> Open' in Moonshine
2. Navigate away from the Desktop and open a file in another part of the Filesystem
3. Go to 'File -> Open' again in Moonshine

**Result:**   The 'Open' dialog starts at the Desktop, always
**Expectation:**    The 'Open' dialog should navigate to the last-opened location, for improved ease-of-use

The main benefit of this small feature improvement is that the user can open multiple files quickly in the same relative directory without having to relocate to the same directory each time.

**Comment by piotrzarzycki21** [comment]
It's annoyed me for a long time ;) +1 :)

**Comment by rat-moonshine** [comment]
Walker, Piotr, give a test this time now. Both file open and project opening locations are interlinked now, that means either will start from last visited/opened location through a file dialog box.

**Comment by JoelProminic** [comment]
The update seems to be working on Windows, but not on macOS.

The FileChooser for SDKs still resets to ~/Desktop every time it opens.  I'll let you know if I think of other interfaces that have this problem.

**Comment by piotrzarzycki21** [comment]
I asked @atinprominic to test that issue as well. Maybe will be good to get that tests once Santanu look into the Mac case.

**Comment by atinprominic** [comment]
@piotrzarzycki21, Joel is right. Its working on Windows but not for MacOS.

**Comment by rat-moonshine** [comment]
All the file open, save and browse events are now linked with same internal file; that means, all the said events are now supposed to be open with the last visited location (unless any event asked to open to a certain location) across Windows and macOS. 

This issue is now open for test.

**Comment by atinprominic** [comment]
@piotrzarzycki21 Its working good now.
