### ISSUE TITLE
Organizer sometime fails to render PanelGrid children on initialization phase

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#395]
As reported by Andrii, when opened a large xhtml file to editor, Organizer not showing children nodes of PanelGrid have large amount of children. 

I able to have them rendered when did this steps, though:
- Delete the PanelGrid component from Organizer
- Make an Undo 
- PanelGrid entry returns and this time renders all its children within

For some reason in initialization scope, PanelGrid fails to provide requisite information about its children, this needs to check.

**Comment by rat-moonshine** [comment]
I see the problem is related to deferred children creation to PanelGrid. I also able to reproduce the above problem in following scenario:

- Have a TabView with multiple tabs
- Place one PanelGrid in each tabs
- Have some cells in each PanelGrid, and preferably some elements inside them
- (Close/Open the file - as Organizer do not reacts on run-time Property Editor yet)
- Go to Organizer
- Except first tab's PanelGrid node, all other PanelGrids in inactive tabs didn't populated with their children

I made some adjustment to the PanelGrid, and all seems good again.

**Comment by atinprominic** [comment]
@rat-moonshine Can you please provide me the project used for testing this scenario so that I can use it for testing?

**Comment by atinprominic** [comment]
@rat-moonshine I tested by following the steps above - https://github.com/prominic/Moonshine-IDE/issues/395#issuecomment-426250794

I have not found any issue.

**Comment by rat-moonshine** [comment]
@atinprominic , thank you for testing this. I'm not sure why but I do not receive your notifications on your every messages. 

Anyway, the file I received from Andrii was a real-time Notes conversion, I'm not sure if we wants to attach the file here. If you still need the file, please email me I'll send you.
