### ISSUE TITLE
Can't create new files and Error #3218

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#398]
In my mxml js-only project I cannot create new mxml or as files. No matter what is selected in the Projects panel, re-open program, re-start computer, I always see as attached. First time I've needed this since upgrading to 1.15.0.

![create new files disabled](https://user-images.githubusercontent.com/32083838/46646349-5f6bf180-cbbc-11e8-95ad-fd090b96fcb1.png)

Also I get lots of Error #3218 on opening the program and more are generated whenever I run the mouse over the code window. This problem has existed since last time I reported a problem.

Doug

**Comment by piotrzarzycki21** [comment]
Hi @doug777 ,
We know about that. We will release new version very soon. Please contact with me off the list and I will send you nightly build. piotrzarzycki21@gmail.com.

**Comment by piotrzarzycki21** [comment]
@doug777 are you using Mac or Win ?

**Comment by piotrzarzycki21** [comment]
It should be fixed in 1.16.0.
