### ISSUE TITLE
Improvement to Find/Replace

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#40]
When changing a project from Flex to FlexJS, there are many occasions where lots of Find/Replace are required. In this case I need to change a bunch of = to : and space to comma. But I don't want to change every = or space in the whole page, just those within this block of text. So I have to use Replace One, but having done a replace I then have to click next before I can replace the next one. This more than doubles the time it takes to do this. It would be better if it automatically moves to the next after Replace One.

Doug

**Comment by rat-moonshine** [comment]
Following changes will be in next release:

![image](https://user-images.githubusercontent.com/24370870/31437074-a6623740-aea1-11e7-81b5-c89b7423caba.png)

Find: One step forward or backward search (based on radio value)
Replace/Find: One step replace and move for next instance
Replace: One step replace
Replace All: Replace all instances

**Comment by rat-moonshine** [comment]
The above changes looks meets your needs @doug777 , please suggest.

**Comment by doug777** [comment]
Yes agreed, this makes it work the way similar functions work in other programs.

Doug

**Comment by rat-moonshine** [comment]
After some debate here, we chose to keep 3 options only (removing 'replace' option) to reduce confusion:

- Find (single step find instance)
- Replace/Find (single step replace and auto-find next instance)
- Replace All (all instance replace)
