### ISSUE TITLE
PrimeFaces TabView doesn't calculate height properly

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#403]
When PrimeFaces TabView doesn't have set property height it doesn't stretch to the height of children. Content in that case is outside component. 

![tabview_content_outside_component](https://user-images.githubusercontent.com/24554795/46953205-7a8fa300-d08d-11e8-90ef-70118445d1b1.png)

**Comment by piotrzarzycki21** [comment]
I thought that it takes me a lot of time, but code for all calculations were in place. I just didn't launch it when Tab was changing. It can go to 1.16.0.

**Comment by atinprominic** [comment]
@piotrzarzycki21 

I have tested and found that the reported issue is resolved. However I found another issue in the same form. The issue is that  the DIVs which are outside the TabView, are overlapping with the TabView.

Please check below screenshot.

![image](https://user-images.githubusercontent.com/34882311/47131880-b78eac00-d2be-11e8-94cb-709d41302f8b.png)

**Comment by piotrzarzycki21** [comment]
@atinprominic Does TabView have setup some height ?

**Comment by atinprominic** [comment]
Yes it has. Please check attached screenshot:

![image](https://user-images.githubusercontent.com/34882311/47135355-7356d800-d2cd-11e8-9e1e-852184a612d1.png)

**Comment by piotrzarzycki21** [comment]
@atinprominic If you unselect height it will work correctly. In case when TabView have some height it's content goes outside if it's heigher than TabView itself. - Exactly the same issue can be seen after exporting that stuff to PrimeFaces project. I did fix issue when we don't have height for TabView - above case wasn't considered in that fix and I don't won't to spend time for now - since we have some solution. I'm keeping in mind this scenario.

**Comment by atinprominic** [comment]
Ok. Then we should consider this task as closed.
