### ISSUE TITLE
Auto completion adding close attribute string in CDATA

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#405]
Following gif depicting issue:
![item_close_attribute_cdata](https://user-images.githubusercontent.com/24554795/47020572-ee977d00-d159-11e8-9c32-7661754aa2bc.gif)

**Comment by piotrzarzycki21** [comment]
Are you saying that if you declare in function variable like that - intellisense doesn't work ?

```
private function myFunction():void
{
     var item:Object = {};
    ///Trying to use intellisense on declared variable - Doesn't work ?
}
```

**Comment by atinprominic** [comment]
@piotrzarzycki21 

Its working fine. I was doing some mistake while testing.

**Comment by piotrzarzycki21** [comment]
I'm reopening this one cause CDATA should be added to all components.

**Comment by piotrzarzycki21** [comment]
I have reopened wrong issue. This one is finished.
