### ISSUE TITLE
Add  Privacy Policy information

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#406]
In order to satisfy [requirements](https://developer.apple.com/app-store/review/guidelines/#legal) from Apple App store we need to add Privacy Policy window.
Suggestion is to have it in menu _Help_ ->  _Privacy Policy_

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have window ready locally, so I'm waiting for Privacy Policy.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Whether it should be there in the other place - please talk with the person in Prominic who will be responsible for creating that Privacy Policy. I'm fine with whatever decision which I get from that preson. @JoelProminic should have more information.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Whether it should be as you suggested or in the place where I actually put it - depends on the person which is responsible for creating that Privacy Policy. Talk with that person from Prominic. - @JoelProminic should have more information if you are interested in that task.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Whether it should or shouldn't be there need to decide person responsible for a creating that privacy in Prominic. Please contact @JoelProminic if you are interested in details of that task. I'm fine with whatever decision we will get.

**Comment by rat-moonshine** [comment]
A privacy policy is not a part of Help (to any software application). It generally resides somewhere inside of Settings, or About. I do not understand what you meant by it depends on the person who is responsible for creating the Privacy Policy. If that does mean I should ask the client only (in this case Prominic or Joel) whom this software belong to, I shall ask the client. Please, open the issue for modification.

**Comment by piotrzarzycki21** [comment]
> Please, open the issue for modification.

What issue do you want me to open ?

**Comment by rat-moonshine** [comment]
I was thinking more on these recently, what about something we do more obvious to make the user aware of the newly introduced privacy policy? Something like opening with a window when Moonshine next time start with v1.16.0, describing with the privacy policy and force the user to agree to enter Moonshine. We can keep a flag to cookie to not to shown up the window again when next time Moonshine starts (if once agreed by the user).

I see a few advantage of this system:

1. User surely be aware of the newly introduce privacy policy by Moonshine
2. User will bound to be align with the privacy policy proposed (they never able to say we were not agreed at any circumstances)
3. We can use the same window system 'if' at sometime we require to update/change the privacy policy 

In my opinion, user will not be able to use the system if not accept by the terms, so that we can be assure by the new privacy policy laws enforced by the Apple/EU.

**Comment by rat-moonshine** [comment]
This is more an idea, and these stuff over our likeliness. This could be done if we want the privacy policies more obvious to the users. I'm still good enough by having this under Help menu, though.

**Comment by JoelProminic** [comment]
I did some work drafting a privacy policy, but I realized that the SVN or Git credentials could be considered personal information.  I reviewed #307, and I think we can make the following assertions about how we use the credentials:
- Moonshine itself does not save the credentials
- The credentials will be passed to user-configured third-party applications.  These applications may save the credentials.
- The user is not required to enter credentials - they can save the credentials with the third-party application directly, or they can use an external source control application.

@rat-moonshine, please verify whether the code is consistent with these assertions.

Another case that I considered was the "This is great!" and "I'm having some problems" interfaces.   However, these interfaces do not request any personal information or account information from the user - instead the requests are forwarded to the Twitter, Facebook, or GitHub websites.  So, I don't think this needs any special attention in the privacy policy.

If anyone else thinks of other collected data that may need to be considered for the privacy policy,please let me know.

**Comment by rat-moonshine** [comment]
I have checked through SVN and Git process on using the credentials, I confirm Moonshine do not stores any credential data to its local storage or neither to any server. While in case of Git, Moonshine provides option to re-use entered credential for the same application session - the entered credential stores to the memory as long Moonshine session is running, but I think this is irrelevant to an extent too. 

The Git authentication window is suppose to come if user do not have any credential already stored to the system keychain. It seems like once any Git command _push_ command executes with a credential, it stores to the keychain, and next time you don't even need to provide any credential. I seen the behaviour in Windows, too.

The bottom-line is, by executing any SVN or Git command with given credential through Moonshine, the credential may store to the system keychain (by SVN/Git application) but Moonshine has no control over it.

**Comment by JustinProminic** [comment]
Options I have found for this are:

https://digital.com/blog/best-privacy-policy-generators/
https://app.termly.io/user/products
https://www.iubenda.com/en/help/401-privacy-policy-for-ios-and-macos-apps
https://privacypolicytemplate.net/privacy-policy-required-law/

**Comment by JustinProminic** [comment]
I also found this list of policies:
https://digital.com/blog/best-privacy-policy-generators/

and ended up using the first one on the list:
https://privacypolicies.com

to create the privacy policy, which is available at:
https://privacypolicies.com

The resulting files are attached:

**Comment by piotrzarzycki21** [comment]
@JoelProminic , @JustinProminic - I have added privacy policy to Moonshine - it's under menu **Help** -> **Privacy Policy**. However I have one issue. I loaded privacy policy from HTML, because it's the easiest way of displaying it and have looking as it is in document.
In order to load that html I used class called [FlexHTMLLoader](https://flex.apache.org/asdoc/mx/core/FlexHTMLLoader.html). In order to display what's is loaded I need to use UIComponent class, FlexHTMLLoader cannot be added to spark components. Unfortunately UIComponent doesn't have scrollbar, so I need to work a bit more in order to add those to displayed html. Currently you can scroll all content by mouse, but scrollbar is not visible. 
We can move slowly forward with release - I will try to work on that tomorrow more.

**Comment by JoelProminic** [comment]
When I tested Help > Privacy Policy on Mac OS 10.10.5, I got this error:

    : HTMLLoader failed to initialize
    : Error: HTMLLoader failed to initialize
    : 	at flash.html::HTMLLoader()
    : 	at mx.core::FlexHTMLLoader()
    : 	at actionScripts.plugins.help.view::PrivacyPolicyScreen/onAboutScreenCreationComplete()
    : 	at actionScripts.plugins.help.view::PrivacyPolicyScreen/___PrivacyPolicyScreen_BorderContainer1_creationComplete()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at mx.core::UIComponent/set initialized()
    : 	at mx.managers::LayoutManager/doPhasedInstantiation()
    : 	at mx.managers::LayoutManager/doPhasedInstantiationCallback()
    :
    : Click here to Report a Bug


We need to have a copy of this Privacy Policy available on moonshine-ide.com for the App Store release.   It may be simpler to just open the privacy policy page in a external browser.

**Comment by piotrzarzycki21** [comment]
We can do that in that way as well! Please deploy HTML version on Moonshine website somewhere and I will link it.

**Comment by JoelProminic** [comment]
The Privacy Policy was added to the website here:  http://moonshine-ide.com/privacy-policy/

I confirmed that Moonshine now opens the Privacy Policy in a browser window/tab on both macOS and Windows.

**Comment by rat-moonshine** [comment]
> 
> 
> @JoelProminic , @JustinProminic - I have added privacy policy to Moonshine - it's under menu **Help** -> **Privacy Policy**. However I have one issue. I loaded privacy policy from HTML, because it's the easiest way of displaying it and have looking as it is in document.
> In order to load that html I used class called [FlexHTMLLoader](https://flex.apache.org/asdoc/mx/core/FlexHTMLLoader.html). In order to display what's is loaded I need to use UIComponent class, FlexHTMLLoader cannot be added to spark components. Unfortunately UIComponent doesn't have scrollbar, so I need to work a bit more in order to add those to displayed html. Currently you can scroll all content by mouse, but scrollbar is not visible.
> We can move slowly forward with release - I will try to work on that tomorrow more.

Please ensure the API do not use HTML API in-background. We can not bundle WebKit to the App Store version, they'll reject it.

On the other hand as an alternative, we can display the texts in-Moonshine as plain texts to an editor/tab and make it uneditable.
