### ISSUE TITLE
Auto import package insert it in a first line instead Script

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#408]
I have created simple Flex project with listener for `creationComplete` and discovered that importing package doesn't work properly. It inserts it in the first line of file. It is reproducible in VSCode with extension 0.14.1.
The most important thing is that you shouldn't have any import in the `Script` section. If you have at least one - It's working without the problem.

![import_package_in_wrong_place](https://user-images.githubusercontent.com/24554795/47149661-87ea9e80-d2d4-11e8-92a4-7f01b17093d1.gif)

**Comment by joshtynjala** [comment]
This is fixed in BowlerHatLLC/vscode-nextgenas@c89cc593e22b3d23bfb09685c37790fb1e16142c. It will be included in Moonshine the next time that the language server is updated.

**Comment by piotrzarzycki21** [comment]
I just tested it and it's working after your update to v0.15.0
