### ISSUE TITLE
Missing Application Descriptor for New AIR Project

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#41]
I noticed that new AIR projects are not created properly in the recent builds of Moonshine:
1. Open Moonshine
2. File > New > New Flex Desktop Project (MacOS, Windowos)
3. Give the project a name, and click Create
4. BUG:  the generated project does not have a application descriptor file (src/<project>-app.xml)
![2017_10_12__testinvalidair](https://user-images.githubusercontent.com/24532731/31524228-c42aa1b8-af7d-11e7-89f4-c23a9f4fd5fc.jpg)

Here is the console output when I try Project > Build & Run
    : Launch Applcation
    : bin-debug/TestInvalidAIR.swf (1007613 bytes)
    : (fcsh) 
    : application descriptor not found

This does not trigger with the latest release, 1.6.0, so somthing broke for this feature after the release.

I tested with Mac OS 10.10.5.

**Comment by rat-moonshine** [comment]
Fixed.

**Comment by JoelProminic** [comment]
I retested this and confirmed the fix.

**Comment by piotrzarzycki21** [comment]
@JoelProminic do we want to release 1.6.1 soon because of that issue ?

**Comment by JoelProminic** [comment]
@piotrzarzycki21 Fortunately, this bug was added after the 1.6.0 release, so we should not need to rush 1.6.1.
