### ISSUE TITLE
Reorganization in Apache Ant build system

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#410]
Before we add #409 we should reorganize a bit [Apache Ant](https://ant.apache.org) build support.

**Current state with Ant:**
There are three places where Apache Ant can be configured, run etc. 
1. Menu **Ant**
2. Menu **Project** -> **Build with Apache Ant**
3. Menu **File** -> **Settings** -> **Ant Build Setup**

**Proposition of changes for Ant:**
1. Menu Ant - Should be removed, cause it's redundant with menu **Project** -> **Build with Apache Ant**
2. Menu **Project** -> **Build with Apache Ant** 
- Should redirect to Settings if path to Ant is not setup
- Should check whether in Root directory or "build" folder ant script for building exists. If doesn't exists we should ask to point it for selected project.

**Comment by rat-moonshine** [comment]
You need to understand the difference between `Ant -> Build Apache Ant File` and `Project -> Build with Apache Ant`. 

When the former is liable to execute any arbitrary Ant build file from any location - this only needs to locate the Ant build file in user's system; the latter tries to auto-find Ant build file in the opened project's project folder only. The latter one resides in the 'Project' menu because its project specific. 

Because of their different purposes, the options decided to kept separately, they are not redundant.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Thanks for explanation. What do you propose to do when we will have second build system Maven ?

**Comment by piotrzarzycki21** [comment]
My question is - How to organize current UI in order to have all of that + also ability to build whatever Maven pom file which we wanted to ?

**Comment by rat-moonshine** [comment]
If your target to build Maven project-based, then I can see the option will added along with 'Build with Apache Ant' under 'Project' menu. If you also wants to build any arbitrary pom file by an option, then perhaps we move both the 'Build Apache Ant File' and 'Build Apache Maven File'(proposed) to 'Others' menu option - to be included with existing 'Build an Away3D Model'.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine That's a good idea! Thanks! I will talk on the meeting about that.

**Comment by piotrzarzycki21** [comment]
I think I'm done with that. Here is the changes which I did:
1) I removed **Ant** from menu and moved that option to **Others**
2) I made a bit of a clean up in [AntBuildPlugin](https://github.com/prominic/Moonshine-IDE/blob/features/issue_410_reorganization_in_apache_ant_build_system/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ant/AntBuildPlugin.as)
