### ISSUE TITLE
Introduce Maven setup through Moonshine App Store Helper

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#412]
For the need of Visual Editor PrimeFaces preview task, we shall require to run micro-server and compiled by Maven. Due to Apple sandbox, any executable permitted to run if only in user's ~/Downloads folder. 

The proposed idea is to have the setup automated to use's ~/Downloads directory through MASH which will also eliminate the chance of having extended attributes added to the binaries when downloaded through browser.

**Comment by rat-moonshine** [comment]
Maven setup added in MASH to download to user's `~/Downloads/MoonshineSDKs/Maven/..` folder. Targeted release with v4.0.0.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Since you have pushed this to master instead on the branch it's part of 1.16.0.

**Comment by piotrzarzycki21** [comment]
Please update CHANGELOG.

**Comment by piotrzarzycki21** [comment]
> We have different page for Moonshine App Store Helper to the Moonshine website, I'm not sure if we want to mention this update to Moonshine CHANGELOG but I'll ask this to Joel.

Ahh If that's the case I'm fine with that.

**Comment by rat-moonshine** [comment]
It appears that I misunderstood the release with Moonshine v.1.16.0. Returning the release tag to v.1.17.0.

**Comment by piotrzarzycki21** [comment]
If you are return to 1.17.0 you will have to revert changes from master as well. Master contains all the changes which are in 1.16.0, that's why I'm doing Maven support on separate branch to do not mess up things on master. Does your changes can break something ? If not let's leave it in 1.16.0 with appropriate milestone.

**Comment by rat-moonshine** [comment]
Changes to SDK installer library only likes to be visible in Moonshine App Store Helper. Since we're not releasing a MASH application now, that is not suppose to affect anything the existing in-built SDK installer UI in Windows, so I'm not worrying about this; This can go with v1.16.0 without any visible effect.
