### ISSUE TITLE
Closing and re-opening Home view do not triggers recent projects/files

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#419]
- Have some projects opened so the references shown up to Home tab recent-opened projects/files
- Close the Home tab
- Re-open Home tab by going to `View > Home`
- Try to open any recent-opened project/files from Home tab link
- Nothing opens

The above breaks are also applicable from `File > Recent Projects` and `File > Recent Files`.

**Comment by JoelProminic** [comment]
I tested with the updated Moonshine build, and the problem seems to be fixed.  To be safe, I confirmed all of the features on the Home page:
- Recent projects
- Recent files
- Open Project
- Create Project
- "This is great!" button
- "I'm having some problems" button.
