### ISSUE TITLE
Editor masking issue produced by horizontal scrolling

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#42]
As reported by @JoelProminic in #39 ,

> I was able to reproduce the horizontal scroll issue like this:
> 
> 1. Create a new FlexJS Project
> 2. Make sure that the project is using a FlexJS SDK
> 3. Add a long line of code with an error.  The line needs to be long enough that it will require a horizontal scroll.  I added an example below that will trigger both an error and a warning
> 4. Slide the horizontal scroll bar.  You should see that the wavy lines do not move
> 
> ```
> 	<fx:Script>
> 		<![CDATA[
> 		private var  foo:String = doesNotExist + "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." + doesNotExist2 + " Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";
> 		private var bar = "";
> 		]]>
> 	</fx:Script>
> ```
> 
> Unfortunately, I also noticed that the code overlaps with the sidebar.  
> ![2017_10_12__sidebaroverlap](https://user-images.githubusercontent.com/24532731/31523894-e2ae5f00-af7b-11e7-99db-ddc5d2d7546d.jpg)
> 
> 
> Here is my test project, if you need it.  I tested with Moonshine 1.6.0 on Mac OS 10.10.5:
> [2017_10_12__TestHorizontalScroll.zip](https://github.com/prominic/Moonshine-IDE/files/1381023/2017_10_12__TestHorizontalScroll.zip)

**Comment by rat-moonshine** [comment]
I found a solution, but I need to ensure some more test cases.

**Comment by JoelProminic** [comment]
I tested with:
- Maximized window
- Unmaximized window
- Changing the width of the editor window by dragging
- Testing with existing text that exceeded the scrollable threshold
- Adding new text to exceed the scrollable threshold 

I did not see any problems.  Additionally, I confirmed that the error and warning lines are still working properly through these tests (see #39).
