### ISSUE TITLE
New XHTML files do not appears to project sidebar against non-conversed or maually-added XMLs

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#420]
**Severity:**

1. Create a new Visual Editor PrimeFaces project in Moonshine, close the project after it's being created
2. Put some new non-conversed _.xml_ files under the project's `visualeditor-src\main\webapp` folder
3. Based on #396 manually-added _.xml_ files in above folder are now suppose to show under project's _src_ folder in Moonshine IDE
4. Re-open the project in Moonshine
5. No _.xhtml_ file shows against manually-newly-added _.xml_ files [Bug] (`src/main/webapp`)
6. Right-click on the `webapp` folder in Moonshine, choose 'Refresh'
7. No new file appeared (against manually-added _.xml_ files) [Bug]
8. Again right-click on the `webapp` folder in Moonshine and choose 'Refresh'
9. This time newer _.xhtml_ files appeared against manually-added _.xml_ files under `src/main/webapp`

Further related to this issue - this may involve other logic-check how source folder determines against Visual Editor Primefaces project in Moonshine; Instead of above step.6 continue by following:

6. Right-click on `src` folder and choose Refresh
7. Sub-tree-folders collapsed
8. Source-folder (s) icon disappeared
9. Upon expanding the collapsed folder under `src/main/webapp` we can see new _.xhtml_ files against manually-added _.xml_ files

If I order the current requirements based on above findings:

1. New _.xhtml_ file references suppose to get generated during opening of project
2. Refreshing the source folder should appear the new _.xhtml_ files in one attempt
3. Check the logic behind determine the Visual Editor Primefaces source folder so (s) icon do not disappears on refresh

**Comment by rat-moonshine** [comment]
Yeh, I just updated my comment wording.

**Comment by rat-moonshine** [comment]
Above issues should be resolve now, and Visual Editor Primefaces project now checks and generate requisite .xhtml file during opening, too. 

However, I saw a bug after some tests which needs to address:

1. Open a Visual Editor Primefaces project which has few xml and same number of xhtml files available
2. Moonshine properly displays the number of xhtml files to its sidebar
3. Open (system)explorer and deletes one or multiple xhtml files by going to src/main/webapp
4. Return to Moonshine the sidebar still shows old number of files
5. Try a refresh to the project source folder inside Moonshine
6. Sidebar tree duplicates those xhtml files those were deleted in step.3
7. Refresh the folder again, this time it shows actual number of files deducting duplicated file entries

I shall check this tomorrow.

**Comment by rat-moonshine** [comment]
Duplicate entry population to sidebar tree should be fixed now.

**Comment by piotrzarzycki21** [comment]
> Moonshine created new Visual Editor project were using older 'MainApplication' tag which is obsolete now, thus skipped during determination phase of new Visual Editor XML file presence - now template file updated with newer tag.

This is not true! MainApplication is not obsoleted. It's being used as it was before. Please revert your commit https://github.com/prominic/Moonshine-IDE/commit/e3a82797b95c992e5b138be5a53218c77ea17065
RootDiv - is being used only for files which has been created by user - It means that every new file has that.

**Comment by rat-moonshine** [comment]
Sorry, I'm unclear. 

What does it meant by 'RootDiv is being used only for files which has been created by user'? As I have seen by older template (which was using `MainApplication` tag) Moonshine was saving .xml files with `MainApplication`. Now consider this scenario - 

- User duplicated one saved .xml file (which has `MainApplication`) to many
- User now wants to have them detected into Moonshine tree view
- Moonshine failed to detect because of the use of `RootDiv` restriction in the codes [here](https://github.com/prominic/Moonshine-IDE/blob/3d85519a83f9f3abcdc1af3f14f6a1c3e58e3a02/ide/MoonshineSharedCore/src/visualEditor/plugin/VisualEditorRefreshFilesPlugin.as#L120)

I don't have any problem to revert the template file but I need to know how these two different tags still serving and since the above conditional restriction how would user auto-detect .xml files having `MainApplication` tag?

**Comment by piotrzarzycki21** [comment]
> What does it meant by 'RootDiv is being used only for files which has been created by user'
It means that if you right click on Project tree and choose **New** -> **Visual Editor PrimeFaces File** -File with `RootDiv` will be created.

`MainApplication` - This tag contains additional property for main window, apart of that it is used as a marker that we are in a starting point of our application. User doesn't have to detect anything. User is not aware what root tag we are using. It serves only to our purposes. 

If you would like to cover your scenario you have two options:
1. Do not allow duplicate Main application file. 
2. Change that file to RootDiv during duplication - Which I don't recommend, but it's possible.

**Comment by piotrzarzycki21** [comment]
> User duplicated one saved .xml file (which has MainApplication) to many

First of all how user duplicate that file ? If it is being done manually - that is not concerns. If user provides many MainApplication file cause converter did it - We have a bug. Converter itself should produce RootDiv files only. 
If converter should produce MainApplication for one of the file - It should be some kind of parameter which allows to do that for one file.

**Comment by piotrzarzycki21** [comment]
Think about Flex application - can you have two main application file ? 

The only thing in my opinion which you should do is don't allow duplicate MainApplication file or leave it as is. 
If user duplicate that file manually - That's his problem not ours.

**Comment by rat-moonshine** [comment]
> Think about Flex application - can you have two main application file ?

I don't think this match the scenario of ours here. In Flex they offers different types to create a .mxml file. At here, we are not giving such _type_ options; So even if the user is not entirely idiot-proof, s/he might see the .xml files are same initially (unless, they observe to the fine-details). 

We seen the above scenario when testing last night with Joel. It's true we may not knew fine details those you've explained now, but to us it came first as a bug - when we manually-duplicated the .xml file and were expecting them to shown in the tree view. 

Yet, we may not need to worry about the above kind of event as this (project) template type we're working on is very specialized and possibly people will generate/duplicate through given options.
