### ISSUE TITLE
Allow multiple file selection in sidebar tree

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#421]
As a general need that come up during #413 to select multiple files, allowing the ability will not limit to copy/paste feature but will avail to many other things:

Function | Current | Should Behave After
------------ | ------------- | ----------------
Copy/paste | Select one | Select multiple and copy/paste
Open | Opens one | Opens multiple files
Delete | Deletes one | Deletes multiple files
Rename | Rename one | Rename should disabled
Duplicate | Duplicate one | Option should disabled
Copy Path | Copying single path to clipboard | Option should disabled
Open in Explorer | Opens against one | Option should disabled

**Completion:**

- [x] Copy/paste
- [x] Open
- [x] Delete
- [x] Rename
- [x] Duplicate
- [x] Copy Path
- [x] Open in Explorer

**Comment by rat-moonshine** [comment]
Multiple file selected to tree view across one or more projects, now deletes and updates the tree view properly. There are couple of rules exists against this, though:

Doable: 
- Multiple files/folders across opened projects can deleted

Restricted:
- Terminates if one or more file do not exists physically
- Terminates if any project root and files from project(s) have been selected
- Terminates if multiple project roots are selected (due to our current design, we need to prompt with a dialog on each project's going-to-be deletable files)

**Comment by rat-moonshine** [comment]
Since file-duplicate process consists of opening an window and asking target name of the duplicate file - this fits for only file at a time. Thus, I'm making the option disable in case of multi-selection.

**Comment by rat-moonshine** [comment]
Multi-selection of files are now opening.

Notes:
1. If directory selected, it just expand in current process
2. If multiple binary files selected - Moonshine currently throws multiple alert asking if user wants to open the file with system default application - I need to show the alert in such cases only once mentioning one or multiple files in selection are binary files if user wants to open by system default application

**Comment by JoelProminic** [comment]
Action | Observed behavior
------ | -----------------
Copy | Works
Open | Opens all selected files
Open (directory in selection) | Expands directory, doesn't open any files in the directory unless they are also selected
Open (binary in selection) | Prompts to open binary
Delete | Works, only prompted once
Rename | Disabled
Duplicate | Disabled
Copy Path | Disabled
Open in Explorer | Disabled

The prompt for deleting multiple files or folders is:

    Are you sure you want to delete selected file/folder from the file system?

Instead, use:

    Are you sure you want to delete all selected files and folders from the file system?

**Comment by JoelProminic** [comment]
I noticed this behavior with Copy/Paste
1. Select a directory and its nested files
2. Right click > Copy
3. Create a new directory
4. Paste into the new directory.  BUG:  Moonshine prompts that the pasted directory already exists.

I think this is because the files are copied as part of the directory, and then copied again.  Oddly, the duplicate error is for the directory rather than the files

**Comment by rat-moonshine** [comment]
`OpenFileCommand` restructured to work in following ways:
- Load file data once - previously it was loading multiple times to open a file
- Alert once if multiple binary files are present in a selection process
- Opens selected files in order - non-binaries first, binaries last

The above will change open file call event as well, sending array of `FileLocation` object instead of one.

Delete files confirmation message changed.

**Comment by rat-moonshine** [comment]
> I think this is because the files are copied as part of the directory, and then copied again. Oddly, the duplicate error is for the directory rather than the files

I see the file copying had given preference instead of folder. I have changed the ordering, please check how this looks valid now.

I also seen a bug when:
- Multiple files are selected in tree view
- Right-click on any other file that is not in the selection
- Choose option to delete
- Moonshine deletes all the files those were in selection, instead of the file we wanted to delete

The above problem should have fixed now.

**Comment by JoelProminic** [comment]
The updates seems to work well.

I would like to update the messages we display when opening binary files.  Let me if you feel the new text does not match the actual behavior.

#### Current:

Single selection:

    Unable to open binary file ant-contrib-0.6.jar.
    Do you want to open the file by operating system?


Multiple selection:

    Unable to open all selected binary files.
    Do you want to open the files by operating system?


#### Updated:

Single selection:

    Unable to open binary file ant-contrib-0.6.jar.
    Do you want to open the file with the default system application?


Multiple selection:

    Unable to open the selected binary files.
    Do you want to open the files with the default system applications?

**Comment by rat-moonshine** [comment]
The message is more clear in manner, Joel. I have updated the messages to the branch.

**Comment by piotrzarzycki21** [comment]
It it's finished please close it.

**Comment by rat-moonshine** [comment]
Yeh, I will need to close it. I have some other issues to close as well.
