### ISSUE TITLE
TreeView Error on Java Maven/Gradle Projects

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#423]
Opening/creating a Java Maven or Java Gradle project gives this error

    : Error #1009
    : TypeError: Error #1009
    : 	at components.views.project::TreeView/handleProjectsChange()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.collections::ListCollectionView/dispatchEvent()
    : 	at mx.collections::ListCollectionView/addItemsToView()
    : 	at mx.collections::ListCollectionView/listChangeHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.collections::ArrayList/internalDispatchEvent()
    : 	at mx.collections::ArrayList/addItemAt()
    : 	at mx.collections::ListCollectionView/addItemAt()
    : 	at actionScripts.plugin.project::ProjectPlugin/handleAddProject()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugin.project::ProjectPlugin/openPreviouslyOpenedProject()
    : 	at actionScripts.plugin.project::ProjectPlugin/handleShowPreviouslyOpenedProjects()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at MethodInfo-14797()
    : 	at SetIntervalTimer/onTimer()
    : 	at flash.utils::Timer/tick()
    :
    : Click here to Report a Bug 

I have had a Java Maven project in my project list for a while now, but I have not seen this error until today.

**Comment by rat-moonshine** [comment]
These errors should be fix by now. Please, check.

**Comment by rat-moonshine** [comment]
I'm closing this as fixed.
