### ISSUE TITLE
Multiple ANE in the folder are not unpacked during compilation

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#425]
I have  Flex mobile project where there is a multiple ANE files in one folder. I have pointed that folder in Moonshine (project **Settings** -> Paths -> **Native extension folder**) and did a **Debug** -> **Build & Debug**.

**Results:**
Only one ANE extension was expanded into a separate project.

Additionally classes in the project from ANE extensions are not recognized by Moonshine.

**Comment by rat-moonshine** [comment]
I tried to reproduce the problem using multiple .ane files in both Windows and macOS platform, but unfortunately I couldn't able to reproduce it.

For a cross-check, try to rename the .ane file (that demonstrated you not-unpacking) to .zip in your OS explorer, and try to open it. If you see this opens without any problem, then you might want to send me the .ane to investigate with (if possible).

**Comment by rat-moonshine** [comment]
Thank you, for providing with the ANEs to test with. 

I confirm the issue, and this seems like a name parsing issue, which I'm looking into now.

**Comment by rat-moonshine** [comment]
This should be fix now. Please, check.

**Comment by piotrzarzycki21** [comment]
Your fix in general is working. ANE are being extracted, but I have huge problems with Moonshine. Josh's extension is crashing all the time. Lately I was trying to work with Moonshine a bit longer and it was almost unusable. I will try to find time to capture when I'm getting those problems. 

Overall I cannot run that application, cause it's complaining that one of the ANE do not exists. You can close this issue - I wold like to first get to the bottom of problems with crashing extension.

**Comment by rat-moonshine** [comment]
It'd be helpful if you can record some steps that is reproduceable, everytime. If this happens against any particular ane file, then you might want to investigate more with its type/rules/validity etc. Though, complaining on ANE does not exists - sounds strange, if you confirm the ANE does exists. 

One thing you can also try out, as I have mentioned you before, try to rename the ane file's extension to .zip and try manually unzipping it. That would also help you to look inside the ane file. 

If you would have any further problem with unpacking ane files, please reopen this.
