### ISSUE TITLE
Moonshine Java project detection and deletion problem

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#426]
Currently there are two new project templates as supplied by Moonshine:
- Java Gradle Project
- Java Maven Project

**Problems:**

1. Moonshine do not detect as a project folder when Open/Import operation to any of the above project types
2. Deletion of the above project types from Moonshine tree view, do not deletes the project or its files at all from the physical drive

**To-do:**

- [x] Implement detection process against Java project templates
- [x] Implement project deletion process against Java project templates

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 can you able to light on how the project configuration maintains against those Java projects - as there are no configuration file exists for projects as does for other project types.

**Comment by joshtynjala** [comment]
Moonshine looks for *pom.xml* or *build.gradle* to determine if it's one of the Java project types.

**Comment by rat-moonshine** [comment]
@joshtynjala , it is possible that any other project folder (i.e. Visual Editor Moonshine project) might consists of pom.xml or build.gradle file. How you suggest we can standardize a process in such scenario, which do not creates any side-effect for other project types, but effectively identify a Java Moonshine project. Please, advise.

**Comment by joshtynjala** [comment]
I could be wrong, but I think that Moonshine currently checks if a project matches other types before it checks for Java. However, you're probably right that it would be better to have a more foolproof detection that doesn't rely on a specific order.

After the Java language server initializes in a folder that contains *pom.xml* or *build.gradle*, it creates a few additional files: *.project*, *.classpath*, and a folder named *.settings*. We could possibly use these for a more robust detection.

**Comment by rat-moonshine** [comment]
At this moment, I see Moonshine do not detect an already created Java project - while import/open. 

It checks for few pre-defined configuration file types, i.e. _.as3proj_, _.veditorproj_, or configuration files exists while project created by Flash Builder IDE. 

On other project folders checking like, _.project_, _.classpath_ etc. I guess they creates after language-server initialized to the project folder (?) as you suggested, but first we need to able to import the folder as valid project folder to Moonshine, I guess..

**Comment by joshtynjala** [comment]
In `SplashScreen.getProjectBasedOnFileOption()` and `ProjectPlugin.openPreviouslyOpenedProject()`, I added calls to `model.javaCore.testJava()` to detect the Java project type after checks for other existing project types.

**Comment by rat-moonshine** [comment]
That looks helpful, I shall try to use the same test Java methods while open/import project, to test if an expected Java project, after other types' checking:

```
projectFileLocation = model.javaCore.testJava(projectFile);
if (projectFileLocation)
{
      project = model.javaCore.parseJava(projectLocation);
}
```

Thank you!

**Comment by rat-moonshine** [comment]
Adding the Java project test codes, open/import now works fine. However, the way it checks to determine if a Java project, can be manipulated if a folder do not has a known project configuration file (i.e. _.as3proj_, _.veditorproj_) and also have a _pom.xml_ or _build.gradle_ file. 

This may sound an unlike or invalid scenario, but per given feature (by Moonshine) to import a folder with source files as a valid project folder - breaks in this case. 

To give some more details on this, I tested by a Visual Editor type of project which consists of a _pom.xml_ file in its root folder as well. I deleted the _.veditorproj_ configuration file intentionally. Next, I tried to open/import that project in hope to 'import project with existing source' feature.

Since the _pom.xml_ file present to the root of the folder, import didn't ask me if I want to import the project with existing source feature, but imported the project (possibly) as a Java project instead. This reason unavailability of requisite flags to treat the imported project as a Visual Editor project, and opens all its files to text editor instead in visual editor.

I'm not sure if we really want to worry about such scenario immediately now, but this can be manipulated.

**Comment by piotrzarzycki21** [comment]
Not sure if it is important but in case of Visual Editor - I'm not running at all Language Server for those projects.

**Comment by joshtynjala** [comment]
We could check if a *src/main/java* folder exists too. I need to do something similar with Groovy because it also has a *build.gradle* file. For Groovy, I check for *src/main/groovy*.

**Comment by rat-moonshine** [comment]
I'm closing this as we don't have any other resolution on this for now.
