### ISSUE TITLE
Add JS Output path in project setting for Royale applications

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#427]
Royale framework allows configure path for JS compilation. In order to do that currently we need specify in **Additional compiler options** `-js-output=some directory`. 
Lack of that option in Moonshines UI limit our possibility to use option Clean Project - which simply trying to clean **Output Path** for SWF.

The idea is to add option **JS Output Path** to project **Settings** -> **Run**

![settings_output](https://user-images.githubusercontent.com/24554795/49859803-c1cdb200-fdf8-11e8-8be4-50aa1cd0f4c3.png)

**Comment by rat-moonshine** [comment]
A pre-defined path is already available for FlexJS type of project (I think RoyalJS is also similar to this) at [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/plugin/actionscript/as3project/vo/AS3ProjectVO.as#L64). Which is also uses in FlexJS/RoyalJS compilation-after-lunch event [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCJavaScriptPlugin.as#L648). 

Do you think, we can have some use of this, too?

**Comment by piotrzarzycki21** [comment]
If it is predefined it shouldn't be. If It's empty compiler have some default location where it is placed. We need to add UI which allows specify that path. 
I'm running into scenario where.
1. I specify in **Additional compiler options** -js-output=some custom direcoty
2. Build is running and outputting JS files there 
3. When I wanted to clean directory it will tries to clear those hard coded one which you have mention

That's why we need something which user can specify through UI.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine , @joshtynjala I think I would like to ask for a bit of help with some issue which I have faced. I have added option JS output path to project Settings -> Run.
![jsoutput_path](https://user-images.githubusercontent.com/24554795/51179454-ce489d00-18c5-11e9-8395-16ae19fdf5d1.png)

As you can see above example contains spaces in path. We are calling Royale compiler using CMD on Windows - in that case this kind of path is failing due to spaces. Solution for that is add apostrophe to command, so it would be:
`-js-output="D:\Work\projects\Prominic.NET\Moonshine Tests\Royale Projects\TestRoyaleProject"`

When I copy and paste such command to Windows CMD it's building my project without the problem. However when NativeProcess is taking care of it it's failing every time regardless I have apostrophes or not.

**Path without apostrophes:**
```
Compiling TestRoyaleProject
: SDK path: D:\Work\royale_ide\royale_nightly_js
: Using Royale Compiler codebase: D:\Work\royale_ide\royale_nightly_js
: Using Royale SDK: D:\Work\royale_ide\royale_nightly_js
: MXMLJSC
: -sdk-js-lib=D:\Work\royale_ide\royale_nightly_js\frameworks\js\Royale\generated-sources
: -load-config+=obj/TestRoyaleProjectConfig.xml
: -compiler.targets=JSRoyale
: -js-output=D:\Work\projects\Prominic.NET\Moonshine
: Tests\Royale
: Projects\TestRoyaleProject
: Error: unable to open 'Projects\TestRoyaleProject'.
: 
: 
: 
: 3.934599321 seconds
: Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
```

**Path with apostrophes:**
```
: Compiling TestRoyaleProject
: SDK path: D:\Work\royale_ide\royale_nightly_js
: Using Royale Compiler codebase: D:\Work\royale_ide\royale_nightly_js
: Using Royale SDK: D:\Work\royale_ide\royale_nightly_js
: MXMLJSC
: -sdk-js-lib=D:\Work\royale_ide\royale_nightly_js\frameworks\js\Royale\generated-sources
: -load-config+=obj/TestRoyaleProjectConfig.xml
: -compiler.targets=JSRoyale
: -js-output="D:\Work\projects\Prominic.NET\Moonshine
: Tests\Royale
: Projects\TestRoyaleProject"
: Error: unable to open 'Projects\TestRoyaleProject"'.
: 
: 
: 
: 3.942310752 seconds
: Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
```

Interesting thing is that NativProcess is always breaking into separate lines that path.  I have checked also that one in VSCode, but it's building without the problem project. 

[TestRoyaleProject.zip](https://github.com/prominic/Moonshine-IDE/files/2759545/TestRoyaleProject.zip)

I would be much appreciated for some thoughts on that.

**Comment by rat-moonshine** [comment]
Try using [this](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/utils/UtilsCore.as#L859) if this helps you.

You can try by using or without-using double-quotes surrounding the path value.

**Comment by piotrzarzycki21** [comment]
Thanks for pointing that @rat-moonshine - Unfortunately it doesn't work.

> You can try by using or without-using double-quotes surrounding the path value.

Both way are presented in above example.

**Comment by piotrzarzycki21** [comment]
I really would love to see some different method of using Royale/Flex stuff. Maybe we could switch completely somehow to language server API ?

**Comment by joshtynjala** [comment]
The AS3 & MXML language server provides a command to create a debug build of a project, managed using the Flex Compiler Shell (or a similar shell for other SDKs). In theory, Moonshine could use this command too. However, there are two limitations in the current implementation:

1) It cannot create a release build. However, this would be relatively simple to add.
2) It requires an asconfig.json file. While Moonshine has its own custom configuration provider for the language server's code intelligence, custom configuration providers aren't supported by the Quick Compile command yet. This would be a more challenging refactor.

**Comment by rat-moonshine** [comment]
> Maybe we could switch completely somehow to language server API ?

Well, I have different opinion on this, if this involve using of language-server jar file.

1. The current system is stable for our needs
2. I would prefer to keep the code-base to ActionScript side as much as possible than distributing to other languages like Java, AppleScript etc. and compile them separately - unless we have no choice
3. We would continue to keep the jar usage optional - because of the limitation in macOS to use jar/Java in sandbox application

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I don't agree with you on every point. 

> 1. The current system is stable for our needs

It's definitely not stable, cause whenever I would like to change it I'm absolutely scared doing that. Anything what is in those two classes `MXMLCJavaScriptPlugin`, `MXMLCPlugin `looks like spaghetti code which is hard to analyze and change. In fact we are concatenating strings and pushes all of that to CMD - it's not the first time when we have problems with command line launched from AS3. - Support for Payara server is great example - more than 4 days we have spend on resolving similar issue as I have here and we ended up using Maven to do that. :)
Look into that feature which I have added - it's simple and I have spend almost 2 days on above issue and there is not solution. Right now when user have his project in path with spaces he won't be able to build it, because of that - This is critical for me. Any solution for that is just workaround, not a real fix.  

> 2. I would prefer to keep the code-base to ActionScript side as much as possible than distributing to other languages like Java, AppleScript etc. and compile them separately - unless we have no choice

Justin asked us to support for more languages, so I cannot imagine that we are full filling requirements for building projects in some specific language in AS3 code - since we have language server which is responsible for that.  

> 3. We would continue to keep the jar usage optional - because of the limitation in macOS to use jar/Java in sandbox application

There is absolutely no problem with language server on mac, so I don't see that this point is valid one. 

Huge +1 from me on having that build using language server. @JoelProminic can you give some thoughts having my concerns in mind.

**Comment by piotrzarzycki21** [comment]
@joshtynjala if I correctly understand below:

> It requires an asconfig.json file. While Moonshine has its own custom configuration provider for the language server's code intelligence, custom configuration providers aren't supported by the Quick Compile command yet. This would be a more challenging refactor.

Are you saying that in order to feed that custom configuration we need asconfig.json for language server? What if I provide one from Moonshine and launch build through some command ? Let's say that I will create temporary some file with params and launch command - This is what I mean.

**Comment by rat-moonshine** [comment]
> Anything what is in those two classes MXMLCJavaScriptPlugin, MXMLCPlugin looks like spaghetti code which is hard to analyze and change. In fact we are concatenating strings and pushes all of that to CMD - it's not the first time when we have problems with command line launched from AS3. - Support for Payara server is great example - more than 4 days we have spend on resolving similar issue as I have here and we ended up using Maven to do that. :)
> Look into that feature which I have added - it's simple and I have spend almost 2 days on above issue and there is not solution. Right now when user have his project in path with spaces he won't be able to build it, because of that - This is critical for me. Any solution for that is just workaround, not a real fix.

I agree that there are spaghetti code but we received the original-codes to the IDE mostly in that way, and therefore had to fix/improve lot of other things also other than spending time fixing spaghetti code structure. But this is so-far stable if you don't agree, you can. 

For more 'newer' feature additions (like RoyalJS compilation), the current _NativeProcess_ implementation is not working - which I also seen as you reported. This is funny that although other Flex SDK compilation does work through _NativeProcess_ injection but RoyalJS (I wonder what this SDK has missing). But that is not our point of interest at this moment certainly - if we require RoyalJS, we need to find a solution then, be it by _NativeProcess_ or by Java process. But I personally continue to prefer if things can be keep-able at AS side only, that is my preference. 

Justin asked for more language support - I never oppose that either, so let not mistake on this point. For code-completion, we have no other choice but to depend on Java only and that is final, and also clear truth to me. I even can't dream of having these functionalities out of AS framework only! But supporting language support means porting existing everything to Java - does not same to me, and my preference differs in that place, if you can understand. 

> There is absolutely no problem with language server on mac, so I don't see that this point is valid one.

Here you also didn't get gist of my saying. To run the language server we need Java in system; in macOS sandbox situation, the application can not access the Java by itself from beginning. **User needs to provide acceptance to let the application use Java** by performing certain steps. This do not comes in-box, user can even reject to give that permission - of course, we can tell user by big-bad words that **nothing** will work unless you permit us to use Java. So, this part is optional which I tried to say, and I do know there is no problem running .jar file on macOS.

Last but not least, all these thoughts of course my only, if certain decision will be taken on these regards, we'll anyway need to follow that.

**Comment by joshtynjala** [comment]
> Are you saying that in order to feed that custom configuration we need asconfig.json for language server? What if I provide one from Moonshine and launch build through some command ? Let's say that I will create temporary some file with params and launch command - This is what I mean.

Yes, this would work very well! Actually, I just realized that we'd be able to launch asconfigc.jar, the same tool that I use in VSCode to build projects. It can compile both debug and release builds, and even package AIR apps.

**Comment by joshtynjala** [comment]
> in macOS sandbox situation, the application can not access the Java by itself from beginning. User needs to provide acceptance to let the application use Java by performing certain steps. This do not comes in-box, user can even reject to give that permission - of course, we can tell user by big-bad words that nothing will work unless you permit us to use Java. So, this part is optional which I tried to say, and I do know there is no problem running .jar file on macOS.

It's worth mentioning that this is required only for the Mac App Store version of Moonshine. Outside of the app store, there is no sandbox, so it would be easy to make everything just work. Developer tools provided through the app store usually have a terrible user experience, for this reason.

We're only making this hard on ourselves by insisting that Moonshine is available on the app store. Developers are used to downloading most of their tools from outside the app store.

**Comment by piotrzarzycki21** [comment]
> Yes, this would work very well! Actually, I just realized that we'd be able to launch asconfigc.jar, the same tool that I use in VSCode to build projects. It can compile both debug and release builds, and even package AIR apps.

@joshtynjala is it asconfigc.jar separated or it is part of codecompletion.jar which is being added to Moonshine ?
In order to use approach of temporary creation of asconfig.json and command launch -
1. Do I need something more than we currently have in Moonshine ? 
2. What would be the command in order to do so ? 
3. Can I listen to some event for taking progress of build ?

**Comment by piotrzarzycki21** [comment]
> > in macOS sandbox situation, the application can not access the Java by itself from beginning. User needs to provide acceptance to let the application use Java by performing certain steps. This do not comes in-box, user can even reject to give that permission - of course, we can tell user by big-bad words that nothing will work unless you permit us to use Java. So, this part is optional which I tried to say, and I do know there is no problem running .jar file on macOS.
> 
> It's worth mentioning that this is required only for the Mac App Store version of Moonshine. Outside of the app store, macOS apps don't need to be sandboxed, so it would be easy to make everything just work. Developer tools provided through the app store usually have a terrible user experience, for this reason.
> 
> We're only making this hard on ourselves by insisting that Moonshine is available on the app store. Developers are used to downloading most of their tools from outside the app store.

I think it's worth to give Justin your thoughts and concerns.

**Comment by joshtynjala** [comment]
> I think it's worth to give Justin your thoughts and concerns.

I have told Justin my thoughts on the user experience problems with developer tools in the Mac App Store in the past, but I could not seem to convince him of the importance. This may require more than one of us to work together, or for some users to get annoyed by it and complain.

**Comment by joshtynjala** [comment]
> is it asconfigc.jar separated or it is part of codecompletion.jar which is being added to Moonshine ?

asconfigc.jar is a dependency of language-server.jar in the VSCode version, so it should be fully compiled into codecompletion.jar.

> Do I need something more than we currently have in Moonshine ?

I've been considering splitting up codecompletion.jar back into its separate JAR files due to various quirks that I've encountered, and because it may be easier to update some things when I release a new version of the as3mxml language server. Additionally, since the Java and Groovy language servers have their own folders, I'd like to move the as3mxml language server into its own folder too, for consistency. If I make this change, I will ensure that asconfigc.jar is included and easy to access.

> What would be the command in order to do so ?

This is the basic command:

``` sh
java -jar path/to/asconfigc.jar --sdk path/to/sdk --debug=true --project path/to/asconfig.json
```

All paths will be relative to the folder that contains asconfig.json.

There is also an --air command line option for packaging AIR apps, and a couple of other options that could be useful for things like ANEs and cleaning a project.

> Can I listen to some event for taking progress of build ?

The output from any tools that asconfigc executes, including the compiler, is written to the console normally. Assuming that we currently display the console output from the compiler, we can keep doing the same thing with asconfigc.

**Comment by joshtynjala** [comment]
I just updated the as3mxml language server to v0.17.1. In the process, I also split up codecompletion.jar, so asconfigc.jar is now available as a standalone file.

All of the as3mxml language server files have been moved here:

https://github.com/prominic/Moonshine-IDE/tree/master/ide/MoonshineSharedCore/src/elements/as3mxml-language-server

**Comment by piotrzarzycki21** [comment]
I'm closing that one cause this feature has been added. More work it would be an improvement.
