### ISSUE TITLE
Extract logic for Visual Editor XML conversion to xHTML to separate library

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#428]
As part of this task I will move all logic related to conversion from Visual Editor XML to xHTML to separate library. It will be places in following repository [VisualEditorConverterLib](https://github.com/prominic/VisualEditorConverterLib). 

Library will be used by Visual Editor and whatever other entities which will provide valid format of XML to it. 

**Sub-goal (Components)**

- [x] Div (@piotrzarzycki21)
- [x] RootDiv (@piotrzarzycki21)
- [x] OutputLabel (@rat-moonshine)
- [x] TextInput (@piotrzarzycki21)
- [x] Button (@piotrzarzycki21)
- [x] InputMask (@rat-moonshine)
- [x] InputNumber (@rat-moonshine)
- [x] InputTextarea (@rat-moonshine)
- [x] TextEditor (@rat-moonshine)
- [x] SelectedBooleanCheckbox (@piotrzarzycki21)
- [x] SelectOneRadio (@piotrzarzycki21)
- [x] SelectOneMenu (@rat-moonshine)
- [x] SelectOneListbox (@piotrzarzycki21)
- [x] AutoComplete (@piotrzarzycki21)
- [x] TabView (@piotrzarzycki21)
- [x] Tree (@rat-moonshine)
- [x] DataTable (@rat-moonshine) [Not usable in Visual Editor as is]
- [x] Fieldset (@rat-moonshine)
- [x] Include (@rat-moonshine)
- [x] Grid (@piotrzarzycki21) [Not usable in Visual Editor as is]
- [x] PanelGrid (@rat-moonshine) 
- [x] Calendar (@piotrzarzycki21)
- [x] MainApplication (@piotrzarzycki21)

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 please let me know, if I need to join-hand to speed up the process.

**Comment by piotrzarzycki21** [comment]
That's possible if I reach the point when at least one component will be fully converted using extracted code. I will let you know.

**Comment by rat-moonshine** [comment]
@JoelProminic reported a strange behavior he noticed while testing latest builds from Bamboo, last night. He reported that an extra `Div` adds to the converted xhtml file as he compared below:

![image](https://user-images.githubusercontent.com/24370870/50325155-3b585500-0509-11e9-8d18-5bbcc296da2b.png)

He compared the converted one (right-side) through CLI with Moonshine in-app conversion - he pointed the extra `Div` addition before the `Button` components.

However, with latest code-builds, I couldn't able to reproduce this in Windows, or later on macOS.

**Comment by piotrzarzycki21** [comment]
I have fixed issue with Div duplication. @rat-moonshine I have added as well event `ConverterEvent.UNKNOWN_CONVERSION_ITEM` which notifies you when someone provide some unknown tag in VE XML. You may wanna register on it and log some message. 
I noticed that we also have to add handling of MainApplication from VE XML. - Currently conversion files with that tag may not be possible.

**Comment by rat-moonshine** [comment]
I able to reproduce the problem from @JoelProminic reported [last night](https://github.com/prominic/Moonshine-IDE/issues/428#issuecomment-449248182). 

@piotrzarzycki21 please, look into this. 

This problem is not applicable to XML file starts with `MainApplication` tag but `RootDiv`.

This is the simple example XML file as generated by Moonshine:
```
<mockup>
  <RootDiv width="700" height="450" class="flexHorizontalLayout flexHorizontalLayoutLeft flexHorizontalLayoutTop" wrap="false">
    <Button width="100" height="30" disabled="false" value="Foo" title="" isCommandButton="false" actionListener=""/>
    <Button width="100" height="30" disabled="false" value="Bar" title="" isCommandButton="false" actionListener=""/>
    <OutputLabel width="100" height="30" value="Test" indicateRequired="false"/>
  </RootDiv>
</mockup>
```
When converted through XHTMLConverterCLI, it adds an extra Div as showing in following output (this do not occur when conversion in-Moonshine):
```
<h:body>
    <div class="flexHorizontalLayout flexHorizontalLayoutLeft flexHorizontalLayoutTop" style="width:700px;height:450px;">
      **<div style="width:700px;height:450px;" class="flexHorizontalLayout flexHorizontalLayoutLeft flexHorizontalLayoutTop">**
        <p:button style="width:100px;height:30px;" disabled="false" value="Foo" title=""/>
        <p:button style="width:100px;height:30px;" disabled="false" value="Bar" title=""/>
        <p:outputLabel style="width:100px;height:30px;" value="Test"/>
      **</div>**
    </div>
  </h:body>
```

**Comment by piotrzarzycki21** [comment]
I didn't say that Joel's issue is related to MainApplication. I knew from the beginning that is related to RootDiv and I was mention that on our meeting :) It should be fixed by that commit https://github.com/prominic/VisualEditorConverterLib/commit/ce29b1b97b16255acd8d6695ae39d67a5c0d5f5b Make sure that your app is up to date.

**Comment by rat-moonshine** [comment]
The update with Div duplication seems breaking conversion against file with tag `MainApplication`:

XML:
```
<mockup>
  <MainApplication title="" width="700" height="450" class="flexHorizontalLayout flexHorizontalLayoutLeft flexHorizontalLayoutTop" wrap="false"/>
</mockup>
```
Conversion output:
```
[info] Starting the conversion..
[info] Unknown conversion item: MainApplication
[error] Error while XML conversion: TypeError: Error #1009
	at utils::MainTagCodeUtils$/getParentContent()
	at surface::SurfaceMockup/toCode()
	at converter::Converter/fromXMLOnly()
	at XHTMLConverterCLI/sendForConversion()
	at MethodInfo-5()
	at MethodInfo-31()
[info] Application has been closed.
```

However, file with tag `RootDiv` pass the conversion well.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine MainApplication has been added to the components and it should be handled properly now.

**Comment by piotrzarzycki21** [comment]
All components has been moved. @rat-moonshine do you have anything to add to that list ?

**Comment by rat-moonshine** [comment]
While running PanelGrid conversion, it prints following warning to the log file:

```
[info] Starting the conversion..
[info] Unknown conversion item: Column
```

However, the conversion succeeds, but the above print out can cause unnecessary confusion. @piotrzarzycki21 please check if you can do anything about it. This looks like <Column/> from the PanelGrid XML turns to unexpected ActionScript class [search](https://github.com/prominic/VisualEditorConverterLib/blob/master/src/converter/Converter.as#L92).

**Comment by rat-moonshine** [comment]
While testing latest conversion, @JoelProminic pointed some differences in conversion between in-Moonshine and CLI application - as following code snippet shown the difference between two:

```
// in-Moonshine
< <p:selectOneRadio style="width:230px;height:21px;" value="">
< <f:selectItem itemLabel="One" itemValue=""/>
< <f:selectItem itemLabel="Two" itemValue=""/>
// by-CLI
> <p:selectOneRadio style="width:230px;height:21px;">
> <f:selectItem itemLabel="One" itemValue="null"/>
> <f:selectItem itemLabel="Two" itemValue="null"/>
```
While testing these in a fresh Visual Editor PrimeFaces file, having most of the `value`/`var` fields blanks, I couldn't able to reproduce this anymore by CLI conversion. Following is a small code snippet for SelectOneRadio, but this valid for other likewise components, too.

```
<p:selectOneRadio style="width:230px;height:21px;" layout="grid" columns="2">
        <f:selectItem itemLabel="Title 252" itemValue=""/>
        <f:selectItem itemLabel="Title 252" itemValue=""/>
</p:selectOneRadio>
```

Point to be noted that while in-Moonshine it prints `value=""` to `<p:selectOneRadio` tag, the field do not generates while XML generation, that is by intention.

**Comment by piotrzarzycki21** [comment]
> While running PanelGrid conversion, it prints following warning to the log file:
> 
> [info] Starting the conversion..
> [info] Unknown conversion item: Column
> However, the conversion succeeds, but the above print out can cause unnecessary confusion. @piotrzarzycki21 please check if you can do anything about it. This looks like <Column/> from the PanelGrid XML turns to unexpected ActionScript class search.

I have fixed above case and covered it by unit tests. :)

**Comment by piotrzarzycki21** [comment]
I think I covered problems with selectone components. I have changed so those components won't output `value` or `itemValue` if any value wasn't provided. Once we integrate library with current Visual Editor all that fixes will be available as well.
