### ISSUE TITLE
IDE alerted twice while deleting a project

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#43]
Deleting an opened project from sidebar, alerts twice:

![image](https://user-images.githubusercontent.com/24370870/31533616-cab835a2-b010-11e7-9892-76b88d8fe7b4.png)
![image](https://user-images.githubusercontent.com/24370870/31533619-d2162b1a-b010-11e7-9ee1-a1e191d7c729.png)

**Comment by JoelProminic** [comment]
I tested this on Mac OS and Windows, and it seems to be fixed.
