### ISSUE TITLE
Component shows by its 'label' rather than 'type' in Organizer

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#433]
- Create a new Visual Editor PrimeFaces project
- Add two button on to the editor stage
- Change the label of both buttons to Foo and Bar
- Toggle to the Organizer
- Under `Stage` it'll show the added components are as `Button` - which is the expected behavior
- Close the editor file
- Re-open the file
- Organizer now shows the button components by their _label_ rather than their _type_

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I don't know how it happened cause it's not visible in git history, but your last two commits https://github.com/prominic/Moonshine-IDE/commit/57628b9fd67a4c0b201dd8de173a6e126d8d3626 and https://github.com/prominic/Moonshine-IDE/commit/2a22a38717ba08052b8995e91ebe04c4b27ba807 completely reverted Josh's changes https://github.com/prominic/Moonshine-IDE/commit/0dd259434c87c2fc1ff761b22b0a6c071e9b6dfa, https://github.com/prominic/Moonshine-IDE/commit/11850833c639f1d0646bfdf01eb3cbcbd03f3a49, https://github.com/prominic/Moonshine-IDE/commit/f7662e7adbf0b06be690f00a95ad99aabd36975b. Try to revert that one to this commit https://github.com/prominic/Moonshine-IDE/commit/0dd259434c87c2fc1ff761b22b0a6c071e9b6dfa and than add your changes.

**Comment by rat-moonshine** [comment]
Can I ask you to do that for me (?) I often found myself messed-up sometime with Git commits. I don't want to mess any further, if already we have a mess to fix.

**Comment by piotrzarzycki21** [comment]
Ok I will do that!
