### ISSUE TITLE
Integrate VisualEditorConverterLib with Visual Editor

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#438]
As part of that issue we need to adjust code of Visual Editor in order to use [VisualEditorConverterLib](https://github.com/prominic/VisualEditorConverterLib).

Following components need to be changed in order to finish integration:
- [x] Div 
- [x] RootDiv
- [x] OutputLabel
- [x] InputText
- [x] Button
- [x] InputMask
- [x] InputNumber
- [x] InputTextarea
- [x] TextEditor
- [x] SelectedBooleanCheckbox
- [x] SelectOneRadio
- [x] SelectOneMenu
- [x] SelectOneListbox
- [x] AutoComplete
- [x] TabView
- [x] Tree
- [x] DataTable
- [x] Fieldset 
- [x] Include
- [x] Grid 
- [x] PanelGrid 
- [x] Calendar

**Comment by atinprominic** [comment]
Hi Piotr,
 
For any converted project, when I open the xhtml file, its shown blank and I am getting the below error in Moonshine:
 
Also attaching the screenshot.
 
: Error #1009
: TypeError: Error #1009
:     at converter::Converter/itemFromXML()
:     at components.primeFaces::Div/fromXML()
:     at view.primeFaces.surfaceComponents.components::Div/fromXML()
:     at view.primeFaces.surfaceComponents.components::RootDiv/fromXML()
:     at converter::Converter/itemFromXML()
:     at converter::Converter/fromXML()
:     at utils::EditingSurfaceReader$/fromXML()
:     at view::EditingSurface/fromXML()
:     at view::VisualEditor/loadFile()
:     at actionScripts.plugins.ui.editor::VisualEditorViewer/createVisualEditorFile()
:     at actionScripts.plugins.ui.editor::VisualEditorViewer/openHandler()
:
: Click here to Report a Bug
 
 
![screen shot 2019-01-29 at 11 44 03 am](https://user-images.githubusercontent.com/34882311/51889308-39fb3180-23bf-11e9-95d6-9aae2ab5381b.png)


Some more behaviours I noted, in this version of Moonshine:
 1. When I create a new project and then using file system delete the xhtml file, it should automatically create it from xml file. But its not doing that.
2. The error reported is occurring only for the converted primefaces project only. If I create a new Moonshine project then this behaviour is not observed.
 
 
 
Thanks
Atin

**Comment by piotrzarzycki21** [comment]
Ok the issue here is that xml counterpart of xHTML file is not deleted. - It should be - It's a bug. 

If you are referring more here to putting xml to visualeditor-src and later translate them without opening - that's something which is not working yet or I'm not sure whether will be so soon. :)

**Comment by piotrzarzycki21** [comment]
@atinprominic are you referring to that issue #415?

**Comment by piotrzarzycki21** [comment]
@atinprominic I just tested deleting xhtml file from Moonshine and everything is working fine. It deleting xhtml file along with it's counterpart in visualeditor-src folder. - I don't understand your problem - provide me screen cast - here or trough email.

**Comment by atinprominic** [comment]
@piotrzarzycki21 I think you are deleting using Moonshine IDE. Please delete xml file from OS filesystem.

**Comment by atinprominic** [comment]
@piotrzarzycki21 
I tested the latest build but unfortunately it still has issues.

It successfully opens and shown the xhtml file which I open after first launching the Moonshine. But Its throwing the same error when I open any xhtml file after that.


Please let me know if that makes sense and you understood the issue.

Thanks
Atin

**Comment by atinprominic** [comment]
@piotrzarzycki21 
When we click on the button - "open in editor" then it doesn't open the subform in another window. Please refer to below screenshot:

![image](https://user-images.githubusercontent.com/34882311/52000425-14674880-24e3-11e9-8a77-6e06b62764c3.png)


Thanks
Atin

**Comment by piotrzarzycki21** [comment]
I have merged stuff to master. I will handle above issue as a separate one.
