### ISSUE TITLE
Auto namespace insertion out of place by 1 character

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#44]
If I choose to add a Text tag, Moonshine auto inserts a new namespace "ns2" into the Application tag.

This is great except that it places the new text one character to the left of where it should be.

Application tag before choosing Text tag

<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/flexjs/basic"
                xmlns:ns="library://ns.apache.org/flexjs/html5"
		xmlns:ns1="org.apache.flex.html.beads.*" initialize="init()">

Application tag after choosing Text tag

<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
		xmlns:js="library://ns.apache.org/flexjs/basic"
		xmlns:ns="library://ns.apache.org/flexjs/html5"
		xmlns:ns1="org.apache.flex.html.beads.* xmlns:ns2="org.apache.flex.svg.*"" initialize="init()">

Doug

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I think we could remove that namespace xmlns:ns="library://ns.apache.org/flexjs/html5" -> It has not been used at all.

**Comment by rat-moonshine** [comment]
> @rat-moonshine I think we could remove that namespace xmlns:ns="library://ns.apache.org/flexjs/html5" -  It has not been used at all.

Okay. I probably copied that from some FlexJS template. I can remove that.

**Comment by rat-moonshine** [comment]
> If I choose to add a Text tag, Moonshine auto inserts a new namespace "ns2" into the Application tag.

@doug777 can you please help with some steps how you auto-inserts namespace 'ns2' in Moonshine?

**Comment by JoelProminic** [comment]
@piotrzarzycki21, is the "library://ns.apache.org/flexjs/html5" namespace no longer commonly used in FlexJS?   If it is a namespace that users will generally want to use, then it would make sense to keep it in the template, even if it is not directly used by the template code.

That said, if the namespace auto-insertion works well, then the users could easily add it back anyway.

**Comment by piotrzarzycki21** [comment]
@JoelProminic ,

The most common namespace is "Basic" (library://ns.apache.org/flexjs/basic), which has been shared with package [HTML ](https://github.com/apache/royale-asjs/tree/develop/frameworks/projects/HTML/src/main/flex/org/apache/flex/html)- This package contains pure html components.

 Namespace/package "[HTML5](https://github.com/apache/royale-asjs/tree/develop/frameworks/projects/HTML5/src/main/flex/org/apache/flex/html5)" contains components like "List", "RadioButton" etc. where each of them just extend controls from "Basic", but don't add any new logic. Currently there is no reason have it as default for new projects, cause everything what is inside that package exists in "Basic". I have no idea why it was being created.

Piotr

**Comment by JoelProminic** [comment]
I was able to reproduce @doug777's problem like this:
1. Create a new FlexJS Project
2. Create a new line in the <js:Container and type "<Text"
3. "Text" appears in the auto-completion UI.  Hit Enter
4. Moonshine automatically adds the namespace:

![2017_10_13__namespaceautoinsertion](https://user-images.githubusercontent.com/24532731/31555520-f1c82ea4-b006-11e7-8087-85550656cfc4.jpg)

**Comment by joshtynjala** [comment]
I think that this issue will be fixed the next time that I update Moonshine with the latest language-server code from vscode-nextgenas.

**Comment by JoelProminic** [comment]
I ran some tests in the 1.6.1 release candidate, and this seems to work well:
- Adding a single namespace
- Adding multiple namespaces in a row (eventually this causes the current interface to scroll)
- Adding another namespace after reformatting the previous entries to be one per line (the new entry is added to the last namespace line)
