### ISSUE TITLE
Prequisites to a complete bundled Moonshine IDE system distributable without App Store limitations

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#444]
#### Questions:
1. Are we legally allowed to bundle all of these items into our download?
2. How do we want to design the distributed SDKs in the application directory. For example:
prereqs/svn
prereqs/maven
3. Can we distribute software that we compile that is no longer separately developed:
- Away3D
4. How big does Moonshine become if we bundle in all of the following large independent projects:
- OpenJDK
- Payara (from Maven but we should have our own)
- Flex SDK
- Royale SDK
- ANT
- Maven
- Git
- SVN
- Feathers
5. Since we can't distribute Adobe AIR without proper distributorship, how we want to have this be used in Moonshine?

**Comment by rat-moonshine** [comment]
Sizes for the SDKs in uncompressed format:
SDK | Size (uncompressed) | Size (compressed (.zip))
------------- | ------------------------- | -----------------------------
OpenJDK | - awaiting review - | - awaiting review -
Payara (from Maven but we should have our own) | - awaiting review - | - awaiting review -
Flex SDK 4.16.1 | 106 MB (without AIR), 1.20 GB (after installed by installer with AIR) | 69 MB (without AIR)
Royal 0.9.4 | 161 MB | 63 MB
Apache Ant 1.10.5 | 37 MB | 8.6 MB
Git 2.20.1 | - awaiting review - | 44 MB (normal), 40 MB (thumbdrive/portable edition - could be suitable for distribution as bundle)
Apache Subversion 1.11.1 | - awaiting review - | 11 MB
Feathers | - awaiting review - | - awaiting review -

If we want to distribute compressed SDK, then we probably have less-weighty installer, we can expand those SDKs during first-time application start to:
/User/AppData/<moonshine.id>/<sdk.name> (in Windows)
application-storage-directory (in OSX)

I'm not sure how updating/overwriting will smooth when a new SDK version out, in this expanded way though, this needs to be check.

**Comment by rat-moonshine** [comment]
> Are we legally allowed to bundle all of these items into our download?

SDK | Yes/No | Thoughts
------------- | ------------------------- | -----------------------------
OpenJDK | - awaiting review - | -
Payara (from Maven but we should have our own) | - awaiting review - | -
Flex SDK | - awaiting review - | -
Royal | - awaiting review - | -
Adobe AIR | No | Requires distributorship (https://www.adobe.com/in/products/air/sdk-agreement.html)
Apache Ant | - awaiting review - | -
Apache Maven | - awaiting review - | -
Git 2.20.1 | - awaiting review - | -
Apache Subversion 1.11.1 | - awaiting review - | -
Feathers | - awaiting review - | --

**Comment by piotrzarzycki21** [comment]
@rat-moonshine done - I'm wondering whether those sizes won't be a bit different on Mac/Windows.

**Comment by rat-moonshine** [comment]
The different between Windows installer and Mac installer size will remain; Compression while containing in a installer may vary based between the platform, but the differences probably remain between the amount of difference we use to see between EXE and PKG.

**Comment by rat-moonshine** [comment]
### More bundling tests with ADT

SDKs | Time Taken | Completed | Output
----------- | ----------- | ------| ----------------------------
Flex + Royale + Feathers | 40 Minutes | With Error | CompileSWFWindowsSelfSignedPackage:
     [echo] Self-signed Process Running
     [java] unexpected failure: Platform conversion failed. Process exited with error 5. Output was "Conversion complete
     [java] [ErrorEvent type="error" bubbles=false cancelable=false eventPhase=2 text="Error #2038" errorID=2038]
     [java] "
     [java] java.io.IOException: Platform conversion failed. Process exited with error 5. Output was "Conversion complete
     [java] [ErrorEvent type="error" bubbles=false cancelable=false eventPhase=2 text="Error #2038" errorID=2038]
     [java] "
     [java]     at com.adobe.air.nai.NativePackager.conversionFail(NativePackager.java:279)
     [java]     at com.adobe.air.nai.NativePackager.invokePlatformConversion(NativePackager.java:260)
     [java]     at com.adobe.air.nai.NativePackager.createPackage(NativePackager.java:133)
     [java]     at com.adobe.air.ADT.parseArgsAndGo(ADT.java:696)
     [java]     at com.adobe.air.ADT.run(ADT.java:485)
     [java]     at com.adobe.air.ADT.main(ADT.java:535)

BUILD FAILED
G:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\build\build-lib.xml:211: The following error occurred while executing this line:
G:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\build\build-lib.xml:291: The following error occurred while executing this line:
G:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\build\build-lib.xml:297: Java returned: 5

Total time: 39 minutes 8 seconds

**Comment by rat-moonshine** [comment]
**Q. Will Moonshine able to execute binaries if bundled within in non-sandbox, without having a restriction of running from ~/Downloads in OSX?**

I ran some tests by bundling Flex SDK (along with AIR, for this test only) in Moonshine; After being compiled the SDK path looked like this: `Moonshine.app/Contents/Resources/defaultSDKs/Flex_4.16.1_AIR_28.0`. Did made some changes in Moonshine code to carry out this particular test, and list the SDK to its SDK list. 

I able to run a Flex desktop project using the bundled SDK without any problem in non-sandbox build.

**Comment by rat-moonshine** [comment]
I'm closing this issue as this is not relevant anymore.
