### ISSUE TITLE
feathers android compile ant fail and windows 7 dosnt show starling exe components 

### ISSUE THREAD

**Issue by yoel123** [prominic/Moonshine-IDE#447]
two issues.

when I try to compile a  feathers mobile project i get the following error:

`: compileAPKProject:
: 
:      [java] dx tool failed:
: 
: BUILD FAILED
: C:\moonshine\bbbNewFeathersMobileProject\build\build.xml:146: Java returned: 17
: 
: Total time: 20 seconds
: 
: BUILD FAILED
: C:\moonshine\bbbNewFeathersMobileProject\build\build.xml:146: Java returned: 17
: 
: Total time: 20 seconds
: FSCH exit code: 17`

according to this link:
https://help.adobe.com/en_US/air/build/WSBE9908A0-8E3A-4329-8ABD-12F2A19AB5E9.html

when adt. jar returns 17 it means: "Device packaging tool failed.
The package could not be created because expected operating system components are missing."

I have no idea what that means I just know as3.

second issue

feathers exe project. compiles and runs with no errors.
the only problem is that when I install it, it doesn't show the hello world btn component and the red quad I add.
but it dose show the brown bg.
also in the simulator, there is no problem.

please help.

**Comment by piotrzarzycki21** [comment]
Hey @yoel123 we haven't released new version for some time, but for a beginning could you try [dev](https://moonshine-ide.com/downloads/releases/dev/windows/) version and try again. It contains all fixes. I hope we will soon release it.

**Comment by yoel123** [comment]
sure thank you, I will let you know the result.

I hope this project lives and will grows.  I wanted to come back to as3 for years. it's way better than js or lua (corona sdk dosnt have proper oop).

im not sure my problem is the ide but ant .lets see.

**Comment by piotrzarzycki21** [comment]
We are not going to disappear - believe me :) Just shot us with whatever problems we have and we try to help you and resolve issues :)

**Comment by rat-moonshine** [comment]
Hey @yoel123 , thank you for raising your problems with us. 

On your first problem (Ant packaging issue to Feathers mobile project), the error is a bit confusing 'expected operating system components are missing' - I'm not sure at this moment what cause you that error. Did you tried by simple Feathers mobile project that created by Moonshine or, you added something more to the project at your side? When I tried to run the Ant build script by creating a new Feathers mobile project, I couldn't able to reproduce the error and packaging completed well. I used my stocked Feathers 3.3.0 SDK with AIR 26.0.

On your second problem (Ant packaging issue to Feathers desktop project), I confirm. We'll investigate on this.

**Comment by yoel123** [comment]
for the first problem.
I downloaded feathers sdk (latest) installer and installed it. I installed ant apache (latest binaries).
installed moonshine (latest and later dev). in settings, I connected everything to moonshine.
created a fresh desktop and mobile projects no changes.
I got the "dx failed" error and the return 17 from line 146 on build xml.
I checked the build xml and found it refers to adt.jar. I searched the web and found adobe errors list for adt. it appears that 17 mean: "Device packaging tool failed.
The package could not be created because expected operating system components are missing."
you can see for yourself from the link I provided.

a tool shouldn't be that hard to use(its a scripting language for people who used as3...), although I love as3. corona sdk installation is  a 100 times simpler and can compile to exe or apk with no problem. as I created a few projects with it. I think I will return to it, they don't have a proper oop at all, but it works.
I wasted a day of my life thinking I could use flashpunk again (the starling port).

**Comment by rat-moonshine** [comment]
I'm sorry hearing your experience in recent times with AS3, @yoel123 . 

`ADT` is use to for packaging an installer as supplied by the Adobe AIR SDK. I'm not sure how the recent Feathers SDK affect along with latest AIR SDK on packaging an installer, or it bring some other dependencies which is unknown to us at this moment. This is something we would like to investigate, though.

If you don't mind, can you tell us some more on how simpler you were expecting SDK installation in Moonshine (compared to your experience with Corona) - so might work on to make it better!

**Comment by piotrzarzycki21** [comment]
@yoel123 Could you please tell what version of Adobe Air did you use ? 

@rat-moonshine As I understand from your last description you are able to reproduce only one bug from raised by @yoel123 ?

**Comment by yoel123** [comment]
edit: I also tried running as admin as that is the reason for errors with a lot of apis I used in the past (almost 90% of the time). didn't work this time.

**air version: air32.0** 

I'm not sure you can do the same as corona as you relay on external libs and tools.

for corona its one installer and your good to go. my antivirus once deleted a corona file which caused a problem. I just reinstalled with two clicks and it solved it, I don't even need to worry about screen size setting. it auto resizes it (or something else I tested on smartphone tablet and pc and the app fits all). I read that starling doesn't have this out of the box.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine please try Feathers with Air 32.

**Comment by rat-moonshine** [comment]
> @rat-moonshine As I understand from your last description you are able to reproduce only one bug from raised by @yoel123 ?

I commented my findings on both the issues.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine 

1) I downloaded Feathers with Adobe Air 32.
2) I have created Hellow world Feathers mobile app
3) I did buid using ANT script
4) Copied *.apk file to my phone - I have OnePlus 5t.  

I was able to reproduce problem described by @yoel123. I see blank brown page without button. 

**Screenshot:**
![screenshot_20190208-124223](https://user-images.githubusercontent.com/24554795/52476596-5ce7cb80-2b9f-11e9-8fae-6686dec4acc0.jpg)

**Comment by rat-moonshine** [comment]
Thanks for giving this a try, Piotr. I think your test result may raise this as new issue but which is similar to the reported second issue ) In the reported second issue same thing discovered in case of desktop installer. 

But it seems you have not able to reproduce the Ant build issue reported, as well.

**Comment by yoel123** [comment]
I tried remaking the hello world example but something went wrong:

https://github.com/yoel123/starling-feathers-FAIL/

**Comment by piotrzarzycki21** [comment]
@yoel123 what exactly went wrong ?

**Comment by piotrzarzycki21** [comment]
@joshtynjala have you seen such problems with Feathers, where after build apk and deploying it on phone I can see only blank screen - instead Button ?

**Comment by joshtynjala** [comment]
I'm not aware of any issues with how the Feathers SDK integrates with AIR. I'm sure that some kind of runtime error would be detected if you connected the app to the debugger while it's running on Android. As far as I know, Moonshine can't do that yet, but other IDEs can.

**Comment by joshtynjala** [comment]
It's possible that some of my changes in Feathers SDK 4.0 caused new issues in release builds. I probably only tested in the simulator. It might be worth trying the previous version of Feathers SDK to see if there's a difference.

**Comment by piotrzarzycki21** [comment]
> It's possible that some of my changes in Feathers SDK 4.0 caused new issues in release builds. I probably only tested in the simulator. It might be worth trying the previous version of Feathers SDK to see if there's a difference.

@joshtynjala I have downloaded Feathers 3.5 with Adobe Air 32 and got following exception during build Hello World app which you can create with Moonshine. Screen becomes in that case blank.

```
Compiling NewFeathersMobileProject
: Sending to mxmlc: mxmlc -load-config+=obj/NewFeathersMobileProjectConfig.xml -static-link-runtime-shared-libraries=true +configname=airmobile -debug=true -o bin-debug/NewFeathersMobileProject.swf
: Apache Flex Compiler SHell (fcsh)
: Version 4.14.0 build 20180621
: Copyright 2015 The Apache Software Foundation.
: 
: (fcsh) 
: FSCH target: 1
: fcsh: Assigned 1 as the compile target id
: Loading configuration file D:\Work\feathers_3.5_adobe_air_32\frameworks\airmobile-config.xml
: Loading configuration file D:\Work\projects\Prominic.NET\MoonshineTests\Feathers\NewFeathersMobileProject\obj\NewFeathersMobileProjectConfig.xml
: bin-debug/NewFeathersMobileProject.swf (1279554 bytes)
: (fcsh) 
: Project Build Successfully.
: Launching application NewFeathersMobileProject.
: Application NewFeathersMobileProject started.
: [Starling] Context ready. Display Driver: DirectX11
: VerifyError: Error #1014: Class feathers.controls::Toast could not be found.
: 
: 	at Main/addedToStageHandler()[D:\Work\projects\Prominic.NET\MoonshineTests\Feathers\NewFeathersMobileProject\src\Main.as:50]
: 	at starling.events::EventDispatcher/invokeEvent()[C:\Users\josht\Development\feathers\feathers-sdk\frameworks\projects\starling\Starling-Framework\starling\src\starling\events\EventDispatcher.as:156]
: 	at starling.events::EventDispatcher/dispatchEvent()[C:\Users\josht\Development\feathers\feathers-sdk\frameworks\projects\starling\Starling-Framework\starling\src\starling\events\EventDispatcher.as:126]
: 	at starling.display::DisplayObject/dispatchEvent()[C:\Users\josht\Development\feathers\feathers-sdk\frameworks\projects\starling\Starling-Framework\starling\src\starling\display\DisplayObject.as:731]
: 	at starling.display::DisplayObjectContainer/broadcastEvent()[C:\Users\josht\Development\feathers\feathers-sdk\frameworks\projects\starling\Starling-Framework\starling\src\starling\display\DisplayObjectContainer.as:425]
: 	at starling.display::DisplayObjectContainer/broadcastEventWith()[C:\Users\josht\Development\feathers\feathers-sdk\frameworks\projects\starling\Starling-Framework\starling\src\starling\display\DisplayObjectContainer.as:435]
: 	at starling.display::DisplayObjectContainer/addChildAt()[C:\Users\josht\Development\feathers\feathers-sdk\frameworks\projects\starling\Starling-Framework\starling\src\starling\display\DisplayObjectContainer.as:135]
: 	at starling.core::Starling/initializeRoot()[C:\Users\josht\Development\feathers\feathers-sdk\frameworks\projects\starling\Starling-Framework\starling\src\starling\core\Starling.as:372]
: 	at starling.core::Starling/initialize()[C:\Users\josht\Development\feathers\feathers-sdk\frameworks\projects\starling\Starling-Framework\starling\src\starling\core\Starling.as:362]
: 	at starling.core::Starling/onContextCreated()[C:\Users\josht\Development\feathers\feathers-sdk\frameworks\projects\starling\Starling-Framework\starling\src\starling\core\Starling.as:595]
```

**Comment by piotrzarzycki21** [comment]
Sorry about that it looks like it was my fault. I switched SDK and for existing project didn't change path to Theme. Once I did that project run without the problem in simulator. I will check what is happen after deploy.
![theme](https://user-images.githubusercontent.com/24554795/52766229-cd22a100-3026-11e9-862e-8a7f9a43b0b9.png)

**Comment by joshtynjala** [comment]
The Toast component was added in 4.0, so there must still be some reference to that SDK.

**Comment by piotrzarzycki21** [comment]
I have found the issue. Our build script pointed out [specific swf version](https://github.com/prominic/Moonshine-IDE/blob/146b25af0742a5d4413e5a7fec359c428e04e6a5/ide/MoonshineSharedCore/src/elements/templates/projects/Feathers%20Mobile%20Project%20(iOS%2C%20Android)/build_air/build.xml.template#L125) and it ended up with blank screen. Apart of that I will move initialization of Theme, cause we are doing that ADDED_TO_STAGE and you are suggesting in [this article](https://feathersui.com/help/themes.html) that it should be in constructor.

**Comment by piotrzarzycki21** [comment]
@yoel123 I have fixed issue with blank screen and possible with building as well. Grab [nightly build](https://moonshine-ide.com/downloads/releases/dev/windows/) and create once again new Feathers mobile project. Additionally before you do this make sure that you have Feathers SDK setup, either in menu **File** -> **Settings** -> **Default SDK** or during project creation. 

If you will have different SDK setup in of those places in build.xml script you may have wrong path to theme MetalWorksMobileTheme. Take a look into the line 131 in build.xml to make sure that everything is ok with it.

**Comment by piotrzarzycki21** [comment]
Reopen if your issue still occurs.
