### ISSUE TITLE
Interface Completion Fails in New AS3 Interface Form

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#448]
I noticed this behavior with code completion in the New Interface form (see #251 and #431):
1. Open Moonshine
2. Open/Create a Flex Desktop project
3. Right-click on src > New > AS3 Interface
4. Enter an interface name
5. In the "Interfaces" field, type "Flex".  After a short delay, some completion options are populated:
6. Double-click on one of the completion options.  BUG:  The option remains as "Flex". 

I get the same result if I try to select a completion option with the arrow keys

**Comment by piotrzarzycki21** [comment]
I think @joshtynjala is not needed here. I see where the issue is. Should be fixed very soon.

**Comment by JoelProminic** [comment]
I tested on MacOS 10.10.5, and this worked as expected for me after the update.
