### ISSUE TITLE
Moonshine App Store Helper not opens through menu in OSX

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#45]
`File > Moonshine App Store Helper` does nothing in Moonshine, OSX.

**Comment by rat-moonshine** [comment]
Moonshine App Store Helper downloader prompt now properly shown through Mac menu even a default SDK has already set.

**Comment by JoelProminic** [comment]
I checked this in the v1.6.1 release candidate.  The Moonshine App Store Helper prompt opened properly, and it did not duplicate the SDKs
