### ISSUE TITLE
Support SWF Builds with Apache Royale

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#453]
While testing #451, we encountered some issues whith SWF builds using Apache Royale.  I extracted this issue from #451 - if there is an existing issue that I missed, we can close this.

    : Compiling NewJavaScriptBrowserProject
    : SDK path: /Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs
    : Using Royale Compiler codebase: /Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs
    : Using Royale SDK: /Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs
    : MXMLJSC
    : +royalelib=/Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks
    : -sdk-js-lib=/Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/js/Royale/generated-sources
    : -load-config+=obj/NewJavaScriptBrowserProjectConfig.xml
    : -compiler.targets=JSRoyale
    : -js-output=/Users/devsena/Desktop/NewJavaScriptBrowserProject
    : /Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/royale-config.xml(74): col: 0 Error: unable to open '/Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/libs/player/11.1/playerglobal.swc'.
    : /Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/royale-config.xml (line: 74)
    :       </external-library-path>
    : /Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/royale-config.xml(98): col: 0 Error: unable to open '/Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/libs/player/11.1'.
    : /Users/devsena/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/royale-config.xml (line: 98)
    :       </library-path>
    : 1.51293756 seconds

In order to perform SWF builds, we need the following environment variables:
- FLEX_HOME
- AIR_HOME
- PLAYERGLOBAL_HOME

Since the Apple sandbox (or other security measures) prevent apps from reading the environment variables, we will need the user to define paths for AIR_HOME and PLAYERGLOBAL_HOME.  If these items are already bundled in the SDKs, Moonshine should detect this and automatically populate the paths after we have setup the SDKs.

In Windows, these can be set as global environment variables.  However, I think we should still give users the option to configure AIR_HOME and PLAYERGLOBAL_HOME so that:
- New users will be guided through the initial setup of the SDK.
- Users can configure different AIR SDK versions if desired.

On Windows, the values can be populated from the environment variables by default.  Failing that, it can check the contents of the configured SDKs instead, as discussed above.

If we proceed with #444, we will need to automate the setup of AIR_HOME and PLAYERGLOBAL_HOME.

**Comment by piotrzarzycki21** [comment]
You need only PLAYERGLOBAL_HOME per my comments https://github.com/prominic/Moonshine-IDE/issues/451#issuecomment-462279731

**Comment by rat-moonshine** [comment]
The fun part of the distributed Royale SDKs is, `playerglobal.swc` that is a requirement to build **js-swf** SDK, does not comes with the distributed **js-swf** bundle; But comes with the **js-only** bundle. The **js-only** bundle also holds the files related to AIR development in the same directory.

Path to the `playerglobal.swc` can be found in **js-only** SDK is:
`/$Royale-SDK-path/frameworks/libs/player/..`

**js-swf** SDK searches `playerglobal.swc` by that path only when env.variable is not present. Joel thinks this could be a build problem at Apache side.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine playerglobal which comes with JS only version of Royale is a fake file added to do not have problems during compilation. :)

**Comment by piotrzarzycki21** [comment]
I believe we are good with that after our changes and add Getting Started view.

**Comment by JoelProminic** [comment]
The Javascript builds work well with Moonshine v2.0.0.  However, the SWF builds are currently disabled.  

    : This SDK only supports JavaScript Builds.

If we want to enable these, we will need to:
- Download a js-swf SDK with Moonshine SDK Installer
- Make sure that playerglobal.swc is present
- set the PLAYERGLOBAL_HOME environment variable

**Comment by piotrzarzycki21** [comment]
> If we want to enable these, we will need to:
> 
> * Download a js-swf SDK with Moonshine SDK Installer
> * Make sure that playerglobal.swc is present
> * set the PLAYERGLOBAL_HOME environment variable

Yes, but I don't understand where is issue on our sight ? Do you expect to setup by us PLAYERGLOBAL_HOME ?

**Comment by rat-moonshine** [comment]
> > If we want to enable these, we will need to:
> > 
> > * Download a js-swf SDK with Moonshine SDK Installer
> > * Make sure that playerglobal.swc is present
> > * set the PLAYERGLOBAL_HOME environment variable
> 
> Yes, but I don't understand where is issue on our sight ? Do you expect to setup by us PLAYERGLOBAL_HOME ?

We need to come to a conclusion first in my opinion. 

If we want to provide SWF compilation from Roayle SDK, then we need to investigate on what we can do from Moonshine side to support the compilation (some steps which Joel already mentioned). If setting up local PLAYERGLOBAL_HOME would do, we need to investigate on that.

If SWF compilation involve more problem, then we need to disable SWF compilation option if already available in Moonshine (probably disabling `Build & Run`) and close this issue as wontfix.

**Comment by piotrzarzycki21** [comment]
> If we want to provide SWF compilation from Roayle SDK, then we need to investigate on what we can do from Moonshine side to support the compilation (some steps which Joel already mentioned). If setting up local PLAYERGLOBAL_HOME would do, we need to investigate on that.

I was thinking about that more and I don't think we should do anything. User have to have on it's own download playerglobal and configure SDK if he would like use it. We could provide link to playerglobal in the message with explanation where downloaded file should be placed.

**Comment by piotrzarzycki21** [comment]
I have added PLAYERGLOBAL_HOME detection and I'm displaying error in the console if someone doesn't have playerglobal.swc suggesting downloading from adobe website. Let me know whether I did any mistake in message:

`This SDK does not contains playerglobal.swc in 'frameworkslibsplayer{version}playerglobal.swc'. Download playerglobal here`

![info](https://user-images.githubusercontent.com/24554795/55971360-9f9e5080-5c81-11e9-91b4-6a076787a768.png)

**Comment by piotrzarzycki21** [comment]
I think I'm going to spend a bit more time on that and display in this message specific version of playerglobal which is required for Royale. That version is specified in [royale-config.xml](https://github.com/apache/royale-asjs/blob/develop/distribution/src/main/resources/frameworks/royale-config.xml)

**Comment by JoelProminic** [comment]
I was able to trigger this message:

    : This SDK does not contains playerglobal.swc in frameworks/libs/player/11.1/playerglobal.swc. Download playerglobal here

However:
- The new message does not work properly with the console scroll.  In my tests, it is consistently appearing outside of the scroll window, and I have to scroll down to see the message.
- If I download playerglobal.swc to royale-asjs/frameworks/libs/player/11.1/playerglobal.swc, I still get the same error on later builds.   I think I still need to set PLAYERGLOBAL_HOME, but I can't set the environment outside of Moonshine in macOS.

**Comment by piotrzarzycki21** [comment]
> I was able to trigger this message:
> 
> ```
> : This SDK does not contains playerglobal.swc in frameworks/libs/player/11.1/playerglobal.swc. Download playerglobal here
> ```
> However:
> 
> * The new message does not work properly with the console scroll.  In my tests, it is consistently appearing outside of the scroll window, and I have to scroll down to see the message.
> * If I download playerglobal.swc to royale-asjs/frameworks/libs/player/11.1/playerglobal.swc, I still get the same error on later builds.   I think I still need to set PLAYERGLOBAL_HOME, but I can't set the environment outside of Moonshine in macOS.

@JoelProminic both issues should be fixed with newest build

**Comment by JoelProminic** [comment]
I tested this on macOS, and I confirmed that the error messages display properly now.

If I don't have playerglobal.swc setup properly, I can still run Project > Build as Javascript or Build & Run as Javascript from Moonshine.  However, I get this error during the build:

    : /Users/joelanderson/Downloads/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/royale-config.xml(74): col: 0 Error: unable to open '/Users/joelanderson/Downloads/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/libs/player/11.1/playerglobal.swc'.
    : /Users/joelanderson/Downloads/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/royale-config.xml (line: 74)
    :       </external-library-path>


I confirmed that once I setup playerglobal.swc, I the PLAYERGLOBAL_HOME environment variable seems to be set properly for all of he build actions.
- Build Project
- Build & Run
- Build as Javascript
- Build & Run as Javascript
- Build Release

**Comment by JoelProminic** [comment]
However, I got this error after completing required setup on macOS:

    : /bin/bash: /Users/<user>/Downloads/apache-royale-0.9.4-bin-js-swf/royale-asjs/js/bin/mxmlc: Permission denied


This occurs because the quarantine attribute was set for the SDK files since I downloaded and extracted them manually.  Also, mxmlc does not have executable permissions:

    bin$ ls -lah@ mxmlc
    -rw-r--r--@ 1 <user>  staff   2.2K Nov 14 08:48 mxmlc
            com.apple.quarantine	  62B 


To fix this, you can use these commmands

    # remove the com.apple.quarantine attribute from all SDK files
    xattr -r -d com.apple.quarantine Downloads/apache-royale-0.9.4-bin-js-swf 
    # give mxlmc executable permissions
    chmod 744 Downloads/apache-royale-0.9.4-bin-js-swf/royale-asjs/js/bin/mxmlc


I documented the problem and fix here for future reference.   I would be nice if Moonshine could guide users on how to correct this problem, but this may need to wait until a later version.

**Comment by piotrzarzycki21** [comment]
> I tested this on macOS, and I confirmed that the error messages display properly now.
> 
> If I don't have playerglobal.swc setup properly, I can still run Project > Build as Javascript or Build & Run as Javascript from Moonshine. However, I get this error during the build:
> 
> ```
> : /Users/joelanderson/Downloads/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/royale-config.xml(74): col: 0 Error: unable to open '/Users/joelanderson/Downloads/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/libs/player/11.1/playerglobal.swc'.
> : /Users/joelanderson/Downloads/apache-royale-0.9.4-bin-js-swf/royale-asjs/frameworks/royale-config.xml (line: 74)
> :       </external-library-path>
> ```
> I confirmed that once I setup playerglobal.swc, I the PLAYERGLOBAL_HOME environment variable seems to be set properly for all of he build actions.
> 
> * Build Project
> * Build & Run
> * Build as Javascript
> * Build & Run as Javascript
> * Build Release

In general in order to use Royale SDK whether it is JS only or JS/SWF you need to have playerglobal.swc in place. In case of JS only SDK we have added fake playerglobal.swc. 
It means that having JS/SWF version of SDK without playerglobal you won't be able to build your application either to JS nor SWF. You just makes me realize that I should display message for the user for JS build as well.

**Comment by piotrzarzycki21** [comment]
I have added message for JS build as well in case when we are using SDK JS/SWF.
