### ISSUE TITLE
Template Not Populated for New Java Class

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#457]
I noticed a problem when testing a Java project in Moonshine today:
1. Create a new Java Maven Project
2. Right-click on src/main/java and select New > Java Class
3. Enter "TestClass" as the name and create
4. BUG:  the file template is not filled in

I saw this with the Moonshine 1.16.0 release on both macOS Yosemite and Windows 10.

![image](https://user-images.githubusercontent.com/24532731/52975651-ecedf800-338b-11e9-86f4-6b7d54b409f2.png)

I saw these errors on the console:

    : Feb 18, 2019 12:11:52 PM 
    : null
    : org.eclipse.jface.text.BadLocationException
    : 	at org.eclipse.jface.text.ListLineTracker.getLineOffset(ListLineTracker.java:194)
    : 	at org.eclipse.jface.text.AbstractLineTracker.getLineOffset(AbstractLineTracker.java:157)
    : 	at org.eclipse.jface.text.AbstractDocument.getLineOffset(AbstractDocument.java:873)
    : 	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineOffset(SynchronizableDocument.java:320)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.convertRange(WorkspaceDiagnosticsHandler.java:165)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.toDiagnostic(WorkspaceDiagnosticsHandler.java:145)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.lambda$0(WorkspaceDiagnosticsHandler.java:130)
    : 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    : 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    : 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    : 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    : 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    : 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    : 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.toDiagnosticsArray(WorkspaceDiagnosticsHandler.java:132)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.visit(WorkspaceDiagnosticsHandler.java:116)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:74)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:74)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:74)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:74)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:74)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.resourceChanged(WorkspaceDiagnosticsHandler.java:63)
    : 	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:297)
    : 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    : 	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:287)
    : 	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:150)
    : 	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:376)
    : 	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1499)
    : 	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:157)
    : 	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
    : 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
    : Error #1125
    : RangeError: Error #1125
    : 	at actionScripts.ui.editor.text::DiagnosticsManager/showDiagnostics()
    : 	at actionScripts.ui.editor.text::TextEditor/showDiagnostics()
    : 	at actionScripts.ui.editor::LanguageServerTextEditor/showDiagnosticsHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.languageServer::LanguageClient/textDocument__publishDiagnostics()
    : 	at actionScripts.languageServer::LanguageClient/parseMethod()
    : 	at actionScripts.languageServer::LanguageClient/parseMessage()
    : 	at actionScripts.languageServer::LanguageClient/parseMessageBuffer()
    : 	at actionScripts.languageServer::LanguageClient/input_onData()
    :
    : Click here to Report a Bug

**Comment by piotrzarzycki21** [comment]
It looks like this part is not implemented yet. I'm trying to work on this. However I noticed that Java project doesn't have his own settings event. I will add there Maven and Paths options.
![java_settings](https://user-images.githubusercontent.com/24554795/53004515-a521ac00-3431-11e9-84b6-972422b59851.png)

**Comment by piotrzarzycki21** [comment]
@joshtynjala I would like to add Maven build options and Paths - similar which we have in AS3 project. Once they added I need to implement [saveSettings](https://github.com/prominic/Moonshine-IDE/blob/5df8f25e78030e99d5efdef7e95751f9341d717a/ide/MoonshineSharedCore/src/actionScripts/plugin/actionscript/as3project/vo/AS3ProjectVO.as#L404) - In case of AS3ProjectVO we are saving it to .as3proj. - Do you think we should have similar file for Java ? I see in created Java project following files  `.project`, `.classpath` - Those are some eclipse stuff ?

**Comment by piotrzarzycki21** [comment]
After more thinking about that we should have such file, so we could keep project related settings in it.

**Comment by joshtynjala** [comment]
We should modify pom.xml or build.gradle. The language server will need to know about any paths and things that affect the build, and those files are considered the main source of truth.

The language server generates .project and .classpath automatically. I don't think that we should try to modify these files. Our changes will probably be overwritten.

**Comment by piotrzarzycki21** [comment]
Fair enough. I will modify than pom file in order to have information and feed the system with it. The one thing which I actually need is path to source folder, so pom file can have it.

**Comment by piotrzarzycki21** [comment]
I have fixed main issue from this ticket. I have added missing things, so Java project has currently some settings where we can point main source folder. Everything is based on what we have in pom.xml file. I still see more issues - I will work on fixing them.

@JoelProminic  Note that you may required recreate your project again to test that.

**Comment by JoelProminic** [comment]
As you warned, I got this error when opening my old project:

    : Error #1088
    : TypeError: Error #1088
    : 	at actionScripts.utils::MavenPomUtil$/getProjectSourceDirectory()
    : 	at actionScripts.plugin.java.javaproject.importer::JavaImporter$/parse()
    : 	at actionScripts.impls::IJavaBridgeImpl/parseJava()
    : 	at actionScripts.plugin.project::ProjectPlugin/openPreviouslyOpenedProject()
    : 	at actionScripts.plugin.project::ProjectPlugin/handleShowPreviouslyOpenedProjects()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at MethodInfo-14805()
    : 	at SetIntervalTimer/onTimer()
    : 	at flash.utils::Timer/tick()
    :
    : Click here to Report a Bug


This may be a problem if we want to import an external Java project.  Maven (and Gradle) are designed to use reasonable default paths, so many projects will not have explicit definitions for project.build.sourceDirectory.


I created a new project, and I confirmed that I can create a new Java class.  I also tested each of the options for the new Java file, and the only problem I found was that the "internal" option was not valid:

IMAGE

The Java equivalent of Actionscript's "internal" keyword is using no modifier (this is called "package-private"):
Actionscript:  https://help.adobe.com/en_US/as3/learn/WS5b3ccc516d4fbf351e63e3d118a9b90204-7f36.html
Java:  https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html

```
class TestPackagePrivate  
{
	public TestPackagePrivate()
	{
	}
}
```

**Comment by joshtynjala** [comment]
> This may be a problem if we want to import an external Java project. Maven (and Gradle) are designed to use reasonable default paths, so many projects will not have explicit definitions for project.build.sourceDirectory.

Agreed. If a field is missing in pom.xml or build.gradle, Moonshine should use a default value. As a Java developer, I would expect my existing projects to work without changes to my build file.

**Comment by JoelProminic** [comment]
Here is the Gradle documentation for the Java task properties:  https://docs.gradle.org/current/userguide/java_plugin.html

The best documentation I could find for the Maven options were in the default Super POM here:  https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Super_POM

I checked to see if the super POM was available in the Maven SDK, but it seems it is embedded in one of the library JARs, and the location may not be stable:
https://stackoverflow.com/questions/6797209/where-is-super-pom-for-maven-3

**Comment by piotrzarzycki21** [comment]
> > This may be a problem if we want to import an external Java project. Maven (and Gradle) are designed to use reasonable default paths, so many projects will not have explicit definitions for project.build.sourceDirectory.
> 
> Agreed. If a field is missing in pom.xml or build.gradle, Moonshine should use a default value. As a Java developer, I would expect my existing projects to work without changes to my build file.

Question is what is the default path if it exits in the average for Maven and Gradle projects ?

**Comment by piotrzarzycki21** [comment]
> Here is the Gradle documentation for the Java task properties: https://docs.gradle.org/current/userguide/java_plugin.html
> 
> The best documentation I could find for the Maven options were in the default Super POM here: https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Super_POM
> 
> I checked to see if the super POM was available in the Maven SDK, but it seems it is embedded in one of the library JARs, and the location may not be stable:
> https://stackoverflow.com/questions/6797209/where-is-super-pom-for-maven-3

I see something like that in super POM src/main/java - I will make that default, but if location doesn't exist I will make sure that nothing happen.

**Comment by piotrzarzycki21** [comment]
I think I'm done in case of issues related to this ticket. I will raise two new separate. 
1) Making adjustment to Java Gradle project
2) Make available Maven build system for Java projects - it's requries some work.
