### ISSUE TITLE
Build and Run Java Maven Applications

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#459]
Java Maven and Java Gradle projects do not have an options to Build or Build & Run in Moonshine.

They can be compiled with Maven (pom.xml) and Gradle (build.gradle) respectively.

### Maven:

We currently have support for Maven in Moonshine, for PrimeFaces Preview at least.  However, this is not configurable for Java Maven projects (the settings page for Java Maven has no options currently).  The basic build and run commands look like this:

    # Build JAR
    mvn pkg
    # Run - you can find <name> and <version> in pom.xml.  
    #     - main_class_name is the project name by default, but we could support other main classes if desired
    java -classpath $project_home/target/$name-$version.jar $main_class_name

Alternatively, we could update the default pom.xml scripts with an exec task, similar to what we have for PrimeFaces Preview

To support libraries, we'll need to update pom.xml to add the dependency.

### Gradle

We don't have any Gradle support in Moonshine currently, but the build process is like this:

    # Compile
    gradle build
    # Run - main_class_name is the project name by default, but we could support other main classes if desired
    java -classpath build/libs//$project_name.jar $main_class_name

For more advanced functionality, see:  https://docs.gradle.org/current/userguide/java_plugin.html

Gradle also provides a wrapper so that you don't have to install Gradle (or worry about which version is installed).  Unfortunately, this is probably not practical for Moonshine on macOS because the bash script will be blocked from inside the sandbox.
https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by piotrzarzycki21** [comment]
First part of this issue is working now #464

**Comment by piotrzarzycki21** [comment]
> First part of this issue is working now #464

I was wrong with that, it should be still implemented.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I looked into that and I see that the main problem is to recognize what actually is the main class for application. In case of new application there is no problem, cause I can assume that main class will have the same name. 
However how to discover what is the main class for existing project ? 

My idea on that is to provide option similar to what exists for AS3 applications in Moonshine "Set as Default Application", when you right click on some file. However where to save that info ? The only thing which come up to my mind is pom.xml file and add some extra property, which I [did lately](https://github.com/prominic/Moonshine-IDE/blob/c68e220999a46356ad213bfa8e73ff7725693123/ide/MoonshineSharedCore/src/elements/templates/projects/Java%20Maven%20Project/pom.xml.template#L13) for saving current maven build action. 

Thoughts ?

**Comment by JoelProminic** [comment]
My suggestion would be to add the main class as a property in the project settings.  If the user tries to Build & Run without setting a main class, they should be directed to the settings page to make a selection.  Selecting the class using a context menu action would also be useful.

Not all Java applications will have main classes, since they may be designed to run on a server instead.  While Maven and Gradle support running a Java application, I don't think that this is part of the normal workflow.  So, I think it is fine to configure the main class outside of pom.xml or build.gradle.

The main class must implement "public static void main(String[])".  Perhaps we could detect if a class meets this requirement using the language server.  Either way, this check is not required for a basic implementation.

**Comment by piotrzarzycki21** [comment]
> My suggestion would be to add the main class as a property in the project settings.

But problem with that, we don't have in Java and Gradle projects IDE files, like it is in AS3 type of projects where you have `NewFeathersDesktopProject.as3proj`. That's why in my previous comment I have mention that I'm creating custom property inside pom.xml which holds default value for building Java app. Create Java project and go to pom file, so you can see.

**Comment by joshtynjala** [comment]
If Moonshine can modify things like the classpath and main class in its settings dialogs, but it does not modify pom.xml and build.gradle, the language server will not be aware of any of those settings. The user will be forced to manually update their build file to get proper code intelligence. Is that the workflow that we want?

**Comment by piotrzarzycki21** [comment]
Probably not, but is it common to have options in IDE and modify pom to save them? Today I have pushed for Java project settings file where those stuff can be saved. When I would like to start run jar, are you suggesting modify pom to tell what class should be run? 

I thought it's enough if:
1. Run Maven build
2. Run jar trough the console with appropriate parameter

**Comment by piotrzarzycki21** [comment]
If I understand from your code the only thing what changes you require for Language Server is path to folder with pom. You doesn't need path to source folder at all. Am I right?

**Comment by joshtynjala** [comment]
> If I understand from your code the only thing what you require for Language Server is path to folder with pom. You doesn't need path to source folder at all. Am I right?

If the user wants to use a different source folder than the default, then it needs to be saved in the pom.xml file.

**Comment by piotrzarzycki21** [comment]
I'm trying to understand this. Initially pom.xml template wasn't contains any point to source folder. What path language server uses in that time?

**Comment by joshtynjala** [comment]
> Probably not, but is it common to have options in IDE and modify pom to save them?

No, I don't think it's common. However, the Java language server treats pom.xml (or build.gradle) as the main source of truth to configure its code intelligence. With that in mind, I'm not sure that we have a choice. Users will expect changes that they make in the settings to be reflected in code intelligence without manually changing their build file.

**Comment by joshtynjala** [comment]
> I'm trying to understand this. Initially pom.xml template wasn't contains any point to source folder. What path language server uses in that time?

If the path is omitted, Maven uses *src/main/java* by default.

**Comment by piotrzarzycki21** [comment]
I think we are on a good path right now with my changes. I just need to bring back ability to modify pom. Some information which are not related to language server but rather some kind of convenience addition would be saved to configuration file of the project. 

There is very last questions: In order to change path to source I have to specify in pom ?
`<sourceDirectory>src/main/java</sourceDirectory>`

How to modify pom file in order to specify main class ?

As for the gradle build file, we have found huge difficulties with reading/writing anything to it, so probably this project would be an exception where all settings have to be provided trough that file not UI in Moonshine.

**Comment by joshtynjala** [comment]
Here's how you specify the main class in a JAR file

``` xml
<build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-jar-plugin</artifactId>
      <configuration>
        <archive>
          <manifest>
            <mainClass>com.example.Main</mainClass>
          </manifest>
        </archive>
      </configuration>
    </plugin>
  </plugins>
</build>
```

An example of a real pom.xml where I used this option:

https://github.com/BowlerHatLLC/vscode-as3mxml/blob/ee97d98c092af10a301f5d498a73ebfcf2147ac8/check-royale-version/pom.xml#L49

**Comment by JoelProminic** [comment]
For reference, I see that Gradle configures the main class like this:

```
jar {
    manifest {
        attributes 'Main-Class': 'com.moonshine.DemoMain'
    }
}
```

However, this value could be definied programatically, so it will be difficult to support configuring the settings from Moonshine for Gradle projects.   See #465 for more discussion about this.

**Comment by JoelProminic** [comment]
So, we could implement this in two ways.  We could choose to implement both ways if desired - they cover slightly different use cases:

1. Have the user select which class they want to run from Moonshine.  This would not be persisted to pom.xml or build.gradle.  On Build & Run, Moonshine would build the JAR and run it with the selected class, regardless of whether it was defined as the Main-Class of the JAR.

This solution is what I am used to from Eclipse.  However, in Eclipse I generally right-click on the class and choose "Run as Java Application", rather than running it from the application menu.

2. Have the user configure the Main-Class for the JAR.   This would need to be updated in pom.xml or build.gradle.    On Build & Run, Moonshine would run the JAR with the default main class only:

    java -jar build/libs/$project_name.jar

However, we would not be able to define Main-Class for Gradle projects until we had a more reliable way to read and edit build.gradle (see #465).   The Java Gradle template should define Main-Class so that a new project will run properly from Moonshine.   If no Main-Class is defined, the execution would fail.

If we only want to implement one of these designs, then this design would be preferrable, since it would cover the JAR configuration as well.

**Comment by piotrzarzycki21** [comment]
Here is my plan for today. I will go with option 2:
1. Java Project
- I will get back with reading/writing to pom, since it is what language server expects
- Other UI features can be saved in settings file - unrelated to maven pom
2. Gradle project
- Currently we are not reading/writing gradle build, so Moonshine can be for that type of projects as an editor without configuration on the UI sight.
- If we give user option to point main class - it could be saved to settings file not gradle build. The question is: If user in external place build Gradle project using gradle build - can we run that jar assuming that user configured the same Main application file ?

**Comment by piotrzarzycki21** [comment]
Now I'm saving source directory and main application to pom file. It doesn't have reflection in the UI yet. However I will add it probably next week. We don't have to wait for my update with release. Java project now is working pretty stable, unless you @JoelProminic find something new.

**Comment by JoelProminic** [comment]
I see that there is now a menu option for "Project > Build with Apache Maven".

I tried this with a fresh Java Maven project on macOS, but I was prompted to set the Build Actions.   I would like to see Moonshine set a default for this in the template.   "clean package" would do a minimal build to create the jar, while "clean install" would install the project to the local  Maven repository.

I didn't see a way to Build & Run the Java Maven project currently.

I didn't see a "Build with Gradle" menu action.   "Project > Build with Apache Maven" was enabled, so I tried that, but Moonshine showed "Specify Maven commands (Ex. clean install)" on the console, and showed me the setting page which showed:  "Project configuraiton is currently managed by build.gradle only."

**Comment by piotrzarzycki21** [comment]
> I see that there is now a menu option for "Project > Build with Apache Maven".
> 
> I tried this with a fresh Java Maven project on macOS, but I was prompted to set the Build Actions. I would like to see Moonshine set a default for this in the template. "clean package" would do a minimal build to create the jar, while "clean install" would install the project to the local Maven repository.
> 
> I didn't see a way to Build & Run the Java Maven project currently.
> 
> I didn't see a "Build with Gradle" menu action. "Project > Build with Apache Maven" was enabled, so I tried that, but Moonshine showed "Specify Maven commands (Ex. clean install)" on the console, and showed me the setting page which showed: "Project configuraiton is currently managed by build.gradle only."

Thanks for a quick check. Option Build and Run is still not working yet. The only thing which I have implemented yesterday was take care of settings write/read to Maven pom file. Everything is still under development. However I will make sure that we have some default action for a new Java Maven project.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have added default action for maven build. Next I have spent quite a bit of time on checking how actually implement `Build and Run`. It looks like to me we should make changes to menu `Build`. Currently we have 3 type of projects ActionScript, JavaScript (Royale) and Java, so we are displaying all options build related regardless project type. Behind the stage when user chooses build ActionScript project or Royale there is not too much of difference, we just provide what compiler should be run. However Java require different action, so we can add more condition and somehow make that "Build and Run" 

If we look a bit wider on that situation and add third type of projects we may have a mess in Build menu. I think to avoid growing chaos because of more types of project menu Build should be generated dynamically, depends on what type of project is selected. Even if names of items in menu would be similar to other projects (like Build and Run could exists in AS and Java projects), underneath action would be handled different. 

That's my proposition to handle menu options in a better way which prepares us for more project specific type of action.

**Comment by JoelProminic** [comment]
I ran a test with a new Java Maven project on macOS today, and I confirmed that the default action was set to "clean package".   

However, I noticed this warning (the formatting matches how it appears in Moonshine - the line breaks are not working properly for some reason in this case - this problem didn't trigger in a later test):

    : [INFO] Scanning for projects...
    : [WARNING] 
    : [W
    : ARNING] Some problems were encountered while building the effective model for local:
    : TestJavaMaven_0308:jar:0.1.0-SNAPSHOT
    : [WARNING] 'build.plugin
    : s.plugin.version' for org.apache.
    : maven.plugins:maven-jar-plugin 
    : is missing. @ line 14, column 15
    : [WA
    : RNING] 
    : [WARNING] It is highly recommended to fix
    :  these problems because they threaten the sta
    : bility of
    :  your build.
    : [WARNING] 
    : [WARNING] For this reason, f
    : uture Maven versions might no longer support building such malformed projects.
    : [WARNING] 


The plougin was configured like this

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <mainClass>TestJavaMaven_0308</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
```


If I add a version number, that clears the warning:
```
        <version>3.1.1</version>
```

**Comment by JoelProminic** [comment]
I agree that it sounds more reasonable to define build actions for each project type rather than trying to make a single menu action work for all project types.  

I think we should make a "Build & Run" action available for all project types (if relevant - for example, it doesn't make sense for Flex Library).  This will allow us to provide the user with project templates that will actually do something (even if it just displays or prints "Hello, World").

**Comment by piotrzarzycki21** [comment]
> However, I noticed this warning (the formatting matches how it appears in Moonshine - the line breaks are not working properly for some reason in this case - this problem didn't trigger in a later test):

It's pretty unpredictable with line breaks. I doubt I would be able to do with it anything. I've seen that before.

**Comment by piotrzarzycki21** [comment]
> If I add a version number, that clears the warning:

Thanks for that - I just updated default template with version for that plugin.

**Comment by piotrzarzycki21** [comment]
> I agree that it sounds more reasonable to define build actions for each project type rather than trying to make a single menu action work for all project types.
> 
> I think we should make a "Build & Run" action available for all project types (if relevant - for example, it doesn't make sense for Flex Library). This will allow us to provide the user with project templates that will actually do something (even if it just displays or prints "Hello, World").

I will work on that - hopefully for the next release we will have nice working menu with Build and Run for Java as well.

**Comment by piotrzarzycki21** [comment]
@JoelProminic  I forgot to show you where am I with that issue. I have implemented start application using Maven. However it is probably insufficient, cause output from application is happen in our Moonshine's console. I'm committing that stuff and for now Build and Run is doing only Run, before you try it build application and than run. Cause I really don't know how this should looks like. Maybe I should try to open separate console application and in some way  do whole run there. I need some input on that. On the screenshot you can see in our console **Hello World**
![helloworld](https://user-images.githubusercontent.com/24554795/55159355-16572c00-5161-11e9-9e41-14bf6ef893cc.png)

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have implemented Java Build and Run for non gradle version of project. It's currently running project using jar which has been produced by Maven build. It's running in our console window:
I have following concerns:
1) Should I output command which is being used for running application?
2) What to do with Gradle build ? - My suggestion is to disable menu options for now for this type of projects.

Thoughts ?

**Comment by piotrzarzycki21** [comment]
Instead of disabling anything I'm displaying on the console warning: `Project build is currently managed by build.gradle only.`. It's enough for now I think so.

**Comment by JoelProminic** [comment]
Sorry, I missed your earlier question.  Unless we can find a reliable way to read the executable path, I think that we can hide Build & Run for Java Gradle projects.


For Project > Build, I think we should just run "$GRADLE_HOME/bin/gradle clean build" by default.  You can see all of the other tasks that will be executed with this command:


    $ gradle clean build
    Starting a Gradle Daemon (subsequent builds will be faster)
    :clean UP-TO-DATE
    :compileJava
    :processResources NO-SOURCE
    :classes
    :jar
    :assemble
    :compileTestJava NO-SOURCE
    :processTestResources NO-SOURCE
    :testClasses UP-TO-DATE
    :test NO-SOURCE
    :check UP-TO-DATE
    :build

A more advanced solution would be to let the user configure the tasks for Gradle, similar to the Build actions for Maven.

Is there some limitation I am forgetting that prevents us from running Gradle builds like this?

**Comment by JoelProminic** [comment]
Another option would be to read the Jar location and main class using logic like this:  https://github.com/prominic/Moonshine-IDE/issues/465#issuecomment-482715769

This is a read-only solution, but it should work for Build & Run.

That said, we don't even download Gradle as part of Moonshine SDK Installer, currently, so any of the solutions I listed should probably be saved until after the 2.1.0 release.

**Comment by piotrzarzycki21** [comment]
I have raised separate issue for making Gradle app build working.
