### ISSUE TITLE
Additional compiler option is disabled for other projects than Adobe Air

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#46]
I have noticed that all non Air projects (FlexJS, Flex Web browser) has disabled "Additional compiler options" in Settings.

**Scenario:** 
1. Create new non Air project for example FlexJS
2. Right click on the project and choose "Settings"
3. Click "Build options"

"Additional compiler options" is disabled.

![image](https://user-images.githubusercontent.com/24554795/31586899-18fcdf10-b1d8-11e7-9ebc-0f9afa20b808.png)

**Code:** 
I see that line number 180 in `AS3ProjectVO` -> `additional.isEditable = air;` caused that issue. Is it mistake or there were some purpose of doing such restriction ?

**Comment by rat-moonshine** [comment]
I see for some reasons I chose to disable compiler options in case of browser based projects. But I'm not exactly clear now why it was been disabled. Restoring it again, please keep an eye if this breaks anything (in case).

**Comment by piotrzarzycki21** [comment]
I think we will not have problems with web based projects, but not sure what's with Feathers projects. 
I will close it after some tests. 

Thanks!
