### ISSUE TITLE
Auto-Import Packages in Java Projects

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#462]
During my testing with Moonshine 1.16.0, I found that class/package imports are not automatically added when editing Java classes.  See #408 for more detail about the expected behavior and implementation.

**Comment by piotrzarzycki21** [comment]
Josh if it's something from not your area let me know I will take that from you.

**Comment by joshtynjala** [comment]
I'll take a look. It's possible that I'm not properly handling some field of the CompletionItem returned by the Java language server.
