### ISSUE TITLE
How Visual Editor works

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#467]
In issue BowlerHatLLC/vscode-as3mxml#324 we got comments related to Visual Editor -> https://github.com/BowlerHatLLC/vscode-as3mxml/issues/324#issuecomment-466803328

I will try to answer as part of this issue how VE is working.

**Comment by piotrzarzycki21** [comment]
Visual Editor in Moonshine is a simple way of creating mockups of your application or rather some views from your application and eventually transform it to real app. We are giving users options to create mockups in Flex or [PrimeFaces](https://www.primefaces.org/) along with export features which creates Adobe Air Desktop or Java PrimeFaces application. (menu **Project** -> **Export Visual Editor Project** ).

However VE is not giving you fully the same options as it was in for example Adobe Flash Builder:
1. You cannot edit code - We have learned in the past that when user had really complex views visual editor in Flash Builder never worked. It always crushed due to complexity which can exists in MXML code. In order to avoid such problems we do not allow edit code. 
2. You cannot debug code created in Visual Editor, cause this type of project is not a real application until you export it. In PrimeFaces type of Visual Editor you have option **Preview** when you right click on file.
3. You cannot copy existing MXML files straight to the VE and display it. In order to have it displayed you would have to conform with special type of XML which visual editor understand which is being hold in **visualeditor-src** folder of created project. This folder is default hidden from the user in Moonshine - you can make it available by selecting option in menu **File** -> **Settings** -> **General** -> **Show hidden files/folders**. However we do not recommend make modification in those files on your own. 

In last half year we have put a lot of emphasis into PrimeFaces type of Visual Editor, so that part is probably more sophisticated than Flex one.

**Comment by LudvikWiejowski** [comment]
Thanks for explanation!

**Comment by piotrzarzycki21** [comment]
@LudvikWiejowski No problem. :) I will leave it open for some time if you will have any more question.

**Comment by rat-moonshine** [comment]
> Also, I could not debug project, all items of Debug menu are disabled. Also, I tried Away builder (I was curious) and now I can't close it, close button is inactive.

We are investigating on some problems when clearing and re-creating Away Builder different fields; Currently, the close-able option is blocked to Away Builder tab.
