### ISSUE TITLE
New folder dialog should allow creation of nested folders

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#468]
1. Right-click in file explorer and choose **New** -> **Folder** to open the **New Folder** dialog.
2. In the input box, I should be able to type `com/example` and Moonshine will smartly create a folder named *com* that contains a subfolder named *example*.

I should be able to create folders as deeply as I want. For example, `com/example/myproject` or `com/example/myproject/components/utils`.

Visual Studio Code has a similar feature, and it's really convenient for quickly creating deep folder hierarchies.

**Comment by rat-moonshine** [comment]
This is a nice suggestion, thank you @joshtynjala .

**Comment by rat-moonshine** [comment]
Extending the feature to be available in other file creation dialogs as well.

**Comment by rat-moonshine** [comment]
Updates:

- Validation of file/folder existence during nested file/folder creation
- Updated all file popups with requisite handling
- Creation of nested file/folder
- Properly updates to sidebar tree
- Fixed nested class-file package and file-name; Previously:
```
package src
{
	public class abcd/efgh/MyNewClass
	{
		public function abcd/efgh/MyNewClass()
		{
```

**Comment by JoelProminic** [comment]
I did some testing for this.  Moonshine required File and XML files to be created in the src directory (and New File didn't even work in this case).  @rat-moonshine fixed this problem during the morning meeting.  I got some other errors while revisiting the other project types that I'll report separately.

Type | Test
-----|-----
Folder | Working
AS3 Class | Working, package set correctly
AS3 Interface | Working, package set correctly
CSS File | Working (restricted to src directory)
File | Working
Form Builder DXL File | Working
Groovy Class | Working, package set correctly
Haxe Class | Working, package set correctly
Java Class | Working, package set correctly
MXML File | Working
MXML Module | Working
Visual Editor DXL File | Working
Visual Editor Flex File | Working
Visual Editor PrimeFaces File | Working
XML File | Working

**Comment by rat-moonshine** [comment]
While testing on Windows I noticed nested package path generation is broken. Problems now been fixed and I have updated @JoelProminic [test-matrix](https://github.com/prominic/Moonshine-IDE/issues/468#issuecomment-707235880) with addition of Windows-test column.

**Comment by piotrzarzycki21** [comment]
If this is ready and you have tested - please close the issue. Do not wait for Joel to test. - I'm using Moonshine every day - if I noticed somethign weird I will let you know.

**Comment by JoelProminic** [comment]
The test matrix looks mostly good, so this can be merged if it hasn't been already.

To test the Groovy file, use a Grails project and create the file under src/main/groovy.

**Comment by rat-moonshine** [comment]
This issue is now merged into 'master'. All tests to be done on 'master' from now.

**Comment by joshtynjala** [comment]
A couple of issues I noticed (I'm on Windows 10, if it matters):

1) The header for the Project view is using an incorrect serif font.

2) The same header says "Projects (IDE-Default)". What is the meaning of "(IDE-Default)" part of the text? That seems like it probably shouldn't be there.

**Comment by piotrzarzycki21** [comment]
@joshtynjala we have introduced #416 in Moonshine. (IDE-Default) is the name of default workspace.

**Comment by joshtynjala** [comment]
Cool, thanks. My first thought was that I was looking at some kind of string added for debugging purposes that someone forgot to remove before committing. With that in mind, maybe if the workspace name is "IDE-Default", it should not be shown. Alternatively, maybe the default name should be different, like "MoonshineWorkspace" or something like that.

**Comment by rat-moonshine** [comment]
Thanks for the suggestions, @joshtynjala . Eventually, @JoelProminic also pointed out the problem on wrong Font-type usage to the sidebar. He also proposed a naming for the default-workspace, [here](https://github.com/prominic/Moonshine-IDE/issues/416#issuecomment-733171114). Let us know if you have more thoughts over the line.

**Comment by JoelProminic** [comment]
I filled in the missing test case (Groovy on Windows).  This seems to be working fine now, so I'm closing the issue.

**Comment by JoelProminic** [comment]
Reviewing this for release, I realized that we did not support using Windows path separators (i.e. foo\bar\test) for creating the nested folders.  Backslash characters are blocked in the input field, so there shouldn't be any confusion about whether this is supported.   I don't think this needs to be changed now, but it is something we could consider for a later release.
