### ISSUE TITLE
How do I migrate Flex code to Royale in Moonshine IDE?

### ISSUE THREAD

**Issue by lmarevaloa** [prominic/Moonshine-IDE#470]
Hello friends, I am trying to migrate flex code to royale. I am changing the following lines:
xmlns: s = "library: //ns.adobe.com/flex/spark"
xmlns: mx = "library: //ns.adobe.com/flex/mx"

by:

xmlns: s = "library: //ns.apache.org/royale/spark"
xmlns: mx = "library: //ns.apache.org/royale/mx"

but this error comes out !!
col: 1 Error: This tag could not be resolved to an ActionScript class. It will be ignored. : : <s:Application xmlns:fx="http://ns.adobe.com/mxml/2009"

**Comment by piotrzarzycki21** [comment]
Hi @lmarevaloa ,
Could you provide us a bit more information. What version of Royale SDK are you using [Nightly build](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/lastSuccessfulBuild/artifact/out/) or [Released one](https://royale.apache.org/download/)?

Can you provide full code of you main class, by excluding some external component etc. Even better if you could attach your simple project where you reproduce the problem. There is possibility that this is not related to Royale at all.

**Comment by lmarevaloa** [comment]
> Hi @lmarevaloa ,
> Could you provide us a bit more information. What version of Royale SDK are you using [Nightly build](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/lastSuccessfulBuild/artifact/out/) or [Released one](https://royale.apache.org/download/)?
> 
> Can you provide full code of you main class, by excluding some external component etc. Even better if you could attach your simple project where you reproduce the problem. There is possibility that this is not related to Royale at all.



I tried it with "Hello World" and I use the sdk royale: Apache Royale 0.9.2 FP11.1 AIR14.0 (JS, SWF). Download apache-royale-0.9.6-bin-js-swf but I get the following error: Unable to access jarfile C: \ apache-royale-0.9.6-bin-js-swf \ royale-asjs \ lib \ fcsh. jar

**Comment by piotrzarzycki21** [comment]
Did you point in Moonshine royale-asjs folder ? Maybe you should move Royale to different folder, cause maybe it can be problem with accessing to some part of sdk.

**Comment by lmarevaloa** [comment]
> Did you point in Moonshine royale-asjs folder ? Maybe you should move Royale to different folder, cause maybe it can be problem with accessing to some part of sdk in that location.


I already probe with several locations of the folder but still I have the same error. 
 Error: Unable to access jarfile C:\Users\equipopc\Documents\apache-royale-0.9.6-bin-js-swf\royale-asjs\lib\fcsh.jar

Do you have any settings that you have successfully tested?

**Comment by piotrzarzycki21** [comment]
No there is no specific settings. You need to remember that this version of SDK needs as well playerglobal.swc and it should be placed `frameworks\libs\player\11.7\`. Another questions:
1) What version of Moonshine are you using released one or did I provide you Nightly build ?
2) What version of JAVA JDK do you have setup in Moonshine ?
3) If you use [Apache Flex SDK](https://flex.apache.org/installer.html) and create hello world project do you experience the same issue ? 
4) Can you try with [JS only Royale](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/).

**Comment by lmarevaloa** [comment]
> No there is no specific settings. You need to remember that this version of SDK needs as well playerglobal.swc and it should be placed `frameworks\libs\player\11.7\`. Another questions:
> 
> 1. What version of Moonshine are you using released one or did I provide you Nightly build ?
> 2. What version of JAVA JDK do you have setup in Moonshine ?
> 3. If you use [Apache Flex SDK](https://flex.apache.org/installer.html) and create hello world project do you experience the same issue ?
> 4. Can you try with [JS only Royale](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/).


I use the one recent version of Moonshine IDE 1.16:

![image](https://user-images.githubusercontent.com/47543948/53655533-74562980-3c1e-11e9-8a7b-e0d5bd4fdfb4.png)

Probe with flex only JS Royale "Hello World" and if it works. The error I get when I want to migrate from flex to royale.

**Comment by piotrzarzycki21** [comment]
> Probe with flex only JS Royale "Hello World" and if it works. The error I get when I want to migrate from flex to royale.

I'm not sure what is happen here. Can you provide what project are you trying to build - Maybe attach it here. 

Did you went trough all my steps without success ?

**Comment by piotrzarzycki21** [comment]
@lmarevaloa please try newest release and report back if you found any problems.

**Comment by lmarevaloa** [comment]
> @lmarevaloa please try newest release and report back if you found any problems.

Hi, Update mooshine ide 2.0 but it does not do anything when creating a new flash web project and the following error is displayed: 


: Compiling TRES
: Unknown tag:compiler.targets

:( :(

**Comment by piotrzarzycki21** [comment]
> > @lmarevaloa please try newest release and report back if you found any problems.
> 
> Hi, Update mooshine ide 2.0 but it does not do anything when creating a new flash web project and the following error is displayed:
> 
> : Compiling TRES
> : Unknown tag:compiler.targets
> 
> :( :(

I don't understand. Previously you have had problems with Royale project, now you are reporting issue with Flash Web project - Could you describe what do you want to achieve ?

**Comment by piotrzarzycki21** [comment]
I just tried and created new Flex Browser Project (SWF) and compiled it without the problem. However as I understand you are talking about Royale project yes ?

**Comment by lmarevaloa** [comment]
> I just tried and created new Flex Browser Project (SWF) and compiled it without the problem. However as I understand you are talking about Royale project yes ?


Yes, according to the apache article
https://apache.github.io/royale-docs/create-an-application/migrate-an-existing-app/migrate-from-flex.html
, which says that you have to change some parameters to migrate code from flex to royale. But I just did the test with "Hello World" and it gives me the following error:

 Compiling cuatro
: Using Royale SDK: C:\apache-royale-0.9.0-bin-js-swf\royale-asjs
: MXMLJSC
: -sdk-js-lib=C:\apache-royale-0.9.0-bin-js-swf\royale-asjs\frameworks\js\Royale\generated-sources
: -load-config+=obj/cuatroConfig.xml
: -optimize=false
: +configname=flex
: -debug=true
: 
: -o
: bin-debug/cuatro.swf
: -compiler.targets=SWF
: Loading configuration: C:\apache-royale-0.9.0-bin-js-swf\royale-asjs\frameworks\flex-config.xml
: Loading configuration: C:\Users\equipopc\Documents\cuatro\obj\cuatroConfig.xml
: 
: C:\Users\equipopc\Documents\cuatro\src\cuatro.mxml(2): col: 1 Error: This tag could not be resolved to an ActionScript class. It will be ignored.
: 
: <s:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 


This is the code that modifies the header:

<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009" 
			   xmlns:s="library://ns.apache.org/royale/spark" 
			   xmlns:mx="library://ns.apache.org/royale/mx" minWidth="955" minHeight="600">
			   
	<fx:Declarations>
	</fx:Declarations>
	
	<fx:Script>
		<![CDATA[
			
		]]>
	</fx:Script>
	
	<s:Label fontSize="24" fontWeight="bold" textAlign="center"
		horizontalCenter="0" verticalCenter="0"
		text="Hello World!"/>
</s:Application>

**Comment by piotrzarzycki21** [comment]
@lmarevaloa I have created for you Hello World example where I just copied your code pasted here. It's working perfectly. Note that in project **Settings** (right click on the project) -> **Build options** -> **Additional compiler options** -> I have added +configname=flex parameter. Use that attached project as an starting point. I have used [Nightly Build of Royale](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/lastSuccessfulBuild/artifact/out/)

[cuatro.zip](https://github.com/prominic/Moonshine-IDE/files/3053056/cuatro.zip)
