### ISSUE TITLE
Signature Help: UI needs buttons to see other overloaded signatures

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#474]
A language server may return multiple signatures for the same function, if the language supports overloads. Currently, we display the active signature, but the user should be able to scroll through all of them.

**Comment by piotrzarzycki21** [comment]
@joshtynjala Can you please show at least screenshot what do you mean by overloads ? I would like to check this one.

**Comment by joshtynjala** [comment]
Some languages allow you to define multiple methods with the same name, but different parameters.

For example, you can do this in Java:

```java
public void doSomething()
{
	doSomething(false);
}

public void doSomething(boolean flag)
{
}
```

If you call `doSomething`, you should see the new buttons in the signature help popup to let you cycle through each of methods.

ActionScript does not support method overloads.

**Comment by piotrzarzycki21** [comment]
> Some languages allow you to define multiple methods with the same name, but different parameters.
> 
> For example, you can do this in Java:
> 
> ```java
> public void doSomething()
> {
> 	doSomething(false);
> }
> 
> public void doSomething(boolean flag)
> {
> }
> ```
> 
> If you call `doSomething`, you should see the new buttons in the signature help popup to let you cycle through each of methods.
> 
> ActionScript does not support method overloads.

Silly me. Looking into that I was only thinking about AS3, forgot that Moonshine supports Java as well. :) I'm sorry about that! Thanks!

**Comment by JoelProminic** [comment]
I have been using this for a Java Gradle project, and it works well.  Eventually, we may want to add some parameter guidance after one of the signatures has been selected - for example, Eclipse shows placeholders for the parameters that are overwritten as we type.   This works for now, though.

However, I see this does not work for Java or Groovy files in an existing Grails project (new Grails projects are broken currently:  #635 ).  If this is not something that can be added easily, we can create an issue for a later release.

**Comment by joshtynjala** [comment]
I tested in a Groovy project, and `System.getenv()` correctly shows two overloads.

**Comment by JoelProminic** [comment]
I tested this with the latest build on Windows with classes in src/main/groovy, src/main/java, and grails-app/controllers, and I found that in all cases, the overloads were not displayed.

![image](https://user-images.githubusercontent.com/24532731/68903191-f8463800-06ff-11ea-8acb-b13e61745d5d.png)
![image](https://user-images.githubusercontent.com/24532731/68903199-fc725580-06ff-11ea-87fa-3c796f44f150.png)

On a side note, the language server did not work for src/main/java classes until I did Project > Refresh Gradle Classpath.  src/main/java was already in the Class Paths list in the Project settings by default, the directory was not created automatically.

**Comment by joshtynjala** [comment]
@JoelProminic Your screenshots appear to display the completion list. Overloads are shown in signature help after you type `(`.

**Comment by JoelProminic** [comment]
Okay, I see this interface, but it did not seem to open consistently for me.  Is there a way to scroll through the options without using the mouse?   The arrow keys moved the cursor position instead.
![image](https://user-images.githubusercontent.com/24532731/68904127-c387b000-0702-11ea-8033-9f92a843bd2e.png)

I get this instead in a Java Gradle project, which is what I am used to with Eclipse:
![image](https://user-images.githubusercontent.com/24532731/68903942-33496b00-0702-11ea-87de-c0cd1be1daed.png)

And the other overload interface you described looks like this in the same Java Gradle project:
![image](https://user-images.githubusercontent.com/24532731/68904066-8cb19a00-0702-11ea-923d-05af464b643d.png)

**Comment by joshtynjala** [comment]
> And the other overload interface you described looks like this in the same Java Gradle project:

The blank signature issue in the screenshot is now fixed.
