### ISSUE TITLE
Miscellanous Tweaks for Moonshine 2.0.0

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#475]
Here is a list of minor issues I found while testing #449. 

The "GitHub" settings menu should be "Git".

Update the message for Allowing access to Git/SVN:

Old:

>In order to use Git and SVN in Moonshine it needs XCode, due to Apple sandbox.  
>
>You can allow permission to access XCode by clicking on Allow Access button below. In the opening window click on "Open".

New:

>In order to use Git and SVN, you must grant permission for Moonshine to access the XCode command line tools.
>
>Click "Allow Access" to open the folder show below.  Then click "Open" to grant access.

Re-skin the  "Install Everything Now" and "Download Third-Party Software" buttons.  Currenlty they look like plain HTML buttons, so they look out of place.

**Comment by JoelProminic** [comment]
In the "By Software" mode for the features list, the "Required by" text should be generated automatically based on the relationship between the software and features.  Currently this is not generated for Ant, Maven, Subversion, Feathers, or Git.

**Comment by rat-moonshine** [comment]
All of the above modifications have applied. Please, check.
