### ISSUE TITLE
Dynamic menu Project

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#477]
In the results of discussion in https://github.com/prominic/Moonshine-IDE/issues/459#issuecomment-471483791 and https://github.com/prominic/Moonshine-IDE/issues/459#issuecomment-471767537 as part of that issue I will try to improve Project menu. It should change along with selected project in the side bar. Appropriate options related to the project type will be displayed or not. 

**Section without change:**
_Search_
_Open/Import Flex project_ -> It should be change to something more generic _Open project_
_Import project Archive_ 

**Flex/Feathers/ActionScript Desktop/Mobile/Web:**
_Build project_
_Build and Run_
_Build release_
_Clean project_
_Build with Apache Ant_
_Build with Apache Maven_

**Flex Library** in future **Royale Library** as well:
_Build project_
_Clean project_
_Build with Apache Ant_
_Build with Apache Maven_

**Royale project**:
_Build project_
_Build and Run_
_Build as JavaScript_
_Build and Run as JavaScript_
_Build release_
_Build with Apache Ant_
_Build with Apache Maven_
_Clean project_

**Visual Editor project**:
_Export Visual Editor Project_
_Stop preview_

**Java Project**:
_Build project_
_Build and Run_
_Build release_ - Not sure whether this is something applicable.
_Clean project_
_Build with Apache Maven_

**Java Gradle Project**:
No options apart of **Section without change** cause we are not support Gradle build yet.

**Comment by piotrzarzycki21** [comment]
If I'm thinking about that more in case of **Java Gradle Project** we could leave almost all options as it is in Java Project but disabled, because those projects are related.

**Comment by piotrzarzycki21** [comment]
Branch with dynamic menu has been merged to master.

**Comment by rat-moonshine** [comment]
I start seeing this problem while working on v2.0.0 macOS version. @piotrzarzycki21 please, give some test if the problem still exists in current builds.

1. Make sure no project is already opened in Moonshine
2. Restart Moonshine
3. Choose to create a new ActionScript project
4. Upon creation expand the project in sidebar
5. Create a new folder 'libs' to the root of the project
6. I Copied a SWC from somewhere and pasted inside the newly created 'libs' folder (_this may not needed to be SWC only but I document how I tested_)
7. I confirm the selection in sidebar remain to the 'libs' folder
8. I tried to perform `Project -> Build & Run`
9. There were no project compilation menu available
10. I tried to re-select root of the project to the sidebar, but it didn't make any difference

![image](https://user-images.githubusercontent.com/24370870/55147926-4ad0e500-516d-11e9-84c6-2c0ae7b9a10e.png)

**Comment by piotrzarzycki21** [comment]
Thanks for detailed scenario - I will look into that!

**Comment by rat-moonshine** [comment]
I confirm this problem also exists with latest Bamboo build. I also noticed it trigger when renaming a folder.

**Comment by piotrzarzycki21** [comment]
It took me a while but I was able to fixed! Thanks!

**Comment by JoelProminic** [comment]
I tried a couple cases with rename and paste, and I couldn't reproduce the issues reported by @rat-moonshine anymore.   

I started verifying the different projects before I got pulled into other tasks.  I noticed that the Java Maven project did not have the "Build release" or "Build with Apache Maven" action you listed in the original description.  However, I gree that "Build release" doesn't make sense for this project right now, and "Build with Apache Maven" is a bit redundant.

I noticed that the Projects menu didn't update when I closed or deleted a project:
1. Open two projects that have different Projects menus
2. Select one of the projects, and check the menu
3. Close the project
4. Check the projects menu.  BUG:  this shows the menu items from the closed project.  Selecting different files in the same project does not update the menu

**Comment by piotrzarzycki21** [comment]
> I tried a couple cases with rename and paste, and I couldn't reproduce the issues reported by @rat-moonshine anymore.
> 
> I started verifying the different projects before I got pulled into other tasks. I noticed that the Java Maven project did not have the "Build release" or "Build with Apache Maven" action you listed in the original description. However, I gree that "Build release" doesn't make sense for this project right now, and "Build with Apache Maven" is a bit redundant.
> 
> I noticed that the Projects menu didn't update when I closed or deleted a project:
> 
> 1. Open two projects that have different Projects menus
> 2. Select one of the projects, and check the menu
> 3. Close the project
> 4. Check the projects menu.  BUG:  this shows the menu items from the closed project.  Selecting different files in the same project does not update the menu

I have fixed issue from your scenario.

**Comment by JoelProminic** [comment]
When I tested this today, I noticed that all of the build actions were disabled for a new Java Maven project.
1. Create a new Java Maven Project
2. Click the Project menu.  BUG:  Build, Build & Run, and Clean Project are present, but disabled
3. Select a different project, and then select the Maven project again
4. Click the Project menu.  BUG:  Build, Build & Run, and Clean Project are present, but disabled
5. Close and reopen the Maven project
6. Click the Project menu.  BUG:  Build, Build & Run, and Clean Project are present, but disabled
7. Restart Moonshine
8. Select the Maven project and click the Project menu.  The menu actions are properly enabled

**Comment by piotrzarzycki21** [comment]
@JoelProminic I cannot reproduce that problem on my Mac and Windows. Not sure what is happening here. @rat-moonshine if will have some time tomorrow try that as well with above scenario. In general those options should be disabled only for Java Gradle project.

**Comment by JoelProminic** [comment]
I couldn't reproduce this issue again after restarting Moonshine.   @rat-moonshine reported that he could not reproduce this issue either.  If I can find a better test procedure after the release, I'll create a new issue after the release.
