### ISSUE TITLE
Network Shares and Moonshine SDK Installer

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#478]
I talked to a coworker who is managing the Windows workstations for the office.   He confirmed that the profile directory can be mapped to a file share or a network share.  (With the current VDI we are using, this is not the case, but he is working on a new environment that would use network shares).

Since we are downloading the SDKs under the user's profile directory, we could have the following problems:
- Reduced performance
- Space limitations
- Interference with other users in the environment

My original idea to avoid this problem was to let the user select a custom download directory for Moonshine SDK Installer (#449) on Windows.  This feature would be generally useful, but we were not sure if we wanted to include it in the initial release (2.0.0).

However, this would not protect users who are not paying attention to the install directory.  In this case, we might want a check to determine if the target directory is on a network drive.  This command might be a place to start for this (but it requires running with administrator privileges, so it is not appropriate for Moonshine currently):  https://www.crestline.net/powershell-get-list-of-ad-users-and-their-profilepath-and-homedirectory/

**Comment by rat-moonshine** [comment]
In my opinion the easy way out would be to providing option to choose custom location for `MoonshineSDKs` folder on Windows only (to avoid other immediate complexities like network drive and other limitations). The providing option (to choose) can be an one time event - people can choose to go by default SDK Installer location (which is User directory), or choose another location where `MoonshineSDKs` folder can generate.

The next question is, when and how user can reset this option and choose a new directory for `MoonshineSDKs` folder. One option is to delete the 64-bit archive folder and start fresh.

**Comment by piotrzarzycki21** [comment]
The one thing is to provide option to change directory, but the other one is that how this network shares problems affect users when as default their SDKs are installed in `File.documentsDirectory` -> `c:\Users\{mysuer}\Documents` ? 

**Reduced performance** - This one I think it may happen when your disk space is near full. Maybe there are other factors which I'm not aware.

**Space limitations** - That could be a problem, but it's not something which we have to bother too much, cause user will have ability to change path to different location.

**Interference with other users in the environment** - How it can interference with others when we are placing SDKs in Documents per user ?

I think we don't have to bother for this release to have custom location of installed SDKs. 

There is one more thing if we debate about that even more - maybe even custom location is not necessary, cause in the end user may close **Getting Started** and manually setup everything in the settings.

**Comment by rat-moonshine** [comment]
That is fine. But I think we can supply the option by this release only. I have done my ground works hopefully it'll serve the purpose. To choose between default and custom on Windows.

**Comment by piotrzarzycki21** [comment]
> That is fine. But I think we can supply the option by this release only. I have done my ground works hopefully it'll serve the purpose. To choose between default and custom on Windows.

I think having options to choose folder where it is installed is definitely less important than other fixes. We are one week behind. Let's release tomorrow Moonshine. Do not implement new stuff cause it's require testing and time.

**Comment by rat-moonshine** [comment]
> 
> 
> > That is fine. But I think we can supply the option by this release only. I have done my ground works hopefully it'll serve the purpose. To choose between default and custom on Windows.
> 
> I think having options to choose folder where it is installed is definitely less important than other fixes. We are one week behind. Let's release tomorrow Moonshine. Do not implement new stuff cause it's require testing and time.

Yeh, thanks for reminding! I'm on my tasks.

**Comment by rat-moonshine** [comment]
Is the issue still appropriate when we have changed to user's Documents directory (however, we may want to change that again because of [this](https://github.com/prominic/Moonshine-IDE/issues/449#issuecomment-474326510) problem) and introduction of custom default path option on Windows (?)

**Comment by piotrzarzycki21** [comment]
Please discuss this today if you can with Joel. My proposition is to have C:/ drive - even if it doesn't exists, cause I think most of the user have that drive and we avoid bad first impression when someone will try to install SDKs in Documents.

**Comment by rat-moonshine** [comment]
Default SDK location on Windows set to use system root drive (usually `C:\`).

I noticed File API has method to return all the available system drive, ordered in ascending order (C-Z). SDK Installer takes the first drive reference (usually `C:\`) and use for the purpose. However, I'm not entirely sure how the method will return in network sharing cases. If it'll return no drive File objects, then MSDKI will choose to user's directory to save as default location.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I wanted to test newest build, so cleaned my settings to Moonshine related. Should I see `C:\` drive as a Default SDK Location ? Cause I'm still seeing point to Documents.

**Comment by piotrzarzycki21** [comment]
I think I know what is happen. This default path is being saved to cookie. When I do reset settings using Moonshine options, are you removing cookies related to that location ?

**Comment by rat-moonshine** [comment]
> I think I know what is happen. This default path is being saved to cookie. When I do reset settings using Moonshine options, are you removing cookies related to that location ?

:) I yet to upload latest MSDKI build to the download location and update the update notification file. When you shall upgrade to MSDKI 2.8.0 you'll get the newer updates which will try to look for default location by `C:\MoonshineSDKs`.

**Comment by rat-moonshine** [comment]
Okay, I have updated the SDK Installers to 2.8.0 to location. You should able to upgrade in your next test with latest Moonshine build available to you.

[Note: If previously you was using any custom SDK path on Windows and the path still exists, then MSDKI will continue using that location]

**Comment by JoelProminic** [comment]
I confirmed that the default path was updated to C:\MoonshineSDKs, and Moonshine SDK Installer ran properly on a fresh VM using this default.

**Comment by piotrzarzycki21** [comment]
Can we close that one as well ?

**Comment by JoelProminic** [comment]
The change to the default path should avoid the Network Share issue in the default case.  The user could still choose a network shared directory for their install, but for now, I think we can let them try that if they want.   If we find major problems in practice when working with network shares, we can reopen this issue (or create a new one).
