### ISSUE TITLE
Camera.getCamera() returns null

### ISSUE THREAD

**Issue by dpanzer** [prominic/Moonshine-IDE#479]
Hi, I'm new to Moonshine and AS3 development but I've gotten identical code working fine with FlashDevelop on a PC.

I'm using Moonshine on a Mac with OS X High Sierra with Flex 4.16.1 FP31.0 AIR31.0 and I can get the Hello World AS3 project to run fine.

However, when I run the following, it complains that `Camera.getCamera()` returns null. Any guidance would be appreciated as I don't understand why it is not detecting my Mac's built in webcam (I have no problem using the webcam in other applications)

```
package
{
    import flash.display.*;
    import flash.media.Camera;
    import flash.media.Video;

	public class NewActionScriptProject extends Sprite
	{
		// video variables
		private var camW:int = 300;
		private var camH:int = 300;
		private var video:Video;
		
		
		public function NewActionScriptProject()
		{
			super();
			
			var camera:Camera = Camera.getCamera();
			camera.setMode(camW, camH, 30);
			video = new Video(camW, camH);
			video.attachCamera(camera);
		}
	}
}
```

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Build & Run didn't work for me for pure AS3 application. Build itself is working but running not.

**Comment by piotrzarzycki21** [comment]
Hi @dpanzer, 

I have created pure AS3 project with latest release, build it and run successfully without any problems. Unfortunately Build & Run didn't work, but I went to `bin-debug` folder  debug and double click on swf - I got this one which indicates that camera was able to run without the problem.

![alert_cam](https://user-images.githubusercontent.com/24554795/54413488-21887180-46f6-11e9-95df-204f0c4c53fa.png)

I have associated with swf files in my system [Flash Player projector content debugger](https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flashplayer_32_sa_debug.exe)

I did test on Windows. 

@rat-moonshine Can you give a try on your Mac with Camera, cause I don't any on my sight.

**Comment by piotrzarzycki21** [comment]
> @rat-moonshine Build & Run didn't work for me for pure AS3 application. Build itself is working but running not.

If this is an issue we have to raise another one and close this one cause it's not related to Moonshine.

**Comment by dpanzer** [comment]
Thanks for the quick reply! I am also able to get it to work by building and then running the .swf locally (or in browser)

However it is pretty critical to be able to Build & Debug so that I can set breakpoints, see console output, and in general not have a really tedious workflow each time.

How exactly is the app run in Build & Debug mode? Would something prevent that container from accessing system devices? Both `Camera.names` and `Microphone.names` return empty arrays in this case.

**Comment by piotrzarzycki21** [comment]
@joshtynjala should actually Debug work for pure AS3 project ?

**Comment by joshtynjala** [comment]
Yes, debugging should work. The only thing that I never got around to implementing is debugging an app that's running on a mobile device.

**Comment by JoelProminic** [comment]
Hmm, this may be because of the Apple sandbox.  There is special entitlement for accessing a camera, which Moonshine does not have:  https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_camera

Any applications started by Moonshine have the same entitlements (and restrictions) as Moonshine.

The above page also linked me to some other hardware entitlements that may be relevant:
Microphone:  https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_microphone
Printer:  https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_print
USB?:  https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_usb
Bluetooth?:  https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_bluetooth

We could add these entitlements to Moonshine, but we would need to justify why they are necessary to the App Store.

The copy of Moonshine on available on our [website](http://moonshine-ide.com/) also uses the sandbox, for now.   I think we have previously discussed releasing a version of Moonshine without the sandbox, and we may need to revisit this idea.

**Comment by dpanzer** [comment]
That sounds like it would be the issue
> We could add these entitlements to Moonshine, but we would need to justify why they are necessary to the App Store.

Seems like it would be fairly straightforward to say Moonshine is an IDE and developers may want to test apps that access various hardware capabilities, no?

**Comment by rat-moonshine** [comment]
> 
> 
> Yes, debugging should work. The only thing that I never got around to implementing is debugging an app that's running on a mobile device.

I see you made some updates to #10 , though. I was in-fact wondering where the development state now following a conversation from #481 .

**Comment by joshtynjala** [comment]
Since Justin has had me working on support for other languages, I haven't had time the properly dive into larger tasks like that. I can only fit in quick things, like updating the as3mxml language server and fixing bugs.

**Comment by rat-moonshine** [comment]
Sorry, as it took me some time to look into this. 

In my initial finding, I couldn't able have the code snippet run in Moonshine (as others already reported). I couldn't able to run the code snippet in other IDEs either. I found the `Camera.getCamera()` is a popular problem discussion when running in an IDE environment. 

I found the code-snippet requires some changes to have them work. I'm attaching the fixed snippet that worked for me. ALSO, this requires to run in a non-sandbox environment. 

That means, this API is suppose to work in Moonshine Windows, and Moonshine OSX **non-sandbox version** - we're introducing a non-sandbox version to direct download soon!

```
package
{
	import flash.display.Sprite;
	import flash.media.Camera;
	import flash.media.Video;
	
	public class CameraTest extends Sprite
	{
		private var camW:int = 300;
		private var camH:int = 300;
		private var video:Video;
		
		public function CameraTest()
		{
			super();
			
			var camera:Camera = Camera.getCamera();
			camera.setMode(camW, camH, 30);
			camera.setQuality(0, 0);
			video = new Video(camW, camH);
			video.attachCamera(camera);
			this.addChild(video);
		}
	}
}
```

**Comment by piotrzarzycki21** [comment]
Please try non-sandbox version with newest 2.2.0 release and let us know if you still have that issue.

**Comment by dpanzer** [comment]
I've tested this and it works now, thanks!
