### ISSUE TITLE
Flex browser project creates with wrong 'URL to Launch' value

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#48]
Upon creation of a new Flex browser project, it sets the projects `Settings > Run > URL to Launch` value wrongly to open `.swf` file instead of `.html`:

![image](https://user-images.githubusercontent.com/24370870/31734277-d5545ba4-b45b-11e7-9791-63b3cba835b1.png)

The project suppose to open the wrapper HTML file to compiled SWF, by default.

**Comment by rat-moonshine** [comment]
New project creation populates the `URL to Launch` path properly, now. 

For Flex web project the default path sets to `bin-debug/[projectName].html`.
For FlexJS project the default path sets to `bin/js-debug/index.html`.

Clearing the field value (by going through `project > Settings > Run`) resets them back again.

**Comment by JoelProminic** [comment]
Confirmed for FlexJS, Flex SWF, and ActionScript SWF projects
