### ISSUE TITLE
install SDK Error #1000

### ISSUE THREAD

**Issue by dolphin520** [prominic/Moonshine-IDE#480]
- [ ] Review the documentation: https://github.com/prominic/Moonshine-IDE
- [ ] Search for existing issues: https://github.com/prominic/Moonshine-IDE/issues
- [ ] Use the latest stable version at: http://moonshine-ide.com
- [ ] Let us know how to reproduce the issue. Include a code sample, or share a project that reproduces the issue

## Steps to Reproduce
When install SDK in window 10.

### Errors
Error #1000
Error: Error #1000
	at flash.net::URLLoader/onComplete()

**Comment by piotrzarzycki21** [comment]
Hi @dolphin520 ,
We are pretty close to release new version. You should have new one on Monday or so and those error should gone.

**Comment by dolphin520** [comment]
oh okie! your reply is fast! Thank you!

**Comment by piotrzarzycki21** [comment]
Should be resolved by #449

**Comment by dolphin520** [comment]
How can i use this recent update? i need to reinstall the application?

**Comment by piotrzarzycki21** [comment]
Hey @dolphin520 you can try to use [dev](https://moonshine-ide.com/downloads/releases/dev/windows/) build, but we probably add some more fixes today/tomorrow. It will be released by the end of the week. Let us know whether you had any problems with that it would be helpful to get better quality of that release.

**Comment by piotrzarzycki21** [comment]
It should be fixed in 2.0.0 version.
