### ISSUE TITLE
Actual release builds?

### ISSUE THREAD

**Issue by cjseahorn** [prominic/Moonshine-IDE#481]
What’s the roadmap for being able to build actual release builds for Adobe Air desktop apps? I like the speed of the IDE but everything I compile as a release build (no matter the type of project) just comes out as an .SWF   Forgive me if I’ve missed some documentation but it seems to be sparse at this point. Thanks in advance for any insight you can give me on this.

**Comment by piotrzarzycki21** [comment]
Hi @cjseahorn ,

Currently the only option to produce release package is using [Apache Ant](https://ant.apache.org/) script which we are adding to every new created project. You will find it in `build` folder of created project. 
By choosing menu **Project** -> **Build with Apache Ant** script will run and produce package to `build/DEPLOY`.

**Comment by rat-moonshine** [comment]
> Currently the only option to produce release package is using [Apache Ant](https://ant.apache.org/) script which we are adding to every new created project. You will find it in `build` folder of created project.
> By choosing menu **Project** -> **Build with Apache Ant** script will run and produce package to `build/DEPLOY`.

@cjseahorn @piotrzarzycki21 I think that is the only available option at present supplied by Moonshine to packaging application (providing certificates can be modified by editing the Ant build script). 

We had some development already started towards packaging mobile application through Moonshine UI by providing certificates and other information (#10 ) but I need to update myself about the current status of integration. Having that interface available, one can package application through Moonshine interface itself.

**Comment by cjseahorn** [comment]
You know what...I’ve used that menu choice a few times and it seemed to do nothing (as nothing in the IDE informs the action was confirmed). I’d check the root folder and bin-release (flashbuilder habit) but would only see the swf which spurred my question. Today I paid attention a little closer and when i chose compile with ANT i see the java icon pop up in my taskbar so i knew something happened. I then explored the project directory and found the .air file in the build-Deploy folder. Eureka.  I don’t care where you guys put it as long as you put it somewhere lol. Maybe a little identifier could pop up when people choose that inside the IDE to let them know something is going on?  Either way you guys are doing a fantastic job. I’m a Mac user so the only open source option (FlashDevelop) isn’t really an option for me to compile against Apache Flex. I’ve been with Adobe Air since the Apollo days so I’ve been handling all air code through flash builder 4.7 with my creative cloud account which is really unstable at this point and pretty much abandoned by Adobe so Moonshine immediately brought a smile to my face.  Keep up the great work you got a fan here!

**Comment by piotrzarzycki21** [comment]
> You know what...I’ve used that menu choice a few times and it seemed to do nothing (as nothing in the IDE informs the action was confirmed). I’d check the root folder and bin-release (flashbuilder habit) but would only see the swf which spurred my question. Today I paid attention a little closer and when i chose compile with ANT i see the java icon pop up in my taskbar so i knew something happened. I then explored the project directory and found the .air file in the build-Deploy folder. Eureka. I don’t care where you guys put it as long as you put it somewhere lol. Maybe a little identifier could pop up when people choose that inside the IDE to let them know something is going on? Either way you guys are doing a fantastic job. I’m a Mac user so the only open source option (FlashDevelop) isn’t really an option for me to compile against Apache Flex. I’ve been with Adobe Air since the Apollo days so I’ve been handling all air code through flash builder 4.7 with my creative cloud account which is really unstable at this point and pretty much abandoned by Adobe so Moonshine immediately brought a smile to my face. Keep up the great work you got a fan here!

Many Thanks for that feedback! We definitely need more users who are using IDE daily. We are pretty close to release new version. If it not happened today/tomorrow I will provide you link to development build, cause there are a lot's of fixes. 

Our way of communication with user is mostly console - if nothing pop up, take a look into the console and you should see some notification - mostly. ;)

**Comment by piotrzarzycki21** [comment]
> Maybe a little identifier could pop up when people choose that inside the IDE to let them know something is going on?

However I'm still thinking to bring to Moonshine some day some kind of nice notification system. Definitely something else than ugly popups. Hopefully it will happen some day, but for now we are using console a lot.

**Comment by cjseahorn** [comment]
No you’re doing fine my problems are mainly based on my lack of experience with the IDE. I would pull up the console if I knew I was running a trace and in times where my code wouldn’t compile I’d open up the problems window.  Now that I had a chance to use it more all I really need is the console  because it tells me everything.  I’ll just get in the habit of keeping it up in view. I’m looking forward to the new build!

**Comment by piotrzarzycki21** [comment]
Thank you! I'm closing this one. If you will have more questions raise new ticket.

**Comment by piotrzarzycki21** [comment]
@cjseahorn It looks like release takes us a bit more time, so here you have [development build](https://moonshine-ide.com/downloads/releases/dev/macos/) for Mac. This link provides a build which is being updated whenever we push fixes to this github. There are lot's of changes in general flow of getting started with Moonshine. I hope you will like it and everything make it easier.

**Comment by cjseahorn** [comment]
Fantastic. I’m hammering it with everything from embedded databases to server side sql requests with no problems so far. It plays nice with my existing FlashBuilder/Air projects so I’ve got plenty of existing code to shove down its throat to put it through its paces. I see other guys use this to compile Java but I mainly need this to compile AS3/AIR and while I may dabble with it’s Java side I don’t see me leaving Apache Netbeans anytime soon. Any plans to bring Adobe Air to current (v32) in Apache Flex or can I safely overlay it over the v28 you are currently carrying?

**Comment by piotrzarzycki21** [comment]
> Any plans to bring Adobe Air to current (v32) in Apache Flex or can I safely overlay it over the v28 you are currently carrying?

I'm not sure what do you mean here. Moonshine sources itself is being build with Adobe Air 28, we just didn't switch to the newest one yet, but your applications can use whatever version of Adobe Air you want. If you could elaborate a bit more what do you mean here... 

Thanks!

**Comment by cjseahorn** [comment]
I think you just answered my question. By default install you guys are
pointing to the Apache Flex/ Adobe air that you guys put in the desktop
folder so the only changes I’ve needed to make bringing my flash builder
code into Moonshine is just to downgrade the air version from 32 to 28 in
the app-xml. I don’t want to run a boatload of the same kind of SDK’s in
various places but if I have to I’ll point it out to a different one in
Moonshine. Was just curious to know when Apache Flex bumps Air version is
all. Meant no offense :-).

Chris

**Comment by piotrzarzycki21** [comment]
I'm still not entirely sure whether I understand you. In Moonshine version which I provide you can download Apache Flex 4.16.1 with Adobe Air 32 using Getting Started view. Next you can use that in your app. Saying that you downgrade version to 28 - Do you mean that you did that in your Application?

**Comment by cjseahorn** [comment]
I hadn’t used the new build. The prior created air 28. Installed moments
ago.
