### ISSUE TITLE
Project Sidebar Does Not Open Until Getting Started Page Opens

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#482]
I started noticing this issue with development builds on Windows today.   It seems to have some connection to the updates for #449:
1. Ensure that all SDKs are installed so that the Getting Started page does not open automatically on startup.
2. Open at least one project in Moonshine
3. Restart Moonshine
4. Moonshine opens.  BUG:  the project sidebar does not open
5. Wait 60 seconds - the sidebar still does not open
6. Help > Getting Started.  The sidebar loads within a couple seconds of the tab opening.

I originally only saw this issue when Moonshine was launched from the Windows installer (either on update or clicking "Run Now" if installer had already been executed).  @rat-moonshine tried some fixes during the chat today, and now I am seeing this issue even when I start Moonshine normally.   @rat-moonshine couldn't reproduce this behavior, but I have triggered it two different Windows 10 environments.

I have not seen this trigger on macOS.

**Comment by rat-moonshine** [comment]
If this is not triggering in macOS, then perhaps it's something associated to the environment variable parsing area. I'll continue investigate on this.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 can you able to give some tests with recent Moonshine builds and see if you can reproduce Joel's problem, if yes in which circumstances.

**Comment by JoelProminic** [comment]
For my test procedure to work, you would want to have all SDKs present and configured so that the Getting Started page does not open.   In my testing, the Project sidebar always opened when the Getting Started tab was open.

I'll continue to watch for more clues about why this error is triggering on my VMs.

**Comment by JoelProminic** [comment]
Something else interesting I noticed:   If I open a project from the Recents section on the Home page between steps 4 and 6 above, then that project only will open in the Projects sidebar.   Once I open the Getting Started page (step 6), then the previous projects will also load in the sidebar.

**Comment by rat-moonshine** [comment]
Since I couldn't able to reproduce the original issue, I thought to add some step-logs to understand the problem where these might breaking in your case @JoelProminic . 

With latest Moonshine build, you shall see some logs stepping from 1-7 in console view. They will start with `TEST::482::#` prefix as following:

```
: TEST::482::###::Completed dependency sequence test; All present: false 
: TEST::482::#1::Ready to read from cookie 
: Moonshine IDE 0.0.0
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 28.0.0.125
: TEST::482::#2::Dispatching event to read cookie
: TEST::482::#3::Event catch by ProjectPlugin
: TEST::482::#4::Method called to parse from cookie; Removing listener
: TEST::482::#5::Fetching previously opened projects from cookie
: TEST::482::#6::Found projects by length: 1
: TEST::482::#7::Project object created - sending to open: G:\Tests\TestProject
```

Let me know your complete log when such issue happen again for you.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I was able to reproduce that problem. I have build **992** installed. The weird thing is that I don't see at all your traces in the console. It means that code is note being reached for opening latest project at all.

I didn't install anything trough Moonshine SDK Installer. I have configured JAVA and Royale SDK. I opened one project. I have restarted Moonshine and project wasn't reopen, side bar didn't show up. 

```
: 'null' is not recognized as an internal or external command,
: operable program or batch file.
: Moonshine IDE 2.0.0
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 32.0.0.89
```

**Comment by rat-moonshine** [comment]
That is interesting! I see it didn't reached the dependency check completion either. Looking for a probable break, but this is a good hint when you able to reproduce this at you.

**Comment by piotrzarzycki21** [comment]
I can try to debug it tomorrow if you won't figure out it today.

**Comment by rat-moonshine** [comment]
I added more logs. Try after 5/10 minutes with newly generated Moonshine. We shall go to its root.

**Comment by piotrzarzycki21** [comment]
Here you have from latest build: 

```
: TEST::482::0::Initiating dependency checks. 
: TEST::482::1::Dependency checks method called 
: TEST::482::1-1::Going to parse system environments 
: 'null' is not recognized as an internal or external command,
: operable program or batch file.
: Moonshine IDE 2.0.0
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 32.0.0.89
```

**Comment by rat-moonshine** [comment]
Okay. This says environment variable loading/parsing call never returned - nor complete or error event.

Since this producing at you it make sense you debug this at you. Inside StartupHelperPlugin you can see EnvironmentUtils.read() call is happening. Moonshine listens to its returns by two separate events. What is happening after the read() method, that you want to debug - whether the NativeProcess inside it able to load its standard.output or if there was any parsing break after data being loaded. Parsing happens at process Exit event.

**Comment by piotrzarzycki21** [comment]
One more thing, cause I didn't bother so far. I have empty Getting Started when I'm running from IDE:
![gettingstarted](https://user-images.githubusercontent.com/24554795/54689142-3febd400-4b1f-11e9-99b8-dfb6bd466edd.png)

**Comment by rat-moonshine** [comment]
> 
> 
> One more thing, cause I didn't bother so far, cause I was working on different tasks, but I have empty Getting Started when I'm running from IDE:
> ![gettingstarted](https://user-images.githubusercontent.com/24554795/54689142-3febd400-4b1f-11e9-99b8-dfb6bd466edd.png)

The list populates by an external XML resides in sdk-installer library; This could be related to some configuration setup difference in your IDE, so I'm not very worrying about this at this moment. I updated something to EnvironmentUtils, so please update your local before a debug/test.

**Comment by JoelProminic** [comment]
I tested this again on the same Vagrant VM, and I got mixed results.  Sometimes the Project Sidebar opened properly, but I had at least one case where it failed to open.  Here is the console output I saw:
![image](https://user-images.githubusercontent.com/24532731/54720057-77ad4880-4b2c-11e9-8242-fbf8663c5129.png)

I tested this issue on a more recent Windows version (https://app.vagrantup.com/StefanScherer/boxes/windows_10).  I could not reproduce the problem - the project sidebar opened every time Moonshine started.  I tried:
- Opening multiple projects
- Opening different project types

**Comment by rat-moonshine** [comment]
I confirm when I tested on Vagrant VM with EdgeOnWindows10 template, I able to reproduce the problem same as was with @JoelProminic . It is good to know that the problem didn't produced with more recent version of template, but here the code should have enough intelligence so it can pass the blocker and continue to its other course of actions even in older template/VM.

Hopefully I'll able to get more data on this break when I have Vagrant/VM running now.

**Comment by piotrzarzycki21** [comment]
> Hopefully I'll able to get more data on this break now when I have Vagrant/VM running.

I'm not sure what do you mean by that. Do you have it running and reproduced the problem ?

**Comment by rat-moonshine** [comment]
Yes, I able to reproduce the problem with my Vagrant VM running. I also able to find the reason behind this.

Environment does parsing well and returning its planned completion event to Moonshine, however the weak referencing to those event listening turned out the problem. Once I removed the weak referencing, it starts working in Vagrant VM, too:

```
// previously
environmentUtil.addEventListener(EnvironmentUtils.ENV_READ_COMPLETED, continueOnHelping, false, 0, true);

// now
environmentUtil.addEventListener(EnvironmentUtils.ENV_READ_COMPLETED, continueOnHelping);
```

Later I'm removing these listeners anyway when process ends.

I'm going to commit my changes with test data clean-up shortly.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 @JoelProminic , please, give some some test with Moonshine build revision 997, if this problem now resolved for you. 

(Piotr, build has updated at nightly build section)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I'm not able to reproduce this issue. It looks like it is working.

**Comment by JoelProminic** [comment]
I have not seen this issue reproduce either.  I will close this issue, and we can reopen it if see it trigger again.
