### ISSUE TITLE
Getting started should shown on every Moonshine start

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#490]
Description need to be updated.

**Comment by rat-moonshine** [comment]
After a discussion with @JoelProminic we agreed to have following conditions set to on opening of Getting Started tab during Moonshine start:

1. The tab should display if _any_ of the item listed there found not installed
2. The tab won't open if all the items from its list found installed
3. This tab will accompany a "Do not show again" checkbox - if selected, it'll overrule 1; However, user can still able to open the tab from `Help -> Getting Started`

**Comment by piotrzarzycki21** [comment]
We should also specify what does that mean "installed":
1) Does that mean that user has all settings setup in File -> Settings menu ?
2) Does that mean user have all SDK in Moonshine SDKs folder ?

**Comment by rat-moonshine** [comment]
I think "installed" logic will remain the same way as it is now.

**Comment by rat-moonshine** [comment]
[These](https://github.com/prominic/Moonshine-IDE/issues/490#issuecomment-476978140) conditions now set.

**Comment by rat-moonshine** [comment]
Following are the updated Getting Started tab opening test matrix:

Case | Environment Var. | Default SDK Location | 'Do not show' | Getting Started opens
-------------------- | --------- | ----------- | --------- | -------------
Moonshine path not exists | No | No | Yes | No
'Reset All Settings' | No | No | Yes | No
Manually open Getting Started | No | No | Yes | Yes
Moonshine path not exists | No | No | No | Yes
Moonshine has all default path set. MSDKI has few items not downloaded, i.e. Feathers | No | - | No | Yes
-same as above- | No | - | Yes | No

Following are path setting logic to Moonshine after structural changes in MSDKI:

Case | Environment Var. | Default SDK Location | Action
--------------- | ------- | ------- | -------------------
Moonshine path not exists | No | No | MSDKI downloads SDKs to default location and set Moonshine paths by default SDKs location
Moonshine path not exists | Yes | No | Moonshine paths set by environment variables'
Moonshine path not exists | No | Yes | Moonshine paths set by default SDK download location's paths
Moonshine path not exists | Yes | Yes | Moonshine paths set by default SDK download location's paths
Moonshine path not exists but SDK list has item (in case of default SDK) | No | No | Default SDK path set by first item in SDK list

**Comment by piotrzarzycki21** [comment]
Do we need tests only so to close that ?

**Comment by JoelProminic** [comment]
I did some quick tests with a couple of the SDKs and the "Do not show" checkbox, and this seems to be behaving properly according to the original specification.
