### ISSUE TITLE
Improvement to About screen

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#491]
The About page should show all configured SDK/framework versions. 

Use a table format to keep this tidy.

**Comment by JoelProminic** [comment]
This looks good on macOS:
![image](https://user-images.githubusercontent.com/24532731/56066798-89a29580-5d3e-11e9-90f7-20291888946d.png)

However, I got this on my VDI, even though Getting Started showed that every SDK had been installed:
![image](https://user-images.githubusercontent.com/24532731/56066837-b22a8f80-5d3e-11e9-9c03-a827d63b535d.png)

On my first attempt, I also got SVN and Git results in the first two entries:
![image](https://user-images.githubusercontent.com/24532731/56066910-dedea700-5d3e-11e9-9fab-fa80d43719ef.png)

**Comment by rat-moonshine** [comment]
Inspecting the case on my Vagrant VM, it turned out most of the version-call to the executable were failed throwing java-not-found output:

```
: 'java' is not recognized as an internal or external command,
: operable program or batch file.
: 'java' is not recognized as an internal or external command,
: operable program or batch file.
: 'java' is not recognized as an internal or external command,
: operable program or batch file.
: 'java' is not recognized as an internal or external command,
: operable program or batch file.
: 'java' is not recognized as an internal or external command,
: operable program or batch file.
: openjdk version "1.8.0_202"
: 
: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08
: )
: 
: OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)
: 
: '"java.exe"' is not recognized as an internal or external command,
: operable program or batch file.
: The JAVA_HOME environment variable is not defined correctly 
: This environment variable is needed to run this program 
: NB: JAVA_HOME should point to a JDK not a JRE 
: 'java' is not recognized as an internal or external command,
: operable program or batch file.
: 'java' is not recognized as an internal or external command,
: operable program or batch file.
: git version 2.20.1.windows.1
```

In above chain of calls, only a few calls were returned well.

We have runtime environment setup process created recently #456 . To have this process work properly, we requires to execute all the target commands written in a batch file (on Windows) and execute at once. 

To have the About screen's version-list fetch, we need to have all the version-fetch command written in the same file and execute once - but that will return a bulk of text and will be difficult to determine texts belongs to executable.

Other thing is doable if we execute every version-fetch command by executing individual batch files - that will also set *_HOME variables every time (during the execution) but I don't think this would make any big effect. I'll work per this implementation for now.

**Comment by rat-moonshine** [comment]
This should work now on Vagrant.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I thought this issue is for 2.2.0. What has changed ?

**Comment by rat-moonshine** [comment]
This issue have covered some time back. We should be good to bundle this with v2.1.0 only.

**Comment by piotrzarzycki21** [comment]
Well I'm not in favor of mentioning in CHANGELOG if it looks like that now:
![about](https://user-images.githubusercontent.com/24554795/56144442-a9d28e80-5fa2-11e9-86a8-b3b28b07ccab.png)

- It displays some additional information which is completely unrelated like: JAVA_TOOL_OPTIONS.
- Some SDKs have wrong build number
- Mave on my Machine is installed (no MAVEN_HOME), but I'm getting info that is not available - not sure if it's ok
- Default SDK - doesn't make sense right now
- I think SDKs should have their logos near names as it is in Getting Started

If all above issue can be fixed for 2.1.0 I agree it can be part of that build, if not move that to 2.2.0.

**Comment by rat-moonshine** [comment]
Your system output is quite weird. 

Do one thing for each of the executable to give me data. 

These version numbers are populates against fields configured to Moonshine only. It doesn't care what is in your system environment variable. 

1. Check if you have Apache Flex SDK type of SDK exists in your SDK list or not (probably you would have one)
2. Get the path of that Flex SDK, append "/bin/mxmlc.bat --version" and run on your command line
3. Provide me the full output
4. Do 2-3 for Adobe AIR version too - this time you should append "/bin/adt.bat -version"
5. Check if you have any Maven path set in your Moonshine configuration or not
6. Check if the path is valid or not
7. Test what if you run your Moonshine configured Maven path appending "/bin/mvn.cmd -version" on command-line and return me the output

**Comment by piotrzarzycki21** [comment]
> Your system output is quite weird.

I agree on that completely, cause my Windows system in general is weird. :)

**Comment by piotrzarzycki21** [comment]
> 1. Check if you have Apache Flex SDK type of SDK exists in your SDK list or not (probably you would have one)

Yes I have:
![yes_id](https://user-images.githubusercontent.com/24554795/56145844-5ca3ec00-5fa5-11e9-8a26-ef28fc5589bf.png)

**Comment by piotrzarzycki21** [comment]
> 2\. Get the first occurrence of Flex SDK (in SDK list) path, append "/bin/mxmlc.bat --version" and run on your command line

Full output:
```
c:\MoonshineSDKs\Flex_SDK\Flex_4.16.1_AIR_32.0\bin>mxmlc.bat --version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Version 4.16.1 build 20171115
```

**Comment by piotrzarzycki21** [comment]
> 4\. Do 2-3 for Adobe AIR version too - this time you should append "/bin/adt.bat -version"

```
c:\MoonshineSDKs\Flex_SDK\Flex_4.16.1_AIR_32.0\bin>adt.bat -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
32.0.0.89
```

**Comment by piotrzarzycki21** [comment]
> * Check if you have any Maven path set in your Moonshine configuration or not
> * Check if the path is valid or not

Yes I have path setup and yest it is valid path. 
![maven](https://user-images.githubusercontent.com/24554795/56146215-2450dd80-5fa6-11e9-8166-374a292a1a72.png)

**Comment by piotrzarzycki21** [comment]
> 7\. Test what if you run your Moonshine configured Maven path appending "/bin/mvn.cmd -version" on command-line and return me the output

Output for Maven version:
```
c:\Maven\bin>mvn.cmd -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: c:\Maven\bin\..
Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.2
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by rat-moonshine** [comment]
Your system command-line output is not normal. I don't know why is this, generally the version prints as first line. 

Having practically no eyes of what can return by the "--version" command, I can only go by regular output by this command, and take the first line of the output. 

On Maven, I see you have configured to "maven/bin" - is that path is workable with other Moonshine functionality? If yes, then I'll need to add another test to determine the "mvn.cmd" location other than appending "/bin/mvn.cmd" (which is currently).

**Comment by JoelProminic** [comment]
For Piotr's "JAVA_TOOL_OPTIONS" issues, we could use a regular expression to find the first line that seems to contain a version number:
- Partial match:  \d+\.\d+.\d+
- Full match:  ^.*\d+\.\d+.\d+.*$

I was able to reproduce the Flex SDK behavior Piotr reported by changing the default SDK to a Royale SDK.

![image](https://user-images.githubusercontent.com/24532731/56162058-be0d9000-5f90-11e9-8970-a8e60bcb6eab.png)

Note that both "Apache Flex SDK" and "Feathers" seem to use the Default SDK rather than the first configured SDK of that type.

**Comment by rat-moonshine** [comment]
Using RegExp format to identify version number is a good idea. This now incorporated. 

However, I noticed some strange behavior on my Windows' tests while testing the above report when Royale SDK set as default SDK in Moonshine. I noticed that if Royale SDK set as the default SDK to Moonshine and therefore set Moonshine's local environment variables, any SDK's version request always returns Royale's version only. 

To test the scenario,
1. Run a command-prompt on Windows
2. Set the `FLEX_HOME` to a valid Royale SDK path, i.e. `set FLEX_HOME=G:\ApacheFlexSDK\apache-royale-0.9.4-bin-js\royale-asjs`
3. Set the path to use in opened command-prompt: `set PATH=%FLEX_HOME%\bin;%PATH%`
4. Now request version number by any downloaded Flex SDK, i.e. `G:\ApacheFlexSDK\4.16.1_AIR_28.0\bin\mxmlc.bat --version`
5. Command-prompt returns the version figure of Royale, i.e. `Version 0.9.4 build 0`

The result answers why Piotr or Joel seeing wrong (or Royale's) version number to Flex or Feathers SDKs. I'm wondering how a different-direct-path version request messed up with the value in `FLEX_HOME`.

**Comment by piotrzarzycki21** [comment]
> On Maven, I see you have configured to "maven/bin" - is that path is workable with other Moonshine functionality? If yes, then I'll need to add another test to determine the "mvn.cmd" location other than appending "/bin/mvn.cmd" (which is currently).

As far as I know it's working with other functionalities.

**Comment by piotrzarzycki21** [comment]
> * Run a command-prompt on Windows
> * Set the `FLEX_HOME` to a valid Royale SDK path, i.e. `set FLEX_HOME=G:\ApacheFlexSDK\apache-royale-0.9.4-bin-js\royale-asjs`
> * Set the path to use in opened command-prompt: `set PATH=%FLEX_HOME%\bin;%PATH%`
> * Now request version number of any different Flex SDK, i.e. `G:\ApacheFlexSDK\4.16.1_AIR_28.0\bin\mxmlc.bat --version`
> * Command-prompt returns the version figure of Royale, i.e. `Version 0.9.4 build 0`

Above scenario is a bit weird to me - who would setup FLEX_HOME to Royale SDK ? You shouldn't bother about that. I see also that version of build is 0 - I will take a look why it is happen.

**Comment by piotrzarzycki21** [comment]
I have submitted issue to Royale compiler https://github.com/apache/royale-compiler/issues/86

**Comment by rat-moonshine** [comment]
> Above scenario is a bit weird to me - who would setup FLEX_HOME to Royale SDK ? You shouldn't bother about that. I see also that version of build is 0 - I will take a look why it is happen.

When a SDK is set to Moonshine as its default SDK, in the process of setting local environment variables to Moonshine we set `FLEX_HOME` by the default SDK path. This default SDK could be Flex, Feathers or Royale SDK type of. 

Are you suggesting we shouldn't set `FLEX_HOME` with Royale path? I'm worrying non-setup of FLEX_HOME might fail different functionalities in different place.

**Comment by piotrzarzycki21** [comment]
If default SDK for us is that which is setup in main Settings of Moonshine, we should rather have internal field which is holding reference to that SDK instead using FLEX_HOME. Probably in case of Royale we should use ROYALE_HOME. 

However above idea is something for 2.2.0 or farther

**Comment by rat-moonshine** [comment]
The need of having `FLEX_HOME` usage came out a needful thing when navigating through different features in Moonshine, specially when in a fresh Windows system like Vagrant tested by us. We probably can't remove setting of local FLEX_HOME as this will bring back many a problem those we discovered in recent times. 

We can set ROYALE_HOME in case if Royale SDK set as default SDK to Moonshine, but we require to test if non-setup of FLEX_HOME not breaks something again. 

Furthermore, this is even more strange, why setting up FLEX_HOME with Roayle SDK path messing version request values from other executable.

**Comment by rat-moonshine** [comment]
About screen software version now testing returned string for probable version figure with following RegExp format:
` \d+.\d+.\d+`

Using the other format seems creating problem in ActionScript, though:
`^.\d+.\d+.\d+.$`
([RegExp Tester](http://probertson.com/resources/projects/actionscript-regexp-test/RegExpTestHarness.html))

Some compiled-tests are still due as timestamp generation URL is failing at this moment (http://timestamp.comodoca.com/rfc3161) for some reason, we'll test this later.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 can you please confirm after recent changes if you now get rid of the extra line displaying in About section ("Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8"):

> c:\MoonshineSDKs\Flex_SDK\Flex_4.16.1_AIR_32.0\bin>mxmlc.bat --version
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
> Version 4.16.1 build 20171115

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 can you please confirm after recent changes if you now get rid of the extra line displaying in About section ("Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8"):
> 
> > c:\MoonshineSDKs\Flex_SDK\Flex_4.16.1_AIR_32.0\bin>mxmlc.bat --version
> > Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
> > Version 4.16.1 build 20171115

I have now a bunch of nulls in about screen:

![about](https://user-images.githubusercontent.com/24554795/56267766-11e2bb00-60f0-11e9-93a7-8543893df32b.png)

**Comment by piotrzarzycki21** [comment]
Here you go:
```
D:\Work\projects\Prominic.NET\MoonshineTests>setLocalEnvironment.bat
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Version 4.16.1 build 20171115
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
32.0.0.89
```

Note that I did setup Flex SDK path to those downloaded by Moonshine Getting Started page, but for Royale I have set path to Nightly build which I have on `D:\Work` etc...

**Comment by rat-moonshine** [comment]
I took measure to the problem hopefully it'll rectify at your case. Please, give a test with build later than 1144.

**Comment by JoelProminic** [comment]
The About screen looks correct for me on macOS and Windows.  The process is a bit slow, though - it was taking 2-5 seconds for each entry.    

This should be fine for the 2.1.0 release.
