### ISSUE TITLE
Exclude 'Tour de Flex' files from being shown in RECENT section

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#495]
Currently, opening any Tour De Flex article also adds its source-file link to the RECENT section, but they do not open with the expected editor as RECENT section do not include necessary attributes to the event that make the event handle as Tour de Flex articles.

Upon discussion we agreed that it'd be best to prevent Tour de Flex files from being included in RECENT.

**Comment by piotrzarzycki21** [comment]
I'm not sure why you have raised separate issue instead reopened #489 which had all discussion related to that. This is not actually a Task but rather Bug.

**Comment by rat-moonshine** [comment]
> 
> 
> I'm not sure why you have raised separate issue instead reopened #489 which had all discussion related to that. This is not actually a Task but rather Bug.

I don't have any strong objection if we want to continue this task with #489 but we never able to reproduce the original error reported in #489 . However, we also agreed that showing up the article link is not right in RECENT section; I think this is more of a managing task than bug. If you feel strongly to this then go ahead and open this to #489, we'll continue tracking there.

**Comment by rat-moonshine** [comment]
I'm closing this as fixed, reopen this if any problem found.
