### ISSUE TITLE
Project Import Fails when Main Application File is not in Base Source Directory

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#498]
I was trying to import some Prominic projects from SVN today.  The checkout worked, and I was prompted to use the Project Import interface to open the project.   I was able to select the source directory, but I could not choose a main file when the main file was not directly in the src directory.

I was able to reproduce this with these steps:
1. Create a new ActionScript AIR project
2. Create a folder under src called "test"
3. Create a new .as file under src/test
4. Right click on the new .as file and select "Set as Default Application"
5. Delete the original .as file
6. Close the project
7. Delete the .as3proj file
8. Project > Open/Import Project
9. Update the "Project name" to match the original name.  NOTE:  why isn't this derived from the directory name by default?
10. Choose "ActionScript Project" for Select Template Type
11. Use Browse dir to set the "Main source folder"
12. Try to set the "Main application file" with Browse file.  BUG:  the prompt is blank

![image](https://user-images.githubusercontent.com/24532731/55116078-2bc24c80-50b4-11e9-972a-a04ef846d26d.png)

Note that the prompt reports "Source file should be immediate children of main source folder"  ('children' should be 'child' if we keep this).  However, we support subdirectories for the application fclass, so we should support it on import as well.  This will be helpful for importing production projects.

(This is outside the scope of this issue, but we should be thinking about how we will import other project types, like Java Maven.  Does "Main application file" suppport .java or other file types?)

**Comment by piotrzarzycki21** [comment]
> However, we support subdirectories for the application fclass, so we should support it on import as well.

I don't understand to what you are referring to here - Do you mean popup where you are creating new class ?

**Comment by piotrzarzycki21** [comment]
In the other words you are proposing here to have tree of your project. However if I correctly understand it would be actually tree of source directory ?

**Comment by JoelProminic** [comment]
I mean the that the "Set as Default Application" feature does not require that the main application class is directly in the src directory, as shown by steps 2-4:
>2. Create a folder under src called "test"
>3. Create a new .as file under src/test
>4. Right click on the new .as file and select "Set as Default Application"

So this does not seem to be a fundamental limitation.

Yes, I would expect to see a tree representing the contents of the selected src directory.

**Comment by piotrzarzycki21** [comment]
I'm on it, but it looks like it is a bit more work than I thoughts, so I will provide solution probably tomorrow.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed changes which allows you point to main application file placed in different folder than source. In the other words I have added Tree component to the popup. Next bamboo build should have all changes.
