### ISSUE TITLE
Cannot Update Invalid Library Paths

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#499]
I got errors today when trying to fix an invalid Library path in an imported project.

1. Create a new Actionscript AIR Project
2. Create a directory called "libs"
3. Copy a SWC to the libs directory
4. Open the the Paths tab in Project Settings
5. Add the SWC as a library.  NOTE:  this opens the ~/Desktop directory by default.  It should use the last opened directory or the project directory instead
6. Save the settings
7. Try Project > Build & Run to make sure that the project configuration is valid
8. Rename "libs" to "lib"
9. Try Project > Build & Run.  This opens the Access Manager to resolve the Unaccesible Dependencies
10. Click the Add button for the invalid path, and select to the "lib" directory
11. BUG:  Moonshine reports "<swc> does not exist on the filesystem."
12. Open the the Paths tab in Project Settings
13. Click "Browse file" for the entry in Libraries, and select the SWC at the new location
14. BUG:  Moonshine reports "<swc> does not exist on the filesystem."

I saw these errors on the console:

    : Unable to access file:/Users/<user>/Documents/Flex/temp_workspace/TestLibraryPaths_0327/libs/away3d-core-fp11_4_1_6.swc
    : Unable to access file:/Users/<user>/Documents/Flex/temp_workspace/TestLibraryPaths_0327/libs/away3d-core-fp11_4_1_6.swc

Note that this references "libs" instead of "lib".  For some reason, it seems to check the old path.

**Comment by rat-moonshine** [comment]
Added settings' path validation and error reporting (if path/s are invalid) prior to compilation of any project (i.e. Flex, ActionScript, Java etc.). This will trigger before validating bookmarks on OSX.

An error reporting may consists of one or multiple path values based collected from different sources:
![image](https://user-images.githubusercontent.com/24370870/55160274-fd627100-5188-11e9-9c46-d0d8ba48fbe3.png)

User will need to fix the path error and then continue again.

**Comment by piotrzarzycki21** [comment]
@JoelProminic could you test it so we could close for 2.1.0 ?

**Comment by rat-moonshine** [comment]
We recently noticed that selecting any file/folder through "Browse dir" option in project's `Settings -> Paths` thrown exception in following scenario:
- A previous path already exists to the Settings
- The previous path does not exists in the file system
- Selected a new path by "Browse dir" option

This issue is now rectified.

**Comment by JoelProminic** [comment]
I tested some of the other path entries, and I couldn't reproduce the error I reported above.
![image](https://user-images.githubusercontent.com/24532731/55976963-40c1e280-5c53-11e9-96e2-90fca3ee82b8.png)

While we are thinking about this interface, there are a couple minor updates I would like to see:
- Show a red 'x' if a path is invalid.   This will be better to draw the user's attention to the entries that need to be fixed.
- Currently file choosers for new path entries always open to ~/Desktop.  This should instead open to either the project base directory or the last open directory.  Using the last open directory would fit better with the file chooser logic in the rest of the application.

**Comment by piotrzarzycki21** [comment]
> I tested some of the other path entries, and I couldn't reproduce the error I reported above.
> ![image](https://user-images.githubusercontent.com/24532731/55976963-40c1e280-5c53-11e9-96e2-90fca3ee82b8.png)
> 
> While we are thinking about this interface, there are a couple minor updates I would like to see:
> 
> * Show a red 'x' if a path is invalid.   This will be better to draw the user's attention to the entries that need to be fixed.
> * Currently file choosers for new path entries always open to ~/Desktop.  This should instead open to either the project base directory or the last open directory.  Using the last open directory would fit better with the file chooser logic in the rest of the application.

@rat-moonshine I propose close this issue and open new one if above suggestions.

**Comment by rat-moonshine** [comment]
I have added the red cross-icon against invalid paths. 

Opening file-browser-by-path fix I would like to move to v2.2 or later, as this will surely cost me time and different test cases. I can only remember using regular API process gave me trouble on sandbox against this.

**Comment by piotrzarzycki21** [comment]
> I have added the red cross-icon against invalid paths.
> 
> Opening file-browser-by-path fix I would like to move to v2.2 or later, as this will surely cost me time and different test cases. I can only remember using regular API process gave me trouble on sandbox against this.

That's ok. Just raise different issue for that work and close this one.

**Comment by JoelProminic** [comment]
The updated icons are an improvement.  In the future, we may want to consider making this more obvious, like highlighting the entire path in read, but this is fine for now:
![image](https://user-images.githubusercontent.com/24532731/56049379-f3a34680-5d0e-11e9-8c4a-17aea1706a34.png)

**Comment by piotrzarzycki21** [comment]
> Opening file-browser-by-path fix I would like to move to v2.2 or later, as this will surely cost me time and different test cases. I can only remember using regular API process gave me trouble on sandbox against this.

Please raise issue for that. I'm closing this one.
