### ISSUE TITLE
Moonshine-IDE opens App Store Helper instead of Moonshine SDK Installer

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#505]
As reported by @JustinProminic ,

> I updated Moonshine through the App Store on my Mojave machine and ended up with an old version of AppStore Helper opening, without telling me it is an old version.
> 
> It is very important the Moonshine IDE know whether it needs to direct the user to download the latest SDK Installer.
> 
> it is also important that the SDK Installer itself knows whether it is the latest version for the given Moonshine that is installed.
> 
> ![image](https://user-images.githubusercontent.com/24370870/55603929-d7d9f680-578a-11e9-903d-7eb83d738b58.png)
>

**Comment by piotrzarzycki21** [comment]
I would really want to have mechanism which checks whether we have installed newest version. Is this what failed here, cause we have such mechanism ?

**Comment by rat-moonshine** [comment]
I think this is probably id related.

**Comment by rat-moonshine** [comment]
On update logic issue:
- On Windows, Moonshine checks current installed 64-Bit SDK Installer's version, compare it with remote updater XML, and download latest SDK Installer files as requires - this part all completes silently
- On OSX, since SDK Installer installs as .pkg, the application check for new updates in a fashioned way during application startup, and notify the user appropriately

We can discuss on showing a new (SDK Installer) update message in Getting Started tab on OSX, based on remote update notification file, though.

**Comment by rat-moonshine** [comment]
![newInstall](https://user-images.githubusercontent.com/24370870/55856047-c166dd00-5b86-11e9-95ea-044f7408ac49.png)

**Comment by rat-moonshine** [comment]
![newInstall](https://user-images.githubusercontent.com/24370870/55856117-fecb6a80-5b86-11e9-90fc-40aaa82404f6.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine That changes make it working fine ?

**Comment by JoelProminic** [comment]
This works fine for me on macOS and Windows.  The application duplication on macOS is annoying, but I don't think we can avoid it (we should have fixed this before the 2.0.0 release...).  I will close the issue.
