### ISSUE TITLE
Native extension for bookmarking is broken on OSX post certificate renewal

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#507]
We noticed this problem recently after Mac App certificates renewed and installed to system keychain on OSX build systems. With newer build of Moonshine, we noticed using native file-browsing throws error to Moonshine console on OSX. File-browsing completely handles by the extension to avail file-bookmarking to the browsed location in sandbox.

After investigation, it turned out following error message throws while trying to bookmark any file-path with Obj-c API:

`Error Domain=NSCocoaErrorDomain Code=256 "Failed to retrieve app-scope key" UserInfo={NSDebugDescription=Failed to retrieve app-scope key}`

Reading different articles, it looks like it's a signing issue:
https://forums.developer.apple.com/thread/46583
https://stackoverflow.com/questions/13392077/unable-to-get-app-scoped-bookmark-for-file-os-x-sandbox

However, other communications between the extension and Moonshine application works fine.

So far I tried to test with all possible combination of certificates those I have in my system, but none worked. It looks like it continued missing something. I'm still having the above error after all of the tests.

**Comment by rat-moonshine** [comment]
I installed Vagrant macOS from [this](https://app.vagrantup.com/yzgyyang/boxes/macOS-10.14) location on my Windows system. Installation completed without any trouble.

When boot-up the VM, I started by this following prompt, then a list-of process starts in command-line to the screen, at a time when they over, the screen returns to this following screen again. After returning to the screen multiple times, the VM aborted:

![VirtualBox_macOS1014_Moonshine_default_1554881352670_57575_10_04_2019_13_13_59](https://user-images.githubusercontent.com/24370870/55861054-350ee700-5b93-11e9-8bf3-98c425ed1b06.png)

**Comment by JoelProminic** [comment]
I still see an error like this:
1. Open Moonshine
2. Open Moonshine Settings
3. Open Git tab
4. Click Browse for the Git Binary.  NOTE:  this opens to ~/Desktop for me, even though I have an existing path set
5. Browse to /Library/Developer/CommandLineTools/usr/bin/git
6. Get Error #2004 on the console 

    : Error #2004
    : ArgumentError: Error #2004
    : 	at Error$/throwError()
    : 	at flash.filesystem::File/set nativePath()
    : 	at actionScripts.impls::IFileBridgeImp/browseForOpen()
    : 	at actionScripts.plugin.settings.renderers::PathRenderer/selectPath()
    : 	at actionScripts.plugin.settings.renderers::PathRenderer/___PathRenderer_Button2_click()


Note that this is the same path that was configured from MoonshineSDKInstaller, so there was already a bookmark added.

**Comment by rat-moonshine** [comment]
It looks like OSX has its own set of rules on file selection through its file-browsing dialog. 

Selecting a path like `/Library/Developer/Command Line Tools/usr/bin/git` throws following error from the bookmarking extension:

`Error Domain=NSCocoaErrorDomain Code=256 "Could not open() the item" UserInfo={NSURL=file:///Library/Developer/CommandLineTools/usr/bin/git, NSDebugDescription=Could not open() the item}`

I also found how the said rule differ in cases:

```
// works
../Downloads/MoonshineSDKs/Flex_SDK/$flexSDKname/bin/{any executable}
/Users/$user/$flexSDKname/bin/{any executable}
/Library/Developer/Command Line Tools
/Applications/XCode.app

// do not works
/Applications/XCode.app/Contents/MacOS/XCode
/Library/Developer/Command Line Tools/usr/bin/{any executable}
```

I'm not sure how to pass such restrictions in sandbox, but I added to alert the corresponding error as returned by the bookmarking api.

**Comment by JoelProminic** [comment]
I haven't seen any more issues that seem to be related to the bookmark API, so I am closing this issue.
