### ISSUE TITLE
Project File Syntax Highlighting

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#509]
@JustinProminic reported that .javaproj files do not have syntax highlighting.   I confirmed the same behavior for .as3proj and .veditorproj files.

Since these files use XML format, we should use the XML syntax highlighting.

**Comment by rat-moonshine** [comment]
Syntax highlighting decides on file's extension. Until now it was only 'xml' extension check. 

I have added following extension to its check-list:
- javaproj
- as3proj
- veditorproj

If you remember any other file types that can include to this list, let me know.

**Comment by piotrzarzycki21** [comment]
I think that's all for now. It looks like it is working now.

**Comment by JoelProminic** [comment]
The syntax highlighting looks right for all three of those file types now.  I verified that it is still being used for XML files as well.
