### ISSUE TITLE
Can't resolve chosen bead

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#51]
I create a Panel component, add js:beads and type IBe - drop down list appears and I choose IBeadModel.

After correcting the insertion position of the new namespace, hovering over IBeadModel shows this 

![ns error](https://user-images.githubusercontent.com/32083838/31813602-94b31e96-b5b9-11e7-86d7-f9a5b7430dcf.png)

The code underneath the pop-up as follows

js:Panel xmlns:fx="http://ns.adobe.com/mxml/2009"
		  xmlns:js="library://ns.apache.org/flexjs/basic"
		  xmlns:ns1="org.apache.flex.core.*"

Have I made some mistake here? 

Doug

**Comment by piotrzarzycki21** [comment]
Hi @doug777 ,

You probably didn't make any mistake. I believe it is related to that issue #44 . If you experience such issue just correct namespace to <js: in mxml. 
Additionally probably this suggestion is correct, cause IBeadModel is an interface, so you shouldn't use it in <js:beads.

**Comment by doug777** [comment]
Oh yes you're right. Changed it and it's working now. Thanks

Doug
