### ISSUE TITLE
Selected component in Visual Editor organizer doesn't highlight code

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#511]
When I select any component in Visual Editor Organizer, code of selected component should be highlighted as well.

**Comment by rat-moonshine** [comment]
Was the feature turn broken?

**Comment by piotrzarzycki21** [comment]
> Was the feature turn broken?

It doesn't work right now.

**Comment by rat-moonshine** [comment]
This should work you now again.

**Comment by piotrzarzycki21** [comment]
Yes it's working now! Thank you for a quick fix!

**Comment by JoelProminic** [comment]
It is working properly for me as well.  I tested with some of the converted Domino forms, and it worked fine for the more complicated cases I tried.
