### ISSUE TITLE
Access Manager Error with Java Project

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#514]
I noticed today that File > Access Manager triggers an error with the Moonshine 2.1.0 builds on macOS.  

    : Error #1034
    : TypeError: Error #1034
    : 	at actionScripts.utils::OSXBookmarkerNotifiers$/checkAccessDependencies()
    : 	at actionScripts.plugin.actionscript.as3project.files::SaveFilesPlugin/openAccessManager()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
    : 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
    : 	at actionScripts.ui.menu::MenuPlugin/redispatch()

@rat-moonshine traced this to the new JavaProjectVO class:

>rat-moonshine: Okay some more data on Access Manager crash. 
>rat-moonshine: It happens when you have a Java project opens to sidebar 
>rat-moonshine: Not any other project will cause this crash 
>JoelProminic: Ah, I fixed it by disabling the Input Sources shortcuts. 
>JoelProminic: Hmm, is it missing an expected setting, maybe? 
>JoelProminic: For the Java project 
>rat-moonshine: Yes, I think that is the reason.  
>rat-moonshine: checkAccessDependencies() method loads some configuration data from its settings file 
>rat-moonshine: Perhaps some configuration is never stored for the projec! 
>rat-moonshine: I can check that now one moment 
>JoelProminic: Java projects have very limited settings for now. 
>rat-moonshine: Got it. 
>rat-moonshine: Until now, or when the method developed, we had only one VO class for projects - AS3ProjectVO 
>rat-moonshine: But now we have JavaProjectVO; type-casting thrown error 
>rat-moonshine: I need to handle the types. There is a base class for all the project VO types - ProjectVO, but some configuration those checking here probably native to AS3ProjectVO

**Comment by rat-moonshine** [comment]
This should work now.

**Comment by JoelProminic** [comment]
I don't see an error for this anymore, and I can add new bookmarks.
