### ISSUE TITLE
File Chooser Errors with Import Project Archive

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#515]
I am getting errors when I try Project > Import Project Archive.  The simplest test procedure is:

1. Project > Import Project Archive
2. Click "Change" for Target Directory
3. BUG:  Error #1009:

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugin.settings.renderers::PathRenderer/openFile()
    : 	at actionScripts.impls::IFileBridgeImp/browseForDirectory()
    : 	at actionScripts.plugin.settings.renderers::PathRenderer/selectPath()
    : 	at actionScripts.plugin.settings.renderers::PathRenderer/___PathRenderer_Button2_click()
    :
    : Click here to Report a Bug 

Similarly, I get this error when trying to chose an archive:

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugin.settings.renderers::PathRenderer/openFile()
    : 	at actionScripts.impls::IFileBridgeImp/browseForOpen()
    : 	at actionScripts.plugin.settings.renderers::PathRenderer/selectPath()
    : 	at actionScripts.plugin.settings.renderers::PathRenderer/___PathRenderer_Button2_click()
    :

And when I submit the form with Import, I get:

    : Click here to Report a Bug
    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugins.as3project::ImportArchiveProject/createSavePreparation()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at MethodInfo-25940()
    : 	at actionScripts.plugin.settings::SettingsView/save()
    : 	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()
    :
    : Click here to Report a Bug

I originally though this issue was related to #507, but @rat-monshine asked me to report is separately.

**Comment by rat-moonshine** [comment]
This should work now.

**Comment by JoelProminic** [comment]
I don't see the errors anymore with the new build.  i was able to import a PrimeFaces and a Flex Browser project from ZIP archives.
