### ISSUE TITLE
AIR SDK directory refused to add by Moonshine

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#516]
- Open Moonshine -> Settings -> Default SDK
- Click on the Change option next to "Default Apache Flex, Royale or Feathers SDK"
- From opening "Select SDK" window try to add a new SDK
- Point to the directory where you downloaded AIR only SDK from [here](https://www.adobe.com/devnet/air/air-sdk-download.html)
- Moonshine shows "Not a valid SDK directory"

**Comment by piotrzarzycki21** [comment]
What projects actually in our stack can use AIR SKD only without Flex or Feathers ?

**Comment by rat-moonshine** [comment]
Prominic has project in pure ActionScript and desktop. The project can work with Flex/AIR SDK, but why not provide option to use AIR only SDK without any overhead of Flex or Feathers framework?

**Comment by piotrzarzycki21** [comment]
Ok but can you build pure AS3 project using AIR SDK ?

**Comment by rat-moonshine** [comment]
Yes, that is something I haven't thought about, it would anyway requires something like `mxmlc` to build the project. The project is separately developed, I have seen that it was pointing to an external AIR SDK only; After you pointing, I re-checked and found it was attached with Feathers SWC! So that perhaps helping in `mxmlc` process. Good to pointing to this.

**Comment by piotrzarzycki21** [comment]
IMO language server may not cooperate with that, so if it doesn't work maybe it doesn't make sense to do such support.

**Comment by rat-moonshine** [comment]
Hm.. that is something I don't know about (if language-server won't support), so I think we can only find out once we add an Adobe AIR SDK and test. 

If Eclipse can do, I think we can also support of adding standalone AIR SDK for such case types, users can do many things you know.

**Comment by piotrzarzycki21** [comment]
I think adding support just to check may be a waste of time. You can try that scenario using VSCode + Josh's extension. If you get any support for code completion or able to build pure AS3 project than we can thing about adding anything.

**Comment by JoelProminic** [comment]
@JustinProminic got in contact with Harman about Apache AIR.  They reported that they had some familiarity with Moonshine, but they had noticed that it didn't have full support for AIR SDKs:

>I noticed that in the SDK set-up, I could select a Flex SDK, but not an AIR SDK..?
> ![image](https://user-images.githubusercontent.com/24532731/58738979-aae24280-83cd-11e9-9d3c-921837d6ee0f.png)
> 
>I get “Not a valid SDK directory.” when I try selecting an AIR SDK folder. I’d be interested to know the reasons for that, although I guess if the main audience is for Flex apps rather than just pure-AS3 apps created using Starling/Feathers, then this makes sense.


We would like to revisit this issue, to see if this is something we cnan easily add.

**Comment by rat-moonshine** [comment]
> 
> 
> @JustinProminic got in contact with Harman about Apache AIR. They reported that they had some familiarity with Moonshine, but they had noticed that it didn't have full support for AIR SDKs:
> 
> > I noticed that in the SDK set-up, I could select a Flex SDK, but not an AIR SDK..?
> > ![image](https://user-images.githubusercontent.com/24532731/58738979-aae24280-83cd-11e9-9d3c-921837d6ee0f.png)
> > I get “Not a valid SDK directory.” when I try selecting an AIR SDK folder. I’d be interested to know the reasons for that, although I guess if the main audience is for Flex apps rather than just pure-AS3 apps created using Starling/Feathers, then this makes sense.
> 
> We would like to revisit this issue, to see if this is something we cnan easily add.

Yes, I was thinking of this issue only.

**Comment by piotrzarzycki21** [comment]
Before we jump into that issue I would like to understand what would be implementation of adding Air SDK to Moonshine. I will express that in email, so do not spend too much time on that today.

**Comment by rat-moonshine** [comment]
> 
> 
> Before we jump into that issue I would like to understand what would be implications of adding Air SDK to Moonshine. I will express that in email, so do not spend too much time on that today.

If your thought pointing to the language-server implications (which you've already noted to this thread), I see language-server is working nice with pure Adobe AIR SDK too! If you think about any other implication, please raise them here too so we'll have them in-note.

**Comment by piotrzarzycki21** [comment]
> If your thought pointing to the language-server implications (which you've already noted to this thread), I see language-server is working nice with pure Adobe AIR SDK too! If you think about any other implication, please raise them here too so we'll have them in-note.

It's working and you have code completion in pure AS3 projects ?

**Comment by rat-moonshine** [comment]
Oh yes! I see that!

![image](https://user-images.githubusercontent.com/24370870/58779958-10644800-85f5-11e9-8aed-8c7db94d1469.png)
![image](https://user-images.githubusercontent.com/24370870/58779992-27a33580-85f5-11e9-9016-f82135a9d400.png)

**Comment by piotrzarzycki21** [comment]
> Oh yes! I see that!
> 
> ![image](https://user-images.githubusercontent.com/24370870/58779958-10644800-85f5-11e9-8aed-8c7db94d1469.png)
> ![image](https://user-images.githubusercontent.com/24370870/58779992-27a33580-85f5-11e9-9016-f82135a9d400.png)

That's wonderful! Once you add support we should provide to Andrew dev version of Moonshine or submit 2.3.0 - did you do that already? We are off the schedule one week I don't won't to wait another one

**Comment by rat-moonshine** [comment]
First of all, the above screens are from my initial tests. I see, we require to have some adjustment for compilation process (Build & Run) in Moonshine, which I'm working onto. Here two thing I see:
1. Give thorough testing of the code-completion using pure Adobe AIR 
2. Test and adjust requisite things in Moonshine to work with pure Adobe AIR SDK

v2.3.0 have already approved by the App Store, and I do not want to hold this release for further implementation. Let's continue with the release of v2.3.0, any further development and testing shall be taken for v2.4.0.

**Comment by rat-moonshine** [comment]
This should be working now. Stock Ant build script also worked without any error in my tests.

I'll add some more details on this later.

**Comment by JoelProminic** [comment]
I downloaded the AIR SDK from here: https://www.adobe.com/devnet/air/air-sdk-download-mac.html
I used the first Download Now link for Mac OS X, which downloaded a DMG.

I noticed there was no installer in the DMG, so I just copied the files to a directory under ~/Downloads/MoonshineSDKs.  I also had to run this command to remove the quarantine attribute:

    xattr -r -d com.apple.quarantine .

After this, I was able to add the AIR SDK to the SDK list, and use it to build a new Actionscript AIR project.

**Comment by rat-moonshine** [comment]
> I also had to run this command to remove the quarantine attribute:
> 
> ```
> xattr -r -d com.apple.quarantine .
> ```

We'll need not to do that if in future we'll decide to provide Adobe AIR download through Moonshine SDK Installer.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Can we close that issue ?

**Comment by rat-moonshine** [comment]
Yes, let's close this if no new issue come-up against this.

**Comment by piotrzarzycki21** [comment]
Hey @ajwfrost,
Moonshine is now recognizing Air SDK itself. If you don't won't to wait for official release you can try development build of Moonshine. I'm not sure which version are you using but here you have [Windows](https://moonshine-ide.com/downloads/releases/dev/windows/) and [Mac](https://moonshine-ide.com/downloads/releases/dev/macos/). Those builds are refreshed whenever we push anything to Moonshine repository.
