### ISSUE TITLE
Moonshine logo needs a small "TM"

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#523]
As the requirement suggested:

> We need to get a small (TM) somewhere on this logo in all locations that it is present.
> 
> We also need to make sure this is on the splash screen.
> 
> It also needs to clearly show Copyright (C) Prominic.NET, Inc. in all of these locations
> 
> Ideally the about page should also show the logo in full size with the (TM)
> 
> AND the Dock icon / Start button should as well please.

> Anytime the words Moonshine IDE appears, it needs to have "Moonshine IDE (TM)" in text.
> 
> Anytime "Moonshine IDE" or the moon with "IDE" written on it appear there needs to be a small (TM) on the graphic.
> 
> The only time you don't need to put the (TM) is on the Mac menu. So don't put it in the menu.  Put it everywhere else please.

**Comment by rat-moonshine** [comment]
- Moonshine website pages updated replacing 'Moonshine IDE' with 'Moonshine IDE ™'
- Logos/icons updated to Moonshine
- Textual referencing updated to 'Moonshine IDE ™' in Moonshine where applicable
- About section added with Moonshine logo and copyright text

Note, having Moonshine logo and copyright text in Home screen requires work to create adequate space which is always visible and not overflow by existing listing/items.

**Comment by rat-moonshine** [comment]
One thing to note, I couldn't found where to edit the curved "Moonshine IDE" text in Moonshine website splash image (if we also want to add the trademark there) so I could able to add the (TM) mark there.

**Comment by JoelProminic** [comment]
I reviewed this while testing the 2.1.0 build before release.

I confirmed that the updated icon is present at:
- The macOS Dock and Windows taskbar
- The macOS Applications folder and Windows start menu
- The macOS spotlight
- The Windows application title bar.
- The About page

The new icon is not yet present at these locations.  This can wait until a later Moonshine release if necessary:
- The Home/Splash screen.


The "TM" was added at:
- The initial console output
- The About Page
- The "Moonshine IDE Project Team" plugin pages in the application settings
- The Getting Started page

I don't see any instances of "Moonshine IDE" in the Moonshine application where this was not updated.

**Comment by rat-moonshine** [comment]
Since this is a 'task' and not includes in the CHANGELOG.md, let's keep this issue open. Once v2.1 release I'll change the milestone to later follow-up logo/copyright incorporation in Home/Splash screen.

**Comment by JoelProminic** [comment]
Adding the logo to the splash screen is not necessary.  I am closing this issue.
