### ISSUE TITLE
Ant Home is Reset When Starting Moonshine

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#53]
While testing #27, I noticed a problem with the behavior for the Ant Home setting.

1. Open Moonshine
2. Open Settings > Ant Build Setup
3. Change Ant Home to a different directory (in my case, I used ~/Downloads/MoonshineSDKs/ant-1.9.7).  (On a side note, the filechooser always opens to ~/Desktop for Ant Home)
4. Save the change
5. Restart Moonshine
6. Open Settings > Ant Build Setup
7. BUG:  the value has been reset to the default (~/Downloads/MoonshineSDKs/Ant/apache-ant-1.10.1

So, if the user tries to use a different copy of Ant (for example, a newer version), then they would have to set the home location again each time they opened Moonshine.

I get the same results if I use a directory outside of MoonshineSDKs:  /Users/joelanderson/.sdkman/candidates/ant/1.9.7

**Comment by rat-moonshine** [comment]
I see the existing logic against setting Ant home path was if Ant SDK found inside the folder that creates by App Store Helper (`~/Downloads/MoonshineSDKs/Ant`), then automatically set the path with the same. This by dismissing any existing path as I see in the logic.

I'm going to make requisite changes per current expectation.

**Comment by JoelProminic** [comment]
I tested this again in preparation for the 1.6.1 release.  I confirmed these cases:
- Setting path to different directory under ~/Downloads/MoonshineSDKs
- Setting path to other directory (~/SDKs/...)
- Resetting the value.
