### ISSUE TITLE
Basic Git Support for Repository Manager

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#530]
For the 2.2.0 release, we would like to add support to manage Git repositories with Repository Manage (#502).  Since Git itself doesn't provide access to list the repository files, this will have limited functionality for Browse.

I extracted this from #503, which will focus more on project dependencies and meta-git projects.

The expected process is:
1. Open Git > Manage Repositories
2. Add a repository, selecting the Git type
3. (Optional) Select the repository and click Browse or Browse All.  This will will not do much when first checking out a Git repository, but I included this for consistency with SVN projects
4. Select the desired repository and click Clone
5. Complete the Clone and click Clone
![image](https://user-images.githubusercontent.com/24532731/56445562-79049900-62c3-11e9-9972-9a9be758e838.png)

I am not sure if we want the Repository list to show Git/SVN.   For now, I favor hiding this and letting Moonshine determine the appropriate buttons and behavior for the project type.

This is just a rough mockup of the interface, so let me know if you have concerns or suggestions.

**Comment by rat-moonshine** [comment]
[BUG] Editing an existing entry throws error:

![image](https://user-images.githubusercontent.com/24370870/56673734-74cae800-66d6-11e9-8edc-b767f1b50ad8.png)

**Comment by rat-moonshine** [comment]
The above duplicate entry error while editing should fix now.

**Comment by JoelProminic** [comment]
Please change the default repository type to "Git".  Reverse the order of the radio buttons so that they are in alphabetical order.

**Comment by JoelProminic** [comment]
For the Clone (and Checkout) prompt, I would like to see the last used parent directory selected by default.  This will save two clicks for each repository while setting up the environment for Moonshine or a similarly complicated environment.   The current directory should be displayed so that the last part of the path is visible, either by positioning or by abbreviating the path.

If the user had not selected a parent directory previously, then this can be left blank.  I'm open to other ideas.

I'd also like to see the "Choose Parent Directory" button replaced with a file icon next to the field.  I think this will be more clear.

Here is an example of how these updates might look:
![image](https://user-images.githubusercontent.com/24532731/57040063-f2857b00-6c23-11e9-9f54-92e1614cf18a.png)

**Comment by rat-moonshine** [comment]
Dotted path probably not possible here as the calculation requires a source and target path. In clone/checkout window we do not have any source but target only. Instead, I make the cursor position move to the end of the text-field to show the last part of the path.

On pre-population of parent directory path, I made it this way:
- When first time the interface will show it will have no value to the field
- Once choose any location by the file-chooser dialog from 'Clone/Checkout Repository' interface, interface will keep populating the field with last-browsed location (location browsed from anywhere inside the application)

"Choose Parent Directory" replaced with folder icon/button as suggested.

**Comment by JoelProminic** [comment]
This is a bit off topic, but I got this error when checking out a new SVN repository from the Checkout button (which was added as part of of this issue) on the Manage Repositories menu:

    : Trying to check out https://svn.../TestMoonshineSubversionJoel. May take a while.
    : svn: E170001: Unable to connect to a repository at URL 'https://svn.../TestMoonshineSubversionJoel'
    : svn: E170001: OPTIONS of 'https://svn.../TestMoonshineSubversionJoel': authorization failed: Could not authenticate to server: rejected Basic challenge (https://svn...)

It looks like the authentication logic did not trigger in this case.  Authentication is still working for exploring the SVN repository in the Browse interface.

**Comment by JoelProminic** [comment]
The text position of the path looks good.   I don't like how the icon looks, though - the white background looks strange, and the folder icon is too small:

![image](https://user-images.githubusercontent.com/24532731/57107149-da316100-6cf4-11e9-8d15-a2da7b82475b.png)

I remember that we previously used an icon for the file browser in the "Define a SDK Path" prompt, but I see this has been broken since at least 2.1.0.

![image](https://user-images.githubusercontent.com/24532731/57107139-d43b8000-6cf4-11e9-8be7-8f2cd1c005f3.png)

**Comment by rat-moonshine** [comment]
Light button background replaced with dark button background with new folder icon. However, I'm not sure how the 'Define a SDK Path' has broken label - it is not suppose to display any icon but text/label. When I tested with newer build on macOS, it properly displayed me 'Browse' text.

**Comment by JoelProminic** [comment]
The SVN authentication issue was resolved.

I think the browse button looks fine for now.  I see the white buttons are more common than I thought in Moonshine - we may want to revisit the skinning for these at some point, and consider replacing the text with icons, but this is a low priority.

![image](https://user-images.githubusercontent.com/24532731/57154121-b24a0800-6d9d-11e9-9f2d-5d06ff802278.png)
