### ISSUE TITLE
Browse All Fails on Empty Repository List

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#531]
I was demonstrating Moonshine to a coworker today, and he noticed that if you click the Browse All button in the Manage Repositories interface when no repositories are defined, Moonshine shows a blank interface and throws an error:

![image](https://user-images.githubusercontent.com/24532731/56446455-680a5680-62c8-11e9-8309-40de7cb71c43.png)

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.ui.renderers::RepositoryTreeItemRenderer/set data()
    : 	at mx.controls::List/http://www.adobe.com/2006/flex/mx/internal::setupRendererFromData()
    : 	at mx.controls::List/commitProperties()
    : 	at mx.controls::Tree/commitProperties()
    : 	at mx.core::UIComponent/validateProperties()
    : 	at mx.managers::LayoutManager/validateProperties()
    : 	at mx.managers::LayoutManager/doPhasedInstantiation()
    : 	at mx.managers::LayoutManager/doPhasedInstantiationCallback()
    :
    : Click here to Report a Bug

This initially triggered on a fresh install of Moonshine, and I was able to reproduce it by removing all entries.

After this, we found that there were other problems with Moonshine.  For example, the checkboxes don't work in the Add Repository prompt.  These issues were resolved once Moonshine restarted.

**Comment by rat-moonshine** [comment]
I couldn't able to reproduce the problem in my initial tests to Windows and macOS. If you still have the repository list and able to produce the error, please send me the cookie file to examine (in email) from the application storage directory.

**Comment by JoelProminic** [comment]
The error occurs when there are no repositories configured.   I updated the description to clarify this.

**Comment by rat-moonshine** [comment]
This should have rectified now. Please, check.

**Comment by JoelProminic** [comment]
I confirmed that this is fixed on macOS.
