### ISSUE TITLE
Add Royale Jewel template project

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#532]
Whenever I would like to create Jewel only type of project I have to create Royale Browser Project and change main application file. Instead doing that my proposition is to have two type of projects:

Royale Browser Project - Basic
Royale Browser Project - Jewel

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I analyzed all mechanism which is responsible for creating what we displaying on Home tab and in File menu. We are basically reading file in templates/projects, [taking their name](https://github.com/prominic/Moonshine-IDE/blob/758ea3df732e0d883ec58880b37be7b58c15786a/ide/MoonshineSharedCore/src/actionScripts/plugin/templating/TemplatingPlugin.as#L301). I would like to change that to be able to display different title than file name. 

I basically need to see when user clicks on **File** -> **New** -> **Royale Browser Project** two types of templates in combobox **Royale Browser Project Basic** and **Royale Browser Project Jewel**.

I was thinking instead having [txt files](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/elements/templates/projects/Royale%20Browser%20Project.txt) I could have xml file instead which holds description for the project and it's title. In the other word I would have **Royale Browser Project.xml** - which provides all information, maybe even list of templates folder for this type of project. You know a bit better from me that mechanism, so the question what do you thing about that idea ?

This is how file **Royale Browser Project.xml** could looks like
```
<templates>
    <template>
         <title></title>
        <name></name>
       <description></description>
    </template>
   <template>
         <title></title>
        <name></name>
       <description></description>
    </template>
</templates>
```

I would also provide such files for other projects, so for example ActionScript Flex type of projects etc. All txt files would be removed.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 I'm good with replacing txt files with XML. I see you read the flow good already.

I'm not sure about the internal mechanism on showing template types (to dropdown) read from the said XML, but that should be good, too. (I think we're populating those template types by static codes at this moment, i.e. [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/CreateProject.as#L276))

**Comment by piotrzarzycki21** [comment]
Another big thing if I make such changes would be, how much I will break mechanism of custom template creation. It is probably related to all of that ? I mean when you go to **File** -> **Settings** -> **Templating**

**Comment by piotrzarzycki21** [comment]
Ok I will dive into that with hope that I won't get drown. ;) No matter what we may have in the future different type of templates for specific type of project - it is need to be handled at some point.

**Comment by rat-moonshine** [comment]
I see this is broken, too.. Let me know if you want me to look into this at some time. I'm not sure which changes brought to this. Maybe, it'd be better if we track this by raising a separate issue.

**Comment by piotrzarzycki21** [comment]
> I see this is broken, too.. Let me know if you want me to look into this at some time. I'm not sure which changes brought to this. Maybe, it'd be better if we track this by raising a separate issue.

If you can try to fix that - I would prefer to focus on this task and yes this make sense to create separate bug for that.

**Comment by rat-moonshine** [comment]
Okay. I'll see this. Please, raise me an issue.

**Comment by piotrzarzycki21** [comment]
I just merged that one to master. There is one thing which I need to fix. build.xml script for Royale Jewel template.

**Comment by piotrzarzycki21** [comment]
I'm done with that. We can now create two types of project in case of Royale. I simplify template loading and we can use XML config to display stuff on Home and Menu [Royale Browser Project](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/elements/templates/projects/Royale%20Browser%20Project.xml)

**Comment by JoelProminic** [comment]
I get this error on macOS (sandboxed) when I open the New Project prompt for a Royale Browser project:

    : Index '-1' specified is out of bounds.
    : RangeError: Index '-1' specified is out of bounds.
    : 	at mx.collections::ListCollectionView/getItemAt()
    : 	at mx.collections::ListCollectionView/http://www.adobe.com/2006/actionscript/flash/proxy::getProperty()
    : 	at MethodInfo-35863()
    : 	at mx.core::UIComponent/callLaterDispatcher2()
    : 	at mx.core::UIComponent/callLaterDispatcher()
    :
    : Click here to Report a Bug


Note that the dialog shows "Royale Browser Project Jewel", but the header shows "New Royale Project Basic".

IMAGE

If I then create a project without changing the Template Type, the project is created from the Basic template instead.

I do not see the RangeError on Windows.


If I test the Royale Jewel project with the current version of Royale from Moonshine SDK Installer (0.9.4), or the latest nightly build (0.9.6), I get errors:

macOS:

    : command line Error: unable to open '/themes/JewelTheme/src/main/resources/defaults.css'.

Windows:

    : C:\Users\vagrant\Documents\TestRoyaleJewel\src\MainContent.mxml(8): col: 71 Error: This attribute is unexpected. It will be ignored.
    : 
    :     <j:ApplicationMainContent hasTopAppBar="true" hasFooterBar="true" selectedContent="content">
    :                                                                       ^
    : 
    : C:\Users\vagrant\Documents\TestRoyaleJewel\src\MainContent.mxml(8): col: 51 Error: This attribute is unexpected. It will be ignored.
    : 
    :     <j:ApplicationMainContent hasTopAppBar="true" hasFooterBar="true" selectedContent="content">
    :                                                   ^
    : 
    : C:\Users\vagrant\Documents\TestRoyaleJewel\src\MainContent.mxml(9): col: 26 Error: This attribute is unexpected. It will be ignored.
    : 
    :        <j:SectionContent name="content">

**Comment by piotrzarzycki21** [comment]
@JoelProminic I just did quick look and I'm not sure why but on Mac some part of the path is being stripped out. We have following parameter for compiler in case of Jewel:
`-theme=${royalelib}/themes/JewelTheme/src/main/resources/defaults.css`
Royale compiler replace royalelib with appropriate path.

**Comment by piotrzarzycki21** [comment]
I just quick debug it and we are sending to Terminal proper path -> `-theme=${royalelib}/themes/JewelTheme/src/main/resources/defaults.css` - It's being stripped out and I have no idea why. I can tomorrow try to grab that argument and replace royalelib with path to SDK - This is what comes to my mind as a workaround. Is it something special for Mac Terminal when such argument like `${royalelib}` appear ?

**Comment by piotrzarzycki21** [comment]
It's late here in Poland, so I will look into any comments tomorrow, but I cannot promise that I will try to implement this workaround due to tomorrow's vacation. I don't won't to as well give users stuff which doesn't build. I'm pretty sure that I was able to build other Jewel stuff earlier on Mac.

**Comment by piotrzarzycki21** [comment]
> Windows:
> 
> ```
> : C:\Users\vagrant\Documents\TestRoyaleJewel\src\MainContent.mxml(8): col: 71 Error: This attribute is unexpected. It will be ignored.
> : 
> :     <j:ApplicationMainContent hasTopAppBar="true" hasFooterBar="true" selectedContent="content">
> :                                                                       ^
> : 
> : C:\Users\vagrant\Documents\TestRoyaleJewel\src\MainContent.mxml(8): col: 51 Error: This attribute is unexpected. It will be ignored.
> : 
> :     <j:ApplicationMainContent hasTopAppBar="true" hasFooterBar="true" selectedContent="content">
> :                                                   ^
> : 
> : C:\Users\vagrant\Documents\TestRoyaleJewel\src\MainContent.mxml(9): col: 26 Error: This attribute is unexpected. It will be ignored.
> : 
> :        <j:SectionContent name="content">
> ```

It looks like my template is not compatible with released version 0.9.4. However I'm more worried with error on Mac than that compatibility.

**Comment by JoelProminic** [comment]
If "${royalelib}" is sent to the command line, then it will be evaluated as an environment variable.   This will be blank unless we define it in the environment.   If this has special meaning , we can escape it like "\\${royalelib}"

**Comment by piotrzarzycki21** [comment]
> If "${royalelib}" is sent to the command line, then it will be evaluated as an environment variable. This will be blank unless we define it in the environment. If this has special meaning , we can escape it like "\${royalelib}"

It may not be the case. It just came to my mind that lately we have change environment variable for Royale to ROYALE_HOME - maybe on Mac compiler has some problem with that and it has to be FLEX_HOME. I need to check that!

**Comment by piotrzarzycki21** [comment]
> ${royalelib}

I checked and using ROYALE_HOME wasn't a problem. I go with your suggestion and I'm setup as environment variable royalelib for Mac users. 
Now build should work, but this template will work only with Royale 0.9.6. I'm for leaving it as is - in the next version of Moonshine we should provide Nightly Build as part of Getting Started as well.

**Comment by JoelProminic** [comment]
Yeah, I see I get this error with Royale-Examples/HelloWorld and the basic Apache Jewel template if I use the 0.9.4 build:

    : /Users/-user-/Documents/Flex/temp_workspace/TestRoyaleJewel3/src/MainContent.mxml(8): col: 71 Error: This attribute is unexpected. It will be ignored.
    :     <j:ApplicationMainContent hasTopAppBar="true" hasFooterBar="true" selectedContent="content">
    :                                                                       ^
    : /Users/-user-/Documents/Flex/temp_workspace/TestRoyaleJewel3/src/MainContent.mxml(8): col: 51 Error: This attribute is unexpected. It will be ignored.
    :     <j:ApplicationMainContent hasTopAppBar="true" hasFooterBar="true" selectedContent="content">
    :                                                   ^
    : /Users/-user-/Documents/Flex/temp_workspace/TestRoyaleJewel3/src/MainContent.mxml(9): col: 26 Error: This attribute is unexpected. It will be ignored.
    :        <j:SectionContent name="content">


This does not leave a good impression, but I don't want to delay the release while we try to get the nightly build downloaded.  (I'm not sure if I even like the idea of using the nightly build in Moonshine SDK Installer, but we can test this with the next release).

The basic Royale Template works fine with 0.9.6.
