### ISSUE TITLE
Clone/Checkout Status Dialog

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#538]
Currently, Moonshine reports the status of a repository clone/checkout on the console only.

Instead, I would like to see:
1. User submits the Clone/Checkout form
2. The dialog updates to show that the operation is in progress.  Ideally this would show a progress bar, but a busy icon sould be sufficient for the initial implementation.
3. Once the Clone/Checkout completes, show a confirmation message.  If the project defined moonshine-dependencies.xml, it should show the Label for the project.
4. Give the user the option to clone/checkout another project, or close the Manage Repositories dialog.

Here is a mockup:
![image](https://user-images.githubusercontent.com/24532731/57041422-c1a74500-6c27-11e9-9abc-154fd9245446.png)

If you think this would significantly delay the 2.2.0 release, it can wait until 2.3.0.

**Comment by piotrzarzycki21** [comment]
@JoelProminic This is something not for 2.2.0 ? Another thought is that we have many places where we need some progress or at least indication that something is taking a bit longer. Progress bar may be used in other places, so make it useful to other views.

**Comment by rat-moonshine** [comment]
I'm not sure how this 'Clone Another' is suppose to work. 

Generally, clone/checkout form populates/avail by 'Manage Repositories' and 'Browse Repositories' window. So user selects an item in said windows and clone/checkout form auto-populates with minimal information. Of course, user can also choose to write his/her own information there and do a clone/checkout. 

'Clone Another' I think can do any from the following option:
1. Reset the form to empty fields and user input a new clone URL - but this may not be that useful
2. Close 'Clone Repository' window and return to 'Manage Repository' and let user select a new one

Here (2) is same as closing the window, I don't see a need of new button-label then. In the design it's mentioned 'Close' button will close 'Manage Repositories' window - which I'd suggest to avoid. It's confusing when a child popup close its parent popup (Manage Repositories -> Clone Repository).

**Comment by JoelProminic** [comment]
Perhaps this is an unrelated issue, but I just noticed that Moonshine is duplicating the project name on the console: (Royale-Examples/Royale-Examples)

    : 'Royale-Examples'...downloaded successfully (https://github.com/prominic/Royale-Examples/Royale-Examples)

**Comment by rat-moonshine** [comment]
- New 'Close All' button added to the clone/checkout interface to close both clone/checkout and 'Manage Repositories' popup at a time.

**Comment by rat-moonshine** [comment]
> 
> 
> Perhaps this is an unrelated issue, but I just noticed that Moonshine is duplicating the project name on the console: (Royale-Examples/Royale-Examples)
> 
> ```
> : 'Royale-Examples'...downloaded successfully (https://github.com/prominic/Royale-Examples/Royale-Examples)
> ```

I saw the message was mixing-up remote URL and local directory value. This should print only remote URL now.

**Comment by JoelProminic** [comment]
The "Close All" button works as expected.  We may update the behavior or labels for these buttons later if they don't feel comfortable in our normal use.

The duplicating name issue was actually because the directory name was appended to the URL.  This is fixed in the latest build.

The status dialog works for SVN.  There was a minor error where authentication errors showed up in the status even after the user authenticated, but this was fixed during our meeting.
