### ISSUE TITLE
Default Repositories for Moonshine

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#539]
We would like to populate some Manage Repositories entries in new installations of Moonshine.  This list will include relevant projects for the users like the Moonshine source and Apache Royale examples

Repository                                  | Notes
--------------------------------------------|----------------------------------
https://github.com/prominic/Moonshine-IDE   | Moonshine-IDE Source Code
https://github.com/apache/royale-asjs       | Apache Royale Source and Examples
https://github.com/prominic/Royale-Examples | Additional Apache Royale Examples

royale-asjs has many examples that will be detected by Moonshine (#529), and they have already been populated with Moonshine directory.

We just created Royale-Examples today.  @piotrzarzycki21 wil populate at least one example, and may add some moonshine-dependencies.xml entries (#503).

For now, the user should be allowed to delete these default entries if they want to clean up their repository list.

**Comment by piotrzarzycki21** [comment]
Maybe it's worth to add my example which I did some time ago as part of [TranspiledActionScript](https://github.com/piotrzarzycki21/TranspiledActionScript). There are two examples which utilize usage of [PureMVC](https://puremvc.org/).

**Comment by rat-moonshine** [comment]
Hm.. somehow I overlooked this issue and reported updates to #503 . Here are the updates for documentation:

Following items will now pre-populate as _default_ items to the 'Manage Repositories':

Repository | Notes
------------------------------------------- | ----------------------------------
https://github.com/prominic/Moonshine-IDE   | Moonshine-IDE Source Code
https://github.com/apache/royale-asjs       | Apache Royale Source and Examples
https://github.com/prominic/Royale-Examples | Additional Apache Royale Examples

Items are allowed to delete. If application storage clears for some reason, interface will again pre-populate with the items.

**Comment by JoelProminic** [comment]
I noticed on Windows that Moonshine duplicated the default repository entries every time that I user Settings > General > Reset to Default.   (Note that Reset to Default should not clear the repository list, since this is user data rather than "settings".  We can change this later if desired.)

I updated the README.md for Royale-Examples.  Currently this has only one project, but we can update this later. 

The HelloWorld project fails for me on Windows and macOS with the same errors I reported here:  https://github.com/prominic/Moonshine-IDE/issues/532#issuecomment-488822330

**Comment by rat-moonshine** [comment]
> I noticed on Windows that Moonshine duplicated the default repository entries every time that I user Settings > General > Reset to Default. (Note that Reset to Default should not clear the repository list, since this is user data rather than "settings". We can change this later if desired.)

I confirm the problem when tested in Vagrant. This have fix now.
