### ISSUE TITLE
Organize Imports command

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#54]

**Comment by piotrzarzycki21** [comment]
@joshtynjala just wanted to confirm that shortcut for organizing imports are:
Windows: CTRL + SHIFT + O
Mac: CTRL + SHIFT + O

What actually we are getting by this feature - Once I executed command - it will remove unused imports ?
Should it work in the MXML <fx:Script> section ?

**Comment by joshtynjala** [comment]
Yes, that's the correct keyboard shortcut.

It will reorganize imports into alphabetical order, remove unused imports, and try to add missing imports (if there aren't multiple classes with the same name).

I think it should work in MXML scripts.

**Comment by piotrzarzycki21** [comment]
I have created following class in Flex Desktop application:

```
package 
{
	import flash.events.MouseEvent;

	public class Test  
	{
		public function Test()
		{
			
		}
	}
}
```

MouseEvent has not been used. When I user CTRL+SHIFT+O - There is no action.

In MXML code I have similar situation and there is no action either:

```
	<fx:Script>
		<![CDATA[
			import flash.events.MouseEvent;

			public function test():void
			{
				
			}
		]]>
	</fx:Script>
```

**Comment by joshtynjala** [comment]
It looks like you found a bug. Apparently, if all imports are to be removed, then it won't remove them.

It works correctly with this code, though:

``` actionscript
package 
{
	import flash.events.MouseEvent;
	import flash.display.Sprite;

	public class Test extends Sprite
	{
		public function Test()
		{
		
		}
	}
}
```

**Comment by joshtynjala** [comment]
It also appears that removing imports is not working in MXML. However, they are correctly reorganized.
