### ISSUE TITLE
Restore Default Repository Entries

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#541]
I talked with Justin about #539, and he wants to either not allow the default entries to be deleted, or give the users a method to bring back the default entries if they have been deleted.

I would like to allow deletion of the entries so that the user can clean up their list if desired, I I favor the second option.

We need to find a place for this action that will be relatively easy for a user to find, but not too intrusive, since it is something users will need rarely.  I think a Help menu item will be fine to start.

**Comment by rat-moonshine** [comment]
What if we restore the items on 'Reset Everything to Default' action? Having a new option in Help may require an additional explanation to the purpose.

**Comment by rat-moonshine** [comment]
A new menu item now created as `Help -> Restore Default Repositories` which should do the purpose. 

The check for item existence done upon repository URL value; if a custom added URL found same as one to default repository URL, that also will consider as exists.

**Comment by JoelProminic** [comment]
I tested the Help > Restore Default Repositories action, and the logic seems to work well.

I see these messages on the console:

    : Default repositories: Items already exists to Manage Repositories under Subversion/Git.
    : Default repositories: Items restored to Manage Repositories under Subversion/Git.

These messages should be updated to:

    : The default repositories are already present in Manage Repositories.
    : The default repositories were restored in Manage Repositories.

**Comment by JoelProminic** [comment]
This looks good.  I am closing the issue.
