### ISSUE TITLE
Modifying Moonshine template do not reflect in new project creation

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#542]
While testing #535 , Joel noticed following problem:

> I confirmed that I don't see any errors when adding, editing, or deleting files. However, when I try to use the template to create a new project, I do not see any of my modifications.

This was my initial understanding to the issue:

> Moonshine creates a new copy of template project to application storage area when modifying. But I couldn't found any relevant code that updates the existing application links to use the version from application storage (instead of regular location).
> 
> I tried to change and update the using-collection that used in project creation, but I noticed separate issues like not using the custom location in first attempt, no reset button and delete/rename button shown up against the modified template entry.
> 
> A delete button is not suppose to be available against default templates, and template name also not permitted to change. The entry should show a reset button only. This seems requires some work, and involvement.

**Comment by rat-moonshine** [comment]
Moonshine now using modified template path instead of the original, if the original template have modified. But this still have some bug inside during expected folder copy/delete process, this requires more tests. One incident is file renaming as mentioned below. 

Upon modification of original template the template folder opens to sidebar for modification. User avail rename option against any file/folder. Having current format of file-name renaming, the renaming window shows the file-name only without an extension (so user not permit to change its extension). The existing logic fail to support renaming a multi-dotted file name properly:

![image](https://user-images.githubusercontent.com/24370870/57222577-b8035000-7020-11e9-9aff-755c422ef9f9.png)

**Comment by rat-moonshine** [comment]
File name with multi-dots now handled in file-rename window.

**Comment by rat-moonshine** [comment]
Both file and project template modified version should use now if the original has modified.

**Comment by rat-moonshine** [comment]
Resetting of original template removes the item from `File -> New` menu - Fixed.

**Comment by JoelProminic** [comment]
This seems to be working fine for me now.
