### ISSUE TITLE
Update the update-notification texts for the App Store version on macOS

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#543]
Currently, we have basic texts added for the update-notification view that needs to be displayed in Mac App Store version of Moonshine saying "-- To be updated --". 

We should not accompany any download link to the interface but a suggestion/advise to update the software through the "App Store" software on macOS.

**Comment by rat-moonshine** [comment]
Here are some information on how Moonshine determines between non-sandbox and the App Store version when both the packages are identical, and we practically have no idea where the package has installed from once installed. Unless, we have some file that provide us different information between non-sandbox and the App Store version. 

We generates an XML file to the package during our Ant build process and modify its value between non-sandbox and the App Store version. In simple word, we read that XML file from its installed location and determines the build based on its value. 

The XML file generates under the package's `elements` folder named `InstallConfig.xml`. It holds a simple XML with tag `isAppStoreVersion` which value varies between the non-sandbox and the App Store version.

**Comment by JoelProminic** [comment]
I would like to figure out a way to test without changing the production configuration.

For example, by my understanding this is reading the XML version file from moonshine-ide.com.  We could remap moonshine-ide.com with the local hosts file and read the XML file from a test server instead.

**Comment by rat-moonshine** [comment]
No, it do not reads from any remote file. We can not rely on remote server for this, internet may not be present at certain time of use. The `InstallConfig.xml` file is local to the application directory. This file generates and bundled during Ant build process. Thus, the file is always available to Moonshine (unless user plays with the application files).

**Comment by JoelProminic** [comment]
I was able to test the update prompt by opening Moonshine.app and changing:
- Contents/Resources/elements/InstallConfig.xml:  make sure the value is true
- Contents/Resources/META-INF/AIR/application.xml - change the version to 2.0.

The window looks like this:
![image](https://user-images.githubusercontent.com/24532731/58204985-1d06a900-7ca3-11e9-93db-f754023cee42.png)

The text should look like:
> New Update Available
> A new version of Moonshine (2.2.0) is available.
> You can download this update from the App Store or from moonshine-ide.com.

Otherwise, this looks good.

**Comment by piotrzarzycki21** [comment]
Is it finished ? If yes please close that.

**Comment by rat-moonshine** [comment]
I'm closing this as fixed. Please, reopen if something we want to change.
