### ISSUE TITLE
Clarify Expected Paths for SDKs

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#545]
From this comment:  https://github.com/prominic/Moonshine-IDE/issues/493#issuecomment-489702601

The user tried to use /usr/local/Cellar/ant/1.10.5/libexec/bin for the path, but /usr/local/Cellar/ant/1.10.5/libexec was expected (don't worry about whether to use libexec for this issue - this is an issue specific to brew and Ant).

We need to make it clear what the expected format should be for the path, for both Ant and the other SDKs.

I see two general ways to do this:
- Include a message indicating the format.  I'm not sure how I would express this, though...
- Validate the path after it is selected.  For example, Moonshine would check $ANT_HOME/bin/ant after the path was set, and if it did not exist, it would report an error like "Invalid path:  Directory must contain bin/ant."

**Comment by rat-moonshine** [comment]
We have a message line below the path-field in settings, which occupies by some pre-defined messages for some. I'm not sure if having many message would attract an user. 

In that case, perhaps a check after setting up a SDK path, and alert accordingly may help better. (we can use the same message line below the path-field, this may complicate the design to some extent as the result would require to return to the origin by some channel)

**Comment by rat-moonshine** [comment]
Suggested notification added to following plugin classes for now:
- Ant
- SVN

**Comment by rat-moonshine** [comment]
Path suggestion added for:
- Java
- Maven
- Gradle
- Git

(Grails path suggestion yet to be added)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Just quick question to that. When you updating Moonshine SDK Installer and Moonshine rebuilds on bamboo. Once I download it do I have as well the freshest development version of Moonshine SDK Installer ?

**Comment by rat-moonshine** [comment]
Yes, @piotrzarzycki21 . Moonshine build with latest source of Moonshine SDK Installer library from Git. Any changes to that library will also reflect in latest build of Moonshine.

**Comment by rat-moonshine** [comment]
Grails suggestion will get added once we decide on distributing Grails through Moonshine SDK Installer and have requisite information in its configuration file (information from configuration file acts to this suggestions).

**Comment by rat-moonshine** [comment]
> Grails suggestion will get added once we decide on distributing Grails through Moonshine SDK Installer and have requisite information in its configuration file (information from configuration file acts to these suggestions).

The above requirement has completed now as Grails download implemented to Moonshine SDK Installer (https://github.com/prominic/Moonshine-SDK-Installer/issues/11).

**Comment by JoelProminic** [comment]
I confirmed that the new logic is working as expected for each of the SDKs on macOS.  Some things to note:
- I can't manually set the paths for SVN or Git on macOS, because of a known issue with the binaries:  https://github.com/prominic/Moonshine- IDE/issues/507#issuecomment-482001313
- The Flex SDK interface does not allow invalid SDK paths, so we did not need to update the logic for this case.
