### ISSUE TITLE
Few project templates are missing/not-available in v2.2.0

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#546]
I noticed few of the following templates are not available in `File -> New` menu and does not open any project creation dialog when clicked in `Home` tab:

- Away3D Project
- Feathers Desktop Project 
- Feathers Mobile Project

This affect all the Moonshine versions/platform.

This may result of the recent changes done against #532 . I confirm this problem does not exist in v2.1.0.

**Comment by rat-moonshine** [comment]
The template list is still missing 'Feathers Mobile Project (MacOS, Windows)'.

I confirm following two items now populates to `File -> New` menu and opens project creation dialog from Home tab:
- Away3D Project
- Feathers Desktop Project (MacOS, Windows)

**Comment by piotrzarzycki21** [comment]
I have fixed that, plus I've found that icons were missed on Home for each projects, so I added them as well.

**Comment by rat-moonshine** [comment]
I noticed some oddity to default project creation in newer build. Moonshine includes icon files to the project directory which are for Moonshine's purpose only.

![image](https://user-images.githubusercontent.com/24370870/57429995-db5e1300-724b-11e9-8666-ef72626cac7d.png)

**Comment by piotrzarzycki21** [comment]
Ahh! What a boomel! I'm sorry about that I forgot that those folders are being used for project creation. Let me quick fix that!

**Comment by piotrzarzycki21** [comment]
Ok it should be fixed, check with next build. I moved those icons to separate folder `templates/projects/icons`

**Comment by rat-moonshine** [comment]
I don't see this behavior anymore in updates. This seems to be fixed. Thanks!
