### ISSUE TITLE
New -> File menu should support creating file with arbitrary extension

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#549]
At this moment `New -> File` menu option generates only `.txt` file. We need ability to generate file with arbitrary extension - ideally, user will write it.

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/57432239-e9636200-7252-11e9-81d2-3f95b3a39855.png)

**Comment by JoelProminic** [comment]
A leading '.' should be allowed, for files like [.gitignore](https://www.atlassian.com/git/tutorials/saving-changes/gitignore). 

I think we should still not allow a trailing '.'.  This may be strictly allowed, but I can't think of a case where I have seen this.  You can update the error to.

> Trailing '.' not permitted for file name.

On a related note, I also noticed that '-' is not allowed in file names, which prevents me from creating a file like [moonshine-dependencies.txt](https://github.com/prominic/Moonshine-IDE/wiki/Link-Related-Projects-with-moonshine-dependencies.xml).  @rat-moonshine reported that the current allowed characters are:  "0-9A-Za-z_.".  For now, let's add '-', and leave the other modifications to a different issue if we find that they are needed.

**Comment by JoelProminic** [comment]
Also, New > File should be available for all project types.  Currently it is not available for Java Maven or Java Gradle projects.

**Comment by rat-moonshine** [comment]
- Leading "." is now permitted to file naming
- Dash is acceptable to file naming
- `New -> File` is now available to context menu to Java projects
- Fix: `File -> New` files was not populating to Java projects from top menu
- Code-cleanup to context-menu generation against Java projects

**Comment by JoelProminic** [comment]
I tested the updates on macOS (AppStore version), and they all seem to be working properly.    
- I verified that New > File action was available in both the main menu and the context menu, and for both Maven and Gradle projects.
- I verified the other allowed characters, and this seems reasonable for now.

**Comment by JoelProminic** [comment]
New > File currently doesn't work for Grails projects (see #554).  Grails projects were added after the initial implementation of this issue.

**Comment by rat-moonshine** [comment]
Groovy Class, File and XML type of file creations now available to Grails project. Please, check.

**Comment by piotrzarzycki21** [comment]
> `New -> File` interface now provide support to choose user's own extension.
> 
> As a starting point, and to give a better understanding to a general file format, the interface starts with an auto-generated .txt file extension. However, this can be editable or even user choose not to declare an extension. We can talk on if we don't want to include this pre-population.
> 
> ![image](https://user-images.githubusercontent.com/24370870/57432239-e9636200-7252-11e9-81d2-3f95b3a39855.png)
> 
> In case of following format input the interface should notify the user against bad format and terminate:
> 
> * `myFileName.`
> * `.myExtension`
> 
> Following cases tested against file with custom extension and file with no extension:
> 
> * Creation
> * Duplicate
> * Rename

In case of New File I would not suggest anything to the user for extension. Yesterday I created couple of json files and it was really annoying when I had to change extension.

**Comment by JoelProminic** [comment]
I confirmed the new file types for Grails project,s and i confirmed that New > File works as well.

Not that Grails has multiple default source directories, by convention: 
- src/main/groovy
- src/main/java
- grails-app/services
- grails-app/controllers
- grails-app/init 

However, I could only create class files in src/main/groovy for now.  This is a separate issue we'll need to address for v2.4.0, though.
