### ISSUE TITLE
Sorting for Setting Menu Tabs

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#55]
The setting tabs are currently ordered in a seemingly arbitrary manner.

Application Settings:

    Templating
    Console
    Ant Build Setup
    Default SDK
    Subversion
    General
    Away3d

Project Settings:

    Output
    Build Options
    Paths
    Warnings and Errors
    Run

The should be sorted alphabetically instead.

Application Settings:

    Ant Build Setup
    Away3d
    Console
    Default SDK
    General
    Subversion
    Templating

Project Settings:

    Build Options
    Output
    Paths
    Run
    Warnings and Errors

Alternatively, we could organize them so that the tabs that are expected to be important or commonly used are at the top.  For example:

Application Settings:

    Default SDK
    General
    Ant Build Setup
    Templating
    Console
    Subversion
    Away3d

Project Settings:

    Build Options
    Paths
    Output
    Warnings and Errors
    Run

I think that sorting like this will be too subjective, though, and it would be easy for this to become out of date.  

For now, my preference is for the alphabetical sorting, but I'm open to other opinions.

**Comment by rat-moonshine** [comment]
In regular applications, vertical list settings generally sorted in alphabetical order. So my vote for the alphabetical ordering, too.

**Comment by rat-moonshine** [comment]
Sorry @piotrzarzycki21 my bad - I started work on this before you self-assigned but only able to commit now due to bad network :P

**Comment by piotrzarzycki21** [comment]
haha :) No problem reassign to yourself I didn't start to work on that. I just thought that since I'm touching Java Path task I will fix this one, but please proceed. I'm right now on #16 :)

**Comment by JoelProminic** [comment]
The updates look good to me.
