### ISSUE TITLE
Gradle Daemon Management

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#550]
In order to improve performance, Gradle uses a daemon:  https://docs.gradle.org/current/userguide/gradle_daemon.html

However, this daemon will remain running after Moonshine restarts.  This is a problem because:
- It leaves running Java processes on the machine, which can use a non-trivial amount of memory
- It may cause builds to fail after restarting Moonshine.  See https://github.com/prominic/Moonshine-IDE/issues/547#issuecomment-492380809

Normally you can check the status of the Gradle daemon with "gradle --status"

    $ gradle --status
       PID STATUS   INFO
     70292 IDLE     3.5.1
     98713 IDLE     3.5.1

    Only Daemons for the current Gradle version are displayed. See https://docs.gradle.org/3.5.1/userguide/gradle_daemon.html#sec:status

However, I found that the AppStore Moonshine uses a different path than the Terminal (~/Library/Containers/com.moonshine-ide/Data vs ~), so gradle --status won't work for your manual tests:

    $ lsof -a -d cwd -p 92948 -p 92543 -p 70292 -p 58042 -p 59911 -p 71024
    COMMAND   PID         USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
    java    58042 <user>  cwd    DIR    1,2      238 56424546 /Users/<user>/Library/Containers/com.moonshine-ide/Data/.gradle/daemon/5.0
    java    59911 <user>  cwd    DIR    1,2      170 57277655 /Users/<user>/Library/Containers/com.moonshine-ide/Data/.gradle/daemon/5.4.1
    java    70292 <user>  cwd    DIR    1,2    26452  1668136 /Users/<user>/.gradle/daemon/3.5.1
    java    71024 <user>  cwd    DIR    1,2      238 56555738 /Users/<user>/.gradle/daemon/5.4.1

I see two solutions to cleaning up the daemons:

### Kill running daemons on Moonshine close

We can use "gradle --stop" to stop all running daemons for the configured Gradle SDK.  

However, this will also kill any currently running Gradle builds.  For the App Store version, this would only affect Gradle processes run from Moonshine, but for other builds, this will affect all Gradle builds using the same Gradle version.

### Avoid using daemons

We can disable the daemon with one of these options:
- add the --no-daemon argument to the command line
- set GRADLE_OPTS="-Dorg.gradle.daemon=false"  (NOTE:  we may eventually allow the user to edit GRADLE_OPTS

I prefer the GRADLE_OPTS solution, since it allows the user to overwrite the behavior by adding --daemon to the arguments.

This solutions is less desirable because it will reduce performance.

**Comment by JoelProminic** [comment]
I continue to see Gradle daemons and errors related to Gradle 5.0:

    : May 15, 2019 11:49:44 AM Synchronize project GradleTest3 failed due to an error in the referenced Gradle build.
    : Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-5.0-bin.zip'.
    : org.gradle.tooling.BuildException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-5.0-bin.zip'.

These instances will not be stopped by {{$GradleHome/bin/gradle --stop}}, since they are a different Gradle version.  I suspect that these instances are being launched by the language servers, but I have not confirmed this yet.  I'll report when I find more information.

**Comment by rat-moonshine** [comment]
If any Gradle daemon started or 'gradle eclipse' ran once, `gradle --stop` now ran on Moonshine exit. I see the running daemon instances closing in both sandbox and non-sandbox builds.

This stop process requires one or two seconds to complete, until then Moonshine requires to stay else it's possible that command-line do not finish and daemon instances do not exits. Since this takes a few moment, following steps taken against running the stop command:
1. Run only if Gradle daemon started by Moonshine
2. Shows a message "Preparing to close.. Please wait." until Moonshine exit since the closing-request 

When on Windows this waiting seems a little longer (1-3 seconds) on macOS this is considerably faster.

I not exactly happy by the way of notification here, but I'm open to discuss if any other way.

**Comment by rat-moonshine** [comment]
I'm closing this as fixed. Please, reopen if any problem found or we decide to change something.

**Comment by JoelProminic** [comment]
I have seen a couple cases where Moonshine hung on shutdown.   This has been rare, though, and I haven't figured out what conditions cause it.

Here is an example.  The interface is locked, so I can't see the full stack trace:
![image](https://user-images.githubusercontent.com/24532731/58671089-f1b93500-8306-11e9-921f-7ff7a1a80bf1.png)
