### ISSUE TITLE
Grails Project Support

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#554]
From @joshtynjala 
>Today, I merged the groovy-language-server branch into master. This doesn't mean that I've completely finished my work on Grails/Groovy yet. However, things should be good enough now that others can try creating a Grails project and do some basic testing.
>
>When you create a Grails project, Moonshine will run the standard grails create-app command. Before the language server starts, Moonshine runs the gradle eclipse command, similar to the new behavior that we recently added for Java Gradle projects. This creates a .classpath file with all of the required dependencies, which the language server uses to configure the Groovy compiler to provide code intelligence. It seems to be correctly finding all of the project's source paths in src and grails-app, along with .jar libraries that are dependencies in build.gradle.
>
>Following Joel's advice, I mapped the following Moonshine build actions to Grails commands:
>
>- Clean:  grails clean
>- Build:  grails compile
>- Build & Run:  grails run-app
>- Build Release:  grails war
>
>Please let me know if you run into any issues, especially with code intelligence. For other things, like settings and build/run commands, it may make sense for others to take over now.

**Comment by JoelProminic** [comment]
I created an example project with some example code in the various source directories for Grails.   I may update this attachment later if I need to do some cleanup:  
[2019_05_17__TestGrailsProject.zip](https://github.com/prominic/Moonshine-IDE/files/3193114/2019_05_17__TestGrailsProject.zip)

You can view a CRUD interface generated from the Person controller here:  http://localhost:8080/person/index

I included some of the commands I used to initialize these files below, for reference.

NOTE: I ran the Grails commands from the command line, but we may want to consider adding an interface action to run a Grails command instead.  That said, this feature is present in IntelliJ but I personally find it more confortable to use the command line instead :).

Also note that I did not have a way to create the .groovy files in Moonshine currently.   The New->File prompt (see https://github.com/prominic/Moonshine-IDE/issues/549) would be one way to do this, if it were enabled for Grails projects, but we'll eventually need a template for this.


    # Create a domain class in grails-app/domain
    $GRAILS_HOME/bin/grails create-domain-class test.Person

    # edit grails-app/domain/test/Person.groovy:
    package test

    class Person {
        String firstName
        String lastName
        int age

        static constraints = {
        }
    }

    # Create a controller in grails-app/controllers
    $GRAILS_HOME/bin/grails create-controller test.Person

    # Edit grails-app/controllers/test/PersonController.groovy
    package test

    class PersonController {
        static scaffold = Person  // NOTE:  this will generate a simple CRUD interface

        def test() {
            // you can test code intelligence here
        }

    }



    # Create a service in grails-app/services
    $GRAILS_HOME/bin/grails create-service test.Person

    # Other source directories:
    # The domain, controller, and service commands above also created test files in src/test/groovy.  These test files use Spock, which is a DSL based on Groovy:  http://spockframework.org/ .  I'm not sure how this will interact with the groovy-language-server
    # Write code that will run on startup in grails-app/init/.../Bootstrap.groovy
    # Manually create Groovy classes in src/main/groovy
    # Manually create Java class is in src/main/java

**Comment by JoelProminic** [comment]
Some notes from my testing.

The "grails run-app" command from Project > Build & Run does not terminate automatically.  It needs to be killed using the stop icon in the bottom right of the window.  This is sufficient for now, but we may want to make this more clear for new users.

It seems to take a while for the language server to stabilize after I make a change.   You can see the Problems view - the problem list keeps updating for at least 10 seconds after I make a change.

I noticed that the language server had a particularly hard time resolving custom classes.  I created these classes in src/main/groovy/test:
- test.TestGroovy
- test.Foo
- test.Bar

However, Moonshine showed me "unable to resolve class" warnings/errors for Foo and Bar in TestGroov

**Comment by JoelProminic** [comment]
@joshtynjala reported that groovy-language-server does not support .java files, which is a problem for src/main/java.    This surprises me a little, since Java code is valid Groovy code.   

I think src/main/java is discouraged for Grails projects, but some of the Prominic projects have some legacy code here.  This is a lower priority to support in Moonshine, but we may have revisit it eventually.

**Comment by joshtynjala** [comment]
> This surprises me a little, since Java code is valid Groovy code.

@JoelProminic It was my understanding that Groovy accepted *.java* files, but it was just passing them to the Java compiler behind the scenes to produce bytecode or something. Maybe I made a bad assumption, though.  Is Groovy a strict superset of Java? In other words, any valid Java code can be copied into a *.groovy* file and just work?

**Comment by JoelProminic** [comment]
Yes, that is my understanding.   Groovy replaces some of the Java libraries, so the functionality may be a bit different, but to my knowledge and experience Java code works just fine in a .groovy class.  This is really nice as a Java developer who is trying to get used to using some of the nice additions from Groovy.

That said, I'm not sure if the groovy compiler accepts .java files directly - my experience has been with using Groovy files only or using a mix of files within a Grails project.

**Comment by JoelProminic** [comment]
The Grails SDK is now also downloaded from Moonshine SDK Installer:  https://github.com/prominic/Moonshine-SDK-Installer/issues/11

This issue will probably be extended into the 2.4.0 milestone for updates like
- Resolve the language server problems I mentioned above
- Add syntax highlighting for some of the Grails project files including:  .yml, .gradle (can we use the .groovy syntax highlighting?), .gsp (XML/HTML)
- Support for more Grails/Gradle tasks (including creating controllers, services, domain classes, etc)

**Comment by joshtynjala** [comment]
> Resolve the language server problems I mentioned above

I'll be looking into these next week!

**Comment by JoelProminic** [comment]
When I tested creating a new Grails project on Windows, I got this error:

    : Creating Grails application TestGrails0524
    : 
    : ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
    : 
    : Please set the JAVA_HOME variable in your environment to match the
    : location of your Java installation.

I suspect this did not trigger before because JAVA_HOME was set outside of Moonshine.   The "grails create-app" command should use the same environment settings as the other commands.   @rat-moonshine, can you take a look at this?

This worked fine for me on macOS, but it may be using /usr/libexec/java_home to get Java.

**Comment by rat-moonshine** [comment]
I have made requisite changes to run the 'grails create-app' command through local-environment setting batch process. This looks good in my Windows' run:

```
: Creating Grails application NewGrailsProject
: Resolving dependencies..
: 
: .
: .
: .
: ..
: .
: .
: .
: .
: .
: .
: .
: ..
: .
: ..
: .
: ..
: .
: .
: |Application created at C:\Users\devsena\Desktop\NewGrailsProject
: Starting a Gradle Daemon (subsequent builds will be faster)
: > Task :eclipseClasspath
: > Task :eclipseJdt
: > Task :eclipseProject
: > Task :eclipseWtpComponent
: > Task :eclipseWtpFacet
: > Task :eclipseWtp
: > Task :eclipse
: Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
: Use '--warning-mode all' to show the individual deprecation warnings.
: See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
: 
: BUILD SUCCESSFUL in 5m 57s
: 5 actionable tasks: 5 executed27-05-2019
```

Please, check.

**Comment by JoelProminic** [comment]
When I create a new Groovy class under src/main/groovy in a Grails project, I see that the package is defined based on the absolute path of the directory

```
package Users.<user>.Documents.Flex.temp_workspace.TestGrailsNonSandbox.src.main.groovy


public class TestGroovy   {
	public TestGroovy() {
	}
}
```

The packages are defined correctly for new Java files in Java Gradle projects.

**Comment by rat-moonshine** [comment]
I noticed package generation fails for both `.java` and `.groovy` files in a Grails project on Windows; this generate something like this:

`package :.Users.<user>.Desktop.NewGrailsProject.src.main.groovy;`

This should be fix now. Please, check.

**Comment by joshtynjala** [comment]
> However, Moonshine showed me "unable to resolve class" warnings/errors for Foo and Bar in TestGroov

My latest commit resolves this issue. 59f21cb6f1064f3d051d86719e297dee9994fe34

**Comment by JoelProminic** [comment]
A little more context:

> I noticed that the language server had a particularly hard time resolving custom classes. I created these classes in src/main/groovy/test:
> 
>     * test.TestGroovy
> 
>     * test.Foo
> 
>     * test.Bar
> 
> 
> However, Moonshine showed me "unable to resolve class" warnings/errors for Foo and Bar in TestGroov

This seems to be working properly now in the test project I attached earlier.

**Comment by JoelProminic** [comment]
The behavior starts to get strange after I do more testing:
1. Restart Moonshine
2. Open the test project from above: [2019_05_17__TestGrailsProject.zip](https://github.com/prominic/Moonshine-IDE/files/3193114/2019_05_17__TestGrailsProject.zip)
3. Open src/main/groovy/test/TestGroovy.groovy
4. Hold CMD and mouse over the different references.   The references will highlight, and the tooltips look correct
5. CMD-Click on "Person".  This opens grails-app/domain/test/Person.groovy
6. Open grails-app/controllers/test/PersonController.groovy. As you mouse over the code, you will start seeing that some of the tooltips don't match the code - they may be misaligned.
7. Return to TestGroovy.groovy.  Now, this class has the same strange behavior with the tooltips.   CMD-Click does not highlight or work anymore

**Comment by JoelProminic** [comment]
> I noticed package generation fails for both `.java` and `.groovy` files in a Grails project on Windows; this generate something like this:
> 
> `package :.Users.<user>.Desktop.NewGrailsProject.src.main.groovy;`
> 
> This should be fix now. Please, check.

This worked for me with both Groovy and Java files, and with no package, a single level package (test.TestClass), and a multi-level package (foo.bar.TestClass)

**Comment by rat-moonshine** [comment]
> 
> 
> > I noticed package generation fails for both `.java` and `.groovy` files in a Grails project on Windows; this generate something like this:
> > `package :.Users.<user>.Desktop.NewGrailsProject.src.main.groovy;`
> > This should be fix now. Please, check.
> 
> This worked for me with both Groovy and Java files, and with no package, a single level package (test.TestClass), and a multi-level package (foo.bar.TestClass)

As we discussed earlier on one to multi source-folder situation in Grails project - this calculation of package path generation works upon the current source folder to the project. To keep in document, if we want to have multi-source folders, we'll need to look into this area for necessary changes as well.

**Comment by joshtynjala** [comment]
> The behavior starts to get strange after I do more testing... https://github.com/prominic/Moonshine-IDE/issues/554#issuecomment-497133764

These issues should be fixed with my latest commits.

**Comment by JoelProminic** [comment]
The language server seems to be working well after @joshtynjala's update.  I confirmed that I can follow references in:
- grails-app/controllers/test/PersonController.groovy
- grails-app/services/test/PersonService.groovy
- grails-app/init/testgrails/Bootstrap.groovy
- gralis-app/domain/test/Person.grooovy
- src/main/groovy/test/TestGroovy.groovy

**Comment by JoelProminic** [comment]
Basic Grails support is working in Moonshine.   I am going to close this issue, and create separate, more-specific issues to track any other issues I find.
