### ISSUE TITLE
"New -> $file" list is broken in context menu to projects

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#555]
Between different project types when `File -> New -> $files` from top menu generates proper file lists, context-menu to projects `New -> $files` generates only Folder and Java Class options.

**Comment by rat-moonshine** [comment]
The above problem should have resolve now.

Also, earlier we have seen file listings generates selectively to the templating projects. I think now that all the file-choices should be available when modifying a template project so an user can freely edit/modify the project. 

I make available full file-list to the template-project modification now. If we think this might create some other problem, we can discuss on that.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine In the other word this issue has been resolved ?

**Comment by rat-moonshine** [comment]
Yes, I'm closing this issue for now @piotrzarzycki21 .

All files-templates are now available to create in template projects. Note: Visual Editor Project files are not available to create to template projects for now, as the file-creation dialog opening/display etc. requires added logic to work against headless template projects.
