### ISSUE TITLE
Handling Invalid SDK Paths with Getting Started Interface

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#556]
I noticed this error while testing https://github.com/prominic/Moonshine-SDK-Installer/issues/11 today:
1. Create ~/Downloads/MoonshineSDKs/invalid_grails
2. Change Grails Home to the above directory
3. Close Moonshine
4. Remove the above directory
5. Restart Moonshine
6. Getting Started does not open
7. Open Help > Getting Started.  Grails is reported as successfully installed.
8. Check the Grails Home path - is shows as invalid 

As a result, I got an error when I tried to run a Grails test.  

In this case, Moonshine should either:
- Report that the SDK path is still invalid
- Automatically correct the path

**Comment by JoelProminic** [comment]
I did some thinking about which solution I prefered.  I see potential prompts and advantages to auto-correction.  I wrote up a couple user stories to explore this.

In this "power user" case, correcting the path causes some confusion.
1. User downloads a different version of Grails
2. User sets the Grails Home to the new Grails version, but does not set it correctly for some reason
3. User restarts Moonshine.  Moonshine resets the SDK to the default version
4. User tries to use Grails, and gets errors because the version is wrong. 

However a new user could have the opposite problem.
1. A new user installs Moonshine, but tries to install the SDKs themselves
2. After getting errors trying to set the SDK path, the user decides to use Moonshine SDK Installer instead
3. The user goes through Moonshine SDK Installer, and all SDKs are downloaded correctly
4. In Moonshine, the SDK they tried earlier shows it is still not configured
5. The user has to figure out how to set the ~/Downloads/MoonshineSDKs/... path


Both of these cases are pretty contrived, but I think it is more important to make this work properly for the new user.  *So, Moonshine should auto-correct the SDK path if it is available in MoonshineSDKs and the current path is invalid (or missing).*

However, we need to be careful not to overwrite a valid SDK path, since this would cause frustration for users who need to use a different version of the SDKs.

**Comment by rat-moonshine** [comment]
- Made some changes to the UtilsCore path validation logic - now they works with SDK Installer library configuration
- Made changes to auto-setup path if existing Moonshine path found invalid and a valid path is available to Moonshine SDK Installer library

**Comment by rat-moonshine** [comment]
I'm closing this as fix. Please, reopen if any problem found or we want more modifications.
