### ISSUE TITLE
Moonshine Requires Git and SVN Configuration After Restart

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#557]
I noticed today that Moonshine (tested on macOS, AppStore build) is prompting me configure Git and SVN after every restart.

![image](https://user-images.githubusercontent.com/24532731/58204118-432b4980-7ca1-11e9-9cf0-c5fa985da236.png)

Even after I go through the steps to reconfigure Git and SVN, when I open Manage Dependencies and try to create a new repository, it shows an error that Git is not configured.

![image](https://user-images.githubusercontent.com/24532731/58204148-50e0cf00-7ca1-11e9-9fc6-6cbf3f964eb1.png)

I don't think this was triggering when I was doing testing for #556 yesterday, but I was focused on a different problem.

**Comment by rat-moonshine** [comment]
The above problems should have fixed now. Please, check.

**Comment by JoelProminic** [comment]
Some clarification from @rat-moonshine 
> the util class in Moonshine wasn't returning proper path-validation for SVN and Git on macOS - where the validation was suppose to do against executable rather than directory.

The behavior seems fine in my tests today.

**Comment by rat-moonshine** [comment]
I'm closing this as fixed. Please, reopen if any problem found.
