### ISSUE TITLE
Creation Error for Flex Projects

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#559]
I got this error while creating a new Flex Desktop Project on macOS (with both the App Store and non-sandbox builds).  The new project was created on the filesystem, but not opened.

    : Error #3003
    : Error: Error #3003
    : 	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/parse()
    : 	at actionScripts.plugins.as3project::CreateProject/createFileSystemBeforeSave()
    : 	at actionScripts.plugins.as3project::CreateProject/onCreateProjectSave()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at MethodInfo-25866()
    : 	at actionScripts.plugin.settings::SettingsView/save()
    : 	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()
    :
    : Click here to Report a Bug

I also noticed that I was prompted to select a template type - Flex or PrimeFaces.  These sound like the options for a Visual Editor project.

I saw the same results for a Flex Browser Project, but not an Actionscript project.

**Comment by rat-moonshine** [comment]
I see following things were missing to the dialog:

![image](https://user-images.githubusercontent.com/24370870/58303789-42182a80-7e0f-11e9-8cdd-cc74bec1f00b.png)

This could be some side-effect from #527 . @piotrzarzycki21 can you look into this?

**Comment by rat-moonshine** [comment]
While testing, I noticed this different error on macOS:

1. Create a new ActionScript Flex project
2. Moonshine throws following error to console
3. Project folder creates to the physical file-system but nothing opens to the sidebar

```
: Error #1088
: TypeError: Error #1088
: 	at actionScripts.plugin.core.exporter::FlashDevelopExporterBase$/exportPathString()
: 	at actionScripts.plugins.as3project.exporter::FlashDevelopExporter$/toXML()
: 	at actionScripts.plugins.as3project.exporter::FlashDevelopExporter$/export()
: 	at actionScripts.plugins.as3project::CreateProject/createFileSystemBeforeSave()
: 	at actionScripts.plugins.as3project::CreateProject/onCreateProjectSave()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at MethodInfo-25866()
: 	at actionScripts.plugin.settings::SettingsView/save()
: 	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()
:
: Click here to Report a Bug
```

I'm trying to debug this meanwhile.

**Comment by rat-moonshine** [comment]
I see Away3D app generation is broken:
![image](https://user-images.githubusercontent.com/24370870/58308580-93c8b100-7e1f-11e9-86fc-552ae941ee52.png)

We probably require a total evaluation of functionalities after the recent changes to the CreateProject class.

**Comment by rat-moonshine** [comment]
> While testing, I noticed this different error on macOS:
> 
> 1. Create a new ActionScript Flex project
> 2. Moonshine throws following error to console
> 3. Project folder creates to the physical file-system but nothing opens to the sidebar
> 
I couldn't able to reproduce the above error anymore after a restart. I'll watch for this error, though. However, I see a different error which I'll start as a separate issue.

**Comment by piotrzarzycki21** [comment]
I just fixed @JoelProminic 's issue, so try with my update.

**Comment by piotrzarzycki21** [comment]
> I see Away3D app generation is broken:
> ![image](https://user-images.githubusercontent.com/24370870/58308580-93c8b100-7e1f-11e9-86fc-552ae941ee52.png)
> 
> We probably require a total evaluation of functionalities after the recent changes to the CreateProject class.

However above problem still remains even for Flex type of project.

**Comment by piotrzarzycki21** [comment]
Problem with Away3D should be also fixed with my latest commit.

**Comment by piotrzarzycki21** [comment]
Please report any additional findings into separate issue.

**Comment by rat-moonshine** [comment]
With latest build, I don't found any break during project creation anymore. All the fields are now correctly visible during different types of project creation, and application descriptor files are also generates properly for desktop/mobile applications.

**Comment by JoelProminic** [comment]
I tested each of the project types (checking the options in File > New and the New context menu for #555):

Project Type | Test Build | Status | File > New
-------------|------------|--------|-----------
ActionScript AIR | macOS non-Sandbox | Works | Correct
ActionScript SWF | macOS AppStore | Works | Correct
Library Project - Flex | macOS AppStore | Works | Correct
Library Project - ActionScript | Windows | Works | Correct
Library Project - Mobile | Windows | Works | Correct
Flex Browser Project | macOS AppStore | Works | Correct
Flex Desktop Project | macOS non-Sandbox | Works | Correct
Flex Mobile Project | Windows | Works | Correct
Grails Project | macOS Sandbox | Works (See #554 for different error on Windows) | Nothing except Folder is enabled
Java Maven Project | macOS non-Sandbox | Works | Correct
Java Gradle Project | Windows | Works | Correct
Royale Browser Project - Basic | Windows | Works | Correct
Royale Browser Project - Jewel | macOS AppStore | Works | Correct
Visual Editor Project - Flex | macOS AppStore | Fails, Error #3003 | N/A
Visual Editor Project - PrimeFaces | Windows | Fails, Error #3003 | N/A
Away3D Project | macOS non-Sandbox | Works | Correct
Feathers Desktop Project | macOS AppStore | Works | Correct
Feathers Mobile Project | Windows | Works | Correct


I still see an error for Visual Editor on macOS and Windows:

    : Error #3003
    : Error: Error #3003
    : 	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/parse()
    : 	at actionScripts.plugins.as3project::CreateProject/createFileSystemBeforeSave()
    : 	at actionScripts.plugins.as3project::CreateProject/onCreateProjectSave()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at MethodInfo-25866()
    : 	at actionScripts.plugin.settings::SettingsView/save()
    : 	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()
    :
    : Click here to Report a Bug


For a while, I was getting a different error when creating an Actionscript AIR project, but I couldn't reproduce this consistently.  I'm including this in case you recognize the potential problem.

    : TypeError: Error #1088
    : 	at actionScripts.plugin.core.exporter::FlashDevelopExporterBase$/exportPathString()
    : 	at actionScripts.plugins.as3project.exporter::FlashDevelopExporter$/toXML()
    : 	at actionScripts.plugins.as3project.exporter::FlashDevelopExporter$/export()
    : 	at actionScripts.plugins.as3project::CreateProject/createFileSystemBeforeSave()
    : 	at actionScripts.plugins.as3project::CreateProject/onCreateProjectSave()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at MethodInfo-25866()
    : 	at actionScripts.plugin.settings::SettingsView/save()
    : 	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()
    :
    : Click here to Report a Bug

**Comment by rat-moonshine** [comment]
> I still see an error for Visual Editor on macOS and Windows:
> 
> ```
> : Error #3003
> : Error: Error #3003
> : 	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/parse()
> : 	at actionScripts.plugins.as3project::CreateProject/createFileSystemBeforeSave()
> : 	at actionScripts.plugins.as3project::CreateProject/onCreateProjectSave()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at mx.core::UIComponent/dispatchEvent()
> : 	at MethodInfo-25866()
> : 	at actionScripts.plugin.settings::SettingsView/save()
> : 	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()
> :
> : Click here to Report a Bug
> ```

I'm looking into this.

**Comment by rat-moonshine** [comment]
> 
> 
> > I still see an error for Visual Editor on macOS and Windows:
> > ```
> > : Error #3003
> > : Error: Error #3003
> > : 	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/parse()
> > : 	at actionScripts.plugins.as3project::CreateProject/createFileSystemBeforeSave()
> > : 	at actionScripts.plugins.as3project::CreateProject/onCreateProjectSave()
> > : 	at flash.events::EventDispatcher/dispatchEvent()
> > : 	at mx.core::UIComponent/dispatchEvent()
> > : 	at MethodInfo-25866()
> > : 	at actionScripts.plugin.settings::SettingsView/save()
> > : 	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()
> > :
> > : Click here to Report a Bug
> > ```
> 
> I'm looking into this.

This issue should have resolved now.

**Comment by piotrzarzycki21** [comment]
I just pushed a fix for Visual Editor error. I hope now it will be resolved. I did test to make sure that other stuff is not broken.

**Comment by JoelProminic** [comment]
I saw a different error with ActionScript AIR, today.  If I create an ActionScript AIR project with a non-sandbox macOS build, I get these errors when submitting the form:

    : Error #1010
    : TypeError: Error #1010
    : 	at actionScripts.ui.menu::MenuPlugin/recentProjectListUpdatedHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at MethodInfo-13681()
    : 	at SetIntervalTimer/onTimer()
    : 	at flash.utils::Timer/tick()
    :
    : Click here to Report a Bug
    : Error #1010
    : TypeError: Error #1010
    : 	at actionScripts.ui.menu::MenuPlugin/recentFilesListUpdatedHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at MethodInfo-13683()
    : 	at SetIntervalTimer/onTimer()
    : 	at flash.utils::Timer/tick()
    :
    : Click here to Report a Bug

Also, Moonshine shows me a prompt with "New Project is changed"

![image](https://user-images.githubusercontent.com/24532731/58514965-065fc680-8169-11e9-8d7f-9749cee7b17e.png)


The project seems to be created properly, though.  The same behavior did not trigger for me with a Java Maven project.

**Comment by piotrzarzycki21** [comment]
> I saw a different error with ActionScript AIR, today. If I create an ActionScript AIR project with a non-sandbox macOS build, I get these errors when submitting the form:
> 
> ```
> : Error #1010
> : TypeError: Error #1010
> : 	at actionScripts.ui.menu::MenuPlugin/recentProjectListUpdatedHandler()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at MethodInfo-13681()
> : 	at SetIntervalTimer/onTimer()
> : 	at flash.utils::Timer/tick()
> :
> : Click here to Report a Bug
> : Error #1010
> : TypeError: Error #1010
> : 	at actionScripts.ui.menu::MenuPlugin/recentFilesListUpdatedHandler()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at MethodInfo-13683()
> : 	at SetIntervalTimer/onTimer()
> : 	at flash.utils::Timer/tick()
> :
> : Click here to Report a Bug
> ```
> 
> Also, Moonshine shows me a prompt with "New Project is changed"
> 
> ![image](https://user-images.githubusercontent.com/24532731/58514965-065fc680-8169-11e9-8d7f-9749cee7b17e.png)
> 
> The project seems to be created properly, though. The same behavior did not trigger for me with a Java Maven project.

I just fixed that issue.

**Comment by rat-moonshine** [comment]
Can you confirm specifically which fix you're pointing to - the above console errors, or the editor alert, or both?

**Comment by piotrzarzycki21** [comment]
Ahh sorry about that ! I have fixed issue where Joel gets prompt once project was created.

**Comment by rat-moonshine** [comment]
Thank you for confirming! I saw your fix. Surprisingly, that small thing caused so many trouble in non-sandbox build and I don't have any clear idea why! 

I saw breaks in following section before your fix:
1. Updating recent opened project menu to top-menu throwing error - I found manu-menu collection [returned](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/ui/menu/MenuPlugin.as#L925) by framework is returning strange collection
2. I found that above problem was happening to any project creation, too
3. I found that opening any project and starting language-server freeze Moonshine

Once that small [fix](https://github.com/prominic/Moonshine-IDE/commit/f3272ccb938c75e4c0c96e86e9b9f78a1fcc680c) done, everything started worked again! I don't have any good idea why this way really. I'm now wondering if we require to ensure `customSdkPathSetting.commitChanges();` called everywhere in `CreateProject` class where `customSdkPathSetting` has updated.

**Comment by piotrzarzycki21** [comment]
There is no point to spend more time on that whether this fix is proper or not - if it's working right now it is enough. This code probably will be completely removed once we start refactoring. ;)

**Comment by rat-moonshine** [comment]
> 
> 
> There is no point to spend more time on that whether this fix is proper or not - if it's working right now it is enough. This code probably will be completely removed once we start refactoring. ;)

Yes, yet this this might take some time to refactoring, so we need to ensure at least running stable version do not breaks with strange error like these.. I was tearing my hairs why this build returning strange mac-menu!

**Comment by JoelProminic** [comment]
I confirmed that the issues are resolved for Actionscript AIR projects.   I did some other tests on projects creation and importing, and I didn't see any problems.
