### ISSUE TITLE
Non-Sandbox Build Gets Error On Import Form

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#560]
When testing with the non-sandbox build on macOS, I now get this error when I open the Import form:

    : Index '-1' specified is out of bounds.
    : RangeError: Index '-1' specified is out of bounds.
    : 	at mx.collections::ListCollectionView/getItemAt()
    : 	at MethodInfo-36178()
    : 	at mx.core::UIComponent/callLaterDispatcher2()
    : 	at mx.core::UIComponent/callLaterDispatcher()
    : 	at flash.utils::Timer/tick()
    :
    : Click here to Report a Bug

I triggered this on both a Maven project and an Actionscript project (and the error triggers before I have a chance to select the type).

This does not trigger with the App Store build.

**Comment by rat-moonshine** [comment]
Until now, in my multiple tests I couldn't able to reproduce the problem. 

I tried by importing valid Gradle project and also by invalid-Gradle project. In case of latter, I able to move through the import/create project dialog successfully when none or multiple different projects were already opened to the sidebar. I'll keep watch for this error, though.

**Comment by piotrzarzycki21** [comment]
I couldn't reproduce that issue as well. Let's take it from 2.3.0 and observer farther.

**Comment by JoelProminic** [comment]
I think this problem was because of a separate issue I had.  I had a project that kept opening whenever I restarted Moonshine, even if I closed it before the restart.   I had no idea what triggered that behavior, though, so I haven't created an issue.

I cleared the application settings, and now I can't reproduce the issue anymore.
1. Remove ~/Libraries/Application\ Support/com.moonshine-ide
1. Open non-sandbox Moonshine
1. Create a new ActionScript AIR project
1. Close the project
1. Delete <project>/<project>.asproj
1. Import the project - this works with no error
1. Create a Java Maven project.  Make sure that this project name comes later in alphabetical order than the first project
1. Close the second project
1. Delete <project>/<project>.asproj for the second project
1. Import the project - this works with no error
1. Close the first project
1. Delete <project>/<project>.asproj for the first project

I'll reopen this issue if I can trigger it again.
