### ISSUE TITLE
Changes in SVN repository project testing

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#564]
Currently, Moonshine checks if following file exists to the project directory to determine if it's a SVN repository:

`.svn/wc.db`

This testing is error-prone as many a time sub-projects exists in multi-level deep and does not contain the above file. 

To overcome this problem, we want to run `svn info` to the opened project's directory rather, which should return us more prominent result if it's a SVN repository.

**Comment by rat-moonshine** [comment]
This should be fix now. Please, check.

**Comment by JoelProminic** [comment]
The new logic works well for me on macOS.

One case to note:  If you clear the bookmarks and then open a subproject of an SVN repository, it wil not be considered an SVN project.  You would need to allow access to the parent directory to detect this.  However, Moonshine did not trigger any errors or break the logic when I tried this, so Moonshine is handling this case like I expect.
