### ISSUE TITLE
Template Reset Fails after Moonshine Restart

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#565]
While testing #552, I noticed this error with both the macOS App Store and Windows bulds
1. Open Moonshine Settings and select Templating
1. Select a Template and click "Modify" (I tried with ActionScript Project and Java Gradle project
1. Click Save
1. Restart Monshine.  NOTE:  without this step, the bug does not trigger.
1. Open Moonshine Settings and select Templating
1. Find the same template and click Reset. BUG:  this triggers and error
1. Close and reopen the settings.  BUG:  the template did not reset.

    : Error #1034
    : TypeError: Error #1034
    : 	at actionScripts.plugin.templating::TemplatingPlugin/handleTemplateReset()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at actionScripts.plugin.templating.settings.renderer::TemplateRenderer/reset()
    : 	at actionScripts.plugin.templating.settings.renderer::TemplateRenderer/___TemplateRenderer_Button3_click()
    :
    : Click here to Report a Bug

I think I noticed this before with #535, but I couln't reproduce it at the time.

**Comment by rat-moonshine** [comment]
I tested on Windows, non-sandbox macOS and sandbox macOS builds, but I couldn't able to reproduce the above-said behavior. Following were my steps:

1. (macOS) removed `/Users/$user/Library/Containers/com.moonshine-ide` (for non-sandbox` /Users/$user/Library/Application Support/com.moonshine-ide`) for clean test (Windows folder `/Users/$user/AppData/Roaming/com.moonshine-ide`)
2. Started Moonshine and moved to `Settings -> Templating`
3. Clicked on 'Modify' to two project templates - ActionScript and Java Gradle project
4. `Save` to opened settings tab
5. Restarted Moonshine and again navigate to `Settings -> Templating`
6. Templating list shown 'Reset' button against two projects those I did 'Modify'
7. `Reset` done against both the templates - no error thrown
8. Closed settings tab
9. Reopened settings tab - no error thrown 
10. Restarted Moonshine and did 2-9 again, no error thrown

@piotrzarzycki21 can you give some test to the above behavior Joel mentioned?

**Comment by piotrzarzycki21** [comment]
Unfortunately I couldn't reproduce it either.

**Comment by JoelProminic** [comment]
I did some more testing, and I confirmed that this bug only triggers if I have another project open:
1. Clear application settings
2. Open Moonshine
3. Create a new Java Gradle project
4. Modify the Java Gradle template
5. Restart Moonshine
6. Reset the Java Gradle template.  BUG:  Error  #1034, same as above.

**Comment by JoelProminic** [comment]
It looks like @rat-moonshine already fixed this after we discussed it in the morning meeting.  I also tested the logic on a VisualEditor template, and on a file template, and I did not see any errors.
