### ISSUE TITLE
Default Source Folders for Grails

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#567]
The user should be allowed to create class files (.java and .groovy) in at least these directories (not all of these directories will exist by default):
- grails-app/controllers
- grails-app/domains
- grails-app/services
- scripts
- src/main/groovy
- src/main/java
- src/test/groovy
- src/test/java

You can see the more information about these directories here:  http://docs.grails.org/latest/guide/single.html#conventionOverConfiguration

Currently this is not allowed except for src/main/groovy, because that is the only directory that is considered a source folder by Mooonshine.  We can implement this by adding all of these directories as source folders, but I am open to other implementations.  Moonshine will use build.gradle to determine the actual source directories during builds, so this may just be duplication of the configuraiton.

The user can still create code in other locations using the New > File action.

**Comment by piotrzarzycki21** [comment]
Whatever implementation will be choosen it doesn't matter too much, cause I expect that behind the stage it will change, cause we are planning refactoring.

**Comment by JoelProminic** [comment]
Right, I am not too worried about the implementation details, but I want to make sure that we can create classes in the different source directories (and that the language server works in each of the directories, but that seems to be working already).

**Comment by piotrzarzycki21** [comment]
I have started playing with some ideas today, but there were too many distractions and I didn't finish yet. We will see tomorrow if I managed to do with it something.

**Comment by piotrzarzycki21** [comment]
@JoelProminic @rat-moonshine I just added ability to create classes in above folders. My implementation is based on mechanism which we are currently have. In our project objects we have property for holding path to source folder ([sourceFolder](https://github.com/prominic/Moonshine-IDE/blob/d29be81a2f2663fe639e9916d3f432b91ae9ecb2/ide/MoonshineSharedCore/src/actionScripts/valueObjects/ProjectVO.as#L47)) and property to store [classpaths](https://github.com/prominic/Moonshine-IDE/blob/d29be81a2f2663fe639e9916d3f432b91ae9ecb2/ide/MoonshineSharedCore/src/actionScripts/plugin/groovy/grailsproject/vo/GrailsProjectVO.as#L23). 

**I have extended permission to create classes to what classpaths property contains.**
1. Initially when someone creates Grails project he will be able to create classes in:
```
       <class path="src/main/groovy"/>
       <class path="grails-app/controllers"/>
       <class path="grails-app/services"/>
       <class path="grails-app/domain"/>
       <class path="src/test/groovy"/>
```
Only above folder has been created during project creation.
2. If user import project from existing source he will have to add on his own folders to classpath in project **Settings**. Here I was thinking to discover automatically during export whether those folders exists and add them to classpath, but I'm not sure whether it is good idea.

There are two questions to above:
1. I see that there is some kind of process of updating classpaths during project creation - If I will add all of above paths to classpaths array -Will it be used in that update process? 
2. Currently in the UI in project tree we are marking by "S" icon only source folder - should we mark classpaths folders as "S" as well ?

**Comment by rat-moonshine** [comment]
Seen your update on checking `classpaths` instead of only `sourceFolder`, that should work.

> 1. I see that there is some kind of process of updating classpaths during project creation - If I will add all of above paths to classpaths array -Will it be used in that update process?

Generally all the classpaths are available for project compilation and updates. I don't think we should have any problem if we add multiple folders from same project to the classpaths - of course, you can give this a try and confirm. 

> 2. Currently in the UI in project tree we are marking by "S" icon only source folder - should we mark classpaths folders as "S" as well ?

This will create conflict of 'source folder' idea to other Moonshine projects then. User can add different projects' paths to the `classPaths` also. They can't be the selected project's direct source folders.

**Comment by piotrzarzycki21** [comment]
> Generally all the classpaths are available for project compilation and updates. I don't think we should have any problem if we add multiple folders from same project to the classpaths - of course, you can give this a try and confirm.

That's cool. Should I run any command for Grails project when someone go to the settings and add new folder to that list ?

**Comment by piotrzarzycki21** [comment]
> This will create conflict of 'source folder' idea to other Moonshine projects then. User can add different projects' paths to the `classPaths` also. They can't be the selected project's direct source folders.

Let's leave it for now, but I think above issue should be address in some way when we start refactoring.

**Comment by piotrzarzycki21** [comment]
I have tested changes with bigger Royale application where there are a lot of class paths and everything seems to working fine.

**Comment by rat-moonshine** [comment]
> This will create conflict of 'source folder' idea to other Moonshine projects then. User can add different projects' paths to the classPaths also. They can't be the selected project's direct source folders.

On a second thought, path from different projects do not shows to the selected project's tree in Moonshine (as Eclipse does); So marking 'S' icon to every `classPaths` paths shouldn't make any different to the UI.

**Comment by JoelProminic** [comment]
I confirmed I can create classes in directories @piotrzarzycki21 listed.

For the other directories, do we get errors if we add them to the classpath but they don't exist on the filesystem?  I would like to see these directories work automatically if the user adds them (and have the classpaths be added automatically for imported projects).

**Comment by piotrzarzycki21** [comment]
If I add non existing directory to classpaths when you go to project settings you will see red "x" near directory path. We don't get any errors. That's not the problem I can add them automatically - all those listed in the issue for import/open and creat project even if they doesn't exists.

**Comment by rat-moonshine** [comment]
> 
> 
> If I add non existing directory to classpaths when you go to project settings you will see red "x" near directory path. We don't get any errors. That's not the problem I can add them automatically - all those listed in the issue for import/open and creat project even if they doesn't exists.

That means the building plugin class doesn't checking invalid file paths before building/compilation - which suppose to notify user for invalid paths (as [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L500)). In my opinion, the procedures should be similar for all the project types.

**Comment by piotrzarzycki21** [comment]
> > If I add non existing directory to classpaths when you go to project settings you will see red "x" near directory path. We don't get any errors. That's not the problem I can add them automatically - all those listed in the issue for import/open and creat project even if they doesn't exists.
> 
> That means the building plugin class doesn't checking invalid file paths before building/compilation - which suppose to notify user for invalid paths (as [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L500)). In my opinion, the procedures should be similar for all the project types.

I think this is not the case. I didn't check building with that classpaths - if it will fail I shouldn't add it - in correct case it should. Thanks for pointing it.

**Comment by piotrzarzycki21** [comment]
I'm working on that farther today, but still something bothers me. What if I will add to `classpaths `in project **Settings** something - Should I notify language server about that changes ? I'm asking because when you create project you have information that classpath is being updated.

![classpath](https://user-images.githubusercontent.com/24554795/58941028-3c113a80-877b-11e9-9c69-b7a03e75e064.png)

**Comment by rat-moonshine** [comment]
> 
> 
> I'm working on that farther today, but still something bothers me. What if I will add to `classpaths `in project **Settings** something - Should I notify language server about that changes ? I'm asking because when you create project you have information that classpath is being updated.
> 
> ![classpath](https://user-images.githubusercontent.com/24554795/58941028-3c113a80-877b-11e9-9c69-b7a03e75e064.png)

That is a good question. Since language-server starts during project import, or when SDK updates to the project - any changes to the `classPaths` might not affect the current running language-server instance - which should actually. If a path removed, not-updating may not make much difference, but adding a new path from different project shall not take effect.

**Comment by piotrzarzycki21** [comment]
> If a path removed, not-updating may not make much difference, but adding a new path from different project shall not take effect.

I'm not entirely sure what do you mean. If let's say is true that language server should know that classpaths has been change - I think it should happen regardless it's remove/update or add.

**Comment by piotrzarzycki21** [comment]
Additional question is if in one of my classpaths I have class which contains some syntax error - I miss coma somewhere or whatever. - When I remove folder with that class from classpaths - should I still see errors during compilation ?

**Comment by rat-moonshine** [comment]
> 
> 
> > If a path removed, not-updating may not make much difference, but adding a new path from different project shall not take effect.
> 
> I'm not entirely sure what do you mean. If let's say is true that language server should know that classpaths has been change - I think it should happen regardless it's remove/update or add.

I see I have in misconception (as I never tested this before in particular way) that adding or removing paths doesn't affect to running-language server; It does. I tested this in following way for general project cases:

1. Create a new Flex desktop project
2. Make sure language-server is working to its opened editor
3. Add a new classpath from _different_ project
4. Return to the opened editor try to import any class-file from _different_ project's directory
5. Class-file imported

**Comment by piotrzarzycki21** [comment]
> I see I have in misconception (as I never tested this before in particular way) that adding or removing paths doesn't affect to running-language server; It does. I tested this in following way for general project cases:
> 
> 1. Create a new Flex desktop project
> 2. Make sure language-server is working to its opened editor
> 3. Add a new classpath from _different_ project
> 4. Return to the opened editor try to import any class-file from _different_ project's directory
> 5. Class-file imported

Ok in Flex project, but it looks like to me that in Grails it does not happen. I'm still in a process of analyzing code. @joshtynjala could you shed some light how actually this is working for Grails projects ?

**Comment by piotrzarzycki21** [comment]
My investigation towards me that what is in classpaths doesn't matter to language server, but let's wait for Josh's response, cause I may be totally wrong.

**Comment by piotrzarzycki21** [comment]
> For the other directories, do we get errors if we add them to the classpath but they don't exist on the filesystem? I would like to see these directories work automatically if the user adds them (and have the classpaths be added automatically for imported projects).

@JoelProminic your suggestion has been applied for new and imported project. Check new build.

**Comment by joshtynjala** [comment]
I guess that there's some kind of menu command to update Gradle class paths? It's for Java and Grails projects that use Gradle.

The Grails language server gets its class paths from the .classpath file that is updated when running this command. Moonshine also restarts the language server.

**Comment by rat-moonshine** [comment]
> 
> 
> I guess that there's some kind of menu command to update Gradle class paths? It's for Java and Grails projects that use Gradle.
> 
> The Grails language server gets its class paths from the .classpath file that is updated when running this command. Moonshine also restarts the language server.

Yes, it's `Project -> Refresh Gradle Classpaths`. So I'm wondering, adding new paths to the classpaths section also updates to the language-server after running this? (Or, adding any new path to the classpaths does make any sense for Gradle/Grails project (?))

**Comment by joshtynjala** [comment]
The Groovy language server should restart when you refresh Gradle classpaths, just like the Java language server is restarted. However, I just took a peek at the code, and it looks like I forgot to set up a listener for GradleBuildEvent.REFRESH_GRADLE_CLASSPATH.

**Comment by piotrzarzycki21** [comment]
> The Groovy language server should be restarted when you refresh Gradle classpaths, just like the Java language server is restarted. However, I just took a peek at the code, and it looks like I forgot to set up a listener for GradleBuildEvent.REFRESH_GRADLE_CLASSPATH.

Are you referring to code in language server ? Cause in Moonshine there is listener for that event and code for restarting language server.

**Comment by piotrzarzycki21** [comment]
I think we are good here. If I'm correct @rat-moonshine setup that listener. If there is any new work here lets raise new issue.
