### ISSUE TITLE
Import Grails Projects

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#568]
We need to update the import logic to allow users to import Grails projects.

Currently, "Grails Project" is an allowed Template Type in the project import form.  However, this project type requires that I choose a source folder and a main application file.  Grails doesn't have a main application file, so this doesn't make sense.  The source folder and main application file should not be required for Grails projects

I tried to use a file in src/main/groovy to get around this, but ".groovy" is not included in the filter for the main application file.   I used a Java file in src/main/java instead, but I got this error:

    : Error #3003
    : Error: Error #3003
    : 	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/parse()
    : 	at actionScripts.plugins.as3project::CreateProject/getProjectWithTemplate()
    : 	at actionScripts.plugins.as3project::CreateProject/createFileSystemBeforeSave()
    : 	at actionScripts.plugins.as3project::CreateProject/onCreateProjectSave()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at MethodInfo-25876()
    : 	at actionScripts.plugin.settings::SettingsView/save()
    : 	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()
    :
    : Click here to Report a Bug

Imported projects would reuse the existing build.gradle, and use the default configuration for Grails projects (for example, see #567)

**Comment by rat-moonshine** [comment]
This should be working now, however I noticed exception thrown to console after language-server start - but I think I did seen such error on macOS after re-opening Grails project, so I'm not sure if they are similar.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine  Are you working on that still ?

**Comment by JoelProminic** [comment]
This is working fine in my tests.
