### ISSUE TITLE
Run Grails Commands

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#570]
I would like a way to run arbitrary Grails commands from Moonshine.  For example:
- ```create-controller <name>``` - create a controller in grails-app/controllers
- ```create-domain <name>``` - create a domain in grails-app/domains
- ```create-service <name>``` - create a service in grails-app/services
- ```test-app``` - run the configured test cases

Note that the user can run these commands from an external command line, but I expect an IDE to be able to handle running at least basic tasks so that the user doesn't have to leave the application.

Requirements:
- Allow the user to enter a Grails command
- Keep a history of the commands used by the user, so that they can quickly rerun old commands.  It would also be nice to be able to edit commands (i.e. if user wants to run a bunch of create-controler commands)
- The task output needs to be diplayed, either in the console, or in a new interface.
- Some commands may launch a server, so the action may not finish automatically.  We should show the status of the running task, and allow the user to kill the task if desired. 

Some additional thoughts to consider:
- We could use a similar interface for Maven phases/goals and Gradle tasks (currently, we configure the "build actions" in the project settings instead).  We may want to make the code reusable for these other projects.
- Grails projects also some commands run from Gradle, like "clean" and "bootRun".  We may want to allow Gradle commands as well.

**Comment by rat-moonshine** [comment]
This issue is now up for test.

**Comment by JoelProminic** [comment]
@rat-moonshine, your implementation used the same Project Settings > Build interface from the Maven and Gradle projects.  However, I find this interface cumbersome to use, especially for one-time commands like "gradle create-domain-class demo.Author":
1. Right-Click on Project > Settings
2. Open Build tab
3. Click Change
4. Edit the create-domain-class entry (sorry, I did not write this correctly in my original writeup)
5. Save the selection
6. Project > Run Gradle Tasks
7. Repeat steps 1-6 to change the command back to my normal build command 

Instead, I want to be able to do it like this:
1. Build > Run Grails Task...   
2. Moonshine opens a small interface with an editable combobox to enter the command "create-domain-class demo.Person".  The user could check the drop down for previous commands
3. Click Run
4. The project can still be built with Project > Build & Run

Here is an example of how the interface might look.  
![image](https://user-images.githubusercontent.com/24532731/59068825-e2903500-887a-11e9-806c-73aec9c61c07.png)

Alternatively, we could run this with commands on the Moonshine console.  Unfortunately, I think most users may not even notice that they can run commands on the console - so would need to add some guidance to help them find this feature.

    > grails create-domain-class demo.Author

Please bring back the Project actions that Josh originally added (Build & Run and Build Release, I think).   These are useful as common commands that the user will want to execute.  The new feature described above should be a new action:   "Project > Run Grails Command...".

**Comment by rat-moonshine** [comment]
Following bug report from @JoelProminic should be fix now:

> And I am having trouble with completion
> 1. Select "create-service <name>"
> 2. Backspace to "create-service " and enter a name: "demo.Book"
> 3. Hit enter - this is fine
> 4. Backspace again to "create-" and complete with "domain demo.Book".
> 5. Hit enter. This corrects to "create service demo.Book"

**Comment by JoelProminic** [comment]
The behavior of the Run Custom Command prompt seems pretty good now.  The only remaining problem I have at the moment is that the secondary description field does not fit well in the interface.  As you can see in this screenshot, it got out of sync with the field value.

![image](https://user-images.githubusercontent.com/24532731/59471618-21853400-8e01-11e9-80f7-93ac2d293b23.png)

Since I intend to phase out the old "Build Actions" interface as we switch to the design described in #582, I think we should just remove this secondary field.

**Comment by JoelProminic** [comment]
For Grails project, I also occasionally need to run Gradle commands.  For example, I need to run ```gradle install``` in order to install this project to the local repository:  https://github.com/prominic/grails4-primefaces.git (If you try this, not that Grails 4.0.0 is required).  I also occasionally find that I need to run "gradle clean" on a Grails project to fully clean it.

To support this, please add a menu action under Project called "Run Gradle Command".  This should open a similar interface to Run Grails Command, but the label should be changed from "grails" to "gradle", and it should use a separate saved command list.   If it becomes confusing to have two similar prompts for this, we can look for ways to make it easier to tell them apart.

Note that Grails allows syntax like this ```grails gradle install```.  However, this failed even on the Terminal in my tests with errors that seemed to indicate that Grails and Grails were not matching up correctly.

**Comment by rat-moonshine** [comment]
@joshtynjala I have an query related to language-server(s) start to Java/Groovy projects. 

As some requirement came in where we may want some functionalities/fields shared by JavaProjectVO to GrailsProjectVO, I was testing if we can extends the latter with former. Do you think that approach could create any possible problem in future?

Also, while testing the changes, I noticed some exception thrown to console over language-server start to the Grails project:

```
: 14 Jun, 2019 11:15:09 AM Failed to configure project NewGrailsProject
: Build path contains duplicate entry: 'grails-app/conf' for project 'NewGrailsProject'
: Java Model Exception: Java Model Status [Build path contains duplicate entry: 'grails-app/conf' for project 'NewGrailsProject']
```
I found it's by the JavaLanguageServerManager that started against Grails project. I was in impression that its GroovyLanguageServerManager which probably creates particularly for the Grails project, but I see we have both the language-servers [starts](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/impls/ILanguageServerBridgeImp.as#L191) for the Grails project.

If the project-type extend approach you think is alright, do you think we can somehow overcome the above error?

**Comment by piotrzarzycki21** [comment]
> As some requirement came in where we may want some functionalities/fields shared by JavaProjectVO to GrailsProjectVO, I was testing if we can extends the latter with former. Do you think that approach could create any possible problem in future?

If that part is not needed, but rather wish it should be leave it as is, cause we will do significant refactoring.

**Comment by rat-moonshine** [comment]
Can you give some more hint on which areas' of refactoring you're pointing to here? 

It seems like we'll require to have Gradle build options etc. to be available to Grails project vo also. My thought was to instead of having duplicated fields here or there, if we can access the goodness of Java project inside Grails so any changes can apply to both the places.

**Comment by piotrzarzycki21** [comment]
> Can you give some more hint on which areas' of refactoring you're pointing to here?
> 
> It seems like we'll require to have Gradle build options etc. to be available to Grails project vo also. My thought was to instead of having duplicated fields here or there, if we can access the goodness of Java project inside Grails so any changes can apply to both the places.

I'm talking about refactoring CreateProject and All VO related to projects to be more robust, so do not bother about duplication. If we come up with good plan we should get rid of such concerns in the future. We will see.

**Comment by rat-moonshine** [comment]
Okay. But maybe it'd be better to have less wasted codes until a restructure is happen. I'll see what I can do about it.

**Comment by joshtynjala** [comment]
> but I see we have both the language-servers starts for the Grails project.

We definitely don't want both language servers to start for one project. If we changed GrailsProjectVO to extend JavaProjectVO, we'd need to change that code to ensure that only one language server starts. Instead of separate ifs, we'd need if and else if there.

There are many places where we check which type of ProjectVO is being used. If we made this change, they'd all need to be double-checked for similar problems where two conditions could match.

The Groovy language server does not actually use the contents of the grailsproj file at all, so the changes would not affect it. It would all be on the Moonshine side.

**Comment by JoelProminic** [comment]
The interface requested for this issue has been working well, so I'll close this issue.

The "Run Gradle Commands" interface also works well, but note that Grails may require a different version of Gradle than the one installed by Moonshine.  See #593 for more details.
