### ISSUE TITLE
Moonshine 2.4.0 Starter Page not downloading SDK

### ISSUE THREAD

**Issue by slow1ne** [prominic/Moonshine-IDE#572]
- [ ] Review the documentation: https://github.com/prominic/Moonshine-IDE
- [ ] Search for existing issues: https://github.com/prominic/Moonshine-IDE/issues
- [ ] Use the latest stable version at: http://moonshine-ide.com
- [ ] Let us know how to reproduce the issue. Include a code sample, or share a project that reproduces the issue

## Environment
Windows 7 Professional 32bit
Moonshine 2.4.0
## Description
Additional error from previous error in Moonshine 2.2.0
Scrolling in report a bug not working.

## Steps to Reproduce
Try to download missing SDKs from Starter Page ( Feathers, Maven, Etc )

## Expected Behavior
Download missing SDKs

## Actual Behavior/Errors
Errors, however manually adding my installed SDKs shows them now. 
But this version has additional error messages.

### Errors
 'null' is not recognized as an internal or external command,
: operable program or batch file.
: Moonshine IDE™ 2.4.0
: Copyright © Prominic.NET, Inc. All rights reserved.
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 32.0.0.125
: Error #3219
: Error: Error #3219
: 	at flash.desktop::NativeProcess/start()
: 	at actionScripts.utils::MSDKIdownloadUtil/runAppStoreHelperWindows()
: 	at MethodInfo-39232()
: 	at actionScripts.utils::Unzip/unzipTo()
: 	at MethodInfo-25952()
: 	at MethodInfo-15074()
:
: Click here to Report a Bug
: Error #3219
: Error: Error #3219
: 	at flash.desktop::NativeProcess/start()
: 	at actionScripts.utils::MSDKIdownloadUtil/runAppStoreHelperWindows()
: 	at actionScripts.utils::MSDKIdownloadUtil/runOrDownloadSDKInstaller()
: 	at components.popup::GettingStartedPopup/runAppStoreHelper()
: 	at components.popup::GettingStartedPopup/__viewHelper_DOWNLOAD_COMPONENT()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at components.renderers::PackageDependencyRenderer/onDownloadRequest()
: 	at components.renderers::PackageDependencyRenderer/__imgDownload_click()
:
: Click here to Report a Bug
: Error #3219
: Error: Error #3219
: 	at flash.desktop::NativeProcess/start()
: 	at actionScripts.utils::MSDKIdownloadUtil/runAppStoreHelperWindows()
: 	at actionScripts.utils::MSDKIdownloadUtil/runOrDownloadSDKInstaller()
: 	at components.popup::GettingStartedPopup/runAppStoreHelper()
: 	at components.popup::GettingStartedPopup/__viewHelper_DOWNLOAD_COMPONENT()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at components.renderers::PackageDependencyRenderer/onDownloadRequest()
: 	at components.renderers::PackageDependencyRenderer/__imgDownload_click()
:
: Click here to Report a Bug
: Error #3219
: Error: Error #3219
: 	at flash.desktop::NativeProcess/start()
: 	at actionScripts.utils::MSDKIdownloadUtil/runAppStoreHelperWindows()
: 	at actionScripts.utils::MSDKIdownloadUtil/runOrDownloadSDKInstaller()
: 	at components.popup::GettingStartedPopup/runAppStoreHelper()
: 	at components.popup::GettingStartedPopup/__viewHelper_DOWNLOAD_COMPONENT()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at components.renderers::PackageDependencyRenderer/onDownloadRequest()
: 	at components.renderers::PackageDependencyRenderer/__imgDownload_click()
:
: Click here to Report a Bug
: Error #3219
: Error: Error #3219
: 	at flash.desktop::NativeProcess/start()
: 	at actionScripts.utils::MSDKIdownloadUtil/runAppStoreHelperWindows()
: 	at actionScripts.utils::MSDKIdownloadUtil/runOrDownloadSDKInstaller()
: 	at components.popup::GettingStartedPopup/runAppStoreHelper()
: 	at components.popup::GettingStartedPopup/___GettingStartedPopup_Button1_click()
:
: Click here to Report a Bug
: Error #3219
: Error: Error #3219
: 	at flash.desktop::NativeProcess/start()
: 	at actionScripts.utils::MSDKIdownloadUtil/runAppStoreHelperWindows()
: 	at actionScripts.utils::MSDKIdownloadUtil/runOrDownloadSDKInstaller()
: 	at components.popup::GettingStartedPopup/runAppStoreHelper()
: 	at components.popup::GettingStartedPopup/___GettingStartedPopup_Button1_click()
:
: Click here to Report a Bug

**Comment by piotrzarzycki21** [comment]
@rat-moonshine let's close this one if it occurs to be a duplication with #563 . Can you setup some virtual machine and check this ?

**Comment by slow1ne** [comment]
Oh, it asked me to try some feature and connect it with the old one.

**Comment by slow1ne** [comment]
![image](https://user-images.githubusercontent.com/22088839/58801652-206e2e80-85d9-11e9-8448-2511f4bf4fd9.png)

**Comment by piotrzarzycki21** [comment]
When you click on whatever SDK you have on the list Moonshine SDK Installer do not even launch for you ? You should see following application:

![msdk](https://user-images.githubusercontent.com/24554795/58801709-955a5c00-860b-11e9-99aa-ee63aab41664.png)

**Comment by slow1ne** [comment]
Negative.
Clicking the Download third party button does nothing. Even waiting several minutes now.

**Comment by slow1ne** [comment]
![image](https://user-images.githubusercontent.com/22088839/58801815-9c687680-85d9-11e9-822b-949a40e75ed0.png)

**Comment by piotrzarzycki21** [comment]
Ok one more question do you see following folder -> `c:\Users\{youruser}\AppData\Roaming\net.prominic.MoonshineSDKInstaller\64Bit\`

**Comment by slow1ne** [comment]
![image](https://user-images.githubusercontent.com/22088839/58802329-e7cf5480-85da-11e9-93a3-875f9d43c5d2.png)

**Comment by rat-moonshine** [comment]
@slow1ne Thank you again, for showing your patience and helping us finding the problem for you.

> 
> 
> As you can see, GIT and SVN are installed, but they are not listed as installed.
> ![image](https://user-images.githubusercontent.com/22088839/58801652-206e2e80-85d9-11e9-8448-2511f4bf4fd9.png)

Few immediate thoughts from my side.. 

SDKs those shown as installed in 'Getting Started' page calculates upon few things. One crucial one is the paths set in Moonshine Settings (`File > Settings`):
![image](https://user-images.githubusercontent.com/24370870/58802410-c26a3700-862a-11e9-8cc0-86e64b439da7.png)

"Repository Manager" only holds entries. Can you check if 'Git' and 'Subversion' section in your Moonshine settings has correct paths?

On opening Moonshine SDK Installer, the screenshot says you have already it downloaded, thus it tries to open it only:
![image](https://user-images.githubusercontent.com/24370870/58802536-107f3a80-862b-11e9-8997-87567fad2399.png)

What happen if you manually try to run "Moonshine SDK Installer.exe" from that folder?

**Comment by slow1ne** [comment]
I do not mind helping at all! 
![image](https://user-images.githubusercontent.com/22088839/58802741-eb171000-85db-11e9-9702-45bc18105314.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine He is on 32 bit system, so I'm not sure how our app will work there.

**Comment by slow1ne** [comment]
I thought it may have been a 32bit vs 64bit problem.. After this error that popped up in my above screenshot.

**Comment by piotrzarzycki21** [comment]
> I do not mind helping at all!
> ![image](https://user-images.githubusercontent.com/22088839/58802741-eb171000-85db-11e9-9702-45bc18105314.png)

It doesn't work at all which make perfectly sense now. We need to discuss what to do with that. 
@slow1ne Are you going at some point move to newest windows ?

**Comment by piotrzarzycki21** [comment]
> I thought it may have been a 32bit vs 64bit problem.. After this error that popped up in my above screenshot.

What SDK are you particularly interested ? Apache Royale ? You can download it for now manually and setup in Moonshine.

**Comment by slow1ne** [comment]
> > I do not mind helping at all!
> > ![image](https://user-images.githubusercontent.com/22088839/58802741-eb171000-85db-11e9-9702-45bc18105314.png)
> 
> It doesn't work at all which make perfectly sense now. We need to discuss what to do with that.
> @slow1ne Are you going at some point move to newest windows ?

No. I do not plan to ever move past windows 7.
 I still have an IBM thinkpad x40 with XP and Kali dual boot.
My issues was just not having the installer work, which it makes sense now -  it's meant for 64bit systems. I have manually configured my SDKS to be found in the settings.

**Comment by rat-moonshine** [comment]
> 
> 
> I do not mind helping at all!
> ![image](https://user-images.githubusercontent.com/22088839/58802741-eb171000-85db-11e9-9702-45bc18105314.png)



> 
> 
> @rat-moonshine He is on 32 bit system, so I'm not sure how our app will work there.

Yes, it's makes sense now.

**Comment by piotrzarzycki21** [comment]
Report if you have problems to SDK related. We will discuss farther what to do with above issue, but we may decide not pursue this. OS in general on PC are moving toward 64bit and support for Windows 7 will end at some point from MS. Who know it is possible that Moonshine will move to 64bit itself as well.

**Comment by slow1ne** [comment]
I would just suggest adding a disclaimer for now, that 32bit systems are a bit wonky and requires to manually add your SDKs and other things, and leave the starter page alone.

I appreciate the help. 
If i can figure a work around in the mean time, I will let you all know.

And maybe one day I will go 64bit. ;)

**Comment by slow1ne** [comment]
After a little bit of research.. (https://docs.microsoft.com/en-us/windows/desktop/sbscs/application-manifests)
I was wondering if it was possible to do a Side by Side assembly?
Using my Hex editor I found this:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>..
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
<security><requestedPrivileges>
<requestedExecutionLevel level="asInvoker" uiAccess="false">
</requestedExecutionLevel>
</requestedPrivileges>
</security>
</trustInfo>
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
<application><supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}">
</supportedOS><supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}">
</supportedOS><supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}">
</supportedOS><supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}">
</supportedOS><supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}">
</supportedOS>
</application>
</compatibility>
</assembly>
Windows 7 is included, but what about including ia64 and x86 support in the assemblies? Just an idea.

**Comment by JustinProminic** [comment]
@piotrzarzycki21 we have not heard from this user since June 2019, so if we can't revive this issue by the close of milestone 2.7.1, then lets close this issue. Thanks!

**Comment by piotrzarzycki21** [comment]
@slow1ne Test with newest Moonshine. Bear in mind that we rather do not support Windows 7 anymore.
