### ISSUE TITLE
File > Open vs Project > Open

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#574]
Multiple Prominic developers have reported confusion with the File > Open prompt.  They tried to use it to open a project, but the file chooser wouldn't allow selection of a directory.  I would like to update this so that it is more clear.

Here are my proposed changes.  I am open to discussion if someone doesn't like these ideas.
- Add another menu item called File > Open/Import Project.  This will point to the same action as Project > Open/Import Project - I would like to keep it in both locations.
- Change File > Open to File > Open File
- Move the CMD-O/CTRL-O shortcut to File > Open/Import Project.  File > Open can use CMD-Shift-O or CTRL-Shift-O.

I updated the shortcuts because I felt that Open/Import Project was the more important of these options.  Since we have Edit > Find Resources (CMD-Shift-R), I almost never use File > Open File.  (We could also consider assigning CMD-O to Edit > Find Resources, so match IntelliJ).

**Comment by rat-moonshine** [comment]
This should work as asked now.

**Comment by JoelProminic** [comment]
I confirmed that the menu actions are updated for macOS and Windows

**Comment by JoelProminic** [comment]
However, after a bit more testing, I see that File > Open gives an error when I try to open a file:

macOS (AppStore, but I have a bookmark to the parent directory):

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.controllers::OpenFileCommand/openTextFile()
    : 	at actionScripts.controllers::OpenFileCommand/openFile()
    : 	at actionScripts.impls::IFileBridgeImp/browseForOpen()
    : 	at actionScripts.controllers::OpenFileCommand/execute()
    : 	at actionScripts.locator::IDEController/execCommand()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
    : 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
    : 	at actionScripts.ui.menu::MenuPlugin/redispatch()
    : 	at flash.display::NativeMenuItem/performKeyEquivalent()
    : 	at flash.display::NativeMenu/performKeyEquivalent()
    : 	at flash.display::NativeMenuItem/performKeyEquivalent()
    : 	at flash.display::NativeMenu/performKeyEquivalent()
    : 	at flash.desktop::NativeApplication/_onKeyDownCapture()
    :
    : Click here to Report a Bug

Windows:

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.controllers::OpenFileCommand/openTextFile()
    : 	at actionScripts.controllers::OpenFileCommand/openFile()
    : 	at MethodInfo-5132()
    :
    : Click here to Report a Bug

**Comment by rat-moonshine** [comment]
I noticed the existing `Open File` type list was not updated with recent times'. This has been updated now.

Error during opening through `Open File` command also fixed. Please, check.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine You have made File Shorcut CTRL + SHIFT + O - I think it was shortcut to organize imports - If I'm correct what is the shortcut for organize import now ?

**Comment by rat-moonshine** [comment]
The shortcut keys alternated between Open File and Open/Import Projects:

> Move the CMD-O/CTRL-O shortcut to File > Open/Import Project. File > Open can use CMD-Shift-O or CTRL-Shift-O

**Comment by piotrzarzycki21** [comment]
> The shortcut keys alternated between Open File and Open/Import Projects:
> 
> > Move the CMD-O/CTRL-O shortcut to File > Open/Import Project. File > Open can use CMD-Shift-O or CTRL-Shift-O

Ok. How to organize import by shortcut right now ?

**Comment by piotrzarzycki21** [comment]
Ok I just checked in the code and organize imports had exactly shortcuts as it is changed now CTRL+SHIFT+O, so to what shortcut we would like to change it now ?

**Comment by rat-moonshine** [comment]
Can someone tell me how `Duplicate (CTRL+U)` works? I also think we need a line-deletion shortcut (something like CTRL+D to remove a line at once).

**Comment by piotrzarzycki21** [comment]
If there is no proposition so far I'm changing organize imports to CTRL+SHIFT+I.

**Comment by piotrzarzycki21** [comment]
Can we close that one or is it still need to be tested ?

**Comment by piotrzarzycki21** [comment]
Can we close that one or is it still need to be tested ?

**Comment by rat-moonshine** [comment]
The main area for this issue reported has been resolved. I think Joel also confirmed that having Ctrl+Shift+I for Organize Imports is Okay. Thus, let's close this.

**Comment by JoelProminic** [comment]
Yeah, I don't have any immediate concerns for CTRL+Shift+I - I was waiting to see if we found any other conflicts during testing.  

Otherwise, the updates seem good.
