### ISSUE TITLE
Last Character Excluded in Text Selection

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#576]
I noticed some strange text selection behavior in Moonshine.  I tested with the macOS App Store build.
1. Clone https://github.com/prominic/git-meta.git
2. Open moonshine-dependencies.xml
3. Find the line "<label>Prominic.NET Projects on GitHub</label>"
4. Click between the 'b' and the '<' at the end of the label, and drag to the left to select the entire contents of the <label> element. BUG:  the selection expands to include the '<' character from ""</label>"
5. Click between the 'u' an and 'b' in "GitHub".  Drag to the left to the beginning of "Prominic".  This will select the entire text of the <label> element>
6. Press Delete.  BUG:  Moonshine deletes the selected text except for the last character.

I noticed similar errors if I select from left to right - the last character appears in the selection, but it is not affected by any commands.

I saw similar behavior in the MXML, Java, and Actionscript editors as well.

**Comment by rat-moonshine** [comment]
Mouse caret position and selection should be in sync now.

**Comment by JoelProminic** [comment]
This works well for me now.

On a related note, I am seeing some intermittent issues where I can't select to the end of a previous line without selecting the last character of this line.   We origininally fixed problem back when we were still using the Prominic JIRA to track issues (MOON-302).   If I can repeat the issue consistently, I'll get it added in an issue on GitHub.

**Comment by rat-moonshine** [comment]
Okay. I'm closing this particular then. Please, reopen if any further problem found to this.

**Comment by JoelProminic** [comment]
Another Prominic developer noted that double-clicking on a word/symbol in the editor also selects the trailing whitespace, if any.   If this is a separate issue, we can move it to a different issue as appropriate.  If this was an intentional behavior, we can discuss whether it is still desirable.

**Comment by rat-moonshine** [comment]
> 
> 
> Another Prominic developer noted that double-clicking on a word/symbol in the editor also selects the trailing whitespace, if any. If this is a separate issue, we can move it to a different issue as appropriate. If this was an intentional behavior, we can discuss whether it is still desirable.

This behavior is a bug, we need to fix it.

**Comment by rat-moonshine** [comment]
The trailing space should be handled now. Please. check.

**Comment by JoelProminic** [comment]
This seems to be working well.   One oddity I noticed that clicking on a space or at the very beginning of a word selects both the preceding and following word.  I'm not too worried about this for now, though, since the primary use case is clicking in the middle of the word:
![image](https://user-images.githubusercontent.com/24532731/59301052-54d78f80-8c56-11e9-8883-eb306fb896e5.png)
