### ISSUE TITLE
Breakpoint adds to a line even when clicked outside of the line-number area

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#581]
I noticed this sometime back (I didn't had a chance to report this issue), and this is very irritating.

I noticed even if I clicked outside of the line-number area in the editor (marked in red), the line receive a breakpoint:

![image](https://user-images.githubusercontent.com/24370870/59244563-9bb38e00-8c32-11e9-8c4b-1c3b2fb5d513.png)

**Comment by rat-moonshine** [comment]
Breakpoint hit area should be more flexible now. Report if any accessibility issue noticed.

**Comment by JoelProminic** [comment]
I tested this, and it seemed to work mostly like I expect.   

I noticed that when I have added a breakpoint, the highlighted area after the number is not clickable.

![image](https://user-images.githubusercontent.com/24532731/59937931-4db03e80-9419-11e9-91f0-7fbb6ef7006b.png)

@rat-moonshine clarified that this area was what was causing the original problem - when it is not highlighted, this looks like part of the whitespace on the line.   I'm not sure if this will be an annoyance for normal users (who are not specifically checking the clickable area), but if we get complaints, we could try changing the clickable area based on whether it is currently highlighted or not.

**Comment by rat-moonshine** [comment]
> @rat-moonshine clarified that this area was what was causing the original problem - when it is not highlighted, this looks like part of the whitespace on the line. I'm not sure if this will be an annoyance for normal users (who are not specifically checking the clickable area), but if we get complaints, we could try changing the clickable area based on whether it is currently highlighted or not.

I think this is not about a very close-click to the line number, but also when you clicked somewhere even away from the line-number; Please, check the issue description here:
![image](https://user-images.githubusercontent.com/24370870/59244563-9bb38e00-8c32-11e9-8c4b-1c3b2fb5d513.png)

As the current fix behave more gentle manner now, I'm closing this unless we'll see any problem to this.
