### ISSUE TITLE
Flex and Feather Download Fail on Flash

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#584]
A Prominic coworker tried to use the Moonshine SDK Installer today, and he got errors on Flex, Feathers, and OpenJDK:

    Installing Adobe Flash Player playerglobal.swc from: https://fpdownload.macromedia.com/get/flashplayer/updaters/32//playerglobal32_0.swc
    Validating download: /Users/<user>/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/frameworks/libs/player/32.0/playerglobal.swc
    Flash SDK download failed

    Downloading openjava from: http://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u202b08.tar.gz
    Unable to download openjava

    /Users/<user>/Downloads/MoonshineSDKs/Flex_SDK/feathers-sdk-4.0.0-bin is now an IDE compatible folder
    Flash SDK download failed

I ran the test myself, and I got the same errors for Flex and Feathers.  OpenJDK worked fine in my test, but we should watch for more errors.

https://fpdownload.macromedia.com/get/flashplayer/updaters/32//playerglobal32_0.swc worked for me in a manual test, so I'm not sure why this failed from Moonshine SDK Installer.

**Comment by JoelProminic** [comment]
Here is my full import log:
[2019_06_14__MoomshineSDKInstaller_Joel.log](https://github.com/prominic/Moonshine-IDE/files/3292423/2019_06_14__MoomshineSDKInstaller_Joel.log)

**Comment by piotrzarzycki21** [comment]
This is probably due to MD5 changes on Adobe sight. I will look into that.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just removed Flex SDK from `c:\MoonshineSDKs\Flex_SDK\` manually and removed from lists in the Moonshine settings. - Getting started still indicates for me that I have Flex installed. - I did this exercises in order to test download of Flex SDK.

**Comment by piotrzarzycki21** [comment]
Along with removing Flex I have removed as well Feathers and this is being indicated correctly on Getting Started:
![feathers](https://user-images.githubusercontent.com/24554795/59550456-44cbf280-8f6b-11e9-91f3-35d4015e966a.png)

**Comment by piotrzarzycki21** [comment]
Ok sorry for the noise it seems to flex is being used from FLEX_HOME that's why I'm seeing it is installed.

**Comment by piotrzarzycki21** [comment]
Downloading SDK should work.

**Comment by rat-moonshine** [comment]
I tested Moonshine SDK Installer downloads with v2.3.0 on Windows and macOS El Capitan. I confirm I able to download Feathers and OpenJDK (from their respective locations) without any problem. It is possible that some Macromedia/Adobe download severs/links may not accessible time to time. I would like to recommend to try this once again.

As a second download, I downloaded Apache Flex SDK which also downloads playerglobal_swc_32, but I didn't noticed any problem either. All downloads worked fine for me.

**Comment by piotrzarzycki21** [comment]
> I tested Moonshine SDK Installer downloads with v2.3.0 on Windows and macOS El Capitan. I confirm I able to download Feathers and OpenJDK (from their respective locations) without any problem. It is possible that some Macromedia/Adobe download severs/links may not accessible time to time. I would like to recommend to try this once again.
> 
> As a second download, I downloaded Apache Flex SDK which also downloads playerglobal_swc_32, but I didn't noticed any problem either. All downloads worked fine for me.

It was MD5 problem not inaccessibility of links. If it's working I'm closing this.

**Comment by rat-moonshine** [comment]
I don't think MD5 changes often, we could have access problem to the online MD5 checker though. 

Also, it'd be helpful if we keep the issue open for the reporter's final tests, and then we move to close it.

**Comment by piotrzarzycki21** [comment]
> I don't think MD5 changes often, we could have access problem to the online MD5 checker though.
> 
> Also, it'd be helpful if we keep the issue open for the reporter's final tests, and then we move to close it.

MD5 changes occasionally by Adobe and it is independent from us. Once it's changed I need to make updates on Apache Flex project sight. It think it's enough that already 3 people tested it (me, you and [one Apache Flex user](http://apache-flex-users.2333346.n4.nabble.com/SDK-Installer-failure-on-Mac-Windows-td17794.html)) - I don't expect that something will be different on Joel's sight.

**Comment by rat-moonshine** [comment]
Okay, thanks for explaining this @piotrzarzycki21 .

**Comment by JoelProminic** [comment]
I retested this on my laptop on macOS 10.13.6, and the Flex and Feathers SDK downloads did not fail.
