### ISSUE TITLE
SDKs Do Not Configure Automatically From Installer with non-Sandbox Build

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#585]
While testing #584 on macOS 10.13.6 with the non-Sandbox build, I found that the SDK paths were not populated automaticallly after running Moonshine SDK Installer.
1. Install the latest non-Sandbox macOS build
1. Remove/Rename ~/Desktop/MoonshineSDKs
1. Remove project settings:  ~/Library/Application Support/com.moonshine-ide
1. Open Moonshine - Getting Started prompt appears
1. Install all SDKs with Moonshine SDK Installer.  Flex and Feathers failed for me (see #584)
1. Check Moonshine - BUG:  none of the SDKs show as configured
1. Check the setting pages - the SDKs do not show up.
1. Restart Moonshine, and check the SDKs again.   Now all of the SDKs have been setup.

This is a bad user experience, because then they think they have to go configure all the SDKs manually.   It is nice that the references update on restart, but the user may not know that this was a possibility.

**Comment by rat-moonshine** [comment]
The paths are suppose to automatically updated to the running Moonshine, and this is how we tested the system. I'll need to check if this procedure is failing for non-sandbox particularly, as we may have not tested this with the particular build.

**Comment by rat-moonshine** [comment]
This issue is now handled. Please, install both Moonshine and Moonshine-SDK-Installer applications to test.

**Comment by JoelProminic** [comment]
We found some more problems during the meeting this morning, but @rat-moonshine pushed a fix.  This works for me on macOS 10.13.6.

However, the fix involved moving the status file to ~/Downloads/MoonshineSDKs, so that it would be reachable by all Moonshine versions.   We need to retest this on macOS App Store and Windows.

**Comment by rat-moonshine** [comment]
Tested on Windows, so far I didn't noticed any problem with recent changes.
