### ISSUE TITLE
"Esc exits" in plugin descriptions

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#587]
For example, `AntBuildPlugin` has the following description:

```actionscript
override public function get description():String
{
    return "Apache Ant® Build Plugin. Esc exits.";
}
```

(many other plugins have it too)

Pressing the <kbd>Esc</kbd> key doesn't actually exit the settings. Either it should exit the settings, or this text should be removed from the description.

**Comment by rat-moonshine** [comment]
What is the expected behavior we would want against Settings windows - do we want to have the tab removed on Esc keys or close by buttons?

**Comment by JoelProminic** [comment]
I think that " Esc exists." should be removed from these messages - either way, I don't think this is the right place for this message.

I don't have a really strong opinion on whether Esc should close (Cancel) the settings page.   However, I don't want this behavior for Esc on the editor pages (I am used to vi shortcuts, so I have a habit of tapping the Esc key).

Unless someone really wants the mentioned Esc logic, I think we should just remove the text and keep the current behavior.

**Comment by rat-moonshine** [comment]
All the 'Esc exits.' reference have removed in Moonshine.
