### ISSUE TITLE
Sets option -optimize=true in project settings doesn't work

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#59]
While my work on #50 I have run into issue where build of SWF only FlexJS/Royale application is failing if I don't have setup "-optimize=true" in project settings.

**Scenario 1:** User has in the FlexJS project settings unchecked option "Optimize". 
- Choose "Project" -> "Build Project".

We are building compiler arguments by that [line ](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L570) and gets value:
`" -load-config+=obj/NewFlexJSBrowserProjectConfig.xml -optimize=false -debug=true -o bin-debug/NewFlexJSBrowserProject.swf"`
Next step is retrieving whether user add some additional argument by that [line ](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L572) and gets value:
`"  -optimize=false"`

In the results compiler gets two time optimize and will fail with:
`command line configuration variable 'compiler.optimize' must only be set once.`

**Scenario 2:** User has in the FlexJS project settings has checked option "Optimize". 
Mentioned lines in **Scenario 1** returns:
[Line 1](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L570):  `" -load-config+=obj/NewFlexJSBrowserProjectConfig.xml -debug=true -o bin-debug/NewFlexJSBrowserProject.swf"`
[Line 2](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L572): `Additional compiler options is empty`

As you can see after checking "Optimize" (**Scenario 2**) in the settings "-optimize=true" disappear completely from command line.

**Why ?** 
It look like it is caused by function `getArgumetns` in `BuildOptions` by following [line](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/plugin/actionscript/as3project/vo/BuildOptions.as#L125). If selected option in settings is different than default one we are adding it to the command line arguments, but what is happen if it's same as default one? -> **Scenario 2**

**Comment by piotrzarzycki21** [comment]
I forgot to mention that I have temporary added this [line](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L568) for compilation FlexJS/Royale applications you have to commented out in order to reproduce the issue.

**Comment by rat-moonshine** [comment]
> At the end it look like we need to decide what should have precedence:
> 
> Selected option in settings or typed argument in the users field "Additional compiler options"?
> Selected option in the settings or default one ?
I think different people would have different view on this - which option should take preference over another - typed argument or option in Settings. 

Even if we give one of them preference, that may confuse users at some time (when they might forgot that other way of setting 'optimize' also exists). 

I suggest two options in this case:
- Remove 'optimize' option (checkbox) from Settings and internally handle it, or depends on additional argument value; But this chose has downside - because almost every option can be set through additional argument, and we may end by removing all the options from Settings. 
- Giving preference to additional argument - because that argument is intentional and we can think user knows what s/he is doing

Let me know your thought on this, @piotrzarzycki21 .

**Comment by piotrzarzycki21** [comment]
I would go with the option 2 and in my opinion it is working the same in other IDEs.

**Comment by rat-moonshine** [comment]
You can proceed if you want, else I shall if you are taken with other things.

**Comment by piotrzarzycki21** [comment]
Let me take this one and I will give other which I'm raising. It is UI issue, not so trivial probably. I believe you are more familiar in that area.
