### ISSUE TITLE
.grailsproj Does Not Need to Match Directory Name

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#592]
I noticed that Moonshine triggers an error if the .grailsproj does not match the name of the Grails project.  For example:
1. Add this repository: https://github.com/prominic/grails4-primefaces.git 
1. Clone the project, but rename the project directory to "grails4-primefaces_rename"
1. The project opens, but this error triggers on the console.

    : Error reading XML file: /Users/-user-/Documents/Flex/temp_workspace/grails4-primefaces_changename/grails4-primefaces_changename.grailsproj
    : java.io.FileNotFoundException: /Users/joelanderson/Documents/Flex/temp_workspace/grails4-primefaces_changename/grails4-primefaces_changename.grailsproj (No such file or directory)
    : 	at java.io.FileInputStream.open0(Native Method)
    : 	at java.io.FileInputStream.open(FileInputStream.java:195)
    : 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
    : 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
    : 	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    : 	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
    : 	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
    : 	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
    : 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806)
    : 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
    : 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    : 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
    : 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
    : 	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
    : 	at moonshine.groovyls.GrailsProjectCompilationUnitFactory.loadXMLDocument(GrailsProjectCompilationUnitFactory.java:151)
    : 	at moonshine.groovyls.GrailsProjectCompilationUnitFactory.create(GrailsProjectCompilationUnitFactory.java:71)
    : 	at net.prominic.groovyls.GroovyServices.createOrUpdateCompilationUnit(GroovyServices.java:358)
    : 	at net.prominic.groovyls.GroovyServices.setWorkspaceRoot(GroovyServices.java:112)
    : 	at net.prominic.groovyls.GroovyLanguageServer.initialize(GroovyLanguageServer.java:70)
    : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    : 	at java.lang.reflect.Method.invoke(Method.java:498)
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
    : 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
    : 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
    : 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
    : 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
    : 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    : 	at java.lang.Thread.run(Thread.java:748)

**Comment by rat-moonshine** [comment]
I did some updates at Moonshine side, I also found a static name+extension reference in [GrailsProjectCompilationUnitFactory.java](https://github.com/prominic/Moonshine-IDE/blob/master/language-server-wrappers/moonshine-groovy/src/main/java/moonshine/groovyls/GrailsProjectCompilationUnitFactory.java#L75) which was throwing the error during language-server start. 

I don't know things requisite to Java, I just tried to search for some examples, and API docs etc online and created an working method [here](https://github.com/prominic/Moonshine-IDE/blob/master/language-server-wrappers/moonshine-groovy/src/main/java/moonshine/groovyls/GrailsProjectCompilationUnitFactory.java#L169). Which suppose to search for a file with .grailsproj name extension in a directory listing. @joshtynjala please, do update the method if we have some more proper way to do this. I just did per my basic understanding, I don't know Java.

For the moment, I don't see any above error anymore during language-server start to Grails project. Please, check.

**Comment by JoelProminic** [comment]
The .grailsproj updates seem fine. I tested:
- .grailsproj with a different name
- .grailsproj with the same name
- no .grails4proj (triggered import dialog)

I notice that double-clicking the .grails4proj file does not open the project in Moonshine, though.

**Comment by rat-moonshine** [comment]
> I notice that double-clicking the .grails4proj file does not open the project in Moonshine, though.

I pushed an update for above. But this requires to build and install to test it's working.

**Comment by rat-moonshine** [comment]
As the above requirements seems met, I'm closing this issue unless we want to do anymore amendments/fix.
