### ISSUE TITLE
Add Apache Royale nightly build download to Getting Started

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#594]
@rat-moonshine this should be first priority adding Nightly Build for next release. Another user come to Moonshine and first thing which he did he download 0.9.4 SDK which is definitely outdated and had problem with building newest examples.

**Comment by rat-moonshine** [comment]
Yeah, this likely a very problematic thing when stable release does not work. I'll talk to @JoelProminic whether we want to create a new entry for nightly build download (in MSDKI) or replace the existing one (anyway, the existing stable one does not meet our purpose now).

**Comment by rat-moonshine** [comment]
I think it'd be good to move the issue to https://github.com/prominic/Moonshine-SDK-Installer/issues @piotrzarzycki21 .

**Comment by piotrzarzycki21** [comment]
I have added issue there. Closing this one.
