### ISSUE TITLE
Royale references to Useful Links

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#597]
We need to add known useful (and not-outdated) links of Royale/Jewel references to Useful Links in Moonshine. Following are few links which I noticed during my involvement, this can be updated per necessary:

- Royale website (https://royale.apache.org/)
- Tour de Jewel (https://royale.apache.org/tourdejewel/)
- [Royale API Docs](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/Royale_ASDoc_Example/lastSuccessfulBuild/artifact/examples/royale/ASDoc/bin/js-debug/index.html) (nightly)

**Comment by piotrzarzycki21** [comment]
New nightly build link: http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/194/

**Comment by piotrzarzycki21** [comment]
API ASDoc: http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/Royale_ASDoc_Example/lastSuccessfulBuild/artifact/examples/royale/ASDoc/bin/js-release/index.html

**Comment by rat-moonshine** [comment]
Links have updated.

**Comment by JoelProminic** [comment]
I checked the links, and they seem to be correct now.
