### ISSUE TITLE
Section "RECENT" projects disappear after open console

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#60]
When I start Moonshine with closed console "Home" tab looks perfectly fine, but once I open console and make it a bit higher UI is being messed up. Note that it is not always reproducible if you have some projects on the list.

**Scenario:**
1) Open Moonshine with closed console
2) Open console and observe "RECENT" - If nothing happen, try to restart Moonshine with that console position.

Screenshot - No "RECENT":
![image](https://user-images.githubusercontent.com/24554795/32366696-84deba90-c07f-11e7-8d20-0c18e531c096.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine In IDE (debug) mode when I have all settings cleaned up, no Recent projects etc. I'm getting following exceptions clicking on "Open Apache Flex/JS Project"

```
Type Coercion failed: cannot convert components.renderers::TemplateItemRenderer@10088c29 to components.renderers.RecentProjectRenderer.
at components.views.splashscreen::SplashScreen/handleRecentClick()[D:\flex_sdk\Projects\Prominic.NET\Moonshine Project\Moonshine-IDE\ide\MoonshineSharedCore\src\components\views\splashscreen\SplashScreen.mxml:233]
at flash.events::EventDispatcher/dispatchEventFunction()
at flash.events::EventDispatcher/dispatchEvent()
```

![image](https://user-images.githubusercontent.com/24554795/32548811-4bc06cc0-c487-11e7-9425-8c466803d443.png)

It is not happened on build version of application. Let me know if I need to reopen that bug.

**Comment by rat-moonshine** [comment]
Please, reopen. I'm working on the fix.

**Comment by JoelProminic** [comment]
I never had a good way to reproduce the problem that Piotr reported - his test procedure did not trigger the bug for me.

However, I have not seen any problems with the RECENT section during my 1.6.1 release candidate tests, so this looks fine.
