### ISSUE TITLE
Not able to COMPILE Flex mobile project

### ISSUE THREAD

**Issue by mprabhu33** [prominic/Moonshine-IDE#600]
MoonShineIDE version: 2.4.0, Build 1387
Apache Flex SDK: 4.13.0
Adobe AIR SDK: 32.0.0.116

When compile flex mobile project using Moonshine IDE(Project -> Build & Run)
Getting below error in the console
Compiling ServiceManagement
: Error #3214
: ArgumentError: Error #3214
: 	at Error$/throwError()
: 	at flash.desktop::NativeProcessStartupInfo/set executable()
: 	at actionScripts.plugins.swflauncher.launchers::NativeExtensionExpander/startUnzipProcess()
: 	at actionScripts.plugins.swflauncher.launchers::NativeExtensionExpander()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/compile()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/compileRegularFlexApplication()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/proceedWithBuild()
: 	at MethodInfo-13588()
: 	at actionScripts.utils::UtilsCore$/closeAllRelativeEditors()
: 	at MethodInfo-16069()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/buildStart()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/build()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/buildAndRun()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.ui.menu::MenuModel/dispatchMenuEvent()
: 	at actionScripts.ui.menu::MenuModel/menuItemRenderClickHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at mx.managers::SystemManager/mouseEventHandler()
:
: Click here to Report a Bug

Kindly let me know, how to resolve the above issue?

**Comment by piotrzarzycki21** [comment]
@mprabhu33 Did you compile hello world project or this is your's one ?

**Comment by piotrzarzycki21** [comment]
Sorry I see you were compiling your project. Do you use some ANE ?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Do you see anything suspicious in this stacktrace ?

**Comment by rat-moonshine** [comment]
This looks like error thrown while setting `executable` to NativeProcess while processing project's Native Extension(s).

@mprabhu33 , we need more information at your side to address the problem. 

1. Go to `File -> Settings -> Default SDK`, and check if you have any Java path set (something like this):
![image](https://user-images.githubusercontent.com/24370870/61206708-dff1ec80-a710-11e9-9a19-76e04ea8d7b8.png)
2. If yes, please validate if the path is valid per your system
3. The Native Extension process uses Java in your machine. Moonshine also tries to validate a path like this in your system - `c:\Users\{userName}\Program Files\Java\jre{versionNumber}\bin\javaw.exe` (x64), or, `c:\Users\{userName}\Program Files (x86)\Java\jre{versionNumber}\bin\javaw.exe` (x32) - can you confirm if the likewise folder/Java-installation is available in your system?

Additionally, you can run the following command in a (Windows) command-prompt and let us know their output:
1. `echo %JAVA_HOME%`
2. `where javaw`

**Comment by mprabhu33** [comment]
Able to compile our project now.
Thanks to @piotrzarzycki21 and @rat-moonshine .

We are using ANE in our project. 

Set the JDK path under File -> Settings -> Default SDK. 
![JDKPath](https://user-images.githubusercontent.com/29938922/61270445-53523780-a7bf-11e9-90b5-7ab798eb4658.PNG)

**Comment by rat-moonshine** [comment]
Glad that worked for you @mprabhu33 . Let me know if you have any further trouble. Thanks!
