### ISSUE TITLE
[Haxe] Code-completion issue on Windows

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#603]
@joshtynjala , I'm adding a screen-recording to explain the problem I encountered on Windows. Also, after a variable declaration `var abcd:` hitting Ctrl+Space do not opens the code-completion list until something typed.

![GIF1](https://user-images.githubusercontent.com/24370870/61689940-cfabc400-ad45-11e9-9374-e27adf2bc4d2.gif)

**Comment by JoelProminic** [comment]
I see some language features enabled for Haxe on macOS, but I get an empty list when trying to  complete a local variable name:

![image](https://user-images.githubusercontent.com/24532731/68512027-d438b180-023c-11ea-852e-a99a9fc3a80c.png)

**Comment by JoelProminic** [comment]
I tried on Windows as well, and it seems to be searching the wrong list of symbols:
![image](https://user-images.githubusercontent.com/24532731/68514683-06014680-0244-11ea-8103-72fcbfeaf0f3.png)

![image](https://user-images.githubusercontent.com/24532731/68514699-16192600-0244-11ea-8406-83ad6f6a40fe.png)

**Comment by joshtynjala** [comment]
I'll check out this one after the 2.5.0 release when I merge in my latest Haxe changes.
