### ISSUE TITLE
Missing a menu item that can actually open a project

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#608]
When I search the menus for a way to open a project that I created in Moonshine, I cannot find anything that seems to work.

In the *File* menu, if I click *Open/Import Project*, and I choose a folder that contains an *.as3proj* file, nothing happens. No project opens in Moonshine. There is no error message displayed. It's the same when I choose *Open/Import Project* from the *Project* menu. This seems strange. It should give me some kind of feedback.

I found that I can open a project by dragging the *.as3proj* file from Windows Explorer into the Project view. However, there really should be something in the menus that works too.

**Comment by rat-moonshine** [comment]
> In the File menu, if I click Open/Import Project, and I choose a folder that contains an .as3proj file, nothing happens.

If the folder contains a known project file (i.e. .as3proj, .javaproj etc.) then this suppose to work; This is how it's designed from beginning. If Moonshine see there is no project file exists to the location you selected - then Moonshine suppose to alert you if you want to create a new project to that directory with containing (possible)source-files. 

If the above is not working for you, then I suspect something else is messed up in your environment. I'd suggest to try once by removing your application cookies-folder and try afresh. 

> I found that I can open a project by dragging the .as3proj file from Windows Explorer into the Project view. However, there really should be something in the menus that works too.

You can also double-click any known project-file in OS explorer to open the project directly to the Moonshine.

**Comment by joshtynjala** [comment]
Going into settings and clicking the "Reset All Settings (Hard)" button seems to have fixed this issue for me. I can now choose a folder, and it will open the project.
