### ISSUE TITLE
Remember more items in File menu -> Recent Projects

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#609]
I have several projects that I frequently open in Moonshine. Sometimes, they disappear from the recent projects list, and I need to track down the *.as3proj* file (or *.javaproj*, etc.) on my hard drive.

I suspect that it's limited to 6 because we don't want too many appearing on the Home screen. That makes sense. However, in the Recent Projects menu, it would be nice to have a longer history available.

**Comment by rat-moonshine** [comment]
I don't see we have any limitation to show up-to 6 projects/files to the recent list in Home menu. I suspect if this limit you to show only 6, then there possibly some other problem. The recent list in Home is suppose to show scroll if there are many items. 

The same applied for the `File -> Recent` items, too. There not suppose to be any item cap.

![image](https://user-images.githubusercontent.com/24370870/63163854-42a61300-c044-11e9-9454-bdb6a64d4f62.png)
![image](https://user-images.githubusercontent.com/24370870/63163860-45a10380-c044-11e9-801b-90290c4d3c63.png)

Can you try deleting your application cookies once and try again (?) if something messed up to your settings.

**Comment by joshtynjala** [comment]
This seems to have started working properly after I deleted my Moonshine settings a while back. So I guess they got corrupted somehow. Closing.
