### ISSUE TITLE
Ability to navigate through opened editors by key-combination-press

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#612]
While working on more and more on Moonshine these days, I found a keen need of having a functionality to change the tab by key-combination, other than setting my hand on mouse and move to the tab to active again. 

I would like to have standard key-combination to change between last-active tab and moving through all the opened tabs. I like how this handles in Visual Studio Code. 

While pressing `Ctrl/Cmd+Tab` will open a similar small file-list-menu consisting of all the opened editor references:

![image](https://user-images.githubusercontent.com/24370870/63160128-a7f50680-c03a-11e9-808a-4c6c50a302d5.png)

..pressing `Tab` key everytime will navigate the selection through the file-list-menu. This is easier to choose through all the opened tabs.

**Comment by rat-moonshine** [comment]
- [x] Ctrl+Tab to jump backward/forward between two last selected tabs
- [x] Ctrl+Shift+Tab opens opened editors list, navigates through key-combination or Ctrl+Tab

**Comment by rat-moonshine** [comment]
Now merged into 'master'.

**Comment by JoelProminic** [comment]
This seems to be working well on macOS

**Comment by JoelProminic** [comment]
@Aszusz reported that this is working on Windows as well. I'm closing the issue.
