### ISSUE TITLE
Git: Prompt for authentication when cloning a private repository

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#617]
The problem discovered during #614 , where no-authentcation handling in macOS run. On Windows the authentication prompt is automatic and managed by the Git-native process. We need ensure authentication prompt properly prompts to the user in case of cloning a private repository in both Windows and OSX.

We also noticed that the user-name provides in the 'Add/Edit Repository' window mainly using during SVN checkout. We need to re-visit the complete authentication saving/managing area.

**Comment by rat-moonshine** [comment]
Things to note, in case of cloning repository with `ssh` protocol, this involve more than cloning from `http/s` with credentials.

When cloning from http/s the command looks like this:
`git clone https://{user}:{pass}@{host}/{repo}`

When cloning from `ssh` protocol, it involves `sshpass` executable:
`sshpass -p {pass} git clone ssh://{user}@{host}:{port}/{repo}`

**Comment by rat-moonshine** [comment]
So I did some changes to the clone/checkout window with the addition of username-input, this will work as a reminder of authentication the URL may be needed, along with a chance to update/add the user-name:

![image](https://user-images.githubusercontent.com/24370870/96570878-83548880-12e8-11eb-99a0-c06a92625b85.png)

To test the updates, firstly I removed my previously-stored Git authentication for the username "rat-moonshine":

![image](https://user-images.githubusercontent.com/24370870/96570437-00cbc900-12e8-11eb-81d4-70e0e64716c5.png)

Following is my test-matrix during the tests against a _private_ Git repository:

Type of authentication | Results
-------------------------- | ------------------------
No authentication data | Console shows `fatal: repository not found` error
Entering non-member user-name | Console shows<br/>`fatal: repository 'https://santanu4ver@github.com/prominic/Sxxxxs/' not found`<br/>`Insufficient authentication to the repository.`
Entering member user-name | Moonshine prompts with an authentication prompt

While the authentication prompt, Moonshine suggests using Personal Access Token instead of password:

![image](https://user-images.githubusercontent.com/24370870/96572491-805a9780-12ea-11eb-853e-e90f73fb954e.png)

Please, check.

**Comment by JoelProminic** [comment]
Instead of this message:

> Use Personal Access token instead of Password in case you have dual-authentication enabled.

Show this message:

> Use a Personal Authentication Token instead of a password if you have two-factor authentication enabled on GitHub.

It would also be nice to link "Personal Access Token" to https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token , but this is not required if it would need special logic.

**Comment by JoelProminic** [comment]
Unfortunately, this issue has a lot of test cases to cover.  Here are the cases I can think of for authentication.   As you test this, let me know the error messages that are displayed.  If we are missing error messages for some cases, then I can help write them.  Let me know if I have the wrong git/GitHub logic for some of these cases.


Repository | Requires Auth | Password Prompt | Expected Result
-----------|---------------|-----------------|-------
Invalid | false | None | Report that repository does not exist
Invalid | true | Invalid | Report authentication failed
Invalid | true | Valid | Report that the repository does not exist
Public | false | None | Run action
Public | true | None | Run action.  GitHub won't require authentication even for an invalid username
Private | false | None? | Report insufficient access rights?  I'm not sure of the behavior for Git here
Private | true | Valid password without two-factor authentication | Run action
Private | true | Valid token with two-factor authentication | Run action
Private | true | Password with two-factor authentication | Authentication error? Verify this case
Private | true | Invalid | Report authentication error
Private | true | Valid, but no access for this project | Insufficient permissions
Private | true | Saved by system | No password prompt, perform action
Private | true | Saved by Moonshine | No password prompt, perform action
Private | true | Valid password with special characters that need to be escaped ('@', '%', ' ') | Perform action


We also need to check the logic for other Git actions that may require authentication.  We don't necessarily need to cover all cases for all actions:
- Clone
- Pull
- Push
- Are there others I am forgetting?

**Comment by rat-moonshine** [comment]
I did some cloning tests and updated the previously created [test-matrix](https://github.com/prominic/Moonshine-IDE/issues/617#issuecomment-713003333), after the recent updates.

**Comment by JoelProminic** [comment]
Here is a private repository that users (besides me) can use to test the case with valid authentication but no rights to the repository:
https://github.com/JoelProminic/Test-Private-Repository

**Comment by rat-moonshine** [comment]
- Non-permitted private repository test and password with special characters tested and updated to the [matrix](https://github.com/prominic/Moonshine-IDE/issues/617#issuecomment-713003333) 
- Opening of authentication window with user-name during clone and pull command

**Comment by JoelProminic** [comment]
If this is ready for testing, please provide @Aszusz  and me with a build to test.    This should only require testing on macOS.

**Comment by rat-moonshine** [comment]
Here are the latest branch builds at Bamboo:
macOS: https://bamboo.prominic.net/browse/MS-MGOBB-308/artifact
Windows: https://bamboo.prominic.net/browse/MS-MGWBB-161/artifact

@Aszusz let me know if you have trouble accessing Bamboo, I shall upload the builds somewhere else.

**Comment by Aszusz** [comment]
I can access bamboo without problems.

**Comment by Aszusz** [comment]
One very minor issue I noticed during the tests is when I am prompted for password and I close the window the cloning spinner is still spinning:

![image](https://user-images.githubusercontent.com/7197014/102639269-154a0780-4159-11eb-8327-638dd1939e74.png)

**Comment by JoelProminic** [comment]
I did a quick test to confirm that the password prompt logic would trigger for all actions that require authentication, if needed:

Actions requiring authentication | Password Prompt
---------------------------------|----------------
Clone | Confirmed
Pull | Confirmed
Push | Confirmed
Validate/Create Branch and Push | BUG:  hangs on validation with no prompt
List Remote Branches | BUG: fails to load either local or remote branches, no prompt


I focused my testing on the Clone operation, since this will generally be the first and only time the user needs to enter a password for a repository (if they save it to the keychain).

Repository | Requires Auth | Password Prompt | Expected Result | Actual Results
-----------|---------------|-----------------|------- | ---------
Invalid | false | None | Report that repository does not exist | Confirmed error
Invalid | true | Invalid | Report authentication failed | Confirmed, "Invalid username or password"
Invalid | true | Valid | Report that the repository does not exist, insufficient permission | Confirmed error
Public | false | None | Run action | Confirmed
Public | true | None | Run action.  GitHub won't require authentication even for an invalid username | Confirmed
Private | false | Prompt for password | See cases below | Confirmed
Private | true | Canceled | Cancel action | BUG:  hangs on status window, which can be closed
Private | true | Valid password without two-factor authentication | Run action | TODO - Need to test this on a different account
Private | true | Valid token with two-factor authentication | Run action | Confirmed
Private | true | Password with two-factor authentication | Authentication error. | Confirmed:  "Invalid username or password"
Private | true | Invalid | Report authentication error | Confirmed:  "Invalid username or password"
Private | true | Valid, but no access for this project | Repository not found | Confirmed
Private | true | Saved by system | No password prompt, perform action | Confirmed
Private | true | Saved by Moonshine | No password prompt, perform action | Confirmed
Private | true | Valid password with special characters that need to be escaped ('@', '%', ' ') | Perform action | TODO:  need account to test this

**Comment by rat-moonshine** [comment]
> One very minor issue I noticed during the tests is when I am prompted for password and I close the window the cloning spinner is still spinning:
> 
> ![image](https://user-images.githubusercontent.com/7197014/102639269-154a0780-4159-11eb-8327-638dd1939e74.png)

Can you create me a separate issue so I don't missout on the bug in this trail of comments (?)

**Comment by rat-moonshine** [comment]
As a note from GitHub, I received this email on the usage of the password during authentication to access a private repository, which is going to be deprecated; So, personal access token possibly will be the only way to authenticate in the future:

> You recently used a password to access the repository at `$myUserName/testPrivateRepo` with git using git/2.24.3 (Apple Git-128).
> 
> Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

**Comment by rat-moonshine** [comment]
Actions requiring authentication | Password Prompt
---------------------------------|----------------
Validate/Create Branch and Push | BUG:  hangs on validation with no prompt
List Remote Branches | BUG: fails to load either local or remote branches, no prompt

The above two bugs from @JoelProminic [test-matrix](https://github.com/prominic/Moonshine-IDE/issues/617#issuecomment-748375473) are now rectified and both the sections now included with authentication checks. Please, check.

**Comment by rat-moonshine** [comment]
(Following fixes are part of branch #617 only)

As reported by @Aszusz on the [checkout/clone window](https://github.com/prominic/Moonshine-IDE/issues/617#issuecomment-748199928), a few other areas also updated which shown busy/working even when the git-authentication window canceled:

- Repository checkout/clone
- New Branch popup window
- Switch/Change to a branch window

**Comment by JoelProminic** [comment]
I did some tests with the authentication prompt for different interfaces:

Actions requiring authentication | Password Prompt | Cancel | Failed Auth | Valid Auth
---------------------------------|-----------------|--------|-------------|-----------
Clone | Confirmed | Return to clone prompt | Report error, allows later attempts | Works
Pull | Confirmed | Works | BUG: prompt does not reopen on later attempts | Works
Push | Confirmed | Works | BUG: Username error | BUG: Username error
Validate/Create Branch and Push | Confirmed | Works | BUG: prompt does not reopen on later attempts | Works
List Remote Branches | Confirmed | Works | BUG: prompt does not reopen on later attempts | Works


For the Push errors, I got an error like this on the console.  It seems that it is trying to read the username from somewhere besides the prompt:

    : Pushing to -repository-
    : fatal: could not read Username for 'https://github.com':  Device not configured
    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugins.git.commands::PushCommand/onAuthenticationSuccess()
    : 	at actionScripts.plugins.git.commands::GitCommandBase/onAuthSubmitted()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at components.popup::GitAuthenticationPopup/onSubmit()
    : 	at components.popup::GitAuthenticationPopup/__btnCommit_click()
    :
    : Click here to Report a Bug

For the "prompt does not reopen" cases, I see authentication errors on the console when I try the action again, but the prompt does not reappear, so I don't have a chance to fix the password until I restart Moonshine.

**Comment by rat-moonshine** [comment]
The [above](https://github.com/prominic/Moonshine-IDE/issues/617#issuecomment-749672323) problems should have fixed now. Please, check.

**Comment by rat-moonshine** [comment]
So, as I see it if we run the following command once after cloning a private repository, with authentication:

`git remote set-url origin https://privateUser@github.com/santanu4ver/testPrivateRepo`

the `.git/config` file never updates its "url" value anymore, even if you entered authentication again from Moonshine. I see this is a cost-effective option for us.

In the above command, 'privateUser' could be any static word, but we require to add the user-name format to the URL unless Git will not find any private repository. So based on the above finding, I see the following behaviors:

1. User clone a private repository with authentication in Moonshine
2. `.git/config` file updated with auth information 
3. I ran `git remote set-url origin https://privateUser@github.com/santanu4ver/testPrivateRepo`
4. `.git/config` file updated with the given url 
5. I removed the stored Github password from my macOS keychain
6. In Moonshine, I prompted by the authentication window when tried to do a _push_ command to the project
7. Upon providing correct authentication _push_ completes
8. Checking in the `.git/config` file, the "url" value still unmodified 

Here, practically setting the `.git/config`"url" with `git remote set-url` is a one-time procedure therefore the config "url" never updates itself.

**Comment by rat-moonshine** [comment]
Okay. Here's some good news in this regard, I think we can use ExpectScript to dynamically enter the password when prompted. 

In my local tests, I able to pass authentication by entering a password when prompted, without opening any Terminal window but running Expect directly; And I also noticed this doesn't store the password in .git/config file either.

**Comment by rat-moonshine** [comment]
I have added the first version of authentication with the expect script. Other sections will follow.

**Comment by rat-moonshine** [comment]
I have implemented exp git-authentication across the sections where it's needed. So far, in my local tests, the sections worked well. Following are the sections where exp git-auth enabled:

- Clone
- Pull
- Push
- New Branch Creation
- Branch Listing (switch/change branch)

Please, check.

**Comment by rat-moonshine** [comment]
Known issue - Console history shows password during exp calls - fixed. Instead, the console will advise only on checking for authentication.

**Comment by JoelProminic** [comment]
The expect script is here:  https://github.com/prominic/Moonshine-IDE/blob/4a0d71be2112fee32e650737ee751d76837af3e9/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/utils/GitUtils.as#L10

We could try sending the password by STDIN by changing the [set password line](https://github.com/prominic/Moonshine-IDE/blob/4a0d71be2112fee32e650737ee751d76837af3e9/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/utils/GitUtils.as#L12) to a command from [this article](https://stackoverflow.com/questions/40034674/reading-a-variable-from-the-user-in-an-expect-script/40035403).  For example:

```
gets stdin password
```

Then, send the password to STDIN using the API calls [here](https://help.adobe.com/en_US/air/html/dev/WSb2ba3b1aad8a27b060d22f991220f00ad8a-8000.html#WS789ea67d3e73a8b2-368e74cb123de962251-7fff)

**Comment by rat-moonshine** [comment]
`stdin` seems to be working good. However, I required to adjust the script to properly receive and use the input - https://github.com/prominic/Moonshine-IDE/blob/bugfix/issue_617_git_auth_mac/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/utils/GitUtils.as#L13, it seems `puts -nonewline "message: "` does the job in exp. I confirm I able to receive the waiting prompt where I can use stdInput.writeUTF in the NativeProcess.

I also required to adjust the worker class (where the processes execute) to send to stdInput from Moonshine. 

All the git commands now updated with the requisite codes. They seem to be working in an expected manner. However, I couldn't able to test the ps front.

**Comment by rat-moonshine** [comment]
Updates:

- Process as if not ending during cloning a repository - fixed
- The same problem fixed for other git-commands which involved an authentication scenario
- Fixed areas when running auth-oriented exp script throws unexpected values in the console for non-private repositories

**Comment by JoelProminic** [comment]
This sounds good, but I'd like to see a test matrix for the different actions.   If we don't see any more problems, we can merge this to master.

**Comment by Aszusz** [comment]
@rat-moonshine 
I have some general problems with the test matrix. Am I using the correct build?
https://bamboo.prominic.net/browse/MS-MGOBB-328/artifact

**Comment by rat-moonshine** [comment]
Yes, this was the targeted build for this issue. Let me know what problems you're facing.

**Comment by Aszusz** [comment]
It seems I had some internal issues. After some tweaking and A LOT of testing I conclude almost everything works as expected. The only case failing for me is clone with password containing special character. Here's summary of my tests:

#### Test 1
**Scenario:** Clone invalid repsoitory with no-auth
**Result:** Moonshine fails with `: fatal: could not read Username for 'https://github.com': Device not configured` and prompts for password/token. When correct credentials are given Moonshine fails with `: remote: Repository not found.
: fatal: repository 'https://github.com/aszusz/invalid/' not found`.
**Comment:** This is correct. Git bash behaves in similar fashion. Credentials are not stored in the Keychain which is also correct.

#### Test 2
**Scenario:** Clone invalid repository with-auth
**Result:** Same as Test 1

#### Test 3
**Scenario:** Clone public repository with no-auth
**Result:** Clone successful

#### Test 4
**Scenario:** Clone public repository with-auth
**Result:** Same as Test 3

#### Test 5
**Scenario:** Clone private repository with no-auth
**Result:** Shows moonshine's prompt for password/token, succeeds with correct credentials.

#### Test 6
**Scenario:** Clone private repository with-auth
**Result:** Same as Test 5

#### Test 7
**Scenario:** Clone private repository with wrong credentials
**Result:** Fails with `: remote: Invalid username or password.
		: fatal: Authentication failed for 'https://github.com/aszusz/some/'`

#### Test 8
**Scenario:** Clone private repository with no access
**Result:** The same as Test 1
**Comment:** This is very good. User should not be abel to distingusih between invalid repository and a repository he/she has no access into.

#### Test 9
**Scenario:** Clone private repository with credentials stored in the Keychain
**Result:** Clone successful, no password prompt.
**Comment:** To achieve this scenario I restarted Moonshine session.

#### Test 10
**Scenario:** Clone private repository with credentials stored in Moonshine
**Result:** Clone successful, no password prompt.
**Comment:** To achieve this scenario I deleted credentials from the Keychain while keeping open Moonshine IDE. After the clone credentials propagated back to the Keychain.

#### Test 11
**Scenario:** Clone private repository and cancel the password prompt
**Result:** Clone action spinner is closed correctly.

#### Test 12
**Scenario:** Clone private repository with 2FA disabled (password instead of token).
**Result:** Same as Test 5

#### Test 13 !!!FAILING!!!
**Scenario:** Clone private repository with 2FA disabled and password containing secial symbols
**Result:** Moonshine rejected credentials as invalid.
**Comment:** In my password I used '@','%' and '*'.

In any of the test I didn't see password displayed on the console or in config file.

**Comment by Aszusz** [comment]
Here's another portion of tests. These tests fail for me today although I'm almost sure those cases were working for me yesterday:

All test below executed against a private repository with 2FA enabled:

#### Test 14
**Preconditions:** PAT cached in Keychain
**Scenario:** Try to create branch that already exists remotely
**Result:** Prompt freezes on "Validating..."
**Error on the console:**
```
: Sending to command: expect -f "/Users/adrian/Library/Application Support/com.moonshine-ide/Local Store/spawn/connectgit.exp"
```

#### Test 15
**Preconditions:** No credentials cached
**Scenario:** Try to create branch that already exists remotely
**Result:** Moonshine prompts for password. Then freezes on branch "Validating..." like in Test 14

#### Test 16
**Preconditions:** PAT cached in Keychain
**Scenario:** Try to switch to remote branch
**Result:** Remote branch not present on the list
***Error on the console:***
```
: Fetching branch details...
: Sending to command: expect -f "/Users/adrian/Library/Application Support/com.moonshine-ide/Local Store/spawn/connectgit.exp"
: Checking for any authentication..
: spawn /Library/Developer/CommandLineTools/usr/bin/git fetch https://aszusz@github.com/Aszusz/Private_AS_Repo
: From https://github.com/Aszusz/Private_AS_Repo
:  * branch            HEAD       -> FETCH_HEAD
: spawn_id: spawn id exp5 not open
:     while executing
: "interact"
:     (file "/Users/adrian/Library/Application Support/com.moonshine-ide/Local Store/spawn/connectgit.exp" line 22)
```

**Comment by rat-moonshine** [comment]
> Test 14
> Preconditions: No credentials cached
> Scenario:
> 
> Go to Git -> New Branch
> When prompted for credentials give username and valid PAT
> Try to create a branch that already exists on remote
> Result: Prompt freezes on "Validating..."
> Error on the console:

This now fixed.

**Comment by rat-moonshine** [comment]
> Test 16
> Preconditions: No credentials cached
> Scenario:
> 
> Go to Git -> Switch Branch
> When prompted for credentials give username and valid PAT
> Result: Remote branch not present on the list (unless it was cached previously by Git)
> Error on the console:

This now fixed.

**Comment by rat-moonshine** [comment]
@Aszusz you can download and test from Bamboo using following two links:
macOS: https://bamboo.prominic.net/browse/MS-MGOBB-354
Windows: https://bamboo.prominic.net/browse/MS-MGWBB-210

Please, let me know what else we left before closing this issue.

**Comment by rat-moonshine** [comment]
> Test 13 !!!FAILING!!!
> 
> Scenario: Clone private repository with 2FA disabled and password containing secial symbols
> Result: Moonshine rejected credentials as invalid.
> Comment: In my password I used '@','%' and '*'.

I see we still have this left. Unfortunately, I don't have an account with special char in password at this moment. Can you able to arrange a test account for us on this? Also, is 2FA enable/disable is a factor to test this problem?

**Comment by Aszusz** [comment]
> Also, is 2FA enable/disable is a factor to test this problem?

Unfortunately, yes. As far as I know, you need to disable 2FA for git integration to accept the password. Otherwise it expects the PAT and the password doesn't matter.

> Can you able to arrange a test account for us on this?

I'll try. I'll mail you the details. If it doesn't work, maybe forcing our users to always use 2FA is not a bad idea either.

**Comment by rat-moonshine** [comment]
> Otherwise it expects the PAT and the password doesn't matter.

That make sense. On 2FA, I think Git has a plan to make this mandatory in coming days, however, I see that didn't happened yet.

**Comment by Aszusz** [comment]
I tested the macOS build and I confirm Test 14 and Test 16 are fixed.

**Comment by Aszusz** [comment]
**Test 17 !!FAILING!!**

**Preconditions:** No credentials cached
**Scenario:**
1. Go to `Git->Push`
2. When prompted for credentials give valid username and PAT

**Result:** Changes are not pushed to the remote
On the console there is no confirmation that push succeeded:
```
: Git push requested...
: Sending to command: expect -f "/Users/adrian/Library/Application Support/com.moonshine-ide/Local Store/spawn/connectgit.exp"
: Checking for any authentication..
```

**Comment by rat-moonshine** [comment]
> **Test 17 !!FAILING!!**
> 
> **Preconditions:** No credentials cached
> **Scenario:**
> 
> 1. Go to `Git->Push`
> 2. When prompted for credentials give valid username and PAT
> 
> **Result:** Changes are not pushed to the remote
> On the console there is no confirmation that push succeeded:
> 
> ```
> : Git push requested...
> : Sending to command: expect -f "/Users/adrian/Library/Application Support/com.moonshine-ide/Local Store/spawn/connectgit.exp"
> : Checking for any authentication..
> ```

This now fixed. Please test on later builds than [this](https://github.com/prominic/Moonshine-IDE/issues/617#issuecomment-785791441).

**Comment by Aszusz** [comment]
I confirm Test 17 is fixed. I also tested pulling in the same way and it seems to work without problems. Apart from special characters in the password I think we covered everything. Give it your best shot with the password, but if it's too troublesome, it's ready to merge.

**Comment by rat-moonshine** [comment]
> Test 13 !!!FAILING!!!
> 
> Scenario: Clone private repository with 2FA disabled and password containing secial symbols
> Result: Moonshine rejected credentials as invalid.
> Comment: In my password I used '@','%' and '*'.

This should be fixed in the newer branch builds. 

However, I'm seeing another problem while testing cloning a private repository on Windows 10 lately. @Aszusz please give a test to see if you can also reproduce the same problem in your tests.

Simple command-line execution-test would be adequate for this:

1. Start command-line
2. Enter git clone https://gittutorial-user1@github.com/gittutorial-user1/Private-Git-AS3-Repo
3. Windows' native git-authentication prompt should open after this:
![image](https://user-images.githubusercontent.com/24370870/109611450-416c0680-7b54-11eb-93f7-9f3db5a07e31.png)
4. Having valid auth-information entered, try to login
5. Command-line shows "Logon failed", in-addition with another prompt for entering the password:
![image](https://user-images.githubusercontent.com/24370870/109611555-6c565a80-7b54-11eb-9cc3-dd40e394b13e.png)
6. Enter the same password again and hit Enter
7. This time it accepts the password and starts a clone

While running this procedure through Moonshine, once 4 returns an invalid response by the native git-auth window, Moonshine terminates its process as if password is wrong. 

I'm trying to override this behavior and will try to see if a shell-input is open during this time where we can enter the password using own process.

**Comment by rat-moonshine** [comment]
> I'm trying to override this behavior and will try to see if a shell-input is open during this time where we can enter the password using own process.

Bad thing is, it's not opening any input stream to enter a password :/

**Comment by Aszusz** [comment]
> However, I'm seeing another problem while testing cloning a private repository on Windows 10 lately. @Aszusz please give a test to see if you can also reproduce the same problem in your tests.

I cannot reproduce this issue. Also, my prompt looks different than yours:
<img width="331" alt="Screenshot_1" src="https://user-images.githubusercontent.com/7197014/109655822-0245b180-7b64-11eb-932e-07a9fbe54b5d.png">
And it works for me with **password** although it says it wants PAT.
```
$ git --version
git version 2.30.0.windows.2
```

**Comment by rat-moonshine** [comment]
It seems I'm in lower version - 2.20.1.windows.1. However, I think this is the version that downloads through MSDKI!

**Comment by rat-moonshine** [comment]
So it appears it needs a version update, of Git. I have created an issue to track this - https://github.com/prominic/Moonshine-SDK-Installer/issues/37.

As we mostly able to cover all the issues here, I guess, I'll plan for a merge. @Aszusz please raise any issue if you see any immediate problem with the recent branch updates.

**Comment by Aszusz** [comment]
I run Test 13 against build 359 and it is fixed. I see no other issues.

**Comment by rat-moonshine** [comment]
Sounds good! This issue is now merged into 'master'.
