### ISSUE TITLE
Re-structuring of Git process

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#619]
In the initial age of Git functionality integration we had a plugin-class (`GitHubPlugin`) along with a command management class (for the _plugin_) which communicates with Worker/NativeProcess to run functional commands and listens/acts/notify upon them, [GitProcessManager](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/GitProcessManager.as).

I admit in the initial days I oversight that it could turn into a mammoth class consisting of all the Git-functionalities' command executions and handling of returns. The only purpose of having all things centrally located during that time. Over the period, as more and more features keep added and some features even turn more critical in command-execution aspect, the class added with many function/handlers etc.; And at a time, the class became too dense, hard to find any particular thing, and difficult to co-relate any function connected to/from how many places. A need of more modular approach came in a need therefore.

This issue targets for an approach which breaks the functionalities to individual classes but easy to found, co-relate which methods are related to which Git functionality, with an underlying similarity/connectivity.

**Comment by rat-moonshine** [comment]
So far I have completed the re-structure of the existing `GitProcessManager` class; This also affect the existing `GitHubPlugin` class to an extent if not all.

Now the Git-functionalities are structured in a more modular approach, extending a base class for every of them. All the functional areas in Git now broken into smaller [Command](https://github.com/prominic/Moonshine-IDE/tree/features/issue_619_git_restructure/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/commands) classes, which all extends [GitCommandBase](https://github.com/prominic/Moonshine-IDE/blob/features/issue_619_git_restructure/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/commands/GitCommandBase.as) holding the very basic necessary elements those may require for all the _Command_ classes.

A typical _Command_ class is [GitCheckoutCommand](https://github.com/prominic/Moonshine-IDE/blob/features/issue_619_git_restructure/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/commands/GitCheckoutCommand.as), which executes the requisite shell-command, override necessary methods that the _Command_ may needs, i.e. `shellTick`, `listOfProcessEnded` in this case. These override can varies based on the _Command_ class' needs, i.e. [CloneCommand](https://github.com/prominic/Moonshine-IDE/blob/features/issue_619_git_restructure/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/commands/CloneCommand.as) listens `shellData`, `shellError `and `shellExit`; It is also possible that some _Command_ class need not to have any of them to override and have the base class handle them default-way.

Inside the `GitHubPlugin` call of these _Command_ classes also now very easy, just to initialize a new instance every time when it's needed, i.e. [onPullRequest()](https://github.com/prominic/Moonshine-IDE/blob/features/issue_619_git_restructure/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/GitHubPlugin.as#L473). The _Command_ class therefore executes command, call any further _Commands_ if its needed within, and [dispose](https://github.com/prominic/Moonshine-IDE/blob/features/issue_619_git_restructure/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/commands/GitCommandBase.as#L62) when the _Command_ class' process is done, and ideally ready for next system gc.

I spent sometime testing all the functionalities on Windows (so far), and I didn't noticed any problem so far (macOS testing pending). However, I noticed the problem of Git-path-with-space problem still prevailing which we noticed some time back as #641 on Windows. Although the said issue now addressed, but the same problem seems to showing up different areas like commit-request to server, revert etc. We need to track separate issue(s) for them.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine This is still on branch ?

**Comment by rat-moonshine** [comment]
Yes. We're undergoing with tests now, Piotr.

**Comment by rat-moonshine** [comment]
This issue now merged into 'master' and ready for further tests.

**Comment by rat-moonshine** [comment]
I found a similar problem like #652 if not exact, while testing merge state on Windows. 

On Windows, the authentication window to a repository opens by the native Git process itself. I noticed today it triggers only twice. If for some reason user input bad-auth twice or cancelled twice, the window never appear again until a new call.

In that situation when the auth-window do not appears anymore on Windows, Moonshine keeps showing the waiting window with message 'in-progress' without having any additional details like end-of-native-window-appearance or such. This scenario is handled now.

**Comment by piotrzarzycki21** [comment]
If we are good with that please close that issue.

**Comment by JoelProminic** [comment]
Testing on macOS Yosemite, Nightly non-Sandbox Build 1571, I found that Git > Switch to Branch... did not work for me:
1. Clone Moonshine-IDE.git, or use an existing copy
2. Open MoonshineDESKTOPevolved
3. Git > Switch to Branch
4. BUG:  Some progress appears in the console, but the corresponding dialog does not open.

    : From https://github.com/prominic/Moonshine-IDE
    :    aa6581a..6646014  master     -> origin/master
    :    b24d1ea..c05ecdd  features/issue_619_git_restructure -> origin/features/issue_619_git_restructure
    :  * [new branch]      features/issue_633_updateOpenedTab -> origin/features/issue_633_updateOpenedTab
    :  * [new branch]      features/issue_646_ve_to_notes -> origin/features/issue_646_ve_to_notes
    : Fetching branch details...


I also confirmed this on macOS High Sierra, App Store Build #1573, with the Store-Manager project.

If this bug is not related to this issue, we can move it to a new issue.

**Comment by rat-moonshine** [comment]
Breaking to 'Switch to Branch' as it's appeared to me could possible reason of recent changes in NativeProcess/Worker API during #648 fixes. I don't remember this break before.

I noticed that event listeners are getting removed before completing other queued executions. I tried to careful to my now-changes so we shouldn't have any drastic effect elsewhere. This seems to be working good in my debug/tests.

@piotrzarzycki21 please re-test your API report problems after these new change.

@JoelProminic 'Switch to Branch' is working now and open for tests.

**Comment by piotrzarzycki21** [comment]
> I noticed that event listeners are getting removed before completing other queued executions.

In this sentence are you describing your current change or do you point what has happened before ?

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 please re-test your API report problems after these new change.

It didn't break anything on API report, but I'm still having some concerns about those changes. How are you sure that you are cleaning up event listeners and native process is already exited ? You have to be sure and I think if you use `cleanUpShell` you should check `customProcess.running`.

**Comment by piotrzarzycki21** [comment]
It's just experimentation - if there are some unwanted artifacts let's leave it as is.

**Comment by rat-moonshine** [comment]
> > @piotrzarzycki21 please re-test your API report problems after these new change.
> 
> It didn't break anything on API report, but I'm still having some concerns about those changes. How are you sure that you are cleaning up event listeners and native process is already exited ? You have to be sure and I think if you use `cleanUpShell` you should check `customProcess.running`.

I think this injects some confident in me after reviewing the queued cycle and listener-cleaning/re-initializing for some time in debugging. Perhaps, only one addition I would like to do to ensure safety - executing `cleanup()` while `shellError()` (it's possible that shell-exit do not fire when shell-error).

**Comment by piotrzarzycki21** [comment]
Thanks for update. You can close the issue than once Joel test it.

**Comment by rat-moonshine** [comment]
I did some small cleanup, tested through Git and About section processes. @piotrzarzycki21 if you can give a test once again with API report, we shall be ensured then.

**Comment by piotrzarzycki21** [comment]
> I did some small cleanup, tested through Git and About section processes. @piotrzarzycki21 if you can give a test once again with API report, we shall be ensured then.

With you clean up you just get back to the previous state ! I have made that cleanUp method to clean event listeners not stop native process.

**Comment by piotrzarzycki21** [comment]
Please revert your changes to previous state - they were working. I don't want to spend another half hour on testing stuff which were working previously. Do not make manual changes but use revert in git.

**Comment by rat-moonshine** [comment]
Hm. Yours sound a weird states of process. Anyway, I have reverted to the earlier changes. I don't see git Revert command listing the file that I wants to revert, the class file restored to earlier state anyway. Give a test.

**Comment by piotrzarzycki21** [comment]
> Hm. Yours sound a weird states of process. Anyway, I have reverted to the earlier changes. I don't see git Revert command listing the file that I wants to revert, the class file restored to earlier state anyway. Give a test.
I'm sorry I could not be enough precise - You should use following Git command to [revert](https://git-scm.com/docs/git-revert) changes. - Next time please do this accordingly - If you wanted to have UI help you can use for example SourceTree. @Aszusz Can for sure elaborate more how to make proper revert of last two commits. :) Another drawback with your manual revert is that - I need to review again code - which again ends up with additional time.

**Comment by piotrzarzycki21** [comment]
> Hm. Yours sound a weird states of process.

I'm not sure what do you mean here.

**Comment by rat-moonshine** [comment]
> > Hm. Yours sound a weird states of process.
> 
> I'm not sure what do you mean here.

Let's leave it and give a test with your feature instead we spending more on this ;)

**Comment by piotrzarzycki21** [comment]
Closing as it was tested.
