### ISSUE TITLE
Testing for release 2.4.1

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#620]
We need to test following items before start release process:
- ~~Getting Started: Added Apache Royale Nightly build. (@piotrzarzycki21 )~~ It's not implemented yet -> https://github.com/prominic/Moonshine-SDK-Installer/issues/12
- [x] Added USB device debugging on mobile for Adobe AIR. (@rat-moonshine )
- [x] Added Go To Implementation for interfaces. (@piotrzarzycki21 )
- [ ] Added Ctrl+Click on Flex SDK items parent classes. (@rat-moonshine )
- [x] Added Outline View with symbols in current view. (@piotrzarzycki21 )
- [x] Signature Help: Add buttons to see other overloaded signatures. (@piotrzarzycki21 )
- [ ] Added basic OpenFL/Haxe project support. (@JoelProminic )

**Comment by rat-moonshine** [comment]
Thank you, for creating the issue @piotrzarzycki21 . This will work as a reminder for me.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine can you provide me nightly version of Moonshine SDK installer 3.3.1 somehow ?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine can you please look into that this week ?

**Comment by piotrzarzycki21** [comment]
> * Added Outline View with symbols in current view.

Outlive view is working fine, but I would definitely have some UI improvements to the next releases.

**Comment by rat-moonshine** [comment]
> @rat-moonshine can you provide me nightly version of Moonshine SDK installer 3.3.1 somehow ?

Sent you download link to email.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Any chance to look into that before you go on vacation ?

**Comment by rat-moonshine** [comment]
Yes, this been pending at my end. I'm working on testing USB debugging at least by today and tomorrow.

**Comment by rat-moonshine** [comment]
On a quick update to device-debug testing - I spent sometime trying to debug example mobile project to my Android device, from my macOS. For some reason, Moonshine failed to determine any connected device. However, I confirm if I ran the related command on Terminal I can see connected device.

I suspect the conditions to determine available connected device(s) somehow outdated and I will probably need to spend some more time debugging this. This may or may-not complete quickly.

**Comment by rat-moonshine** [comment]
Joel pointed to a good point here - https://github.com/prominic/Moonshine-IDE/issues/479#issuecomment-474089329 whether we need to have an entitlement to access USB in sandbox. I will need to try by that.

**Comment by rat-moonshine** [comment]
> @rat-moonshine Any chance to look into that before you go on vacation ?

I have updated my test results to the issue.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine @JoelProminic I think we can close that ?

**Comment by rat-moonshine** [comment]
What is this - "Added Ctrl+Click on Flex SDK items parent classes" ?

**Comment by piotrzarzycki21** [comment]
> What is this - "Added Ctrl+Click on Flex SDK items parent classes" ?

When you extend some class you would like to have CTRL+Click available to see what is the source code of parent class. If you go to such class it can extends another one, so CTRL+Click should work on that as well. 

`class A extends B {}` <- I'm clicking on B (CTRL+Click)

`class B extends C {} `< I jumped here from A, so now I wanted to go farther by doing CTRL + Click on C

**Comment by rat-moonshine** [comment]
The Ctrl/CMD+Click on an object definition is something suppose to provided by the language-server. Isn't this happening now (?) If not, then perhaps we need to raise an issue requesting Josh to look into.

**Comment by piotrzarzycki21** [comment]
> The Ctrl/CMD+Click on an object definition is something suppose to provided by the language-server. Isn't this happening now (?) If not, then perhaps we need to raise an issue requesting Josh to look into.

This was your task to test ;)

**Comment by rat-moonshine** [comment]
I never worked to language-server side. If you have a clear idea how this can be implemented, please place here. If this involves more server-side support that demands more specific expertise of Josh, I'd suggest to open a separate issue and request Josh than waiting for me to heads into and try understanding the design flow.

**Comment by piotrzarzycki21** [comment]
> I never worked to language-server side. If you have a clear idea how this can be implemented, please place here. If this involves more server-side support that demands more specific expertise of Josh, I'd suggest to open a separate issue and request Josh than waiting for me to heads into and try understanding the design flow.

This issue was raised in order to track testing - Did you test feature ? Is it working ? If it doesn't work - just make a note here and mark your task as done.
