### ISSUE TITLE
ArgumentError: Error #3214

### ISSUE THREAD

**Issue by zhangfeibao** [prominic/Moonshine-IDE#623]
- [x] Review the documentation: https://github.com/prominic/Moonshine-IDE
- [ ] Search for existing issues: https://github.com/prominic/Moonshine-IDE/issues
- [ ] Use the latest stable version at: http://moonshine-ide.com
- [ ] Let us know how to reproduce the issue. Include a code sample, or share a project that reproduces the issue

### Errors
Error #3214
ArgumentError: Error #3214
	at Error$/throwError()
	at flash.desktop::NativeProcessStartupInfo/set executable()
	at actionScripts.utils::MSDKIdownloadUtil/runAppStoreHelperWindows()
	at MethodInfo-39345()
	at actionScripts.utils::Unzip/unzipTo()
	at MethodInfo-26018()
	at MethodInfo-15091()

**Comment by piotrzarzycki21** [comment]
Could you please try development version of Moonshine and let us know whether you have same issue. [Mac](https://moonshine-ide.com/downloads/releases/dev/macos/) and [Windows](https://moonshine-ide.com/downloads/releases/dev/windows/)

**Comment by piotrzarzycki21** [comment]
@zhangfeibao did you try suggested nightly build ?

**Comment by piotrzarzycki21** [comment]
Please try with latest released version or Nightly Build.
