### ISSUE TITLE
Closing editor with keyboard shortcut throws exception

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#625]
Tested on macOS with CMD+W.

Having any editor opened and using shortcut-keys to close the editor (i.e. CMD+W) does close the editor but throws an exception to console:

```
: Running on Adobe AIR 28.0.0.125
: Error #1034
: TypeError: Error #1034
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
: 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
: 	at actionScripts.ui.menu::MenuPlugin/redispatch()
: 	at flash.display::NativeMenuItem/performKeyEquivalent()
: 	at flash.display::NativeMenu/performKeyEquivalent()
: 	at flash.display::NativeMenuItem/performKeyEquivalent()
: 	at flash.display::NativeMenu/performKeyEquivalent()
: 	at flash.desktop::NativeApplication/_onKeyDownCapture()
:
: Click here to Report a Bug
```

**Comment by rat-moonshine** [comment]
Editor closing with shortcut keys (Ctrl/CMD+W) should have resolved now.

**Comment by JoelProminic** [comment]
I wasn't able to reproduce the issue on macOS or Windows.  I'm closing the issue.

**Comment by rat-moonshine** [comment]
Closing any tab with keyboard shortcuts reopens on Moonshine restart. This is not true in the case of the editor's cross-button click. Re-opening to further investigate.

**Comment by rat-moonshine** [comment]
Closing and saving seem to be fixed now. Here's a test-matrix of a different mode of closing:

Test | Expected | Actual
-------------------- | ---------------------- | -------
Closing tab by its cross-button click | Close, do not opens on Moonshine restart | Confirm
Closing tab by keyboard-shortcuts | Close, do not opens on Moonshine restart | Confirm
Closing tabs by `File -> Close All` | Close, do not opens on Moonshine restart | Confirm
Closing tab by `File -> Close` | Close, do not opens on Moonshine restart | Confirm
Closing tabs by during project close | Close, open next time the project reopens | Confirm
Closing tabs during IDE quit | Close, reopens on Moonshine restart | Confirm

**Comment by JoelProminic** [comment]
@piotrzarzycki21 asked us to check that #691 was still working with the changes to the close logic.   I found that code completion still worked after closing and reopening a tab, and when opening a hidden tab.

The close and reopen logic looks good to me in my tests.   I'm closing this issue.
