### ISSUE TITLE
First class import in MXML file has been inserted at the beginning of file

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#63]
When I'm trying to add import to some class it's being inserted at the beginning of file:

![import_wrong_position](https://user-images.githubusercontent.com/24554795/32548414-db6faf36-c485-11e7-810d-96f1f5557658.gif)

However if it is second import in that file insertion working fine:

![second_import_good_position](https://user-images.githubusercontent.com/24554795/32548431-e6566688-c485-11e7-812c-2475ba7f8150.gif)

**Comment by joshtynjala** [comment]
I can also reproduce this issue in VSCode.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I just built your latest released version 0.8.0 of extension and I can confirm that this issue is no longer reproducible.

**Comment by joshtynjala** [comment]
Closed in commit 38a63e61d4dfe67e15d5e5ee87c2c5cb4b279cc7
