### ISSUE TITLE
overriding URL

### ISSUE THREAD

**Issue by verymandeep** [prominic/Moonshine-IDE#632]
When I try to override the URL to use http instead of the local disk, override doesn't seem to work, am I misunderstanding something ?
(hopefully I'm asking this question in the right place as I never asked a question on GitHub) 
![moonshine url question]
(https://user-images.githubusercontent.com/57406671/68222413-f9b58900-ffb8-11e9-87e4-2abea4108bfb.png)

**Comment by piotrzarzycki21** [comment]
Just for the reference [discussion](http://apache-royale-users.20374.n8.nabble.com/moonshine-td2935.html) on Royale dev list.

**Comment by piotrzarzycki21** [comment]
Hi @verymandeep ,
I have fixed this issue. We will soon release version 2.4.1, but if you don't won't to wait you can try out nightly build. I'm not sure what OS you are using so here are the links [Windows](https://moonshine-ide.com/downloads/releases/dev/windows/) and [Mac](http://moonshine-ide.com/downloads/releases/dev/macos/)
