### ISSUE TITLE
Hang on New Grails Project

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#635]
I am unable to create a Grails project in the Moonshine 2.5.0 development build on macOS. 
1. Open Moonshine
1. File > New > Grails Project
1. BUG:  The interface hangs.  I do not see the New Project prompt, even after I wait a few minutes.

I got this error with both the default Grails and Gradle SDKs from ~/Downloads/MoonshineSDKs and with external SDKs that I was using for a different test.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I didn't have any kind of problems with creating Grails project on Windows and my Mac. @rat-moonshine can you give a quick test with that on your machine as well. 

I was using installed version of Grails with SDK Installer.

**Comment by rat-moonshine** [comment]
I confirm Joel's problem using the latest non-sandbox build on macOS. Clicking on 'Create New Grails Project' from the home-screen hangs the process for a minute for me. Cursor turns busy.

I remember for some project template(s) we had such problem in past. Later, after some changes applied to template handling during project creation the problem resolved.

**Comment by piotrzarzycki21** [comment]
> I confirm Joel's problem using the latest non-sandbox build on macOS. Clicking on 'Create New Grails Project' from the home-screen hangs the process for a minute before opening the project creation dialog. Cursor turns busy.
> 
> I remember for some project template(s) we had such problem in past. Later, after some changes applied to template handling during project creation the problem resolved.

I used non sandbox version as well - no problems at all. It looks like you will have to try debug it on your end since you are able to reproduce it...

**Comment by piotrzarzycki21** [comment]
@JoelProminic What is the path where you are trying to save project ? Can you change it to something else and try.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, I don't even get the chance to choose a target directory for the project.  Moonshine hangs immediately after clicking File > New > Grails Project

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 Can you take a look to #402 if you can retrieve some memory for the problem you found and your applied fix - if they are identical here, too? (Although, I understand you are not encountering the problem but if you can at least find the pattern)

**Comment by JoelProminic** [comment]
Some more information from my last test:
1. I closed all other projects
1. I clicked File > New > Grails Project
1. Moonshine hung for about 7 minutes, then displayed the dialog
1. I clicked on the project name and started to change it.  
1. Moonshine hung again for 3-5 minutes
1. I was able to change the project name and create the project.  These steps seemed normal to me.

**Comment by piotrzarzycki21** [comment]
Were you able to see what was the path where project was trying to be saved ?

**Comment by piotrzarzycki21** [comment]
@JoelProminic I just pushed potential fix for this issue. Take a look with next bamboo build.

**Comment by JoelProminic** [comment]
I confirmed that this fixed the problem on macOS, with the App Store version.  I also tested on Windows and confirmed I did not see a problem there.
