### ISSUE TITLE
"URL to Launch" Errors

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#636]
I tested the Custom URL to Launch updates for the 2.5.0 release, and this worked fine.  However, I got unexpected behavior for the "URL To Launch" field.  I tested on macOS.
1. Create a new Flex Browser or Royale Jewel project
1. Create test/test.html (see example below)
1. Open Project > Settings, Run,.
1. Change "URL to Launch" to test/test.html
1. Project > Build & Run ("as Javascript" for Royale)

test.html example (for convenience)
```
<html>
<head>
	<title>Test Alternate File</title>
</head>
<body>
	<p>Test Alternate File.</p>
</body>
</html>
```

With the Flex Browser Project, it opened the original HTML file anyway

With Royale Jewel, it gave me this error:

    : Project Build Successfully.
    : Launching application TestCustomURLRoyale.
    : TypeError: Error #2007
    : 	at actionScripts.plugins.swflauncher::SWFLauncherPlugin/launchExternal()
    : 	at actionScripts.plugins.swflauncher::SWFLauncherPlugin/launchSwf()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugins.as3project.mxmlc::MXMLCJavaScriptPlugin/launchApplication()
    : 	at actionScripts.plugins.as3project.mxmlc::MXMLCJavaScriptPlugin/onSuccesfullBuildCompleted()
    : 	at MethodInfo-17691()
    : 	at SetIntervalTimer/onTimer()
    : 	at flash.utils::Timer/tick() Error
    : Application TestCustomURLRoyale started.

Should I be using Custom URL to Launch for this as well?  If so, what is the purpose of "URL to Launch"?

**Comment by piotrzarzycki21** [comment]
@JoelProminic I just pushed more fixes to this area. It turns out that url to launch option wasn't used in Flex applications at all. There were used custom build path to html wrapper which is created for new project. Current logic looks like that:

1) Custom html have precedence and if exists it will be used first regardless type of the project
2) If custom html doesn't exists launch url will be used
3) If launch url doesn't exists - there fall back to some default path - That part exists previously and I didn't change it

**Comment by JoelProminic** [comment]
Project Type | URL To Launch | Custom URL | Result
-------------|---------------|------------|-------
Flex Browser | Default on Creation | Default (Empty) | bin-debug/<Project>.html
Flex Browser | Cleared (value was reset) | Empty | bin-debug/<Project>.html
Flex Browser | Custom(test.html) | Empty | test.html
Flex Browser | Empty | Custom (moonshine-ide.com) | moonshine-ide.com
Flex Browser | Custom (test.html) | Custom (moonshine-ide.com) | moonshine-ide.com
Royale JS Jewel | Default on Creation  | Default (Empty) | /bin/js-debug/index.html
Royale JS Jewel | Cleared (value was reset) | Empty | /bin/js-debug/index.html
Royale JS Jewel | Custom(test.html) | Empty | test.html
Royale JS Jewel | Empty | Custom (moonshine-ide.com) | moonshine-ide.com
Royale JS Jewel | Custom (test.html) | Custom (moonshine-ide.com) |

There are other project types to test, and some Windows tests would be nice too, but I need to move on to other tasks for now.

**Comment by piotrzarzycki21** [comment]
> Project Type	URL To Launch	Custom URL	Result
> Flex Browser	Default on Creation	Default (Empty)	bin-debug/.html
> Flex Browser	Cleared (value was reset)	Empty	bin-debug/.html
> Flex Browser	Custom(test.html)	Empty	test.html
> Flex Browser	Empty	Custom (moonshine-ide.com)	moonshine-ide.com
> Flex Browser	Custom (test.html)	Custom (moonshine-ide.com)	moonshine-ide.com
> Royale JS Jewel	Default on Creation	Default (Empty)	/bin/js-debug/index.html
> Royale JS Jewel	Cleared (value was reset)	Empty	/bin/js-debug/index.html
> Royale JS Jewel	Custom(test.html)	Empty	test.html
> Royale JS Jewel	Empty	Custom (moonshine-ide.com)	moonshine-ide.com
> Royale JS Jewel	Custom (test.html)	Custom (moonshine-ide.com)	
> There are other project types to test, and some Windows tests would be nice too, but I need to move on to other tasks for now.

Yeah for sure, but the question is whether it is enough good so we could finally move to release ?
