### ISSUE TITLE
Navigate to method/classes crashes on CTRL + Click

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#639]
In Moonshine update [1475](https://moonshine-ide.com/downloads/releases/dev/windows/build_details_windows.json) navigating to method or components trough ctrl+click stopped working.

![crash_ctrl_click](https://user-images.githubusercontent.com/24554795/69651521-7eec0500-1070-11ea-9bcc-8bf96631e44c.gif)

**Stacktrace from installed version:**
```
: Click here to Report a Bug
: Error #1125
: RangeError: Error #1125
: 	at actionScripts.ui.editor.text::TextEditor/getXYForCharAndLine()
: 	at actionScripts.ui.editor.text::GotoDefinitionManager/showDefinitionLink()
: 	at actionScripts.ui.editor.text::TextEditor/showDefinitionLink()
: 	at actionScripts.ui.editor::LanguageServerTextEditor/showDefinitionLinkHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.languageServer::LanguageClient/handleDefinitionLinkResponse()
: 	at actionScripts.languageServer::LanguageClient/parseMessage()
: 	at actionScripts.languageServer::LanguageClient/parseMessageBuffer()
: 	at actionScripts.languageServer::LanguageClient/input_onData()
```

**Screenshot from debug mode using Intellij:**
![crash](https://user-images.githubusercontent.com/24554795/69652737-6a107100-1072-11ea-9c67-fa220e366b32.png)

**Comment by piotrzarzycki21** [comment]
@joshtynjala I assigned to you this one cause I'm not sure if it's cause by your latest updates. If not let me know maybe I will start figuring out what is happening.

**Comment by joshtynjala** [comment]
Yeah, it's probably my changes. Looking into it!
