### ISSUE TITLE
[UI Builder] "Export Visual Editor Project" option is disabled when user open another project

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#64]
In following scenario "Export Visual Editor Project" option should be enabled:

> 1) I opened a Visual Editor project - 'Export Visual Editor Project' option turns enabled 
> 2) Opened any other Flex project at the same time - selecting the project make 'Export Visual Editor Project' option disabled; but it never enable back when I select back the Visual Editor project

**Comment by piotrzarzycki21** [comment]
I need a bit more clarification from you @rat-moonshine . Currently if I go through your scenario and than open some file from Visual Editor project "Export Visual Editor Project" option turn back to Enabled.

What do you mean by saying ? 

> when I select back the Visual Editor project

Do you mean clicking on the name of the project ?
That issue expose more general problem in Moonshine, where we actually don't know what project is currently active. By active I mean that user know he has opened 10 projects which one will be build if he go to Project -> Build Project. Am I miss something ?

**Comment by rat-moonshine** [comment]
I think sometime back we probably discussed on this to how to determine which project file is currently selected at a time. I think you also made some changes on this line, too. That should help to determine which project is 'active' - or am I looking into different direction (?)

What I did in my tests are mainly these:
- Opened VE project 
- I see 'Export Visual Editor Project' option is enable
- I opened a new Flex project 
- When I selects any file inside the Flex project I found that 'Export Visual Editor Project' turns disabled
- When I re-select any file of VE project, I don't found the option turned enabled

So there's must some logic that you used to determine if the active/selected project is non-VE, and turned the option disabled. So you should be able to turn it enable when the active/selected project is type of VE again, I guess (?)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Yes I did changes and it makes active project property more alive. We are refreshing that property on couple of events for example: when new project is opened, or some of the project file is being opened (double click in Tree).  Although I think it is impossible to discover all scenarios which user can run into.
The fix which I will do to handle that problem for me is workaround. 

We need to discuss feature where user will be able to select project which will be active. It simplifies everything in case of Menu. Currently when I have 5 projects open and I'm clicking Build - I have no idea which one will be actually build. I'm going to raise issue for that.

**Comment by rat-moonshine** [comment]
> Currently when I have 5 projects open and I'm clicking Build - I have no idea which one will be actually build. I'm going to raise issue for that.

When there multiple projects are open, and you choose build option from the menu, it build the project that has the file selection. Although, there are certain cases when selection lost. At that time if multiple projects are opened and you choose build option, Moonshine alerts a popup with currently opened project list, from where you need to choose the project you want to build.

**Comment by piotrzarzycki21** [comment]
Understand. I wasn't aware of that popup. Didn't get that, but it good to know. I just fixed issue by having "activeProject" property refreshed if user click on item in project TreeView.
