### ISSUE TITLE
Java Path Spaces Error for Java Maven Project

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#647]
I found another case where SDK spaces are not handled properly in Windows Moonshine (2.5.0, and the latest nightly build).   I already had Java installed on this Windows machine, so Moonshine used the path from the environment variable:

    C:\Program Files\Java\jdk1.8.0_161

1. Create a new Java Maven Project
2. Wait for the Language server to finish starting.  Note that this works fine
3. Project > Build.  BUG: this fails with the error:

    : Starting Maven build...
    : Maven path: C:\MoonshineSDKs\Maven\apache-maven-3.6.0
    : Maven build directory: C:\Flex\temp_workspace\TestJavaMavenSpaces
    : Command: C:\MoonshineSDKs\Maven\apache-maven-3.6.0\bin\mvn.cmd clean package
    : Files\Java\jdk1.8.0_161""=="" was unexpected at this time.
    : Maven build has been terminated with exit code: 255

From the error, it looks to me like the space is not escaped properly.

On a side note, I tried to work around this by clearing JAVA_HOME and using Moonshine SDK Installer to download Java to the default path (with no spaces).  However, Moonshine still repopulated the above Java path.

**Comment by piotrzarzycki21** [comment]
I have finally nailed it down! It looks like on Windows when we setup `JAVA_HOME` with quotes it causes an error when Maven is using it. This causes issue:

`set JAVA_HOME="C:\Program Files\Java\jdk8u202-b08"`
without 
`set JAVA_HOME=C:\Program Files\Java\jdk8u202-b08`

Everything is working fine. I'm going to commit my changes so please if you will have any problems with something related to Java on Windows let me know.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Be careful with my changes - if anything will be broken related to Java - let me know. I will test also Java project once nightly build will be ready.

**Comment by piotrzarzycki21** [comment]
It looks like Java Maven project is working fine.
