### ISSUE TITLE
Build & Run Opens Debug Mode for Flex Browser Project

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#649]
I noticed errors with Flex Browser projects using the latest non-Sandbox macOS build from Bamboo:
1. Create a new Flex Browser project
1. Project > Build & Run.  
1. BUG:  Debug tab opens
1. Close the Debug tab
1. Project > Clean Project
1. Project > Build & Run
1. BUG:  Debug tab opens again
1. BUG:  The application does not open in a browser, and I see this error on the console:
1. Project > Build & Debug
1. This gives the same behavior and errors

    : Compiling TestRoyaleAPIReport2
    : SDK path: /Users/-user-/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0
    : Sending to mxmlc: "/Users/-user-/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/bin/mxmlc" -load-config+=obj/TestRoyaleAPIReport2Config.xml -optimize=false -debug=true -o bin-debug/TestRoyaleAPIReport2.swf
    : Loading configuration file /Users/-user-/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/frameworks/flex-config.xml
    : Loading configuration file /Users/-user-/Documents/Flex/temp_workspace/TestRoyaleAPIReport2/obj/TestRoyaleAPIReport2Config.xml
    : /Users/-user-/Documents/Flex/temp_workspace/TestRoyaleAPIReport2/bin-debug/TestRoyaleAPIReport2.swf (619333 bytes)
    : Project Build Successfully.
    : Process error: Exception in debugger on launch request:
    : Process error: java.io.FileNotFoundException: /bin-debug/TestRoyaleAPIReport2.html
    : 	at flash.tools.debugger.concrete.PlayerSessionManager.tweakNativeLaunchUri(PlayerSessionManager.java:303)
    : 	at flash.tools.debugger.concrete.PlayerSessionManager.getLaunchCommand(PlayerSessionManager.java:1144)
    : 	at flash.tools.debugger.concrete.PlayerSessionManager.launchForRun(PlayerSessionManager.java:1103)
    : 	at flash.tools.debugger.threadsafe.ThreadSafeSessionManager.launchForRun(ThreadSafeSessionManager.java:168)
    : Process error: 
    : 	at com.as3mxml.vscode.SWFDebugSession.launch(SWFDebugSession.java:506)
    : 	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:100)
    : 	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:143)
    : 	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:102)
    : 	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:81)
    : 	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:49)
    : Debug launch failed.

**Comment by rat-moonshine** [comment]
I confirm the behaviour of open-up Debug tab everytime I perform 'Build & Run' in case of desktop projects, too. 

```
: Process error: Exception in debugger on launch request:
: Process error: java.io.FileNotFoundException: /bin-debug/NewFlexBrowserProject.html
```
For browser-Flash project Moonshine generates the corresponding wrapper HTML/JS file to the project's "bin-debug" folder on project creation. In my tests I able to have the example project run properly on Safari (which has Flash plugin installed) and in Chrome (showing enable Flash message as it is default-disabled in my Chrome).

I see the above error fires once I perform "Project -> Clean Project" command which deletes the files inside "bin-debug" folder. I remember they were suppose to re-generate on next time project compilation if the wrapper HTML/JS files are missing. I don't know when it's stopped working. I need to look into the related area.

**Comment by rat-moonshine** [comment]
The second part of this issue probably still valid, so I'm reopening this to look into further.

**Comment by rat-moonshine** [comment]
The fix from Josh seems to fixed the second part (non population of deleted HTML wrapper) of this problem as well. I have tested on Windows and macOS-debug and confirm Moonshine does re-creates missing/deleted wrapper HTML files on next compilation. Since the Ant build script failing at this moment, I could not able to test from a packaged installation for now.

I'll reopen this if wrapper generation demonstrate any problem when testing from packaged installation on macOS.
