### ISSUE TITLE
[UI Builder] Visual Editor don't prompt the user for saving once add new items and close

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#65]
User should be prompted for saving files once add to new items and close visual editor project.

> After opening the application file (Mockup UI) I placed some components there, while closing the file editor asks me to save, I choose it to save. Re-opened the file on editor, added some more components in it. This time when closing the editor Moonshine didn't prompt me to save. Opening the application file again, I see my last changes not saved.

**Comment by piotrzarzycki21** [comment]
I have fixed scenario above, but it seems I will have to work more in Visual Editor to handle changes for individual properties. I will raise separate issue for that work.

**Comment by rat-moonshine** [comment]
I see the following scenario do not covers the fixes, with my current tests:

**When it do not works**
- Open a Visual Editor project
- Drag any component to the editor - IMPORTANT - do not deselect the component
- Close the editor tab
- [BUG] No editor change alert came 

**When it works**
- Open a Visual Editor project
- Drag any component to the editor
- Deselect the component and select back
- Close the editor tab
- Moonshine alerts on editor changes

I'm reopening this issue for further investigation.
