### ISSUE TITLE
Authentication failure on SVN hangs checkout process when renaming the project during checkout

### ISSUE THREAD

**Issue by JustinProminic** [prominic/Moonshine-IDE#652]
- [ ] Review the documentation: https://github.com/prominic/Moonshine-IDE
- [ ] Search for existing issues: https://github.com/prominic/Moonshine-IDE/issues
- [ ] Use the latest stable version at: http://moonshine-ide.com
- [ ] Let us know how to reproduce the issue. Include a code sample, or share a project that reproduces the issue

## Environment
MacOS App Store Version 2.5.0.   MacOS release 10.14.6 (Mojave)

## Description
From the Repository Manager, I checked out a project from SVN.  I was prompted for authentication.  I entered what I believed to be my correct username/password, but clearly mistyped.  The error below appeared in the console, but the window showing checkout had "hung" believing it was checking something out.

## Steps to Reproduce
See above

## Expected Behavior
An error prompt for bad username/password

### Errors
Error #1009
TypeError: Error #1009
	at actionScripts.plugins.svn.commands::SVNCommandBase/onAuthSubmitted()
	at flash.events::EventDispatcher/dispatchEvent()
	at mx.core::UIComponent/dispatchEvent()
	at components.popup::GitAuthenticationPopup/onSubmit()
	at components.popup::GitAuthenticationPopup/__btnCommit_click()

**Comment by JustinProminic** [comment]
It appears this bug is triggered by renaming the project during checkout:

![image](https://user-images.githubusercontent.com/30169573/72853554-59960480-3c77-11ea-94f1-118f8a03854c.png)

**Comment by JustinProminic** [comment]
Joel tested this with me 'live' and he is running Mac OS Yosemite and the App Store build of Moonshine and could not reproduce this issue.  So it may be a Mojave related bug.

**Comment by rat-moonshine** [comment]
While looked into the codes, I confirm we have listeners added to react accordingly when a bad-authentication or, user cancel the authentication window.

I did a quick test on El Capitan, using iTunes version of Moonshine, following were my output:

1. Bad authentication, the authentication-window suppose to return as long user do a bad auth 
![image](https://user-images.githubusercontent.com/24370870/72867444-f8b50d80-3d04-11ea-9918-40094b9a2415.png)

2. If the authentication-window cancelled,
![image](https://user-images.githubusercontent.com/24370870/72867484-1a15f980-3d05-11ea-8420-5f64d62869ff.png)

Following were my console output which is different than @JustinProminic ,

```
: svn: E170013: Unable to connect to a repository at URL 'https://xxxx.net/svn/sh-flex/trunk/GBAuth'
: svn: E215004: No more credentials or we tried too many times.
: Authentication failed
```

Justin's error points to internal exception. I'll try to investigate if any possible way an error can throw from pointing location.

**Comment by rat-moonshine** [comment]
I tried to give this re-test after upgraded to Mojave. Following are test results from my initial tests:

1. Downloaded latest iTunes sandbox version of Moonshine IDE
2. Made sure that I do not have any saved SVN authentication to keychain
3. Tried to checkout GBAuth through Repository Manager
4. Renamed the target download directory in Checkout window
![image](https://user-images.githubusercontent.com/24370870/73722035-9966ec80-474b-11ea-9dc7-a50889c5f7e8.png)
5. Upon authentication prompt, I intentionally entered wrong credentials three times but authentication prompt keep appearing for me as expected, and without any exception in this case:
```
: Trying to check out https://-censored-/trunk/GBAuth. May take a while.
: svn: E170013: Unable to connect to a repository at URL 'https://-censored-/trunk/GBAuth'
: svn: E215004: No more credentials or we tried too many times.
: Authentication failed
: Trying to check out https://-censored-/trunk/GBAuth. May take a while.
: svn: E170013: Unable to connect to a repository at URL 'https://-censored-/trunk/GBAuth'
: svn: E215004: No more credentials or we tried too many times.
: Authentication failed
: Trying to check out https://-censored-/trunk/GBAuth. May take a while.
: svn: E170013: Unable to connect to a repository at URL 'https://-censored-/trunk/GBAuth'
: svn: E215004: No more credentials or we tried too many times.
: Authentication failed
: Trying to check out https://-censored-/trunk/GBAuth. May take a while.
: A    GBAuthDownloaded/fla-raws
: A    GBAuthDownloaded/fla-raws/Global.fla
: A    GBAuthDownloaded/.settings
: A    GBAuthDownloaded/.project
: A    GBAuthDownloaded/src
```
6. Upon proper credential it starts downloading for me (as shown above)

In another attempt, after removing any saved credentials, I tried to checkout GBAuth again by entering wrong credentials twice and then cancel the authentication window. That closed all the process as expected for me, too.

@JoelProminic can you give this a test on High Sierra (?)

**Comment by rat-moonshine** [comment]
After many tests and experiments with @JoelProminic , I finally able to find the right steps to re-produce this on Mojave. Here's the step details for future reference:

1. Add a repository like **ProminicSVNDirectoryAssistance** which has repository XML information, in Repository Manager
2. Successful checkout of above should add you a new XML entry to Repository Manager
3. Remove any saved SVN credential (I removed from Keychain)
4. Click on the newly added XML entry in Repository Manager, and click on 'Browse'
5. This should open you a list of repository information 
6. Select any of them and try checkout 
7. I tested by changing the target folder name in checkout window
8. I entered wrong credential in first authentication attempt
9. In next authentication prompt I entered wrong credential again, and also checked to save auth for the session
10. Exception thrown to console and busy icon didn't removed from the screen

We also talked about some possible areas we wants to check/debug, hopefully identifying the problem would be easy from now as I able to reproduce the problem myself, finally.

**Comment by rat-moonshine** [comment]
I confirm the problem is valid for Windows, too.

**Comment by rat-moonshine** [comment]
I have a growing feeling if we really needs to continue this options anymore or not. Since we have seen in both macOS and Windows, once successful authentication the information gets saved to keychain or windows-credential-manager.

![image](https://user-images.githubusercontent.com/24370870/73816657-2f178000-480f-11ea-88b3-a5aa0625705f.png)

Anyway, the problem is handled now. Here are my test procedure after the fix applied:

1. Add a repository like _ProminicSVNDirectoryAssistance_ which has repository XML information, in Repository Manager
2. Successful checkout of above should add you a new XML entry to Repository Manager
3. Remove any saved SVN credential (I removed from Windows-credential-manager)
4. Click on the newly added XML entry in Repository Manager, and click on 'Browse'
5. This should open you a list of repository information
6. Select any of them (I tested with GBAuth) and try checkout
7. I tested by changing the target folder name in checkout window
8. I entered wrong credential in first authentication attempt
9. In next authentication prompt I entered wrong credential again, and also checked to save auth for the session
10. Moonshine report wrong credential and keep prompting with authentication window
11. Once proper authentication entered project successfully checkout 

This issue is now open for test on 'master'.

**Comment by piotrzarzycki21** [comment]
It's fixed.
