### ISSUE TITLE
Git: macOS version of Moonshine fail to determine a private repository

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#656]
Unlike Windows, on macOS when try cloning a private repository, Moonshine fail to determine if the repository really exists by throwing following message:

```
remote: Repository not fount.
fatal: repository https://github.com/...
```

On Windows git-API somehow able to determine private repo followed by authentication window. We at least somehow need to determine the existence of private repository on macOS and do any needful therefore.

**Comment by JoelProminic** [comment]
For macOS High Sierra and Git 2.20.1, I got this error:

    : Cloning into 'Store-Manager.git'...
    : fatal: could not read Username for 'https://github.com': Device not configured

If I try to connect manually from the command line, I see:

    $ git --version
    git version 2.20.1
    $ git clone https://github.com/prominic/Store-Manager.git
    Cloning into 'Store-Manager'...
    Username for 'https://github.com': JoelProminic
    Password for 'https://JoelProminic@github.com': 
    remote: Enumerating objects: 242, done.
    remote: Counting objects: 100% (242/242), done.
    remote: Compressing objects: 100% (162/162), done.
    remote: Total 242 (delta 80), reused 216 (delta 63), pack-reused 0
    Receiving objects: 100% (242/242), 543.37 KiB | 2.66 MiB/s, done.
    Resolving deltas: 100% (80/80), done.

**Comment by rat-moonshine** [comment]
For note, following was my test results using El Capitan and Git 2.8.4 (Apple Git-73) (it seems High Sierra has a very higher version), on Terminal:

```
$ git clone https://github.com/prominic/Store-Manager.git
Cloning into 'Store-Manager'...
remote: Repository not found.
fatal: repository 'https://github.com/prominic/Store-Manager.git/' not found
```

**Comment by rat-moonshine** [comment]
We probably need to track an issue (separately) to avail possibility to enter PIN/token when prompt, for two-factor authentication specifically. At present we have only prompt for login username and password on macOS.

**Comment by JoelProminic** [comment]
Here is the documentation for [authenticating from Git command line with two-factor authentication](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).  On the user side, this works the same as entering a normal userame and password (but you use the token instead of a password).

**Comment by rat-moonshine** [comment]
After upgraded to Mojave, I tried to give this a test:

1. Tried to checkout Store Manager which is a private repository, I continued to get same error:
$ git clone https://github.com/prominic/Store-Manager.git
Cloning into 'Store-Manager'...
remote: Repository not found.
fatal: repository 'https://github.com/prominic/Store-Manager.git/' not found
2. Upon testing the version of Git, I see the same build is continuing from previous El Capitan:
$ git --version
git version 2.8.4 (Apple Git-73)
3. As it seems upgrading the OS not necessarily upgrades the Git build also; So I went to https://git-scm.com/ and tried to upgrade myself
4. After the Git update I now have a latest Git and I able to see authentication error during private repository checkout **instead of** earlier repository not found message:
```
$ git --version
git version 2.23.0
$ git clone https://github.com/prominic/Store-Manager
Cloning into 'Store-Manager'...
Username for 'https://github.com': rat-moonshine
Password for 'https://rat-moonshine@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/prominic/Store-Manager/'
```

BUT here's the catch. I was using XCode version of Git inside Moonshine. Thus, updating system Git doesn't resolve when I use XCode version of Git - it remain same and keeps throwing me same 'repository not found' error. Maybe, updating XCode is the only way to go in that case.

**Comment by rat-moonshine** [comment]
I confirm updating XCode also updates Git build within which reflects to Moonshine:

![image](https://user-images.githubusercontent.com/24370870/73732955-1b154500-4761-11ea-8a27-164511c3bd82.png)

But using the updated version, I'm still receiving 'repository not found' error:
```
$ /Applications/Xcode.app/Contents/Developer/usr/bin/git --version
git version 2.21.1 (Apple Git-122.3)
$ /Applications/Xcode.app/Contents/Developer/usr/bin/git clone https://github.com/prominic/Store-Manager
Cloning into 'Store-Manager'...
remote: Repository not found.
fatal: repository 'https://github.com/prominic/Store-Manager/' not found
```

**Comment by rat-moonshine** [comment]
After a few more tests it appears that macOS was using my personal Git-credential stored into system keychain against the Prominic private repository checkout, however the Git error was not meaningful. 

```
$ git clone https://github.com/prominic/Store-Manager
Cloning into 'Store-Manager'...
remote: Repository not found.
fatal: repository 'https://github.com/prominic/Store-Manager/' not found
```
After I removed _any_ credentials from keychain:
```
$ git clone https://github.com/prominic/Store-Manager
Cloning into 'Store-Manager'...
Username for 'https://github.com':
```
Earlier I tested that providing personal-access-token as password to Moonshine git-authentication window works as expected, on macOS.

@JoelProminic do you think we needs to add/modify anymore functionality on these (?)

**Comment by JoelProminic** [comment]
Ah, so your keychain had credentials for a different account which did not have access to Store-Manager.  When you tried to access Store-Manager, it reported that the project does not exist, rather than giving an error about not having access.   This behavior makes sense for GitHub, since these repositories are supposed to be private (though I fear that this will cause confusions for other users in a similar case).

I think this is matching the behavior of GitHub and Git, so it should be fine to leave the behavior like this.

**Comment by JoelProminic** [comment]
@rat-moonshine, did we have any code updates for this issue, or was it just a problem on your workstation?   If it is the latter, then I'll remove this from the Changelog.

**Comment by rat-moonshine** [comment]
There have been no code-updates against this issue as this more likely how the Git works in-communication with the OS. However, it could have been better if Git could provide a more meaningful message when an auth-error in such a scenario. But then again, what we could do about it.
