### ISSUE TITLE
Moonshine Builds Multiple Projects with Build & Run

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#657]
I noticed this behavior today:
1. Create/Open a Flex Desktop project
2. Create/Open a Royale project
3. Try to Build & Run the Royale project
4. Both projects build and launch. 

If I have multiple Flex projects open, I get a prompt to choose one, while the Royale build runs in the background

![image](https://user-images.githubusercontent.com/24532731/73287816-78d4ea80-41bf-11ea-959a-a21a59719ff3.png)

**Comment by rat-moonshine** [comment]
Following as I tested on Windows:

1. Create/Open a Flex Desktop project
2. Create/Open a Royale project
3. Try to Build & Run the Royale project
4. Both projects starts building same time resulting mixed output to console
5. Royale project thrown some configuration load error however it managed to open the application to browser
6. Desktop compilation lost and never opened anything

**Comment by rat-moonshine** [comment]
It appeared that "Build & Run" broadcasting `ActionScriptBuildEvent.BUILD_AND_RUN` which listens into both MXMLCPlugin (responsible for Flex/ActionScript projects) and MXMLCJavaScriptPlugin (responsible for Royale projects) which triggers compilation in both the plugin classes. I believe we didn't had this problem before as we had separate menu-options for Royale projects, but they combined as one recently as "Build & Run".

I introduced a separate event-type class for Royale project type [JavaScriptBuildEvent](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/plugin/core/compiler/JavaScriptBuildEvent.as), just as we have for Haxe, Java etc. Currently, the particular event type implemented to [menu-items](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/ui/menu/ProjectMenu.as#L157) under "Project" menu only. We will need to test if any other menu-areas also requires such type management.

**Comment by rat-moonshine** [comment]
It seems we probably have a widespread problem in **Debug** menu too, as the menu-item [throws same event](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IFlexCoreBridgeImp.as#L361) (`ActionScriptBuildEvent.BUILD_AND_DEBUG`) for Flex/ActionScript, Royale and Haxe projects.

I tested having both Royale and ActionScript project opened it starts a mixture of debug for both the project types. If Haxe manage its own _plugin_ class and debug process, I believe it'll also start if opened at same time.

We need to work on this.

**Comment by piotrzarzycki21** [comment]
> I tested having both Royale and ActionScript project opened, it starts a mixture of debug for both the project types. If Haxe manage its own _plugin_ class and debug process, I believe it'll also start if opened at same time.
> 
> We need to work on this.

I'm confused - this is separate issue towards what we have in this one ?

**Comment by rat-moonshine** [comment]
The reasoning are same for both `Projects -> Build & Run` and `Debug -> Debug & Run`. We can choose to track the latter in a separate issue if that fits better.

**Comment by rat-moonshine** [comment]
I have some plan and I'm starts working on this @piotrzarzycki21 , unless you've already started to this.

**Comment by piotrzarzycki21** [comment]
> I have some plan and I'm starts working on this @piotrzarzycki21 , unless you've already started to this.

If you don't have more important things go on. I will carefully review your commits.

**Comment by rat-moonshine** [comment]
You do review anyway ;) I'll prioratize my stuff.

**Comment by rat-moonshine** [comment]
Okay. We have added a new middle-manager for the special case/events like of JavaScript projects. I'm not very happy with this treatment, but should be less cluttered then other possible movements. This should do for now. 

A new plugin events/listener now added which listens to certain event from menu-click, do necessary decision based on given logic/procedures, and re-dispatch appropriate events for other stakeholder classes/plugins. The class can be treated for any known project types.

**Comment by piotrzarzycki21** [comment]
> Okay. We have added a new middle-manager for the special case/events like of JavaScript projects. I'm not very happy with this treatment, but should be less cluttered then other possible movements. This should do for now.
> 
> A new plugin events/listener now added which listens to certain event from menu-click, do necessary decision based on given logic/procedures, and re-dispatch appropriate events for other stakeholder classes/plugins. The class can be treated for any known project types. Tested working for both build and debug situations.

So this can be ready for testing ?

**Comment by rat-moonshine** [comment]
Yes, it is on 'master'.

**Comment by rat-moonshine** [comment]
Here's the test-matrix after the updates, having two projects opened at a time - Flex Desktop and Royale.

Project Selection | Action | Results
---------------------- | --------------- | -------------------------------------
Royale | Build & Run | Run the project to browser. Flex desktop project didn't run
Royale | Build | Completes build process. Flex desktop project compilation didn't triggered
Flex Desktop | Build & Run | Run desktop project in AIR. Royale project didn't triggered
Flex Desktop | Build & Run | While running the compilation process - Move to next test -
Royale | Build & Run | Console cleared with Royale build output. Royale project run on browser, desktop project also run eventually in AIR window
Flex Desktop | Build & Debug | Debug started properly. Royale project didn't triggered
Royale | Build & Debug | Process took me to Moonshine Settings to set Node.js first

**Comment by piotrzarzycki21** [comment]
If everything is working and I also tested it a bit I'm closing that one.

**Comment by rat-moonshine** [comment]
While testing the latest nightly Windows Moonshine I noticed Native Royale project build options are not working under the Project menu. This case applicable to all three build options - Build, Build & Run, Build Release.

**Comment by rat-moonshine** [comment]
Fixed issue where Royale project build was not triggering when project menu-type has multiple types.

**Comment by piotrzarzycki21** [comment]
> Fixed issue where Royale project build was not triggering when project menu-type has multiple types.

Carlos reported that issue with mailing list. I will check on my end whether everything is working and I will let him know that it is fixed.

**Comment by piotrzarzycki21** [comment]
Carlos reported that it is working for him. Can you close that ?
