### ISSUE TITLE
[UI Builder] Selection markers of visual editor item added to project are visible during the export

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#66]
In following scenario selection markers are still visible:

1) Create new Visual Editor project and add one item and select it
2) Go to "Project > Export Visual Editor Project"

![image](https://user-images.githubusercontent.com/24554795/32553494-69010db6-c497-11e7-80d9-030d7874cf1a.png)

**Comment by rat-moonshine** [comment]
With my latest tests, I able to reproduce this again.

- Open a Visual Editor project to the editor
- Select any component on the stage - should show its free-transform markers
- Right-click on the project's Settings - this will open the Settings tab and removes free-transform marks in the UI
- Keep that settings tab open, navigate back to the component editor again 
- [BUG] Free-transform marker removed completely and the component is also not selected (the one that previously selected)
- Re-select the component, navigate back to the Settings tab
- [BUG] Free-transform markers are again visible

I'm reopening this issue for further investigation.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just fixed above scenario, however the issue where I'm selecting again previously selected item is something separate. I will need to spend on that more time, but for sure not in 1.7.0 - If you find time raise separate issue for that work.
Solution for removing marker is based on deselect element, that's why when back to the previous tab you see it deselected.

**Comment by rat-moonshine** [comment]
Technically, I understand that deselecting is the answer to now showing the markers in other tabs. But this may be annoying when working through different tabs and it needs to select a component multiple time. However, the main bug reported here is fixed doing so, and we can investigate on the re-selection process with a different issue ticket.
