### ISSUE TITLE
Detect and auto-setup Node.js as applicable

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#661]
![image](https://user-images.githubusercontent.com/24370870/73911000-e0351d80-48d6-11ea-85c6-3aa5641f8cee.png)

Moonshine needs able to detect and auto-setup its Node.js settings, if applicable.

Download of Node.js can be tracked here https://github.com/prominic/Moonshine-SDK-Installer/issues/20. 

@joshtynjala what is the standard of Node.js usage - does it generally set as an environment variable (i.e. `NODEJS_HOME`) or such? Based on the common usage I shall decide on searching through environment variable (apart of looking into SDK-Installer's common download location).

**Comment by rat-moonshine** [comment]
Following are initial test results:

Installed | Moonshine Shown | Action | Results
------ | ------------------------------- | ------------------------- | --------------------
No | <ul><li>Settings Node.Js path is blank</li><li>`About > Getting Started > Node.Js` - download</li></ul> | Opened MSDKI | -
No | - | Install Node.Js through MSDKI | <ul><li>Installation completes</li><li>Node.Js item in Moonshine's **Getting Started** ticked</li><li>Node.Js path in Moonshine Settings updated properly</li></ul>
Yes | Node.Js path in Settings showing proper path | <ul><li>Close **Getting Started** tab</li><li>Clear Node.Js path in Settings and Save</li></ul> | -
Yes | - | Open `About > Getting Started` | Moonshine detects SDK is available and reset NodeJs path in Settings

Currently, the detection process do not involve looking into any particular *_HOME format in environment variable on Windows; Once I advised with a standard of the said naming, I'll add it.

**Comment by joshtynjala** [comment]
I tried to Google for some information on Node.js environment variables. It looks like some people set a `NODE_HOME` environment variable, but I get the impression that it's not as commonly used as `JAVA_HOME` and others.

It's probably good to fall back to detecting standard install locations too. I think that the installer defaults to _c:\Program Files\nodejs_ on Windows, for instance.

**Comment by rat-moonshine** [comment]
Okay, thanks for the advise, @joshtynjala . Meanwhile, I'm not testing any environment variable for Node.js (actually I was waiting for your suggestion on this).

We have no mechanism as of now to test program's default location check, though (i.e. C:\Programe Files\..., or /Applications/...).

**Comment by rat-moonshine** [comment]
This issue now merged into master.

**Comment by piotrzarzycki21** [comment]
I'm closing this one since it's merged. If we decide to release someone will test that out.
