### ISSUE TITLE
Fix 2.5.1 Windows Bamboo Build

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#662]
The Windows Bamboo build is currently failing with this error:

    06-Feb-2020 09:02:46 	CompileSWFWindowsSignedPackage:
    06-Feb-2020 09:02:46 	     [echo] Signed Process Running
    06-Feb-2020 09:03:56 	     [java] unexpected failure: Platform conversion failed. Process exited with error 5. Output was "Conversion complete
    06-Feb-2020 09:03:56 	     [java] [ErrorEvent type="error" bubbles=false cancelable=false eventPhase=2 text="Error #2038" errorID=2038]
    06-Feb-2020 09:03:56 	     [java] "
    06-Feb-2020 09:03:56 	     [java] java.io.IOException: Platform conversion failed. Process exited with error 5. Output was "Conversion complete
    06-Feb-2020 09:03:56 	     [java] [ErrorEvent type="error" bubbles=false cancelable=false eventPhase=2 text="Error #2038" errorID=2038]
    06-Feb-2020 09:03:56 	     [java] "
    06-Feb-2020 09:03:56 	     [java]         at com.adobe.air.nai.NativePackager.conversionFail(NativePackager.java:279)
    06-Feb-2020 09:03:56 	     [java]         at com.adobe.air.nai.NativePackager.invokePlatformConversion(NativePackager.java:260)
    06-Feb-2020 09:03:56 	     [java]         at com.adobe.air.nai.NativePackager.createPackage(NativePackager.java:133)
    06-Feb-2020 09:03:56 	     [java]         at com.adobe.air.ADT.parseArgsAndGo(ADT.java:673)
    06-Feb-2020 09:03:56 	     [java]         at com.adobe.air.ADT.run(ADT.java:471)
    06-Feb-2020 09:03:56 	     [java]         at com.adobe.air.ADT.main(ADT.java:521)
    06-Feb-2020 09:03:56 	     [java] Picked up _JAVA_OPTIONS: -Xmx1024M
    06-Feb-2020 09:03:56 	
    06-Feb-2020 09:03:56 	BUILD FAILED
    06-Feb-2020 09:03:56 	D:\bamboo-agent-home\xml-data\build-dir\MS-MGWS-DJ2\M\ide\MoonshineSharedCore\build\build-lib.xml:209: The following error occurred while executing this line:

Previously, this error has occured because the nested file paths were too long.  We think the problem is probably with `{build-directory}/M/ide/MoonshineDESKTOPevolved/build/elements`

To work around this, we would like to move the elements directory to a shorter path, like `{build-directory}/elements`.  To do this, we will need to define a property for this path in build-lib.xml:  https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/build/build-lib.xml#L277

I'll create a branch to try this.

**Comment by JoelProminic** [comment]
I created this branch:  features/issue_662_shorten_ant_path

However, adt rejected the path when I used this option:  `-Delements_dir=../../../elements`

    compile app project:
         [java] File -snip-/Moonshine-IDE/elements/Config.xml is not relative to directory -snip-/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build


I tried shortening the name instead, but this changed the name of the elements directory inside application:  `-Delements_dir=./e`

    compile app project:
         [java] -snip-/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/bin-debug/MoonshineDESKTOP-app.xml: error 303: Icon elements/moonshine_logo/logo_32.png is missing from package
         [java] -snip-/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/bin-debug/MoonshineDESKTOP-app.xml: error 303: Icon elements/moonshine_logo/logo_48.png is missing from package
         [java] -snip-/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/bin-debug/MoonshineDESKTOP-app.xml: error 303: Icon elements/moonshine_logo/logo_512.png is missing from package
         [java] -snip-/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/bin-debug/MoonshineDESKTOP-app.xml: error 303: Icon elements/moonshine_logo/logo_16.png is missing from package
         [java] -snip-/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/bin-debug/MoonshineDESKTOP-app.xml: error 303: Icon elements/moonshine_logo/logo_128.png is missing from package

I tested on macOS instead of Windows, but I doubt that will make a difference.

I uploaded the branch anyway in case someone wants to explore a similar idea.

I don't see how I can move build/elements/chrome-debug-adapter only and still have this Ant script work.  Moving the build/ directory itself is possible, but it it would require changing almost every path in the Ant script.

**Comment by JoelProminic** [comment]
I applied @joshtynjala's fix to the branch, and that cleared the elements directory error.  HOwever, I'm still getting this error after the update:

    06-Feb-2020 18:55:02 	CompileSWFWindowsSignedPackage:
    06-Feb-2020 18:55:02 	     [echo] Signed Process Running
    06-Feb-2020 18:56:22 	     [java] unexpected failure: Platform conversion failed. Process exited with error 5. Output was "Conversion complete
    06-Feb-2020 18:56:22 	     [java] [ErrorEvent type="error" bubbles=false cancelable=false eventPhase=2 text="Error #2038" errorID=2038]
    06-Feb-2020 18:56:22 	     [java] "
    06-Feb-2020 18:56:22 	     [java] java.io.IOException: Platform conversion failed. Process exited with error 5. Output was "Conversion complete
    06-Feb-2020 18:56:22 	     [java] [ErrorEvent type="error" bubbles=false cancelable=false eventPhase=2 text="Error #2038" errorID=2038]
    06-Feb-2020 18:56:22 	     [java] "
    06-Feb-2020 18:56:22 	     [java]         at com.adobe.air.nai.NativePackager.conversionFail(NativePackager.java:279)
    06-Feb-2020 18:56:22 	     [java]         at com.adobe.air.nai.NativePackager.invokePlatformConversion(NativePackager.java:260)
    06-Feb-2020 18:56:22 	     [java]         at com.adobe.air.nai.NativePackager.createPackage(NativePackager.java:133)
    06-Feb-2020 18:56:22 	     [java]         at com.adobe.air.ADT.parseArgsAndGo(ADT.java:673)
    06-Feb-2020 18:56:22 	     [java]         at com.adobe.air.ADT.run(ADT.java:471)
    06-Feb-2020 18:56:22 	     [java]         at com.adobe.air.ADT.main(ADT.java:521)
    06-Feb-2020 18:56:22 	     [java] Picked up _JAVA_OPTIONS: -Xmx1024M

For this quick test, I used an older plan that didn't have the shortened base directory name, but I'm not sure that would make a difference if the paths are this long.   I'm heading out for the day, but I'll take another look tomorrow.  @rat-moonshine, let me know if you have any other ideas for this.

**Comment by joshtynjala** [comment]
Maybe you can add even more `../` prefixes to go further up than the "/Moonshine-IDE/" folder. Like all the way to the root of the drive?

This is probably way too many, but you get the idea:

-Delements_dir=../../../../../../../../../../../../../../../elements

**Comment by rat-moonshine** [comment]
Okay. The results are not very heartthrob so far. I spent quite some hours behind this. 

The earlier error from @JoelProminic comment probably because of a leftover 'elements' reference at [here](https://github.com/prominic/Moonshine-IDE/commit/e075d3921f64525c2bfc0231108fb50ebaa4b39f#diff-dfd9749fed109abe924331d8353a209bR288). I removed this now.

Having so, I starts getting missing-logo file errors from the application descriptor file **same** as reported in [here](https://github.com/prominic/Moonshine-IDE/issues/662#issuecomment-583100888). After some playing this also fixed; and you can see number of success builds starts therefore.

However, when noticed closely, the build is much smaller now - only 15MB. When installed I found that 'elements' folder haven't bundled at all. 

More investigation on this, the following command didn't even bundling the pointed folder at all, even when run locally (on my Windows 10 x64 machine) by creating same environment:
`<arg line="-C ${elements_dir}/.." />`

Through lots of permutation/combination, I came up to this modified command which finally worked for me, locally:
`<arg line="-C ${elements_dir}/.. elements" />`

I also noticed that the declaration must be the last in the _arg_ list, else it'll start thinking followed by references start from the directory mentioned by `-C` specifier.

Anyway, having boost up and being sure this should bundle the directory now surely, I updated stuff to the repository. Unfortunately, I still starts getting the same file-system length error by compiler. Maybe three "../" wasn't enough.

I moved on to increase the "../" references from three to five - which now copies the 'elements' folder here: `D:\bamboo-agent-home\xml-data\build-dir\elements`; And I stopped thereafter. I don't know what other side-effect it may cause if I go further backwards; I even don't know how larger the file names are actually deep inside the directories! So I stopped, for now.

Things are keep breaking with the same old system-length error.

**Comment by joshtynjala** [comment]
I just ran the **npm dedupe** command for the chrome-debug-adapter, and it moved one of the modules up a level, which might help. I cherry-picked the commit into the features/issue_662_shorten_ant_path branch. Let me know if it helps!

**Comment by JoelProminic** [comment]
That didn't work either, unfortunately.   

@rat-moonshine and i tried using an absolute path instead `-Delements_dir=D:\temp\elements`  I checked the resulting paths, and the longest I saw was 150 characters.  However, we still got the same error.   

I'm think that either these files are either copied again during the build, or there is another problem causing this error.

I think I'm going to try to rerun the build  with the last successful revision, and see if there are any other obvious differences.   I'll also check the path lengths to see how much difference there actually was with the new packages.

**Comment by JoelProminic** [comment]
I didn't have a reliable way to check the file lengths on the server, so I checked the files in MoonshineSharedCore/src/elements instead:

Last successful revision:   66460145ed5719866c367d04471c471131732eca

    This is the longest line, with 162 characters:  
    ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/out/src/chrome/crdpMultiplexing/webSocketToLikeSocketProxy.js.map

First failed revision:  bc4ec65b097e72b218108f5e2f5e03775b87cdc9

    This is the longest line, with 162 characters:  
    ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/out/src/chrome/crdpMultiplexing/webSocketToLikeSocketProxy.js.map

Current state of features/issue_662_shorten_ant_path:  

    This is the longest line, with 161 characters:  
    ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/i18n/chs/out/src/transformers/baseSourceMapTransformer.i18n.json


So, the file paths didn't get longer for the build that broke.  The only changes I saw were with files with much shorter paths

    $ diff <66460145ed5719866c367d04471c471131732eca_files> <bc4ec65b097e72b218108f5e2f5e03775b87cdc9_files> 
    319,326d316
    < ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/glob
    < ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/glob/LICENSE
    < ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/glob/README.md
    < ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/glob/changelog.md
    < ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/glob/common.js
    < ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/glob/glob.js
    < ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/glob/package.json
    < ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/glob/sync.js
    689a680,688
    > ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/node_modules
    > ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/node_modules/glob
    > ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/node_modules/glob/LICENSE
    > ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/node_modules/glob/README.md
    > ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/node_modules/glob/changelog.md
    > ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/node_modules/glob/common.js
    > ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/node_modules/glob/glob.js
    > ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/node_modules/glob/package.json
    > ide/MoonshineSharedCore/src/elements//chrome-debug-adapter/node_modules/vscode-chrome-debug-core/node_modules/glob/sync.js
    2184,2185d2182

**Comment by JoelProminic** [comment]
I vaguely remember that we saw this error when there was a problem with using 32-bit or 64-bit binaries.  Unfortunately, I couldn't find any notes about this in the GitHub issues or Prominic JIRA.

I see we also got this error in #444, but we never reported a solution.

**Comment by joshtynjala** [comment]
There are all of the issues where we've talked about this error: #379 #444 #643

It seems to always involve a file that the AIR packager doesn't like. Maybe it's not the length of the absolute path, but some other factor that we haven't determined yet.

**Comment by joshtynjala** [comment]
> First failed revision: bc4ec65

Just one clarification, so that we have the correct commit recorded here. I made several commits that day, and I pushed them all at once. I'm certain that the actual commit that broke Bamboo builds is this one: 45869e5a4bacb7fb9b5e19d9e146e56c459478cd

**Comment by joshtynjala** [comment]
I deleted a bunch of files that aren't strictly necessary for chrome-debug-adapter. Let me know if that makes any difference.

I suppose that there's a chance that the length of an individual file name matters. If it matters, this removes the longest, which was 49 characters (hitCountBreakpointsDifferentOperators.test.js.map). The longest now is 39 characters (chromeTargetDiscoveryStrategy.test.d.ts).

Judging by the name chromeTargetDiscoveryStrategy.test.d.ts, it looks like I may be able to find some more files to remove. However, we might as well wait to see if the current change is good enough or not.

**Comment by JoelProminic** [comment]
Yeah, I saw that there were multiple commits related to that failed build.   I took the one reported by Bamboo, which I expected to be the last revision.   I ran a test with 45869e5a4bacb7fb9b5e19d9e146e56c459478cd, and I see the same path length.

I see your latest update was on the master branch.  Unfortunately, I see the same error in the Bamboo build.

**Comment by rat-moonshine** [comment]
What is the possibility to bundle the files for chrome-debugger in a Zip and expand them during Moonshine startup? It is inevitable that it is failing when its bundling the 'elements' folder.

**Comment by JoelProminic** [comment]
I have a working Windows 7 remote agent now.  I'm still debugging some errors related to the Flex SDK, but I should be able to try the full build after that.

**Comment by JoelProminic** [comment]
Hooray!  The Windows build is finally available again here:  https://moonshine-ide.com/downloads/releases/dev/windows/

I'll plan to update CHANGELOG.md and start working on the final testing tomorrow.

It seems that FLEX_HOME was read from the system environment variables on the Windows 7 remote agent, which is not good practice.  I have a temporary solution for now, but I'll revisit this tomorrow.

**Comment by JoelProminic** [comment]
I cleaned up the FLEX_HOME environment variable and some other issues I encountered with the Windows Bamboo builds, and I think this engine is in good shape now.  I'll discuss some of the Bamboo changes separately with @rat-moonshine.   I'm working on some CHANGELOG updates and testing for 2.5.1 now.
