### ISSUE TITLE
Detect IBM/HCL Notes Client for Domino Support

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#667]
In order to use Domino tools like DXL Importer (#668) or On Disk Project (#669, #670, #646), the user needs to have the Notes client installed at a location where Moonshine can access it.

This is similar to the checks we do for SDKs with Getting Started.   Nowever, we can't automate the install of IBM/HCL Notes on a workstation, so we just want to find and save the path.

The expected directories are:

    # macOS
    /Applications/IBM Notes.app/
    /Applications/HCL Notes.app/

    # Windows
    C:\Program Files (x86)\IBM\Notes
    TODO:  HCL

The App Store build won't be able to access these directories without a bookmark, so we will need a settings page where they can can select the path.  This should be in the other builds as well, but we expect it to be populated by default.

I'll give the details for how to use this path in the related issues above.

Some other checks we may need to do:
- Check the Notes client version.   If it matters, we'll focus our support on the latest version 11.0
- Check if the Notes client is setup properly to allow DXL Importer or other tools access without a password.  I'll think about whether I can make a script for this.

**Comment by rat-moonshine** [comment]
I think I misunderstood Notes with Nodes when @JustinProminic mentioned about this in Getting Started page, which completed as https://github.com/prominic/Moonshine-IDE/issues/661 in branch.

**Comment by rat-moonshine** [comment]
Are we need two separate entries or one, in Getting Started page?

> # macOS
> /Applications/IBM Notes.app/
> /Applications/HCL Notes.app/

**Comment by rat-moonshine** [comment]
Codes adjusted and tested both on Windows and macOS. While on Windows it suppose to detect by following two default locations:

```
C:\Program Files (x86)\IBM\Notes
C:\Program Files (x86)\HCL\Notes (I don't know if this right, please provide correct path if this is wrong in case of HCL)
```

On macOS, this suppose to test following two locations:

```
/Applications/IBM Notes.app/
/Applications/HCL Notes.app/
```

On macOS, a permission access will be ask through Getting Started window, as we have permission request for Git/SVN on macOS.

**Comment by JoelProminic** [comment]
I tested this from a branch build.

Some minor text updates - I may request further changes after reviewing with @JustinProminic:

Update the Getting Started By Feature entry to:

> Domino Support
> Use Domino On Disk Projects and import Java agents

Update the "Notes Domino" settings page:
- Change the name to "Domino"
- Change the description to "IBM/HCL Domino Integration"
- Change the field label from "IBM/HCL Notes Executable" to "IBM/HCL Notes Installation" to emphasize that this is a directory rather than the executable itself.


I get this prompt when clicking the configure icon on the Getting Started path for both the App Store and non-Sandbox builds.  This is not needed for non-Sandbox, since we don't need a bookmark to acess the directory.

![image](https://user-images.githubusercontent.com/24532731/75704533-28015780-5c7f-11ea-8330-143d66e6b06c.png)

Change the text to:

> In order to use the Domino Integration features, you must grant Moonshine permission to access the IBM Notes installation.
> 
> Click Allow Access to open the application shown below. Then click "Open" to grant access.  
> 
> /Applications/IBM Notes.app

@rat-moonshine and I also discussed some behavior issues with the file chooser.  The behavior changes with the Finder view mode that is selected by the user:
![image](https://user-images.githubusercontent.com/24532731/75704565-35b6dd00-5c7f-11ea-993d-e1cbb17b01b6.png)
![image](https://user-images.githubusercontent.com/24532731/75704594-41a29f00-5c7f-11ea-94bc-d15dc5f566f6.png)

Only the third view mode (from the second screenshot) enables the Open button.  The other views show the contents of IBM Notes.app, and there is no .app file to select (see the first screenshot).

We need to make sure that this will work for all four view modes.  We may need to experiment with a custom filter using [FileFilter](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/FileFilter.html).

**Comment by rat-moonshine** [comment]
- Minor textual changes have done
- Notes-permission window now appear only in App Store version of Moonshine

**Comment by JoelProminic** [comment]
Getting Started window doesn't appear on startup when IBM/HCL Notes is detected, but access is not granted.  I'll discuss with @JustinProminic whether this is desired - not all users will want this.

The text on the Allow Access prompt was not update:
![image](https://user-images.githubusercontent.com/24532731/75798769-a839c280-5d3c-11ea-8c0b-d02ebf50c58a.png)

In the AppStore version, the FileChooser opens to whichever directory was last accessed, rather than to /Applications/IBM Notes.app.   If we can't avoid this, then the FileFilter logic discussed above may not matter, since the user would need to manually browse to IBM Notes.app anyway.

The Allow Access prompt no longer appears on the non-Sandbox build, but I still see the warning icon on the Getting Started page:

![image](https://user-images.githubusercontent.com/24532731/75798739-9fe18780-5d3c-11ea-924e-d535b5b98658.png)

**Comment by rat-moonshine** [comment]
> Getting Started window doesn't appear on startup when IBM/HCL Notes is detected, but access is not granted. I'll discuss with @JustinProminic whether this is desired - not all users will want this.

I'm not sure if I successfully able to test this case - as Getting Started opens for me if an item has pending download and 'do not show again' checkbox is not selected, during my tests. 

> The text on the Allow Access prompt was not update:

Texts have updated.

> The Allow Access prompt no longer appears on the non-Sandbox build, but I still see the warning icon on the Getting Started page:

Showing of warning now adjusted. Please, check.

**Comment by JustinProminic** [comment]
We need to avoid using the trademark name IBM anymore.   Only HCL should be used.  And it should be like this:  HCL (R) Notes / Domino.   Don't make it say in pop-up boxes and configuration screens IBM / HCL.  Just use HCL only.

**Comment by JoelProminic** [comment]
Besides the change from @JustinProminic's comment above, the updates looked good in my test.

**Comment by rat-moonshine** [comment]
IBM references now removed from Moonshine and Moonshine-SDK-Installer.

**Comment by rat-moonshine** [comment]
I had an extensive tests which I'm going to update here. For now, a link only which I'll discuss.

https://apple.stackexchange.com/questions/62410/how-can-i-open-a-folder-called-something-app-in-various-applications

**Comment by JoelProminic** [comment]
In order for the user to do a DXL Import (#668) or On Disk Project (#646, #669) without entering their Notes password, they need to update a setting in the Notes client.  I'd like to provide some guidance for the users when they set up the Notes path.

For now, I'd like to add a writeup like this to the Domino Settings page.  If it doesn't fit well within the page, you can have it open with a link like "Enable passwordless access."

> In order to run HCL Notes operations from Moonshine, you need to enable a Notes setting that will allow local applications to run without your password.  *Note that your Notes client must still be open, authenticated, and unlocked in order for this setting to work.*
> 1. Open HCL Notes > Security > User Security... (or File > Security > User Security... for older versions)
> 2. Enter your Notes Password
> 3. In the Security Basics tab, enable the "Don't prompt for password from other Notes-based programes" checkbox setting.
> 
> ![image](https://user-images.githubusercontent.com/24532731/76873592-eacec500-683b-11ea-8fa7-6559edf295cb.png)
> 
> If you do not wish to enable this setting, then you can still run the Maven or Ant scripts from a Terminal or Command Prompt and enter the password manually.

If the user does not include this setting, they'll see the script hang with a password prompt (and in some cases, the prompt might be buried in other text).

I'll look into how we can make the operations fail in a clearer way.  If we can detect the problems automatically, we can display a message like this:

    ERROR:  Missing password.  To fix this, follow the instructions at Moonshine > Settings > Domino, or run this command from a Terminal or Command Line:  <command>

**Comment by rat-moonshine** [comment]
Above instruction added into Domino settings view.

**Comment by rat-moonshine** [comment]
This issue is now merged into 'master'.

**Comment by piotrzarzycki21** [comment]
If that issue involves update to Installer please send me link for newest version. I'm closing issue.

**Comment by rat-moonshine** [comment]
> If that issue involves update to Installer please send me link for newest version. I'm closing issue.

Branch for Moonshine SDK Installer also merged into 'master'. So you should access the functionality with new usual build.

**Comment by piotrzarzycki21** [comment]
> > If that issue involves update to Installer please send me link for newest version. I'm closing issue.
> 
> Branch for Moonshine SDK Installer also merged into 'master'. So you should access the functionality with new usual build.

Ahh!! Sorry I forgot that we have now automatic build of Installer ;) Thanks!
