### ISSUE TITLE
Domino On Disk Project Examples

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#669]
We would like to have a Domino On Disk Project template that we can use to create a new local Domino database from Moonshine.  We have done some work with this for #646 already, but we want to separate this out from the Visual Editor code for now.  

The example template should have a simple "Hello, World!" example of each design element type, including:
- Form
- View
- Subform
- Page
- XPage and SSJS - Added by @dpastov 2020/03/06
- Shared action
- Java agent
- Java script library
- Lotusscript agent
- Lotusscript script library
- Outline
- etc.

In addition, we should provide some useful views.  These should have web access disabled by default.
- All By UNID
- All By UNID/By Creation Date
- All By UNID/By Form Used
- All By UNID/By Last Modified
- etc.

And we also want some useful shared actions for forms and views.  This can be used for the forms and views generated by #670.

We should try to minimize Prominic references in the database code.  

In general, we should use good practices for all of the example elements.  We should include good security practices as well, but some of this will require the user to configure the ACL appropriately for their application and environment.

We may want to consider providing a template for an empty database as well, but we can revisit this after we have the main template done.

Note that the DXL Import project (#668) should not be based on this template - it is designed to run in a Java project instead.

**Comment by JoelProminic** [comment]
I have a basic database created for this in Domino Designer.  I will review this with @JustinProminic and send an official copy when this is read.

The database is here (requires Prominic database access):
Server:  domino-49.prominic.net
Database:  MoonshineExampleODP.nsf

**Comment by JustinProminic** [comment]
@JoelProminic please update this location above to reflect that the master database is now on @dpastov server.

**Comment by JustinProminic** [comment]
@dpastov will add an XPages example for us, and I will add other things I think are useful to the traditional forms and views.   FYI @JoelProminic

**Comment by JoelProminic** [comment]
I experimented with exporting the test database from Domino.  

To do this, I selected the database in Domino Designer, and opened File > Team Development > Set Up Source Control For This Application.  When selecting a project path, keep in mind that the database subfolders will be created directly under the selected directory.

The resulting files look like files in nsfs/nsf-moonshine/odp/. I think we can use the rest of the files as a base template for the Maven wrapper.

The Database details are stored in AppProperties/database.properties:

    <database xmlns='http://www.lotus.com/dxl' version='9.0' maintenanceversion='1.10'
     replicaid='-replicaid-' path='C:\Flex\workspace\odp\DominoExport\JoelTest1_MoonshineExampleODP.nsf'
     title='JoelTest1 - Moonshine Example On Disk Project' increasemaxfields='true'>
    <databaseinfo dbid='-replicaid-' odsversion='52' diskspace='847872' percentused='90.8816425120773'
     numberofdocuments='7'>

I see most of these properties were stripped out in the official example:

    <database xmlns="http://www.lotus.com/dxl" title="NSF ODP Tooling Example" increasemaxfields="true">
      <databaseinfo/>


Once we have a proper exported example, we'll need to go through and add insertion parameters so that the user can customize the name.

Some other changes:
- make sure that the ACL is generic and has sensible defaults for a user trying to create a brand new database.

**Comment by JoelProminic** [comment]
Here is a breakdown of the required files for the On Disk Project template.  You'll see some extra files in @feather812002's template, but I think we can narrow it down to just these files (plus any additional files we need to add for #670 or #646)

File | Notes
-----|------
nsfs | directory for the on disk projects (only one for now)
nsfs/<db-project-name>/ | maven wrapper for the On Disk Project.  This design can support multiple on disk projects, but I plan to only support one for now
nsfs/<db-project-name>/build.properties | TODO:  does this require any updates for the template?  
nsfs/<db-project-name>/META-INF/MANIFEST.MF | TODO: references the project name - needs more investigation
nsfs/<db-project-name>/odp | DXL files representing the forms, views, etc.  These could be edited directly if desired, but it would only be practical for very simple changes.
nsfs/<db-project-name>/pom.xml | database-specific configuration
pom.xml | general configuration.

I expect these actions for On Disk Projects:
- Create a new On Disk Project
- Update the Domino database at the configured location from the project (mvn install)
- Update the On Disk Project from the Domino database (TODO)
- Add a new "Tabular Interface" form (#670)
- Add a new Visual Editor form (#646)
- Update and regenerate a "Tabular Interface" form.  This will overwrite any Domino Designer changes
- Update and regenerate a Visual Editor form.  This will overwrite any Domino Designer changes
- Edit the DXL directly (for advanced users)

**Comment by piotrzarzycki21** [comment]
> I experimented with exporting the test database from Domino.
> 
> To do this, I selected the database in Domino Designer, and opened File > Team Development > Set Up Source Control For This Application. When selecting a project path, keep in mind that the database subfolders will be created directly under the selected directory.
> 
> The resulting files look like files in nsfs/nsf-moonshine/odp/. I think we can use the rest of the files as a base template for the Maven wrapper.
> 
> The Database details are stored in AppProperties/database.properties:
> 
> ```
> <database xmlns='http://www.lotus.com/dxl' version='9.0' maintenanceversion='1.10'
>  replicaid='-replicaid-' path='C:\Flex\workspace\odp\DominoExport\JoelTest1_MoonshineExampleODP.nsf'
>  title='JoelTest1 - Moonshine Example On Disk Project' increasemaxfields='true'>
> <databaseinfo dbid='-replicaid-' odsversion='52' diskspace='847872' percentused='90.8816425120773'
>  numberofdocuments='7'>
> ```
> 
> I see most of these properties were stripped out in the official example:
> 
> ```
> <database xmlns="http://www.lotus.com/dxl" title="NSF ODP Tooling Example" increasemaxfields="true">
>   <databaseinfo/>
> ```
> 
> Once we have a proper exported example, we'll need to go through and add insertion parameters so that the user can customize the name.
> 
> Some other changes:
> 
> * make sure that the ACL is generic and has sensible defaults for a user trying to create a brand new database.

@rat-moonshine Very first point is something which I envision to do by you. We need new type of project. That point in theory doesn't need code from Bing's work, it needs only his template files of Visual Editor - which is going to be copied and changed into On Disk Project.

**Comment by piotrzarzycki21** [comment]
> * Add a new "Tabular Interface" form (#670)
> * Add a new Visual Editor form (#646)

@JoelProminic This two points are crucial and my next question may have been asked already on a call. I may have repeat them here just to make sure that my direction when I start coding is the right one. 
Does On Disk Project gather two type of form creation ? I thought that Visual Editor (#646) will eventually have second option - Create Tabular interface or something like that later once On Disk Project will be ready to go.

**Comment by rat-moonshine** [comment]
I spent quite some time today understanding/reading-through how Domino is in Moonshine IDE. I see I have been away for quite some time from related discussion on this (#646 , #668 , #669, #670 ), which became inevitable for me to understand what we already have and what we will need, before jumping into any implementation.

Reading through the discussion helped me to clear my understanding to an extent, which were basically filled with questions.

I also tried to give a test to Bing's branch-build (#646 ). Unfortunately, I couldn't able to complete to .nsf generation due to many an errors. We tried to address the errors with @feather812002 however no success so far. 

I still have some questions related to Domino on Disk. Hopefully I shall able to discuss them with @JoelProminic tonight.

**Comment by piotrzarzycki21** [comment]
> I still have some questions related to Domino on Disk. Hopefully I shall able to discuss them with @JoelProminic tonight.

Maybe ask them here, since I will be working on Tabular interface so I would not be completely blind with any of your issue.

**Comment by rat-moonshine** [comment]
I talked to @JoelProminic in length on different queries those I have, mostly to confirm my understanding from the issue readings, and some other queries on how-to things.

As I understood correctly, we'll probably going to need an exclusive project-type for Domino On Disk having ability of visual-editor (for #646 ) and tabular-forms (#670 ). Both the form types will generate DXLs. 

Being said 'exclusive', we'll probably create this as a new project-type (separated from creating as a "Visual Editor Project" type option) and show as a new type-option in home screen of Moonshine-IDE. Since the said new project type will also require visual-editor abilities, it will be a visual-editor type of project but with different project extension preferably (i.e. `ondiskproj.as3proj`). The project should generate taking Bing's file (those @JoelProminic mentioned at [here](https://github.com/prominic/Moonshine-IDE/issues/669#issuecomment-597925945)). 

@piotrzarzycki21 do you see the above assumption fits your idea of having a separate type of project? Or, you have other suggestion which I might failed to understand.

**Comment by JoelProminic** [comment]
I discussed the On Disk Project with @rat-moonshine today, and I wanted to document some of my thoughts.   Here is a mockup of how the project structure might look.  Note that this is not finallized - it is more to present the current ideas I have for feedback.   Soem clarifications
- "Form Builder" refers to #670.  I don't like the "Tabular Interface" name, so I'm trying another name for now.  I highlighted the associated files in Red
- "Visual Editor" refers to #646.  I highlighted the associated files in Blue
- The "nsf" directory should be "nsfs"

![image](https://user-images.githubusercontent.com/24532731/76572093-18f08580-6487-11ea-940b-7ed02d75d830.png)

With this design, the user will update the Form Builder and Visual Editor forms from the src directory only.   I split this into multiple subdirectories for now, but we could also distinguish the files with different extensions (i.e. .dfb and .dve, respectively).  Double-clicking FormBuilderExample.form will open the Form Builder interface (#670), while VisualEditorExample.form will open the Visual Editor interface.

The intermediate files for Form Builder and Visual Editor will be stored in formbuilder-src and visualeditor-src, respectively.  These directories should be hidden so that they are not edited directly.  

The actual form DXL needs to be placed in nsfs/nsf-moonnshine/odp/Forms so that it can be imported to a Notes Database.  Also note that the user can then edit the form in Domino Designer and export it back to this file, so these files will not necessarily match up with the intermediate XML files.   The .form files can be edited directly, but this will only be practical for simple changes or advanced users.

TemplateExample.form is a form included in the template, so it has neither form type.  It can only be edited as DXL or with Domino Designer.

Alternatively, we could allow the user to double-click on the forms in nsfs/nsf-moonnshine/odp/Forms and open the associated editor.  @feather812002's implemenation in #646 works like this.
- FormBuilderExample.form - the FormBuilder form
- TemplateExample.form - Text editor
- VisualEditorExample.form - Visual Editor

However, this has some problems
- It ignores the problem that the .form file may have local changes that will be lost
- I think it may be confusing for the user if the .form files open in different ways in the same directory.

**Comment by rat-moonshine** [comment]
> The actual form DXL needs to be placed in nsfs/nsf-moonnshine/odp/Forms so that it can be imported to a Notes Database. Also note that the user can then edit the form in Domino Designer and export it back to this file, so these files will not necessarily match up with the intermediate XML files. The .form files can be edited directly, but this will only be practical for simple changes or advanced users.
> 
> However, this has some problems
> 
> - It ignores the problem that the .form file may have local changes that will be lost
> - I think it may be confusing for the user if the .form files open in different ways in the same directory.

Yes, I see the advantage and related problems to this design. 

Generally, double-clicking an exported file (i.e. nsfs/nsf-moonnshine/odp/Forms/VisualEditorExample.form) locates its corresponding code/XML file inside 'visualeditor-src' and opens as mockup-editor. Having the .form file edited/updated externally means the file inside 'visualeditor-src' will have sync issue. 

Perhaps, in that case a file timestamp checks between both files may help (as we did for #633 ). Now we need to think what action(s) we want to offer to the user if we found a sync problem.

Overall, the design looks pretty clean and fantastic.

**Comment by piotrzarzycki21** [comment]
> The actual form DXL needs to be placed in nsfs/nsf-moonnshine/odp/Forms so that it can be imported to a Notes Database.

I don't understand this one - if in the end whatever we create in src folder has to be in /odp/Forms - what is the point of having src folder at all? Shouldn't Forms be an src folder actually ?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Your work would be reach the point where user is able to open stuff by double clicking - I will handle part where user see real features for "Form Builder" (Tabular interface).

**Comment by rat-moonshine** [comment]
> > The actual form DXL needs to be placed in nsfs/nsf-moonnshine/odp/Forms so that it can be imported to a Notes Database.
> 
> I don't understand this one - if in the end whatever we create in src folder has to be in /odp/Forms - what is the point of having src folder at all? Shouldn't Forms be an src folder actually ?

/odp/Forms can be updated by external sources (or say, by a database). If we manage same file also for Moonshine visual-editor changes, those changes can lost. Thus, having a separate intermediate file managing the Moonshine visual-editor changes (src/main/formbuilder/..) may save this situation.

However, there are certain update-sync problem can arise which Joel already pointed in his comment.

**Comment by rat-moonshine** [comment]
(I forgot to reference some commits which we can find here https://github.com/prominic/Moonshine-IDE/commit/2509c6fbb968609308665cbdfa0052c5483a14fe)

I see @joshtynjala has introduced some flexible and modular system to introduce new project types to Moonshine (which he used again Haxe, Groovy etc.). I followed the path to introduce the new On Disk Project type, as well.

One thing we need to decide, how we going to introduce @feather812002 's implementation (#646 ) to this new project source. I'm not yet came to the steps where we shall be needing to look into #646 functional implementation, but mostly dealing with creating new project container to have it avail in Moonshine along with its regular tasks like create/import, menu, configuration-updates etc.

So far here are the updates until now and upcoming tasks:

- [x] Creation of new project type supporting the design as suggested by Joel
- [x] Template project containing '`nsfs`' template files from #646 
- [x] Project Creation and Import/Open
- [x] Configuration file update during import/export
- [x] New menu generation 
- [x] Enable/disable menu based on project's type
- [ ] Some bug-fixing (i.e. showing up _Source_ icon during project creation)
- [ ] Cleanup of OnDiskProjectVO - it contains copied content from Haxe
- [ ] Cleanup any other files that may needs
- [ ] Update ODP and wrapper from @JoelProminic 
- [ ] New file creation (?)
- [ ] Opening of visual-editor tab on clicking of .dve and .dfb files (from #646 ?)

**Comment by JoelProminic** [comment]
Sorry @rat-moonshine, I meant to give you the updated template files before you started working on the templates.

Here are the files for the Maven wrapper:
[2020_03_13__ODP_Wrapper.zip](https://github.com/prominic/Moonshine-IDE/files/4331918/2020_03_13__ODP_Wrapper.zip)

My updates are: 
- Removed `releng` - this is an unnecessary update site module from the original demo (I actually never got this working properly on my side)
- Updates the two pom.xml files to remove references to `releng`
- removed `nsfs/nsf-moonshine/odp` - this will be populated with the second zip below

Be careful not to include ./target or ./nsfs/nsf-moonshine/target when you create the template, since these will be populated by Moven.  

Here is an initial version of the example project.  These files should be placed in the above framework `nsfs/nsf-moonshine/odp`, so that `nsfs/nsf-moonshine/odp/Forms` has the example form.
[2020_03_13__Example_ODP.zip](https://github.com/prominic/Moonshine-IDE/files/4331919/2020_03_13__Example_ODP.zip)


Here are some additional notes from my side, so that I can remember how I generated the Example ODP later:  

To generate the example On Disk Project from an NSF, I ran `File > Team Development > Set Up Source Control For This Application` from the Domino Designer menu.

The only file I saw that required cleanup was `odp/AppProperties/database.properties`.  I replaced the `database`, `databaseinfo`, and `acl` sections like this.  Some notes:
- "adminserver" is a Prominic server currently (domino-49.prominic.net).  I'm not sure how to handle this in a generic way, so I'll revisit it up later (the server will not be exposed to general users).   Otherwise, I stripped all Prominic references out of the ACL:
- The `title` section in `<database>` and the `$TITLE` item below should eventually be updated to an insertion parameter to use the template name.  We'll also need to update the .nsf name, but this is currently built with a version number using the Maven properties

    <database xmlns="http://www.lotus.com/dxl" title="Moonshine Example On Disk Project" increasemaxfields="true">
      <databaseinfo/>
    <acl adminserver='CN=domino-49.prominic.net/O=PNI' maxinternetaccess='editor'>
    <aclentry name='-Default-' default='true' level='noaccess' readpublicdocs='false'
     writepublicdocs='false'/>
    <aclentry name='OtherDomainServers' type='servergroup' level='noaccess' readpublicdocs='false'
     writepublicdocs='false'/>
     deletedocs='true'/>
    <aclentry name='Anonymous' level='editor' deletedocs='true' createpersonalagents='true'
     createpersonalviews='true' createsharedviews='true' createlsjavaagents='true'/>
     deletedocs='true'/>
    <aclentry name='LocalDomainAdmins' type='persongroup' level='manager' deletedocs='true'/>
    <aclentry name='LocalDomainServers' type='servergroup' level='manager' deletedocs='true'/>
     deletedocs='true'/>
    </acl>


I also updated the title at the bottom of `odp/AppProperties/database.properties`:

    <item name='$TITLE'><text>Moonshine Example On Disk Project</text></item></note>


I got this error when testing the template:

    Compiling Java source
    - Compiling no classes
    Uninstalling bundles

    !ENTRY org.eclipse.osgi 4 0 2020-03-13 17:06:40.064
    !MESSAGE Application error
    !STACK 1
    java.util.concurrent.ExecutionException: java.lang.IllegalStateException: no source files


It seemed that a Maven task was failing because there were no Java files to compile.  I need to review this more, but to get the demo working I added a placeholder Java file in odp/Code/Java/demo/Placeholder.java

```
package demo;

public class Placeholder {
    /*
     * This is an example class compiled with the On Disk Project.
     * Without at least one class in odp/Code/Java, Maven throws an error.
     * This may be removed later if it is no longer necessary
     */

}
```

**Comment by piotrzarzycki21** [comment]
> * Opening of visual-editor tab on clicking of .dve and .dfb files (from #646 ?)

I'm not sure what do you mean here - what are those files ?

**Comment by rat-moonshine** [comment]
> > * Opening of visual-editor tab on clicking of .dve and .dfb files (from #646 ?)
> 
> I'm not sure what do you mean here - what are those files ?

It is described [here](https://github.com/prominic/Moonshine-IDE/issues/669#issuecomment-598460642) by Joel.

**Comment by piotrzarzycki21** [comment]
> It is described [here](https://github.com/prominic/Moonshine-IDE/issues/669#issuecomment-598460642) by Joel.

Ok I got it, so you will distinguish for simplicity files to have different extension in "formbuilder" and "visualeditor" folders ?

**Comment by rat-moonshine** [comment]
> > It is described [here](https://github.com/prominic/Moonshine-IDE/issues/669#issuecomment-598460642) by Joel.
> 
> Ok I got it, so you will distinguish for simplicity files to have different extension in "formbuilder" and "visualeditor" folders ?

Yeah, that is the idea. But one can generate those files behind 'formbuilder' or 'visualeditor', or can chose to delete those folders and create any new, in that case different extensions will handy.

**Comment by rat-moonshine** [comment]
I noticed some oddity during my tests with Maven builds I thought to document them here. 

While running the _pom.xml_ file by `Projects -> Build with Apache Maven`, I see the process starts and console populates with its output. However, I'm not super sure how this collect information of an _.id_ file located somewhere in my system and tries to use it against HCL Notes installation: 

```
: Compiling Java source
: - Compiling  1 class
: Compiling custom controls
: Compiling XPages
: Creating destination NSF
: Importing DB properties
: [000835:000002-0000070000DBE000] The ID file being used is: /Users/$user/gbauth_kit/user.id
```

I confirm the _.id_ file location is valid, however I'm not sure if this an updated id file. Process halts by the above last line and never proceed anymore. 

While running `mvn install` on Terminal I also faced the similar issue, accidentally I found that if I input my current HCL Notes password while it stuck to that line, progress continues thereafter. However, the prompt is not clear that I need to input a password or the current password in _.id_ file mismatch.

@JoelProminic I hope you're aware of this scenario (?)

**Comment by rat-moonshine** [comment]
Okay. Here's a few things I would like to take in your attention @piotrzarzycki21 , as you're going to take on these next.

File creation now handles by the respective type's plugin class for On Disk Project other than crowding the _TemplatingPlugin_ class anymore. Currently, I'm only populating basic file-templates under `src/main` - you may need to extent the functionalities while file-creation at [here](https://github.com/prominic/Moonshine-IDE/blob/features/issue_669_domino_on_disk/ide/MoonshineSharedCore/src/actionScripts/plugin/ondiskproj/OnDiskProjectPlugin.as#L130) along with corresponding _.form_ file generation under `nsfs/nsf-moonshine/odp/Forms`.

Since you are more knowledgeable on visual-editor part, I need you to review on this following changes. 

Until now visual-editor expects an `AS3ProjectVO`. Now we also has `OnDiskProjectVO`. I didn't wanted to extend the latter with former, so we can keep the object simpler (by its properties). So I introduced some changes, you take a look and let me know if this has any larger effect.

1. [IVisualEditorProjectBridgeImpl](https://github.com/prominic/Moonshine-IDE/blob/features/issue_669_domino_on_disk/ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IVisualEditorProjectBridgeImpl.as#L35) now accepts `ProjectVO` instead of `AS3ProjectVO`
2. Both `AS3ProjectVO` and `OnDiskProjectVO` now implements [IVisualEditorProjectVO](https://github.com/prominic/Moonshine-IDE/blob/features/issue_669_domino_on_disk/ide/MoonshineSharedCore/src/actionScripts/interfaces/IVisualEditorProjectVO.as) - my idea that we keep the visual-editor projects' properties here (we may need to populate the interface with more fields)
3. Having the above change in place, `VisualEditorViewer` now refers to access the said interface methods in [this](https://github.com/prominic/Moonshine-IDE/blob/features/issue_669_domino_on_disk/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ui/editor/VisualEditorViewer.as#L86) way where it may requires

Having the above changes in place, opening any dfb/dve files now opens the Flex/PrimeFaces visual-editor window - this we'll need to adjust eventually to open with OnDisk component developed in #646 . 

Let me know your thoughts.

**Comment by piotrzarzycki21** [comment]
> * [IVisualEditorProjectBridgeImpl](https://github.com/prominic/Moonshine-IDE/blob/features/issue_669_domino_on_disk/ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IVisualEditorProjectBridgeImpl.as#L35) now accepts `ProjectVO` instead of `AS3ProjectVO`
> * Both `AS3ProjectVO` and `OnDiskProjectVO` now implements [IVisualEditorProjectVO](https://github.com/prominic/Moonshine-IDE/blob/features/issue_669_domino_on_disk/ide/MoonshineSharedCore/src/actionScripts/interfaces/IVisualEditorProjectVO.as) - my idea that we keep the visual-editor projects' properties here (we may need to populate the interface with more fields)
> * Having the above change in place, `VisualEditorViewer` now refers to access the said interface methods in [this](https://github.com/prominic/Moonshine-IDE/blob/features/issue_669_domino_on_disk/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ui/editor/VisualEditorViewer.as#L86) way where it may requires

In reality I will start looking into this tomorrow if you really finished your part, but one thing comes to my mind. How above changes influence Bing's work ? I would maybe try merge his branch into yours or even make completely new out of master and merge yours and his branch to see what will happen. I think we should do that before we end up with some conflict for couple of days.

**Comment by rat-moonshine** [comment]
Well I afraid we can't do a straight-forward merge in this case. As I understood, we probably require to cherry-pick functionalities developed in #646 - remember, we have a different project-type with its associated resources now, other than implementing through same old AS3Project ways. 

But yes, you wants to take your time to look through these.

**Comment by piotrzarzycki21** [comment]
> Well I afraid we can't do a straight-forward merge in this case. As I understood, we probably require to cherry-pick functionalities developed in #646 - remember, we have a different project-type with its associated resources now, other than implementing through same old AS3Project ways.
> 
> But yes, you wants to take your time to look through these.

Well I do not recommend to make cherry pick in case where you have more than 1-2 commits. The only way to make those branches work together is normal merge and work with Bing on each conflict.

**Comment by rat-moonshine** [comment]
Standard merges I believe is way to go for visual-editor library projects (for both converter and visual). In case of Moonshine a direct merge won't help because the ways we have changed, by introducing new project type, new plugin and VOs.

**Comment by piotrzarzycki21** [comment]
> Standard merges I believe is way to go for visual-editor library projects (for both converter and visual). In case of Moonshine a direct merge won't help because the ways we have changed, by introducing new project type, new plugin and VOs.

Are you saying about applying changes one by one ? :) I really want to see with what kind of stuff you were dealing with in history and what kind of changes where done by Bing at the end of the merge, so I cannot image do that the way you are I think proposing - No matter how easier it would be.

**Comment by rat-moonshine** [comment]
I'm guessing more than proposing. Since the many new changes in Moonshine that may differ than the way domino-editors opened and managed _in_ Moonshine. Honestly, I also don't has a clear idea as I didn't look through the codes from #646 but introduced only a new type in #669. 

Being said that, whichever ways that fit best I'm fine with it.

**Comment by JoelProminic** [comment]
> I noticed some oddity during my tests with Maven builds I thought to document them here.
> 
> While running the _pom.xml_ file by `Projects -> Build with Apache Maven`, I see the process starts and console populates with its output. However, I'm not super sure how this collect information of an _.id_ file located somewhere in my system and tries to use it against HCL Notes installation:
> 
> ```
> : Compiling Java source
> : - Compiling  1 class
> : Compiling custom controls
> : Compiling XPages
> : Creating destination NSF
> : Importing DB properties
> : [000835:000002-0000070000DBE000] The ID file being used is: /Users/$user/gbauth_kit/user.id
> ```
> 
> I confirm the _.id_ file location is valid, but I'm not sure if this an updated id file. Process halts by the above last line and never proceed anymore.
> 
> While running `mvn install` on Terminal I also faced the similar issue, accidentally I found that if I input my current HCL Notes password while it stuck to that line, progress continues thereafter. At this stage, the prompt is not clear that I need to input a password or the current password in _.id_ file mismatch.
> 
> @JoelProminic I hope you're aware of this scenario (?)

Sorry, I forgot about this case, since I already have the corresponding setting enabled.  I wrote up some instructions [here](https://github.com/prominic/Moonshine-IDE/issues/667#issuecomment-600141650).

**Comment by JoelProminic** [comment]
I'd prefer to hold off on merging @feather812002' changes from #646, since the visual editor work may need more time to complete.   Focus on #670 now for this template.

That said, I understand if we need to do plan ahead about how these projects will need to be merged.

**Comment by JoelProminic** [comment]
> : [000835:000002-0000070000DBE000] The ID file being used is: /Users/$user/gbauth_kit/user.id

Since the ID file is referenced in the On Disk Project startup, I'm wondering if we'll need to setup a bookmark for this for the App Store version.

I'd like to avoid requiring the user to configure this in the Domino Settings page since:
- This is only required for the App Store version
- The ID file path shouldn't be directly required for anything else that Moonshine does
- Even if we had an ID file path, I don't think Notes will let us overwrite the ID file that it uses.

**Comment by JoelProminic** [comment]
I was discussing this issue with @dpastov, and I noticed that it was not really clear from the comments how to setup an On Disk Project using the Moonshine branch build.

So far, we have implemented a very basic On Disk Project template for Moonshine, but it is currenlty only in a test branch.
Source:  https://github.com/prominic/Moonshine-IDE/tree/features/issue_669_domino_on_disk
Automated Build:  https://moonshine-ide.com/downloads/releases/dev/branches/features/issue_669_domino_on_disk/macos (Use Moonshine_Signed_NonSandbox.pkg)

@rat-moonshine or @piotrzarzycki21 should be able to handle the Moonshine Flex updates, but if you need to build the source yourself, there are instructions here:  https://github.com/prominic/Moonshine-IDE/wiki/Running-Moonshine-instance-through-Moonshine-IDE

To setup your environment, follow the steps from [this comment](https://github.com/prominic/Moonshine-IDE/issues/669#issuecomment-595491928) up through generating the update site.  The example project will be generated from Moonshine instead.

To create a new On Disk Project:
1. Install and run the test Moonshine build from the link above
2. File > New > Domino On Disk Project 
3. Choose a project name and directory
4. Right-click on the project and open the Settings
5. In the Maven Build tab, change the Build Action to "install".  Save and close the settings
6. Project > Build with Apache Maven
7. Right-click on the project and choose "Open in Finder"
8. The generated database will be in nsfs/nsf-moonshine/target/.  You can open and view the target in Moonshine

**Comment by JoelProminic** [comment]
Revisiting the project layout [here](https://github.com/prominic/Moonshine-IDE/issues/669#issuecomment-598460642), I see that the intermediate XML directory for Form Builder (formbuilder-src) is probably not necessary.   We do not have any specific content that needs to be placed in the src folder, so we can store the intermediate XML in the .dfb file.

Similarly, we could probably remove visualeditor-src, but we may want to keep this for consistency with the other Visual Editor projects.

**Comment by rat-moonshine** [comment]
> Revisiting the project layout [here](https://github.com/prominic/Moonshine-IDE/issues/669#issuecomment-598460642), I see that the intermediate XML directory for Form Builder (formbuilder-src) is probably not necessary. We do not have any specific content that needs to be placed in the src folder, so we can store the intermediate XML in the .dfb file.
> 
> Similarly, we could probably remove visualeditor-src, but we may want to keep this for consistency with the other Visual Editor projects.

On a second thought, I'm thinking on some other points in term of consistency. I think I want to discuss with you broadly @JoelProminic before writing every pieces now.

**Comment by JoelProminic** [comment]
Currently, the default Maven action for the On Disk Project template is "war:exploded".  I would like to change this to "clean install" instead, since this is what is normally needed to generate the NSF.   I have been using "install" primarily in my testing, but I have seen some cases where the DXL file updates are not detected and the NSF doesn't update.

**Comment by rat-moonshine** [comment]
On addition to above, we noticed that files-tree last-opened-state not properly repopulate when Moonshine restarts, in case of OnDisk project. Also, any last opened files from the project do not auto-opens, this needs to be fixed. I shall work on this shortly.

**Comment by rat-moonshine** [comment]
> Currently, the default Maven action for the On Disk Project template is "war:exploded". I would like to change this to "clean install" instead, since this is what is normally needed to generate the NSF. I have been using "install" primarily in my testing, but I have seen some cases where the DXL file updates are not detected and the NSF doesn't update.

`clean install` now default for new OnDisk projects.

**Comment by rat-moonshine** [comment]
- Fixed tree-state-history population issue
- Fixed not closing of project's editors when project being closed

**Comment by piotrzarzycki21** [comment]
Moving this for next release. No announcement in CHANGELOG

**Comment by piotrzarzycki21** [comment]
@rat-moonshine hide it. We are waiting for tests over 2 months - I don't think that anything is going to change for now, so I don't see any reason to wait even a single day.
