### ISSUE TITLE
[UI Builder] Individual component properties are not saving

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#67]
In following scenario changes made in Visual Editor are not saving.

** Scenario: **
1) Create new Visual Editor Project
2) Add couple of components
3) Save
4) Change properties of added component, save and close file
** Result: **
Reopen saved file and observe that changed properties wasn't saved

**Comment by piotrzarzycki21** [comment]
I have added to Visual Editor mechanism where each component notify about changes of properties. Moonshine register for event "propertyEditorChanged". 

One thing left - I need to figure out how to notify about changes in dataProviders for such components like list.

**Comment by piotrzarzycki21** [comment]
- I have implemented in Visual Editor mechanism for notifying if user change any property using "Visual" tab.
- Additionally Components DropDownList and List saving now their dataProvider(s) to file and they are translated to MXML

**Comment by rat-moonshine** [comment]
I couldn't found properties are actually saving against individual components, in my latest test. 

I took date and checkbox component as an instance. Set a specific date to the date component and made the checkbox selected, and did a `File > Save`. 

Restarted Moonshine, and opened the project, but I couldn't found any previously saved values to the each component. 

I'm reopening this for further investigation.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Look like CheckBox and Calendar components in Visual Editor had some issue in case of saving. I just fixed it and you can check. If it's fixed close the issue.

**Comment by rat-moonshine** [comment]
Properties are now saving properly against individual components, with my recent tests. We shall reopen this if we found any other problem, I'm closing this now.
