### ISSUE TITLE
Stage Dimensions Don't Update When Changing Mobile Device Model

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#673]
I created a new Actionscript Mobile project (#660) with the non-sandbox macOS nightly build (2.7.0).  This mostly worked well, but I noticed that if I changed the Platform and/or Device Model in the Run project settings, the example text was not aligned properly.  For example, with the iPhone 4 model:

![image](https://user-images.githubusercontent.com/24532731/75470230-fb370280-5955-11ea-9214-051ff3fbda48.png)

@rat-moonshine thinks this might affect other mobile projects, but I haven't tested these yet.

**Comment by rat-moonshine** [comment]
Moving the issue to v2.7.0 and it's ready for a test.

**Comment by piotrzarzycki21** [comment]
If it's working it's ready and can be close - Am I right ?

**Comment by rat-moonshine** [comment]
I'm closing this as tested from my side, until we see any other problem we'll reopen this.
