### ISSUE TITLE
Code Completion list improvements

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#68]
As part of that task I would like to give a bit more love to our code completion list. 
- Add icons
- Change colors

If it was discussed before let me know.

**Comment by piotrzarzycki21** [comment]
I just finished first stage of improvement. Small screenshot of how code completion look like right now:

![image](https://user-images.githubusercontent.com/24554795/32849132-a0382872-ca2e-11e7-8a9b-aaa72e2501f8.png)

![image](https://user-images.githubusercontent.com/24554795/32849191-c335b52e-ca2e-11e7-8026-e68021e17a16.png)

1) Added type of item on mouse over and selected
2) Tooltip display some detailed information about item
3) I was looking some free icons which will represents functions, properties etc. but I couldn't find proper set. I have decided to take different approach. I draw myself circles filled by some color and inside 1 char.

Class: "C" color: `0xa848da`  
![image](https://user-images.githubusercontent.com/24554795/32850360-320be47a-ca32-11e7-8e9d-a9d4603ba23c.png)

Function: "M" (like Method) color: `0x3382dd`
![image](https://user-images.githubusercontent.com/24554795/32850486-97de819a-ca32-11e7-977f-a2f6b727a454.png)

Keyword: "K" color: `0x6d5a9c`
![image](https://user-images.githubusercontent.com/24554795/32850574-d801e816-ca32-11e7-958e-a66b5cb786d5.png)

Interface: "I" color: `0x5B4AE4`
![image](https://user-images.githubusercontent.com/24554795/32850647-024982b4-ca33-11e7-972a-c195ec05ccaa.png)

Property: "P" color: `0x3E8854`
![image](https://user-images.githubusercontent.com/24554795/32850417-5d555fc6-ca32-11e7-8e69-8a1e944ccb90.png)

Field: "E" color: `0xC28627`
![image](https://user-images.githubusercontent.com/24554795/32850512-abfe44ee-ca32-11e7-913b-c9bc83951381.png)

Variable: "V" color: `0x6d5a9c`
![image](https://user-images.githubusercontent.com/24554795/32850458-7f6ffb8e-ca32-11e7-9e99-baa04ee4ee5f.png)

Next step will be make something with this scrollbar and add in MXML namespace for displayed components - example:
js:Group
mdl:Card

Not sure whether I will display it as I show above - that's just an idea. @rat-moonshine let me know what do you think.

**Comment by rat-moonshine** [comment]
This looks nice! Thank you for looking into this side @piotrzarzycki21 . 

I guess you probably creating the circles at runtime. The label characters seems out of proper font/embedding (probably the font you are using do not have 'bold' associated with). It'd be nice if they'd look more proper, I guess. 

I'm not clear with point on doing something with this (code-component list) scrollbar and add in MXML namespace, though.

**Comment by piotrzarzycki21** [comment]
Thanks! I'm glad that you like that approach. In case of fonts I did those screenshot from version building in debug mode etc. I think I have some mess with styles there. In case of release build it should look better.

I have added prefixes to the names:
![image](https://user-images.githubusercontent.com/24554795/32877630-b9a48ce6-caa2-11e7-87f3-d0f8b005b567.png)

As you can see all classes which doesn't have namespaces added yet have ns1 prefix, but all of them which currently exists are displayed nicely. Maybe I will exclude somehow that ns1 prefixes not sure yet.
![image](https://user-images.githubusercontent.com/24554795/32877734-3e4ef31e-caa3-11e7-8bb4-de445ff9c0b1.png)

Thanks for the feedback!

**Comment by piotrzarzycki21** [comment]
@joshtynjala I'm trying to display documentation in code hints, but I can't fully understand how it actually work in your extension. Is it all about pointing sources in -source-path ? If I'm using flex-js framework the -source-path should point there ? 
In VSCode it seems to help, but in Moonshine not. Does your documentation parsing is based on -source-path ?

**Comment by piotrzarzycki21** [comment]
Ok I have found the problem "documentation" property wasn't parsed in LanguageServerForProject->parseCompletionItem at all.

**Comment by piotrzarzycki21** [comment]
I will display in code completion documentation, but if I figure out correctly in order to have documentation we need to have in the source-path - path to the sources of framework. 
@joshtynjala you are building -source-path in Moonshine by assigning from project settings "Class paths" in `LanguageServerForProject -> DidChangeConfigurationParams`.

It means that the only option to display documentation for classes is to add in "Class paths" path to sources of framework which being used. 
I think we should have separate setting in project maybe called "Documentation path" or something like that only for that purpose. Thoughts ? 

On the other hand maybe SWCs itselfs should have documentation information ?

**Comment by joshtynjala** [comment]
>Ok I have found the problem "documentation" property wasn't parsed in LanguageServerForProject->parseCompletionItem at all.

It's a new feature on the VSCode extension, so there wasn't anything to parse in Moonshine until recently.

>  On the other hand maybe SWCs itselfs should have documentation information ?

Yes, SWCs can optionally contain documentation. We'll need to use that for an SDK's framework (or third party libraries distributed as SWC). However, the Royale/FlexJS compiler doesn't currently implement a parser.

**Comment by piotrzarzycki21** [comment]
I just finished simple documentation popup. I'm still thinking about omitting this title popup. Couple of screenshot and thoughts. Popup will be switched on users demand:

1) User can click on small icon and display documentation if exists:
![image](https://user-images.githubusercontent.com/24554795/32953859-c1586f42-cbb1-11e7-863a-bcb912931f8b.png)

2) Documentation popup with long comment:
![image](https://user-images.githubusercontent.com/24554795/32953878-cf21e78e-cbb1-11e7-9687-b6faadf0d871.png)

3) Documentation popup with long title (that's why I'm thinking about removing it):
![image](https://user-images.githubusercontent.com/24554795/32953902-e6667068-cbb1-11e7-94b0-24645f918ed5.png)

Let me know what you think. The documentation icon (i) won't be displayed if documentation doesn't exists.

**Comment by piotrzarzycki21** [comment]
I have decided to remove those title and final doc popup look like that:
![image](https://user-images.githubusercontent.com/24554795/32981629-527e1b5e-cc78-11e7-808c-533bf00bd474.png)

**Comment by rat-moonshine** [comment]
I tested the new updates, and code-completion list looks nice! However, I couldn't found a proper item to test the documentation (popup) feature. Is there any certain item that you can suggest of @piotrzarzycki21 ?

**Comment by piotrzarzycki21** [comment]
I have created new class, add some test method and ASDoc there.

**Comment by piotrzarzycki21** [comment]
Closing this one @rat-moonshine reopen if you have some crucial comments.

**Comment by piotrzarzycki21** [comment]
Reopen this one cause I see one small improvements which I need to add for code completion list. When user selecting some item on the list I would like to show signature of function/var etc. Currently it's showing on mouse over which is not so convenient.

**Comment by piotrzarzycki21** [comment]
I have added custom tooltip when user selects one of the option in code completion. It shows method signature which is giving more information to the selected item. If it will be to annoying I will hide that tooltip behind some shortcut.

**Comment by piotrzarzycki21** [comment]
I was using Moonshine more extensively and that additional tooltip with signature details is a bit annoying as I thought. I will hide it behind shortcut. On Windows it will be Ctrl + Q.

**Comment by piotrzarzycki21** [comment]
Following shortcuts will show custom tooltip on selected element with signature details and documentation popup if available:
Windows: Ctrl + Q
Mac: Shift + F1 - @rat-moonshine could you please test it on your Mac, I have weird behavior when I'm hitting this combination. I'm using my Mac through the remote control not directly with keyboard connected.
Once you use that shortcut you should see following tooltip:
![custom_tooltip_signature](https://user-images.githubusercontent.com/24554795/33240375-529334ec-d2b5-11e7-9c3a-731ddf729fdc.gif)
