### ISSUE TITLE
Reopen any project from "Recent" section doesn't work

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#683]
In following scenario on Windows I'm experiencing issue where I cannot reopen project using "Recent" section on Home screen and in menu.

**Scenario:** 
1) **Open/Import Project...** in Moonshine
2) Right click on project and **Close** it
3) Try to reopen project using **Recent* section on **Home** or in menu **File** -> **Recent Projects**

**Result:** Project doesn't open, there is no indication that is even trying to open.

**Comment by rat-moonshine** [comment]
I spent some time testing with stable v2.6.0 and with latest nightly build. 

Unfortunately, I couldn't reproduce the problem above reported. I successfully able to open previously closed projects using _Home_ or Moonshine top-down-menu recent lists. I confirm I tried by the above steps, as well.

Since we have a known issue where project path with space creates problem in particular areas on Windows, I tried to put my project in a folder having space in its name. That also opened properly in my tests. 

@JoelProminic did you noticed any problem while opening recent items on Windows (?)

**Comment by piotrzarzycki21** [comment]
> I spent some time testing with stable v2.6.0 and with latest nightly build.
> 
> Unfortunately, I couldn't reproduce the problem above reported. I successfully able to open previously closed projects using _Home_ or Moonshine top-down-menu recent lists. I confirm I tried by the mentioned steps, as well.
> 
> Since we have a known issue where project path with space creates problem in particular areas on Windows, I tried to put my project in a folder having space in its name. That also opened properly in my tests.
> 
> @JoelProminic did you noticed any problem while opening recent items on Windows (?)

Did you have on your opened project list always one project ?

**Comment by rat-moonshine** [comment]
No, it updates based on number of projects opened into Moonshine, as it was supposed to be. 

If your lists are not updating, then it's possible that cookie files on your system somehow messed up. Try deleting them and re-test.

**Comment by piotrzarzycki21** [comment]
> No, it updates based on number of projects opened into Moonshine, as it was supposed to be.
> 
> If your lists are not updating, then it's possible that cookie files on your system somehow messed up. Try deleting them and re-test.

No, What I meant here is that - I do have only one project when I'm trying to reproduce that issue. Maybe this is the factor. Let's say that you will open Moonshine, close all projects, restart Moonshine and than try to reproduce the issue.

**Comment by piotrzarzycki21** [comment]
If you won't be able to reproduce that - I will have to look into what is the problem on my sight.

**Comment by rat-moonshine** [comment]
> > No, it updates based on number of projects opened into Moonshine, as it was supposed to be.
> > If your lists are not updating, then it's possible that cookie files on your system somehow messed up. Try deleting them and re-test.
> 
> No, What I meant here is that - I do have only one project when I'm trying to reproduce that issue. Maybe this is the factor. Let's say that you will open Moonshine, close all projects, restart Moonshine and than try to reproduce the issue.

Yeah, I try by that way, too.

**Comment by JoelProminic** [comment]
I gave this a test on Windows 10, with no projects already in my Recents list.  I found that the project (MoonshineDESKTOPevolved) appeared in the Recents section on the home page once I had opened the project, and I could reopen the project from File > Recent Projects.  This seems fine to me as well...

**Comment by piotrzarzycki21** [comment]
I'm closing that issue as non reproducible. I have reset all settings in Moonshine and did complete clean up. I may have broken something - in the end this is developer's machine, so my usage of Moonshine may have been different than simple user. If it occurs again I will reopen.

**Comment by rat-moonshine** [comment]
Yeah. Things can be tricky sometime in the development system. Glad cleaning cookies fixed the issue for you.

**Comment by piotrzarzycki21** [comment]
> Yeah. Things can be tricky sometime in the development system. Glad cleaning cookies fixed the issue for you.

After couple of hours of work - it gets back again, so I will probably reopen that and look into it myself. :)

**Comment by rat-moonshine** [comment]
I able to reproduce this in a particular scenario - if we have the Home tab closed, opening the recent project/files from Moonshine top menu doesn't work. 

I'm reopening this for further investigation.

**Comment by rat-moonshine** [comment]
Associated listeners now relocated to recent-plugins from Home screen. The issue is ready for a test.

**Comment by piotrzarzycki21** [comment]
> Associated listeners now relocated to recent-plugins from Home screen. The issue is ready for a test.

I will test it cause I was able to reproduce that every time. I'm waiting for bamboo build.

**Comment by piotrzarzycki21** [comment]
Working without the problem now! Thanks!
