### ISSUE TITLE
Code completion stop working when non visible tab back to active

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#691]
In following scenario code inspection stop working:

1) Open more tabs than available spaces for them. You should see on the right sight Hamburger drop down list with tabs which didn't feed into available space
2) Click on one of the file from drop down list

**Result:** Code inspection in opened file doesn't work

**Comment by piotrzarzycki21** [comment]
@rat-moonshine This issue is caused by that changes https://github.com/prominic/Moonshine-IDE/commit/dac30ca4bf281f02e8c82846700e0aa7271c56ad#diff-89466c63c4195cae480f3c383a87fd7a . Download Nightly build and observer during usage of Moonshine whether you don't experience other issues with code completion.

**Comment by rat-moonshine** [comment]
Okay. I shall give this a test soon.
