### ISSUE TITLE
Nightly build of Moonshine should use Nightly build of Installer

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#695]
@yozef reported in following issue https://github.com/prominic/Moonshine-SDK-Installer/issues/25

> On another note Apache Royale 0.9.7 is not downloading at all, it shows an empty temp folder (I'm guessing it was very recently released and no download URL is being fetched)

It simply means that Nightly build is not using latest nightly installer which should be working like that.

**Comment by rat-moonshine** [comment]
Moonshine SDK Installer is a separate entity. Until we release a new version of the application user continue to use their existing version-one with existing downloads-set. 

Using Nightly version of SDK Installer in Nightly Moonshine wouldn't be that easy, considering the technical and usabilities.

On macOS `~/Applications` can hold any single version with same app-id. If we change the app-id for nightly build that will create other many complexities. 

On Windows, we may need to manage another directory/space for installing x64 version of the SDK-Installer. 

In either cases I see managing two different application entities will create more complexities. I wonder if we really wants to get into managing that much of trouble for nightly ones. Or, provide a notification with Nightly SDK Installer download link in case of Moonshine Nightly.

@JoelProminic what you suggest (?)

**Comment by piotrzarzycki21** [comment]
Thanks for explanation. It looks like it is too complex. We just need more frequently release installer. Let's focus on that.
