### ISSUE TITLE
Node.js and HCL Notes version not showing in About screen

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#698]
We noticed that `Help > About` section not populates (or wrongly populates) versions for Node.js and HCL Notes. We need to have the tests added.

![image](https://user-images.githubusercontent.com/24370870/83286154-16d3d280-a1fd-11ea-86bb-64e05b07eec7.png)

**Comment by rat-moonshine** [comment]
NodeJS and Notes version now testing in About section:
![image](https://user-images.githubusercontent.com/24370870/83386891-6a1a7080-a409-11ea-949e-e7a607c9e0d9.png)

I see we can check version of an .app file in two following ways when I took latter:

```
$ defaults read /Applications/HCL\ Notes.app/Contents/Info CFBundleGetInfoString
11.0, (C) Copyright HCL Technologies. 1987, 2019.

$ defaults read "/Applications/HCL Notes.app"/Contents/Info CFBundleShortVersionString
11.0
```

**Comment by JoelProminic** [comment]
This worked for me on MacOS.   I'd like to check with Windows as well.

Since you found a way to read the version number for macOS, I may not need the version for #699.

**Comment by JoelProminic** [comment]
I found the license number in %NOTES_HOME%/licenses/notices.rtf on Windows:


    NOTICES AND INFORMATION

    HCL Notes 11.0.1
    ...


Unfortunately, this is not a plain txt file.  It looks like you can search for a line like this:

    \par HCL Notes 11.0.1


If this meets the immediate needs for Windows, we can push #699 to a later release.

**Comment by rat-moonshine** [comment]
Besides the said `%NOTES_HOME%/licenses/notices.rtf` solution to extract version value on Windows for HCL Notes, I found `nsd.exe` provides a version information though not sure if this adequate for the purpose:

```
C:\Program Files (x86)\HCL\Notes>nsd.exe -version
ERROR (44): unable to open file 'C:\Program Files (x86)\HCL\Notes\dbghelp_x86_v6.8.40.dll' - (13) Permission denied
NSD Version     : 11.00.0100.0080 (Release 11.0.1)
```
HCL Notes here v11.0.1 which matches the above output.

**Comment by rat-moonshine** [comment]
Following things have updated:

1. An older issue where version values duplicate to wrong SDK rows - fixed
2. I found it is not readable as a plain text parsing .rtf file-value as String. Thus I chose to go by the [command](https://github.com/prominic/Moonshine-IDE/issues/698#issuecomment-652787405) for now. If we think using this could be a concern, then we may need to think about what other way we have to read the .rtf file on Windows.

**Comment by JoelProminic** [comment]
Using the `%NOTES_HOME%/nsd.exe -version` command should be fine.   `nsd.exe` actually does a lot of things, most notably killing a hung Notes client, but those require different arguments.   Show the "Release ..." version rather than the NSD Version - this seems to match what is reported in the Notes client.

**Comment by JoelProminic** [comment]
I tested on a VM with an IBM Notes installation, and the version number was detected properly with the "Release" format.

However, the NodeJS version number is broken now on Windows.   I am using the default MoonshineSDKs path for NodeJS, and it works fine with a Royale project

![image](https://user-images.githubusercontent.com/24532731/86413176-3049bd80-bc86-11ea-819e-dcbd65185348.png)
![image](https://user-images.githubusercontent.com/24532731/86413257-5cfdd500-bc86-11ea-9459-7d6f61cf6740.png)

**Comment by rat-moonshine** [comment]
> However, the NodeJS version number is broken now on Windows. I am using the default MoonshineSDKs path for NodeJS, and it works fine with a Royale project

This should have resolved now.

**Comment by piotrzarzycki21** [comment]
Original issue was tested and one more fixed along the way. I'm closing this issue.
