### ISSUE TITLE
Debugging Royale project fails with error

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#701]
As reported by @JoelProminic , he's having a problem doing "Build & Debug" for Royale application on macOS. Following is the error output he encountered:

```
: Available on:
:   http://127.0.0.1:3000
:   http://192.168.1.75:3000
: Hit CTRL-C to stop the server
: Debug launch failed.
: http-server stopped.
: HTTP server has been terminated.

: Available on:
:   http://127.0.0.1:3000
:   http://192.168.1.75:3000
: Hit CTRL-C to stop the server
: ******** Unhandled error in debug adapter - Unhandled promise rejection: Error: Cannot navigate to invalid URL
:     at Client.processMessage (/Applications/Moonshine.app/Contents/Resources/elements/chrome-debug-adapter/node_modules/noice-json-rpc/lib/noice-json-rpc.js:66:36)
:     at LoggingSocket.<anonymous> (/Applications/Moonshine.app/Contents/Resources/elements/chrome-debug-adapter/node_modules/noice-json-rpc/lib/noice-json-rpc.js:42:48)
:     at LoggingSocket.emit (events.js:228:7)
:     at Receiver.receiverOnMessage (/Applications/Moonshine.app/Contents/Resources/elements/chrome-debug-adapter/node_modules/ws/lib/websocket.js:789:20)
:     at Receiver.emit (events.js:223:5)
:     at Receiver.dataMessage (/Applications/Moonshine.app/Contents/Resources/elements/chrome-debug-adapter/node_modules/ws/lib/receiver.js:422:14)
:     at /Applications/Moonshine.app/Contents/Resources/elements/chrome-debug-adapter/node_modules/ws/lib/receiver.js:379:23
:     at /Applications/Moonshine.app/Contents/Resources/elements/chrome-debug-adapter/node_modules/ws/lib/permessage-deflate.js:298:9
:     at /Applications/Moonshine.app/Contents/Resources/elements/chrome-debug-adapter/node_modules/ws/lib/permessage-deflate.js:376:7
:     at afterWrite (_stream_writable.js:522:5)
```

While testing the "Build & Debug" against MyAccount Royale project, I confirm the above error. @joshtynjala do we need any custom settings to the project to overcome the issue?

Currently, I have following paths set to my Royale project:
![image](https://user-images.githubusercontent.com/24370870/83394241-def3a780-a415-11ea-98ff-9a51477e9624.png)

**Comment by piotrzarzycki21** [comment]
Your problems are a bit more complicated and I was hesitant get into the details of that for quite some time. I wanted to get attention of @joshtynjala to that.

In order to have properly working MyAccount with Moonshine we need to in custom url have our:

`https://localdev.prominic.net/prominic/bin/js-debug/index.html`

Above url allows us to be recognized properly by server sight. 
- Moonshine do not start with that url. It's running application under different url
- When I close my project http server is still running behind instead of stopping 

Note that I have this url in hosts file `c:\Windows\System32\drivers\etc\`:

127.0.0.1   localdev.prominic.net 

If that makes some "collision" with what node is trying to start let me know. 

I would be really glad if I could run MyAccount trough Moonshine by just doing "Build & Run".

**Comment by joshtynjala** [comment]
> Moonshine do not start with that url. It's running application under different url

Okay, I'll try to get that fixed. The "Custom URL to launch" is supposed to override the default behavior where Moonshine starts its own HTTP server.

> When I close my project http server is still running behind instead of stopping

That sounds like a case that I simply forgot to handle. I handled the various "stop" buttons and Moonshine exiting, but I didn't think of closing a project without exiting Moonshine. I'll get that fixed.

> If that makes some "collision" with what node is trying to start let me know.

I don't think that there's a collision with that.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 With my latest commit, if "Custom URL to launch" is specified in a Royale project, Moonshine will not start the local HTTP server. It appears that this was originally working correctly when I initially implemented it, but unfortunately, commit 4cb85f537c4c8245246728807d7efafedbd87f80 broke this and some other things.

@rat-moonshine You should also check to see if my commit fixes your issue.

**Comment by piotrzarzycki21** [comment]
@joshtynjala It's working now. Thanks! I have noticed that "Step Over" in debugging window doesn't work. I will raise issue once I test it on a Hello World type of example - I did tests so far in our MyAccount application.

**Comment by rat-moonshine** [comment]
I tried to download a sandbox build and tested it on macOS Mojave. 

While "Build & Debug" a basic Royale example with project-default Chrome browser (Settings > Run > Web Browser) the browser terminates abruptly throwing this error (I'm not sure if this already a known issue in sandbox):

![image](https://user-images.githubusercontent.com/24370870/84117729-978d9c80-aa4f-11ea-8cfe-4fa846384189.png)

I tried to change the browser to Mozilla, it did start but without any address to its address-bar, nor the application started:

![image](https://user-images.githubusercontent.com/24370870/84118527-be000780-aa50-11ea-81e6-ce25766a49e6.png)

Testing with a non-sandbox build however didn't face the above issues. "Step Over" didn't seem to function, though.

**Comment by joshtynjala** [comment]
I guess I'll just launch without a server when running in the macOS sandbox. It's not worth the effort to debug why a web browser started by Node.js process started by a sandboxed process won't work correctly. It might not even be solvable.

Is there an easy way to detect sandbox vs non-sandbox builds?

**Comment by rat-moonshine** [comment]
> Is there an easy way to detect sandbox vs non-sandbox builds?

[This](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/valueObjects/ConstantsCoreVO.as#L245) can help to determine between sandbox and non-sandbox version.

**Comment by joshtynjala** [comment]
Perfect. Thank you!

**Comment by joshtynjala** [comment]
Closing in favor of #732 as a dedicated issue.
