### ISSUE TITLE
Error downloading moonshine SDK installer

### ISSUE THREAD

**Issue by Joanne16** [prominic/Moonshine-IDE#711]
- [ ] Review the documentation: https://github.com/prominic/Moonshine-IDE
- [ ] Search for existing issues: https://github.com/prominic/Moonshine-IDE/issues
- [ ] Use the latest stable version at: http://moonshine-ide.com
- [ ] Let us know how to reproduce the issue. Include a code sample, or share a project that reproduces the issue

### Errors
Error #3219
Error: Error #3219
	at flash.desktop::NativeProcess/start()
	at actionScripts.utils::MSDKIdownloadUtil/runAppStoreHelperWindows()
	at MethodInfo-40110()
	at actionScripts.utils::Unzip/unzipTo()
	at MethodInfo-26326()
	at MethodInfo-15195()

Error #3219
Error: Error #3219
	at flash.desktop::NativeProcess/start()
	at actionScripts.utils::MSDKIdownloadUtil/runAppStoreHelperWindows()
	at actionScripts.utils::MSDKIdownloadUtil/runOrDownloadSDKInstaller()
	at components.popup::GettingStartedPopup/runAppStoreHelper()
	at components.popup::GettingStartedPopup/___GettingStartedPopup_Button1_click()

**Comment by piotrzarzycki21** [comment]
@Joanne16 are you using Win or Mac?

**Comment by Joanne16** [comment]
@piotrzarzycki21 I'm using windows 7 - 32bit - latest build of moonshine (2.6.0)

**Comment by piotrzarzycki21** [comment]
We are not guarantee that Moonshine will work on Windows 7. Support for that system ended, so we do not bother on testing there. Additionally Moonshine SDK installer is 64 bit application, so it probably won't work either.

**Comment by rat-moonshine** [comment]
@Joanne16 I made changes to the execution of Moonshine SDK Installer in more of an OS-way. You can give a try by downloading the latest nightly build from here: https://moonshine-ide.com/download/.

If you continue to face  non-opening of the Moonshine SDK Installer, then this could be related to deeper areas like Windows-bit, (security (?)). Unfortunately, the application bound to be a 64-bit application.

Thanks for reporting this, though.

**Comment by piotrzarzycki21** [comment]
> @Joanne16 I made changes to the execution of Moonshine SDK Installer in more of an OS-way. You can give a try by downloading the latest nightly build from here: https://moonshine-ide.com/download/.
> 
> If you continue to face non-opening of the Moonshine SDK Installer, then this could be related to deeper areas like Windows-bit, (security (?)). Unfortunately, the application bound to be a 64-bit application.
> 
> Thanks for reporting this, though.

If our app is 64bit it won't work on her Windows 7 32bit. I will wait couple of more days with closing that issue.

@rat-moonshine did you provide instruction how to install nightly of Moonshine SDK Installer manually ?

**Comment by rat-moonshine** [comment]
Are we distributing Moonshine SDK Installer nightly?

**Comment by piotrzarzycki21** [comment]
If you mean by distribution - some installation - No we are not, but you can download Nightly zip and provide instructions where copy that after unpack. 
It's not enough that you download Nightly Moonshine - it won't update installer to Nightly - unless it's officially released.

**Comment by Joanne16** [comment]
Hi, I tried using the nighly build, but it does not work at all... I was able to use the apacheRoyale SDK by manually downloading the SDK files and setting the path for the project in moonshine and this works correctly

Thanks for your help
