### ISSUE TITLE
Windows installer delayed-start problem

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#712]
Recently as many users reported encountered slow-start of Moonshine-IDE Windows installer, this issue for any related discussion on finding/thought against the same.

**Comment by rat-moonshine** [comment]
Here are some of my test results packaged and tested locally, using the same certificates as on Bamboo.

Removed | Installer Start Time (1) | Until Moonshine start (2) (excludes installer-start-time)
-------------------------------------- | --------------------- | ------------------------
`elements` | Less than 30 seconds | A minute
`elements/as3mxml-language-server` | 4 minutes | 5 minutes
`elements/chrome-debug-adapter` and `elements/firefox-debug-adapter` | Less than a minute | 1-2 minutes
Nothing | 4 minutes | 6 minutes

(1) to appear screen:
![image](https://user-images.githubusercontent.com/24370870/86769637-0ec54900-c06d-11ea-83eb-759172c77d27.png)

(2) Progress to Moonshine start:
![image](https://user-images.githubusercontent.com/24370870/86769697-2a305400-c06d-11ea-83b3-6a0750c65b8f.png)

**Comment by piotrzarzycki21** [comment]
I think it would be reasonable to get your attention here @joshtynjala. @rat-moonshine please try to do test where you removing from inside of those folders (`elements/chrome-debug-adapter` and `elements/firefox-debug-adapter`) some larger file - maybe we could specify which files are causes that.

**Comment by rat-moonshine** [comment]
> I think it would be reasonable to get your attention here @joshtynjala. @rat-moonshine please try to do test where you removing from inside of those folders (`elements/chrome-debug-adapter` and `elements/firefox-debug-adapter`) some larger file - maybe we could specify which files are causes that.

Unfortunately, it'd be a tedious process to test in such a way without having a direction. Probably 'node_modules' are the biggest folder in the said directories, but they can't be removed for a working version of an application (I guess) so doesn't make sense if removing them could speed up the installer.

**Comment by joshtynjala** [comment]
If we hadn't been able to solve the previous issue with the files in elements, I was going to suggest adding them to one or more .zip files, and then unzipping them on first run. It might be somewhat tricky to manage that, though. We'd need some way to detect when Moonshine is updated so that the new files can replace the old ones.

**Comment by rat-moonshine** [comment]
We can use Bamboo build value to determine between version-differences/updates.

**Comment by rat-moonshine** [comment]
Okay. While working on this I gave a test to see how actual startup time will improve if we bundle some directories as Zip. Following are the results as I have seen (in my system configuration).

Directories zipped:
- elements/as3mxml-language-server
- elements/chrome-debug-adapter 
- elements/firefox-debug-adapter

Installer Start Time (1) | Until Moonshine start (2) (excludes installer-start-time) | Total
--------------------- | ------------------------ | -------
Less than 25 seconds | 1.5 minutes | Around 2 minutes 

For the time being, I'm targeting to zip the said three directories as mostly concerned-oriented. I don't think adding more directories to zip may improve better than this time, but we can see if we require that too.

**Comment by rat-moonshine** [comment]
Unfortunately, this turns fatal after several hours investing into these doing planning, structuring etc.

Application throws security error on any of these following cases:
- Unzip to its directory 
- Unzip somewhere and then copied to its directory

We should had thought about this concern far earlier when we were discussing this. But we missed it.

I don't have any other easy-going. Let me know if anyone has any alternative thought.

**Comment by joshtynjala** [comment]
The Java language server copies some files to `File.applicationStorageDirectory`. We could try doing something similar. Obviously, we'd need change the code that loads those files to load them from there instead of `File.applicationDirectory`.

**Comment by rat-moonshine** [comment]
Yeah... this only put more burden on you..

**Comment by JoelProminic** [comment]
Some clarifications from @rat-moonshine:

The exception was:

    SecurityError: fileWriteResource
    at flash.filesystem::File/createDirectory()
    at Function/actionScripts.utils:LanguageServerUnzipper/protected:startUnzip/actionScripts.utils:onFileLoadedInMemory()[D:\DevareaLocal\Prominic\GIT\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\utils\LanguageServerUnzipper.as:99]
    at flash.events::EventDispatcher/dispatchEventFunction()
    at flash.events::EventDispatcher/dispatchEvent()
    at actionScripts.utils::Unzip/onReadCompletes()[D:\DevareaLocal\Prominic\GIT\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\utils\Unzip.as:79]
    at Function/actionScripts.utils:FileUtils/readFromFileAsync/actionScripts.utils:onOutputProgress()[D:\DevareaLocal\Prominic\GIT\Moonshine-SDK-Installer\InstallerSharedCore\src\actionScripts\utils\FileUtils.as:231]

The current process is:
1. Create installers with Zips as you understood
2. User installs Moonshine
3. Before starting plugins-registraiton queues, plugins those auto-loads previously opened projects, starts language-server against them etc. - we requires to have the language-server etc. directories uncompressed. This process must be done before starting any of the regular plugins-activity starts; So we can not execute this unzipping process out-of-the-box but with tightly controlled ordering
4. Thus Moonshine starts the check and unzipping process before starts its regular plugins-functionalities.  Moonshine doing the unzipping process itself to have the full control to monitor when the unzip completes, and then starts the regular plugins-registration processes.
5. Once unzip done, Moonshine resumes the plugins-registration process again 

I see some example workarounds here:
https://community.adobe.com/t5/air/securityerror-filewriteresource/td-p/783118?page=1
https://stackoverflow.com/questions/2872136/how-to-put-save-files-into-your-application-directory-adobe-air


Can we extract this to a less restricted directory, like `File.applicationStorageDirectory` instead?

**Comment by rat-moonshine** [comment]
> Can we extract this to a less restricted directory, like File.applicationStorageDirectory instead?

I think that's what @joshtynjala suggested. But this may need him to change the codes to point to the different directory instead.

**Comment by joshtynjala** [comment]
I think that we currently use the AIR "shared runtime" with its native installer on Windows (`-target native`). Perhaps we could switch to "captive runtime" instead  (`-target bundle`) and create a custom installer, similar to what we do for the macOS app store. While I cannot say for sure, I would guess that a custom installer isn't going to be as slow.

Regardless, in my professional opinion, we should have AIR's captive runtime on the roadmap. I believe that it's very likely that Adobe and HARMAN will decide to get rid of the shared runtime and require all AIR apps to use captive runtime instead. It's already happened on Android, so Windows and macOS are likely too.

**Comment by rat-moonshine** [comment]
> I think that we currently use the AIR "shared runtime" with its native installer on Windows (-target native). Perhaps we could switch to "captive runtime" instead (-target bundle) and create a custom installer, similar to what we do for the macOS app store. While I cannot say for sure, I would guess that a custom installer isn't going to be as slow.

While on macOS using `-target bundle` produce DMG, on Windows it produces a directory containing executable and related resource files. The good thing is we can have a 64-bit executable in this case. 

But this will require us to bundle as an installer, sign and distribute. Unfortunately, the commercial installers are pretty expensive in this race.

**Comment by rat-moonshine** [comment]
> I see some example workarounds here:
> https://community.adobe.com/t5/air/securityerror-filewriteresource/td-p/783118?page=1
> https://stackoverflow.com/questions/2872136/how-to-put-save-files-into-your-application-directory-adobe-air

Thanks @JoelProminic , for the directions.. The discussions are quite old though, but two said workarounds discussed using `new File($pathToApplicationDirectory)` instead of `File.ApplicationDirectory`.

While using the above way I see this still works! Unfortunately, it's workingsness limited in debug-run only.

When tried in installer-mode, the process simply terminates by throwing `Error #2038` (File I/O Error). This only works when can run Moonshine 'as Administrator'; However this may not an intuitive way to ask users to do that, because we couldn't figure out.

**Comment by JoelProminic** [comment]
@rat-moonshine reported this was the full error stack trace when running in installer mode without Administration access:

    Error: Error #2038
            at actionScripts.utils::LanguageServerUnzipper/initiateProcess()
            at actionScripts.utils::LanguageServerUnzipper/checkAndUnzip()
            at actionScripts.impls::IFlexCoreBridgeImp/unzipLanguageServerFiles()
            at actionScripts.plugin.preInitialization::PreInitializationTasksPlugin/startLanguageServerUnzip()
            at actionScripts.plugin.preInitialization::PreInitializationTasksPlugin/initializePlugin()
            at actionScripts.plugin::PluginManager/setupPlugins()
            at components::MainEntryPoint/onAddedToStage()
            at components::MainEntryPoint/___MainEntryPoint_Group1_addedToStage()
            at mx.managers::SystemManager/preloader_preloaderDoneHandler()
            at flash.events::EventDispatcher/dispatchEvent()
            at mx.preloaders::Preloader/displayClassCompleteHandler()
            at flash.events::EventDispatcher/dispatchEvent()
            at mx.preloaders::SparkDownloadProgressBar/initCompleteHandler()
            at flash.events::EventDispatcher/dispatchEvent()
            at mx.preloaders::Preloader/dispatchAppEndEvent()
            at mx.preloaders::Preloader/appCreationCompleteHandler()
            at flash.events::EventDispatcher/dispatchEvent()
            at mx.core::UIComponent/dispatchEvent()
            at mx.core::UIComponent/set initialized()
            at mx.managers::LayoutManager/doPhasedInstantiation()
            at mx.managers::LayoutManager/doPhasedInstantiationCallback()

**Comment by joshtynjala** [comment]
I've successfully used NSIS to create Window installers for a couple of AIR apps. Some other folks have mentioned that they were happy with Inno Setup. Both are free.

**Comment by rat-moonshine** [comment]
I haven't moved deep into the said two installer systems although it's promising that you used one. Are they, or any, can use in an automated manner? i.e. running Ant build script that automates the packaging at any remote system, i.e. Bamboo?

**Comment by joshtynjala** [comment]
Yeah, I run the NSIS executable from an Ant script in both projects.

For reference, one of the projects is the Feathers (Starling) SDK Manager, which is open source:

https://github.com/BowlerHatLLC/feathersui-starling-sdk-manager

I'm not familiar with Inno Setup (I've only heard others say it is good), but it looks like it can also run from the command line, so it should be relatively easy to add to a build script:

https://jrsoftware.org/ishelp/index.php?topic=compilercmdline

**Comment by rat-moonshine** [comment]
Thank you @joshtynjala , for the information on possible CLI.

However, I'm a little concerned as I see both the software are Windows-centric only. I was expecting a software that we can use for both macOS (PNG) and Windows (EXE) packaging. I'm not sure if this a legit expectation anyway as I see we require to do many a treatment to produce PNG in our current Ant-build script.

I was hoping to have a system that is applicable for both the OS on packaging without the use of Adobe's proprietary one. However, we can also build only for Windows using any of the above software that may fit best, if getting macOS support is a problem.

**Comment by rat-moonshine** [comment]
Okay. Please ignore my above comment on macOS installer, it seems I confused myself. On macOS we use pkgutil to produce the standard pkg, so no Adobe proprietary packager using in the process. However, it could be great if a custom packager/installer would avail for macOS too where we can do specialized tasks like running post-installations tasks etc.

**Comment by joshtynjala** [comment]
> However, it could be great if a custom packager/installer would avail for macOS too where we can do specialized tasks like running post-installations tasks etc.

I think that it is best to continue to use Apple's official pkgutil. They're so picky about how things are done that we shouldn't stray too far from the standard approach. Three times now I've been ready to release an app update, only to discover that my previous notarization commands weren't enough anymore (for an app outside of the app store). I can only imagine how much harder that could be if I used something other than pkgutil.

> Can you provide sample scrips/settings-file that used in NSIS process? A documentation link to prepare settings file would be helpful, too.

Here's my .nsi file for the Feathers SDK Manager:

https://github.com/BowlerHatLLC/feathersui-starling-sdk-manager/blob/master/nsis/feathers-sdk-manager.nsi

One thing to note is that I included every individual file that needed to be installed/uninstalled. However, I remember someone telling me that you can specify folders, and all included files will be included. That should make things a bit simpler, I think. Especially since Moonshine has many, many included files.

Here's the official documentation (I see a section on scripting that is probably relevent):

https://nsis.sourceforge.io/Docs/

**Comment by rat-moonshine** [comment]
Thank you for the information, @joshtynjala . I probably would try to investigate with a simpler app as that would cost me less time (than building Moonshine) to test different attributes provided through the .nsi file. 

I'll be going to create a sub-issue to track the investigation, the .nsi file structure little bit cumbersome at this point )

**Comment by Aszusz** [comment]
Recently I was testing different builds with Windows Defender turned on and off. Here are my results:

|| WinDef OFF | WinDef ON |
|---|---|---|
|2.4.0|6s|10s|
|2.5.0|6s|10s|
|2.6.0|7s|21s|
|nightly feb-24|6s|21s|
|nightly jun-24|2m54s|3m46s|
|nightly jul-15|2m54s|5m05s|

**Comment by rat-moonshine** [comment]
I vaguely remember you reported your tests were taken more than 5 minutes or even closer than 10 minutes. But anyway, we need to run these staying inside the conventional environment.

**Comment by Aszusz** [comment]
> I vaguely remember you reported your tests were taken more than 5 minutes or even closer than 10 minutes. But anyway, we need to run these staying inside the conventional environment.

Yes, I reported launch times up to 15 minutes. It was during my normal workflow. This time I tested with no applications running alongside Moonshine IDE installer and I was not using my machine at all during the wait period.

**Comment by JoelProminic** [comment]
This has been resolved by #713
