### ISSUE TITLE
Flex and Feather Download Fail on Flash

### ISSUE THREAD

**Issue by taromaecap** [prominic/Moonshine-IDE#715]
I tried to use the Moonshine SDK Installer today, and I got errors on Flex.

Installing Adobe Flash Player playerglobal.swc from: https://fpdownload.macromedia.com/get/flashplayer/updaters/32//playerglobal32_0.swc
Validating download: /Users/<user>/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/frameworks/libs/player/32.0/playerglobal.swc
Flash SDK download failed

When I checked the contents in the downloaded SDK folder, osmf related files and swfObject related files were missing.

PC environment is as follows

Mac OS: yosemite
MoonshineIDE 2.6.0
Installer version 3.6.0 (mac)

Thanking you in advance

**Comment by piotrzarzycki21** [comment]
Hi @taromaecap ,
I've updated MD5 of those files and you should be good now. Please try again download SDKs.

**Comment by taromaecap** [comment]
Dear  Mr. Piotr

Thank you for your reply

I tried and it worked

---  install Log  ---
< FlexSdk >
Installing frameworks configuration files configured for use with an IDE
/Users/<user>/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0 is now an IDE compatible folder
Installation complete

< Feathers >
/Users/<user>/Downloads/MoonshineSDKs/Flex_SDK/feathers-sdk-4.0.0-bin is now an IDE compatible folder
Installation complete
-------------------

Also, it worked fine on Windows version

Thank you

**Comment by rat-moonshine** [comment]
Sounds great! Thanks @piotrzarzycki21 for looking into this. I'm closing this issue now.
