### ISSUE TITLE
Building Flex project failing when source files places in the root folder

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#716]
One of our client have Flex app, which doesn't contains **src** folder - instead all the files are places in the main folder. Project was configured previously in Flash Builder - when I have opened it in Moonshine and tried build I was prompted that main application file doesn't exits. 

I'm attaching example where that issue can be reproduced. 

`: Error: unable to open '\NewFlexDesktopProject.mxml'
`
[NewFlexDesktopProject.zip](https://github.com/prominic/Moonshine-IDE/files/4981478/NewFlexDesktopProject.zip)

**Comment by piotrzarzycki21** [comment]
Please @rat-moonshine look into that when you will be able to. Workaround for this is to modify Moonshine IDE project file `.as3proj` by changing 

```
  <compileTargets>
    <compile path="/NewFlexDesktopProject.mxml"/>
  </compileTargets>
```

to

```
  <compileTargets>
    <compile path="NewFlexDesktopProject.mxml"/>
  </compileTargets>
```

**Comment by rat-moonshine** [comment]
I haven't look into the attached project yet. But I can tell you from this point a project MUST need to have its own source folder - be it 'src', 'abc', 'dfg' or 'xyz'. That is how Moonshine project management has designed. This is the conventional design for a project and we'll not be going to change that. This design actually helps many things in different test cases, opposing it may conflict in different functionalities.

**Comment by rat-moonshine** [comment]
> Please @rat-moonshine look into that when you will be able to. Workaround for this is to modify Moonshine IDE project file `.as3proj` by changing
> 
> ```
>   <compileTargets>
>     <compile path="/NewFlexDesktopProject.mxml"/>
>   </compileTargets>
> ```
> 
> to
> 
> ```
>   <compileTargets>
>     <compile path="NewFlexDesktopProject.mxml"/>
>   </compileTargets>
> ```

That seems to be valid in my tests. Opening the project with its configuration file, I also required to reset its 'Paths' section to have the project run successfully (set the only path entry to "/").

**Comment by piotrzarzycki21** [comment]
> I haven't look into the attached project yet. But I can tell you from this point a project MUST have its own source folder - be it 'src', 'abc', 'dfg' or 'xyz'. That is how Moonshine project management has designed. This is the conventional design for a project and we'll not be going to change that. This design actually helps many things in different test cases, opposing it may create conflict in different functionalities.

As you can see we have bump into the scenario where real world project have different convention.

**Comment by piotrzarzycki21** [comment]
> That seems to be valid in my tests. Opening the project with its configuration file, I also required to reset its 'Paths' section to have the project run successfully (set the only path entry to "/").

What you did exactly ? 

No matter what if file with following path cannot be found `/NewFlexDesktopProject.mxml`, but it's exists something is wrong and it's need to be simply fixed. I don't expect that you start avoid src in code etc.

**Comment by rat-moonshine** [comment]
In real-world there could be many a scenario. 

What I did was:
1. Manually: Changed the configuration file as you [mentioned](https://github.com/prominic/Moonshine-IDE/issues/716#issuecomment-664304345) 
2. After opening the project its 'Settings -> Paths' had wrong path-value, that required to be fixed; Basically pointing to the root project folder only which updates the path as '/'

Unfortunately, the user needs to fix this on his/her own if varied from general convention; I don't want to dive into changing the existing rules that could introduce more headaches against already running rules.

**Comment by piotrzarzycki21** [comment]
> 2\. After opening the project its 'Settings -> Paths' had wrong path-value, that required to be fixed; Basically pointing to the root project folder only which updates the path as '/'

This doesn't work - tested on windows - I would not raise issue if it would work.

**Comment by piotrzarzycki21** [comment]
> In real-world there could be many a scenario.

Sure and we need to cover whatever we can.

**Comment by rat-moonshine** [comment]
> > 2. After opening the project its 'Settings -> Paths' had wrong path-value, that required to be fixed; Basically pointing to the root project folder only which updates the path as '/'
> 
> This doesn't work - tested on windows - I would not raise issue if it would work.

This worked for me. 
[NewFlexDesktopProject.zip](https://github.com/prominic/Moonshine-IDE/files/4988501/NewFlexDesktopProject.zip)

**Comment by piotrzarzycki21** [comment]
I have sent you trough email small recording about **2**.

**Comment by rat-moonshine** [comment]
I have replied to your email @piotrzarzycki21 , I hope you able to run the project with the custom changes. 

I tried to do a test case creating a Flash Builder project and having all the source files to its root. Then tried to import the project into Moonshine and do a save Settings. 

I had placed the project on Desktop. After doing a Moonshine 'Save Settings' I noticed the .as3proj file has a value like this to point to the main application file, which is wrong:

```
<compileTargets>
    <compile path="../../../../NewFlexDesktopProject.mxml"/>
</compileTargets>
```

While the class-paths section saved correctly and showing valid in Moonshine:
```
<classpaths>
    <class path="/Users/Devsena/Desktop/NewFlexDesktopProject"/>
 </classpaths>
```
I'll look into the path-generation problem.

**Comment by rat-moonshine** [comment]
I have updated the Flash Builder importer codes to properly set application paths, no matter if source files placed at the root.

Here's a demo Flash Builder project which set up to use its source files from its root location. This can be tested for the purpose:
[NewFlexDesktopProject.zip](https://github.com/prominic/Moonshine-IDE/files/4994594/NewFlexDesktopProject.zip)

Updated areas are supposed to generate the following tags in the generated .as3proj file:

```
<compileTargets>
    <compile path="..."/>
</compileTargets>
<classpaths>
    <class path="..."/>
 </classpaths>
```

**Comment by piotrzarzycki21** [comment]
I've downloaded version which you have provided me on Skype. It's Build 917. I have same error. I have removed first .as3proj and opened project again. Do I need to do anything more before I build ?

**Comment by rat-moonshine** [comment]
Ah, sorry for the trouble. The branch that builds x64 was updated with 'master' just before committing this fix to master. :/ I shall try to resend you an updated x64 version, soon.

**Comment by piotrzarzycki21** [comment]
It's working. I'm closing it.
