### ISSUE TITLE
Unordered menu items on macOS

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#717]
![image](https://user-images.githubusercontent.com/24370870/89630513-1fabe900-d8bd-11ea-871a-465f4785b5f5.png)

Unordered menu-items are applicable in the following locations:

- [x] File -> New
- [x] File -> Recent Projects
- [x] File -> Recent Files
- [x] `File -> New` in context-menu on tree-items

**Comment by rat-moonshine** [comment]
This is ready for a test now.

**Comment by JoelProminic** [comment]
I reviewed this today with the latest macOS 10.14.6 build from Bamboo, and I found some remaining ordering issues for the project lists:

![image](https://user-images.githubusercontent.com/24532731/93395133-f7f45d00-f83a-11ea-9641-c913b1a58549.png)

I see the same ordering on the Home tab

![image](https://user-images.githubusercontent.com/24532731/93395157-03478880-f83b-11ea-8200-51f7272ceef7.png)

**Comment by rat-moonshine** [comment]
I see I missed these two items hidden between others. I have updated sort-field which properly affects the visual now. Please, check.

**Comment by JoelProminic** [comment]
The sorting looks good to me now on macOS 10.14.6.
