### ISSUE TITLE
Importing/opening of a project shows long delay

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#719]
Used project to test: https://github.com/prominic/Moonshine-IDE/tree/master/ide/MoonshineSharedCore

Tested on the last stable release of Moonshine, having no previous project opened.
macOS Mojave time (RAM 8GB): 30 seconds
Windows 10 time (RAM 16GB): 16-18 seconds

We need some investigation if this delay can improve-able. 

@joshtynjala please share if you think of any possible area which may cause this delay.

**Comment by piotrzarzycki21** [comment]
It's related to #640

**Comment by rat-moonshine** [comment]
It could be!

Isn't the language/debug-server etc. stars once the project adds/shown-up to the sidebar tree? The maximum amount of delay as seen showing up before the project adds to the sidebar. What it does during the time, what information Moonshine retrieves/reads during that time (?)
