### ISSUE TITLE
[UI Builder] Project with existing source do not works

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#72]
- I kept a folder with a Visual Editor project's "MyPreviousVEProject/src" folder on my desktop
- Tried to create a new Visual Editor project with "project with existing source option"
- Select the MXML file reside in the said "src" folder as the main application file
- After a brief wait (unresponsiveness) Moonshine opened a Visual Editor project in the editor - but I couldn't found any content from my existing source file
- When I expand the project's tree folder - I noticed it has all of my desktop directory's files/folders inside it (actually the project created in the root of the Desktop folder only)

[Alternate solution: If we found solving this would be critical, then I'll suggest to not to avail the "project with existing source" option in case of Visual Editor project]

**Comment by rat-moonshine** [comment]
I still see the problem remain with my latest tests. 

- Had an existing folder with source on my desktop - MyExistingProject/src/MyExistingProject.mxml
- Tried to create a new VE project with "Project with existing source" option
- I chose to give the project a different name this time
- After a brief wait a VE project opened to the editor 
- I didn't found any saved content in newly opened editor
- I found all my desktop's files/folders came under the newly opened project

I'm reopening this to investigate.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine just check and it's working for me. Quick question as I understand you are removing "*..veditorproj" and than going through your scenario ?

**Comment by rat-moonshine** [comment]
Exactly. That is how I conceived it. A folder with only the application source file inside it.

**Comment by piotrzarzycki21** [comment]
Does your initial folder before your scenario look like that ? 
![image](https://user-images.githubusercontent.com/24554795/33059554-fab6f89a-ce94-11e7-86cb-2bed68532d99.png)

**Comment by rat-moonshine** [comment]
Initially when the project was in working state I had following file/folders inside it:
- src
- visualeditor-src
- *.veditorproj
I deletes both 'visualeditor-src' and the .veditorproj file. Thereafter I tried to create a new VE project in Moonshine with the option 'Project with existing source'.

**Comment by piotrzarzycki21** [comment]
I got ya! It won't work like that. UI builder won't have feature where we will be opening mxml file, parsing it and translate to the format of builder. Opening project from existing source in that case will work if those sources were previously UI builder type and have that folder "visualeditor-src'. I think we may handle this in two way:
- Display for the user information if that folder doesn't exists
- Disable opening from existing source

Thoughts?

**Comment by rat-moonshine** [comment]
I understand the involved complexities in this case. I vote for the 2nd option (to disable options from existing source) for this project type.

**Comment by piotrzarzycki21** [comment]
I will go with 2nd option. Thanks!

**Comment by piotrzarzycki21** [comment]
I have completely removed those settings in case of that project. Let me know if it's ok. I don't want to confuse user.
