### ISSUE TITLE
Duplicate shortcut-keys on different features

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#725]
`Edit -> Find (CMD + F)`
![image](https://user-images.githubusercontent.com/24370870/93202376-3cff8d00-f770-11ea-9bc0-a90ce7aff24b.png)

`View -> Find References (CMD + F)`
![image](https://user-images.githubusercontent.com/24370870/93202468-5a345b80-f770-11ea-9c0f-17a06cb73222.png)

**Comment by rat-moonshine** [comment]
The original key-combination to "Find References" were this way:

macOS: CMD + F7
Windows: Alt + F7

For some reason, none of the special key declarations seems to work on macOS menu, many options already have different keys set when special keys like F6, F7, etc. used on Windows.

I have changed the key-combination for the feature to this now:

macOS: Shift+Cmd+F

**Comment by JoelProminic** [comment]
I see the shortcut is Shift+Ctrl+F on macOS.   This works fine for me, but I'd like to do a quick test with Windows once we have the updated certificate

**Comment by JoelProminic** [comment]
I confirmed CTRL-F and ALT-F7 on Windows as well.
