### ISSUE TITLE
Reopen previously opened project files 

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#73]
It is quite inconvenient if I'm working on project where I have several opened files, close project, reopen it and all previously opened files has been closed.

As part of that feature I propose:
- Remember and reopen all files which we were working on

**Comment by piotrzarzycki21** [comment]
This feature is related to #79 and #86

**Comment by JoelProminic** [comment]
Some thoughts:

Another use case to consider is that the user may want a fresh start when they reopen the project.  I am bad about leaving tabs open in general, so having all of the files reopened when I opened the project could be annoying.

I am not opposed to this feature, but I think we would also want to provide one or more of these options:
- A way to quickly close lots of tabs (close all, close to right, close for project?).  Normally I see this as a context menu on the tab bar.
- A way to disable the file reopening setting
- Prompt the user if they want to reopen all the files before reopening the project.

**Comment by piotrzarzycki21** [comment]
Fully agree that this feature should be configurable through the settings along with #86 . However I would rather not go with the prompting users about files reopening - this could be more annoying. 

I think options for configuration those features should be in tab General.

**Comment by piotrzarzycki21** [comment]
Feature is ready:
- Files is being reopened if we select in the settings appropriate options. They are available for review in General tab
- I have added context menu on the Tab with options: "Close" and "Close All"

**Comment by JoelProminic** [comment]
The Close and Close All context menu buttons seem to work fine.  They are not available when all tabs except the Home tab are closed, so I can't even try to trigger #102.

The tab and branch restore logic seems to work well.   To test the robustness, I tried renaming a file that was open in the editor and a director that was expanded and reopened the project.  I found that the missing file and directory were skipped.  If I renamed the file and directory later and reopened the project, the tab and branch were opened again automatically.

Are the open tab and branch statuses stored with the project, or in the application settings?   I renamed and reopened a project, and I found that the tabs and branches were not opened automatically, which suggest the settings are saved by path in the application settings.

I see that the tab/branch reopen logic is disabled by default.    I don't have a strong opinion on whether this should be the default or not.   @rat-moonshine, does the new logic feel more intuitive to you?

**Comment by rat-moonshine** [comment]
@JoelProminic for me it's more convenient to revisit the last worked projects immediately (after IDE starts) instead of re-opening each of them individually.

Although, having different options for opening files and project folders, I also don't have any hard opinion but also not sure about. We may want the labels should be something different, though.

If there were too many projects opened at a time, complete startup of Moonshine may take some more seconds if we want to auto-load those projects (during startup) to sidebar - we need to see how this will come up. Anyway I've created a feature request at #106 .

**Comment by piotrzarzycki21** [comment]
@JoelProminic current state of tabs and project branches are stored by flash SharedObject. 
Project branches: I'm storing array of objects with "name": "location" 
Project files: I'm storing "projectFiles"+porjectName: "file location"

As for the renaming whole project - If you think that it should work raise separate issue I will get back to that later. I would like to focus on #106

**Comment by piotrzarzycki21** [comment]
@JoelProminic as for the default state of both options. Yesterday I didn't have strong opinion either, but in the evening I have started to use development version of Moonshine and I'm more for making those option true as default. - It is very useful to me.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, since rat-moonshine and I don't have a strong preference on this, go ahead and enable these options by default.

**Comment by JoelProminic** [comment]
While testing #96, I noticed this behavior
1. Open/Create a project
2. Open Multiple files
3. File > Close All (or Right-click on tabs and select Close All)
4. Restart Moonshine
5. Reopen the project
6. All of the opened files are reopened.

This also triggers when closing and reopening the project
1. Open/Create a project
2. Open Multiple files
3. File > Close All (or Right-click on tabs and select Close All)
4. Close the project
5. Reopen the project
6. All of the opened files are reopened.

It seems that the open tabs are not being saved after closing all tabs, but closing individual tabs works fine.

**Comment by piotrzarzycki21** [comment]
@JoelProminic Issues has been fixed.

**Comment by piotrzarzycki21** [comment]
Both options has been set to true as default.

**Comment by JoelProminic** [comment]
This seemed to work for me after your last update.  I tried:
- clearing the application settings - the settings were set to the default, and the logic worked as expected
- Disabling the settings - the logic was disabled properly
- Reenabling the settings - the logic worked properly
