### ISSUE TITLE
Royale Debug Plugin Problems on macOS 10.14.6 (App Store) and Chrome 85

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#732]
I got errors with Build & Run and Build and Debug for an Apache Royale project with the latest Moonshine 3.0.0 release candidate build.   I tested with macOS 10.14.6 and Google Chrome 85.0.4183.121

1. Create a new Royale Browser Jewel project
2. Project > Build & Run. 
3. BUG:  Console shows "Debug adapter exited unexpectedly" and the application does not open in a browser.
4. Debug > Build & Debug.
5. BUG:  Console shows "Debug launch failed."  I get a popup from macOS reporting that "Google Chrome quit unexpectedly"

I reinstalled Google Chrome, but I got the same behavior.

I could not reproduce the problems on Windows.

**Comment by JoelProminic** [comment]
I got this error with the App Store build on Moonshine, so this could be a sandbox error.  Did we support the Royale debugger for the App Store build in previous releases?

**Comment by piotrzarzycki21** [comment]
@JoelProminic I don't think so we support that.

**Comment by rat-moonshine** [comment]
I see the behavior also reported here - https://github.com/prominic/Moonshine-IDE/issues/701#issuecomment-641098212.

@joshtynjala might suggest if we need to move this issue to another milestone.

**Comment by rat-moonshine** [comment]
For now in v3.0, the 'Debug' menu-option set to unavailable in the App Store version.

**Comment by joshtynjala** [comment]
That's probably the best option for now. I'll revisit in another milestone.

**Comment by JoelProminic** [comment]
I see that @rat-moonshine's update completely hides the Debug menu in the AppStore build.  However, this is overkill - debugging was working fine for me for a Flex Desktop project, but now it is no longer available.

Also, this does not resolve the higher-priority problem:  I can not Build & Run Royale projects without getting the Google Chrome crash.  From #701 in sounds like we planned to have Royale projects to open without the local server on the App Store build - was this ever implemented.   Is it something that we could add/fix easily?

**Comment by joshtynjala** [comment]
I can probably get Build & Run for Royale projects working without the crash by the end of the month, if that's a priority.

I'd rather revisit Build & Debug after I've switched over to the updated JS debug adapter. I suspect that Microsoft's rewrite may work better than the current Chrome debug adapter.

**Comment by rat-moonshine** [comment]
> I see that @rat-moonshine's update completely hides the Debug menu in the AppStore build. However, this is overkill - debugging was working fine for me for a Flex Desktop project, but now it is no longer available.

I assume then it works for any Flash-based projects including Feathers project types. I'll see if it is easy to avail the Debug option only for the Flash-based projects in the App Store version, that should help in both the world!

**Comment by rat-moonshine** [comment]
So I have updated menus to avail the Debug option for Royale projects only in non-App-Store builds. This should help us now to go with the release.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine What's it the summary - Did you hide for Royale or disable it ?

**Comment by rat-moonshine** [comment]
> @rat-moonshine What's it the summary - Did you hide for Royale or disable it ?

As I mentioned, the Debug options for Royale project available in non-App-Store version only; This includes MacOS non-sandbox and Windows.

**Comment by joshtynjala** [comment]
Okay, in the app store version, Build & Run for a Royale project will now simply launch the .html file in the browser instead of starting a web server. It opens in the default web browser, I think. It's basically the same behavior as when Node.js is not configured.

**Comment by rat-moonshine** [comment]
> Okay, in the app store version, Build & Run for a Royale project will now simply launch the .html file in the browser instead of starting a web server. It opens in the default web browser, I think. It's basically the same behavior as when Node.js is not configured.

I confirm having the said changes, running Royale project in the App Store version opens directly to the browser without any problem. I didn't notice any browser crash during my tests anymore.

However, the application opens to the default browser instead of what set in the project's Settings; But I think that is less important for now.

**Comment by JoelProminic** [comment]
Yeah, this should be good enough for the 3.0.0 release.  I confirmed that I can Build & Run a Royale project with the App Store build, and the Debug menu options are disabled.

**Comment by JoelProminic** [comment]
It looks like this was fixed before the 3.0.0 release, but the issue was never closed.
