### ISSUE TITLE
Error #1009 (MXMLCFlashModulePlugin/compileModule()) For Flex and Actionscript Projects

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#733]
While testing the 3.0.0 release candidate (App-Store version) on macOS 10.14.6, I got this error when building a Actionscript Mobile project

    : Build completed successfully.
    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugins.as3project.mxmlc::MXMLCFlashModulePlugin/compileModule()
    : 	at actionScripts.plugins.as3project.mxmlc::MXMLCFlashModulePlugin/projectBuildSuccessfully()
    : 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/shellData()

Steps to reproduce:
1. Create a new Actionscript Mobile project.  Do not change any of the default settings
1. Project > Build & Run
1. BUG:  The console shows the above error
1. Note:  The application launches anyway after the error.

I saw the same error with a Flex Desktop project.

**Comment by rat-moonshine** [comment]
Tested in following Flash-based projects where Module is applicable:

Project Type | Action | Working
---------------------- | ------------------- | ------------
ActionScript Desktop | Build, Build & Run | Yes
Feathers Desktop | Build, Build & Run | Yes
Feathers Mobile | Build, Build & Run | Yes
Flex Desktop | Build, Build & Run | Yes
Flex Mobile | Build, Build & Run | Yes

**Comment by JoelProminic** [comment]
This is resolved in my tests as well.

**Comment by JoelProminic** [comment]
I found that at most two modules would build for a project after this change.  After this, Moonshine stopped the build.   @rat-moonshine has already fixed the problem.
