### ISSUE TITLE
Listening for non-available debug-event-information when top-menu option clicked

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#735]
This problem is valid for all the options under "Debug" top-menu except "Build & Debug".

1. Create/Open a Flex project
2. Debug > Build & Debug
3. Try `Debug > Stop`. BUG. This triggers an exception twice

```
: Error #1034
: TypeError: Error #1034
: at flash.events::EventDispatcher/dispatchEvent()
: at actionScripts.utils::KeyboardShortcutManager/dispatch()
: at actionScripts.utils::KeyboardShortcutManager/stopEvent()
: at actionScripts.ui.menu::MenuPlugin/redispatch()
```

While looking into the source, in different places of debug-APIs it tries to type-conversion an _Event_ (which sends by the top-menu click event) to _DebugActionEvent_ in its handler function:

```
dispatcher.addEventListener(DebugActionEvent.DEBUG_STEP_OVER, dispatcher_debugStepOverHandler);
private function dispatcher_debugStepOverHandler(event:DebugActionEvent):void
{
	this.stepOverDebugAdapter(event.threadId);
}
```

I couldn't able to replace `(event:DebugActionEvent)` with `(event:Event)` because of the event-information it's going to use in its corresponding commands, i.e. `event.threadId`.

**Comment by joshtynjala** [comment]
I'm trying to test this, but I can't seem to build any of my Flex projects anymore. I get the following output in the console when I choose Build & Debug:

> : Compiling NewFlexDesktopProject
> : Command: "C:\Users\josht\Development\flash\sdks\Flex4.16.1_AIR32\bin\mxmlc.bat" -load-config+=obj/NewFlexDesktopProjectConfig.xml -optimize=false +configname=air -debug=true
> : 'C:\Program' is not recognized as an internal or external command,
> : operable program or batch file.
> : 'C:\Program' is not recognized as an internal or external command,
> : operable program or batch file.

It's probably worth mentioning that the path to my JDK is: _C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot_.

**Comment by joshtynjala** [comment]
@rat-moonshine I remembered that I recently set the path to Git in my Moonshine settings. When I cleared that path, builds started working correctly.

It appears that the build was failing because Moonshine's _setLocalEnvironment.cmd_ runs the following command, and it isn't properly escaping a Git path with spaces:

```
%GIT_HOME%\bin\git config --global http.sslCAInfo %GIT_HOME%\mingw64\ssl\cert.pem
```

For reference, _C:\Program Files\Git_ is the standard installation path on Windows, so handling spaces is very important.

**Comment by joshtynjala** [comment]
For future reference, I found that I specifically need to use the Ctrl+T keyboard shortcut to reproduce this issue. I was not able to reproduce by choosing Debug -> Stop with the mouse.

**Comment by rat-moonshine** [comment]
> @rat-moonshine I remembered that I recently set the path to Git in my Moonshine settings. When I cleared that path, builds started working correctly.
> 
> It appears that the build was failing because Moonshine's _setLocalEnvironment.cmd_ runs the following command, and it isn't properly escaping a Git path with spaces:
> 
> ```
> %GIT_HOME%\bin\git config --global http.sslCAInfo %GIT_HOME%\mingw64\ssl\cert.pem
> ```
> 
> For reference, _C:\Program Files\Git_ is the standard installation path on Windows, so handling spaces is very important.

I confirm the problem, @joshtynjala . I shall be going to look into that. Thanks!

**Comment by JoelProminic** [comment]
I did some tests on macOS with the non-Sandbox build, and I was not able to reproduce the exceptions with any of the buttons that we use to stop the server.
