### ISSUE TITLE
Switch to new Moonshine Icon

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#738]
We have a new icon prepared for Moonshine, and the 3.0.0 release would be a good time to add it.

**Comment by Aszusz** [comment]
Based on @joshtynjala design I prepared three versions of the logo for the 3.0 dock icon:

- with the background
![moonshine-ide-dock-icon](https://user-images.githubusercontent.com/7197014/95367930-abe68680-08d5-11eb-95a8-72e5b4dd42e6.png)

- just blue moon
![moonshine-ide-dock-icon-blue](https://user-images.githubusercontent.com/7197014/95367933-ac7f1d00-08d5-11eb-9fd7-eb3175e25603.png)

- just yellow moon
![moonshine-ide-dock-icon-yellow](https://user-images.githubusercontent.com/7197014/95367934-ad17b380-08d5-11eb-8591-292846ac1778.png)

**Comment by JoelProminic** [comment]
@rat-moonshine, let's use the first icon for now and see how it looks in the Doc and shortcuts.   The second icon may also also work, but I think it will be better to have the solid background.

**Comment by rat-moonshine** [comment]
Fine. 

@Aszusz please provide me the said icon-variant of PNG file, which must be of 1024 pixels.

**Comment by Aszusz** [comment]
@rat-moonshine 
Here you go:



![moonshine-ide-dock-icon-round-1024](https://user-images.githubusercontent.com/7197014/95751741-53313800-0c9f-11eb-9aa8-de6f992775dc.png)
![moonshine-ide-dock-icon-square-1024](https://user-images.githubusercontent.com/7197014/95751761-57f5ec00-0c9f-11eb-9944-a167831e1d4f.png)

**Comment by rat-moonshine** [comment]
The new logo is updated to wherever it requires. I also tried to look into any _in-application_ usage of the same, so far I only able to find in the following places which are updated now:

`Help -> About`

Let me know if you see any other section(s) where the Moonshine logo being used and I may have missed updating it.

**Comment by rat-moonshine** [comment]
> which I find super weird because in C:\Users\Adrian\AppData\Roaming\Microsoft\Windows\Start Menu\Programs it looks OK

Maybe, the OS stores the history version of the icon somewhere to render the Start Menu. I see a similar incident in the case of macOS. I manually added Moonshine icon to macOS task-bar in my previous installation:

![image](https://user-images.githubusercontent.com/24370870/95879446-febbb480-0d93-11eb-873b-98a3f74a6acd.png)

This old icon remains even after I updated the application with its newer icon in `/Applications`.

**Comment by rat-moonshine** [comment]
Updates on above start menu icon differences:

On macOS as soon I click on the old-icon in taskbar, the icon auto-updated for me.

On Windows, this may similarly affect however I see the Start Menu icon already updated in my case.

**Comment by Aszusz** [comment]
For me it didn't update after click and didn't update after pc restart.

**Comment by rat-moonshine** [comment]
> For me it didn't update after click and didn't update after pc restart.

Unfortunately, I don't know if I can help with this aspect. OS generally updates the shortcuts with an appropriate icon-set. In my tests things updated automatically while testing on Windows 10. 

It is possible that OS shall update the icons eventually, in your case, too.

**Comment by JoelProminic** [comment]
The icons updated for me on macOS, though I had to unpin the application on the dock and reopen before this icon changed:
![image](https://user-images.githubusercontent.com/24532731/95890440-6bf62800-0d49-11eb-9b8c-2bd2f78f00c4.png)

On Windows, everything updated for me except the taskbar icon.  I don't see the distortion @rat-moonshine  mentioned:
![image](https://user-images.githubusercontent.com/24532731/95890914-00608a80-0d4a-11eb-81f4-f9ea39f32ca8.png)

**Comment by rat-moonshine** [comment]
Okay. Here's a funny thing with Windows update I want you to note @Aszusz @JoelProminic . 

I see the Moonshine icon properly updated when I scroll to the Start Menu:

![image](https://user-images.githubusercontent.com/24370870/95891069-2fa2e600-0da2-11eb-9c1b-d9a0c3b18b3e.png)

When I open Start Menu Search and type 'Moonshine', it lists the same application's shortcut but with different icon:

![image](https://user-images.githubusercontent.com/24370870/95891163-4d704b00-0da2-11eb-8333-9a42eb417500.png)

Unfortunately, I have no knowledge of Windows' update logic in this case.

**Comment by rat-moonshine** [comment]
I have added a few more additional sizes of icons to use with app-descriptor file which generally not very required in conventional usage, but let's see if they help to fit into some icon/size problems on Windows 10, i.e. smaller icon on right:

![image](https://user-images.githubusercontent.com/24370870/96010972-06488f80-0e60-11eb-8969-788e8e491f10.png)

**Comment by JoelProminic** [comment]
I tested with a different Windows machine, and all the icons seemed to update properly.  It seemed like Moonshine was unusually slow to start, this machine was pretty slow in general.
