### ISSUE TITLE
Project Directory Does Not Default to Last Used

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#74]
I have defined three project directories in Moonshine.

/Users/joelanderson/Library/Containers/com.moonshine-ide/Data/Documents
/Users/joelanderson/Documents/Flex/temp_workspace
/Users/joelanderson/Documents/Flex/workspace

![image](https://user-images.githubusercontent.com/24532731/33095789-76d0c9d0-ceca-11e7-8bdd-79401268abb2.png)

In previous versions, Moonshine would populate the project directory field with the last project directory used to create a project.    However, now it only uses my "workspace" directory.

Test Procedure
1. Configure two additional project directories for Moonshine
2. Create a new project, selecting a different project directory
3. Create another new project.  BUG:  Moonshine does *not* default to the same directory used in the previous step.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine will you be able take this one for the next release? I would like to jump to the auto closing feature.

**Comment by rat-moonshine** [comment]
Yes, I can. I shall look into this once I done with #62 .

**Comment by JoelProminic** [comment]
I tested this logic for each of my workspaces, and a variety of project templates (including a custom template and the new Royale template).  It seemed to work properly.

I see that if I change the workspace but cancel before the project is created, the change is not saved.  This is the behavior I would expect.
