### ISSUE TITLE
Java Uses Flex Language Server for Superclass and Interface Completion

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#742]
While doing other testing today, I noticed this problem when creating a new Java class:
1. Create/Open a Flex Project
2. Create/Open a Java Project
3. In the Java project, right-click in src/main/java and choose New > Java Class 
4. Type "ArrayList" in the "Superclass" menu.  BUG:  this shows Flex packages (i.e. mx.collections) instead of Java packages (i.e. java.util)
5. Type "List" in the Interface field.   BUG:  This also shows Flex packages

I saw the same behavior if I opened the Java project first.  However, the list showed Java classes and interfaces only if I only had a Java project open.

**Comment by piotrzarzycki21** [comment]
I have tested this issue on Windows and cannot reproduce it. @rat-moonshine can you do a quick test on Mac ? For some reason I have problems with starting language server for Java project.

**Comment by rat-moonshine** [comment]
In my quick tests on the latest non-sandbox build, while creating a new Java Gradle or Maven project, the console throws the following warning. However, re-opening the project continue to throw the following warning.

`: Java language server exited unexpectedly. Close the NewJavaGradleProject project and re-open it to enable code intelligence.`

While trying to create a new class under the **_Java Gradle_** project, typing anything in the "Superclass" or "Interfaces" field (in the new file dialog) do not open the class-listing; This works in the case of Java Maven project but with wrong package reference as reported by @JoelProminic in the issue:

![image](https://user-images.githubusercontent.com/24370870/99931581-1450d080-2d7b-11eb-920c-49c281183034.png)

@joshtynjala can you please take a look into this (?)

**Comment by piotrzarzycki21** [comment]
> In my quick tests on the latest non-sandbox build,

I was using as well non-sandbox version

**Comment by rat-moonshine** [comment]
> > In my quick tests on the latest non-sandbox build,
> 
> I was using as well non-sandbox version

What do you mean by that statement? Did you able to reproduce the same problem in your tests or everything is working the expected way for you?

**Comment by piotrzarzycki21** [comment]
I was having exactly same problems on Mac as you with same message on the console (https://github.com/prominic/Moonshine-IDE/issues/742#issuecomment-731935280). On Windows everything was working fine and I didn't reproduce Joel's issue.

**Comment by joshtynjala** [comment]
Previously, when requesting workspace symbols, I manually looked up which project the file in the `activeEditor` belongs to (and fell back to `activeProject`, if no editors are open). I guess I only accounted for the case of searching for symbols from the Find Workspace Symbols dialog. I forgot that we also request workspace symbols from the new file dialog too. When you open the new file dialog, you may be trying to add a new file to a different project than the project associated with the active editor. That's what you were seeing. It was requesting symbols for the active editor's project instead of the new file dialog's project.

I updated the language server events to accept an optional `ProjectVO` reference. If the `ProjectVO` is not null, then it will be used. Otherwise, it will fall back to the old behavior of basing requests on the current  `activeEditor`. The new file dialog now passes its `ProjectVO` when it requests workspace symbols.

**Comment by rat-moonshine** [comment]
I gave some tests with the new non-sandbox build on macOS. I'm not sure how the Java project-files are supposed to create but the following behavior probably not how they should be:

1. Opened Moonshine
2. Created two new projects - Royale and Flex Desktop, keep the active-editor from the Flex Desktop project
3. Create a new Java Gradle project - console throws a warning  "`Java language server exited unexpectedly. Close the NewJavaGradleProject project and re-open it to enable code intelligence.`"
4. Try to create a new Java class for the Java Gradle project
5. Try to write "ArrayList" in the "Superclass" field or "List" in the "Interfaces" field
6. No package-listing like [this](https://github.com/prominic/Moonshine-IDE/issues/742#issuecomment-731935280) pops-up during the writing of the words [Bug ?]
7. Create a new Java Maven project
8. Same behavior as of 3-6 [Bug ?]

@piotrzarzycki21 can you please give a try and confirm if you see the same behavior?

**Comment by piotrzarzycki21** [comment]
> 3\. Create a new Java Gradle project - console throws a warning  "`Java language server exited unexpectedly. Close the NewJavaGradleProject project and re-open it to enable code intelligence.`"

I have installed fresh version of Moonshine on my Mac and I have same issue as you - when I open Java project.

**Comment by joshtynjala** [comment]
I tested with an existing Java Maven project that I had already created, and it worked successfully. I'll try with a Java Gradle project,  Iguses. It may be that I need to update the Java language server again. Maybe the version we're using has a bug with Gradle integration.

**Comment by joshtynjala** [comment]
Apparently, recent updates to the Java language server now have a minimum requirement of JDK 11. I can confirm that it fails with JDK 8, but when I switch to JDK 11, the language server starts successfully. I'm going to add a version check similar to the one we have for Haxe 4 as the minimum.

**Comment by joshtynjala** [comment]
Okay, Moonshine now explains that Java 11 is required, so please update to Java 11 and try testing my changes again.

**Comment by rat-moonshine** [comment]
> Okay, Moonshine now explains that Java 11 is required, so please update to Java 11 and try testing my changes again.

Does this also require us to upgrade the distributing OpenJava version through Moonshine SDK Installer now?

Currently, it has the following version in distribution:
```
$ /Users/devsena/Downloads/MoonshineSDKs/Java/openjdk-1.8.0/bin/java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)
```

**Comment by rat-moonshine** [comment]
> Okay, Moonshine now explains that Java 11 is required, so please update to Java 11 and try testing my changes again.

I confirm creating the Java project throws an error to console in the following way:
![image](https://user-images.githubusercontent.com/24370870/100192491-156b3480-2f18-11eb-897a-d975bd3c6732.png)

**Comment by joshtynjala** [comment]
Yeah, we'll probably need to update the OpenJDK version in the Moonshine SDK Installer, if we want Java projects to "just work".
