### ISSUE TITLE
New Java File Reports External Change

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#743]
I noticed this behavior today when creating a new Java file:
1. Open/Create a Java Gradle project (not tested with Maven)
2. Right-click on src/main/java and choose New > Java Class
3. Fill out the form as desired and submit
4. The class opens and seems to be populated correctly
5. Change to a different tab and then back to the new class
6. BUG:  Moonshine reports "<Class>.java is changed outside.  Do you want to reload it?"
7. Click "Yes". There are no noticeable changes to text, but the above prompt does not trigger again.

Is Moonshine still writing to the file when the editor is opened?

**Comment by rat-moonshine** [comment]
This probably deeper than I was assuming initially. I spent quite some time today on investigating this, it appears that a .java file re-writes twice from somewhere when the opened editor holds the first update time reference only. The second re-write probably unexpected in this scenario and never updates the opened editor's time-reference, thus a difference of time always found when the tab is selected and it alerts with file-changed-outside notification.

Here is how I made the above assumption:

When a new ActionScript file creates, command-line shows only one reference of its update time:

```
$ stat NewASFile.as 
16777220 12896112394 -rw-r--r-- 1 devsena staff 0 87 "Oct 13 17:22:37 2020" "Oct 13 17:22:37 2020" "Oct 13 17:22:37 2020" "Oct 13 17:22:37 2020" 4096 8 0 NewASFile.as
```

When a Java file creates command-line shows two or multiple update times with a second's difference:

```
$ stat MyNewJavaClass2.java 
16777220 12896112420 -rw-r--r-- 1 devsena staff 0 66 "Oct 13 17:24:17 2020" "Oct 13 17:24:16 2020" "Oct 13 17:24:16 2020" "Oct 13 17:24:15 2020" 4096 8 0 MyNewJavaClass2.java
```

So far, I haven't found where this multi-save is happening in the case of a Java file. I shall continue to look on.

**Comment by rat-moonshine** [comment]
I have updated the last-modification time set a little bit and that seems to fix the issue. I also tested this in different projects/class-files, all appeared good, in my tests.

Project-class types | Throws notification without any change | Throws notification after changed outside
----------------- | ---------------------- | ----------------
ActionScript/Flash-based | No | Yes
Feathers | No | Yes
Haxe-Feathers | No | Yes
Haxe-fl | No | Yes
Java Gradle | No | Yes
Java Maven | No | Yes
Royale | No | Yes

**Comment by JoelProminic** [comment]
I couldn't reproduce this with the 3.0.0 release candidate on macOS.   I also tried a Java file in a Grails project, and I did not see the bug.
