### ISSUE TITLE
[App Store] Invalid Signature error to "node_modules" files during App Store validation

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#746]
While validating the package at iTunesConnect, it reports with the following "Invalid Signature" errors and terminates the process:

>  ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.10/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.11/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.12/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-10/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-11/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-12/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-4/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-5/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-6/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-7/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-8/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> ITMS-90238: Invalid Signature - The executable at path Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-9/deasync.node has following signing error(s): code object is not signed at all In architecture: x86_64 . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information. 

I tried to `codesign` with Apple certificates to one of the said files but it returns "Illegal instruction: 4" - possibly because this `codesign` process/certificate used to be against executable files.

@joshtynjala do you have any idea how to sign/overcome these files (?) 

Currently, no App Store review is possible unless fixing these errors.

**Comment by rat-moonshine** [comment]
When I tried to `codesign` one of the .node files at Bamboo it succeeds. Possibly my local keychain crippled during my earlier tests. 

I have added each of those files in the [buld-script](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/build/build-lib.xml#L641) to sign with `codesign` and Apple certificates for now, and they all signed well while building at Bamboo:

```
15-Oct-2020 03:06:32	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.10/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:33	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.11/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:33	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-0.12/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:34	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-10/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:34	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-11/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:34	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-12/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:35	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-4/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:35	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-5/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:36	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-6/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:36	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-7/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:36	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-8/deasync.node: signed Mach-O thin (x86_64) [deasync]
15-Oct-2020 03:06:37	     [exec] DEPLOY/Moonshine.app/Contents/Resources/elements/hashlink-debug-adapter/node_modules/deasync/bin/darwin-x64-node-9/deasync.node: signed Mach-O thin (x86_64) [deasync]
```
This will do for now but any changes to that list in the future may force us to update this signing list, as well.

I confirm the build passed iTunesConnect validation and ready for submission.

**Comment by JoelProminic** [comment]
Some suggestions for the Ant script:

If we want to explicitly define the list of .node files to sign, you can use [macrodef](https://ant.apache.org/manual/Tasks/macrodef.html) to reduce code duplication.

It looks like you can use the for [task from AntContrib](http://ant-contrib.sourceforge.net/tasks/tasks/for.html) to detect and sign all the .node files.  I don't remember using this task before, but the path/fileset example looks to be what you need.

**Comment by rat-moonshine** [comment]
I replaced the signing .node files using [for-loop](http://ant-contrib.sourceforge.net/tasks/tasks/for.html), it is working fine. Thanks!
