### ISSUE TITLE
Add auto closing quotes for MXML tag attributes

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#75]
In following scenario quotes of MXML tag attributes should auto close

![auto_closing_quotes_attributes](https://user-images.githubusercontent.com/24554795/33095925-9619e412-cf05-11e7-96d5-9ac2d2269231.gif)

**Comment by piotrzarzycki21** [comment]
Main functionality is finished. It look like that currently:
![auto_closing_quotes_attributes](https://user-images.githubusercontent.com/24554795/33172132-27422a68-d04f-11e7-8c00-d04dbbd241b3.gif)

The only think which is missing is to set cursor between quotes. I cannot find so far the way to do this. @rat-moonshine any tip in that area ? I was going through the TextEditor and tried several things, but so far no luck. If I won't figure out it I will close this issue and raise another one just for that part.
Even without this cursor in place writing something in MXML now is much more pleasant.

**Comment by piotrzarzycki21** [comment]
I have found the solution. In order to put cursor between quotes I have used "setSelection" from TextEditorModel. I have found one more case where my auto completion not working - I will try to fix that, so work on that is still in progress.

**Comment by rat-moonshine** [comment]
This update looks good in my test. I confirm cursor manages to stay between the quotes. However, having the problem #71 seems much consistent now.

**Comment by piotrzarzycki21** [comment]
I just fixed scenario which you have described. My case is different. Maybe I will describe how did I implement the logic for auto closing. In order to add auto closing for tag attributes I need to know that user currently placed cursor in some XML tag.
I'm checking whether selected line started with "<" and ends with ">", but doesn't start with "</>". - Unfortunately it's failing if I have following tag structure:
![image](https://user-images.githubusercontent.com/24554795/33207548-61142dda-d10e-11e7-82db-17f569b4b851.png)

As you can see selected line doesn't have "<" or ">" - I need improvement in that place.

**Comment by piotrzarzycki21** [comment]
I think I have finished and cover all common scenario. If anyone find some case where quotes are not auto close reopen this one.
