### ISSUE TITLE
Validate the Target Path for Git Clone and SVN Checkout

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#750]
When I try to clone a Git project to path that already exists:
![image](https://user-images.githubusercontent.com/24532731/98276483-a7a49c00-1f5b-11eb-9c07-09216899c245.png)

I get this error, and then I need to clone the project again:
![image](https://user-images.githubusercontent.com/24532731/98276511-b2f7c780-1f5b-11eb-88da-35e5c64e8347.png)

Instead, Moonshine should validate whether the path already exists, similar to how the New Project form works.   This should apply to SVN Checkout requests as well.

**Comment by rat-moonshine** [comment]
It's fixed and ready for a test.

**Comment by piotrzarzycki21** [comment]
I'm assuming this is not critical ? We have released yesterday Moonshine, definitely without that fix.

**Comment by rat-moonshine** [comment]
Yeah, it's fair to keep this for v3.1.0 release.

**Comment by JoelProminic** [comment]
Yeah, I intended for this to wait for the 3.1.0 release.

I tested @rat-moonshine's updates and it seems to be working properly.

On my case-sensitive Mac, I saw that it allowed names with different case (i.e. "Royale-Examples" vs "royale-examples").  However,on a case insensitive Mac or Windows machine, it properly considered these names duplicates.
