### ISSUE TITLE
"New Branch" Remote Push

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#754]
I revisited the Git > New Branch logic for #751 and #533 recently, and I was confused by the "Push newly created branch to remote".  @rat-moonshine confirmed that the [code](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/commands/CreateCheckoutNewBranchCommand.as) is automatically pushing the new branch to the remote repository in this case.   Is this desirable default behavior for this use case?

I found that if I disable this option and create a branch, the new branch does not show up in Git > Switch to Branch.   @rat-moonshine reported that even if he left this option enabled, the branch list was not updated until he did a manual Git > Push on the branch.

@Aszusz, do you have a Git command that would show both the remote and local branches?  Do you have any opinions on this default behavior?

**Comment by Aszusz** [comment]
> @Aszusz, do you have a Git command that would show both the remote and local branches? Do you have any opinions on this default behavior?

@JoelProminic, the usual commands for showing branches in Git are:
- `git branch` -- show only local branches
- `git branch --remote` -- show only remote branches
- `git branch --all` -- show all branches

As for the default behavior, I suggest showing initially only local branches with an option to show only remote branches. I motivate this with the following:
- You usually don't want to look at local and remote branches at the same time
- Most of the time you're interested only in local branches. Some repositories have *a lot* of remote branches.

Here is a potential UI for this:

![switch-to-branch-local](https://user-images.githubusercontent.com/7197014/99541270-e5201500-29b0-11eb-9b4f-ba0b018c8961.png)

![switch-to-branch-remote](https://user-images.githubusercontent.com/7197014/99541277-e8b39c00-29b0-11eb-8055-f29714e8b25e.png)

**Comment by rat-moonshine** [comment]
"Push newly created branch to remote" option is now fixed during a new branch creation:

"Push to remote" option selected | Expected | Actual
--------------|-------------------|---------------
No | 1. Newly created branch will not show in the branch list<br/>2. User needs to perform Git/Push to avail the branch in the branch list | Confirm
Yes | 1. Moonshine perform the Push command automatically post-branch-creation<br/>2. Newly created branch immediately show in the branch list | Confirm

**Comment by rat-moonshine** [comment]
"Push newly created branch to remote" option is now default unselected in the new branch creation window.

**Comment by JoelProminic** [comment]
I think we should update the Switch to Branch prompt to work like @Aszusz suggested:  https://github.com/prominic/Moonshine-IDE/issues/754#issuecomment-729716745

We also need a way to push a new local branch to remote.  When I try Git > Push when I have checked out a local branch, it currently does not appear in the remote branch list.

**Comment by JoelProminic** [comment]
We discussed during the meeting whether we wanted to show a unified list of branches using the output from `git branch --all`:

    $ git branch --all
      TestBranch
      TestRemote
      main
    * test-11-25
      remotes/origin/HEAD -> origin/main
      remotes/origin/TestBranch
      remotes/origin/TestRemote
      remotes/origin/main
      remotes/origin/test-11-25

However, the branches are duplicated between local and remote.  This is unnecessary additional information in most cases, and it may confuse some users.

I think I would like to keep them separate according to @Aszusz's original plan.

**Comment by rat-moonshine** [comment]
The "Switch to Branch" [proposed](https://github.com/prominic/Moonshine-IDE/issues/754#issuecomment-729716745) layout is completed:

- User can toggle list-options between local and remote branch types - local default
- Added busy-animation while toggling/fetching the list
- Retains last-selected type for next time window open - for application session only

![image](https://user-images.githubusercontent.com/24370870/101126556-c44af700-3621-11eb-9fcc-54f9cb1715bf.png)

@JoelProminic you can give a test with the following branch builds:
macOS: https://bamboo.prominic.net/browse/MS-MGOBB-298/artifact
Windows: https://bamboo.prominic.net/browse/MS-MGWBB-153/artifact

**Comment by JoelProminic** [comment]
This seemed to work well in my initial macOS tests.  We can merge this into master.

**Comment by rat-moonshine** [comment]
This issue is now merged into 'master'.

**Comment by Aszusz** [comment]
I tested this on master and in my opinion it works correctly. I think we can close this issue.

**Comment by rat-moonshine** [comment]
This may be something unrelated to how we fetch/parse the remote branch information in Moonshine, but I see some oddity to one of my private repository output I thought to note down here.

This is how the available remote branches listed to https://github.com:
![image](https://user-images.githubusercontent.com/24370870/102856907-73266a00-444d-11eb-92a7-d4dc1eac3d4e.png)

While testing the branch listing commands (which we use in Moonshine codes, too), I see some differences in return; In the case of remote-branches it omits all the branch name starts with 'issue617remote*':

```
$ git branch
  issue617remote2
  issue617remote3
  issue617remote4
* issue617remote5
  main

$ git branch -r
  origin/HEAD -> origin/main
  origin/main
```
