### ISSUE TITLE
Error on Git Pull

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#758]
I noticed that Git > Pull is failing for every project I tried in the latest master build (macOS Catalina, non-Sandbox build).  I can reproduce this on a new project:
1. Git > Manage Repositories
2. Clone https://github.com/prominic/Moonshine-SDK-Installer .  You onlly need to oepn the MoonshineSDKInstaller project
3. Git > Pull. BUG:  this error is displayed on the console:

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.utils::UtilsCore$/getEncodedForShell()
    : 	at actionScripts.plugins.git.commands::PullCommand()
    : 	at actionScripts.plugins.git::GitHubPlugin/onPullRequest()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
    : 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
    : 	at actionScripts.ui.menu::MenuPlugin/redispatch()
    :
    : Click here to Report a Bug

**Comment by rat-moonshine** [comment]
I confirm this problem seen on Windows tests, too.

This should have fixed now. Please, check.

**Comment by JoelProminic** [comment]
I confirmed that this is fixed with the non-Sandbox build on macOS Catalina
