### ISSUE TITLE
Flash EOL Concern

### ISSUE THREAD

**Issue by davis-matthew** [prominic/Moonshine-IDE#768]
Hi Moonshine-IDE team,

I recently stumbled across your IDE and it is very intuitive; good job on making it new-user friendly.

Considering that the majority of the IDE itself seems to be written in actionscript, does this mean it will be unable to work with the flash runtime when adobe flash player reaches EOL the start of next year? 

I'm not sure if the flash EOL will affect online .swf files only, or if local (non-browser) programs will be subject to the termination as well. I am curious if there's any anticipated problems with the continued use of the IDE, along with other local .swf programs.

**Comment by piotrzarzycki21** [comment]
Hello @davis-matthew ,

First of all Thank you for using Moonshine! We are happy to hear that you like usability - I hope it will be even better in future. 
The answer to your question is that - Moonshine will be working without any problems after EOL. We are using [Adobe Air](https://www.adobe.com/products/air.html) to run Moonshine on desktop which exists after EOL. 
If there will be any problems with usage - please let us know here and we are happy to help.

Piotr

**Comment by davis-matthew** [comment]
Thank you for answering my question. It was very helpful.
