### ISSUE TITLE
[Haxe] Code completion closing immediately when I type something

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#772]
Code completion closing and do not show items when I'm trying to use it. List doesn't open at all when I'm trying to find some local variables in calss. Here is short recording in MoonshineGUICore.

![codecompletionbroken](https://user-images.githubusercontent.com/24554795/104732750-f29e1500-573d-11eb-92ae-fea5ba7a2a3c.gif)

My configuration: `Moonshine 3.1 Build 324`
Windows 10 Home
Java version: 
```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Xms256m -Xmx1g
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```
![moonshine](https://user-images.githubusercontent.com/24554795/104733928-ba97d180-573f-11eb-8dda-91072134a6f2.png)

**Comment by joshtynjala** [comment]
I confirm that the results in Moonshine's completion list seem to be different than VSCode when trying to access openResourceButton. Perhaps I need to update the Haxe language server to a newer version. Or maybe Moonshine is incorrectly filtering out results that should be visible. I'll take a look.

**Comment by piotrzarzycki21** [comment]
This issue has been fixed, but I do experience new one. Do you want me to raise separate issue ? 

![leftovers_codecompletion](https://user-images.githubusercontent.com/24554795/105871288-71763600-5ff9-11eb-9ba5-0150d71224d6.gif)

**Comment by joshtynjala** [comment]
Yes, please raise a separate issue. Can you also check if this happens for AS3 too?  If it only happens with Haxe, it's probably related to the language server implementation. If it affects other languages too, someone else can look into the issue instead of me.

**Comment by piotrzarzycki21** [comment]
> Yes, please raise a separate issue. Can you also check if this happens for AS3 too? If it only happens with Haxe, it's probably related to the language server implementation. If it affects other languages too, someone else can look into the issue instead of me.

It does not happen with AS3 - I have checked in Royale project. Additionally sometimes code completion stop working suddenly - When I close and reopen file it gets back work. I cannot isolate issue yet, but if I manage to I will raise bug.
