### ISSUE TITLE
Switch to Harman AIR

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#773]
In order to switch to the latest versions of AIR, we need to switch from Adobe to Harman AIR.

**Comment by rat-moonshine** [comment]
The problem we noticed on using the Harman AIR SDK that it was required to download ApacheFlex+AdobeAIR first, and then extract the HarmanAIR to the SDK folder, to have this worked in Moonshine. This could be troublesome if we want to use Harman AIR SDK for Moonshine and provide a distribution for the users through Moonshine SDK Installer. 

We talked with Andrew from Harman on this, if we can simply extract the HarmanAIR in the ApacheFlex directory without needing to download AdobeAIR during the process. By his understanding, this should work. However, Moonshine fails to compile a project with such installation but passed for the installation where HarmanAIR extracted over Flex+AdobeAIR.

```
: Command: "/Users/devsena/Downloads/apache-flex-sdk-4.16.1-bin/bin/mxmlc" -load-config+=obj/NewFlexDesktopProjectConfig.xml -optimize=false +configname=air -debug=true
: SDK path: /Users/devsena/Downloads/apache-flex-sdk-4.16.1-bin
: Sending to mxmlc: "/Users/devsena/Downloads/apache-flex-sdk-4.16.1-bin/bin/mxmlc" -load-config+=obj/NewFlexDesktopProjectConfig.xml -optimize=false +configname=air -debug=true
: Loading configuration file /Users/devsena/Downloads/apache-flex-sdk-4.16.1-bin/frameworks/air-config.xml
: Loading configuration file /Users/devsena/Downloads/apache-flex-sdk-4.16.1-bin/frameworks/air-config.xml
: Loading configuration file /Users/devsena/Desktop/NewFlexDesktopProject/obj/NewFlexDesktopProjectConfig.xml
: Loading configuration file /Users/devsena/Desktop/NewFlexDesktopProject/obj/NewFlexDesktopProjectConfig.xml
: Apache Flex Compiler (mxmlc)
: Version 4.16.1 build 20171115
: Copyright 2017 The Apache Software Foundation.
: Apache Flex Compiler (mxmlc)
: Version 4.16.1 build 20171115
: Copyright 2017 The Apache Software Foundation.
: /Users/devsena/Downloads/apache-flex-sdk-4.16.1-bin/frameworks/air-config.xml(64): Error: unable to open '{airHome}/frameworks/libs/air/airglobal.swc'
:       </external-library-path>
: /Users/devsena/Downloads/apache-flex-sdk-4.16.1-bin/frameworks/air-config.xml(64): Error: unable to open '{airHome}/frameworks/libs/air/airglobal.swc'
:       </external-library-path> 
```

It is still unclear why this error but Andrew suggested a few probability and test-suggestion:
- Test the compilation command on Terminal 
- (thought) if any process hold-up happening against the said SWCs in Moonshine, maybe during code-completion etc.

In my quick test on macOS, I able to complete the compilation when run on a Terminal prompt. However, I asked for Java access permission window twice, which felt odd to me at that time but I couldn't able to receive that window anymore so I can keep a screenshot. 

The above compilation with Harman SDK problem also noticed in Windows 10 usage, though I don't think it requires any Java access permission as macOS build may do.

I need to give a fresh test on Windows running the compilation on CMD, to test if that also pass the compilation as was in macOS. @piotrzarzycki21 suggested he'll give a test on Visual Studio Code using the Flex+HarmanAIR way. 

The question remains there, what makes it different for Moonshine if the Harman AIR extracted over Flex+AdobeAIR that works but not when Harman AIR extracted over Flex binaries-only.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I can confirm that exactly same issue I have in VSCode, so it is not something in our code.

**Comment by joshtynjala** [comment]
The Flex SDK installer Ant script doesn't seem to have fully completed.

This line in the default air-config.xml:

```
<path-element>{airHome}/frameworks/libs/air/airglobal.swc</path-element>
```

Should have been replaced by this instead:

```
<path-element>libs/air/airglobal.swc</path-element>
```

**Comment by piotrzarzycki21** [comment]
> The Flex SDK installer Ant script doesn't seem to have fully completed.
> 
> This line in the default air-config.xml:
> 
> ```
> <path-element>{airHome}/frameworks/libs/air/airglobal.swc</path-element>
> ```
> 
> Should have been replaced by this instead:
> 
> ```
> <path-element>libs/air/airglobal.swc</path-element>
> ```

We are not using Ant @joshtynjala to install Air sdk. Scenario is:

1) I'm downloading Flex binarise -> https://flex.apache.org/download-binaries.html
2) I'm downloading Harman Air for Flex Developers
3) I'm unpacking 1 and 2 to one folder - I would like to use that as a valid SDK.

**Comment by ajwfrost** [comment]
Hi

In my install of the latest Flex SDK, I'm getting two files here:
air-config.xml -> contains the correct element `libs/air/airglobal.swf`
air-config-template.xml -> contains the other version you've provided there, `{airHome}/frameworks/libs/air/airglobal.swc`

From Adobe's AIR 32 SDK for Flex, I don't see that it contains either file; same for us though in our SDK 33 for Flex developers.

My installation was done using that SDK installer; I've also just checked a location that had the raw (source) Flex SDK in it, and this has both files containing the `{airhome}`  path...

In all this (and have just seen the above comment from Piotr appear) there's nothing I can see that would make it work with/without the Adobe AIR SDK added in before the Harman one..   very curious!

**Comment by JoelProminic** [comment]
Moonshine itself has been converted to use Harman AIR in the latest Bamboo builds.

We have a separate issue for the SDK Installer updates:  https://github.com/prominic/Moonshine-SDK-Installer/issues/32

From my quick test, it looks like we don't need any additional updates in Moonshine to use the Harman AIR SDK.
