### ISSUE TITLE
Move "New Workspace" to Haxe

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#779]
Following popup should be moved to Haxe library. Menu **File** -> **Workspace** -> **Create New Workspace**

![new_workspace](https://user-images.githubusercontent.com/24554795/106325116-93cab680-627a-11eb-843c-2e6ba37c8b8b.png)

**Comment by piotrzarzycki21** [comment]
@joshtynjala I have another issue which is mystery to me. I have created [NewWorkspace](https://github.com/prominic/Moonshine-IDE/blob/features/issue_779_move_new_workspace_to_haxe/ide/MoonshineGUICore/src/moonshine/plugin/workspace/view/NewWorkspaceView.hx) view, but for some reason I cannot type anything in text input. I wish I could provide you more details but there is not. Maybe I'm missing something I don't know. Everything is on branch [features/issue_779_move_new_workspace_to_haxe](https://github.com/prominic/Moonshine-IDE/tree/features/issue_779_move_new_workspace_to_haxe)

**Comment by joshtynjala** [comment]
When you add the NewWorkspace view as a popup, be sure to pass it focus using Flex's assignFocus() method.

Here's an example from one of my converted views:

https://github.com/prominic/Moonshine-IDE/blob/4549316c380dac8b70c47e80367337567503b849/ide/MoonshineSharedCore/src/actionScripts/plugin/findResources/FindResourcesPlugin.as#L73

**Comment by piotrzarzycki21** [comment]
@joshtynjala In your documentation you have 

> ERROR is the text input's state when an error string has been set.

Where actually I can set that error string ? Does TextInput have default error behavior which appear when I enter that error string ?

**Comment by joshtynjala** [comment]
The `errorString` property is not implemented in the Haxe/OpenFL version yet. I plan to add it soon.

**Comment by piotrzarzycki21** [comment]
Hey @joshtynjala - How should we treat icons, which were used in original source code Moonshine ? I would like to use in newly ported Haxe code one of the Moonshine's icon. I see that there is Assets manager, but how to use in our library and when ?

**Comment by piotrzarzycki21** [comment]
I'm closing this issue - view has been moved to Haxe and merge to master.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 OpenFL has asset management, but we are not yet using it in Moonshine. I believe that it requires building the app with OpenFL (not just a .swc library), so switching to OpenFL asset management will probably be one of the last tasks to complete when we remove Flex.

In the meantime, you can embed icons, similar to `[Embed]` in ActionScript.

Here's how I embedded an icon for one component (which is still in another branch, and I need to merge it).

https://github.com/prominic/Moonshine-IDE/blob/d70b404894f101026b0ffb000412ef55f6931abe/ide/MoonshineGUICore/src/moonshine/theme/assets/FolderOpenIcon.hx

It becomes a class that extends BitmapData. To use it, I would call `new Bitmap(new FolderOpenIcon())`.

**Comment by piotrzarzycki21** [comment]
> Here's how I embedded an icon for one component (which is still in another branch, and I need to merge it).

I will create branch for my improvements and take yours one into it. I hope you will merge it soon.

**Comment by rat-moonshine** [comment]
> 
> 
> @piotrzarzycki21 OpenFL has asset management, but we are not yet using it in Moonshine. I believe that it requires building the app with OpenFL (not just a .swc library), so switching to OpenFL asset management will probably be one of the last tasks to complete when we remove Flex.
> 
> In the meantime, you can embed icons, similar to `[Embed]` in ActionScript.
> 
> Here's how I embedded an icon for one component (which is still in another branch, and I need to merge it).
> 
> https://github.com/prominic/Moonshine-IDE/blob/d70b404894f101026b0ffb000412ef55f6931abe/ide/MoonshineGUICore/src/moonshine/theme/assets/FolderOpenIcon.hx
> 
> It becomes a class that extends BitmapData. To use it, I would call `new Bitmap(new FolderOpenIcon())`.

@joshtynjala in this case we don't have access to many properties (to `Bitmap`) to set its position, behavior, i.e. layoutData, visible, buttonMode (in case we want the image to be clickable) etc. What could be best approach in that case, to create separate containers for each of the Bitmap? But that could be more of codes when there is many Bitmap in the interface.

Also, can we has a static class containing all the `BitmapData` references instead of creating separate Haxe class for each image?

**Comment by joshtynjala** [comment]
> in this case we don't have access to many properties (to Bitmap) to set its position, behavior, i.e. layoutData, includeInLayout, buttonMode (in case we want the image to be clickable) etc. What could be best approach in that case, to create separate containers for each of the Bitmap? But that could be more of codes when there is many Bitmap in the interface.

That's pretty the same as it would be in Flex. BitmapData must be used by a Bitmap. You could add it to a Feathers UI component as a skin. For instance, if the image should be clickable, it should probably be used as a `Button` skin or icon.

> Fortunately, using the AssetLoader was providing me all the properties that I may need, but it may miss the embedding feature.

When we can use OpenFL's asset management for embedding assets in the future, we'll be able to use AssetLoader. As I mentioned elsewhere, I don't think using OpenFL's asset management is possible until Moonshine is fully converted Haxe and we can build it with `openfl build air`. I mean... it might be technically possible, but I suspect it will be non-trivial to implement its manifest and preloading system on the Flex side. I think it's better to wait.

> Also, can we has a static class containing all the BitmapData references instead of creating separate Haxe class for each image?

I don't know. This is what I got to work with some trial and error. The Haxe docs don't seem to have much in the way of examples for Flash stuff anymore. I think I might have pieced it together by looking at very old docs and blog posts.

**Comment by JoelProminic** [comment]
I did a quick review and I don't see any problems with the updated interface:
![image](https://user-images.githubusercontent.com/24532731/112547137-5bca8600-8d88-11eb-823f-6dc2286cc585.png)

**Comment by rat-moonshine** [comment]
> > in this case we don't have access to many properties (to Bitmap) to set its position, behavior, i.e. layoutData, includeInLayout, buttonMode (in case we want the image to be clickable) etc. What could be best approach in that case, to create separate containers for each of the Bitmap? But that could be more of codes when there is many Bitmap in the interface.
> 
> That's pretty the same as it would be in Flex. BitmapData must be used by a Bitmap. You could add it to a Feathers UI component as a skin. For instance, if the image should be clickable, it should probably be used as a Button skin or icon.

@joshtynjala , is this skin-declaration way is right, or do you suggest any change? I'm trying to have this rendered over LayoutGroup:

```
private function setImageDownloadWithLabelStyles(layout:LayoutGroup):Void 
{
		var downloadIconBitmap = new DownloadIconWithLabel(cast(layout.width, Int), cast(layout.height, Int));
		var backgroundSkin = new Shape();
		backgroundSkin.graphics.beginBitmapFill(downloadIconBitmap, new Matrix(), false);
		backgroundSkin.graphics.drawRect(0, 0, layout.width, layout.height);
		backgroundSkin.graphics.endFill();

		layout.backgroundSkin = backgroundSkin;
}
```

**Comment by joshtynjala** [comment]
While you can generally use any type of display object as a skin, I generally try to use one of the skin classes if it can do what is needed. So, in this case, I'd probably use a RectangleSkin with a Bitmap fill style.

```hx
var downloadIconBitmap = new DownloadIconWithLabel(cast(layout.width, Int), cast(layout.height, Int));

var backgroundSkin = new RectangleSkin();
backgroundSkin.fill = Bitmap(downloadIconBitmap, new Matrix(), false);
backgroundSkin.width = layout.width;
backgroundSkin.height = layout.height;

layout.backgroundSkin = backgroundSkin;
```

If the LayoutGroup is something that's supposed to be clickable, as your previous question implied, a Button may be more appropriate.

**Comment by rat-moonshine** [comment]
Your declaration is more simplified, thanks! 

Yeah, I shall consider for Button in case of the icons which requires to track MouseEvent, I do remember that suggestion )
