### ISSUE TITLE
Global "Search" doesn't work in Haxe projects

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#780]
When I use search (CTRL+SHIFT+F) doesn't returns any results in Haxe type of projects.

**Comment by piotrzarzycki21** [comment]
Does menu Edit -> Find should open same window as shortcut CTRL+SHIFT+F ?

**Comment by rat-moonshine** [comment]
`Edit -> Find (Ctrl+F)` and `Project -> Search (Ctrl+Shift+F)` are altogether different functionalities, when one search in the particular opened editor another throughout the project(s)

I have fixed the issue, please test with the new nightly build when available. I see there is some error compilation at Bamboo at this point, these errors are not related to this one, though.

**Comment by rat-moonshine** [comment]
Bamboo builds are fixed. You can proceed for a try @piotrzarzycki21 .

**Comment by rat-moonshine** [comment]
Let's close this if done tests @piotrzarzycki21 .

**Comment by piotrzarzycki21** [comment]
Working perfectly! Thanks :)
