### ISSUE TITLE
FeathersUIWrapper throw NPE when on focus out

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#781]
This exception is intermittent. It occurs when I close some Haxe view, sometimes it also being thrown after some time, when view is closed.

```
[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.
at actionScripts.ui::FeathersUIWrapper/feathersUIWrapper_focusOutHandler()[D:\Work\projects\Prominic.NET\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\ui\FeathersUIWrapper.as:312]
```

![npe_stage_haxe](https://user-images.githubusercontent.com/24554795/106769089-e3273300-663c-11eb-8ea1-185bca118e75.png)

**Comment by joshtynjala** [comment]
Thanks! Fixed on master.
