### ISSUE TITLE
Can't Install Nightly Using Moonshine

### ISSUE THREAD

**Issue by Bilbosax** [prominic/Moonshine-IDE#784]
I tried to install the nightly build of 0.9.8 Royale using you built in 3rd Party Moonshine Tools and it repeatedly fails.  But there is a bigger problem because it seems to have deleted my previous install before downloading the new, and thus, I cannot work at all on my project at the moment.  Other than moonshine, I can't seem to find a way to download the nightly builds.  The links on the Royale page don't work either.  ???  Here is the error

Installer path: C:\Program Files\MoonshineSDKInstaller
Installer version 3.7.0 (windows)
Available Memory: 39956480 (64-bit)
Using Locale: en_US
Fetched the SDK download mirror URL from the CGI.
Downloading royale from: http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/apache-royale-0.9.8-bin-js.zip
Unable to download royale

**Comment by piotrzarzycki21** [comment]
@rat-moonshine It looks like we need to improve that area. @Bilbosax please send me an email I will provide you Maven distribution build from today which you will be able to use in your project. My email piotrzarzycki21@gmail.com

**Comment by piotrzarzycki21** [comment]
I think we should first check if url is working than make any actions

**Comment by rat-moonshine** [comment]
Yeah, I guess that would be a good safe-guard.

**Comment by rat-moonshine** [comment]
I have moved this issue to the Moonshine SDK Installer repository - https://github.com/prominic/Moonshine-SDK-Installer/issues/34. @Bilbosax , please response to this newly created issue. 

I'm closing this.
