### ISSUE TITLE
Add hamburger menu to show tabs which couldn't fit into the window

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#79]

**Comment by piotrzarzycki21** [comment]
I think I have finished that feature. Some screenshot with hamburger menu with tabs list which didn't fit into the available space.

![image](https://user-images.githubusercontent.com/24554795/33395533-211cc1e2-d546-11e7-9acf-84958e7a43b1.png)

It would be great if someone could take a look and play a bit with this one on my branch `features/add_hamburger_menu_for_tabs_79`. If everything will be ok I could add this feature to 1.7.0.

**Comment by piotrzarzycki21** [comment]
More description:
1) Tabs which do not fit into the available space will be available under hamburger menu
2) If user open file/settings etc. new tab will be placed at the end and become selected as it was before,
3) If there is no available space for opened tab, the second tab counting from "Home" will be removed from main view and placed under hamburger menu.
4) If user clicks on any of tab in hamburger menu it will be removed from menu and placed at the end of the list on the main view, next step "3" will be repeated

**Comment by rat-moonshine** [comment]
I gave a test to this. I confirm adding tabs larger than display area got added inside the new menu. Selecting any file from the menu make the editor as current selection. 

However, there was a feature auto-focusing an opened editor seems failed to work in this modification. When you have few tabs opened in the editor at a time, re-opening the file (from sidebar) auto-selects and focus the opened editor again. I noticed this feature is not works anymore when the menu is visible.

Maximize and restore of Moonshine window fits the tabs and the menu accordingly.

**Comment by piotrzarzycki21** [comment]
Thank you for testing! I will try to look into that issue before Monday.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine mentioned issues has been fixed. You can try to test it.

**Comment by rat-moonshine** [comment]
I gave a test to @piotrzarzycki21 's latest updates/fix to re-focus on opened editor after double-click on a file in sidebar. I found tab selection problem when maximize/restore the Moonshine window. Following is a test simulation:

![tabselectionproblem](https://user-images.githubusercontent.com/24370870/33549357-32148692-d910-11e7-8bb0-904b2b4e93b0.gif)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I was able to fix that issue. I see some room for improvements in case when tabs are added/removed, but I will leave it for different issue. If you won't experience any crucial tomorrow I will merge it to the master and we can start an release.

**Comment by rat-moonshine** [comment]
We need some margin where hamburger menu suppose to show - this following case noticed in window maximized state:
![image](https://user-images.githubusercontent.com/24370870/33591884-1d1c50b4-d9ae-11e7-853d-b3df6fc1610f.png)

**Comment by rat-moonshine** [comment]
I gave some more test to the branch version of hamburger menu, and I didn't found any noticeable problem so far. I think if the above problem handled it's good to bundle with 1.7.0.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have merged your changes which fixes issue #88 and after that I think will have more work here to do. We need to postpone that feature for the next release. Issue right now is, that when user close the project it will close all opened Tabs, but won't deal with editors which are part of hamburger menu. I need to implement some mechanism which deal with it and it will take more time.

**Comment by piotrzarzycki21** [comment]
Issue with overlapping tabs by hamburger menu and problem with closing after merge with master has been resolved.
