### ISSUE TITLE
Load workspace dropdown list UI improvements after Feathers UI update

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#793]
@joshtynjala I'm going to merge that changes to master. Dropdown list doesn't look perfect, but I'm assuming this is something which is already addressed in upcoming Feathers ui update. Let me know. 

![switch_worskpace](https://user-images.githubusercontent.com/24554795/111903443-9fe52000-8a42-11eb-90d3-8e7daffd629b.png)

_Originally posted by @piotrzarzycki21 in https://github.com/prominic/Moonshine-IDE/issues/775#issuecomment-803561515_

**Comment by piotrzarzycki21** [comment]
This issue is just a reminder that I may have some work to do after Feathers UI update.

**Comment by joshtynjala** [comment]
> but I'm assuming this is something which is already addressed in upcoming Feathers ui update

Yes, I think that it should be better after the update. The OpenFL update seems to be ready, so I'll try to do a Feathers UI update soon after.

**Comment by JoelProminic** [comment]
In addition to the visual oddities with the control, I see that the workspace list is not sorted in my tests on macOS.   We can check this after the update.

**Comment by JoelProminic** [comment]
I see that the dropdown UI is updated on macOS.  This looks good:
![image](https://user-images.githubusercontent.com/24532731/114748662-c03d8d00-9d17-11eb-9588-28bbd03c11cf.png)

Once the Windows build is working again, we'll confirm it there as well.

**Comment by JoelProminic** [comment]
Ah, I see that the combobox is still not sorted correctly on macOS.  Is this a similar issue to #717?

**Comment by piotrzarzycki21** [comment]
@JoelProminic do you expect alphabetical sort or something else ?

**Comment by piotrzarzycki21** [comment]
Closing this issue cause original one is fixed and sorting issue is being raised separately.

**Comment by JoelProminic** [comment]
Yes, I'm expecting alphabetical sorting.   Is it sorted by some other logic (like when the workspace was created) currently?

Is there a separate issue for this?   We have created and resolved other issues for sorting on macOS, but this seems to be a new issue.
