### ISSUE TITLE
New workspace warning improvement

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#794]
Currently New Workspace warning when workspace exists looks like that:
![workspace_exists](https://user-images.githubusercontent.com/24554795/111903959-c0ae7500-8a44-11eb-8215-8ccaae78dce6.png)

I would like to improve this to use errorString once @joshtynjala implements it -> https://github.com/prominic/Moonshine-IDE/issues/779#issuecomment-772701446

**Comment by piotrzarzycki21** [comment]
I con has been added I will wait with merge my branch till @joshtynjala merge his changes from [feathersui](https://github.com/prominic/Moonshine-IDE/tree/feathersui) branch.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 I don't think that your icon relies on anything from my feathersui branch, or did I miss something?

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 I don't think that your icon relies on anything from my feathersui branch, or did I miss something?

Actually it's not, but I wanted to place it in the same folder and avoid conflicts, but maybe it won't be bad if I create same folder in master.

**Comment by joshtynjala** [comment]
I think it will be fine to use the same folder. As long as the image/code files have different names, the folders should merge.

**Comment by piotrzarzycki21** [comment]
Thanks Josh! It's added to master.
