### ISSUE TITLE
Move "Search" (CTRL+SHIFT+F) to Haxe

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#798]
Next to move will be following view:
![search](https://user-images.githubusercontent.com/24554795/112451634-05445400-8d56-11eb-9d3b-1987fd696824.png)

**Comment by piotrzarzycki21** [comment]
@joshtynjala is it something which I can work on ? Is it not a collision to your current work on branches etc ?

**Comment by joshtynjala** [comment]
Yes, you can work on that. There should be a lot of similarities to the `FindReplaceView`, so be sure to copy/paste from that component where appropriate.

**Comment by piotrzarzycki21** [comment]
> Yes, you can work on that. There should be a lot of similarities to the `FindReplaceView`, so be sure to copy/paste from that component where appropriate.

Yep. I literally started from duplicating that view and just changing it. ;) Thanks!
