### ISSUE TITLE
[Run Customization] Advance run customization options for mobile projects

### ISSUE THREAD

**Issue by JustinProminic** [prominic/Moonshine-IDE#8]
We talked about this in past for a couple of times. We need some optimization section to mobile project run.

At this moment Moonshine only supports running any mobile projects in an AIR Android simulator, despite if the project targeted for Android or iOS, and with a specific mobile screen size - Nexus One.

We need some customization option where a user can choose what type of simulator they want to run (iOS or Android), what screen size (from a list of different pre-added mobile model references) etc. We also want to have options to select run platform type (simulator or physical device via USB), but the initial goal should be AIR simulator.

**Comment by JustinProminic** [comment]
Modification starts in following section for these changes:
`[Project] > Settings > Run`

**Comment by JustinProminic** [comment]
Following things are done so far:
- Saving customization option values to .as3proj
- Retrieving the saved values from file and populates in the UI
- UI state logic was done
- A list of few/initial mobile device generation for AIR simulator from configuration XML

To do for AIR simulator run:
- Extending the list of mobile devices for AIR simulator
- Binding values between saved customization options to application launcher code (Build & Run)

**Comment by rat-moonshine** [comment]
Modification starts in following section for these changes:
`[Project] > Settings > Run`

**Comment by rat-moonshine** [comment]
Following things are done so far:
- Saving customization option values to .as3proj
- Retrieving the saved values from file and populates in the UI
- UI state logic was done
- A list of few/initial mobile device generation for AIR simulator from configuration XML

To do for AIR simulator run:
- Extending the list of mobile devices for AIR simulator
- Binding values between saved customization options to application launcher code (Build & Run)

**Comment by rat-moonshine** [comment]
Mobile simulator launch codes are now bind with new run customization option for mobile; one can found the options by right-clicking on project root in sidebar and `Settings > Run`.

**Comment by rat-moonshine** [comment]
The mobile device list is now configurable. One can add, edit or remove devices from the list.
