### ISSUE TITLE
Problems with Project Search

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#801]
While testing the new interface for #798 (in macOS 10.15.7 (Catalina)), I noticed some problems.  I think at least some of these issues are unrelated to the Haxe conversion, so we might want to organize this into multiple issues.
- When opening Project > Search with the "Selected project" scope, this should show the current selected project by default (or parent project, if a file or folder is selected). 
- The Selected project combobox is not sorted.   I'm testing on macOS , so this may be another case where the sorting doesn't work as expected (i.e. #717).
- If I change the selected project before typing a search string, then I can't put the cursor in the search string field again until I switch to another window.
- If I preview a replacement, there is no way to return to the Replace form.  This may be more of an improvement request than a bug...
- If I replace text in this interface, it removes all indentation.

Here is a test procedure to reproduce the above problems:
1. Make sure you have at least one project open
2. Create a new Java Gradle project (other projects should work as well, but I have not tested them yet).
3. Select the new project in the sidebar
4. Choose Project > Search from the menu
5. BUG:  another project is selected by default.  This may not trigger depending on the sorting for the combobox
6. Change combobox to the project created above
7. Click on the top field.  BUG:  nothing happens
8. Switch to another window and back to Moonshine
9. Click on the top field again.  This time, the cursor appears, and you can type text
10. Enter "Hello"
11. Click Replace
12.  For the Replace text, enter "Hi"
13. Click "Preview"
14. Needs improvement:  There is no way to directly return to the previous prompt if I decide I want to change the replace string to "Hi,".  I have to run the steps above again.
15. Click "Replace Selected"
16.  Open the modified file
17.  BUG: the string was replaced, but all indentation has been removed from the file:

```
public class TestJavaGradle_0408
{
public static void main(String args[])
{
System.out.println("Hi World!");
}
}
```

**Comment by JoelProminic** [comment]
Also, if I try to search the entire workspace (on macOS 10.15.7), I get an error like this on the console:

    : Error #1034
    : TypeError: Error #1034
    : 	at components.views.other::SearchInProjectView/getProjectPaths()
    : 	at components.views.other::SearchInProjectView/getSearchObject()
    : 	at components.views.other::SearchInProjectView/onCreationCompletes()
    : 	at components.views.other::SearchInProjectView/___SearchInProjectView_Canvas1_creationComplete()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at mx.core::UIComponent/set initialized()
    : 	at mx.managers::LayoutManager/doPhasedInstantiation()
    : 	at mx.managers::LayoutManager/doPhasedInstantiationCallback()
    :
    : Click here to Report a Bug

**Comment by piotrzarzycki21** [comment]
> * When opening Project > Search with the "Selected project" scope, this should show the current selected project by default (or parent project, if a file or folder is selected).

This has been fixed.

**Comment by piotrzarzycki21** [comment]
>If I change the selected project before typing a search string, then I can't put the cursor in the search string field again until I switch to another window.

I think we should ignore this issue - it is minor one and I believe it will be gone once we migrate Moonshine fully.

**Comment by piotrzarzycki21** [comment]
>If I preview a replacement, there is no way to return to the Replace form. This may be more of an improvement request than a bug...

This one can be considered as part of migration #808

**Comment by piotrzarzycki21** [comment]
> * If I replace text in this interface, it removes all indentation.

I have raised separate issue for that #809

**Comment by piotrzarzycki21** [comment]
> Also, if I try to search the entire workspace (on macOS 10.15.7), I get an error like this on the console:
> 
> ```
> : Error #1034
> : TypeError: Error #1034
> : 	at components.views.other::SearchInProjectView/getProjectPaths()
> : 	at components.views.other::SearchInProjectView/getSearchObject()
> : 	at components.views.other::SearchInProjectView/onCreationCompletes()
> : 	at components.views.other::SearchInProjectView/___SearchInProjectView_Canvas1_creationComplete()
> : 	at flash.events::EventDispatcher/dispatchEvent()
> : 	at mx.core::UIComponent/dispatchEvent()
> : 	at mx.core::UIComponent/set initialized()
> : 	at mx.managers::LayoutManager/doPhasedInstantiation()
> : 	at mx.managers::LayoutManager/doPhasedInstantiationCallback()
> :
> : Click here to Report a Bug
> ```

I have raised separate issue #810

**Comment by piotrzarzycki21** [comment]
I'm closing this one.

**Comment by JoelProminic** [comment]
I confirmed these problems were resolve:
- The project selection works as expected.
- If I change the selected project and click on the search field, the focus changes properly.

The other original problems were moved to separate issues.

New issues:
- We need to check the sorting for the project dropdown.  I moved this to #811
