### ISSUE TITLE
GET/SET creator always creates methods as 'private'

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#803]
1. Try to create a GET/SET method for a field:
![image](https://user-images.githubusercontent.com/24370870/114350280-a15bc100-9b86-11eb-9159-72aef42667d7.png)
2. Chose "Generate 'get' and 'set' accessors" from the context-menu (above)
3. Moonshine always creates the methods with `private` specifiers: 
![image](https://user-images.githubusercontent.com/24370870/114350477-d6681380-9b86-11eb-8e36-73f5262e05e6.png)

It is possible that one may need the methods to be private, but in more general cases they mostly requires in `public` use. 

We can consider to provide both `private` and `public` options in the context-menu giving the priority to `public`.

**Comment by piotrzarzycki21** [comment]
Well more options may confuse user in the popup. I'm not sure if you are aware but if you have public variable like that and generate GET/SET you will get public get/set.

`public var myVar:String;` you should get:

`public function get myVar():String {}`

**Comment by rat-moonshine** [comment]
Okay, that sounds good. But anyway this remain involve the manual editing part.

**Comment by joshtynjala** [comment]
This is by design. The getter/setter will have the same access level as the original variable. So, If the variable is private, the getter/setter will be private. If the variable is protected, the getter/setter will be protected. If the variable is public, the getter/setter will be public.

**Comment by rat-moonshine** [comment]
When I practically tried this, and tried to generate a GET/SET method to a `public` property:
![image](https://user-images.githubusercontent.com/24370870/114501859-6ae67a80-9c48-11eb-93ae-90634269e977.png)

I see the process automatically changed the former declaration from `public` to `private`, and created two new `public` methods for its GET/SET:
![image](https://user-images.githubusercontent.com/24370870/114501899-7d60b400-9c48-11eb-922c-71bdfd432d25.png)

This I think mostly what I required. Sorry for the confusion I haven't noticed this way of doing things.
