### ISSUE TITLE
Rename Not Fully Working For Visual Editor Projects

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#806]
Extracted from https://github.com/prominic/Moonshine-IDE/issues/646#issuecomment-821136365

> Okay ,I think I got why the rename get error , the menu always return null.
> I found the
> 
> https://github.com/prominic/Moonshine-IDE/blob/2a8da35f4a1357e176d62060d57f7d75096d9326/ide/MoonshineGUICore/src/moonshine/plugin/rename/view/RenameFileView.hx#L145
> 
> It look like it only change the file name and not update the middle xml file.
> I not familiar with hx file ,so how we handle this ?
> @JoelProminic
> I think this why rename work with my branch ,but not work the master .

@feather812002 found that the Rename action is failing for Visual Editor projects

This is my test procedure on macOS
1. File > New > Visual Editor Project
1. Enter name, choose the "PrimeFaces Visual Editor" Template Type, and click Create
1. Right-click on the project and choose New > Visual Editor PrimeFaces File
1. Name the file TestNew.xhtml, choose the src/main/webapp directory, and click Create
1. Add a label to the new mockup and save
1. Right-click on src/main/webapp/<project>.xhtml and choose Rename
1. Rename the file as TestRename
1. Right-click the project and choose "Show in Finder"
1. BUG:  src/main/webapp/TestRename.xhtml is updated, but visualeditor-src/main/webapp/TestNew.xml is not renamed.

Domino Visual Editor has a similar problem with .form files.

I remember that rename was working for both projects before we switched to the Haxe interface.

**Comment by piotrzarzycki21** [comment]
I have looked into that and don't fully understand why it is happen for Visual Editor project. There is been used same logic for all projects for renaming. In case of Visual Editor Prime faces project file instead of renaming it's been duplicated, with new name.

Renaming is about somehow overwriting with new one, but without actually setting to true overwrite argument in function -> https://github.com/prominic/Moonshine-IDE/blob/0003fb88e76ac5f3b55b54bc33688496b7105fab/ide/MoonshineSharedCore/src/actionScripts/plugin/rename/RenamePlugin.as#L183

**Comment by piotrzarzycki21** [comment]
Rename for VE type of projects doesn't work in 3.0.0. I will try to add implementation for this.

**Comment by piotrzarzycki21** [comment]
I have found out that native method `moveTo` - Responsible for renaming file have in some cases timing issue. Rename method specifically doesn't exists in Air, moveTo method emulate that by moving File to another place with new name. If I have file named test.mxml and I would like to have it named test2.mxml it looks like that:

`"test.mxml"(File).moveTo("test2.mxml", false)`

Sometimes that method instead of rename - duplicate original file with new name. It's just an observation.

**Comment by piotrzarzycki21** [comment]
Issue has been fixed for Flex and PrimeFaces visual editor, but domino visual editor has been excluded from that fix. I have discovered there much more serious issue which requires more work from @feather812002  - I will raise separate issue for the next release.

**Comment by piotrzarzycki21** [comment]
I was able to figure out what is happening with renaming files in VE Domino. Everything is working now.

**Comment by JoelProminic** [comment]
I did some tests with the latest nightly builds on macOS.

I see rename is mostly working in Domino Visual Editor
1. Open/Create a Domino Visual Editor Project
2. Show the hidden files/folders if this is not done already (Moonshine Settings > General > Show hidden files/folders
3. Open visualeditor-src/main/webapp
4. Right Click > New > Domino Visual Editor Form
5. The new form appears in nsf/nsf-moonshine/odp/Forms and visualeditor-src/main/webapp
6. Add a label to the new form and save
7. Rename the form
8. BUG:  The name updates in the open editor, but not in either nsf/nsf-moonshine/odp/Forms or visualeditor-src/main/webapp
9. Refresh the project.  BUG:  Nothing happens - this is probably a separate issue
10. Try to refresh either nsf/nsf-moonshine/odp/Forms or visualeditor-src/main/webapp.  BUG:  This displays an error - note the duplicate paths:  "Unable to access file:/Users/-username-/Documents/Flex/temp_workspace/TestDominoVisualEditor_0419/visualeditor-src/rs/-username-/Documents/Flex/temp_workspace/TestDominoVisualEditor_0419/nsfs/nsf-moonshine/odp/Forms"
11. Right-click on the project and choose Show in Finder.  Note that the files were correctly updated
12. Make a change in the open editor and save.
13. Reopen the project.  Note that the updated file names are displayed, and the change persists.
14. BUG:  open the renamed file.  BUG:  the last change from editor is missing


The remaining problems are:
- Auto-refresh (and manual refresh, which may be a separate problem)
- Edits to the renamed file do not persist until the editor is reopened


For PrimeFaces Visual Editor, I see this behavior
1. Open/Create a Primefaces Visual Editor project
2. Open visualeditor-src/main/webapp
3. Right Click > New > VisualEditor Primefaces Form
4. BUG:  the corresponding XML file does not show up in visualeditor-src/main/webapp
5. Refresh visualeditor-src/main/webapp.  BUG:  nothing changes
6. Refresh the project.  BUG:  nothing changes
7. Add an Output Label to the open editor and save
8. Rename the XHTML file
9. The name updates in both the editor window and the sidebar (but still missing from visualeditor-src/main/webapp)
10. Make a change in the open editor and save
11. Reopen the editor.  BUG:  the latest update is missing
12. Make another change in the open editor and save
13. Reopen the editor.  The editor is up-to-date

**Comment by piotrzarzycki21** [comment]
@JoelProminic Refresh problem has been addressed. Alle the problems after renaming was just happen due lack of proper refresh. UI just holds old file name.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have fixed issue which we have seen yesterday on our call. However I see that saving files in PrimeFaces Visual Editor doesn't work completely :(. To me it sounds like regression bug after merge with Bing's changes. Cannot find cause of issue so far.

**Comment by JoelProminic** [comment]
Testing with the latest build, I see that I can save to a .form or .xhtml file after renaming the file:
1. Create a .form or .xhtml
2. Add a label and save
3. Rename
4. Add another component to the editor and save.
5. Reopen the editor.  The change is preserved.

What problem are you still seeing with saving the files?

**Comment by piotrzarzycki21** [comment]
I think I have just found scenario how to reproduce my issue, but not fix for now - it requires more time. 

**Scenario 1**:
1) Open visual editor PrimeFaces project - Domino type of VE seems to be not affected with that issue
2) Add to main view some item and save
3) Open second visual editor Flex project
4) Drop on stage some component. [Bug]

**Console report NPE and file was not save**

```
: Error #1009
: TypeError: Error #1009
: 	at utils::MoonshineBridgeUtils$/getRelativeFilePath()
: 	at utils::MainApplicationCodeUtils$/getPrimeFacesMainContainer()
: 	at utils::MainApplicationCodeUtils$/getParentContent()
: 	at utils::EditingSurfaceWriter$/toCode()
: 	at view::EditingSurface/toCode()
: 	at actionScripts.plugins.ui.editor::VisualEditorViewer/getMxmlCode()
: 	at actionScripts.plugins.ui.editor::VisualEditorViewer/save()
: 	at actionScripts.controllers::SaveFileCommand/execute()
: 	at actionScripts.locator::IDEController/execCommand()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
: 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
: 	at actionScripts.ui.menu::MenuPlugin/redispatch()
: 	at flash.display::NativeMenuItem/performKeyEquivalent()
: 	at flash.display::NativeMenu/performKeyEquivalent()
: 	at flash.display::NativeMenuItem/performKeyEquivalent()
: 	at flash.display::NativeMenu/performKeyEquivalent()
: 	at flash.desktop::NativeApplication/_onKeyDownCapture()
:
: Click here to Report a Bug
```

**Senario 2**:
1) Open visual editor Flex project 
2) Add to main view some item and save
3) Open second visual editor Flex project
4) Open main file [Bug]

**Console reports NPE:**
```
: Error #1009
: TypeError: Error #1009
: 	at view::ComponentsOrganizer/getComponentsChildren()
: 	at view::ComponentsOrganizer/loadFirstData()
: 	at mx.core::UIComponent/callLaterDispatcher2()
: 	at mx.core::UIComponent/callLaterDispatcher()
```

4) Click on Main project surface [Bug]

```
: Error #1009
: TypeError: Error #1009
: 	at view::ComponentsOrganizer/getComponentsChildren()
: 	at view::ComponentsOrganizer/loadFirstData()
: 	at mx.core::UIComponent/callLaterDispatcher2()
: 	at mx.core::UIComponent/callLaterDispatcher()
```
5) Drop some component on surface [Bug]
```
: Error #1009
: TypeError: Error #1009
: 	at view::ComponentsOrganizer/getComponentsChildren()
: 	at view::ComponentsOrganizer/loadFirstData()
: 	at mx.core::UIComponent/callLaterDispatcher2()
: 	at mx.core::UIComponent/callLaterDispatcher()
```

**Comment by piotrzarzycki21** [comment]
@JoelProminic I think you can close this issue, but I will open new one. I wanted to spend max Monday to try to fix that - if I won't succed I would like to release Moonshine as is.

**Comment by JoelProminic** [comment]
Okay, this fine.  FYI, Monday is a holiday for me so I will not be available for the release.   We can aim for a release on Tuesday if there are no more problems.
