### ISSUE TITLE
Quit from Moonshine should prompt user

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#81]
Moonshine should prompt user once if he choose to exit. 

Title: "Confirm Exit"
Question: "Are you sure you want to exit Moonshine IDE?"
Checkbox: "Do not ask me again"

- If user check "Do not ask me again" popup should reappear once he reset settings
- Maybe it should be also configurable from general settings ?

**Comment by piotrzarzycki21** [comment]
Prompt for user during process of exit has been added. Option to dismiss popup is also available in the File -> Settings -> General. 

It is ready for review, so reopen once you have some comments.

**Comment by JoelProminic** [comment]
I tested this for 1.8.0.  I confirmed:
* This feature is disabled by default
* The setting is visible in Settings > General
* Both the Exit and Cancel buttons work
* The "Do not ask me again" checkbox works
