### ISSUE TITLE
Source icon in project tree-view do not populates for the Java projects

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#814]
This issue is a carry on from #805 - https://github.com/prominic/Moonshine-IDE/issues/805#issuecomment-824568438.

**Comment by rat-moonshine** [comment]
Since #756 the marking of a source-folder in sidebar became obsolete to some extent, which results non-generation of the icon in different cases. 

I re-structured this area, and the information of a source-folder-wrapper shall present out of the TreeView as well, which also helped to render the source icon in new file/folder popup without an extra effort:

![image](https://user-images.githubusercontent.com/24370870/115875692-1a022d80-a463-11eb-8c31-79c8336030ea.png)

This issue now ready for a test.

**Comment by JoelProminic** [comment]
I checked a sample of projects on macOS:

Project Type | Source directory icon
Java Gradle | Present
Java Maven | Present
Apache Royale | *Missing*
Flex Desktop | *Missing*
Grails | Mixed - see below

Did the update for the Java projects break the other project types?

Grails projects have multiple source directories, but only the first has an icon.  Do we have support for multiple source directories in general?  This might be outside of the scope of this issue

![image](https://user-images.githubusercontent.com/24532731/115903642-7183a780-a429-11eb-87e0-120e48481c03.png)

**Comment by rat-moonshine** [comment]
I'm bit unsure as you can see Flex Desktop project populates with correct source icon in my earlier screenshot. 

The changed logic is supposed to be applied across all project types whoever is extending from `ProjectVO`, which is the base-project-vo in Moonshine, and _if_ populates with its `sourceFolder` property.

> Grails projects have multiple source directories, but only the first has an icon. Do we have support for multiple source directories in general?

The `sourceFolder` is single-file-pointer, and it contain only location information. 

I shall try to re-tests creating new demo projects. Earlier I did with Gradle, and Flex Desktop project, thus the results for Flex Desktop from you seems strange to me.

**Comment by JoelProminic** [comment]
Hmm, the images show up properly for me in macOS Firefox.

I missed your screenshot earlier, but I see that a Flex Desktop project shows the icon correctly for you.   This doesn't show up on my mac, though, even if I close the other projects:
![image](https://user-images.githubusercontent.com/24532731/115906789-9ed25480-a42d-11eb-8410-9f5591eca7ce.png)

**Comment by rat-moonshine** [comment]
For the attached images, I see the problem across browsers on my macOS - Safari, Chrome and Firefox. It seems to me that only previously cached images are rendering for me but new ones, for some reason. I can't even load the recent  image you attached separately. Hopefully, this only a temporary problem.

I shall try downloading a build from Bamboo on demo projects.

**Comment by rat-moonshine** [comment]
I tried to give a test downloading latest nightly from Bamboo (https://bamboo.prominic.net/browse/MS-MGOSX-1905/artifact) on macOS, I created almost each sample projects available in Moonshine (_except Grails_ as this takes longer time to complete its server but tested working with source-icon), unfortunately I couldn't able to reproduce the source-icon non-displaying problem to sidebar:

![image](https://user-images.githubusercontent.com/24370870/116236244-74113480-a77c-11eb-9532-1319d9f8123f.png)
![image](https://user-images.githubusercontent.com/24370870/116236322-8ab78b80-a77c-11eb-9f81-3b071df9f8eb.png)

I did noticed there two placement problems though like in Maven project in my case, but this could be separate problem:
![image](https://user-images.githubusercontent.com/24370870/116237016-58f2f480-a77d-11eb-98c4-91a9852708b4.png)

I didn't see Visual Editor Project has any source-icon, it's probably because it doesn't has any declared source folder.

@Aszusz can you also give a test at yours side on macOS (downloading the latest nightly from Bamboo), and able to reproduce missing source-icon problems as @JoelProminic reported [here](https://github.com/prominic/Moonshine-IDE/issues/814#issuecomment-825782966)?

**Comment by rat-moonshine** [comment]
I pushed a fix for source-icon placement in some scenarios:
![image](https://user-images.githubusercontent.com/24370870/116237016-58f2f480-a77d-11eb-98c4-91a9852708b4.png)
![image](https://user-images.githubusercontent.com/24370870/116238269-c6535500-a77e-11eb-912b-85fee871bfea.png)

**Comment by Aszusz** [comment]
@rat-moonshine
Something is definitely up. My results are the opposite of Joel's.

Project Type | Source directory icon
---|---
Java Gradle | Missing
Java Maven | Missing
Apache Royale | Present
Flex Desktop | Present
Grails | Missing

![Screenshot 2021-04-27 at 15 53 36](https://user-images.githubusercontent.com/7197014/116254310-889bff80-a771-11eb-94a9-475aee1dd55d.png)
![Screenshot 2021-04-27 at 15 57 23](https://user-images.githubusercontent.com/7197014/116254332-8cc81d00-a771-11eb-9e3f-115b1a169b16.png)

Build is 359 from April 27

**Comment by rat-moonshine** [comment]
@Aszusz can you print the version/build details from Moonshine About section please? I'm wondering if we are testing on different builds.

**Comment by Aszusz** [comment]
![image](https://user-images.githubusercontent.com/7197014/116256347-64d9b900-a773-11eb-807b-8b155dcc9e2d.png)

**Comment by rat-moonshine** [comment]
Unfortunately this is not the current build from master branch. Please download by the Bamboo link from my comment earlier, you should have a build number 1905.

**Comment by Aszusz** [comment]
Sorry about that. Upgrade didn't work for me. I tried a couple of times to upgrade from to 359 to 1905 or 1907 but eventually I removed 359 and clean installed 1905:

![image](https://user-images.githubusercontent.com/7197014/116268531-b1c28d00-a77d-11eb-870d-2531603eff60.png)

As for my results, the only thing that changed is Grails:
Project Type | Source directory icon
---|---
Java Gradle | Missing
Java Maven | Missing
Apache Royale | Present
Flex Desktop | Present
Grails | Mixed

![image](https://user-images.githubusercontent.com/7197014/116268321-7de76780-a77d-11eb-98b8-75665ab83eeb.png)

I think it might be, because I don't have Java 11 installed on my Mac. I'll update my Java and get back to you.

**Comment by rat-moonshine** [comment]
> I tried a couple of times to upgrade from to 359 to 1905 or 1907 but eventually I removed 359 and clean installed 1905

macOS has a strange behaviour to overwrite an unexpected executable - if you have multiple executable exists in your system in different location. In such case, macOS may not update the file inside `/Applications`. Although, we also seen macOS do not updates `/Applications` version even you have only executable exists in your system, rarely.

Why Grails result is mixed?

> I think it might be, because I don't have Java 11 installed on my Mac. I'll update my Java and get back to you.

Logic to show source-icon is independent to your Java version.

**Comment by Aszusz** [comment]
> Why Grails result is mixed?

I'm just using the same rhetoric as Joel:
_"Grails projects have multiple source directories, but only the first has an icon. Do we have support for multiple source directories in general? This might be outside of the scope of this issue"_

> Logic to show source-icon is independent to your Java version.

Of course you're right. I saw some errors about Java 11 not being present and I thought it's better to check. But as you expected installing Java 11 didn't help at all.

**Comment by rat-moonshine** [comment]
> I'm just using the same rhetoric as Joel:
> "Grails projects have multiple source directories, but only the first has an icon. Do we have support for multiple source directories in general? This might be outside of the scope of this issue"

Okay. Thanks for explaining @Aszusz . Currently we have only path management for a project's source folder (I gave some details [here](https://github.com/prominic/Moonshine-IDE/issues/814#issuecomment-825795069)).

I able to reproduce the source-icon problem for Gradle on Window finally. Unfortunately, my tests results remain all-correct on macOS; At least, I have a lead to test these now on Windows.

**Comment by rat-moonshine** [comment]
Some misconception to clear at my side - 

> I able to reproduce the source-icon problem for Gradle on Window finally. Unfortunately, my tests results remain all-correct on macOS; At least, I have a lead to test these now on Windows.

Unlike my previous thought - I see I was mistakenly expecting "src" should have source-icon when the icon generated for "src/main/java" in Gradle or Maven project. So, I still not able to reproduce the problem on Windows tests. 

I still can't able to reproduce the problem so far for other project types on Windows, either.

**Comment by JoelProminic** [comment]
The problem does not trigger for me either on Windows. 

However, it triggers consistently for Flex Desktop and Royale projects for me on macOS Catalina

**Comment by Aszusz** [comment]
> can you confirm if "src/main/java" has missing source-icon in your tests for Gradle, Maven (I don't see the projects expanded in your screenshot)?

This is very embarasing...

![image](https://user-images.githubusercontent.com/7197014/116280340-d839f580-a788-11eb-9c87-21334159c0e9.png)

Everything works correctly for me, Gradle, Maven, Royale and Flex.

**Comment by Aszusz** [comment]
I've also just tested Windows: there were icons missing on my previous version but on 1907 everything works correctly too.

**Comment by rat-moonshine** [comment]
> However, it triggers consistently for Flex Desktop and Royale projects for me on macOS Catalina

@JoelProminic do you see any reappearance of the icon on macOS if you do a refresh to the project?

**Comment by JoelProminic** [comment]
No, I don't see any difference when I refresh or reopen a project, or when I restart Moonshine.   I confirmed that the class paths were set like I expected.

**Comment by rat-moonshine** [comment]
> No, I don't see any difference when I refresh or reopen a project, or when I restart Moonshine. I confirmed that the class paths were set like I expected.

I did some amendment in the ways displaying source-icon. Please check, if this works for you now.

**Comment by JoelProminic** [comment]
I still don't see the source icon for Flex, Royale, or Haxe projects on macOS Catalina.   Since I'm the who has this problem, and it does not break functionality, this is a lower priority.

**Comment by JoelProminic** [comment]
I extracted the remaining issues as #825 and #826.
