### ISSUE TITLE
Installed SDKs not auto-detects in Windows environment

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#817]
During our tests to https://github.com/prominic/Moonshine-SDK-Installer/issues/32 with @JoelProminic , he pointed that the newly installed SDK do not auto-populates in the setting's SDK-list. None of the existing item also has any mark as 'Bundled' (as can be seen on macOS).

Looking into the code, I have found the auto-detection only available on macOS run. We may need to have this available on Windows too, with any requisite adjustment.

**Comment by rat-moonshine** [comment]
Okay. This is populating now with 'Bundled' marker on Windows as well. Please, check.

**Comment by piotrzarzycki21** [comment]
Could you make sure that build is running on OS X. I would like to test it before the meeting.

**Comment by piotrzarzycki21** [comment]
I see also some kind of discrepancy. You have discovered issue as part of testing build of MSDKI on branch related with https://github.com/prominic/Moonshine-SDK-Installer/issues/32 , but fix is on Master. Did you merge it also to https://github.com/prominic/Moonshine-SDK-Installer/issues/32 ? I prefer test this one along with Harman Air update.

**Comment by rat-moonshine** [comment]
> I see also some kind of discrepancy. You have discovered issue as part of testing build of MSDKI on branch related with https://github.com/prominic/Moonshine-SDK-Installer/issues/32 , but fix is on Master. Did you merge it also to https://github.com/prominic/Moonshine-SDK-Installer/issues/32 ? I prefer test this one along with Harman Air update. 

This issue is independent to Harman AIR SDK, and applied as general fix to Moonshine working on 'master'.

**Comment by rat-moonshine** [comment]
> Could you make sure that build is running on Mac OS X. I would like to test it before the meeting. 

I shall check once I able to return to my workstations.

**Comment by JoelProminic** [comment]
I did fresh installations for almost all of the SDKS on macOS and Windows.  I confirmed that:
- Moonshine can detect the new SDKs on restart
- Moonshine will update the SDKs while MSDKI is running.

However, I'm seeing that Feathers is not considered a bundled SDK on both macOS and Windows:

![image](https://user-images.githubusercontent.com/24532731/117217968-ee1e6a80-adc7-11eb-8452-eb9d2b47a4e4.png)


In addition, on macOS I see that the Flex Adobe AIR and Royale SDKs are duplicated on restart:

![image](https://user-images.githubusercontent.com/24532731/117217988-f37bb500-adc7-11eb-9570-be6ed6fbe1b2.png)

**Comment by rat-moonshine** [comment]
> However, I'm seeing that Feathers is not considered a bundled SDK on both macOS and Windows:

Feathers now included for _bundled_ SDKs.

> In addition, on macOS I see that the Flex Adobe AIR and Royale SDKs are duplicated on restart:

To ensure I'm not seeing any previously manually added items, I removed the Moonshine cache (/Library/Application Support/com.moonshine-ide), installed a new build from Bamboo, and I don't see any duplication of SDK. Can you please re-check if the duplicated items are any previously added item manually (?)

**Comment by piotrzarzycki21** [comment]
I also don't see duplication. Let's resolve issue during our meeting today.

**Comment by JoelProminic** [comment]
I don't see the issues with the missing bundle flags or duplicate entries in my macOS and Windows testing today.
