### ISSUE TITLE
Error Reporting Grails Version in About Page

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#818]
I tested with the latest macOS and Windows dev builds, and I see that the Grails version shows an error in Help > About:

![image](https://user-images.githubusercontent.com/24532731/117219006-f7103b80-adc9-11eb-80f0-0fc090c49a14.png)

**Comment by rat-moonshine** [comment]
While Grails has two files under its `bin`:
1. grails (seems like an executable on macOS)
2. grails.bat 

Running the `-version` or `--version` command prints the same garbage texts on command-line as well, and at the end it prints the version figures. 

I think I may need to selectively grab-out the version information from its text-output.

**Comment by rat-moonshine** [comment]
This should be fix now. Please, check.

**Comment by piotrzarzycki21** [comment]
I have tested on Mac OSX Catalina and versions is displaying correctly:
![Screenshot 2021-05-12 at 14 12 59](https://user-images.githubusercontent.com/24554795/117973374-9c786180-b32c-11eb-97e5-267596ff7366.png)

On my Windows machine it is working as well.

**Comment by JoelProminic** [comment]
Yeah, it is working for me as well on both OSes.
