### ISSUE TITLE
Change version number to 3.1.0 for Moonshine in Nightly

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#821]

**Comment by JoelProminic** [comment]
I had also noticed the old version number in my recent testing.  This should be fixed now for the pirmary nightly builds.

App/Build | Version | Notes
----------|---------|------
Moonshine Windows | 3.1.0 | Already updated
Moonshine macOS | 3.1.0 | 
Moonshine SDK Installer Windows | 3.7.0 | Already updated
Moonshine SDK Installer macOS | 3.7.0 | Already updated
