### ISSUE TITLE
Compile in AFB with Adobe Flex 4.6 (AIR) but not in Moonshine IDE

### ISSUE THREAD

**Issue by marcotini** [prominic/Moonshine-IDE#822]
Hi, I'm working on an Adobe AIR project that fully compile with Adobe Flash Builder 4.6 and I'm trying to working with Moonshine IDE (so maybe I can convert it to Apache Royale).

I've moved the SDK 4.6.0 folder from: `C:\Program Files (x86)\Adobe\Adobe Flash Builder 4.6\sdks\4.6.0` to  `C:\4.6.0` (maybe the space between the name was an issue) since the API report gave me some error with the spaces.
But anyway the problem that I'm having right now is: when I try to compile, in the Console I got something like this:

    : Loading configuration file C:\4.6.0\frameworks\flex-config.xml
    : Loading configuration file C:\MyProject\obj\MyProjectConfig.xml
    : C:\MyProject\src\MyProject.mxml: Error: Unable to locate specified base class 'spark.components.WindowedApplication' for component class 'MyProject'.
    : 
    : Loading configuration file C:\4.6.0\frameworks\flex-config.xml
    : Loading configuration file C:\MyProject\obj\MyProjectConfig.xml
    : C:\MyProject\src\MyProject.mxml: Error: Unable to locate specified base class 'spark.components.WindowedApplication' for component class 'MyProject'.

What am I doing wrong?

`MyProject.xml` of course start with:

    <s:WindowedApplication xmlns:fx="http://ns.adobe.com/mxml/2009"
					   xmlns:s="library://ns.adobe.com/flex/spark"
					   xmlns:mx="library://ns.adobe.com/flex/mx"

It also have `+configname=air` compile tag since the command for compile is:

    : Compiling MyProject
    : Command: "C:\4.6.0\bin\mxmlc.exe" -load-config+=obj/MyProjectConfig.xml -accessible=true -locale=en_US 

![screenshot](https://user-images.githubusercontent.com/3670558/117990169-2fb99300-b33d-11eb-9f6d-12850433a73a.png)

I'm on Moonshine 3.0.0 and Windows 10.

**Comment by piotrzarzycki21** [comment]
Hi @marcotini , 
Could you please right click on your project in Moonshine and choose **Settings** -> **Build options** and in **Additional compiler options** add option **+configname=air**

**Comment by marcotini** [comment]
Thank you for your reply @piotrzarzycki21 

> Could you please right click on your project in Moonshine and choose Settings -> Build options and in Additional compiler options add option +configname=air

I've already added `+configname=air` tag on the additional compiler options.
Other than that I have multiple `-define+=VAR1::available,false` that maybe can interfere? And also a `-locale=en_US`

**Comment by piotrzarzycki21** [comment]
This is the name of main project file `MyProject.mxml` - in what folder do you have air config file and what is the name of that file ?

**Comment by rat-moonshine** [comment]
@marcotini Can you please give a test by creating a sample Flex Desktop Project (you can get an option in Moonshine dashboard) using the same SDK you were using for your project, and see if you continue to have the error? Thanks!

**Comment by marcotini** [comment]
> This is the name of main project file `MyProject.mxml` - in what folder do you have air config file and what is the name of that file ?

`MyProject-app.xml` and it's on the same folder (under `/src`)

> @marcotini Can you please give a test by creating a sample Flex Desktop Project (you can get an option in Moonshine dashboard) using the same SDK you were using for your project, and see if you continue to have the error? Thanks!

Ok I let you know with the same SDK with a blank project.

> By the way, you are suggested to use Apache Flex SDK, sdk inside Flash Builder application folder might have its own dependencies, i.e. specific-java etc.

Yes I'm trying to move from Adobe to Apache but I'm running in some issue.

**Comment by rat-moonshine** [comment]
@marcotini Did you able to overcome the issue by shifting to Apache Flex?

Since v4.6 is a pretty old by now and Adobe itself do not supports this anymore, it's make less sense to spend time on fixing support on this old version using in an altered way. I'd recommend to give Apache Flex a chance and let us know if you're having any issue. For now, I'm closing this issue.
