### ISSUE TITLE
Build Number Missing in About Page for macOS

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#824]
On the Windows About page, I see a build number:

![image](https://user-images.githubusercontent.com/24532731/118012174-65975100-b316-11eb-8ced-77798573fd29.png)

But I don't see this on macOS

![image](https://user-images.githubusercontent.com/24532731/118012228-71831300-b316-11eb-8e1a-f5081cb92e22.png)

This might be a bug with the build number population in the macOS Bamboo Build

**Comment by rat-moonshine** [comment]
I see requisite information actually available, but for some reason it is not working anymore on macOS. I'm looking into.

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/118084323-26343780-b3de-11eb-84b7-2d4a8f923da7.png)

This seems to be Okay now on macOS, too.

**Comment by piotrzarzycki21** [comment]
About page displaying build number correctly on Mac and Windows.
