### ISSUE TITLE
Error validating path of local git executable on Windows

### ISSUE THREAD

**Issue by ciacob** [prominic/Moonshine-IDE#827]
Code expects "bin/git.exe", whereas on Windows it wil always be "bin\git.exe" (mind the backslash).
![moonshine-git-path-validation-error](https://user-images.githubusercontent.com/7130354/118365604-1c5d3080-b5a6-11eb-8f06-b176ab42db74.jpg)

**Comment by ciacob** [comment]
Observed on v. 3.0.0, build 264

**Comment by piotrzarzycki21** [comment]
Could you please try Nightly build and let us know whether you experience same issue? Thanks!

**Comment by rat-moonshine** [comment]
@ciacob Does this only textual issue to you, or this affect the functionality?

**Comment by JoelProminic** [comment]
I gave this a quick test on Windows.  It looks to me like the backslashes are not a problem with the latest nightly build, at least:

![image](https://user-images.githubusercontent.com/24532731/118715867-c2e54380-b7e9-11eb-9c23-f2055c9b2fda.png)

I don't have a D:\ drive I can use for testing on either of my test Windows VMs - could this explain the error?

**Comment by rat-moonshine** [comment]
I haven't found any problem on Windows using D:\ either using current Nightly.

**Comment by ciacob** [comment]
Great. Then, should I close the issue?

**Comment by rat-moonshine** [comment]
> Great. Then, should I close the issue?

Yes, you can close it! You can re-open if you see the same error with upcoming version v3.0.1.
