### ISSUE TITLE
Update CHANGELOG for 3.1.0 release

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#828]

**Comment by JoelProminic** [comment]
I finished reviewing the changelog.   Thanks for creating the Changelog entries and including the issue links - this was very helpful when reviewing the corresponding issue.

Here are some topics that I would like to review in the meeting tomorrow:
- for #800, has anyone had trouble with the file associations on Windows?  I'm a little concerned about whether we handled this "properly", but I haven't seen any major problems so far.
- Do we want something in the Changelog for On Disk Project issues?

**Comment by JoelProminic** [comment]
We discussed #800, and decided that it should be fine for the release.

I added an entry to CHANGELOG.md for Domino Visual Editor, #646

**Comment by rat-moonshine** [comment]
We had unofficially released #669 , #670 and #831 in v3.0.0. These issues now being closed, we may want to include this in official release-notes now.

**Comment by JoelProminic** [comment]
I added notes for the On Disk Project issues.   I think #831 was related to other issues we have already included in the changelog.
