### ISSUE TITLE
Unable to compile Grails

### ISSUE THREAD

**Issue by Aszusz** [prominic/Moonshine-IDE#829]
When using recent version of Moonshine IDE I am unable to compile Grails projects.
I'm on Windows and I'm using default Java, default Grails and default Gradle.

Steps to reproduce:
1. Create new Grails projects
2. Do Build & Run

Result:
```
: Starting Grails build...
: Grails build directory: C:\home\repos\for-prominic\article\TestProject
: Command: C:\MoonshineSDKs\Grails\grails-3.3.10\bin\grails.bat run-app
: WARNING: An illegal reflective access operation has occurred
: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/MoonshineSDKs/Grails/grails-3.3.10/lib/org.codehaus.groovy/groovy/jars/groovy-2.4.17.jar) to method java.lang.Object.finalize()
: WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
: WARNING: All illegal access operations will be denied in a future release
: Error |
: Error initializing classpath: Could not determine java version from '11.0.10'. (Use --stacktrace to see the full trace)
: Grails build has been terminated with exit code: 1
```

I'm attaching my full stacktrace: [grails-build-error.txt](https://github.com/prominic/Moonshine-IDE/files/6500761/grails-build-error.txt)

@piotrzarzycki21 reproduced this issue on Mac

**Comment by JoelProminic** [comment]
It looks like Grails 3.3.11 doesn't support JDK 11 or higher:  https://stackoverflow.com/questions/51867798/does-grails-3-x-support-java-11

I can work around this by changing the Default JDK to 1.8.0 in the Moonshine settings.  The language server also worked for me in this case, but the user may need to add the compatibility settings if they are working with a project that specifically requires JDK 8:

    sourceCompatibility = 1.8
    targetCompatibility = 1.8


@rat-moonshine, for now we should require new Grails projects to use JDK 8 by default, and add the settings menu to select the JDK, like we do for Java Maven or Gradle projects.  See #755 for more details.

For the next release, we should update support to the latest version of Grails 4 (see https://github.com/prominic/Moonshine-SDK-Installer/issues/43), which should support JDK 8 (but we should still let users choose the JDK in the settings).

**Comment by rat-moonshine** [comment]
I made default-JDK to 8 for the Grails project. Changes to use JDK.8 by default affected in following areas:

1. Grails project creation command-run (`$grailsPath create-app $projectName --inplace`)
2. Project -> Build & Run
3. Project -> Run Grails Command

However, during the project import I see a Gradle Daemon being start which continues to throw the same error:
```
: Creating Grails application NewGrailsProject
: | Application created at /Users/devsena/Desktop/NewGrailsProject
: Starting a Gradle Daemon, 4 stopped Daemons could not be reused, use --status for details
: > Task :eclipseClasspath
: > Task :eclipseJdt
: > Task :eclipseProject
: > Task :eclipseWtpComponent
: > Task :eclipseWtpFacet
: > Task :eclipseWtp
: > Task :eclipse
: Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
: Use '--warning-mode all' to show the individual deprecation warnings.
: See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
: BUILD SUCCESSFUL in 11s
: 5 actionable tasks: 5 executed
: WARNING: An illegal reflective access operation has occurred
: WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Users/devsena/Documents/Adobe%20Flash%20Builder%204.7/ProminicGITBranch/Moonshine-IDE/ide/MoonshineDESKTOPevolved/bin-debug/elements/groovy-language-server/groovy-language-server-all.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
: WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
: WARNING: All illegal access operations will be denied in a future release
```
I failed to find where this Daemon being started, can someone give a direction on this? 

Beside that all command-run on Grails using the defined JDK version.

**Comment by piotrzarzycki21** [comment]
I have tested that on Mac and I'm getting in console following:

```
: Starting Grails build...
: Grails build directory: /Users/piotr/Dev/Prominic.NET/Tests/NewGrailsProject
: Command: /Users/piotr/Downloads/MoonshineSDKs/Grails/grails-3.3.10/bin/grails run-app
: | Running application...
: Grails application running at http://localhost:8080 in environment: development
```

When I copy localhost url and run in browser I'm getting following app:

![Screenshot 2021-05-19 at 12 06 12](https://user-images.githubusercontent.com/24554795/118795223-ab19c800-b89a-11eb-8f3e-5112fbb8412d.png)

Is this what we are look for ? @Aszusz please test @rat-moonshine changes and let me know.

**Comment by Aszusz** [comment]
Looks like Windows build failed
Fixing commit is: 6bd569680910bc7d1ff17aad838ba22424e0e337
But latest windows commit is: 228302bbcb2453f2bee697786bab211e556bf578

**Comment by rat-moonshine** [comment]
I have restarted the Bamboo agent on Windows build system. This may take a while to fully start and start building at Bamboo.

You can test the macOS build in between time if you need.

**Comment by rat-moonshine** [comment]
- `gradle eclipse` in groovy-language-server now using project's JDK version
- `Clean` command from Java projects are now using project's JDK version

**Comment by Aszusz** [comment]
I tested latest build on Windows, everything works.
Thanks a lot.

**Comment by JoelProminic** [comment]
I tested this on macOS and Windows, and I don't see any problems with the selected JDK.
