### ISSUE TITLE
Can't Stop Running Grails Server

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#830]
While testing #829, I noticed this problem on macOS and Windows
1. Create or open a Grails application
1. Once the project is fully created, run Project > Build & Run
1. The server starts, ans shows:  "Grails application running at http://localhost:8080 in environment: development"
1. Moonshine shows that the server is running with a message in the bottom right and a stop icon
1. Click the stop icon.  BUG:  Nothing happens
1. Project > Run Grails Command
1. Type "stop-app" and click Run to attempt to stop the application.  This does not run with the warning "Build is running. Wait for finish...".  This behavior makes sense, but it means that this command is not a solution to stopping the server from Moonshine
1. Restart Moonshine.  The server stops here, but this is not a convenient solution to restart the server.

**Comment by rat-moonshine** [comment]
I see I'm not aware of how individual "Run Grails Command" should work. But I have fixed the Stop button listeners in status-bar; The plugin was listening for wrong events. 

Please, check.

**Comment by piotrzarzycki21** [comment]
Tested on Mac it's working fine. @Aszusz please test on Windows.

**Comment by rat-moonshine** [comment]
I'm not aware of how the server is suppose to function. I only ensure the [method](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/grails/GrailsBuildPlugin.as#L437) get called correctly (which wasn't triggering before on Stop button click), beside that how the post process would happen in Grails I have little knowledge to.

**Comment by piotrzarzycki21** [comment]
@joshtynjala Would you be able help us with that ?

**Comment by joshtynjala** [comment]
I remember that I ran into some serious issues with stopping Node.js web servers on Windows too. It's been a while, so I may not have the exact details right, but I think I remember a little. Looking at the `HttpServerPlugin`, I can see that I launch Node.js directly with `NativeProcess`. Normally, we launch the Windows command line, setup all of the environment variables, and then we tell it to start the process in the shell. I found that this was leaving node.exe processes still running after exiting the shell. I tried all sorts of ways to exit the shell, but no luck. Finally, I discovered that if I launched node.exe directly, I could exit it.

Maybe something similar can be done when launching the Grails server?

**Comment by JoelProminic** [comment]
My initial idea for this was to run "grails stop-app" and then kill the process if it was still running.  However, @rat-moonshine pointed out that Moonshine is currently designed to only run one process at a time, so this would require significant refactoring.

So instead, my suggestion is:
1. Run the normal stop logic
2. Run "grails stop-app"

I confirmed that the stop-app command will still cleanup the hanging process in this case, and that this logic works for "gradle bootRun" as well.   However, the stop-app command will alwasy report an error:

    | Error Application not running.

My recommendation is that we run this sequence to stop any any action running for a Grails project.  One exception would be to not run "grails stop-app" again if we have to kill the "grails stop-app" process.   I don't expect the stop-app command to hang, but I have seen it be unusually slow for large projects.

This is not a perfect solution, but I think it should be good enough for the current release.

**Comment by rat-moonshine** [comment]
I have added execution go `grails stop-app` post the Stop button clicked in status-bar during Grails run. Please, check.

**Comment by piotrzarzycki21** [comment]
Tested on Mac and it's working. However I see that not everything is being stopped, but this is something for separate issue. I just see that once I stop application and even close project - I still have 2 java instances which are over 400 MB in memory running. Those instances are connected to gradle deamon. Instance of project itself is being cleaned up. @Aszusz please test on Windows.

**Comment by Aszusz** [comment]
I'm satisfied with how stop server works now. I can reliably start and stop server and it works across Moonshine restarts.

As @piotrzarzycki21 said, there are still Java instances in the background. A matter for a separate issue, not that important for me personally right now.

**Comment by JoelProminic** [comment]
When I checked my workstation, I saw that I had a lot of hanging `jdt-language-server` and `as3mxml-language-server` instances.  However, after more investigation, I found that these are not related to the Grails instance.  This may need separate investigation.

When I open a Grails project, I see two new Java processes:

    504 15814     1   0 12:23PM ??         0:20.65 /Users/-username-/Downloads/MoonshineSDKs/Java/openjdk-1.8.0/bin/java -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/-username-/Downloads/MoonshineSDKs/Gradle/gradle-5.4.1-bin/lib/gradle-launcher-5.4.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.4.1
    504 15820 15784   0 12:23PM ??         0:02.32 /Users/-username-/Downloads/MoonshineSDKs/Java/openjdk-11.0.10/bin/java -cp /Applications/Moonshine.app/Contents/Resources/elements/groovy-language-server/* moonshine.groovyls.Main

`groovy-language-server` is the expected language server.  I thought we had a Java language server for this as well, but I don't see it.

`GradleDaemon` is something started automatically when running Gradle commands.  This is suppose to persist to make later Gradle commands faster.  

When I close the Grails server, I see that `groovy-language-server` stops, but `GradleDaemon` keeps running.  When I close Moonshine, `GradleDaemon` stops as well.   

Is this consistent with what you saw, @piotrzarzycki21?

For now, this seems like reasonable behavior to me.  If we need to better manage the `GradleDaemon` instances later, here are some commands I have used:
- List status of running daemons:  `gradle --status`
- Stop single daemon:  `kill -9 <pid>`
- Stop all Gradle daemons on system:  `gradle --stop`

**Comment by JoelProminic** [comment]
As for the stop action, I did some tests on macOS Catalina, and this seems to be working well:
- I can stop Project > Build & Run, and the server will also stop.  Unexpectedly, `grails stop-app` doesn't report the "Application not running." error.  Maybe this is because the command runs immediately after the process is killed?
- I also tested this with Run Grails Command > "run-app -https".  This had the same behavior for the stop button, so this should be fine
- I tried to kill the `grails stop-app` action, and it stopped without triggering `grails stop-app` again.

I'm fine with closing this issue if we don't want to discuss the Gradle daemon issue further.

**Comment by joshtynjala** [comment]
> I had a lot of hanging jdt-language-server and as3mxml-language-server instances

When the Moonshine process is force killed, it can leave language servers running because Moonshine isn't given a chance to shut them down cleanly. This is probably what you are encountering. It can happen most commonly when Moonshine is compiled and launched from an IDE, and then you stop the debugger that launched Moonshine. It can also happen if you kill Moonshine from a task manager.

To avoid this during development, avoid stopping from your IDE's debugger. Instead, close Moonshine's window manually (either with the close button in the title bar, or by choosing quit/exit in the menu). Unfortunately, Adobe AIR doesn't provide any way for Moonshine to say that a child NativeProcess should be killed if Moonshine crashes or is force quit. I could potentially add something to the AS3 & MXML language server to check if its parent process still exists, but we have no control over other language servers (and we really don't have the bandwidth to maintain forks with this sort of change).

It's certainly possible that there are still edge cases where Moonshine can exit without cleaning up the language servers, but I think it's unlikely. Off the top of my head, the only other thing that might be worth considering is that I seem to recall that Moonshine has a timeout on exit. If all of the language servers aren't killed in that time, Moonshine will stop trying and exit anyway. However, I remember that it takes several seconds before this happens, and I've always seen the language servers close much more quickly.

**Comment by piotrzarzycki21** [comment]
> When I close the Grails server, I see that `groovy-language-server` stops, but `GradleDaemon` keeps running. When I close Moonshine, `GradleDaemon` stops as well.
> 
> Is this consistent with what you saw, @piotrzarzycki21?

This is partially consistent. Here is what I'm see:
1. Project open and I have 2 java instances
- Project related - language server I think 
- Gradle Daemon
2. After **Build & Run** I have 6 java instances:
- 5 of these java instances has:
```
cwd
/Users/piotr/Dev/Prominic.NET/Tests/NewGrailsProject
```
It sounds like it is related to language server or anything what is needed to Build and Run project.
- One instance is gradle deamon.
3. Once I do project stop I'm staying with 3 instances, but one is new:
 **Instance 1**: 
```
cwd
/Users/piotr/.gradle/daemon/3.5
```
**Instance 2**: 
```
cwd
/Users/piotr/.gradle/daemon/5.4.1
```
**Instance 3**:
```
cwd
/Users/piotr/Dev/Prominic.NET/Tests/NewGrailsProject
```
4. Close project left me with 2 deamon instances mentioned above

I think we should close this issue and eventually open new one to discuss what we can or should do here.

**Comment by JoelProminic** [comment]
I think the  Gradle 3.5 daemon may be related to #593.  The current version of Grails that we use has a dependency on Gradle 3.5.

I mentioned that I thought this was because of an issue with the language server, but I was thinking of the wrong issue:  #552.  This issue would create a Gradle 5.0 instance instead, but I didn't see this trigger for the Grails project.

Otherwise, this issue seems fine.  I will close it for the release.
