### ISSUE TITLE
Cannot create Grails class outside src folder

### ISSUE THREAD

**Issue by Aszusz** [prominic/Moonshine-IDE#831]
When I try to manually create a class inside grails/domain I get an error telling me I cannot do that outside src folder.
I remembering mentioning it on a call to @JoelProminic but I don't remember if there's a workaround.

![cannot-create-grails-class](https://user-images.githubusercontent.com/7197014/119268393-04fbf400-bbf3-11eb-9f23-c42a3773c4ea.png)

**Comment by rat-moonshine** [comment]
This is somewhat related to #826 . I have my comment there on current functional availability.

**Comment by JoelProminic** [comment]
I thought we had checked this behavior with #805, but it may have been overlooked.

For domain classes, at least, you'll probably want to use Project > Run Grails Command to run create-domain instead:
![image](https://user-images.githubusercontent.com/24532731/119368953-39b28e80-bc79-11eb-9536-a296c29b4e6a.png)

We'll want to be able to manually create Java and Groovy classes in src/java (not created by default) and src/groovy, respectively, though.

**Comment by piotrzarzycki21** [comment]
Guys it's working. Adrian didn't have path added in project Settings. He will probably close this issue soon.

**Comment by JoelProminic** [comment]
Hmm, grails-app/domain should have been added to the  classpath automatically:
![image](https://user-images.githubusercontent.com/24532731/119376936-2526c400-bc82-11eb-834d-bf38ce1e01ee.png)

Was this an old project, or a project created externally?

**Comment by Aszusz** [comment]
I'm closing this issue because the functionality works if "grails-app/domain" is added to the Paths.
In my case this was an external project. I'll open appropriate issue if I find a scenario where I can consistently reproduce this path missing from settings.
