### ISSUE TITLE
PermissionError on Browse File

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#839]
I noticed this error today with the 3.1.0 production build on macOS:
1. Create/Open a Flex Desktop project
1. Right click and choose Settings, then open the Path tab
1. Under Libraries, click "Click to add"
1. Click "Browse file" for the new entry.  BUG:  The below error shows up on the console:
1. Click "Browse dir".  The file chooser opens with no error

    : Error #3800
    : PermissionError: 'Error #3800'
    : 	at actionScripts.impls::IFileBridgeImp/browseForOpen()
    : 	at actionScripts.plugin.actionscript.as3project.settings::PathListSettingRenderer/browseFile()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at actionScripts.plugin.actionscript.as3project.settings::PathRenderer/___PathRenderer_Button1_click()
    :
    : Click here to Report a Bug

@rat-moonshine reported that he saw a similar error on another project, and found that it was related to an [AIR bug](https://github.com/airsdk/Adobe-Runtime-Support/issues/653).  This error was cleared in the most recent version of Harman AIR

I'm concerned about whether this bug could affect other parts of the interface.

**Comment by rat-moonshine** [comment]
Based on the discussion here https://github.com/prominic/Moonshine-IDE/issues/860#issuecomment-861369456 I have updated the Harman Flex/AIR SDK on Bamboo build systems.

**Comment by rat-moonshine** [comment]
With the updates of Harman AIR SDK at Bamboo build system and continue using the Flex File API in non-sandbox build, this issue is now fixed. Please, check.

**Comment by JoelProminic** [comment]
The original problem is resolved, and I can select the SVN path for #849 as well (there are still other problems with this, but they are not relevant to this issue).
