### ISSUE TITLE
Option "New" -> "Visual Editor Flex File" should be disabled for other type of projects than Visual Editor

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#84]
In context menu in project tree option "New" -> "Visual Editor Flex File" should be disabled for other type of projects than Visual Editor.

I think this issue could be introduced by changes in #62. I did reset master to the committs before changes and it was working.

**Comment by rat-moonshine** [comment]
Context menus' enable/disable state against VE projects, now fixed. 

While working on the above fix, I noticed following problem in case of VE project in `File/New` menu:

![untitled-1](https://user-images.githubusercontent.com/24370870/33417088-f7c6ffb2-d5c5-11e7-85e2-1bd3b2732f77.jpg)

I noticed `MenuUtils.menuItemsDisabledInVEProject` has a static Array which were using to enable menus in case of VE projects in `File/New` (perhaps @piotrzarzycki21 you want to consider renaming this array as it's using to enable menus but disable).

This menu generation is now dynamic at the time of template parsing, this also includes custom templates. Custom template addition/removal/renaming also updates the collection now.

#83 changes also affected `File/New` enable/disable states between VE and non-VE projects, it's fixed now.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have changed mentioned property to menuItemsEnabledInVEProject. I hate that solution but couldn't come up with better one in current architecture of Menu. I was thinking even about rewrite completely Menu where we will have XML for configuration what is inside and what is not, but that would take too much time.
