### ISSUE TITLE
Moonshine Using Flex File API Instead of Bookmarking ANE During browseForOpen() in macOS Installation

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#860]
Some method(s) while file-browsing in macOS-installation is wrongly using Flex File API instead of the native Bookmarking API which needs to be resolved. 

@JoelProminic has noticed one such problem and reported as #839 . I have created this issue to resolve any similar usage-problem in Moonshine, #839 should be closed when this issue resolved.

**Comment by rat-moonshine** [comment]
While setting the file-browsing to use Bookmarking API only on macOS, it fixed the error with #839 , but I see on El Capitan (and probably on any newer OS version) the ANE failed to open the browsing-dialog by the path it was given. 

Opening the Bookmarking project on Xcode thrown me a lot of errors, including 32/64-bit dependency error on which the project was once setup. This project is very old, I see different architecture errors on opening the project now. The documentations are old and hardly new help is available on this nowadays. 

For now, I returned to use the Flex File API only on non-sandbox build and updated the Harman AIR SDK which is suppose to fix the error #839 .  The sandbox (App Store) build continue to use the ANE for file-browsing but I fear it'll display same open-to-path problem in newer version of OS. Since a very limited help availability on ANE preparation process and we probably moves to Haxe in future, it's probably Okay to keep using the ANE with its earlier build, unless we want to spend more time on fixing this.

I have updated the Harman SDK on Bamboo build systems.

**Comment by rat-moonshine** [comment]
While updating the Harman SDK at macOS Bamboo build system, I receive following error during MockupVisualEditor's documentation generation phase:

```
uild        15-Jun-2021 04:49:36        documentationPrimeFaces:
build        15-Jun-2021 04:49:36             [echo] Creating documentation for Visual Editor PrimeFaces components
build        15-Jun-2021 04:49:37            [asdoc] Loading configuration file /Users/mmb/SDKs/Flex_4.16.1_AIR_33.1/frameworks/flex-config.xml
build        15-Jun-2021 04:49:37            [asdoc] Apache Flex ASDoc
build        15-Jun-2021 04:49:37            [asdoc] Version 4.16.1 build 20171115
build        15-Jun-2021 04:49:37            [asdoc] Copyright 2017 The Apache Software Foundation.
build        15-Jun-2021 04:49:37            [asdoc]
build        15-Jun-2021 04:49:37            [asdoc] /Users/mmb/SDKs/Flex_4.16.1_AIR_33.1/frameworks/flex-config.xml(85): Error: unable to open '{playerglobalHome}/27.0'
build        15-Jun-2021 04:49:37            [asdoc]
build        15-Jun-2021 04:49:37            [asdoc]       </library-path>
build        15-Jun-2021 04:49:37            [asdoc]
error        15-Jun-2021 04:49:37        
error        15-Jun-2021 04:49:37        BUILD FAILED
error        15-Jun-2021 04:49:37        /Users/mmb/bamboo-agent-home/xml-data/build-dir/MS-MGOSX-JOB1/MockupVisualEditor/build.xml:78: asdoc task failed
error        15-Jun-2021 04:49:37
```
I don't see any error on Windows Bamboo though post the update. 

I don't see any problem compiling Moonshine using its build-script locally, with Harman SDK either, however I don't build MockupVisualEditor locally during this test process.

**Comment by rat-moonshine** [comment]
I able to fix the compilation problem using Harman SDK on macOS Bamboo build-system. I'll create a separate issue with the requisite in Moonshine SDK Installer repository.

**Comment by JoelProminic** [comment]
The `unable to open... </library-path>` looks very familiar to me.   The first example I found of this was #483, but think we have had similar errors elsewhere.

**Comment by rat-moonshine** [comment]
With the latest Harman AIR SDK installed at Bamboo build system, this issue is currently completed, I'm closing this issue.
