### ISSUE TITLE
Tabs remains opened when project is being closed

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#88]
Scenario:
1) Open some project
2) Open file from project
3) Right click on the project and close it

Tabs remains opened.

Initially I thought that is problem introduced by my changes in #79 , but it also doesn't work on master. It's quite serious for me, so we should put energy to fix that.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine We are forcing to close all tabs, without asking if one of the tab has been actually edited. I think we should ask about that. Basically CloseEvent which is being sent from UtilsCore.closeAllRelativeEditors shouldn't have flag forceToClose = true. What do you think ?

**Comment by rat-moonshine** [comment]
Thank you for pointing to this @piotrzarzycki21 . I think I can do something about this. Reopening the issue for the time being.

**Comment by rat-moonshine** [comment]
@JoelProminic  also pointed that the Settings window belongs to a particular project remain open when the project closed/deleted from the workspace. This requires to fix as well.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine if you are going to fix both issue, especially the second one for 1.7.0 we should probably merge before that #79 - I think you may touch the code around Tabs with settings issue and there was a lot of changes in that area. If your plan is 1.7.0 let me know I will merge things first ASAP. I hope you will see that message before comit.

**Comment by rat-moonshine** [comment]
We should fix both the said issues for 1.7.0 only.

**Comment by piotrzarzycki21** [comment]
Ok. Let me merge #79 to master. I will do this in about 1,5h from now on. If you commit anything I will try to handle conflicts.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine #79 has been merged to master.

**Comment by rat-moonshine** [comment]
- Unsaved Settings (belong to the project) and editors now alerts for save during project close 
- Above case is true for template project, too

**Comment by JoelProminic** [comment]
I tested with:
- Open project settings tab
- Open files
- Open files that showed up in the new tab menu
- Deleting projects
- Template projects (open files only)

This seems to be working properly.
