### ISSUE TITLE
Embedded AwayBuilder in Moonshine

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#89]
I talked with Justin about #11 (Away Builder Integration), and this is not quite what he wanted. 

Instead of calling AwayBuilder as a remote application, he would like to have AwayBuilder embedded in Moonshine for editing AWD files.

Let me know if there are licensing or other problems that would prevent us from implementing it like this.

This does not need to hold up the 1.7.0 release - this can be a future improvement.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I did quick look and I'm not sure whether I dig into the right source code, but Away3D seems to be under Apache License. -> [here](https://github.com/away3d/away3d-core-fp11). We should be safe here, but maybe we should add to our project additional file NOTICE.md where we mention all libraries which we are using, along with license. - Example in [Royale-compiler](https://github.com/apache/royale-compiler/blob/develop/NOTICE)

**Comment by rat-moonshine** [comment]
Okay. We shall look into the embedding then.

**Comment by rat-moonshine** [comment]
When I looked into the Away3D's main repository (https://github.com/away3d), I couldn't found any reference project to the GUI application, though. I believe mostly are either the core engine source or example sources. 

I also checked that they distributes the engine _.swc_ from there website as well - http://www.away3d.com/download/. But I believe this includes core engine classes only.

I moved forward downloading https://github.com/away3d/integration-examples-fp11 - thanks to Moonshine it helped me setup an ActionScript project very fast - I able to test its one of the application file (there are other application files which demonstrates the same thing in different way with Starling or normal Flex SDK), but this only shown an approach to initiate/render a certain example but no application GUI.

I'm wondering, are they really open sourced their application GUI at all (?)

**Comment by rat-moonshine** [comment]
Update:
- Project source downloaded, installation finalized and it's running good
- New library project created to use in Moonshine, removed initial compiler errors, waiting for next process

**Comment by rat-moonshine** [comment]
So far, after an amount of wrestle I able to run the Away Builder application as a library project, to a demo desktop application. (We already have a running Away Builder setup running as standalone application project and that works good)

The library project conversion still had some menu issues (while running inside another application project), but that is fine, we can look into that latter.

The problem running Away Builder application as a library project (into another application) is - it starts good, it renders all its panel, property editor etc. good, but the actual 3D modelling editor just not rendering. 

After several hours of fighting with these, I found a few things:
1. The 3D modeller and its stage somehow is not running when ran inside a library project
2. I have tested the 3D editor rendering to an _UIComponent_ (this is the base to the 3D editor) that exist directly to the main application project, and that render good; But when the same 3D editor uses an _UIComponent_ that resides inside the library project (Away Builder) it does not renders
3. I tried some crazy stuff as well.. I have created an _UIComponent_ to the main application stage and passed its reference to the Away Builder lib's 3D modeller API (just to check if we can live with a peculiar rendering way having the _UIComponent_ in main application stage), but that didn't worked either

So far, its still failing, and I'm searching through.

**Comment by rat-moonshine** [comment]
After quite a hurdle, and an amount of hours, I able to make Away Builder running properly as a library project to my demo desktop application. 

The builder is now renders all its 3D stage well, imports/open sample Away3D file and do other requisite things. 

I have committed the current library source to Git (https://github.com/prominic/Moonshine-IDE/tree/master/library/AwayBuilderLib), we can further work from here.

**Comment by rat-moonshine** [comment]
Yes, indeed it's big size as its a complete (separate) application. I don't have any plan to integrate any Moonshine level of changes towards this, in upcoming release (if we want to plan a release soon). I shall plan for a separate branch if I'll start the integration sooner.

**Comment by rat-moonshine** [comment]
We probably want to exclude the Away Builder lib source from upcoming build/source release as well. I shall plan to have this source creating a new branch, and exclude from current 'master'.

**Comment by piotrzarzycki21** [comment]
Just one question. Are we planning to change sources of Away Builder ? Why they are landed as part of our repository ?

**Comment by rat-moonshine** [comment]
The source shall have changes to use in Moonshine. I'm not fond to use the application through SWFLoader as unloading has bugs. Therefore, to use the source we shall have changes -

- Having the gateway codes in a separate base class (non-WindowedApplication)
- Eliminate native menu usage to simpler Flex menu so this can fit within Moonshine environment
- Possible File API handling changes to work within sandbox macOS

I've ported the main project source to a library project, and have the additional changes there. Since these needs, like Apache SDK Installer lib, I also made it a part of 'library' section having changes related to Moonshine. If anybody needs to use the Away Builder application source only, s/he can download it from the Awaytools' respective website.

**Comment by piotrzarzycki21** [comment]
As I write in the email in my opinion these sources should not be part of the Moonshine project. 
1) They should be FORK-ed as part of Prominic GitHub as it was done with Visual Editor
2) You should made changes there and provide swc to Moonshine

I can give you really interesting comparison. What you will do if some day you will have to Modify Apache Flex SDK - You won't be allowed to commit those changes to the official repository on GitHub. 

Those custom SDK will be used in Moonshine project - Will you add in that case sources to the Moonshine project ?

**Comment by rat-moonshine** [comment]
I can put the source off-Moonshine repository or forked, and do my changes there. Keeping the modified sources inside Moonshine repository's separate folder was only reason - to keep the modified library available as part of Moonshine source only, since they are directly related to Moonshine usage ways.

The changes I made so far to Apache SDK Installer library, I never had plan to commit them to Apache Git, as those changes are mainly Moonshine related. However, if I could used the source for bug fixing or feature implementation purpose, forked way would have been best.

> Those custom SDK will be used in Moonshine project - Will you add in that case sources to the Moonshine project ?

I'm unclear on above comment.

**Comment by piotrzarzycki21** [comment]
> Those custom SDK will be used in Moonshine project - Will you add in that case sources to the Moonshine project ?

Above comment is just comparison to your situation. Since you are working on stuff which is related to Moonshine inside AwayBuilder it should be FORK-ed as part of Prominic account. If it will be your private idea you should forked it on your own. I believe it doesn't matter whether you are going later make pull request to the official repository of AwayBuilder.

If I would be part of the project when you have started changing installer, my suggestion would be the same. FORK official repository, make the changes, include SWC. 

As you can see I'm working on FORK of Visual Editor several months already.

**Comment by rat-moonshine** [comment]
We can do this Fork'ed as well, anyway EOD we need this running within Moonshine along with our requirements. I shall plan for a fork, Piotr.

**Comment by rat-moonshine** [comment]
Away Builder now set as a non-close-able (until we found a way to re-initiate all its 3D stage during a reload) tab, like Home. User can able to do all the available functionalities to this tab, i.e. load, reload, save etc.

**Comment by rat-moonshine** [comment]
@JoelProminic pointed two problems while his testing:
- After opening an .awd from sidebar project, 'Save As' offering location different than the project opened from
- While in Away Builder initializing time, if another .awd file double-clicked from the sidebar it returns injector error

**Comment by rat-moonshine** [comment]
Update:
- After opening an .awd from sidebar project, 'Save As' offering location different than the project opened from - Fixed

**Comment by rat-moonshine** [comment]
Updates:
- After opening an .awd from sidebar project, 'Save As' offering location different than the project opened from - Fixed
- Open File dialog cause current file change (if any) dialog. Doing save or cancel save in the dialog was not starting 2nd process, i.e. opening file dialog - fixed

**Comment by JoelProminic** [comment]
I saw this behavior for the file chooser.  This looks good:
1. Open a .awd file
2. File > Save As - the file chooser defaults to the same directory as the .awd file
3. Save the file to a different directory in the same project
4. Refresh the project to confirm the file is present
5. Open the original .awd file again
6. File > Save As - the file chooser defaults to the same directory as the original .awd file
7. Open the new .awd file
8. File > Save As - the file chooser defaults to the same directory as the new .awd file


I confirmed that if the current .awd file has unsaved changes, any of these actions triggers a prompt to confirm whether you want to save your changes:
- File > Open
- File > New
- File > Import
- "New" icon
- "Open" icon
- "Import" icon
- Double-click to open another file

I had some strange behavior with the double-click:
1. Open a .awd file
2. Make a change but don't save
3. Double-click another file.   Moonshine shows a prompt for your unsaved changes
4. Click Cancel
5. Double-click the same file again.  BUG:  There is no prompt, and the file does not open
6. Save the file
7. Moonshine opens the other file

**Comment by rat-moonshine** [comment]
Since the main integration part has done now, I'm closing this issue. I have created a separate issue to investigate on restarting Away Builder as a tab after being closed (inside Moonshine) - #227 .
