### ISSUE TITLE
Moonshine editor slowness

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#9]
**Environment:** Windows 7
**Found in version:** Any (Moonshine)

**Issue:** Editor demonstrates masking issue when a file opened having long texts (preferably with a vertical scroll). Also, typing in the editor may not be that fast as we use to see in other Windows native text editors; the slowness maybe of milliseconds but having comfort to type in a fast editor sometime matters.

**Description:** Open the Moonshine in maximized state. Keep opening files to the editor having long texts; sometime or most of the time the editor demonstrates text masking issue. I've created a screen recording on this in Windows 7, for reference: https://vimeo.com/233276215.

**Workaround:** Not sure. For editor slowness, we perhaps want to see if we change the text softness to use 'none'. [Ref: https://ibb.co/nmMpya]

**Notes:** Editor codes can be found at: `MoonshineSharedCore/src/actionScripts/ui/editor/BasicTextEditor.as`. TextEditor (`MoonshineSharedCore/src/actionScripts/ui/editor/text/TextEditor.as`) does has a masking stuff - this place also needs to be investigated from line# 785-790.

**Comment by rat-moonshine** [comment]
I've removed the strange masking codes completely from the `TextEditor` class. With my initial tests I didn't noticed any masking problem anymore or any other (I vaguely remember in past this wasn't the case, though). The removal of the masking codes seems also contribute to this (#9) masking report and I not able to reproduce this again with my tests in Windows. 

We shall need to keep an eye if any other masking issue to the editor we notice, in coming days.

**Comment by rat-moonshine** [comment]
I'm closing this issue for now. Please report if you found any problem with editor masking.

**Comment by rat-moonshine** [comment]
I noticed that the issue reported was for editor slowness as well. I'm changing the title and re-open it for later investigation.

**Comment by piotrzarzycki21** [comment]
I believe I have done enough improvements for now in that area. @JoelProminic , @rat-moonshine keep an eye on code completion and text editor whether there isn't any weird behavior after my changes. I have touched some sensitive places. 

Let me know if you will see any slowness.
