### ISSUE TITLE
the code can't not auto-completion

### ISSUE THREAD

**Issue by gachal** [prominic/Moonshine-IDE#90]
the code can't not auto-completion

**Comment by rat-moonshine** [comment]
Hi @gachal ,

Can you provide some more information, like, on what platform (Windows, Mac) you've tried, did you setup SDK through Moonshine/Settings, have Java detected/configured inside Moonshine/Settings/Default-SDK section, your SDK location, etc.?

Thanks!

**Comment by rat-moonshine** [comment]
Since inactiveness the issue is closing now; we can revisit this if more data will available.
