### ISSUE TITLE
Ability to select project's default application file

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#91]
Its possible that a project consists of different _application_ files at a time, and user wants to toggle between those files as the project's default _application_ file. 

Moonshine needs ability to choose between those available files and select any one of them as the project's default application file. Therefore, the application needs to start with the default selected class file.

**Comment by rat-moonshine** [comment]
User now can choose any arbitrary ActionScript file to select as the default application file to a project:
![untitled-1](https://user-images.githubusercontent.com/24370870/33875715-25bff680-df49-11e7-8b60-3e16eb687b64.jpg)

Following rules applies to having the context menu:
- Visual Editor project files won't have this option
- Any arbitrary _.as_ and _.mxml_ files are entitled for this option
- Files those resides in the project's source folder only applicable for this option
- File that already set as the default application, won't get this option

Further thing to note is, Moonshine do not apply any intelligence of the validity of the selected file (as application). At this stage, it expects user knows what s/he is doing by selecting the option against any arbitrary file. If a selected file is not an application type of, or not made to run as an application file, user will be notified at the project compilation time, through compiler notifications.

**Comment by JoelProminic** [comment]
I ran some tests with this.  These cases worked as described above
- MXML files
- AS files
- files in subdirectories
- Alternate file types (.txt and .xml)
- files in other directories

If I add another directory under Class paths, should I be able to set the default application file to be in the new directory?
1. Open/Create a project
2. Create a directory called src2
3. Create an MXML file in src2
4. Right-click on the src2 MXML file - the "Set as Default Application" option is not present
5. Open the project settings
6. Go to the Paths tab
7. Add src2 to the Class paths section and save
8. Right-click on the src2 MXML file - the "Set as Default Application" option is still not present
