### ISSUE TITLE
Layout Issue for "Define a SDK Path" Prompt

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#92]
While testing with the Apache Royale SDK, I noticed this problem:
1. Launch Moonshine
2. Open the Settings page
3. Go to the Default SDK tab
4. Click "Change" for the Default Apache Flex or FlexJS SDK prompt
5. Click the "+" button.
6. The field are overlapping:  

![2017_12_05__add_sdk](https://user-images.githubusercontent.com/24532731/33634775-0a670702-d9db-11e7-8e10-8e704eb46329.jpg)

I noticed the same problem with this interface in:
- The project settings
- New project form

**Comment by piotrzarzycki21** [comment]
@JoelProminic what build did you use ? It was from bamboo or local build from master ?

**Comment by JoelProminic** [comment]
I used a build from Bamboo (I still need to make that available for you ...).
I tested on Mac OS X.

**Comment by piotrzarzycki21** [comment]
I had an assumption earlier that this layout issue is only when I'm making an development build locally. Strangely loose some styles, but it looks like it is not necessary true.

**Comment by rat-moonshine** [comment]
Since the introduction of new skin class for popup windows, it was requirement to add the class reference to the popup windows. I noticed some popup may overlooked into the process. I have added the reference now in css file, this should affect all the now/future popup as well.

**Comment by JoelProminic** [comment]
The layout is fixed.  

The coloring on the fields and browse button seems a little strange to me, but this does not need to hold up the release.

![2017_12_06__add_sdk_prompt](https://user-images.githubusercontent.com/24532731/33672942-22c0dc4c-da71-11e7-9f90-67824dbe4c1b.jpg)
