### ISSUE TITLE
Custom SDKs Cleared After Restarting Moonshine

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#93]
1. Launch Moonshine
2. Open the Settings page
3. Go to the Default SDK tab
4. Click "Change" for the Default Apache Flex or FlexJS SDK prompt
5. Click the "+" button.
6. Select an SDK (ignore layout issues reported in #92)
7. Save the changes
8. Restart Moonshine
9. Open the SDK list using the above steps.   BUG:  The SDK has been removed

I tested this on macOS with an Apache Royale SDK.

**Comment by piotrzarzycki21** [comment]
I just tested it with development build on Windows and don't have that issue.

**Comment by piotrzarzycki21** [comment]
Although I had two users on the Royale mailing lists who experienced something like that. I recommend them to do reset hard and it helped. They have fresh install of Moonshine, completely new users.

**Comment by piotrzarzycki21** [comment]
I'm able to reproduce that problem on Mac OS Sierra.

**Comment by rat-moonshine** [comment]
I shall check this.

**Comment by rat-moonshine** [comment]
I confirm the problem. This probably in the area where SDK list prepares with bundled/present SDKs, this is valid only for Mac, so this problem can be seen only in Mac.

**Comment by JoelProminic** [comment]
I confirmed that this is resolved.
