### ISSUE TITLE
Simple instance vars have blue wavy underline

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#94]
In all my projects, simple public and private vars in all mxml and as files have a blue wavy underline and appear in the problems pane with the line shown in the Location column and a blank entry under Problem column. Example:

![vars with blue wavy underline](https://user-images.githubusercontent.com/32083838/33641325-01687a38-da70-11e7-88c3-94ab294039c5.PNG)

Also the Location column numbers the lines starting at line 0. Thus if there is an error at line 5 in the main panel, it shows as line 4 in the Location column of the Problems pane.

Doug

**Comment by doug777** [comment]
Forgot to mention this happens only since v1.6.1. I am using Win10 64 bit.

**Comment by piotrzarzycki21** [comment]
Hi @doug777 ,

I don't  have problem with blue lines in our under development version. It is possible that in version 1.7.0 it is resolved.

**Comment by doug777** [comment]
OK I guess this could be caused by or related to the modification of flex-config for the nightly builds.

Anyway I'm really looking forward to v1.7 and don't want to delay that!

Doug

**Comment by piotrzarzycki21** [comment]
IMO, I'm wondering what are you seeing in Problems view for that lines. Can you check and post here some screenshot ?

Thanks!

**Comment by doug777** [comment]
This is what it looks like.

![vars blue underline and problems pane](https://user-images.githubusercontent.com/32083838/33649357-8f40d2b0-da98-11e7-9046-f66898e779c9.PNG)

Doug

**Comment by joshtynjala** [comment]
These are probably the "hints" for generating getters and setters from member variables (which is not yet exposed in Moonshine, but it's used by VSCode). They're returned as problems, but are meant to be hidden from the user. I'll take a look.

**Comment by piotrzarzycki21** [comment]
@joshtynjala does that mean that in theory we have marked those variables and can implement mechanism to generate getter and setter ? VSCode have that mechanism as part of the IDE ? You are just using it ?

**Comment by joshtynjala** [comment]
@piotrzarzycki21 VSCode has a feature called *code actions*. Other IDEs have something similar called *quick fixes*. Basically, it provides commands in context based on the current location of the cursor or the current selection. The generate getter/setter feature is implemented as a code action.

**Comment by piotrzarzycki21** [comment]
Thanks @joshtynjala ! I will get back to the discussion if I start to implement something like that in Moonshine.

**Comment by doug777** [comment]
Confirm that the blue underline fault does not occur in v1.7.0.

But there is still the line number mismatch between the main pane where line numbers start at 1 and the Problems pane Location column where line numbering starts at 0.

In my opinion line number 0 in the Problems pane should refer to a problem where the line number cannot be determined and both 0 and 1 (i.e. undetermined and a real problem in line 1) should cause an underline on the first character of line 1 in the main pane. The tool tip as it is now shows what the problem is so it is easier to follow like this than the way it is now with mismatched line numbers.

And 1.7.0 looks great. Congratulations to everyone.

Doug
