### ISSUE TITLE
"Problems view" should allow copy to clipboard "Problem" and "Location" values of cells 

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#95]
It will be very useful if "Problems view" allow copy to clipboard "Problem" and "Location" values of cells. We can resolve this by some small button in the each cell which can appear after rollover or row selection.

![image](https://user-images.githubusercontent.com/24554795/33657126-92f6dff0-da78-11e7-98cd-6bf9c2743eda.png)

**Comment by piotrzarzycki21** [comment]
Each row in the problems view from now on have icon which allows you copy the content. Icon appear on roll over. 

![image](https://user-images.githubusercontent.com/24554795/34155839-30609c3a-e4bb-11e7-8e7f-e8b513db92a3.png)

**Comment by JoelProminic** [comment]
I confirmed this behavior for 1.8.0.
