### ISSUE TITLE
[UI Builder] Base Window for Visual Editor

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#98]
When I create a new Visual Editor project, I see this as the initial editor window:
![2017_12_06__defaultvisualeditor](https://user-images.githubusercontent.com/24532731/33677464-79f31108-da7e-11e7-9d18-10a12a44b685.jpg)

Since the background is grey and there is no base window, this makes me think that I need to define my own base window:
![2017_12_06__custombasewindow](https://user-images.githubusercontent.com/24532731/33677472-82c9a328-da7e-11e7-9a5c-41ebee947da2.jpg)

However, this window is displayed within the generated application.
![2017_12_06__custombasewindow_result](https://user-images.githubusercontent.com/24532731/33677483-8af8a968-da7e-11e7-8843-581cc2c1f091.jpg)

If I add the label directly to the default screen, this gives the results I expected with the above mockup.

The current behavior feels unintuitive to me.   My suggestion would be to provide a default, undeletable window within the mockup so that it is clear where the user should start populating elements.  This will also allow:
- Controlling the default size of the application window
- Changing the title displayed in the application window
- Make it clear how the items are positioned against the application borders.

**Comment by piotrzarzycki21** [comment]
Here is my plan for that enhancement:
- Current component "Window" it is in fact "Panel" control - I will change the default displayed name
- I will try to add to the editing panel on the right sight basic properties for the main application file:
width, height and window title.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I think I have finished implementation here. Take a look and let me know whether this is what you were looking for. 
Main application file has currently non deletable window which represents main application where we can change basic properties.

**Comment by JoelProminic** [comment]
The base window defaults to 725x450, which is too wide for the default Moonshine resolution.  it seems liek a reasonable application window size, though, so I don't feel too strongly about making it smaller by default.

The base window title defaulted to "Main Window", but I think we would want it to be the project name.

Otherwise, this looks good to me:
- I confirmed that I can change the window title and size from the visual editor.
- I was not able to delete the base window in my tests, which is good.
- The base window makes the positioning of the other components more intuitive for me

**Comment by piotrzarzycki21** [comment]
@rat-moonshine We have in or code logic which injecting some value of variables into `$Settings.veditorproj.template `. I would like to do the same for `$ProjectName.mxml.template` - I need there name of the project as an title - In case of Visual Editor type of project. Is there any way to do this ? Any tips would be valuable, because I cannot find proper place.

**Comment by rat-moonshine** [comment]
I'm not sure if this is what you're looking for - but in general, having any specific keyword in template files, i.e. `$ProjectName` (https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/elements/templates/projects/Actionscript%20Project%20(SWF%2C%20Desktop)/src/%24ProjectName.as.template#L8) or any such, all replaced at the time of project file generation at here: https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/CreateProject.as#L523. So if you want any file's `title` to be name of the project, the perhaps you can add `$ProjectName` word in the file's `title`.

**Comment by piotrzarzycki21** [comment]
Thanks @rat-moonshine  that was helpful. I just make project name as title of the window. I made also a window itself a bit shorter.

**Comment by JoelProminic** [comment]
I confirmed that the window name matched the new project name.

The window is still too wide for the default window size (if we care), but the updated default proportions look good to me.

**Comment by piotrzarzycki21** [comment]
I change default size only a bit from width=725 to width=700 - User have possibility to change it, so let's leave it as is.
